### ISSUE TITLE
Linebreaks in chain.pem (and fullchain.pem) differ from previous versions

### ISSUE THREAD

**Issue by keigel2001** [certbot/certbot#5721] opened 2018-03-14 01:16 UTC
## My operating system is (include version):
Debian Stretch 9.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto (0.22.0)

## I ran this command and it produced this output:
`./certbot-auto certonly --rsa-key-size 4096 --manual --preferred-challenges=dns-01 --manual-auth-hook /opt/eff.org/certbot/certbot_dns_authenticate.sh --manual-cleanup-hook /opt/eff.org/certbot/certbot_dns_cleanup.sh -d 'mydomain.tld','*.mydomain.tld' --server https://acme-v02.api.letsencrypt.org/directory`

## Certbot's behavior differed from what I expected because:
Yesterday I obtained a new wildcard certificate with the help of certbot. Everything went fine and it's working with NGINX and Dovecot like expected. But when I tried my script which is chaining it into a special form for my ZNC, I couldn't connect.
After debugging I noticed that the linebreaks differ from the certs I was obtaining in the past.
Namely chain.pem (and because of this also fullchain.pem) are different. The rest is like excepted.

previous chain.pem:
```
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
```

new chain.pem:
```
LF
-----BEGIN CERTIFICATE-----CRLF
xxxCRLF
yyyCRLF
-----END CERTIFICATE-----
```

Especially the missing linebreak at the end is breaking my application and I don't think it's like this on purpose. Resulting of this change the fullchain.pem is also different now.

**Comment by cpu** [comment] 2018-03-14 13:35
The CRLF's in the X3 intermediate certificate returned in the chain are a bug on the Let's Encrypt side. Please follow https://github.com/letsencrypt/boulder/issues/3557 for resolution.

**Comment by bmw** [comment] 2018-03-14 15:03
I'm struggling to reproduce the missing newline at the end of `chain.pem` or `fullchain.pem`:
```
$ sudo tail -c 1 /etc/letsencrypt/live/example.com/chain.pem | xxd 
00000000: 0a                                       .   
$ sudo tail -c 1 /etc/letsencrypt/live/example.com/fullchain.pem | xxd 
00000000: 0a
```
`0a` is a newline character. Are you still seeing this problem?

I've reproduced the new blank line at the top of `chain.pem` and between the certificates in `fullchain.pem` when used with Let's Encrypt's ACMEv2 endpoint though. The reason for the difference here is with ACMEv1, Certbot obtained each certificate in `fullchain.pem` separately and combined them together, but in ACMEv2, the ACME server provides `fullchain.pem` and Certbot splits it up to create `cert.pem` and `chain.pem`.

We definitely should remove the blank line from the top of `chain.pem`. We probably should also strip any blank lines found in `fullchain.pem` for consistency.

**Comment by keigel2001** [comment] 2018-03-14 18:37
So indeed the results are strange. From my live-cert obtained on ~13 Mar 19:30 CET 2018:

```
tail -c 1 /etc/letsencrypt/live/mydomain.tld/chain.pem | xxd
00000000: 2d                                       -
tail -c 1 /etc/letsencrypt/live/mydomain.tld/fullchain.pem | xxd
00000000: 2d                                       -
```

The syntax of my live-cert fullchain.pem is the following:
```
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
LF
-----BEGIN CERTIFICATE-----CRLF
xxxCRLF
yyyCRLF
-----END CERTIFICATE-----
```

Today I obtained a staging-cert with `./certbot-auto certonly --rsa-key-size 4096 --manual --preferred-challenges=dns-01 --manual-auth-hook /opt/eff.org/certbot/certbot_dns_authenticate.sh --manual-cleanup-hook /opt/eff.org/certbot/certbot_dns_cleanup.sh -d 'mydomain.tld','*.mydomain.tld' --server https://acme-staging-v02.api.letsencrypt.org/directory`

Now the line breaks are different:
```
tail -c 1 /etc/letsencrypt/live/mydomain.tld/fullchain.pem | xxd
00000000: 0a                                       .
tail -c 1 /etc/letsencrypt/live/mydomain.tld/chain.pem | xxd
00000000: 0a                                       .
```

Staging chain.pem:
```
LF
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
```
Leading LF, but no CRLF anymore and a LF at the end. Very strange...


Staging fullchain.pem:
```
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
LF
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
```

**Comment by bmw** [comment] 2018-03-14 19:14
I reproduced this. The certificate chain returned from LE's ACMEv2 prod server doesn't end in a newline.

**Comment by cpu** [comment] 2018-03-14 19:25
> I reproduced this. The certificate chain returned from LE's ACMEv2 prod server doesn't end in a newline.

Thanks! Filed https://github.com/letsencrypt/boulder/issues/3560 for this. That's something Boulder should just fix itself.

**Comment by cpu** [comment] 2018-03-14 21:32
The Windows newlines problem & the missing trailing `\n` are both fixed in production. We'll land Boulder features to prevent these from sneaking in again. Thanks folks!

**Comment by bmw** [comment] 2018-03-15 18:18
I believe all of the issues here have been fixed. On the Certbot side, we've fixed the blank line at the beginning of `chain.pem` and in between certificates in `fullchain.pem` in #5730. We plan on releasing the code containing this fix early next week.

I'm closing this issue, but if I missed anything, please yell at me and I'll reopen.

**Closed by bmw** 2018-03-15 18:18 UTC
Labels: bug, more-info

**Comment by coolaj86** [comment] 2018-07-04 04:54
For my benefit and for future reference, what is the "canonical" line ending format that certificate parsers should expect?

After scanning the issue it looks like this is what's most desirable?

```
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
LF
-----BEGIN CERTIFICATE-----LF
xxxLF
yyyLF
-----END CERTIFICATE-----LF
```

Is there an RFC spec for this or this just a convention?
