### ISSUE TITLE
Certbot uses old version of Python

### ISSUE THREAD

**Issue by DirkWolthuis** [certbot/certbot#4066] opened 2017-01-17 09:27 UTC
Hi all, Certbot on Ubuntu 14.04 uses a old version of Pip (8.0.3) even if the newest version of Pip (9.0.1) is available. I can not run the ```$certbot-auto``` renew command with succes, because it gives the ```InsecurePlatformWarning``` warning. Can I fix this? Underneath I pasted all the output: 

```
Command "/home/wolthuis/.local/share/letsencrypt/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Txn1F9/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('
', '
'), __file__, 'exec'))" install --record /tmp/pip-igOc6P-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/wolthuis/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-Txn1F9/cryptography
/home/wolthuis/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 8.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
=====================================================

Certbot has problem setting up the virtual environment.

Based on your pip output, the problem can likely be fixed by 
increasing the available memory.

Consult https://certbot.eff.org/docs/install.html#problems-with-python-virtual-environment
for possible solutions.
You may also find some support resources at https://certbot.eff.org/support/ .

```

**Comment by bmw** [comment] 2017-01-17 17:16
This looks like a duplicate of #2804 (or #1081). In short, freeing up more memory by (temporarily) stopping other running processes or [adding a swapfile](https://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/) should solve the problem.

**Closed by bmw** 2017-01-17 17:16 UTC

**Comment by seniorcandy** [comment] 2017-04-18 03:38
this is a solution from the official document
creating a temporary swapfile:
`user@webserver:~$ sudo fallocate -l 1G /tmp/swapfile
user@webserver:~$ sudo chmod 600 /tmp/swapfile
user@webserver:~$ sudo mkswap /tmp/swapfile
user@webserver:~$ sudo swapon /tmp/swapfile`

do your renew

Disable and remove the swapfile once the virtual enviroment is constructed:
`user@webserver:~$ sudo swapoff /tmp/swapfile
user@webserver:~$ sudo rm /tmp/swapfile`

**Comment by maxhudson** [comment] 2017-06-13 18:34
This didn't resolve the issue for me.
