### ISSUE TITLE
Certificate expanded with secondary SAN as main CN, as unintended and unexpected

### ISSUE THREAD

**Issue by ageis** [certbot/certbot#5637] opened 2018-02-28 19:38 UTC
## OS
Ubuntu xenial 16.04

## Certbot version
certbot version 0.21.1 via pip/PyPi

## I ran this command and it produced this output:

```certbot certonly --force-renewal --noninteractive --agree-tos --standalone --rsa-key-size 4096 --email 'kevin@libraryfreedomproject.org' --expand -d libraryfreedomproject.org -d mail.libraryfreedomproject.org -d analytics.libraryfreedomproject.org -d irc.libraryfreedomproject.org -d redmine.libraryfreedomproject.org```

## Certbot's behavior differed from what I expected because:
```
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/mail.libraryfreedomproject.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/mail.libraryfreedomproject.org/privkey.pem
   Your cert will expire on 2018-05-29. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"

```
I expected the first domain in the list to be the primary common name: `libraryfreedomproject.org`. Instead, it was the second one. (there was already an existing separate cert for `mail.libraryfreedomproject.org`, which may be the root of the problem).

**Comment by sydneyli** [comment] 2018-03-16 23:48
@ohemorange this behavior is kind of awkward, but I heard from brad that this might be expected behavior. What do you think?

**Comment by ohemorange** [comment] 2018-03-17 00:10
Thanks for reporting, Kevin! You're exactly right; `--expand` takes the existing cert name and adds more domains to it, regardless of the new order. If you want to change the primary common name, you can add the `--cert-name` flag to set the primary name to whatever string you want, including `libraryfreedomproject.org`. If no existing cert uses the name you choose, this will create a new certificate with all the domains whether or not you use `--expand`.

Since using `--cert-name` to manage certs is the currently best-supported version and `--expand/--duplicate` is the legacy code, I'm going to close this issue.

**Closed by ohemorange** 2018-03-17 00:10 UTC
Labels: area: cert management

**Comment by ageis** [comment] 2018-03-17 00:12
Got it.. Thanks.
