### ISSUE TITLE
Special Characters are not being converted

### ISSUE THREAD

**Issue by edupes** [certbot/certbot#4912] opened 2017-07-07 10:21 UTC
## My operating system is (include version):
Ubuntu Server LTS Xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
According to the official manual

## I ran this command and it produced this output:
It could not find "fréch.com", a domain of mine, so i had to lookup the xn- whatever address

## Certbot's behavior differed from what I expected because:
There where special chars

**Comment by SwartzCr** [comment] 2017-07-12 23:04
Can you please elaborate on what you mean when you say that it "couldn't find" that domain?
As in when it prompted you to choose a domain for the certificate you were requesting it didn't suggest that domain?
What web server are you using on this machine? Could you share what your virtual host configuration file(s) look like?

**Comment by htinc** [comment] 2017-07-13 05:08
I use Apache and when I entered my domain, it just failed to create the certificates. 

I was adding certificates for about 10 domains

**Comment by SwartzCr** [comment] 2017-07-13 21:40
Wait sorry, @htinc are you the same person as @edupes ?
If so could you provide some more context? If not, I'd appreciate it if you could open a new issue for the problems you're experiencing - that would really help me be able to debug them.
Thanks!

**Comment by bmw** [comment] 2017-07-25 18:09
What @edupes describes is a duplicate of #3614 so I'm closing in favor of that issue.

**Closed by bmw** 2017-07-25 18:09 UTC
Labels: area: debian / ubuntu, more-info
