### ISSUE TITLE
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'

### ISSUE THREAD

**Issue by heeen** [certbot/certbot#9478] opened 2022-11-22 14:54 UTC
This is more of a question than a bug report.
I am trying to use a dns plugin that appears to have been written against an older version of certbot, which used zope at some point. I realize that this was deprecated on certbot a while ago and plugins should now use `abc` instead.

As a user it was quite a hassle to figure out I had to downgrade certbot to be able to use the plugin I wanted. The error message certbot printed and the stack trace were unhelpful for guiding me in the right direction.

I finally found this [comment](https://github.com/certbot/certbot/issues/9427#issuecomment-1271019939) that got me on the right track.

After I figured it out, I wanted to [help the plugin author](https://github.com/helgeerbe/certbot-dns-ionos/issues/19) to adapt the plugin to certbot 2.0 so it would work with a simple pip install without specifying versions manually.

Since I only occasionally write python, I wanted to check other certbot dns plugins how they moved from zope to abc to do the same for the ionos plugin - however every plugin I checked still had zope in their requirements.

Could you guide me and plugin authors a bit to make the necessary changes?

**Comment by matrix16888** [comment] 2022-11-22 15:00
> 

Hi Heeen, today I encountered no attribute 'IAuthenticator' error too, from your post seems this is caused by new version of certbot but would you mind to share how to resolve this issue? Many thanks!

**Comment by heeen** [comment] 2022-11-22 15:51
the workaround until the plugin is adapted to certbot 2.0 is to use the previous version of certbot:
for example:
```
$ sudo apt install python3 python3-venv libaugeas0
$ sudo python3 -m venv /opt/certbot/
$ sudo /opt/certbot/bin/pip install --upgrade pip
$ sudo /opt/certbot/bin/pip install certbot==1.32.0 certbot-apache==1.32.0 acme==1.32.0 the-certbot-plugin-you-want-to-use
```

**Comment by osirisinferi** [comment] 2022-11-22 19:03
The following PR would probably be a good start I think: https://github.com/certbot/certbot/pull/8950

Depending on if the PR has tests the follow-up PR is also probably a good read: https://github.com/certbot/certbot/pull/8971

**Comment by alexzorin** [comment] 2022-11-22 20:22
I have opened a PR against the plugin to fix the `zope` issue.

Installing 1.32.0 is a fine workaround for this issue.

I did open PRs against a number of third-party DNS plugins a few months ago in anticipation of this issue, but I mainly looked at ones that had activate snap users. Sorry for missing this one.

Going to close this issue, as as solution is found and it is best continued on the plugin issue tracker.

**Closed by alexzorin** 2022-11-22 20:22 UTC

**Comment by heeen** [comment] 2022-11-23 08:33
you can still find many plugins using the outdated interfaces:

https://github.com/search?l=Python&q=%22from+certbot+import+interfaces%22&type=Code

I'm not asking anyone to fix or even message them all, but maybe it could be done with some sort of automation?

**Comment by alexzorin** [comment] 2022-11-23 09:31
Yeah, I based my initial outreach on plugins that had active snap users because the GitHub code results are painful to filter. We might be able to ask Let's Encrypt for DNS authenticator stats, to find active DNS plugins that have this issue. I think that would probably have to wait until after Thanksgiving break, though.
