### ISSUE TITLE
Problem with - character, produced an unexpected error: 'ascii' codec can't encode character u'\xe1' in position 271: ordinal not in range(128). Skipping.

### ISSUE THREAD

**Issue by darius1706** [certbot/certbot#5077] opened 2017-09-06 07:49 UTC
## My operating system is (include version):
FreeBSD 11.1-RELEASE-p1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
FreeBSD pkg system

## I ran this command and it produced this output:
certbot renew --dry-run

## Certbot's behavior differed from what I expected because:
Because I got message for domain names with - 
Attempting to renew cert from /usr/local/etc/letsencrypt/renewal/example-domain.cz.conf produced an unexpected error: 'ascii' codec can't encode character u'\xe1' in position 271: ordinal not in range(128). Skipping.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2017-09-06 07:28:40,000:WARNING:certbot.renewal:Attempting to renew cert from /usr/local/etc/letsencrypt/renewal/example-domain.cz.conf produced an unexpected error: 'ascii' codec can't encode character u'\xe1' in position 271: ordinal not in range(128). Skipping.
2017-09-06 07:28:40,054:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/certbot/renewal.py", line 419, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 641, in renew_cert
    _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python2.7/site-packages/certbot/renewal.py", line 297, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/usr/local/lib/python2.7/site-packages/certbot/client.py", line 317, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 201, in _poll_challenges
    _report_failed_challs(all_failed_achalls)
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 492, in _report_failed_challs
    _generate_failed_chall_msg(achalls), reporter.MEDIUM_PRIORITY)
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 508, in _generate_failed_chall_msg
    if messages.is_acme_error(error):
  File "/usr/local/lib/python2.7/site-packages/acme/messages.py", line 39, in is_acme_error
    return (ERROR_PREFIX in str(err)) or (OLD_ERROR_PREFIX in str(err))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 271: ordinal not in range(128)

2017-09-06 07:28:40,054:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.16.0', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 743, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 693, in renew
    renewal.handle_renewal_request(config)
  File "/usr/local/lib/python2.7/site-packages/certbot/renewal.py", line 436, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

Than you very much.
D

**Comment by SwartzCr** [comment] 2017-09-07 18:24
Do you happen to know what challenge certbot used for this certificate?
Was it webroot, apache, or nginx?
This error typically occurs when certbot fails to properly host the challenge information and the Let's Encrypt server gets back your actual webpage instead of the challenge text.

**Comment by SwartzCr** [comment] 2017-09-25 19:13
@darius1706 have you been able to get it to work? Or made any other progress?

**Comment by ynasser** [comment] 2017-10-02 22:47
@darius1706 what version of certbot are you using? I believe this was fixed in a recent certbot release.

**Comment by SwartzCr** [comment] 2017-10-31 19:11
closing this as stale, if darius comments I'm happy to re-open it

**Closed by SwartzCr** 2017-10-31 19:11 UTC
Labels: area: renewal, debugging, more-info

**Comment by RSol** [comment] 2018-08-28 06:11
This command help me

`grep -r -P '[^\x00-\x7f]' /etc/nginx /etc/letsencrypt`

**Comment by kh71** [comment] 2018-09-06 14:40
@RSol yes i try not show any.

me use certbot version 0.23.0 and Ubuntu 18.04.1 LTS.

certbot renew --dry-run

Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/---.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Attempting to renew cert (---) from /etc/letsencrypt/renewal/---.conf produced an unexpected error: 'ascii' codec can't decode byte 0xe2 in position 301: ordinal not in range(128). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/---/fullchain.pem (failure)

-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/---/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)

**Comment by orzel** [comment] 2019-01-28 00:05
I can confirm: I've had a similar issue. The reason was a non-ascii character in the nginx file. Actually a legitimate one imho : auth_basic "xxxx" , which is used to display text when asking for basic http password to the user.

In this case the message was localized with non-ascii character.

Removing them made certbot happy, but not me, cause i can't speak natively to those users anymore.

**Comment by anza** [comment] 2019-11-07 15:40
I still stumbled upon this, so recording if anyone else finds this thread. The sole reason for this error seems to be non-ascii chars in any config files that are traversed by certbot (in my case /etc/nginx/conf.d/*). I had *comments* with non-ascii characters in the nginx config file and certbot totally choked over them.

Don't know whether this has been already fixed in later versions but imho it should be. My system is CentOS 7 and `certbot 0.39.0`. `# grep -nRPrs '[\x80-\xFF]' /etc/nginx/` might help remedying this.

**Comment by alejandrogih** [comment] 2020-06-16 04:32
@RSol thank you so much, I found an issue in my nginx.conf exactly using that command, removed the comment lines and worked perfectly. thanks again!
