### ISSUE TITLE
Implement locking to ensure two clients do not run at once

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#933] opened 2015-10-09 16:41 UTC
Does the letsencrypt client establish a lock while it is running, so we don't have two separate LE instances trying to modify the same configuration files at once?

**Comment by bmw** [comment] 2015-10-09 22:36
It does not. Running two instances of the client is a good way to break your config. Problems can also occur if the client and the renewer run at the same time. We may want to tag this issue for launch.

**Comment by kuba** [comment] 2015-10-11 10:16
Dupe of #335 and #564?

**Comment by jsha** [comment] 2015-10-12 17:09
Those are slightly different: they are about individual components: the cert db and lineage data. I'm suggesting an overall lock for all letsencrypt-related changes, which is probably simpler to reason about.

We would probably also want to make sure that manually-run clients time out after some time, to ensure that if you leave a terminal hanging in the middle of a `letsencrypt run` instance, it does not prevent renewals from happening.

**Comment by laebshade** [comment] 2015-10-20 03:36
Isn't the binary ad-hoc?  Why prevent users from intentionally shooting themselves in the foot?

**Comment by bmw** [comment] 2017-03-30 19:02
Reopening, but this will be done for 0.13.0.

**Closed** 2017-05-01 21:49 UTC
Labels: enhancement, has pr
