### ISSUE TITLE
Apache configtest fails for conf with WSGI after running certbot 

### ISSUE THREAD

**Issue by arunabhdas** [certbot/certbot#6217] opened 2018-07-13 10:06 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Using apt as follows
$ sudo apt-get update
$ sudo apt-get install python-certbot-apache 

## I ran this command and it produced this output:

sudo certbot --apache

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.app.conf:
Name duplicates previous WSGI daemon definition.

The apache plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError("Error while running apache2ctl configtest.\nAction 'configtest' failed.\nThe Apache error log may have more information.\n\nAH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.app.conf:\nName duplicates previous WSGI daemon definition.\n",)

==> vim /var/log/letsencrypt/letsencrypt.log

2018-07-13 10:03:48,245:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-07-13 10:03:48,287:ERROR:certbot.util:Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.com.conf:
Name duplicates previous WSGI daemon definition.

2018-07-13 10:03:48,288:DEBUG:certbot.plugins.disco:Misconfigured PluginEntryPoint#apache: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.com.conf:
Name duplicates previous WSGI daemon definition.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 2050, in config_test
    util.run_script(self.constant("conftest_cmd"))
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 86, in run_script
    raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.com.conf:
Name duplicates previous WSGI daemon definition.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 127, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 208, in prepare
    self.config_test()
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 2052, in config_test
    raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.com.conf:
Name duplicates previous WSGI daemon definition.

2018-07-13 10:03:48,289:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7f9e78329748>
Prep: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.com.conf:
Name duplicates previous WSGI daemon definition.

2018-07-13 10:03:48,290:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

==> systemctl status apache2.service

● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: active (running) (Result: exit-code) since Fri 2018-07-13 09:53:12 UTC; 3min 54s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5788 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 6228 ExecReload=/etc/init.d/apache2 reload (code=exited, status=1/FAILURE)
  Process: 6050 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)
    Tasks: 7
   Memory: 39.6M
      CPU: 305ms
   CGroup: /system.slice/apache2.service
           ├─6067 /usr/sbin/apache2 -k start
           ├─6070 /usr/sbin/apache2 -k start
           ├─6071 /usr/sbin/apache2 -k start
           ├─6072 /usr/sbin/apache2 -k start
           ├─6073 /usr/sbin/apache2 -k start
           ├─6074 /usr/sbin/apache2 -k start
           └─6077 /usr/sbin/apache2 -k start

Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]:  * Reloading Apache httpd web server apache2
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]:  *
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]:  * The apache2 configtest failed. Not doing anything.
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]: Output of config test was:
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]: AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/mywebsitedomain.app.conf:
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]: Name duplicates previous WSGI daemon definition.
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]: Action 'configtest' failed.
Jul 13 09:56:58 ip-172-31-0-238 apache2[6228]: The Apache error log may have more information.
Jul 13 09:56:58 ip-172-31-0-238 systemd[1]: apache2.service: Control process exited, code=exited status=1
Jul 13 09:56:58 ip-172-31-0-238 systemd[1]: Reload failed for LSB: Apache2 web server.

## Certbot's behavior differed from what I expected because:

Apache should restart and the website should be accessible over https after restart

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        # DocumentRoot /var/www/html
        ServerName mywebsitedomain.com
        ServerAlias www.mywebsitedomain.com
        DocumentRoot /var/www/html/mywebsitedomain-com

        Alias /static/ /home/ubuntu/Sites/mywebsitedomain-com/myproductionfolder/static/
        <Directory /home/ubuntu/Sites/mywebsitedomain-com/myproductionfolder/static>
                Require all granted
         </Directory>

        # adjust the following line to match your Python path 
        <Directory "/home/ubuntu/Sites/mywebsitedomain-com/myproductionfolder">
        <Files wsgi.py>
                AllowOverride all
                Options FollowSymLinks
                Require all granted
        </Files>
        </Directory>

        WSGIDaemonProcess mywebsitedomain.com processes=2 threads=15 display-name=%{GROUP} user=www-data group=www-data python-path=/home/ubuntu/Sites/mywebsitedomain-com:/home/ubuntu/Sites/mywebsitedomain-com/venv/lib/python3.5/site-packages
        WSGIProcessGroup mywebsitedomain.com
        WSGIScriptAlias / /home/ubuntu/Sites/mywebsitedomain-com/myproductionfolder/wsgi.py process-group=mywebsitedomain.com application-group=%{GLOBAL}

        Alias /phpmyadmin /var/www/html/phpmyadmin
        <Location /phpmyadmin>
        </Location>

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

</VirtualHost>

**Comment by schoen** [comment] 2018-07-16 22:46
Cc @joohoi 

@arunabhdas , thank you for the bug report. Which is the other Apache configuration file that contains the duplicated WSGI directive? Could you post that file as well?

And which version of Certbot are you running?

**Comment by joohoi** [comment] 2018-07-17 09:02
It looks like this is a duplicate of #1820 and I'm closing this issue in order to not to fragment the discussion. There is a more generic issue for Apache configuration directives that don't work when copied over at #4797

If you feel that this issue is different, feel free to comment and I'll reopen it.

**Closed by joohoi** 2018-07-17 09:02 UTC
Labels: area: apache, duplicate, more-info
