### ISSUE TITLE
Obtain "Official image" verification on Docker Hub

### ISSUE THREAD

**Issue by atombrella** [certbot/certbot#8991] opened 2021-08-16 13:46 UTC
I skimmed through https://docs.docker.com/docker-hub/official_images/#creating-an-official-image which links to
https://github.com/docker-library/official-images

I think certbot/certbot (and possibly the DNS plugin images) should be labelled as official, since they're most likely used in production.

**Comment by bmw** [comment] 2021-08-19 17:47
I think this is a duplicate of https://github.com/certbot/certbot/issues/5540.

**Closed by bmw** 2021-08-19 17:47 UTC
