### ISSUE TITLE
Paths are getting ignored

### ISSUE THREAD

**Issue by mjesun** [certbot/certbot#4300] opened 2017-03-05 17:37 UTC
## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum

## I ran this command and it produced this output:
certbot certonly --non-interactive --agree-tos --standalone --email='admin@example.com' --key-path=/etc/letsencrypt/live/admin/key.pem --cert-path=/etc/letsencrypt/live/admin/cert.pem --chain-path=/etc/letsencrypt/live/admin/chain.pem --fullchain-path=/etc/letsencrypt/live/admin/fullchain.pem -d my.example.tld

## Certbot's behavior differed from what I expected because:
The certificates were not placed on the expected folders; they were placed y `my.example.tld` folder, instead of the `admin` folder, as I would have expected.

## Here is a Certbot log showing the issue (if available):
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/my.example.tld/fullchain.pem. Your cert
   will expire on 2017-06-03. To obtain a new or tweaked version of
   this certificate in the future, simply run certbot again. To
   non-interactively renew *all* of your certificates, run "certbot
   renew"
 - If you lose your account credentials, you can recover through
   e-mails sent to admin@example.com.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

**Comment by bmw** [comment] 2017-03-07 02:19
This is a duplicate of #3611. To achieve the behavior you want, make sure you're using Certbot 0.12.0+ (which I believe should be in EPEL7 soon) and include `--cert-name admin` on the command line.

**Closed by bmw** 2017-03-07 02:19 UTC

**Comment by Xosmond** [comment] 2017-12-22 17:20
@bmw thanks for that advice, can I use that also for `cerbot renew` ?

**Comment by bmw** [comment] 2018-01-02 21:23
When `--cert-name` is used with `certbot renew`, it only potentially renews the certificate with the matching name rather than checking all certificates being managed by Certbot.
