### ISSUE TITLE
Fail to renew/issue certificate - KeyError: 'server'

### ISSUE THREAD

**Issue by asafco4** [certbot/certbot#3569] opened 2016-10-01 15:46 UTC
I'm trying to renew my certificate, I think my system is in a big mess, tried to to install let's encrypt, certbot, any combination, all ends with errors.
All I need is just the certificates, I do NOT need it to be installed nowhere.

Trying to run:
sudo letsencrypt certonly

Utility opens up, I enter my domain, expecting to get the renewed certificates, but I get an Error:
An unexpected error occurred:
KeyError: 'server'
Please see the logfiles in /var/log/letsencrypt for more details.

The content of the log file is:
2016-10-01 15:21:04,553:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-10-01 15:21:04,554:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-01 15:21:04,554:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.1
2016-10-01 15:21:04,555:DEBUG:letsencrypt.cli:Arguments: []
2016-10-01 15:21:04,555:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual                                             ,PluginEntryPoint#standalone)
2016-10-01 15:21:04,661:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2016-10-01 15:21:09,080:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): Missing parts of webroot configuration; please set eithe                                             r --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/webroot.py", line 56, in prepare
    "Missing parts of webroot configuration; please set either "
PluginError: Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for exam                                             ples.
2016-10-01 15:21:09,082:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7fea32f1ef10>
Prep: True
2016-10-01 15:21:09,083:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7fea32f1ef10> and install                                             er None
2016-10-01 15:21:09,534:DEBUG:letsencrypt.cli:Picked account: <Account(6526f0b09dc0693b60015c4b24811a8c)>
2016-10-01 15:21:09,684:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-01 15:21:09,845:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-01 15:21:10,283:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-10-01 15:21:10,285:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Sat, 01 Oct 2016 15:21:10 GMT', 'Boulder-Re                                             quest-Id': 'Jbvn_mKhMz5Weti_L3E2YvTD0cn4n8ry2modNNVcGOw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive',                                              'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 01 Oct 2016 15:21:10 GMT', 'X-Frame-Options': 'DENY', 'Content-Typ                                             e': 'application/json', 'Replay-Nonce': 'EFp81WRaLEX3ioAzDKITZQOyEi4mGFiCLI4y797pBhQ'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.or                                             g/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg                                             ",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-10-01 15:21:10,285:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Sat, 01 Oct 2016 15:21:10 G                                             MT', 'Boulder-Request-Id': 'Jbvn_mKhMz5Weti_L3E2YvTD0cn4n8ry2modNNVcGOw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection'                                             : 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 01 Oct 2016 15:21:10 GMT', 'X-Frame-Options': 'DEN                                             Y', 'Content-Type': 'application/json', 'Replay-Nonce': 'EFp81WRaLEX3ioAzDKITZQOyEi4mGFiCLI4y797pBhQ'}): '{\n  "new-authz": "https://acme-v01.api.letsen                                             crypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme                                             /new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-10-01 15:21:10,285:DEBUG:letsencrypt.display.ops:No installer, picking names manually
2016-10-01 15:21:18,818:DEBUG:parsedatetime:parse (top of loop): [30 days][]
2016-10-01 15:21:18,901:DEBUG:parsedatetime:CRE_UNITS matched
2016-10-01 15:21:18,901:DEBUG:parsedatetime:parse (bottom) [][30 days][][]
2016-10-01 15:21:18,901:DEBUG:parsedatetime:weekday False, dateStd False, dateStr False, time False, timeStr False, meridian False
2016-10-01 15:21:18,901:DEBUG:parsedatetime:dayStr False, modifier False, modifier2 False, units True, qunits False
2016-10-01 15:21:18,901:DEBUG:parsedatetime:_evalString(30 days, time.struct_time(tm_year=2016, tm_mon=10, tm_mday=1, tm_hour=15, tm_min=21, tm_sec=18,                                              tm_wday=5, tm_yday=275, tm_isdst=0))
2016-10-01 15:21:18,901:DEBUG:parsedatetime:_buildTime: [30 ][][days]
2016-10-01 15:21:18,901:DEBUG:parsedatetime:units days --> realunit days
2016-10-01 15:21:18,901:DEBUG:parsedatetime:return
2016-10-01 15:21:18,901:DEBUG:letsencrypt.storage:Should renew, less than 30 days before certificate expiry 2016-10-19 04:53:00 UTC.
2016-10-01 15:21:18,901:INFO:letsencrypt.cli:Cert is due for renewal, auto-renewing...
2016-10-01 15:21:18,975:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 453, in _auth_from_domains
    original_server = lineage.configuration["renewalparams"]["server"]
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'

**Comment by bmw** [comment] 2016-10-03 19:45
@asafco4, sorry for the trouble. This is caused by taking configuration files from a newer version of `certbot/letsencrypt` and using them with `letsencrypt` 0.4.1 in Ubuntu. The problem has been fixed in newer versions of Certbot, but while we're waiting for Ubuntu to upgrade their `letsencrypt` package, I posted a workaround [here](https://github.com/certbot/certbot/issues/2750#issuecomment-238983818).

**Closed by bmw** 2016-10-03 19:45 UTC
