### ISSUE TITLE
NGINX error and use of  snippets suggesttion

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#4757] opened 2017-05-31 19:13 UTC
My *NGINX script* at `/etc/nginx/nginx.conf` is working fine (!) with all my certbot-certificates... But when I run `certbot --nginx --cert-name domain1` return this error:

> Cannot find a cert or key directive in /etc/nginx/nginx.conf for set(['domain1', 'www.domain1']). VirtualHost was not modified.

It is because all the  lines marked as "managed by Certbot" was grouped in one included file, `snippets/ssl-domain1.conf`, that repeat all time.  

... So snippets file reduce pollution, reduce parsing work, and not cause "Cannot find" error.

## The scripts
File `/etc/nginx/nginx.conf`:
```
....
http {
   ....   
server {
        server_name domain1;
        location / {
                proxy_pass https://heroku.com;
        }
include snippets/ssl-domain1.conf

} # end server

} # end http
```

File `/etc/nginx/snippets/ssl-domain1.conf`, to be managed by Certbot!
```
##
# SSL configs managed by Certbot.
#
listen 80; 
listen 443 ssl; 
ssl_certificate /etc/letsencrypt/live/domain1/fullchain.pem; 
ssl_certificate_key /etc/letsencrypt/live/domain1/privkey.pem;
include /etc/letsencrypt/options-ssl-nginx.conf;

if ($scheme != "https") {
  return 301 https://$host$request_uri;
} 
```

**Comment by SwartzCr** [comment] 2017-06-06 23:12
I'm not quite sure I understand, but maybe @ohemorange does?

**Comment by ohemorange** [comment] 2017-06-06 23:40
@ppKrauss, we work with included files. What we don't currently handle is http-block-level directives. Closing this as a duplicate of #583.

For your particular case, you can enclose the contents of `/etc/nginx/snippets/ssl-domain1.conf` in a `server {}` block, and Certbot should work.

**Closed by ohemorange** 2017-06-06 23:40 UTC
Labels: area: nginx, area: ui / ux

**Comment by ppKrauss** [comment] 2017-06-22 22:15
Thanks @ohemorange, for here and [at discussion](https://community.letsencrypt.org/t/35668/6). My "error" was to declare all servers at `nginx.conf` instead each in a `sites-available/script` ... Now is working as expected.
