### ISSUE TITLE
Certbot defaults to obtaining one single certificate for all  domains and serveraliases (regardless of virtual host)

### ISSUE THREAD

**Issue by RichardNeill** [certbot/certbot#3490] opened 2016-09-12 15:53 UTC
I have multiple websites on a single Apache server, each with separate config files, and each with a DocumentRoot, ServerName and multiple ServerAliases.

To illustrate this, lets assume my server contains 3 completely unrelated websites, dedicated to selling fruit, tools, and travel:
# (A) Fruit:

/etc/apache/sites-enabled/fruit-conf  contains:

ServerName    apples.com 
ServerAlias      www.apples.com
ServerAlias      oranges.com
 ServerAlias      www.oranges.com
ServerAlias      kiwis.com
 ServerAlias      www.kiwis.com
 DocumentRoot   /var/www/fruits/
# (B) tools:

/etc/apache/sites-enabled/tools-conf  contains:

ServerName    spanners.com 
ServerAlias      www.spanners.com
ServerAlias      hammers.com
ServerAlias      www.hammers.com
 DocumentRoot   /var/www/tools/
# (C) Travel:

/etc/apache/sites-enabled/fruit-conf  contains:

ServerName    visit-usa.com 
ServerAlias      www.visit-usa.com
ServerAlias      seefrance.com
ServerAlias      www.seefrance.com
 DocumentRoot   /var/www/travel/

I then use certbot-auto, and follow the prompts. It asks me whether I want to obtain certificates for:
1: apples.com
2: www.oranges.com
3: www.apples.com
...
14: seefrance.com

This is partially correct,  in that I want to https-enable my entire server.

However, it is misleading in that I don't want a single cert that covers both hammers and oranges! I actually want one cert for all the fruity-domains, one cert for all the travel domains, and one cert for all the tools-domains.

Problem 1: Misleading interface - it is unclear from the prompt what will happen (am I being prompted to enable a single cert covering all domains, or am I being prompted to get certs for everything?)

Problem 2: The certs should (by default, imho?) group according to the virtual-hosts. If they don't this is at best confusing to the user, and at worst a possible information leak (a cert for https://hammers.com is allowed to contain a reference to spanners.com, but not to some-unrelated-possibly-private-domain-hosted-on-the-same-ip.com).

Problem 3: A minor one, but the list of domains is not sorted in a sensible way. I think it should sort first by all domains in the same vhost, and then it should order the "www." variant of the url to be listed straight after the unprefixed version.

Workaround: invoke certbot-auto  N times, manually select the appropriate domains from the list to group together. This alternative is much more time-consuming and error-prone.
## 

Thanks for your consideration, and your work on a great product.

**Comment by pde** [comment] 2016-09-13 19:50
> Problem 2: The certs should (by default, imho?) group according to the virtual-hosts.

That's only a good idea if you can assume that all clients [support SNI](https://en.wikipedia.org/wiki/Server_Name_Indication#Support).  If you want to handle older clients, you'll need to either have one giant cert, or a separate public IP address for each cert.

See also: #369.

**Comment by pde** [comment] 2016-09-13 19:52
Regarding domain order: if you supply domains on the command line, the one you provide first will be used as the CN domain (the others will be Subject Alternative Name domains).  If you really want to control the order of the SAN domains, please file a ticket against https://github.com/letsencrypt/boulder, since it would have to be supported by the Let's Encrypt server.

**Comment by pde** [comment] 2016-09-13 19:53
Lastly, the way you get the result you want right now is to invoke Certbot once for each set of names you'd like in a given certificate. That will produce several different certificates (in fact, several different certificate lineages) each containing the names you want.

**Comment by RichardNeill** [comment] 2016-09-20 13:29
Thanks for your comment. I know your point about SNI, but for us, we decided that anyone running a browser that didn't do SNI (which is now really ancient, things like IE6 on XP) would be better off if we do them a favour and deny them access to force an upgrade!

I do know the workaround - invoking certbot multiple times. 

The real issue here is not necessarily certbot's behaviour, but that the UI defaults to something which is (for many users) clearly not what they would want, and yet it gives no obvious cue that it will do this.
For some users, the intention of "https-enable-my-entire-sever" may be interpreted to mean "get me one https cert for everything", whereas for others, it means "https-enable each of my virtual-hosts [but I would never conflate them, and it is unthinkable that certbot would do that either]"

Simply changing the interface text from "Which names would you like to activate HTTPS for?" to "Which names do you want to activate HTTPS, with a single combined certificate, for ?"  (and maybe footnoting it with a link to an explanation)  would make it much less misleading. I would be happy with that.

In addition, I would like to see a CLI/GUI option for "group my domains according to the vhosts files in apache/sites-enabled" (or even better, make that the default, and have a flag for --one-all-encompassing-cert).

[Aside: if certbot would support wildcard certs, some of this problem would go away.] 

Thanks very much

**Comment by Frankkkkk** [comment] 2016-12-10 21:23
Maybe a `--group-by-domain` option to certbo-auto and a corresponding dedicated loop in `certbot/main.py:install` ?

**Comment by pde** [comment] 2016-12-12 20:02
@Frankkkkk probably rather than "group by domain" what people really mean is group by vhost (for Apache) or by server block (for Nginx). Unfortunately that would require us to update the [IInstaller](https://certbot.eff.org/docs/api/interfaces.html#certbot.interfaces.IInstaller) interface to those plugins (and be mindful of the impact on third party plugins).

I think that's actually the same thing as the `--vhosts sni` option discussed in #369 ... it wouldn't make sense to do literally one cert per domain, because you'd have to split your vhosts / server blocks for `example.com` and `www.example.com` (and `example.net` too if that serves identical content) in order to use them.

**Comment by pde** [comment] 2016-12-12 20:04
In any case, I think this is a duplicate of #369.

**Comment by pde** [comment] 2016-12-12 20:09
@RichardNeill to answer your specific concerns:

Problem 1: do you have any proposed wording changes that might clarify things for the user?
Problem 2: one cert for everything is the default because not all clients support SNI; if you do multiple certs you will break various old / less sophisticated clients.

It isn't clear which option has better privacy / information leakage properties -- it depends on the adversary. Network attackers would learn less from TLS connections if there was no SNI, and the server's cert included a large number of domains. And the fact that different domains are on the same server was public information anyway, at least to people who had access to TLD zone files and the inclination to crawl them.

But you may be right about privacy wrt end users who are not paying a lot of attention.

Problem 3: Fixed in git master by #3892

**Closed** 2019-06-20 21:17 UTC
Labels: area: ui / ux, duplicate, needs-update
