### ISSUE TITLE
KeyError: 'code' error message when issuing CloudFlare Challenge

### ISSUE THREAD

**Issue by maretodoric** [certbot/certbot#7970] opened 2020-05-03 18:54 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Raspbian (Debian Buster)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Using Home Assistant Addon and using OS package manager, apt-get install certbot

## I ran this command and it produced this output:
certbot certonly   --dns-cloudflare   --dns-cloudflare-credentials ~/.secrets/cloudflare.ini -d domain1.tk -d '*.domain1.tk' -d domain2.ml -d '*.domain2.ml' -d domain3.tk -d '*.domain3.tk' --preferred-challenges dns --dns-cloudflare-propagation-seconds 60

## Certbot's behavior differed from what I expected because:
It displays same error message when tried executing from both Home Assistant to automate certificate issuing and from cli. Python version is 3.7 (Home assistant is installed via docker and python is ran from docker on letsencrypt addon)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
https://pastebin.com/AUEYV7Xq

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Apache or Nginx not yet used since certificates are not issued.

**Comment by allanesquina** [comment] 2020-05-03 23:32
Hello, the log says `Unable to find TXT record.`.
It may be an issue of `authorization` or a short `propagation time`. 
I'm having a similar problem with Digital Ocean plugin. 
Can you check if the records were created in your CloudFlare panel at the time of validation?

**Comment by tilda** [comment] 2020-05-04 06:52
Same issue, I'm using the packaged version from OpenSUSE Tumbleweed and unable to issue a certificate using Cloudflare plugin. It was working fine before this.

**Comment by maretodoric** [comment] 2020-05-04 08:59
Hello @allanesquina , the error first appears before checking if records are added, right after it's trying to add them.

```
2020-05-03 20:11:54,668:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Attempting to add record to zone 2c0e537b7c6ed142b9a24f19ae0c2d90: {'type': 'TXT', 'name': '_acme-challenge.domain2.ml', 'content': '8DPrtwwBaG5gRP-5D6QBsQp7g1FYdVJWXoFnUmZ7ujE', 'ttl': 120}
2020-05-03 20:11:54,936:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "POST /client/v4/zones/2c0e537b7c6ed142b9a24f19ae0c2d90/dns_records HTTP/1.1" 401 None
2020-05-03 20:11:54,943:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/local/lib/python3.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 116, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "/usr/local/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 671, in post
    params, data, files)
  File "/usr/local/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 123, in call_with_auth
    params, data, files)
  File "/usr/local/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 488, in _call
    code = errors['code']
KeyError: 'code'
```
I don't believe it's authorization issue since I've tried both api token,which has limited permissions and Global API Key which is unrestricted. Error is same in both cases.

**Comment by allanesquina** [comment] 2020-05-05 00:04
@maretodoric It seems you're getting `401 Unauthorized` from the request `https://api.cloudflare.com:443 "POST /client/v4/zones/2c0e537b7c6ed142b9a24f19ae0c2d90/dns_records HTTP/1.1" 401`

Maybe the request headers has changed or your token has not enough permission to perform this request. You can try to call the `CloudFlare API` via `Postman` to ensure that the problem is not your token. 

If it is ok, so maybe the API has changed. 

I found a similar issue on CloudFlare support, it can be an internal problem as well. 

https://community.cloudflare.com/t/no-longer-able-to-update-dns-records-via-api/143942

**Comment by maretodoric** [comment] 2020-05-05 09:23
Argh..... Damn..... Looks like CloudFlare changed something........
I tried calling API manually but via curl, and in JSON response i got the error message:
"You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)"....

Real shame.... It used to work, i know since I've issued couple of certificates already. Well.. Okay... What's done it's done.

**Comment by tilda** [comment] 2020-05-05 10:05
Interesting. Wonder why they did that.

**Comment by maretodoric** [comment] 2020-05-05 10:19
Probably because of misuse. I hear lots of these domains are used for malicious purpose or fraud or something of that sort.. i just use it for my own home projects.

Too bad i cannot enjoy wildcard domains anymore because of this CloudFlare thing...

**Comment by allanesquina** [comment] 2020-05-05 23:19
You can get the wildcard manually or you can use [acme-dns](https://github.com/joohoi/acme-dns)
I've found [Greenlock ](https://greenlock.domains/) in this [video ](https://www.youtube.com/watch?v=lYgTZgMLOIY), it may help you.

**Comment by bmw** [comment] 2020-05-07 21:48
This is unfortunate.

I'm not sure there's much we can do about the problem here though as it was a change Cloudflare made on their end.

The error raised by Certbot here is bad, however, it's a problem that occurs within the official Cloudflare library (or at least the version packaged in Debian). Getting that reported upstream if it hasn't already would be useful, but beyond that, I don't think there's much we can do to help this issue so I'm going to close it.

Sorry for the trouble!

**Closed by bmw** 2020-05-07 21:48 UTC

**Comment by PVasileff** [comment] 2020-05-11 11:52
CloudFlare do that for money.... Here is answer from their support

> Hi,
> 
> Thank you for contacting Cloudflare Support.
> 
> As the error states you won't be able to use the API to update via certbot with those TLDs on a Free plan. You'll either need to upgrade your plan level or use the Dashboard directly.
> 
> Best,
> 
> Mianmian | Cloudflare Support Engineer
> Search the Cloudflare Community for advice and insight.

**Comment by ledlamp** [comment] 2020-07-06 19:30
![fuuu](https://cdn.discordapp.com/attachments/382269195963990017/729781187597303928/derpfuuu.png)

**Comment by ledlamp** [comment] 2020-07-06 19:43
At least I can do it manually for now
```
 certbot certonly --manual --preferred-challenges dns
```
But I will have to look for another DNS provider that certbot has a plugin for, that allows using these free domains.

**Comment by GuyKh** [comment] 2020-07-13 11:59
Any way to update the certificate for Cloudflare then (using .tk domain)?

**Comment by PVasileff** [comment] 2020-07-13 17:40
Yes, see comment:

https://github.com/certbot/certbot/issues/7970#issuecomment-626655360

**Comment by GuyKh** [comment] 2020-07-14 11:37
I'll rephrase - how can I do that without upgrading Cloudflare plan?
I can't run certbot manully with the dashboard... or atleast don't know how

**Comment by ledlamp** [comment] 2020-07-15 05:40
> I'll rephrase - how can I do that without upgrading Cloudflare plan?
> I can't run certbot manully with the dashboard... or atleast don't know how

what dashboard? are you using something like cpanel?

**Comment by GuyKh** [comment] 2020-07-15 08:13
> > I'll rephrase - how can I do that without upgrading Cloudflare plan?
> > I can't run certbot manully with the dashboard... or atleast don't know how
> 
> what dashboard? are you using something like cpanel?

Coppying from the referenced commet from Cloudflare:

> As the error states you won't be able to use the API to update via certbot with those TLDs on a Free plan. You'll either need to upgrade your plan level or use the Dashboard directly.

**Comment by ledlamp** [comment] 2020-07-17 23:07
@GuyKh Bruh you don't use Cloudflare dashboard to run Certbot... Certbot is a command line program you run on your server and it would automatically log in to your Cloudflare account (via API) to change DNS records to complete the challenge to obtain new certificates from LetsEncrypt. Now that Cloudflare blocks this for free domains you will have to do it manually by using that command line I showed and following the instructions. Certbot will tell you to add a TXT record which you do on Cloudflare's website.

**Comment by ledlamp** [comment] 2020-07-29 19:08
Ok so I looked at the list of dns provider plugins Certbot had and checked each service, and found luadns to be a good alternative because they have a free plan (on which you can have 3 domains) and they allow the API for free domains.
