### ISSUE TITLE
Apache Authenticator can not find vhost if multiple vhosts exists in a file

### ISSUE THREAD

**Issue by michi-roth** [certbot/certbot#2275] opened 2016-01-25 10:33 UTC
Commit f5862a7a introduced a change in letsencrypt-apache/letsencrypt_apache/configurator.py in line 536 and following to remove a vhost from the list if a new vhost with the same path is found. This breaks the detection of multiple apache vhosts in a file. With this change my cronjob can not automatically renew my certificates.

In my opinion it would be great if the script does not remove vhosts within the same file when the number of the vhost is different. The variable vhost.vhpath contains the position in braces at the end if multiple vhosts are in a file.

**Comment by michi-roth** [comment] 2016-01-25 20:30
I modified the code to support apache vhost config files with multiple vhosts. Since I only use the authenticator I have not tested the installer.

**Comment by bmw** [comment] 2016-01-27 20:03
Currently, multiple vhosts per file are not supported. See: #1042.

**Comment by michi-roth** [comment] 2016-01-28 10:42
Even the support for the apache installer is complicated it was possible to use only the apache authenticator before.  IMHO it should be possible to request the certificates without the use of the configuration files. Or is there a reason i hove overlooked why the authenticator uses the site configuration files?

**Comment by bmw** [comment] 2016-02-01 22:34
The authenticator uses the configuration files to determine which IP address and port should be used to set up the challenge.

**Comment by bmw** [comment] 2016-10-31 19:28
Our Apache plugin has never properly supported multiple vhosts per file. While we plan on adding support in our next release, the change in behavior you saw here was us actually fixing a bug and it was a coincidence that the plugin worked for you with multiple vhosts in a file before. On different setups, the plugin would have failed.

I'm closing this as a dupe of #1042 and am working on a PR to fully add support for this use case.

**Closed by bmw** 2016-10-31 19:28 UTC
Labels: apache, has pr
