### ISSUE TITLE
poor choice of virtualhost model when creating example configuration file

### ISSUE THREAD

**Issue by JohnDenker** [certbot/certbot#1340] opened 2015-11-04 18:54 UTC
#### Context and Background
- I am running a server with multiple virtual hosts, some on port 80 and some on port 443.
- I did    `./letsencrypt-auto certonly`
#### Observed Behavior:

On the terminal screen:

```
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/xxx.av8n.com/fullchain.pem.
```

In my server configuration directory, a new file:

```
:; cat default-b-le-ssl.conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName xxx.av8n.com
        DocumentRoot /var/www/xxx
        Include             /etc/apache2/sites-available/generic.conf
SSLCertificateFile insert_cert_file_path
SSLCertificateKeyFile insert_key_file_path
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

This example file was evidently modeled on my pre-existing file `default-b.conf` which is the configuration for the virtual host on port 80.
#### Desired and/or Expected Behavior

It would be incomparably better for the newly-created example file to be modeled on the existing virtual host on port 443 (rather than 80).
#### Additional Suggestions
- Having the `./letsencrypt-auto certonly` command scribble in my configuration directory was not expected ... but it is arguably desirable.  Some changes are needed to make iit desirable, to make it useful.
- The contents of the file need to be improved:  rather than saying `insert_cert_file_path` it should incorporate the actual path to the actual file.  The script certainly knows the correct path.
- Ditto for `insert_key_file_path`
- An even more important improvement:  To obtain the desired server behavior, the chain.pem file is required.  The example file should contain all three, not just the first two:

```
        SSLCertificateFile      /etc/letsencrypt/live/xxx.av8n.com/cert.pem
        SSLCertificateKeyFile   /etc/letsencrypt/live/xxx.av8n.com/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/xxx.av8n.com/chain.pem
```
- There are ways of consolidating this to two directives, but leaving it unconsolidated works fine.
- By the same token, the "congratulations" message on the controlling terminal should mention all the relevant .pem files, not just fullchain.pem.
- The "congratulations" message should mention that the example file has been created and can be taken as a suggestion for how to configure the server.  This is required by basic UI design principles. It is utterly pointless to create this file if the user doesn't know it exists.
- The documentation for   `./letsencrypt-auto certonly`  should tell the user to expect this file to be created.  Again, this is a basic UI design issue.
#### Details

```
:; git show HEAD
commit de182946b5cf09a3486f38d3df0c43e2280b3654

:; ./letsencrypt-auto --version
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --version
letsencrypt 0.0.0.dev20151104

:; uname -a
Linux cloud 3.11.4+ #11 Fri Oct 11 05:39:29 PDT 2013 x86_64 x86_64 x86_64 GNU/Linux

:; lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by pde** [comment] 2015-11-04 21:32
@JohnDenker @jdkasten was this new config file placed in `sites-available` or `sites-enabled`?  My understanding is that such a file should not be generated by `letsencrypt certonly` ... it would need to be `letsencrypt`, `letsencrypt run` (those two are equivalent) or `letsencrypt install`.

**Comment by JohnDenker** [comment] 2015-11-04 21:46
In answer to your question, the file is created in sites-available.   This struck me as "unexpected" behavior but it is not entirely "undesired" behavior.  The file was useful as an example.  It would have been more useful if it had been more complete and more correct.

More specifically, here's the file that was created:

```
:; cat /etc/apache2/sites-available/default-b-le-ssl.conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName xxx.av8n.com
        DocumentRoot /var/www/xxx
        Include             /etc/apache2/sites-available/generic.conf
SSLCertificateFile insert_cert_file_path
SSLCertificateKeyFile insert_key_file_path
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by JohnDenker** [comment] 2015-11-04 22:29
In answer to your other question, I am not entirely sure what command created that file. I just retried the "certonly" command and it did not create the file.   It may be that I inadvertently typed some other command at some point, but 

The other parts of the original comment remain valid:  
 * Most importantly, if/whenever such a file is created, it would be better to model it on the prior configuration of port 443 (not 80).
 * Such a file is useful as a model, even when "certonly" behavior is requested.
 * It could be argued that the sites-available directory is not the best location for such a file, but there remain lots of other possible locations.  If a file isn't appropriate, the command could provide guidance via standard output.
 * The guidance should be correct and complete.

**Comment by JohnDenker** [comment] 2015-11-05 21:11
Further clarification:  It is at least ***sometimes*** true that the "certonly" command scribbles a file in the sites-available directory.  I observed this phenomenon just now, and I am quite confident that I didn't mistype anything.
```
:; ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory certonly -d www.av8n.com -d av8n.com

:; dir /etc/apache2/sites-available/default-ssl-a-le-ssl.conf
-rw-r--r-- 1 root root 411 Nov  5 13:05 /etc/apache2/sites-available/default-ssl-a-le-ssl.conf
```

I cannot state with confidence the necessary-and-sufficient conditions for this to happen, but it does sometimes happen.  I have observed it twice now.

**Comment by pde** [comment] 2015-11-06 21:28
There are quite a few things going on here:

* I suspect that the `insert_cert_file_path` line is created before the client has actually obtained a cert for you, so it doesn't actually know the real path yet.  If you run `letsencrypt install` (or use `letsencrypt run`, which combines `certonly` and `install` into a single process), these stub values will be filled out with the real cert path.
* Did you choose to run the `certonly` command because you received a recent beta invite that suggested that command line?

**Comment by pde** [comment] 2015-11-06 21:30
So there's a real bug here, which is that `certonly` shouldn't leave these files lying around.  If the user runs `install`, they should be created (not just in `sites-available` but in `sites-eanbled`) and created correctly.

**Comment by pde** [comment] 2015-11-06 21:31
As for whether they are modelled on the port 80 and port 443 vhosts... that's actually a hard question.  Some people will have an existing and correct 443 setup they wish to replace; others may have *tried* to create something on 443 but failed, so port 80 is a better starting point.  Probably starting with 443 is saner in general though.

**Comment by JohnDenker** [comment] 2015-11-08 08:28
So it looks like there is an emerging consensus.  When constructing a new configuration:
  1. Start by looking for the port 443 configuration.  If it exists, use it as the model.
  2. If there is no port 443 configuration, use the port 80 configuration if it exists.
  3. Otherwise complain that construction is not possible.

By way of contrast, the "tried and failed" scenario is not worth worrying about.  The main counterargument invokes the time-honored principle:  Garbage in, garbage out.  If the user had a syntactically incorrect configuration before calling letsencrypt-auto, why should anybody expect a correct configuration afterwards?

#### Suggestion:

It seems that conceptually there are three phases of operation.  Ideally they would be separate top-level commands:
* Certonly -- just obtain a certificate, plain and simple.
  * This can be done using a stand-alone temporary server, in which case the prior server configuration (if any) will be ignored.
  * Alternatively, this can be done using an existing working server.
* Preconfigure -- Using the old configuration as a model, this constructs a new proposed-configuration that points to the new certificate ... but leaves the old configuration undisturbed.  
  * This can be done using a standalone temporary server, but nevertheless it requires a workable old configuration, obviously.
  * Alternatively, this can be done using an existing working server.
* Install -- This replaces the old configuration with the newly constructed configuration.

#### Rationale:

To answer the question about why someone would choose certonly (or certonly + preconfigure): 

I take security seriously.  I take web server uptime seriously.  I don't have a "spare" web site to play with.  There is no way I am going to turn a piece of "beta" software loose to automatically munge the configuration on any site I care about.  I need to know exactly what's going to be done, before it gets done.

To say the same thing another way, letsencrypt needs some sort of --dry-run mode, so that users can be confident of what's going to be done, before it gets done.  Many, many system-administration tools have such a mode.  A stated goal of the project is good ***usability***.  Instilling confidence is part of the basic usability concept.

**Comment by jdkasten** [comment] 2015-11-08 23:28
@pde That bug is a duplicate of #808.

Here is the code that it uses to select a vhost.

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L237

I do agree that basing it off of a preexisting 443 vhost would be nice.  Though you have to worry about the default 443 vhosts.  (You probably don't want to model your new vhost after it)  Plus all of the various server configurations that are specific to the particular port 80 equivalent vhost.  The two would most certainly need to be merged.  Vhost selection/creation is by far the most difficult problem with Apache.

PRs are always welcome.  Also, you might wish to consider the webroot plugin as an alternative. 

Side note: If anyone would like to get up to speed on the Apache code I would love to discuss how the code works and the current issues.  (Google hangouts, phone, email, etc...)

**Comment by joohoi** [comment] 2017-09-27 13:18
This is an very old issue and a lot has been changed in certbot-apache since then. I'm very confident that this issue has been solved. If this is not the case, feel free to comment here and we'll reopen the issue.

The umbrella issue for all things regarding vhost selection is currently #3358

**Closed by joohoi** 2017-09-27 13:18 UTC
Labels: area: apache
