### ISSUE TITLE
.top domains not getting certificates

### ISSUE THREAD

**Issue by FreireAlexander** [certbot/certbot#9960] opened 2024-06-28 20:16 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output: 

sudo certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Please enter the domain name(s) you would like on your certificate (comma and/or
space separated) (Enter 'c' to cancel): mydomain.top
Requesting a certificate for mydomain.top

Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: mydomain.top
  Type:   dns
  Detail: DNS problem: server failure at resolver looking up A for mydomain.top; DNS problem: looking up AAAA for mydomain.top: DNSSEC: DNSKEY Missing

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

## Certbot's behavior differed from what I expected because:
I expected to get the ssl certification

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

[varlog.txt](https://github.com/user-attachments/files/16036460/varlog.txt)

**Comment by dotmitsu** [comment] 2024-06-29 22:06
I have the same issue. Please help somebody.
![Снимок экрана от 2024-06-30 00-21-45](https://github.com/certbot/certbot/assets/42657211/9cf9b3b2-e037-4adc-8ff2-34f7a3c83085)

**Comment by DimaVIII** [comment] 2024-06-30 09:40
I just also encounter this issue. It's known issue, Let's Encrypt staff is working on it.

https://community.letsencrypt.org/t/dns-problem-looking-up-a-for-xxx-domain-top-dnssec-dnskey-missing-no-valid-aaaa-records-found-for-xxx-domain-top/220650/29

Issue tracker: https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/667b2f1a30637f178a9534a7

**Comment by osirisinferi** [comment] 2024-07-01 08:06
As @DimaVIII mentions there seems to be an issue with the Let's Encrypt CA.

Also, the error message was from the CA itself to begin with. Certbot does not validate the hostname nor does it do anything with DNSSEC. Thus this is not a bug/issue with Certbot and as such I'll close this issue. Please follow up using the links above (but please refrain from posting "I also have this issue!" as that doesn't contribute in any way. The issue and severity are known already.

**Closed by osirisinferi** 2024-07-01 08:06 UTC

**Comment by dotmitsu** [comment] 2024-07-01 08:25
It is Let's Encrypt issue.

https://community.letsencrypt.org/t/dnskey-missing-dns-problem-on-top-domain/220151

https://community.letsencrypt.org/t/some-challenges-have-failed-when-run-certbot-certonly-standalone-d-xxxx-and-certbot-certonly-standalone-d-xxx-debug-challenges-v/220944
