### ISSUE TITLE
certbot-auto can't find libpython2.7 on rhel 6 while running bootstrap/install

### ISSUE THREAD

**Issue by Poohblah** [certbot/certbot#6906] opened 2019-04-03 20:14 UTC
## My operating system is (include version):

RHEL 6.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto, following the instructions here:

https://certbot.eff.org/lets-encrypt/centosrhel6-apache

## I ran this command and it produced this output:

```
[lonetree ~]% sudo certbot-auto --install-only      
/usr/local/bin/certbot-auto: line 282: [: error: integer expression expected
/usr/local/bin/certbot-auto: line 744: [: error: integer expression expected
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: package_upload, priorities, product-id, search-disabled-repos,
              : security, subscription-manager
Setting up Install Process
1827 packages excluded due to repository priority protections
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-51.el6.noarch already installed and latest version
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Package python-devel-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-virtualenv-12.0.7-1.el6.noarch already installed and latest version
Package python-tools-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Nothing to do
/usr/local/bin/certbot-auto: line 282: [: error: integer expression expected
/usr/local/bin/certbot-auto: line 1626: [: error: integer expression expected
python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
WARNING: unable to check for updates.
python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

## Certbot's behavior differed from what I expected because:

When checking with `ldd`, python appears to be linked properly:

```
[lonetree ~]% which python2.7
/opt/rh/python27/root/usr/bin/python2.7
[lonetree ~]% ldd $(which python2.7)
	linux-vdso.so.1 =>  (0x00007ffe7bec1000)
	libpython2.7.so.1.0 => /opt/rh/python27/root/usr/lib64/libpython2.7.so.1.0 (0x00007f7628e5c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00000039d9a00000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00000039d9e00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00000039df200000)
	libm.so.6 => /lib64/libm.so.6 (0x00000039da600000)
	libc.so.6 => /lib64/libc.so.6 (0x00000039d9600000)
	/lib64/ld-linux-x86-64.so.2 (0x00005580ece6f000)
```

and libpython2.7 exists and is in the linker path:

```
[lonetree ~]% file /opt/rh/python27/root/usr/lib64/libpython2.7.so.1.0
/opt/rh/python27/root/usr/lib64/libpython2.7.so.1.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
[lonetree ~]% echo $LD_LIBRARY_PATH
/opt/rh/python27/root/usr/lib64
```

and running python in the same shell session doesn't result in any linker errors:

```
[lonetree ~]% python2.7
Python 2.7.13 (default, Feb  8 2017, 06:30:30) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

## Here is a Certbot log showing the issue (if available):
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
n/a

**Comment by Poohblah** [comment] 2019-04-03 21:32
I got this one figured out.  `sudo` was screwing with my environment, even when using `sudo -E`.  The main issue seemed to be that `LD_LIBRARY_PATH` was getting wiped out, but even after fixing that, I was still running into environment issues like virtualenv getting really confused and trying to use the wrong Python and stuff like that.  Anyway, I ended up writing a wrapper script called `certbot-wrapper` which just sets the right environment.  Calling `sudo certbot-wrapper` works like a charm.  This is the script:

```
#!/bin/bash

source /opt/rh/python27/enable

/usr/local/bin/certbot-auto $@
```

Leaving this open since I'm not sure whether the certbot team thinks it's worth updating the install documentation based on any of the information here.

**Comment by bmw** [comment] 2019-04-05 00:10
Sorry for the trouble @Poohblah! I'm glad you got certbot-auto working with Python 2.7 on RHEL 6.

I don't think I'm going to change any of our documentation though because I don't think Python 2.7 from SCL is normally put into your `PATH` unless you run `source /opt/rh/python27/enable` and when only the OS default of Python 2.6 is found in your `PATH`, certbot-auto walks you through installing Python 3. Because of that, I'm closing this issue, but if you think I misunderstood the problem, feel free to let me know and I'll consider reopening it.

**Comment by Poohblah** [comment] 2019-05-16 20:45
I just think that if you're following the install documentation for your platform, the instructions should "just work" and shouldn't require going on a wild goose chase.  Based on my experience, the instructions don't "just work" for RHEL 6 - certbot-auto doesn't work with the default version of Python on RHEL 6 and so a different version needs to be installed, which leads to issues like the ones reported here.

**Comment by bmw** [comment] 2019-05-17 00:39
If you can still reproduce the problem, what happens if you don't run `certbot-auto` with `sudo`? certbot-auto calls `sudo` internally when it is needed and I think it may preserve all of the environment variables you need.

If this is the case, one solution here may be just be updating our instructions to tell people to run `certbot-auto` without `sudo`.

**Comment by Poohblah** [comment] 2019-05-20 22:31
Spun up a fresh RHEL 6 VM for testing; running without sudo works just fine:
```
[vagrant@cub_rh6 ~]$ wget https://dl.eff.org/certbot-auto
--2019-05-20 16:24:56--  https://dl.eff.org/certbot-auto
Resolving dl.eff.org... 151.101.68.201, 2a04:4e42:10::201
Connecting to dl.eff.org|151.101.68.201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68023 (66K) [application/octet-stream]
Saving to: “certbot-auto”

100%[================================================================>] 68,023      --.-K/s   in 0.02s   

2019-05-20 16:24:56 (3.39 MB/s) - “certbot-auto” saved [68023/68023]

[vagrant@cub_rh6 ~]$ sudo mv certbot-auto /usr/local/bin/certbot-auto
[vagrant@cub_rh6 ~]$ sudo chown root /usr/local/bin/certbot-auto
[vagrant@cub_rh6 ~]$ sudo chmod 0755 /usr/local/bin/certbot-auto
[vagrant@cub_rh6 ~]$ which certbot-auto
/usr/local/bin/certbot-auto
[vagrant@cub_rh6 ~]$ certbot-auto --install-only
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Bootstrapping dependencies for RedHat-based OSes that will use Python3... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: rhnplugin, search-disabled-repos, security
This system is not registered with RHN Classic or RHN Satellite.
You can use rhn_register to register.
RHN Satellite or RHN Classic support will be disabled.
Setting up Install Process
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
No package libffi-devel available.
Package redhat-rpm-config-9.0.3-51.el6.noarch already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package ca-certificates.noarch 0:2015.2.6-65.0.1.el6_7 will be updated
---> Package ca-certificates.noarch 0:2018.2.22-65.1.el6 will be an update
---> Package gcc.x86_64 0:4.4.7-17.el6 will be updated
--> Processing Dependency: gcc = 4.4.7-17.el6 for package: gcc-java-4.4.7-17.el6.x86_64
--> Processing Dependency: gcc = 4.4.7-17.el6 for package: gcc-gfortran-4.4.7-17.el6.x86_64
--> Processing Dependency: gcc = 4.4.7-17.el6 for package: gcc-c++-4.4.7-17.el6.x86_64
---> Package gcc.x86_64 0:4.4.7-23.el6 will be an update
--> Processing Dependency: cpp = 4.4.7-23.el6 for package: gcc-4.4.7-23.el6.x86_64
--> Processing Dependency: libgomp = 4.4.7-23.el6 for package: gcc-4.4.7-23.el6.x86_64
--> Processing Dependency: libgcc >= 4.4.7-23.el6 for package: gcc-4.4.7-23.el6.x86_64
---> Package openssl.x86_64 0:1.0.1e-48.el6_8.1 will be updated
---> Package openssl.x86_64 0:1.0.1e-57.el6 will be an update
---> Package openssl-devel.x86_64 0:1.0.1e-48.el6_8.1 will be updated
---> Package openssl-devel.x86_64 0:1.0.1e-57.el6 will be an update
---> Package python34.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: python34-libs(x86-64) = 3.4.10-1.el6 for package: python34-3.4.10-1.el6.x86_64
--> Processing Dependency: libpython3.4m.so.1.0()(64bit) for package: python34-3.4.10-1.el6.x86_64
---> Package python34-devel.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: python-rpm-macros for package: python34-devel-3.4.10-1.el6.x86_64
--> Processing Dependency: python3-rpm-macros for package: python34-devel-3.4.10-1.el6.x86_64
---> Package python34-tools.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: python34-tkinter = 3.4.10-1.el6 for package: python34-tools-3.4.10-1.el6.x86_64
--> Running transaction check
---> Package cpp.x86_64 0:4.4.7-17.el6 will be updated
---> Package cpp.x86_64 0:4.4.7-23.el6 will be an update
---> Package gcc-c++.x86_64 0:4.4.7-17.el6 will be updated
---> Package gcc-c++.x86_64 0:4.4.7-23.el6 will be an update
--> Processing Dependency: libstdc++ = 4.4.7-23.el6 for package: gcc-c++-4.4.7-23.el6.x86_64
--> Processing Dependency: libstdc++-devel = 4.4.7-23.el6 for package: gcc-c++-4.4.7-23.el6.x86_64
---> Package gcc-gfortran.x86_64 0:4.4.7-17.el6 will be updated
---> Package gcc-gfortran.x86_64 0:4.4.7-23.el6 will be an update
--> Processing Dependency: libgfortran = 4.4.7-23.el6 for package: gcc-gfortran-4.4.7-23.el6.x86_64
---> Package gcc-java.x86_64 0:4.4.7-17.el6 will be updated
---> Package gcc-java.x86_64 0:4.4.7-23.el6 will be an update
--> Processing Dependency: libgcj = 4.4.7-23.el6 for package: gcc-java-4.4.7-23.el6.x86_64
--> Processing Dependency: libgcj-devel = 4.4.7-23.el6 for package: gcc-java-4.4.7-23.el6.x86_64
---> Package libgcc.i686 0:4.4.7-17.el6 will be updated
---> Package libgcc.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgcc.i686 0:4.4.7-23.el6 will be an update
---> Package libgcc.x86_64 0:4.4.7-23.el6 will be an update
---> Package libgomp.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgomp.x86_64 0:4.4.7-23.el6 will be an update
---> Package python-rpm-macros.noarch 0:3-14.el6 will be installed
--> Processing Dependency: python-srpm-macros for package: python-rpm-macros-3-14.el6.noarch
---> Package python3-rpm-macros.noarch 0:3-14.el6 will be installed
---> Package python34-libs.x86_64 0:3.4.10-1.el6 will be installed
---> Package python34-tkinter.x86_64 0:3.4.10-1.el6 will be installed
--> Processing Dependency: libtk8.5.so()(64bit) for package: python34-tkinter-3.4.10-1.el6.x86_64
--> Running transaction check
---> Package libgcj.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgcj.x86_64 0:4.4.7-23.el6 will be an update
---> Package libgcj-devel.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgcj-devel.x86_64 0:4.4.7-23.el6 will be an update
---> Package libgfortran.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgfortran.x86_64 0:4.4.7-23.el6 will be an update
---> Package libstdc++.x86_64 0:4.4.7-17.el6 will be updated
---> Package libstdc++.x86_64 0:4.4.7-23.el6 will be an update
---> Package libstdc++-devel.x86_64 0:4.4.7-17.el6 will be updated
---> Package libstdc++-devel.x86_64 0:4.4.7-23.el6 will be an update
---> Package python-srpm-macros.noarch 0:3-14.el6 will be installed
---> Package tk.x86_64 1:8.5.7-5.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==========================================================================================================
 Package                   Arch          Version                     Repository                      Size
==========================================================================================================
Installing:
 python34                  x86_64        3.4.10-1.el6                epel                            51 k
 python34-devel            x86_64        3.4.10-1.el6                epel                           186 k
 python34-tools            x86_64        3.4.10-1.el6                epel                           426 k
Updating:
 ca-certificates           noarch        2018.2.22-65.1.el6          rhel-6-workstation-rpms        931 k
 gcc                       x86_64        4.4.7-23.el6                rhel-6-workstation-rpms         10 M
 openssl                   x86_64        1.0.1e-57.el6               rhel-6-workstation-rpms        1.5 M
 openssl-devel             x86_64        1.0.1e-57.el6               rhel-6-workstation-rpms        1.2 M
Installing for dependencies:
 python-rpm-macros         noarch        3-14.el6                    epel                           6.6 k
 python-srpm-macros        noarch        3-14.el6                    epel                           5.8 k
 python3-rpm-macros        noarch        3-14.el6                    epel                           5.4 k
 python34-libs             x86_64        3.4.10-1.el6                epel                           8.3 M
 python34-tkinter          x86_64        3.4.10-1.el6                epel                           337 k
 tk                        x86_64        1:8.5.7-5.el6               rhel-6-workstation-rpms        1.4 M
Updating for dependencies:
 cpp                       x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        3.7 M
 gcc-c++                   x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        4.7 M
 gcc-gfortran              x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        4.7 M
 gcc-java                  x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        3.8 M
 libgcc                    i686          4.4.7-23.el6                rhel-6-workstation-rpms        115 k
 libgcc                    x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        104 k
 libgcj                    x86_64        4.4.7-23.el6                rhel-6-workstation-rpms         19 M
 libgcj-devel              x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        1.6 M
 libgfortran               x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        268 k
 libgomp                   x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        135 k
 libstdc++                 x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        296 k
 libstdc++-devel           x86_64        4.4.7-23.el6                rhel-6-workstation-rpms        1.6 M

Transaction Summary
==========================================================================================================
Install       9 Package(s)
Upgrade      16 Package(s)

Total download size: 64 M
Is this ok [y/N]: y
Downloading Packages:
(1/25): ca-certificates-2018.2.22-65.1.el6.noarch.rpm                              | 931 kB     00:00     
(2/25): cpp-4.4.7-23.el6.x86_64.rpm                                                | 3.7 MB     00:00     
(3/25): gcc-4.4.7-23.el6.x86_64.rpm                                                |  10 MB     00:01     
(4/25): gcc-c++-4.4.7-23.el6.x86_64.rpm                                            | 4.7 MB     00:00     
(5/25): gcc-gfortran-4.4.7-23.el6.x86_64.rpm                                       | 4.7 MB     00:01     
(6/25): gcc-java-4.4.7-23.el6.x86_64.rpm                                           | 3.8 MB     00:00     
(7/25): libgcc-4.4.7-23.el6.i686.rpm                                               | 115 kB     00:00     
(8/25): libgcc-4.4.7-23.el6.x86_64.rpm                                             | 104 kB     00:00     
(9/25): libgcj-4.4.7-23.el6.x86_64.rpm                                             |  19 MB     00:01     
(10/25): libgcj-devel-4.4.7-23.el6.x86_64.rpm                                      | 1.6 MB     00:00     
(11/25): libgfortran-4.4.7-23.el6.x86_64.rpm                                       | 268 kB     00:00     
(12/25): libgomp-4.4.7-23.el6.x86_64.rpm                                           | 135 kB     00:00     
(13/25): libstdc++-4.4.7-23.el6.x86_64.rpm                                         | 296 kB     00:00     
(14/25): libstdc++-devel-4.4.7-23.el6.x86_64.rpm                                   | 1.6 MB     00:00     
(15/25): openssl-1.0.1e-57.el6.x86_64.rpm                                          | 1.5 MB     00:00     
(16/25): openssl-devel-1.0.1e-57.el6.x86_64.rpm                                    | 1.2 MB     00:00     
(17/25): python-rpm-macros-3-14.el6.noarch.rpm                                     | 6.6 kB     00:00     
(18/25): python-srpm-macros-3-14.el6.noarch.rpm                                    | 5.8 kB     00:00     
(19/25): python3-rpm-macros-3-14.el6.noarch.rpm                                    | 5.4 kB     00:00     
(20/25): python34-3.4.10-1.el6.x86_64.rpm                                          |  51 kB     00:00     
(21/25): python34-devel-3.4.10-1.el6.x86_64.rpm                                    | 186 kB     00:00     
(22/25): python34-libs-3.4.10-1.el6.x86_64.rpm                                     | 8.3 MB     00:00     
(23/25): python34-tkinter-3.4.10-1.el6.x86_64.rpm                                  | 337 kB     00:00     
(24/25): python34-tools-3.4.10-1.el6.x86_64.rpm                                    | 426 kB     00:00     
(25/25): tk-8.5.7-5.el6.x86_64.rpm                                                 | 1.4 MB     00:00     
----------------------------------------------------------------------------------------------------------
Total                                                                     3.5 MB/s |  64 MB     00:18     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Updating   : libgcc-4.4.7-23.el6.x86_64                                                            1/41 
  Updating   : libstdc++-4.4.7-23.el6.x86_64                                                         2/41 
  Updating   : libgcj-4.4.7-23.el6.x86_64                                                            3/41 
  Updating   : libgcj-devel-4.4.7-23.el6.x86_64                                                      4/41 
  Updating   : libstdc++-devel-4.4.7-23.el6.x86_64                                                   5/41 
  Updating   : cpp-4.4.7-23.el6.x86_64                                                               6/41 
  Updating   : ca-certificates-2018.2.22-65.1.el6.noarch                                             7/41 
warning: /etc/pki/java/cacerts created as /etc/pki/java/cacerts.rpmnew
warning: /etc/pki/tls/certs/ca-bundle.crt created as /etc/pki/tls/certs/ca-bundle.crt.rpmnew
warning: /etc/pki/tls/certs/ca-bundle.trust.crt created as /etc/pki/tls/certs/ca-bundle.trust.crt.rpmnew
p11-kit: duplicate 'COMODO RSA Certification Authority' certificate found in: ca-bundle.legacy.crt
p11-kit: duplicate 'COMODO RSA Certification Authority' certificate found in: ca-bundle.legacy.crt
p11-kit: duplicate 'COMODO RSA Certification Authority' certificate found in: ca-bundle.legacy.crt
p11-kit: duplicate 'COMODO RSA Certification Authority' certificate found in: ca-bundle.legacy.crt
p11-kit: duplicate 'COMODO RSA Certification Authority' certificate found in: ca-bundle.legacy.crt
  Updating   : openssl-1.0.1e-57.el6.x86_64                                                          8/41 
  Installing : python34-libs-3.4.10-1.el6.x86_64                                                     9/41 
  Installing : python34-3.4.10-1.el6.x86_64                                                         10/41 
  Installing : 1:tk-8.5.7-5.el6.x86_64                                                              11/41 
  Installing : python34-tkinter-3.4.10-1.el6.x86_64                                                 12/41 
  Updating   : libgfortran-4.4.7-23.el6.x86_64                                                      13/41 
  Updating   : libgomp-4.4.7-23.el6.x86_64                                                          14/41 
  Updating   : gcc-4.4.7-23.el6.x86_64                                                              15/41 
  Installing : python3-rpm-macros-3-14.el6.noarch                                                   16/41 
  Installing : python-srpm-macros-3-14.el6.noarch                                                   17/41 
  Installing : python-rpm-macros-3-14.el6.noarch                                                    18/41 
  Installing : python34-devel-3.4.10-1.el6.x86_64                                                   19/41 
  Updating   : gcc-c++-4.4.7-23.el6.x86_64                                                          20/41 
  Updating   : gcc-gfortran-4.4.7-23.el6.x86_64                                                     21/41 
  Updating   : gcc-java-4.4.7-23.el6.x86_64                                                         22/41 
  Installing : python34-tools-3.4.10-1.el6.x86_64                                                   23/41 
  Updating   : openssl-devel-1.0.1e-57.el6.x86_64                                                   24/41 
  Updating   : libgcc-4.4.7-23.el6.i686                                                             25/41 
  Cleanup    : openssl-devel-1.0.1e-48.el6_8.1.x86_64                                               26/41 
  Cleanup    : libgcc-4.4.7-17.el6                                                                  27/41 
  Cleanup    : gcc-java-4.4.7-17.el6.x86_64                                                         28/41 
  Cleanup    : gcc-c++-4.4.7-17.el6.x86_64                                                          29/41 
  Cleanup    : gcc-gfortran-4.4.7-17.el6.x86_64                                                     30/41 
  Cleanup    : libstdc++-devel-4.4.7-17.el6.x86_64                                                  31/41 
  Cleanup    : libgcj-devel-4.4.7-17.el6.x86_64                                                     32/41 
  Cleanup    : gcc-4.4.7-17.el6.x86_64                                                              33/41 
  Cleanup    : libgcj-4.4.7-17.el6.x86_64                                                           34/41 
  Cleanup    : libstdc++-4.4.7-17.el6.x86_64                                                        35/41 
  Cleanup    : openssl-1.0.1e-48.el6_8.1.x86_64                                                     36/41 
  Cleanup    : ca-certificates-2015.2.6-65.0.1.el6_7.noarch                                         37/41 
Please ignore warnings about %{lpath}cacerts.rpmnew, they are expected as the new consolidated configuration feature is enabled
Please ignore warnings about %{lpath}ca-bundle.crt.rpmnew, they are expected as the new consolidated configuration feature is enabled
Please ignore warnings about %{lpath}ca-bundle.trust.crt.rpmnew, they are expected as the new consolidated configuration feature is enabled
  Cleanup    : libgcc-4.4.7-17.el6                                                                  38/41 
  Cleanup    : cpp-4.4.7-17.el6.x86_64                                                              39/41 
  Cleanup    : libgomp-4.4.7-17.el6.x86_64                                                          40/41 
  Cleanup    : libgfortran-4.4.7-17.el6.x86_64                                                      41/41 
  Verifying  : libgcc-4.4.7-23.el6.i686                                                              1/41 
  Verifying  : gcc-4.4.7-23.el6.x86_64                                                               2/41 
  Verifying  : python34-3.4.10-1.el6.x86_64                                                          3/41 
  Verifying  : python-srpm-macros-3-14.el6.noarch                                                    4/41 
  Verifying  : libstdc++-devel-4.4.7-23.el6.x86_64                                                   5/41 
  Verifying  : python34-tools-3.4.10-1.el6.x86_64                                                    6/41 
  Verifying  : python34-libs-3.4.10-1.el6.x86_64                                                     7/41 
  Verifying  : python3-rpm-macros-3-14.el6.noarch                                                    8/41 
  Verifying  : python34-tkinter-3.4.10-1.el6.x86_64                                                  9/41 
  Verifying  : libgomp-4.4.7-23.el6.x86_64                                                          10/41 
  Verifying  : libgfortran-4.4.7-23.el6.x86_64                                                      11/41 
  Verifying  : gcc-c++-4.4.7-23.el6.x86_64                                                          12/41 
  Verifying  : openssl-devel-1.0.1e-57.el6.x86_64                                                   13/41 
  Verifying  : 1:tk-8.5.7-5.el6.x86_64                                                              14/41 
  Verifying  : ca-certificates-2018.2.22-65.1.el6.noarch                                            15/41 
  Verifying  : gcc-gfortran-4.4.7-23.el6.x86_64                                                     16/41 
  Verifying  : libgcj-devel-4.4.7-23.el6.x86_64                                                     17/41 
  Verifying  : gcc-java-4.4.7-23.el6.x86_64                                                         18/41 
  Verifying  : python-rpm-macros-3-14.el6.noarch                                                    19/41 
  Verifying  : openssl-1.0.1e-57.el6.x86_64                                                         20/41 
  Verifying  : libstdc++-4.4.7-23.el6.x86_64                                                        21/41 
  Verifying  : python34-devel-3.4.10-1.el6.x86_64                                                   22/41 
  Verifying  : cpp-4.4.7-23.el6.x86_64                                                              23/41 
  Verifying  : libgcj-4.4.7-23.el6.x86_64                                                           24/41 
  Verifying  : libgcc-4.4.7-23.el6.x86_64                                                           25/41 
  Verifying  : gcc-java-4.4.7-17.el6.x86_64                                                         26/41 
  Verifying  : gcc-c++-4.4.7-17.el6.x86_64                                                          27/41 
  Verifying  : libstdc++-4.4.7-17.el6.x86_64                                                        28/41 
  Verifying  : libgcj-4.4.7-17.el6.x86_64                                                           29/41 
  Verifying  : cpp-4.4.7-17.el6.x86_64                                                              30/41 
  Verifying  : libgcc-4.4.7-17.el6.i686                                                             31/41 
  Verifying  : libgfortran-4.4.7-17.el6.x86_64                                                      32/41 
  Verifying  : libgcc-4.4.7-17.el6.x86_64                                                           33/41 
  Verifying  : libgcj-devel-4.4.7-17.el6.x86_64                                                     34/41 
  Verifying  : libstdc++-devel-4.4.7-17.el6.x86_64                                                  35/41 
  Verifying  : openssl-devel-1.0.1e-48.el6_8.1.x86_64                                               36/41 
  Verifying  : openssl-1.0.1e-48.el6_8.1.x86_64                                                     37/41 
  Verifying  : gcc-gfortran-4.4.7-17.el6.x86_64                                                     38/41 
  Verifying  : gcc-4.4.7-17.el6.x86_64                                                              39/41 
  Verifying  : libgomp-4.4.7-17.el6.x86_64                                                          40/41 
  Verifying  : ca-certificates-2015.2.6-65.0.1.el6_7.noarch                                         41/41 

Installed:
  python34.x86_64 0:3.4.10-1.el6                      python34-devel.x86_64 0:3.4.10-1.el6               
  python34-tools.x86_64 0:3.4.10-1.el6               

Dependency Installed:
  python-rpm-macros.noarch 0:3-14.el6                  python-srpm-macros.noarch 0:3-14.el6              
  python3-rpm-macros.noarch 0:3-14.el6                 python34-libs.x86_64 0:3.4.10-1.el6               
  python34-tkinter.x86_64 0:3.4.10-1.el6               tk.x86_64 1:8.5.7-5.el6                           

Updated:
  ca-certificates.noarch 0:2018.2.22-65.1.el6  gcc.x86_64 0:4.4.7-23.el6  openssl.x86_64 0:1.0.1e-57.el6 
  openssl-devel.x86_64 0:1.0.1e-57.el6        

Dependency Updated:
  cpp.x86_64 0:4.4.7-23.el6      gcc-c++.x86_64 0:4.4.7-23.el6      gcc-gfortran.x86_64 0:4.4.7-23.el6   
  gcc-java.x86_64 0:4.4.7-23.el6 libgcc.i686 0:4.4.7-23.el6         libgcc.x86_64 0:4.4.7-23.el6         
  libgcj.x86_64 0:4.4.7-23.el6   libgcj-devel.x86_64 0:4.4.7-23.el6 libgfortran.x86_64 0:4.4.7-23.el6    
  libgomp.x86_64 0:4.4.7-23.el6  libstdc++.x86_64 0:4.4.7-23.el6    libstdc++-devel.x86_64 0:4.4.7-23.el6

Complete!
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Certbot is installed.
[vagrant@cub_rh6 ~]$ certbot-auto certonly -d boguscert.example.com --webroot -w /tmp --register-unsafely-without-email
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Registering without email!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server at
https://acme-v02.api.letsencrypt.org/directory
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(A)gree/(C)ancel:
```

**Comment by bmw** [comment] 2019-05-20 22:43
Is installing Python 3.4 the behavior you expected though?

**Comment by Poohblah** [comment] 2019-05-20 22:44
Ah nevermind disregard that post.  I didn't fully read your request.

So I played around a bit and basically I'm able to trigger the issue on any system that has a non-default Python installation in `$PATH`.  When that's the case, whether or not I use sudo or let certbot-auto internally call sudo, it doesn't seem to make a difference:

```
[hendrenj@destroyer]~% which python
/usr/local/python/bin/python
[hendrenj@destroyer]~% python --version
Python 2.7.13 :: Anaconda custom (64-bit)
```
```
[hendrenj@destroyer]~% ./certbot-auto --install-only
Requesting to rerun ./certbot-auto with root privileges...
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: package_upload, product-id, refresh-packagekit, search-disabled-repos, subscription-
              : manager
Setting up Install Process
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-51.el6.noarch already installed and latest version
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Package python-devel-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-virtualenv-12.0.7-1.el6.noarch already installed and latest version
Package python-tools-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Package 1:mod_ssl-2.2.15-69.el6.x86_64 already installed and latest version
Nothing to do
./certbot-auto has insecure permissions!
To learn how to fix them, visit https://community.letsencrypt.org/t/certbot-auto-deployment-best-practices/91979/
Creating virtual environment...
/opt/eff.org/certbot/venv/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/local/python/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/local/python/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 100
```

```
[hendrenj@destroyer]~% sudo ./certbot-auto --install-only
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: package_upload, product-id, refresh-packagekit, search-disabled-repos, subscription-
              : manager
Setting up Install Process
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-57.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-51.el6.noarch already installed and latest version
Package ca-certificates-2018.2.22-65.1.el6.noarch already installed and latest version
Package python-devel-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-virtualenv-12.0.7-1.el6.noarch already installed and latest version
Package python-tools-2.6.6-66.el6_8.x86_64 already installed and latest version
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Package 1:mod_ssl-2.2.15-69.el6.x86_64 already installed and latest version
Nothing to do
./certbot-auto has insecure permissions!
To learn how to fix them, visit https://community.letsencrypt.org/t/certbot-auto-deployment-best-practices/91979/
Creating virtual environment...
/opt/eff.org/certbot/venv/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/local/python/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/local/python/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 100
```

So I think the installation instructions seem to be fine for a fresh-out-of-the-box RHEL 6 system, but for something that already has another Python in `$PATH`, it doesn't seem to work so well.

**Comment by bmw** [comment] 2019-05-20 23:02
I think the error with conda is slightly different (as far as I can tell, `virtualenv` with Python from Conda is broken), but it's good to know about both issues regardless.

To be honest, we probably won't get to this as RHEL 6 is EOL'd next year and we're trying to replace `certbot-auto` (and have stopped accepting changes to the script outside of regressions), but we'll keep this open just in case.

**Comment by Poohblah** [comment] 2019-05-20 23:20
Ok, sounds good!  Thanks for your help!

**Closed** 2020-06-19 02:33 UTC
Labels: area: certbot-auto, area: fedora / redhat / CentOS, needs-update
