### ISSUE TITLE
Recognize inherited ssl directives

### ISSUE THREAD

**Issue by HepplerDotNet** [certbot/certbot#583] opened 2015-07-02 09:13 UTC
WARNING:letsencrypt_nginx.configurator:Cannot find a cert or key directive in /etc/nginx/vhosts.d/gowide.de.conf for set(['www.gowide.de', 'aws.gowide.de', 'gowide.de']). VirtualHost was not modified.

My gowide.de.conf: https://pastebin.mozilla.org/8838346
Lines 5&6 point to a selfsigned cert.

Command i run:

```
letsencrypt -d www.gowide.de -d gowide.de -d aws.gowide.de -e -t run
```

**Comment by jsha** [comment] 2015-07-09 20:52
@diracdeltas can you look at this one?

**Comment by diracdeltas** [comment] 2015-07-12 01:58
Will look into it. The plugin doesn't expect the NGINX config to already have an SSL configuration defined, so this sort of error is expected (unfortunately).

**Comment by PatrickHeppler** [comment] 2015-07-12 08:45
It works if I have only one server name, even with already enabled SSL.
https://pastebin.mozilla.org/8839291
This config works if I run 
```
letsencrypt -d www.gowide.de -d gowide.de -d aws.gowide.de -e -t run
```
I don't get any errors.  ssl_certificate and ssl_certificate_key get replaced with correct path to the letsencrypt certs in all 3 server blocks.

**Comment by bmw** [comment] 2016-08-17 22:35
I'm unable to repo this issue. Unfortunately, the pastebins above have expired, but taking a simple configuration file and adding multiple server names, Certbot correctly modifies the file.

If you can still reproduce this issue, can you either create a new pastebin or paste the configuration file's contents into this issue?

**Comment by pde** [comment] 2016-09-12 23:10
Closing this as unreproducible for now :(

**Comment by pde** [comment] 2016-09-12 23:10
But pinging @PatrickHeppler in case he can still reproduce :/

**Comment by johnaoss** [comment] 2017-01-13 01:04
I believe I may have reproduced this. Doing a certonly with --dry-run works perfectly fine, yet it fails on installation, stating that it was unable to install the certificate. 

Command:
`./certbot-auto run --nginx -d johnoss.com -d www.johnoss.com -d video.johnoss.com`

Output:
[Link to Gist](https://gist.github.com/johnaoss/e36c706323c701bad4ed4e2313a5f22f)

I'm unsure as to why it fails during expansion, and only for the domain I currently have a cert for (['johnoss.com']).

**Comment by ohemorange** [comment] 2017-01-13 01:11
Could you repost your Nginx config file?

**Comment by johnaoss** [comment] 2017-01-13 01:21
@ohemorange Updated previous comment with other files.

**Comment by ohemorange** [comment] 2017-01-13 01:41
Ah yup we were just talking about this the other day - hoping to get a fix in 0.11.0 (choose_vhost should always ensure all necessary ssl directives are included).

In the meantime, delete 
```
listen 443 ssl default_server;
listen [::]:443 ssl default_server;
```
from any server block that you want a cert to be installed in, then try running certbot again. So, that's lines 6-7 and 93-94 in the gist.

**Comment by silverwind** [comment] 2017-02-14 14:19
Not sure if this is the same issue, but it seems inherited `ssl_` directives are not recognized. I use a `nginx.conf` like this:

````nginx
http {
  ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;

  server {
    server_name example.com;
  }

  server {
    server_name sub.example.com;
  }
}
````

Both `server` statements are sharing the same certificates of the parent and I validate both domains with certbot. When I run `certbot --nginx`, it shows this error after validation:

````
Cannot find a cert or key directive in /etc/nginx/nginx.conf for set(['example.com']). VirtualHost was not modified.
````

**Comment by ohemorange** [comment] 2017-02-18 01:48
Sorry about the earlier promise of a fix - this might have fixed the original problem, but without more info we can't be sure.

There are two other problems here, though:
- we don't handle inherited directives at all
- we can't currently handle updating directives when the original directives were included from another file, and I'm honestly not sure we should.

@johnaoss : if you copy and paste the contents of snippets/ssl-example.com.conf and snippets/ssl-params.conf; directly into the default config file, certbot should work correctly.

**Comment by SwartzCr** [comment] 2017-04-27 20:57
@ohemorange any idea if this is resolved and closable now?

**Comment by ohemorange** [comment] 2017-04-27 21:44
It's not, but I should note that the only remaining AI here is to recognize inherited directives when parsing configs, which is a wishlist item since it's not the recommended use case.

We shouldn't be modifying directives included from other files.

We probably also shouldn't try to add new, better, ssl-related directives to an already-ssl-enabled server block. Not because there's no benefit, but because it's more important to be able to update things like ciphersuites on `renew`.

**Comment by ohemorange** [comment] 2019-06-12 23:15
hey @sydneyli, do you think this will happen automatically in the new parser?

**Comment by sydneyli** [comment] 2019-06-12 23:43
> hey @sydneyli, do you think this will happen automatically in the new parser?

It won't happen automatically (I didn't realize you could inherit directives in Nginx) but w/ the new parser it should be a easy fix (<10 line, not counting tests).

**Closed** 2023-07-18 02:08 UTC
Labels: bug, area: nginx, priority: unplanned, needs-update
