### ISSUE TITLE
u'...' markers shouldn't be shown

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4192] opened 2017-02-08 19:11 UTC
py2.7 rhel6.6 cb 0.11.1
```py
# /root/bin/certbot-auto certonly --cert-name preview.example.com -d preview.example.com
...
Confirm that you intend to update certificate preview.example.com to include
domains [u'preview.example.com']. Note that it previously contained domains
[u'preview.example.com', u'preview.example.org',
u'www.preview.example.org', u'preview.example.net',
u'refresh.example.net', u'test.example.net'].
```

**Comment by SwartzCr** [comment] 2017-02-08 21:23
@jsoref do you think you could explain a little more about what you think the issue is and how we can solve it? I'm not sure I follow (sorry!)

**Comment by jsha** [comment] 2017-02-08 22:37
I think the expected output is:

```
Confirm that you intend to update certificate preview.example.com to include
domains ['preview.example.com']. Note that it previously contained domains
['preview.example.com', 'preview.example.org',
'www.preview.example.org', 'preview.example.net',
'refresh.example.net', 'test.example.net'].
```

**Comment by aaroncohen** [comment] 2017-05-22 18:42
Looking at this in PyCon sprints. It would appear that display of multiple domains is inconsistent...in this case we display what is more-or-less a python-style representation of the list, elsewhere we just display them as comma separated, and not as part of a combined paragraph.

As this is the only example of this style of formatting I can find, I'm going to take the approach of making it consistent with other cases.

**Comment by SwartzCr** [comment] 2017-05-24 19:39
Closing because #4709 was merged

**Closed by SwartzCr** 2017-05-24 19:39 UTC
Labels: area: ui / ux, Good Volunteer Task, low priority, sf-python-sprint
