### ISSUE TITLE
aug.match throws out unsaved augeas changes - temp save before calling?

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#2265] opened 2016-01-22 20:08 UTC
as seen in #2228 we are having some errors where directives are added and then lost before saving due to aug.match being called. One place where aug.match is called is in configurator.find_dir()

This is pretty unexpected behavior, and will likely cause problems down the line. It would be nice if before aug.match is called we check to see if there are unsaved changes and save them.

I've also opened an issue with python-augeas about this behavior: https://github.com/hercules-team/python-augeas/issues/15

**Comment by bmw** [comment] 2016-01-22 20:16
While saving the changes might be a good solution, we need to be careful here. If the save is temporary, it will be reverted on the next run of the client. If the save is permanent, it will create a new checkpoint causing our current rollback mechanisms not work. These are certainly solvable problems, however.

Another approach is to just check/assert that there are no unsaved changes before calling `match`.

**Comment by SwartzCr** [comment] 2016-01-22 20:28
otherwise do what? error out?

**Comment by bmw** [comment] 2016-01-22 20:35
Yeah. I think we could just `assert` that there are no unsaved changes before calling `match`. It'd force us to make sure we're saving everything correctly and not losing changes anywhere else. It'd require a lot of testing though to make sure we're not going to randomly fail for people.

**Comment by joohoi** [comment] 2017-09-27 12:42
I dug in to this, and looks like it's not actually aug.match, but the parse_file under the hood. In example case of find_dir the call stack is (if the stars align, and the issue is exposed): `find_dir -> _get_include_path -> parse_file -> aug.load` which reloads the Augeas DOM, hence discarding the changes. This got fixed in #4104 , so closing the issue.

**Closed by joohoi** 2017-09-27 12:42 UTC
Labels: area: apache, area: code health
