### ISSUE TITLE
Bundle fullchain and privkey (weechat, quassel)

### ISSUE THREAD

**Issue by evrial** [certbot/certbot#1250] opened 2015-10-31 09:16 UTC
See docs here:
https://www.weechat.org/files/doc/stable/weechat_user.en.html#relay_ssl

Some software uses just one file, but `cat` each renew would be a pain.

**Comment by jleclanche** [comment] 2015-10-31 09:17
quassel core uses the same format: https://www.youtube.com/watch?v=yjpGh9ZDECs

**Comment by jleclanche** [comment] 2015-10-31 09:17
quassel core uses the same format: http://quassel-irc.org/faq/cert

**Comment by kuba** [comment] 2015-11-01 19:29
this might be a duplicate of #1201, but I'm not sure

**Comment by jleclanche** [comment] 2015-11-01 19:31
Yes it is.

**Comment by kuba** [comment] 2015-11-01 19:43
It's not, fixing titles.

**Comment by pataquets** [comment] 2016-02-18 17:43
Tomcat also needs fullchain + privkey file.

**Comment by jleclanche** [comment] 2016-02-27 20:11
@kuba is this on track for a fix? It's super frustrating having to update my quassel key every few months.

**Comment by JoKeyser** [comment] 2018-02-24 19:48
Until fixed, a good workaround would be to define a renew-hook that creates the necessary files upon successful certificate renewal. That way you don't have to re-do that manually.

**Comment by sydneyli** [comment] 2018-10-25 19:16
Given that the most discussion is on #5087 about this exact issue, I'm closing this in favor of that one.

**Closed by sydneyli** 2018-10-25 19:16 UTC
Labels: area: cert management, feature request
