### ISSUE TITLE
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by bartvollebregt** [certbot/certbot#2677] opened 2016-03-17 09:43 UTC
Hi there,

When I try to request a certificate using the ./letsencrypt --apache command I get the following error:

> An unexpected error occurred:
> ConnectionError: ('Connection aborted.', BadStatusLine("''",))
> Please see the logfiles in /var/log/letsencrypt for more details.

This happens after accepting the Terms of Service.

The log file reports the following:

> 2016-03-17 09:34:18,681:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
> 2016-03-17 09:34:38,720:DEBUG:letsencrypt.cli:Exiting abnormally:
> Traceback (most recent call last):
>   File "./letsencrypt", line 11, in <module>
>     sys.exit(main())
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1993, in main
>     return config.func(config, plugins)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 661, in run
>     le_client = _init_le_client(config, authenticator, installer)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 207, in _init_le_client
>     acc, acme = _determine_account(config)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 192, in _determine_account
>     config, account_storage, tos_cb=_tos_cb)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 125, in register
>     regr = acme.agree_to_tos(regr)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 164, in agree_to_tos
>     regr.update(body=regr.body.update(agreement=regr.terms_of_service)))
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 137, in update_registration
>     regr, body=messages.UpdateRegistration(*_dict(update)))
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 112, in _send_recv_regr
>     response = self.net.post(regr.uri, body)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 650, in post
>     response = self._send_request('POST', url, data=data, *_kwargs)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 609, in _send_request
>     response = requests.request(method, url, _args, *_kwargs)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/api.py", line 53, in request
>     return session.request(method=method, url=url, *_kwargs)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
>     r = adapter.send(request, **kwargs)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
>     raise ConnectionError(err, request=request)
> ConnectionError: ('Connection aborted.', BadStatusLine("''",))

I'm running Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-79-generic x86_64)

A wget to https://acme-v01.api.letsencrypt.org works perfectly fine and when I try to post the json data (which is also in the log file) with Postman it will return the certificate details perfectly fine.

**Comment by pde** [comment] 2016-03-17 20:56
@kuba, are you interested in taking a look at this?

**Comment by artyom-ace** [comment] 2016-06-28 14:17
I have a similar problem. I'm running Debian 8 (Linux version 3.16.0-4-amd64, gcc version 4.8.4 Debian 4.8.4-1). Im trying different run methods and version of certboot (installed by apt-get install and downloading from here). Everywhere is the same problem.
My web server with nginx is behind a router. Only ports 80 and 443 on external IP mapping to Web server.
What information do you provide to solve the problem?
The log file reports:

> 2016-06-28 13:06:11,383:DEBUG:certbot.main:Root logging level set at 30
2016-06-28 13:06:11,383:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-06-28 13:06:11,384:DEBUG:certbot.main:certbot version: 0.8.0
2016-06-28 13:06:11,384:DEBUG:certbot.main:Arguments: []
2016-06-28 13:06:11,384:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-06-28 13:06:11,386:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-06-28 13:06:11,388:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f4103f18950>
Prep: True
2016-06-28 13:06:11,389:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f4103f18950> and installer None
2016-06-28 13:06:12,025:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-06-28 13:06:12,041:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-06-28 13:06:12,549:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-06-28 13:06:12,550:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Tue, 28 Jun 2016 13:03:51 GMT', 'Boulder-Request-Id': 'kXVotm-9F9Y7QmlhqJvNX8jbzb_fCu8y9BfuBwpLlKc', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 28 Jun 2016 13:03:51 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'INycUlDs0QLBDSdnODnUV7gS_2QdEm6CGdmdSK-w-lg'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-06-28 13:06:12,550:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Tue, 28 Jun 2016 13:03:51 GMT', 'Boulder-Request-Id': 'kXVotm-9F9Y7QmlhqJvNX8jbzb_fCu8y9BfuBwpLlKc', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 28 Jun 2016 13:03:51 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'INycUlDs0QLBDSdnODnUV7gS_2QdEm6CGdmdSK-w-lg'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-06-28 13:06:12,550:DEBUG:root:Requesting fresh nonce
2016-06-28 13:06:12,550:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {}
2016-06-28 13:06:12,756:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-reg HTTP/1.1" 405 0
2016-06-28 13:06:12,757:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': 'RbFQ-JmOlUMPuWRobpB7IkZAhUrRYcf5NHCMgbGRlhQ', 'Expires': 'Tue, 28 Jun 2016 13:03:51 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 28 Jun 2016 13:03:51 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'f1rpDzc-KWHWVDzwWCUdMgaF__6DiT4aXBWLorexD50'}. Content: ''
2016-06-28 13:06:12,757:DEBUG:acme.client:Storing nonce: '\x7fZ\xe9\x0f7>)a\xd6T<\xf0X%\x1d2\x06\x85\xff\xfe\x83\x89>\x1a\\\x15\x8b\xa2\xb7\xb1\x0f\x9d'
2016-06-28 13:06:12,757:DEBUG:acme.jose.json_util:Omitted empty fields: agreement=None, certificates=None, authorizations=None, key=None
2016-06-28 13:06:12,757:DEBUG:acme.client:Serialized JSON: {"contact": ["mailto:info@mydomain.com"], "resource": "new-reg"}
2016-06-28 13:06:12,759:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, alg=None, jku=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None, jwk=None
2016-06-28 13:06:12,769:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, nonce=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None
2016-06-28 13:06:12,769:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "33-7PUzWSO_4PNbNnQTzmQS8LRjqBW_OCDfWeisFdOUTbdbNUdxCM816aVRmg1vwNOKootMn2O7Hf3WXtEZWF-ujAqbE7mAg7KlLnTCmV1UgKtme2lMuXyMqv_UMIJFRQbLHGahY9CyaMctHDzmu1QAPJBGNOVS1_TCyoU0RfTBQB4hN0b0D1pf8nH8PYv4XtCbR-4BDEgM6eS5syEg0SMjn9aVDzBtjkHELQz5XMySwLvGI8TcjfMWv_8-lenFM8cCPcavXh2RJKMJFmcy342ViGI4tKyIyLVSve-AR12c-2sQ_69VRHgOdvhKjtRG2wkOqr_uxTHkwt1D0kor2X9y7hzaxU6oaF8n45CHH4u4ax2P6hUApT3xB6PW76XmG7ElqgrSdMY36yyuMHBfE5p1Pux1AhEfoHU5YgB4aw-F3qkG1QzmLp7D8slJJsRSZ6YwymJcMOXZtr2WB3eZFKRWbxgBbPjX2neGNUDnLB2e2FunVhulmwsV38WkJ0VYzTovYSClxUSoyg3oFh7fWGTkrc-g_jimhUtr5oLRDDSfvSzZ56wX4TccXBDKTzniu0daXNpADf4cLpy7Ziof2bbto-ccXJiTrJT5VzZd3UnijNqwz54nZAUj2frx1h_BwGUTT3YpdCHckIHE6kNCIjP0zwQQq4BBMKdF0qGEUVgc"}}, "protected": "eyJub25jZSI6ICJmMXJwRHpjLUtXSFdWRHp3V0NVZE1nYUZfXzZEaVQ0YVhCV0xvcmV4RDUwIn0", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86aW5mb0B5YS10YXhpLmNvbSJdLCAicmVzb3VyY2UiOiAibmV3LXJlZyJ9", "signature": "KKawCX2X2DFbgFGAP0xjJgcaXkb9Xli6AkLnh99QNF7y4JzdW0pDRAWtap7DUVq94ljxD3HJvk01nWt4kahxYjzmSjyTaS8CVWUe0vPz6iBwWnGLhW8kGM4OQGQzYupbnJR9fmAHzpvRQguTkdt6LCKoSh1hUFCagFt6nEDeiICrg3t1uN8awrCN50pxSK3ZxBuNFs2ro95wKLDfHM9YLNZnTqDCIo6MGneAzA6M94Lx3PCcX6mrIuuoK1LDTGonTo3fOMiUzmAPJFYwYc4JoR9vxqFpcfnAz6gKQGQ1i6yXal_3QOBRGWkhTdD1TB0Xv6syBBxLmEokROAMe9cK9UIt0NKin1pKrTkgvM5JRc_RezKgK77GbkxACiiGGYJHBLiiMwCKeXuvfyJOOtFJmdw-eW0JlFlauzXN8OIGuk5yhQVRZyKAx6ge1C6Z5w7oMkbiqyM0Hnh1kEHeyH3fmmUYKR41rLeI5af2JacZaa6laJewm1d1TZ-UUkonFeJu5TCMUJO4Xvj0sQjYqaswffKACZJ7L7pf_J4uE_NNew8M9u5xZLckmDM2UGDhdG0sZXJ0CvVT3SeAu9XL4BSdZY3zS4ULO7ef8qcG1cTWB1uKbo9T4ZTmfU4ueGYQU0eV0e-5KtgX5b-23vRRfCG4tw_zF5_1KKTooTyOC38aohw"}'}
2016-06-28 13:11:13,038:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 735, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 549, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 359, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 344, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 120, in register
    regr = perform_registration(acme, config)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 150, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 98, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 654, in post
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 412, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by MFlasskamp** [comment] 2016-08-01 12:07
Same problem here with certbot (letsencrypt 0.8.1) and Ubuntu 14.04.4 LTS.
Same VPS and domains worked flawlessly on last cert update. Do you need more details?

```
...
2016-08-01 11:37:23,779:INFO:certbot.auth_handler:http-01 challenge for xyz.net
2016-08-01 11:37:23,779:INFO:certbot.plugins.webroot:Using the webroot path /srv/http/letsencrypt for all unmatched domains.
2016-08-01 11:37:23,779:DEBUG:certbot.plugins.webroot:Creating root challenges validation dir at /srv/http/letsencrypt/.well-known/acme-challenge
2016-08-01 11:37:23,848:DEBUG:certbot.plugins.webroot:Attempting to save validation to /srv/http/letsencrypt/.well-known/acme-challenge/UrhOzS1BvG4VGe-0BAwJ4dLVzTE1nNkXwaILTf0Qwyg
2016-08-01 11:37:23,936:INFO:certbot.auth_handler:Waiting for verification...
2016-08-01 11:37:23,936:DEBUG:acme.client:Serialized JSON: {"keyAuthorization": "UrhOzS1BvG4VGe-0BAwJ4dLVzTE1nNkXwaILTf0Qwyg.KmGCeJEhgdr_EYb_LmFYCB-xIxhbErdPkurCAXzAjII", "type": "http-01", "resource": "challenge"}
2016-08-01 11:37:23,937:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, jwk=None, x5t=None, x5tS256=None, cty=None, x5u=None, typ=None, alg=None, jku=None
2016-08-01 11:37:23,940:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, nonce=None, x5tS256=None, cty=None, x5t=None, x5u=None, typ=None, jku=None
2016-08-01 11:37:23,940:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/0sXz29FTVpx_GI7jOB9_oO8YLylFgGw4TtA3KDutcZU/210018179. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "qSx2sjI-kxOhFHrckpBvLDfW4c-NVzLkcOqIl5mM1p9EF93GwffdhPB401QLgTFm9Gzy2cBsMIQttDI4DgVOfsWO0v_Q1VM3Ah5VFBEkNy7cpGdfkbWInFfSrf3HcrIkJKC_9XwO1OdkCld7U0jSDsEru7LqOUj9obYMGGfjEEVMJ46Ka3btNkuhi1zcnCDol5yEdLG8ypy60b7ikabgVc9tFmIvIBAlIQ0p8BT6Rl5JYwn5B7BbbK24Sgf2Tdvjo5wJusozvQ-1Nx3ONcdudslACmvCKy1QIDXSrknF0qYMKVwGEiRk3oAOlWrM20dgZIUpkFCNyz7cP3ONtwsCvw"}}, "protected": "eyJub25jZSI6ICJPMWRwMEF6Snd1Tkp1eHo5MklBWEhpMlFQRnF4dEs5MkpTcGxkNTBaMThBIn0", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogIlVyaE96UzFCdkc0VkdlLTBCQXdKNGRMVnpURTFuTmtYd2FJTFRmMFF3eWcuS21HQ2VKRWhnZHJfRVliX0xtRllDQi14SXhoYkVyZFBrdXJDQVh6QWpJSSIsICJ0eXBlIjogImh0dHAtMDEiLCAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIn0", "signature": "LZpFbqBGfp2F0U9XQ3vJLCNXY1py0mpJ7KxHLpxlJOCMVzg82LguSDWicjjfkBvyf5NV82LPiIc6PnbhE6UhtVSFG9ngR__7FDqfbP5L_X8X-93I7nwCYfzaMFl88InGmDdFAXj7XHcBeS2susBVT9X3q6m4tOMAaDHC2bR7VjXs4UnwTU9qvvRFlIiGwL0WiC4E-V6hy1BAegCXuijmNEBtmyYhA_5VXFpuxRrRFrDAvwNJRJloRzuzgSkqXsKNGxXEy1lFariMtVjV8TRUDbnFTCwPG5YedGvj4CqLUT6H00pY3nynr4x_-nlu_-P5Qtk0pqMXqa8BEBq_9TchFQ"}'}
2016-08-01 11:42:24,126:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 94, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 276, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 127, in _respond
    resp, chall_update)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 151, in _send_responses
    self.acme.answer_challenge(achall.challb, resp)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 234, in answer_challenge
    response = self.net.post(challb.uri, response)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 654, in post
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by MFlasskamp** [comment] 2016-08-02 17:23
The problem seems somehow related to IPv6. After I disabled IPv6 in /etc/sysctl.conf the client was working (over IPv4).

**Comment by cmenzi** [comment] 2017-08-07 12:19
Problem still exist with (certbot 0.14.1) on CentOS Linux release 7.3.1611 (Core)

Disabling IPv6 does not solve the problem.

Any updates on this?

**Comment by ppKrauss** [comment] 2017-08-24 12:46
Same problem now at UBUNTU 16 LTS with **certbot 0.14.2**, in a DigitalOcean server.

After `certbot --nginx   --cert-name  cerName` all ok but...
```
....
tls-sni-01 challenge for www....
tls-sni-01 challenge for ...
Waiting for verification...
An unexpected error occurred:
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by mnordhoff** [comment] 2019-06-13 08:25
This still comes up on occasion:

https://community.letsencrypt.org/search?q=BadStatusLine(%22%27%27%22)%20order%3Alatest

Though some of the most recent posts were about _pip_ throwing that error while downloading packages.

Still, as a seemingly rare problem that's likely caused by network problems or transient server problems, it might not be worth pursuing.

**Comment by bmw** [comment] 2020-03-20 18:23
Yeah I think this is due to a variety of different networking issues. While maybe the error message should be improved (and if so, I'd push for it to be improved in `requests` so everyone benefits), but I otherwise think there's not much for us to do here so I'm closing this issue.

**Closed by bmw** 2020-03-20 18:23 UTC
Labels: area: acme
