### ISSUE TITLE
certbot generating/parsing/using the wrong webroot_path values

### ISSUE THREAD

**Issue by aarcane** [certbot/certbot#3447] opened 2016-08-20 22:44 UTC
So I run this command:
sudo certbot certonly --expand -w /var/www/certbot/htdocs/ -d aarcane.org -d dev.aarcane.org -d www.aarcane.org -d test.aarcane.org -d jayd.aarcane.org -d jayde.aarcane.org -d smfrench.aarcane.org -d recipewiki.aarcane.org -d 0.s.aarcane.org

and certbot generates this snippet in the config file:

webroot_path = /var/www/certbot/htdocs,
[[webroot_map]]
smfrench.aarcane.org = /var/www/certbot/htdocs
www.aarcane.org = /var/www/certbot/htdocs
dev.aarcane.org = /var/www/certbot/htdocs
jayd.aarcane.org = /var/www/certbot/htdocs
test.aarcane.org = /var/www/certbot/htdocs
aarcane.org = /var/www/certbot/htdocs
jayde.aarcane.org = /var/www/certbot/htdocs
recipewiki.aarcane.org = /var/www/certbot/htdocs
0.s.aarcane.org = /var/www/certbot/htdocs

and finally, certbot renew --dry-run -v fails with this error:

---
## Processing /etc/certbot/renewal/aarcane.org.conf

2016-08-20 15:28:18,088:INFO:certbot.renewal:Cert not due for renewal, but simulating renewal for dry run
2016-08-20 15:28:18,231:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-08-20 15:28:19,089:INFO:certbot.auth_handler:Performing the following challenges:
2016-08-20 15:28:19,090:INFO:certbot.auth_handler:http-01 challenge for aarcane.org
2016-08-20 15:28:19,090:INFO:certbot.auth_handler:http-01 challenge for 0.s.aarcane.org
2016-08-20 15:28:19,090:INFO:certbot.auth_handler:http-01 challenge for dev.aarcane.org
2016-08-20 15:28:19,091:INFO:certbot.auth_handler:http-01 challenge for jayd.aarcane.org
2016-08-20 15:28:19,091:INFO:certbot.auth_handler:http-01 challenge for jayde.aarcane.org
2016-08-20 15:28:19,091:INFO:certbot.auth_handler:http-01 challenge for recipewiki.aarcane.org
2016-08-20 15:28:19,091:INFO:certbot.auth_handler:http-01 challenge for smfrench.aarcane.org
2016-08-20 15:28:19,092:INFO:certbot.auth_handler:http-01 challenge for test.aarcane.org
2016-08-20 15:28:19,092:INFO:certbot.auth_handler:http-01 challenge for www.aarcane.org
2016-08-20 15:28:19,092:INFO:certbot.plugins.webroot:Using the webroot path /srv/www/htdocs for all unmatched domains.
2016-08-20 15:28:19,139:INFO:certbot.auth_handler:Waiting for verification...
2016-08-20 15:28:23,346:INFO:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: 0.s.aarcane.org
Type:   unauthorized
Detail: Invalid response from http://0.s.aarcane.org/.well-known/acme-challenge/cs83bDzkEEcJCy50k4W4ClMXXHLtA5BT-YChIQuNSfI: "<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>"

I'll post workarounds in comments

**Comment by aarcane** [comment] 2016-08-20 22:49
So removing the , in the config file doesn't fix the problem.  the only thing that does is manually editing the cli.ini (for me that's /etc/certbot/cli.ini for others it may be /etc/letsencrypt/cli.ini) and changing the webroot_path variable to the proper location, /var/www/certbot/htdocs .

**Comment by joohoi** [comment] 2016-08-22 07:40
The comma in the configuration variable actually is correct, it's a csv of a list of paths, in this case only one though. 

To me it looks like the actual problem is that the subdomains (in this case 0.s.aarcane.org) are actually served from a filesystem directory other than /var/www/certbot/htdocs/ or do you have a global rule for serving every request for .well-known/  from the afformentioned directory?

**Comment by aarcane** [comment] 2016-08-22 08:07
In fact I do, I have this file included from everywhere in nginx.

location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot/htdocs;
}

If you'll notice the logs above (Easier to read if you turn off markdown...)  say:

2016-08-20 15:28:19,092:INFO:certbot.plugins.webroot:Using the webroot path /srv/www/htdocs for all unmatched domains.

In fact, I *believe* that all of them were validated using that root, but since the certificate was relatively new, and 0.s.aarcane.org was the only one not yet validated with the acme-test server when I did that --dry-run, that it is in fact the only one for which validation was attempted, and therefore failed.  

since /srv/www/htdocs was the value of webroot_path in the cli.ini file, and since changing that functioned as a workaround, it's fairly obvious that somehow either the webroot_map block isn't getting parsed properly, or the last element therein isn't getting parsed properly.

**Comment by bmw** [comment] 2016-09-14 22:02
>  the only thing that does is manually editing the cli.ini (for me that's /etc/certbot/cli.ini for others it may be /etc/letsencrypt/cli.ini)

Values in cli.ini will override those found in `/etc/letsencrypt/renewal`. If you're modifying `webroot-map` in that file, it will cause the behavior you're seeing. I wouldn't expect changing `webroot-path` to be a problem, but it might be depending on your version of Certbot.

**Comment by bmw** [comment] 2018-11-16 00:47
`/etc/letsencrypt/cli.ini` overriding renewal configuration files is the expected behavior so I'm closing this issue. If you think I missed something, please comment or open a new issue.

**Closed by bmw** 2018-11-16 00:47 UTC
Labels: area: webroot
