### ISSUE TITLE
standalone_supported_challenges value from private beta causes renewal failures

### ISSUE THREAD

**Issue by NiklasMerz** [certbot/certbot#2927] opened 2016-05-05 07:42 UTC
I am using a Apache and ran ./letsencrpt-auto renew 

`2016-05-05 07:36:46,390:INFO:letsencrypt.renewal:updating legacy http01_port value
2016-05-05 07:36:46,390:WARNING:letsencrypt.renewal:Renewal configuration file /etc/letsencrypt/renewal/XXXXXX.conf produced an unexpected error: Unrecognized challenges: dvsni. Skipping.
2016-05-05 07:36:46,390:DEBUG:letsencrypt.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 325, in renew_all_lineages
    renewal_candidate = _reconstitute(lineage_config, renewal_file)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 80, in _reconstitute
    _restore_plugin_configs(config, renewalparams)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 155, in _restore_plugin_configs
    setattr(config.namespace, config_item, cast(config_value))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/standalone.py", line 127, in supported_challenges_validator
    "Unrecognized challenges: {0}".format(", ".join(unrecognized)))
ArgumentTypeError: Unrecognized challenges: dvsni

2016-05-05 07:36:46,391:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 538, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 355, in renew_all_lineages
    renew_skipped, parse_failures)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 290, in _renew_describe_results
    notify(parse_failures, "parsefail")
TypeError: append() takes exactly one argument (2 given)
`

**Comment by bmw** [comment] 2016-05-05 22:15
This is actually a combination of two problems, corresponding to the two tracebacks you posted.

The first one we actually haven't seen before, so thank you very much for taking the time to report it. The value for `standalone_supported_challenges` in your renewal config file is from our private beta and is no longer valid. We'll look into adding a fix for this, but in the meantime, I can tell you how to work around the problem.

You said you're using Apache, as long as you're not using the standalone plugin you can simply delete the `standalone_supported_challenges = ...` line from your renewal configuration file. If you are using the standalone plugin, you should replace the string "dvsni" with "tls-sni-01".

The second traceback, which is an error with how `letsencrypt` reports fatal errors during renewal, is a known problem (#2822). The fix for this will be included in our next release, but fixing the standalone problem I described above should fix your issue. Please let me know if you have any more trouble.

**Comment by NiklasMerz** [comment] 2016-05-09 18:02
My certificate seems to work. So I got no real problem.

**Comment by bmw** [comment] 2016-05-09 21:03
The problem is only encountered when trying to use the `letsencrypt(-auto) renew` command with a renewal configuration file from private beta. While this is a very small subset of our users, #2939 should fix the problem.

**Closed** 2016-05-10 00:12 UTC
Labels: bug, has pr, renewal
