### ISSUE TITLE
Unable to override existing certificate

### ISSUE THREAD

**Issue by ssbarnea** [certbot/certbot#2328] opened 2016-02-01 17:51 UTC
I tried to use letsencrypt-auto in order to renew the certificates but it seems that the new certificates are generated in a new directory ` /etc/letsencrypt/live/<domain>-0001` and I do not want this, I just want to replace the old certificate with the current one and to reload them after this. 

I don't want to have to change the nginx configuration path each time I run letsencrypt-auto, probably from inside a cron job.

**Comment by martinjuhasz** [comment] 2016-02-01 18:53
the `/live/` directory contains symlinks that gets updated eacht time you run letsencrypt-auto. So just link these and you're good to go.

**Comment by schoen** [comment] 2016-02-01 19:56
@ssbarnea, I think @martinjuhasz may have misunderstood what you're experiencing. The client *is* supposed to use the original `live` directory, update the symlinks within it, and not make a new one.

While it is possible to manually modify the symlinks and directories, I wouldn't recommend that because it's very easy to get into an inconsistent state. (For reference, you would move the new PEM files from `archive/domain-0001/foo1.pem` into `archive/domain/foo2.pem` for each `foo` in `cert`, `chain`, `fullchain`, and `privkey`, and then change each symlink in `live/foo.pem` to point to the corresponding `../archive/foo2.pem` instead of `../archive/foo1.pem`, and then delete `live/domain-0001` and `archive/domain-0001` and `conf/domain-0001.conf`. However, this is a risky operation because getting any part of the process wrong could confuse the client in a way that's difficult to recover from.)

Did you rerun the client with `-d` options for *each and every* domain name in the old cert, not a subset or a superset of them? That's necessary right now in order to get the client to realize that it should treat the request as a renewal and save the resulting cert as a successor, and many people have found this behavior unintuitive. For example, not specifying a `www.` with a `-d` option (or specifying one if it wasn't specified in the original cert) might not produce the renewal behavior you expect.

I'm working on a `renew` verb for the client that will find certs that need to be renewed and renew them, without having to specify the domains with `-d`. But this hasn't landed in a release yet.

**Comment by mnemonicflow** [comment] 2016-02-05 22:07
I've encountered the same problem after running `./letsencrypt-auto certonly` with webroot plugin and the following config in /etc/letsencrypt/cli.ini:
```
# This is an example of the kind of things you can do in a configuration file.
# All flags used by the client can be configured here. Run Let's Encrypt with
# "--help" to learn more about the available options.

verbose = True
agree-tos = True
renew-by-default = True

# Use a 4096 bit RSA key instead of 2048
rsa-key-size = 4096

# Uncomment and update to register with the specified e-mail address
email = user@example.com

# Uncomment and update to generate certificates for the specified
# domains.
domains = example.com, www.example.com

# Uncomment to use a text interface instead of ncurses
text = True
non-interactive = True

# Uncomment to use the webroot authenticator. Replace webroot-path with the
# path to the public_html / webroot folder being served by your web server.
authenticator = webroot
webroot-path = /var/www/example.com/public_html
```

A new directory has been created for the new certificate:
```
root@example:~/letsencrypt# ls -l /etc/letsencrypt/live/
total 8
drwxr-xr-x 2 root root 4096 Nov  8 09:50 example.com
drwxr-xr-x 2 root root 4096 Feb  5 22:32 example.com-0001

root@example:~/letsencrypt# ls -l /etc/letsencrypt/live/example.com
total 0
lrwxrwxrwx 1 root root 36 Nov  8 09:50 cert.pem -> ../../archive/example.com/cert1.pem
lrwxrwxrwx 1 root root 37 Nov  8 09:50 chain.pem -> ../../archive/example.com/chain1.pem
lrwxrwxrwx 1 root root 41 Nov  8 09:50 fullchain.pem -> ../../archive/example.com/fullchain1.pem
lrwxrwxrwx 1 root root 39 Nov  8 09:50 privkey.pem -> ../../archive/example.com/privkey1.pem

root@example:~/letsencrypt# ls -l /etc/letsencrypt/live/example.com-0001/
total 0
lrwxrwxrwx 1 root root 41 Feb  5 22:32 cert.pem -> ../../archive/example.com-0001/cert2.pem
lrwxrwxrwx 1 root root 42 Feb  5 22:32 chain.pem -> ../../archive/example.com-0001/chain2.pem
lrwxrwxrwx 1 root root 46 Feb  5 22:32 fullchain.pem -> ../../archive/example.com-0001/fullchain2.pem
lrwxrwxrwx 1 root root 44 Feb  5 22:32 privkey.pem -> ../../archive/example.com-0001/privkey2.pem

```

The first certificate was created using `./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth`

**Comment by schoen** [comment] 2016-02-11 05:08
@mnemonicflow, is there any chance that this is a bug having to do with the `cli.ini`? If you manually specify those options on the command line instead of via `cli.ini`, do you see the same thing?

Many parts of CLI parsing were changed dramatically (under the hood) in the just-released 0.4.0 version, so maybe you could also try again with 0.4.0 and see if you have the same problem?

@ssbarnea, I still think that not supplying separate `-d` options for every single domain in the certificate is the most likely explanation for what you experienced (unless you've specifically confirmed that that wasn't the case). I realize that the requirement to do this might be confusing and I'm happy to hear suggestions for how we might change it (I think that there is a pull request that explores one approach already). Right now, we prompt you if you ask for *the same domains* as an existing cert or *a strict superset* of an existing cert, but we don't prompt you if you ask for *a strict subset* of the domains in an existing cert, because we regard that as an independent, separate request.

**Comment by littleguga** [comment] 2016-03-20 00:28
I think this is similar to #2071

**Comment by nerdoc** [comment] 2016-04-24 21:12
I think this is a duplicate of #2071. If you don't think it is a separate issue please mark this as closed (=dupe).

**Closed** 2016-06-02 22:53 UTC
Labels: duplicate
