### ISSUE TITLE
Make v0.9 available via apt-get for Ubuntu servers

### ISSUE THREAD

**Issue by binarykitchen** [certbot/certbot#3838] opened 2016-12-01 05:43 UTC
Currently `apt-get install certbot` on Ubuntu 16.10 installs the 0.8.1-2 version. Would be great to update that to v0.9.x so that internationalized names are possible.

Thanks :)

**Comment by fsanzv** [comment] 2016-12-01 11:59
And in Ubuntu 16.04 simply doesn't install anything. Please update the docs.

Thanks.

**Comment by pde** [comment] 2016-12-01 22:38
I think this mostly a duplicate of #3708 and #1706.

Feel free to also file a bug on launchpad about 16.10; we have filed the one about 16.04:

https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1640978

**Closed** 2016-12-01 22:38 UTC
Labels: debian / ubuntu, duplicate, pkging
