### ISSUE TITLE
 Unable to set value to path!

### ISSUE THREAD

**Issue by ligi** [certbot/certbot#7085] opened 2019-05-19 19:24 UTC
just tried using certboot as described here:

https://certbot.eff.org/lets-encrypt/debianstretch-apache

but got the following error:
```
Deploying Certificate to VirtualHost /etc/apache2/sites-available/000-default-le-ssl.conf
An unexpected error occurred:
ValueError: Unable to set value to path!
Please see the logfiles in /var/log/letsencrypt for more details.

IMPORTANT NOTES:
 - Unable to install the certificate
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/komputing.org/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/komputing.org/privkey.pem
   Your cert will expire on 2019-08-17. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

this is the stacktrace from the log:
```
Your cert will expire on 2019-08-17. To obtain a new or tweaked version of this certificate in the future, simply run certbot again with the "certonly" option. To non-interactively renew *all* of your certificates, run "certbot renew"
2019-05-19 14:20:16,101:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:16,116:DEBUG:certbot.reverter:Creating backup of /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:16,198:INFO:certbot_apache.override_debian:Enabled Apache socache_shmcb module
2019-05-19 14:20:16,550:INFO:certbot_apache.override_debian:Enabled Apache ssl module
2019-05-19 14:20:16,999:INFO:certbot_apache.configurator:Deploying Certificate to VirtualHost /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,000:INFO:certbot_apache.override_debian:Enabling available site: /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,056:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,246:INFO:certbot_apache.configurator:Deploying Certificate to VirtualHost /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,299:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,489:INFO:certbot_apache.configurator:Deploying Certificate to VirtualHost /etc/apache2/sites-available/000-default-le-ssl.conf
2019-05-19 14:20:17,611:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 498, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 336, in deploy_cert
    self._deploy_cert(vhost, cert_path, key_path, chain_path, fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 446, in _deploy_cert
    self._add_dummy_ssl_directives(vhost.path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 1430, in _add_dummy_ssl_directives
    "insert_cert_file_path")
  File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 329, in add_dir
    self.aug.set(aug_conf_path + "/directive[last() + 1]", directive)
  File "/usr/lib/python3/dist-packages/augeas.py", line 187, in set
    raise ValueError("Unable to set value to path!")
ValueError: Unable to set value to path!

2019-05-19 14:20:17,611:DEBUG:certbot.error_handler:Calling registered functions
2019-05-19 14:20:17,736:DEBUG:certbot.reporter:Reporting to user: Unable to install the certificate
2019-05-19 14:20:17,737:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1101, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 735, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 498, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 336, in deploy_cert
    self._deploy_cert(vhost, cert_path, key_path, chain_path, fullchain_path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 446, in _deploy_cert
    self._add_dummy_ssl_directives(vhost.path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 1430, in _add_dummy_ssl_directives
    "insert_cert_file_path")
  File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 329, in add_dir
    self.aug.set(aug_conf_path + "/directive[last() + 1]", directive)
  File "/usr/lib/python3/dist-packages/augeas.py", line 187, in set
    raise ValueError("Unable to set value to path!")
ValueError: Unable to set value to path!
2019-05-19 14:20:17,740:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by joohoi** [comment] 2019-05-20 08:37
In order to not to fragment the comments and discussion, I'm closing this as a duplicate of #5353

**Closed by joohoi** 2019-05-20 08:37 UTC
Labels: area: apache, duplicate
