### ISSUE TITLE
Stuck at "installing Python packages"

### ISSUE THREAD

**Issue by Septillion** [certbot/certbot#3093] opened 2016-05-30 02:30 UTC
![image](https://cloud.githubusercontent.com/assets/5908006/15638298/439c1632-2651-11e6-822f-e25fed8fd899.png)

Looks like this. I waited overnight and it's still installing. I'm running Ubuntu 12.04, Nginx and using the webroot plugin and a command like this:

`./certbot-auto certonly --webroot -w /a/domains/certain.cn/public_html/ -d certain.cn -d www.certain.cn`

Am I doing anything wrong?

**Comment by bmw** [comment] 2016-05-31 20:17
No you're not doing anything wrong and I'm sorry you're having trouble.

I believe this is a duplicate of #2832 though and while very verbose, I provided step by step instructions there on how to manually perform the installation that `certbot-auto` is doing. Doing this by hand may help you determine what's going wrong.

**Closed by bmw** 2016-05-31 20:17 UTC

**Comment by Septillion** [comment] 2016-06-06 18:39
I believe this is not a duplicate. While I was trying to manually do whatever certbot-auto is supposed to do following your instructions in #2832 , I found that the certbot was having trouble actually downloading two .py files. I believe this has something to do with the infamous Great Firewall which might be blocking some of the CDNs you're using.

**Comment by bmw** [comment] 2016-06-06 18:43
Hmm. I fail to see how this is different from #2832. Both issues are about getting stuck at the "Installing Python packages..." output. While one user reported problems with `cffi`, there are other people reporting that issue who haven't mentioned any problems with `cffi`.

**Comment by lvscar** [comment] 2016-07-06 08:57
getting stuck at the "Installing Python packages..." 
Ubuntu 12.04.5 
trying to run certbot-auto  in China.

**Comment by ice6** [comment] 2016-10-19 08:40
https://github.com/certbot/certbot/issues/2516

**Comment by changecheng** [comment] 2016-11-14 14:46
I think its GFW's fault that prevents downloading packages from pip, like https://pypi.python.org/packages/source/p/pip/pip-8.0.3.tar.gz in pipstrap.py.

**Comment by bmw** [comment] 2017-10-11 18:49
We're trying to help people dealing with the GFW and need help testing something. If you can, please follow my instructions [here](https://github.com/certbot/certbot/issues/2516#issuecomment-334332845) and report back.

**Comment by ksallberg** [comment] 2018-11-02 09:57
For what it's worth, I have too had this issue. It was the case that I had too little free memory on my raspberry pi, so it started swapping.

**Comment by Akito13** [comment] 2019-01-28 01:20
> 
> 
> For what it's worth, I too had this issue. It was the case that I had too little free memory on my raspberry pi, so it started swapping.

Same issue here today, but my 0W has still half of the memory free.

**Comment by GiovanH** [comment] 2020-03-03 21:40
Same issue here today, with plenty of free memory and CPU.

**Comment by bmw** [comment] 2020-03-06 00:16
@GiovanH, if we recommend certbot-auto for your platform at https://certbot.eff.org/instructions and you're still having issues, I recommend creating a post at https://community.letsencrypt.org where there is a large community of people familiar with the project who should be able to help you.
