### ISSUE TITLE
Disable automatic character encoding detection from requests

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7229] opened 2019-07-10 18:30 UTC
As reported by @jsha:
> When I set LOGLEVEL=0 locally to get debug info out of the acme module, I see a lot of:
> ```
> DEBUG:chardet.charsetprober:SHIFT_JIS Japanese prober hit error at byte 2
> DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 1
> DEBUG:chardet.charsetprober:GB2312 Chinese prober hit error at byte 2
> DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 1
> ... many lines follow ...
> ```
> To some extent I asked for this by asking for loglevel 0, but I'm curious - do we know when  the charset prober runs and why? it makes it a little annoying to scroll back and see meaningful content.

This looks to be caused by us not telling requests the expected encoding so it tries to figure it out automatically. See https://2.python-requests.org/en/master/user/quickstart/#response-content.

[RFC 8555 specifies that the encoding must be UTF-8](https://tools.ietf.org/html/rfc8555#section-5) so we should tell requests this to remove these unnecessary operations and log output from our ACME library.

**Comment by jsha** [comment] 2019-07-10 18:45
I think things are working as intended for application/json, which doesn't generate these messages. However, the response from an ACME v1 new-cert request, which has Content-Type: application/pkix-cert (and has binary content) does trigger these charset detection messages. It may be that the requests library decides whether to apply this detection based on content-type?

Also, this is a bit odd: In theory I think the detection should only happen when using `r.text`: https://2.python-requests.org//en/latest/api/#requests.Response.text. However, it seems like we mostly use `r.content`. The two exceptions don't seem like they're getting called regularly, certainly not on v1 new-cert responses:

https://github.com/certbot/certbot/blob/43f58ca803b3070365e0ba52471544c1caaec605/acme/acme/client.py#L501-L502

https://github.com/certbot/certbot/blob/43f58ca803b3070365e0ba52471544c1caaec605/acme/acme/client.py#L744-L746 (part of the ACMEv2 flow, which uses PEM certs)

**Comment by jsha** [comment] 2020-07-10 00:33
I haven't noticed this problem in a while. Let's close it.

**Closed by jsha** 2020-07-10 00:33 UTC
Labels: area: acme, needs-update
