### ISSUE TITLE
Certbot --cert-name should re-use old authentication method

### ISSUE THREAD

**Issue by sffc** [certbot/certbot#4660] opened 2017-05-14 05:19 UTC
## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager (yum)

## I ran this command and it produced this output:

I followed the instructions [here](https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains) to add a new domain name to my certificate.  To add my new subdomain ("b.example.com"), I ran:

```bash
sudo certbot certonly --cert-name a.example.com -d b.example.com
```

I was then prompted to pick between webroot and standalone:

```
How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Spin up a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): c
```

## Certbot's behavior differed from what I expected because:

I expect Certbot to re-use the default method, like it does when `certbot renew` is run.

Not a huge issue since modifying existing certificates isn't done that often, but it would improve usability since I don't remember which option I had used when creating my certificate the first time several months ago.

**Comment by SwartzCr** [comment] 2017-05-15 18:09
What you actually want is to use the --expand command as described here: https://certbot.eff.org/docs/using.html?highlight=expand
This seems like a problem with our documentation - @pconrad-fb think you wanna help with this?

**Comment by pconrad-fb** [comment] 2017-05-15 21:49
Already working on more docs for --expand but I need more info. Please see my question in the comments here: https://github.com/certbot/certbot/issues/3664

**Comment by sffc** [comment] 2017-05-16 07:19
Does `--expand` re-use the old authentication method (webroot or standalone)?  That is, if I run the command

    sudo certbot certonly --expand --cert-name a.example.com -d b.example.com

then I want it to go and replace my old certificate with a new one that covers all the old subdomains plus the new subdomain `b.example.com`.  I want it to do this without having to remember what other options I had set in the original call to `certbot` last year, like the choice between webroot and standalone.

**Comment by SwartzCr** [comment] 2017-05-16 21:11
Yes expand should re-use the previous settings you had, much like a basic call to renew would

**Comment by pconrad-fb** [comment] 2017-06-02 20:48
Does --expand take into account the existing domains and just add the ones that you specify? Would this syntax be correct for adding two domains to an existing cert:

  certbot --expand --cert-name existing.com -d example.com,newdomain.com

or

  certbot --expand --cert-name existing.com -d example.com -d newdomain.com

**Comment by bmw** [comment] 2017-06-06 23:38
Expand only takes into account the ones you specify and the two commands you provided are equivalent.

`--cert-name` is strictly more powerful and less error prone than `--expand` though. Additionally, if `--cert-name` is provided, `--expand` is completely ignored. If you run:
```
certbot --cert-name existing.example.org -d <comma delimited list of domains>
```
The cert for `existing.example.org` is updated to include the domains you provided. This can be used to add or remove domains from a cert.

If you modify a cert with `--cert-name`, you'll see a prompt like:
```
-------------------------------------------------------------------------------
You are updating certificate example.org to include domains: abc.example.org,
example.org

It previously included domains: example.org

Did you intend to make this change?
-------------------------------------------------------------------------------
(U)pdate cert/(C)ancel:
```
`--expand` isn't so forgiving. If you use `--expand` without `--cert-name` (because again, `--cert-name` causes `--expand` to be ignored) it tries to find the existing certificate that is the largest [subset](https://en.wikipedia.org/wiki/Subset) of the domains on the command line. If it cannot find any subsets, a new certificate is created. If it finds multiple subsets of the same size, the one chosen is ambiguous!

In general, if the user knows the cert name, that should be used rather than `--expand`.

**Comment by pconrad-fb** [comment] 2017-06-08 19:17
Okay, so, just to back up a step here...

Let's say I have a cert called my-cert that already includes a.com, b. org, and c.net. I want to add d.com and e.com.

Here are my questions:

1. Is there a command where I can specify my-cert and the two new domains and they'll be added? Something like certbot --expand my-cert -d d.com,e.com?
2. Based on your description above, I believe this would result in the existing domains being removed from my-cert. Is that right?
3. Would it make sense for --cert-name to behave that way instead, and have --expand actually be additive only? 
4. ...And to do it by certificate name rather than trying to introspect the largest subset? That seems fraught with peril, for the reason you mentioned.

**Comment by bmw** [comment] 2017-06-08 19:39
1. No. There is no command like this at this time.
2. The command you listed in step 1 actually causes Certbot to exit with an error because it can't parse its arguments (`--expand` doesn't take any arguments). Assuming you meant `certbot --expand --cert-name my-cert -d d.com,e.com`, you're correct that this command causes the existing to domains to be removed from my-cert.
3. (and 4) I think making `--expand` additive only would be a good idea, but as you suggested in question 4, the user would also have to include `--cert-name`. Otherwise, if the user just ran `certbot --expand -d <new-domains>` we wouldn't know which cert to expand! The problem with implementing this though is it will change the behavior of existing commands for our users which we're trying to avoid right now. `--expand` predates `--cert-name` by quite a bit.

I personally think the best path forward for documenting this stuff is to make the minor changes to the `--expand` documentation as suggested at https://github.com/certbot/certbot/issues/3664#issuecomment-294013607. Then you can add documentation using `--cert-name` on how to add and remove domains from a certificate.

**Comment by pconrad-fb** [comment] 2017-06-08 20:35
1. Ok.
2. --expand has to at least take the arguments to the -d flag, right? And then it looks for a matching cert?
3. and 4. Ok. I'll try to make the existing behavior of --expand and --cert-name clear in the docs. 

Just to re-cap:
certbot --cert-name my-cert.org -d b,org,c.net,d.com, e.com will have the effect of deleting a.com, preserving b.org and c.net, and adding d.com and e.com to the cert "my-cert.org". It gives exact control over the domains handled by a cert whose name you know.

certbot --expand -d b,org,c.net,d.com, e.com will look for a cert that has the most domains in common with the list in -d (in this case hopefully it finds my-cert.org) and then makes the same changes (in this example) as the previous --cert-name example.

That is, the difference between --expand and --cert-name is mainly how it finds the cert, and then the domains specified in -d become the new set of domains for the next version of the cert in the lineage.

Am I on the right track?

**Comment by bmw** [comment] 2017-06-08 22:23
> --expand has to at least take the arguments to the -d flag, right? And then it looks for a matching cert?

Sorry I should have worded that better. You're correct that you have to provide domains when using `--expand`. Certbot just errored when running the command `certbot --expand my-cert -d d.com,e.com` written above because I think you forgot `--cert-name` before my-cert.

> certbot --cert-name my-cert.org -d b,org,c.net,d.com, e.com will have the effect of deleting a.com, preserving b.org and c.net, and adding d.com and e.com to the cert "my-cert.org". It gives exact control over the domains handled by a cert whose name you know.

Correct!

> certbot --expand -d b,org,c.net,d.com, e.com will look for a cert that has the most domains in common with the list in -d (in this case hopefully it finds my-cert.org) and then makes the same changes (in this example) as the previous --cert-name example.

So the way the cert is searched for with `--expand`, it only considers certs where all domains in the cert are also included on the command line. In this example, a.com isn't on the command line, but is in the cert so my-cert is ignored because the domains you specified aren't a strict "expansion" of the existing cert. Unless you have another certificate that only contains domains included on the command line, Certbot just creates a new lineage!

> That is, the difference between --expand and --cert-name is mainly how it finds the cert, and then the domains specified in -d become the new set of domains for the next version of the cert in the lineage.

You are correct that `--expand` and `--cert-name` find the cert differently and after running the command, the domains specified become the names in the certificate obtained. The problem identified with `--expand` as seen in your example is although the cert you obtained had the domains specified, you didn't expand anything and Certbot just made you a new lineage.

Hopefully that makes sense! I'm happy to answer more questions if you have them.

**Comment by pconrad-fb** [comment] 2017-06-08 23:09
Got it!

Use --cert-name if you know the name. Use --expand if you know ALL the domains in the cert. You can't remove by using --expand, only, well, expand, because the specified domains have to be a superset of those in the cert (or it won't find the cert).

**Comment by bmw** [comment] 2017-06-08 23:10
Exactly right.

**Comment by pconrad-fb** [comment] 2017-06-08 23:12
WHEW. All right, I'll probably get a chance to work on this in the .rst files tomorrow. Thanks for all your help!

**Comment by sffc** [comment] 2017-06-09 07:35
In [the docs](https://certbot.eff.org/docs/using.html#changing-a-certificate-s-domains), it says:

> The `--cert-name` flag can also be used to modify the domains a certificate contains, by specifying new domains using the `-d` or `--domains` flag.

To me, that means things I list after `-d` are added to the certificate.

I realize now that this is not at all how either`--expand` and `--cert-name` actually works.  If I understand correctly, you *always* have to re-list all domains if you want to keep them covered by the cert.

Here's two things that can be done to help:

1. Make sure that this fact, that `-d` *overwrites all* domains on the cert, is very clear in the docs.
2. Add a new flag to add domains to a named cert without removing old domains.  I would suggest `--expand`, but I understand the desire to keep the behavior stable.

**Comment by ArchangeGabriel** [comment] 2018-11-07 16:14
It seems I’m having an issue here…

If I run `certbot --cert-name <certname> -d <comma separated list of domains>`, I get:
```
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

Per this thread, I thought certbot should use the parameters from the renewal file, but apparently not?

**Comment by soletan** [comment] 2019-11-05 09:56
Hm, I don't know much about its functionality back in 2017 but as of now comments like this one don't seem to apply anymore:

> Yes expand should re-use the previous settings you had, much like a basic call to renew would

It _should_ do so, but it doesn't. Since the CLI seems to have changed as well for most examples given above don't work anymore I'd like to know if there is some progress on the basic issue here.

FWIW I'm using certbot 0.31.0 with Ubuntu 16.04 LTS.

In my case there is a configuration like this one:

```
root@legacy1-php:/cepharum/httpd-configurator# cat /etc/letsencrypt/renewal/cepharum.de.conf
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/cepharum.de
cert = /etc/letsencrypt/live/cepharum.de/cert.pem
privkey = /etc/letsencrypt/live/cepharum.de/privkey.pem
chain = /etc/letsencrypt/live/cepharum.de/chain.pem
fullchain = /etc/letsencrypt/live/cepharum.de/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2f8874d278ea960634764bbc4a16e937
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = webroot
[[webroot_map]]
www.copy.cepharum.de = /home/soletan/sites/cepharum.de/web
copy.cepharum.de = /home/soletan/sites/cepharum.de/web
www.blog.cepharum.de = /home/soletan/sites/cepharum.de/web
blog.cepharum.de = /home/soletan/sites/cepharum.de/web
www.bernau.cepharum.de = /home/soletan/sites/cepharum.de/web
bernau.cepharum.de = /home/soletan/sites/cepharum.de/web
www.toxa.de = /home/soletan/sites/cepharum.de/web
toxa.de = /home/soletan/sites/cepharum.de/web
www.cepharum.net = /home/soletan/sites/cepharum.de/web
cepharum.net = /home/soletan/sites/cepharum.de/web
www.cepharum.gmbh = /home/soletan/sites/cepharum.de/web
cepharum.gmbh = /home/soletan/sites/cepharum.de/web
www.cepharum.eu = /home/soletan/sites/cepharum.de/web
cepharum.eu = /home/soletan/sites/cepharum.de/web
www.cepharum.berlin = /home/soletan/sites/cepharum.de/web
cepharum.berlin = /home/soletan/sites/cepharum.de/web
www.cepharum.at = /home/soletan/sites/cepharum.de/web
cepharum.at = /home/soletan/sites/cepharum.de/web
www.cepharum.de = /home/soletan/sites/cepharum.de/web
cepharum.de = /home/soletan/sites/cepharum.de/web
```

When I run

```
certbot certonly --cert-name cepharum.de -d www.cepharum.de --dry-run
```

(for the previously issued cert doesn't contain all domains listed in configuration but just four of them, thus I wanted to add this given domain to the existing cert) all I get is this:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Nginx Web Server plugin (nginx)
2: Spin up a temporary webserver (standalone)
3: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-3] then [enter] (press 'c' to cancel):
```

So, I consider this a reliable indicator for old authentication method is not re-used.

**Comment by soletan** [comment] 2019-11-05 15:50
Guess, I have to update/correct myself: 

I can't reproduce how I got there, but before posting comment above I tried running certbot without any action name like **renew** or **certonly** and this caused certbot to fail. Right now I was writing a script and observed certbot accepting to be invoked without either action as parameter. In that case certbot wasn't asking for the method to use first, but was asking to confirm some update of existing certificate.

However:

1. I wasn't able to just add some domain names but had to list all the existing domains and include those to be added. Using `--expand` didn't help.
2. More important, instead of using the authentication method found in configuration (as demanded by this issue), certbot was obviously just guessing my desired method of authentication from inspecting the system or maybe relying on its default - I don't know - but it was switching to a different method (was webroot as demonstrated before, now it's nginx).
3. Thus I tried to run it again this time with **certonly**. However, this time certbot was asking for the desired authentication method again..

**Comment by bmw** [comment] 2019-11-05 21:42
@soletan, for better or worse, that's all expected behavior. I deleted the comment you referenced above that contained incorrect information. If you need more help using Certbot, I recommend posting at https://community.letsencrypt.org where there is a large community of people familiar with the project who would be happy to help.

This issue got pretty sidetracked from its original goal so I'm closing this issue in favor of https://github.com/certbot/certbot/issues/7506.

**Closed by bmw** 2019-11-05 21:42 UTC
Labels: area: documentation

**Comment by soletan** [comment] 2019-11-05 22:54
I see, though I don't understand why switching the authentication method is considered eligible and sustainable behaviour. Our nginx setup gets rendered from scripts as well, thus relying on webroot authentication is pretty simple for all the fuzz to fix nginx is for nothing and just some more code to cause headaches and errors. I'm missing KISS in this...

**Comment by bmw** [comment] 2019-11-06 02:02
I understand your frustration. I think this is caused by a difference in understanding about how Certbot subcommands work. `certbot renew` is the only subcommand that automatically reuses options from the previously issued certificate. All other subcommands (or Certbot without a subcommand which is the same thing as `certbot run`) are conceptually (and technically) a request for a different certificate (with a few checks built in to prevent having tons of certificates in `/etc/letsencrypt/live`, hitting rate limits, etc.).

Years ago [we asked our community about this behavior](https://community.letsencrypt.org/t/certbot-certonly-run-and-renewal-parameters/29591) and no one suggested we change it. At this point with over a million active users, I don't think we're likely to change it without a major overhaul of Certbot.

If you think I'm missing something else constructive from #7506 (possibly what caused you to expect other subcommands to remember these values on how we can improve our communication?), feel free to open a new issue and we'll take a look.
