### ISSUE TITLE
Auto-redirect in nginx for multiple hostnames only creates one redirect

### ISSUE THREAD

**Issue by jholovacs** [certbot/certbot#7354] opened 2019-08-26 23:11 UTC
in my server section of my sites-enabled, I have:

```
server {
        ...
        index index.html;
        server_name www.stockteamup.com stockteamup.com;
        ...
}

server {
    if ($host = www.stockteamup.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name www.stockteamup.com;
    return 404; # managed by Certbot
}
```
What was happening is people were typing "stockteamup.com" into their browser, and getting a 404.  However, if they typed in "www.stockteamup.com", it would properly redirect the user to https://www.stockteamup.com.

I added a line after `# managed by Certbot` like so:
```
    if ($host = stockteamup.com) {
        return 301 https://www.stockteamup.com$request_uri;
    }
```
... and now it seems to work, but it seems that Certbot is only "managing" the first hostname, and ignoring the second for redirection.

## My operating system is (include version):
Ubuntu 18.04.1 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get

## I ran this command and it produced this output:
n/a

## Certbot's behavior differed from what I expected because:
I would have expected both entries to be in the second server config area.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
pls see above.

**Comment by bmw** [comment] 2019-08-29 18:45
Is it possible that when you asked Certbot to set up the redirect, the only domain contained in the certificate was www.stockteamup.com? Certificates like that have been created in the past (see https://crt.sh/?id=1546133968) and in that case, Certbot will not set up the redirect for the other domain because doing so will cause TLS errors.

**Comment by jholovacs** [comment] 2020-08-31 01:18
We ended up moving to AWS SSL offloading and had AWS-issued certificates, so I don't think we can see this issue any more, but we cannot confirm that it's reproducible either.

**Comment by bmw** [comment] 2020-08-31 16:34
OK thanks for the update. Since I am not able to reproduce this myself, I'm going to close this issue for now.

If someone else hits it, please open a new issue.

**Closed by bmw** 2020-08-31 16:34 UTC
Labels: area: nginx, more-info
