### ISSUE TITLE
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new registration

### ISSUE THREAD

**Issue by sbwoodside** [certbot/certbot#3711] opened 2016-10-31 05:54 UTC
My let's encrypt setup failed a few times today. The initial failure might have been different from this one. Here's what I get now.

I run this command:

    /opt/letsencrypt/letsencrypt-auto certonly -a webroot --webroot-path=/var/www/html -d test.website.medstack.net

Got:

                       │ Saving debug log to /var/log/letsencrypt/letsencrypt.log             │  
                       │ Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org      │  
    An unexpected error occurred:
    The server experienced an internal error :: Error creating new registration
    Please see the logfiles in /var/log/letsencrypt for more details.

/var/log/letsencrypt has:

```
2016-10-31 05:51:19,652:DEBUG:certbot.main:Root logging level set at 20
2016-10-31 05:51:19,653:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-31 05:51:19,657:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-31 05:51:19,657:DEBUG:certbot.main:Arguments: ['-a', 'webroot', '--webroot-path=/var/www/html', '-d', 'test.website.medstack.net']
2016-10-31 05:51:19,658:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-31 05:51:19,660:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-10-31 05:51:19,663:DEBUG:certbot.plugins.selection:Single candidate plugin: * webfoot
Description: Place files in webfoot directory
Interfaces: IAuthenticator, Plugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f0061aa9f50>
Prep: True
2016-10-31 05:51:19,663:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f0061aa9f50> and installer None
2016-10-31 05:51:24,769:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-31 05:51:24,772:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-31 05:51:24,863:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-10-31 05:51:24,864:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Boulder-Request-Id': 'BdGF4irNJ50-IrwNfGPDeWc4PFWcOLE3rtJ6lAin_gw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:51:25 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'ws-epi9O_ROLaadfQFv7FR47pHAY99doAk0mjDVKaC8'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-10-31 05:51:24,864:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Boulder-Request-Id': 'BdGF4irNJ50-IrwNfGPDeWc4PFWcOLE3rtJ6lAin_gw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:51:25 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'ws-epi9O_ROLaadfQFv7FR47pHAY99doAk0mjDVKaC8'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-10-31 05:51:24,865:DEBUG:root:Requesting fresh nonce
2016-10-31 05:51:24,865:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {}
2016-10-31 05:51:24,923:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-reg HTTP/1.1" 405 0
2016-10-31 05:51:24,923:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': '_ZriCakfVA-YkQ16z2isdY0dSQVt-VxXYC2UxHBL-Ak', 'Expires': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '3I9aaExcy1upuZTtYr0T3bTcpR0HOWbAQRxhPXPlvYo'}. Content: ''
2016-10-31 05:51:24,923:DEBUG:acme.client:Storing nonce: '\xdc\x8fZhL\\\xcb[\xa9\xb9\x94\xedb\xbd\x13\xdd\xb4\xdc\xa5\x1d\x079f\xc0A\x1ca=s\xe5\xbd\x8a'
2016-10-31 05:51:24,924:DEBUG:acme.jose.json_util:Omitted empty fields: agreement=None, certificates=None, authorizations=None, key=None
2016-10-31 05:51:24,924:DEBUG:acme.client:Serialized JSON: {"contact": ["mailto:info@medstack.co"], "resource": "new-reg"}
2016-10-31 05:51:24,925:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, cty=None, x5t=None, alg=None, x5tS256=None, x5u=None, kid=None, jwk=None
2016-10-31 05:51:24,928:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, nonce=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None
2016-10-31 05:51:24,928:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "oOJrc9hlakngikHOdjVCBS3AkpSZRlB2ObqId-8NR5fXLGRt2IlQgYJuv_q5DzRHlqtGiJgyQD-q78zKA3d3alPyL6HPBZNw3eOEAx8QwsTTvZdPSHkXvwYq1jvtP8zTkANv82PkUywWgdB_1TwxWcxDUrAxAfLF97-4U1nKiAnIllR8S4xGe7Vetak3JJk9ryr5ZtIaTM0Oyb68Wyzjimv_jV5fuA4jkUgXs6PG4EfNMvos_4262MNj0vsWLO5MSA4AlQtkT0EL1AELMh3pbo9lo-ikMQBPlAX75ALHV2u9k8TVgEQbhjPt4I8EFQv6zxNUuZSvdvHWSwNRbthtlw"}}, "protected": "eyJub25jZSI6ICIzSTlhYUV4Y3kxdXB1WlR0WXIwVDNiVGNwUjBIT1diQVFSeGhQWFBsdllvIn0", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86aW5mb0BtZWRzdGFjay5jbyJdLCAicmVzb3VyY2UiOiAibmV3LXJlZyJ9", "signature": "jxZ1EmZy6_RCDmPVk8Y2akGFd6-_872Xk3yRcaLb-Jow4yxCDZt6G32fOnd975jM7WLKIsNWsW6LbipXNaysxr22VrG-6uPLps7GSEHoG_kK1mAr35r4t3xmpbJweSdaM_UfdaEU2xvMkcQ30QqkdAbO0OgFsfAfF8uPUvftw0c1DJAZxqLyb_iaDpRMWNFT3Akxf3-J9RgV3lW7ZTR0FsHVyNImZWEm6J4SACNmT4Yh-IQY12mjKy11j9MZMbYucbnL64hkkiy4eDKg3I7NqQ2nzkIYKD9_y-SFgQLVx9gQrJ-jHxjjCjVC3FhXAKYK6UN9Zfxd9zoLskR_QRv6tA"}'}
2016-10-31 05:51:25,107:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-reg HTTP/1.1" 500 109
2016-10-31 05:51:25,109:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '109', 'Boulder-Request-Id': '-F9vZpzcDYGt4S2YPixrggrQPTEDPQahuqmfWcF2Lj4', 'Expires': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'Jy1At56cYmPKTZMIJWijUT7SFihpevQCuS1j68vK8yk'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new registration",\n  "status": 500\n}'
2016-10-31 05:51:25,109:DEBUG:acme.client:Storing nonce: "'-@\xb7\x9e\x9cbc\xcaM\x93\x08%h\xa3Q>\xd2\x16(iz\xf4\x02\xb9-c\xeb\xcb\xca\xf3)"
2016-10-31 05:51:25,110:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '109', 'Boulder-Request-Id': '-F9vZpzcDYGt4S2YPixrggrQPTEDPQahuqmfWcF2Lj4', 'Expires': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:51:25 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'Jy1At56cYmPKTZMIJWijUT7SFihpevQCuS1j68vK8yk'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new registration",\n  "status": 500\n}'
2016-10-31 05:51:25,110:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 353, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 120, in register
    regr = perform_registration(acme, config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 150, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 96, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 649, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 565, in _check_response
    raise messages.Error.from_json(jobs)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new registration

```

**Comment by maltris** [comment] 2016-10-31 06:09
See #3710

**Comment by bmw** [comment] 2016-10-31 21:21
Closing as a dupe of #3710.

**Closed by bmw** 2016-10-31 21:21 UTC
