### ISSUE TITLE
EPEL SELinux problems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4716] opened 2017-05-23 18:13 UTC
Opening an issue here because I feel better about opening potentially spurious bug reports here than on Bugzilla:

Some users are reporting that SELinux is causing the Apache plugin to fail domain validation challenges on CentOS 7. ~~Doing my own testing, this doesn't happen with a default configuration.~~ More details can be found at: https://community.letsencrypt.org/t/letsencrypt-suddenly-failing-to-create-temporary-web-root-for-verification/11739

@hogarthj, what do you think?

EDIT: I know very little about SELinux so the testing I thought I did should be ignored as I think I did it wrong.

**Comment by hogarthj** [comment] 2017-05-23 21:16
I'm configuring selinux to have the certificates in /etc/letsencrypt/(archive|live) correct [here](https://src.fedoraproject.org/cgit/rpms/certbot.git/tree/certbot.spec#n192) but have I missed something happening in /var/lib I need to pay attention to?

I'm not using the apache plugin myself but rather webroot which works fine with this configuration. 

If apache needs to serve out of /var/lib/something we should label correctly there so that it will serve up the files - httpd_sys_content_t if memory serves ...

At any rate they should not be doing apachectl to restart httpd on CentOS7/Fedora/RHEL7 as that's not going to be running in the appropriate selinux context or under the supervision of systemd properly.

I really want to get 0.14.1 to stable as updates have been pending a while, but I'll do some more specific testing of the plugin and get an update prepared for afterwards if I can reproduce.

**Comment by hogarthj** [comment] 2017-05-23 21:40
Okay a quick test of the plugin and I see this:
```
#============= httpd_t ==============
# audit(1495574784.270:117):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:etc_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/etc/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574784.270:117): avc:  denied  { write } for
#   pid=9306 comm="httpd" path="/etc/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=8414283 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:etc_t:s0 tclass=file"
# audit(1495574798.901:118):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:etc_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/etc/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574798.901:118): avc:  denied  { write } for
#   pid=9325 comm="httpd" path="/etc/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=8414283 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:etc_t:s0 tclass=file"
#!!!! WARNING: 'etc_t' is a base type.
allow httpd_t etc_t:file write;
# audit(1495574784.270:117):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:var_lib_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/var/lib/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574784.270:117): avc:  denied  { write } for
#   pid=9306 comm="httpd" path="/var/lib/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=12618355 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file"
# audit(1495574876.532:119):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:var_lib_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/var/lib/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574876.532:119): avc:  denied  { write } for
#   pid=9386 comm="httpd" path="/var/lib/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=12618355 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=file"
#!!!! WARNING 'httpd_t' is not allowed to write or create to var_lib_t.  Change the label to httpd_var_lib_t.
#!!!! $ semanage fcontext -a -t httpd_var_lib_t /var/lib/letsencrypt/.certbot.lock   
#!!!! $ restorecon -R -v /var/lib/letsencrypt/.certbot.lock
allow httpd_t var_lib_t:file write;
# audit(1495574784.270:117):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:var_log_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/var/log/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574784.270:117): avc:  denied  { write } for
#   pid=9306 comm="httpd" path="/var/log/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=4305827 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:var_log_t:s0 tclass=file"
# audit(1495574876.532:119):
#  scontext="unconfined_u:system_r:httpd_t:s0" tcontext="unconfined_u:object_r:var_log_t:s0"
#  class="file" perms="write"
#  comm="httpd" exe="" path="/var/log/letsencrypt/.certbot.lock"
#  message="type=AVC msg=audit(1495574876.532:119): avc:  denied  { write } for
#   pid=9386 comm="httpd" path="/var/log/letsencrypt/.certbot.lock" dev="xvda1"
#   ino=4305827 scontext=unconfined_u:system_r:httpd_t:s0
#   tcontext=unconfined_u:object_r:var_log_t:s0 tclass=file"
allow httpd_t var_log_t:file write;
```

There's clearly some issues surrounding selinux being enabled here whilst the apache plugin is used.

I'll open a ticket in bugzilla as it's something I'm going to need to look at in some detail (note that I have a certification in selinux policy management and this doesn't look too painful).

If there's documentation I can pass back up here or steps that you can incorporate for manual troubleshooting then I'll add them.

For now the best advice I can give is for the small window of certificate gathering:
```
setenforce 0 ; certbot --apache or certbot renew etc ; restorecon -Rv /etc/letsencrypt ; setenforce 1
```

I'll see what I can to make this better in the meanwhile.

**Comment by hogarthj** [comment] 2017-05-23 21:42
I'm tracking this downstream here: https://bugzilla.redhat.com/show_bug.cgi?id=1454961

**Comment by bmw** [comment] 2017-05-23 22:50
I wrote up the files the different Certbot packages access and what they configure other services to access. I can get into more specifics as necessary.

Certbot needs to be able to do whatever it wants with `/etc/letsencrypt`, `/var/lib/letsencrypt`, and `/var/log/letsencrypt`. This applies to both the Apache and Nginx plugins as well.

The Apache and Nginx plugins largely do the same things to their respective webservers. They need to be able to:

* Read, write, and modify Apache/Nginx configuration files
* Configure Apache/Nginx to include configuration files stored in `/etc/letsencrypt`
* Configure Apache/Nginx to use certificates and keys stored in `/var/lib/letsencrypt` (this is done temporarily for domain validation)
* Copy a file from wherever the plugins Python source files are (e.g. `/usr/lib/python2.7/site-packages/`) to `/etc/letsencrypt`.

The Apache plugin also currently configures Apache to use a `DocumentRoot` in `/var/lib/letsencrypt` during domain validation, but Apache actually being able to access the files there is unimportant. The only thing that matters is SELinux doesn't cause Apache to blow up.

**Comment by marcherren** [comment] 2017-07-18 11:17
any news on this issue?

**Comment by davidjb** [comment] 2017-09-25 01:33
I've experienced the same issue with the Nginx plugin for Certbot (version 0.18.1) on RHEL 7.4.  The symptoms looked like this:

```
# certbot --nginx --non-interactive
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for example.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. example.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: example.com
   Type:   connection
   Detail: Error getting validation data
```

The issue came down to file contexts on the access/error logs that were being created in `/var/lib/letsencrypt/`:

```
-rw-r--r--. root root unconfined_u:object_r:var_lib_t:s0 /var/lib/letsencrypt/access.log
-rw-r--r--. root root unconfined_u:object_r:var_lib_t:s0 /var/lib/letsencrypt/error.log
```

which means that when Certbot attempted to restart Nginx, it wouldn't restart because those files couldn't be accessed and therefore validation failed.  The correct context should have been `httpd_log_t` so I fixed this manually by running the following:

```bash
chcon --reference=/var/log/nginx/access.log /var/lib/letsencrypt/access.log
chcon --reference=/var/log/nginx/error.log /var/lib/letsencrypt/error.log
```

Those `/var/lib/letsencrypt/*` files appear to persist (and with the correct context) beyond Cerbot's initial run so hopefully that will stay that way.  Is it appropriate for Certbot to be creating those files and setting the SELinux context after reconfiguring Nginx (but before restarting it) or is that out of scope?

**Comment by bmw** [comment] 2017-09-25 18:25
Thanks for the detailed post @davidjb.

> Is it appropriate for Certbot to be creating those files and setting the SELinux context after reconfiguring Nginx (but before restarting it) or is that out of scope?

Personally I think that Certbot trying to reconfigure an arbitrary SELinux setup so it works properly is complicated and out of scope. What I'd like to see is the packages on systems where SELinux is enabled be modified so Certbot works properly. This can be done using the conventions of the distro rather than Certbot trying to handle any arbitrary configuration.

> Either way, Certbot would be best to confirm that Nginx restarts okay after reconfiguration, which it doesn't appear to do at present. In my case, nginx -t succeeded in the console (because SELinux doesn't apply at that point) but an actual systemctl restart nginx failed with permission denied on the /var/lib/letsencrypt/*.log files.

Since not all systems use systemd (at least not yet), Certbot doesn't use it to start nginx. Instead, it uses the command `nginx -c <path to nginx server root> -s reload`. If nginx isn't already running, it uses `nginx -c <path to nginx server root>`. I'm assuming at least the former command doesn't fail with this setup? If you have a suggestion for a reliable way we can catch this problem earlier without relying on distro specifics, we'd certainly be open to using that rather our current approach. I'm currently not aware of a way to do that.

> Finally, for note the issue wasn't a problem on the test CA; that was issuing certificates fine. I haven't looked into that side of things but I suspect the authorisation was cached or something similar, unless the test configuration generates a different nginx conf that doesn't touch these log files.

Certbot also configures nginx to use these files when getting certs from Let's Encrypt's staging server, but Let's Encrypt does [reuse authorizations](https://community.letsencrypt.org/t/upcoming-change-valid-authz-reuse/16982) when you still have a valid one for that domain tied to your account. I suspect this was the cause of the behavior you were seeing. Certbot sets up the challenge, but because Let's Encrypt didn't verify it, you got a certificate just fine.

**Comment by davidjb** [comment] 2017-09-26 01:17
> Since not all systems use systemd (at least not yet), Certbot doesn't use it to start nginx. Instead, it uses the command nginx -c <path to nginx server root> -s reload. If nginx isn't already running, it uses nginx -c <path to nginx server root>. I'm assuming at least the former command doesn't fail with this setup? 

The former command returns `0` (success; eg the signal was sent), but the reload fails -- permission errors appear in my nginx log.  My suggestion is that Certbot could testing the PIDs of the nginx worker processes.  Nginx's [docs](http://nginx.org/en/docs/control.html) imply this is the only way to know.  Upon a successful reload the `nginx: worker process` processes are replaced and thus their PIDs change; they stay the same otherwise.  In Python, `psutil` could do this:

```python
>>> import psutil
>>> nginx = psutil.Process(25405) #Master
>>> nginx.children()  # Before reload
[<psutil.Process(pid=26609, name='nginx') at 140681397141136>, <psutil.Process(pid=26610, name='nginx') at 140681397141264>]
>>> nginx.children()  # After nginx -s reload in other terminal
[<psutil.Process(pid=27947, name='nginx') at 140681587200080>, <psutil.Process(pid=27948, name='nginx') at 140681397166416>]
```

Certbot's package on RHEL 7 currently depends on psutil so it's already there.

Other non-starter options could be to:
* Test the error log if errors appear immediately after the reload (but that's brittle and people can turn off logging + other errors could conflict) or 
* Test the SNI request locally first (or add a 'dummy' block) to see if nginx was reloaded okay.  This is at risk of a local firewall rule conflicting with this (eg localhost is denied access to its own HTTPS port).

**Comment by bmw** [comment] 2017-09-27 01:23
Certbot hasn't actually depended on `psutil` since version 0.9.0. The Fedora packages continuing to depend on it is unnecessary and I opened a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1496291) about it. Thanks for bringing it to my attention.

While I'm pretty hesitant to add any new dependencies or much complexity here, we ideally should do something more than our current error message. Again, the specific problem for you should be fixed by updating the Fedora/EPEL packages, but we can't always rely on this when Certbot is installed through other means. Finding out a challenge failure is due to SELinux permissions takes quite a bit of digging so we should at least try to improve the error message here.

Thoughts @ohemorange?

**Comment by ohemorange** [comment] 2017-10-02 23:27
The correct thing to do seems to be to use `psutil` to check the worker PIDs, as described. Then we'll get a more straightforward error message, rather than an incorrect one when things fail later, or worse, failing undetectably and not informing the user.

How much of an issue is it to keep `psutil` around as a dependency? Compared to having things work cleanly for our SELinux users?

**Comment by bmw** [comment] 2017-10-02 23:38
> How much of an issue is it to keep psutil around as a dependency? Compared to having things work cleanly for our SELinux users?

It'd be adding a new dependency on most systems. Fedora/EPEL is the only one I'm aware of that didn't update the package's dependencies when we did. It's also a compiled dependency relying on non-Python packages which I've been trying to avoid.

With that said, the package is pretty widely available so adding a dependency might not be a big deal.

**Comment by ILMostro** [comment] 2017-12-20 00:17
I'm seeing this issue on RHEL7 right now.  I'm not sure that the issue is with `/var/lib/letsencrypt/*logs`, as @davidjb previously mentioned.  I could be wrong, but I don't see any such files in the respective directory.  Furthermore, the SELinux AVC details mention nothing of that directory; only the `ServerRoot/.certbot.lock` file is mentioned.

**Comment by bmw** [comment] 2019-03-28 22:29
This issue hasn't seen any updates in a long time and the Red Hat issue tracking changing these SELinux rules has been closed so I'm also closing this issue.

If you continue to have problems, please comment or open a new issue.

**Comment by davidjb** [comment] 2019-04-08 06:57
@bmw Which Red Hat issue was tracking SELinux rules?  The two issues mentioned here were either not fixed or unrelated to SELinux specifically:

https://bugzilla.redhat.com/show_bug.cgi?id=1454961 (closed as Fedora 27 is EOL, not fixed)
https://bugzilla.redhat.com/show_bug.cgi?id=1496291 (dependency cleanup, not specifically SELinux related)

**Comment by bmw** [comment] 2019-04-08 17:08
Ah. I was referring to https://bugzilla.redhat.com/show_bug.cgi?id=1454961 which was linked by one of the Fedora/EPEL package maintainers above and was closed. You're right that the reason that was closed was Fedora 27 reached its end-of-life.

@elyscape, are you aware of this issue?

**Comment by davidjb** [comment] 2020-04-07 23:32
Still an issue as far as I know (/unstale)

**Comment by dk-means** [comment] 2020-06-24 22:43
There is still an SELinux rule or three missing on my CentOS 7 system.
  I have selinux-policy-3.13.1-266.el7.noarch, and certbot 1.4.0-1.el7 installed.

Whenever certbot actually needs to renew a certificate, I see SELinux errors reported.  It appears that certbot tries several different places to establish a lockfile; for the following three, SELinux denies the attempt:
  /etc/httpd/.certbot.lock
  /var/log/letsencrypt/.certbot.lock
  /etc/letsencrypt/.certbot.lock
At least on my systems, here are the labels for the relevant directories
  /etc/httpd    httpd_config_t
  /var/log/letsencrypt    var_log_t
  /etc/letsencrypt    etc_t

**Comment by bmw** [comment] 2020-07-16 18:27
An EPEL 8 user reported problems with this too at https://community.letsencrypt.org/t/selinux-should-the-log-files-be-var-log-t-or-cron-log-t/128552.

@FelixSchwarz, are you aware of this issue in general and do you have a recommendation for the specific problem that user is facing?

**Comment by FelixSchwarz** [comment] 2020-07-16 20:29
Sounds like https://bugzilla.redhat.com/show_bug.cgi?id=1586352 but I did not have enough time to debug this (also I'm not too enthusiastic about SELinux in general). Likely we need some extra SELinux rules (not sure if these should be shipped in the main SELinux package or in certbot).

**Comment by davidjb** [comment] 2021-08-10 15:12
Still an issue as far as I know (/unstale).  I'll confirm the state of things on RHEL 8 on an upcoming project.

**Comment by FelixSchwarz** [comment] 2021-08-11 07:41
Yes, I expect the issues still to be present. Right now I don't have enough free time to fix this - contributions welcome.

**Comment by ILMostro** [comment] 2022-01-11 05:31
> There is still an SELinux rule or three missing on my CentOS 7 system. I have selinux-policy-3.13.1-266.el7.noarch, and certbot 1.4.0-1.el7 installed.
> 
> Whenever certbot actually needs to renew a certificate, I see SELinux errors reported. It appears that certbot tries several different places to establish a lockfile; for the following three, SELinux denies the attempt: /etc/httpd/.certbot.lock /var/log/letsencrypt/.certbot.lock /etc/letsencrypt/.certbot.lock At least on my systems, here are the labels for the relevant directories /etc/httpd httpd_config_t /var/log/letsencrypt var_log_t /etc/letsencrypt etc_t

I'm wondering if there is a specific reason why the lockfile should be created (or even attempts to create it) in any of those locations on the filesystem.  Is it not possible to create it in the `/tmp` or `/var/run/` directories?  So, SELinux is working properly.  While it's possible to create a policy that allows such actions, the proper way to fix it is to establish the appropriate location where that lockfile should be created.

**Closed** 2023-07-12 02:04 UTC
Labels: area: fedora / redhat / CentOS, area: apache, needs-update
