### ISSUE TITLE
./letsencrypt-auto fails if VirtualHost contains FastCgiExternalServer

### ISSUE THREAD

**Issue by julien-lecomte** [certbot/certbot#2144] opened 2016-01-11 23:04 UTC
./letsencrypt-auto fails if VirtualHost contains FastCgiExternalServer

Sample virtualhost conf:

``` xml
<VirtualHost *:80>
  ...
  DocumentRoot /srv/wwwroot/blog/htdocs
  Alias   /php5-fcgi   /usr/lib/cgi-bin/php5-fcgi-blog
  FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi-blog -socket /var/run/php5-fpm.blog.sock -pass-header Authorization
</VirtualHost>
```

Comment the FastCgiExternalServer part and letsencrypt-auto succeeds

Command line 
./letsencrypt-auto --verbose --server https://example.com/  --webroot-path /srv/wwwroot/example/htdocs certonly

**Comment by BlakBat** [comment] 2016-01-12 11:55
Configuration files, command line, stderr and log files available here: http://pastebin.com/Jau23ydQ

**Comment by coreyp1** [comment] 2016-01-29 00:01
Confirmed.  I'm seeing this, too.  This type of configuration is common when using Apache with php-fpm!

**Comment by JKetelaar** [comment] 2016-03-09 16:49
Yep, same here

**Comment by joohoi** [comment] 2017-09-27 12:49
Apache plugin should handle this usecase. This bug seems to be created towards webroot, but as the issue is very old, a lot of improvements have been made and the issue hasn't seen any updates in the last year and a half, I'm closing this as resolved. If this is not the case, please feel free to comment here and we'll reopen the issue.

**Closed by joohoi** 2017-09-27 12:49 UTC
Labels: area: apache, bug
