### ISSUE TITLE
AWS Linux errors

### ISSUE THREAD

**Issue by yobyot** [certbot/certbot#1458] opened 2015-11-11 02:02 UTC
Attempting a stand-alone install on [AWS Linux 2015.03](https://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/) generates this error:

`Command "/home/ec2-user/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-xMWPFC/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r \n', '\n'), __file__, 'exec'))" install --record /tmp/pip-BRUl0h-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2user/.local/share/letsencrypt/include/site/python2.7/cffi" failed with error code 1 in/tmp/pip-build-xMWPFC/cffi`

I suspect its because I am missing something on this instanance, though I did make sure to 

`alternatives --set python /usr/bin/python2.7`

as the default is 2.6 and letsencrypt-auto said support for Python 2.6 is "experimental."

I also looked for logs that might tell me what was missing, but didn't find anything.

Any ideas are appreciated.

**Comment by pde** [comment] 2015-11-11 18:54
It looks like this is `pip` failing to build `python-cffi`, which is needed to build `python-cryptography`. Unfortunately we need the latest version of `python-cryptography`.

**Comment by pde** [comment] 2015-11-11 18:55
You can may be able to get a bit more information by running `letsencrypt-auto --verbose`.

**Comment by pde** [comment] 2015-11-11 19:14
I was able to run the client with a modified `letsencrypt-auto` on Amazon Linux by manualling installing the `python27-virtualenv` package first, then running the RedHat bootstrap path.

**Comment by pde** [comment] 2015-11-11 19:27
OK, I've made an amazonlinux branch of the main git repo; supporting this OS isn't going to be a high priority for us until we've closed out some other urgent tickets, but feel free to try the branch and send results to #1465.

**Comment by yobyot** [comment] 2015-11-12 17:34
Thanks for the quick response, pde. I do hope this will make it into 1.0 as I suspect many business and individuals will do what I did: throw up an AWS Linux instance in order to test the system. It's a quick and fast way to get an Apache system running; you can do it in 15 minutes or less. People might not try again if AWS Linux doesn't work on the first try. ;-) I don't think you need to do automated cert installation in AWS Linux -- but it would be great just to be able to generate the certs.

I've checked out the branch and switched to it. Unfortunately, `./bootstrap/amazon_linux.sh` is missing: 
>[ec2-user@ip-172-31-57-241 letsencrypt]$ ./letsencrypt-auto --debug
>Bootstrapping dependencies for Amazon Linux...
>./letsencrypt-auto: line 64: ./bootstrap/amazon_linux.sh: No such file or directory

I think I have the correct version, no?
>[root@ip-172-31-57-241 letsencrypt]# git status
>On branch letsencrypt/1465
>Your branch is up-to-date with 'origin/letsencrypt/1465'.
>nothing to commit, working directory clean

**Comment by Veraxus** [comment] 2015-11-14 03:34
My company manages dozens of Amazon Linux instances as it includes all the best bits of RHEL and CentOS. Amazon Linux is the defacto gold standard on AWS and it **really** shouldn't be neglected or delayed post-1.0 (as suggested in #1465).

Like @yobyot said, people will either try to install this on their AL instances or launch a quick, cheap AL instance to test, discover that LE is broken, and give up on it altogether.

**Comment by kuba** [comment] 2015-11-14 11:12
Engineering time of the core team is limited. If you need it to work on AWS Linux, please contribute relevant patches and/or test existing ones :) "+1"-ing this thread will not help.

**Comment by yobyot** [comment] 2015-11-14 14:35
Hmmm...a problem is uncovered by a non-technical user (me), it's on a global platform that (apparently) the dev team didn't pay much attention to, it's coming late in the cycle and the response is, "You fix it?"

Let me be explicit: _ignoring AWS is a big mistake._ 

If the objective of the project is to make TLS ubiquitous and easy, I just don't see how you can leave out the number one public cloud provider on the planet and it's native Linux distro. It just makes no sense. As I said previously, if you guys are almost out of time, you could support AWS Linux by simply allowing certificate generation and leave automated installation for later.

**Comment by yobyot** [comment] 2015-12-02 20:34
Well, it's a bit of farting into the wind, but I am shocked that letsencrypt is going into public beta tomorrow (2015-12-03) _and not a single comment here or in #1465 demonstrates success with these changes._

What is the dev community planning on saying when AWS Linux comes up?

**Comment by levskaya** [comment] 2015-12-03 21:32
@yobyot , the most recent master branch works on a fresh amazon linux 2015.09 point release AMI.  I didn't think to test it on the older 2015.03 image, but I can try to see what's different between the two later today.

**Comment by yobyot** [comment] 2015-12-03 21:40
Thx. Will give this a try.

**Comment by jcampbell** [comment] 2016-10-08 22:00
What's the status on this now? I just tried using the latest build but got similar errors; is there currently any expectation that certbot should work on AWS (glaring warning notwithstanding) and/or development plans?

**Comment by bmw** [comment] 2016-10-15 01:08
If people are still having this problem, I'll reopen the issue.

There are known issues (like this one) with using `certbot-auto` on Amazon Linux. Unfortunately, I don't believe anyone knows exactly what the cause of these problems are or how to fix them. If anyone does, I will happily review a pull request.

**Comment by jcampbell** [comment] 2016-10-15 11:48
Thanks, @bmw. I tried to reproduce the error in a different instance type, however, and now believe I was actually being hit by #1081 / #1677 / #1680: the failure was in building the cryptography package, and was in a t2.nano instance that already had a web server running.

Perhaps we could add a check for ```free```? Or consider a prebuilding for distribution?

**Comment by Veraxus** [comment] 2016-10-15 17:37
Certbot works on AWS with a lot of finagling, but auto is completely FUBAR. 

This is the process I use for Amazon Linux & Apache...

1. Download certbot to your ec2-user home directory & make it executable
1. To configure and fetch the certs, use this command:  
`sudo ./certbot-auto --debug -v --server https://acme-v01.api.letsencrypt.org/directory certonly -d YOUR_DOMAIN_HERE -d www.YOUR_DOMAIN_HERE`
1. Switch to superuser with `sudo su` (this is an important step, renewal fails on sudo but works under root)
1. Test that renewal works... `/home/ec2-user/certbot-auto renew --dry-run`
1. Edit your ssl.conf or the appropriate vhost. Add these...
  * `SSLCertificateFile /etc/letsencrypt/live/YOUR_DOMAIN_HERE/cert.pem`
  * `SSLCertificateKeyFile /etc/letsencrypt/live/YOUR_DOMAIN_HERE/privkey.pem`
  * `SSLCertificateChainFile /etc/letsencrypt/live/YOUR_DOMAIN_HERE/fullchain.pem`
1. Edit cron with `crontab -e`
  * Add the following line to your crontab file to enable auto-renewal... `0 1,13 * * * /home/ec2-user/certbot-auto renew`
1. Restart apache: `service httpd restart`
1. Done. Don't forget to exit sudo: `exit`

**Comment by bmw** [comment] 2016-10-17 17:11
> Perhaps we could add a check for free? Or consider a prebuilding for distribution?

We're planning on doing the former in our next release. The issue for that is #3355 and #3513 is a PR that is supposed to solve this issue.

We'd also like to do the latter in `certbot-auto`. If we can get prebuilt versions of all of our packages, we can remove dependencies on things like `gcc` and dramatically reduce the memory needed to run the script. The current compilation, however, is actually required by one of our dependencies rather than Certbot itself. We've asked them to either support a dlopen or prebuilt wheel for linux and they're looking into the issue (see pyca/cryptography#2980).

Another and probably the best solution though is to get a Certbot package available in the Amazon Linux repositories. We have packages available in most modern Linux distros. I confess that I'm not very familiar with Amazon's process here, but we have packages in EPEL7 and the last few versions of Fedora (as well as many non-Red Hat based distros). Perhaps these packages will trickle down eventually, but if anyone knows how to speed up this process, please let us know.

**Comment by jcampbell** [comment] 2016-10-18 12:54
I'm not familiar with the Amazon process, but I did just create a message in the forum where they say they have their engineering team looking for new packages: [https://forums.aws.amazon.com/thread.jspa?threadID=241366]

**Comment by bmw** [comment] 2017-08-01 17:19
This should be fixed in our next release with #4978.

**Closed by bmw** 2017-08-01 17:19 UTC
Labels: area: certbot-auto
