### ISSUE TITLE
Failed to verificate on site which has already https enabled 

### ISSUE THREAD

**Issue by adrianmihalko** [certbot/certbot#5244] opened 2017-11-16 13:15 UTC
Hi,

I am trying to install Letsencrypt. On my site I have already a working SSL solution (RapidSSL), but I want to replace it by Letsenrypt.

`./letsencrypt-auto certonly --agree-tos --webroot --webroot-path /home/html/xy.eu/public_html/ -d xy.eu -d www.xy.eu
`
```
(Y)es/(N)o: Y
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for xy.eu
http-01 challenge for www.xy.eu
Using the webroot path /home/html/xy.eu/public_html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. xy.eu (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://xy.eu/.well-known/acme-challenge/: Timeout, www.xy.eu (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://www.xy.eu/.well-known/acme-challenge/-8K16HrIGfIHzm1MgeZrR-I: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xy.eu
   Type:   connection
   Detail: Fetching
   http://xy.eu/.well-known/acme-challenge/:
   Timeout

   Domain: www.xy.eu
   Type:   connection
   Detail: Fetching
   http://www.xy.eu/.well-known/acme-challenge/-8K16HrIGfIHzm1MgeZrR-I:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```
The $ ls /home/html/xy.eu/public_html/.well-known/ is created and accessible:

```
@-MBP:~$ curl "http://xy.eu/.well-known/"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://xy.eu/.well-known/">here</a>.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at xy.eu Port 80</address>
</body></html>
@-MBP:~$ curl "http://xy.eu/.well-known/" -L
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /.well-known/
on this server.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at xy.eu Port 443</address>
</body></html>
@-MBP:~$
```

**access.log:**

**- - [16/Nov/2017:12:35:47 +0100] "GET /.well-known/acme-challenge/- HTTP/1.1" 301 296 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" 2541 262 698**

- /home/html/xy.eu/public_html/.well-known - it is exists
- /home/html/xy.eu/public_html/.well-known/acme-challenge/ - acme-challenge directory and keys in it are only existing while the letsencrypt-auto script is running.

**I created test.txt:**

http://xy.eu/.well-known/acme-challenge/test.txt1

and it is accessible from web.

**My htaccess:**

```
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP_HOST} ^(www\.)?xy.eu [NC]
RewriteRule (.*) https://xy.eu/$1 [L,R=301,QSA]
```

**Comment by joohoi** [comment] 2017-11-16 13:25
Hi, the error seems to state that Let's Encrypt got a timeout when trying to access the challenge content.

To further debug this problem, you could add `--debug-challenges` to your command line, which will pause Certbot before asking Let's Encrypt to try and retrieve the challenge token. This will allow you (or me) to check that the validation token is indeed accessible.

**Comment by adrianmihalko** [comment] 2017-11-16 13:30
Hi joohoi,

I can retrieve using curl:

```
$ curl "http://xy.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI" -v -L 
*   Trying xy.71...
* TCP_NODELAY set
* Connected to xy.eu (xy.71) port 80 (#0)
> GET /.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI HTTP/1.1
> Host: xy.eu
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 16 Nov 2017 13:28:25 GMT
< Server: Apache/2.2.22 (Debian)
< Location: https://xy.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI
< Cache-Control: max-age=0
< Expires: Thu, 16 Nov 2017 13:28:25 GMT
< Vary: Accept-Encoding
< Content-Length: 373
< Content-Type: text/html; charset=iso-8859-1
< 
* Ignoring the response-body
* Connection #0 to host xy.eu left intact
* Issue another request to this URL: 'https://xy.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI'
*   Trying xy.71...
* TCP_NODELAY set
* Connected to xy.eu (xy.71) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.xy.eu
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI HTTP/1.1
> Host: xy.eu
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 16 Nov 2017 13:28:25 GMT
< Server: Apache/2.2.22 (Debian)
< Last-Modified: Thu, 16 Nov 2017 13:26:31 GMT
< Accept-Ranges: bytes
< Content-Length: 87
< Cache-Control: max-age=2592000
< Expires: Sat, 16 Dec 2017 13:28:25 GMT
< Content-Type: text/plain
< 
* Connection #1 to host xy.eu left intact
2v85LbJ3u8aEJQCiscjpY0LOrxxLOI.3K58u6N3UQWPdTnrFe2E5OXLhgwkL4G14e2eACNkmsw
```

**Comment by joohoi** [comment] 2017-11-16 13:51
Should the redirect to https://... happen every time or just when content is found? Naturally you have already continued on the process and the token is not there anymore, but this is what I'm seeing, notice the lack of redirect (Location header):

```
▶ curl -v http://xy.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI
*   Trying 195.56.45.187...
* TCP_NODELAY set
* Connected to xy.eu (195.56.45.187) port 80 (#0)
> GET /.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI HTTP/1.1
> Host: xy.eu
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Thu, 16 Nov 2017 13:49:25 GMT
< Server: Apache/2.2.22 (Debian)
< Vary: Accept-Encoding
< Content-Length: 326
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
...
* Connection #0 to host xy.eu left intact
```

**Comment by joohoi** [comment] 2017-11-16 14:07
I can also see your connection going to `xy.71`...
```
$ curl "http://xy.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI" -v -L 
*   Trying xy.71...
```

Could you try the following, which should be essentially the same thing that I'm seeing:

`curl -v http://195.56.45.187/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOI -H "Host: xy.eu"`

**Comment by adrianmihalko** [comment] 2017-11-16 14:09
Sorry, I stripped the keys and removed domain for security.

Let's try again:

https://mihalko.eu/.well-known/acme-challenge/2v85LbJ3u8aEJQCiscjpY0LOrxxLOIMqQ5qkNNfD4jE

This is one of the actual key.

**Comment by joohoi** [comment] 2017-11-16 14:11
Ah, I see, and I think I know what your problem is. 
Let's Encrypt prefers IPv6 over IPv4, and your domain seems to have AAAA record in place.
```
▶ dig mihalko.eu

; <<>> DiG 9.8.3-P1 <<>> mihalko.eu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30451
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mihalko.eu.			IN	A

;; ANSWER SECTION:
mihalko.eu.		334	IN	A	213.215.115.71

;; Query time: 19 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 16 16:10:14 2017
;; MSG SIZE  rcvd: 44


~
▶ dig mihalko.eu aaaa

; <<>> DiG 9.8.3-P1 <<>> mihalko.eu aaaa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65399
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mihalko.eu.			IN	AAAA

;; ANSWER SECTION:
mihalko.eu.		15202	IN	AAAA	2001:1ba0:2a0:5965::115:71:1

;; Query time: 20 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 16 16:10:16 2017
;; MSG SIZE  rcvd: 56
```
So Let's Encrypt tries to connect that one. Are you sure IPv6 is functional on your host?

**Comment by adrianmihalko** [comment] 2017-11-16 14:14
Nope, I think ipv6 is not enabled. Can I set somehow ipv4 for letsencrypt?

**Comment by joohoi** [comment] 2017-11-16 14:15
I don't think you can enforce IPv4. You will have to update your DNS zone and remove AAAA record.

**Comment by joohoi** [comment] 2017-11-16 14:26
Let me know how it goes when you get the AAAA record removed!

**Comment by adrianmihalko** [comment] 2017-11-16 14:29
I will arrive at home in 1-2 hours, I let you know.

**Comment by adrianmihalko** [comment] 2017-11-16 15:48
Congratulations! Your certificate and chain have been saved at... success. Thank you very much.

In previous I had SSLCACertificateFile set in the apache2 config, but Letsencrypt tutorials are writing only about SSLCertificateChainFile. Should I use only this one?

**Comment by joohoi** [comment] 2017-11-17 09:24
Awesome!
If you are configuring your Apache manually, I suggest getting good configuration from:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

As the Certbot side of the issue is solved, I'm going to close this issue as resolved.

**Closed by joohoi** 2017-11-17 09:24 UTC
Labels: more-info
