### ISSUE TITLE
Cerbot generated files better explained

### ISSUE THREAD

**Issue by chrisribe** [certbot/certbot#3925] opened 2016-12-16 15:46 UTC
It would be nice if the setup docs would explain the generated pem files....
Running the ./certbot-auto certonly, generates the required certificates but they are confusing since most configs refer to them as *.key, *.cert etc...

cert.pem  => cert file (*.crt)
chain.pem  => ca file (*.ca)
fullchain.pem => ca file (*.ca) With more info ?
privkey.pem => key file (*.key)

Si I have limited knowledge of the SSL details this was confusing for me when setting up.
I do get that these are "just'" text files, but this was a friction point for me.

Chris

**Ex doc:**
https://certbot.eff.org/#debianwheezy-nginx

**Reference where I found the info:**
https://community.letsencrypt.org/t/how-to-get-crt-and-key-files-from-i-just-have-pem-files/7348

**Comment by pde** [comment] 2016-12-19 22:46
I think this may be a duplicate of #1819, which is is already fixed in Git master and will be shipped in 0.10.0.

**Closed by pde** 2016-12-19 22:46 UTC
Labels: cert management, documentation, duplicate
