### ISSUE TITLE
Support for standalone on servers where Apache listens on a different IP

### ISSUE THREAD

**Issue by dwilson390** [certbot/certbot#2326] opened 2016-01-31 20:53 UTC
Trying to setup a SSL certificate for my hostname, however I run Apache on a different IP than the one the hostname points to and as I wish to automate my renewal process this forces me to use the standalone server option.

However, currently the client does not check the IP in use and only checks if the port is in use on the server.  This means that I am not able to run a standalone server as Apache is currently listening on another IP on the ports 80 & 443.

**Comment by schoen** [comment] 2016-02-01 23:53
Duplicate of #255. Sorry to see that this somewhat ancient issue is causing problems in the wild now.

**Comment by dwilson390** [comment] 2016-02-02 16:50
No problem.  The issue isn't major, I can deal with shutting down Apache for a few seconds every 3 months.  At least you guys are aware of this issue :+1:

**Closed** 2016-06-02 22:52 UTC
