### ISSUE TITLE
Certbot could work harder to get libffi-devel on redhat 6.8

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#3992] opened 2017-01-09 15:45 UTC
https://certbot.eff.org/#centosrhel6-apache

https://www.redhat.com/archives/rhelv6-list/2015-December/msg00001.html

Someone else complained over a year ago on a Red Hat ML about letsencrypt-auto not working out of the box on rhel6.8:
> I am referring to
> https://letsencrypt.readthedocs.org/en/latest/using.html#third-party-plugins
>
> and i am getting *No package libffi-devel available*. Please find below the
> console output. Any help will be highly appreciable.

The "answer" was:
> libffi-devel is in the rhel-x86_64-server-optional-6 channel/repo:

It'd be helpful if either the certbot script dealt with this magic.
There's already magic to try to handle EPEL.

see also https://github.com/certbot/website/issues/183

**Comment by jsoref** [comment] 2017-01-09 15:49
afaict, the magic is: `rhn-channel --add --channel=rhel-x86_64-server-optional-6`

**Comment by rfrht** [comment] 2017-01-14 18:58
I can confirm that it helped in a RHEL 6.

**Comment by bmw** [comment] 2017-02-03 01:26
If you're using `certbot-auto`, you also need EPEL as well correct? If this is the case, I think this is a duplicate of #3433 because we [need to enable the optional repo to enable EPEL](https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F).

**Comment by bmw** [comment] 2019-01-25 00:41
I'm going to close this issue in favor of the larger #3433 which should also solve this problem.

**Closed by bmw** 2019-01-25 00:41 UTC
Labels: area: 3rd party, area: fedora / redhat / CentOS, area: ui / ux, more-info
