### ISSUE TITLE
[Pls Help!] Certbox firing multiple times and restarting at odd time...

### ISSUE THREAD

**Issue by hozza** [certbot/certbot#5197] opened 2017-10-20 16:01 UTC
If anyone can shed some light on this problem I'd be forever grateful! Long-time Linux, first time certbot sys-admin. - doing by best to follow the issue template prompts here too...

Ubuntu 16.04

Installed certbox with apt-get (suggested in Digital Ocean docs)

## How I'm running certbot
certbot auto renew is setup on a cron-job at 03:10 everyday to check (and potentially renew the certificates) using the apache plugin

## Certbot's behavior differed from what I expected because:

the letsencrypt logs show at 3am and then again at **12 noon and also midnight - why is that?**

and my apache server is being gracefully restarted (assuming by the apache plugin, as I've not manually configured it to) at 06:25 on the dot everyday. 

_I've looked through the certbot apache plugin code here on github and it does execute a graceful restart (as it needs to), but there is no mention of a specific time...? **Why would the server restart at 06.25** (only) everyday when certbot is firing at 03.10 (I would guess a varying delay in restart, based on how long certbot took this time, maybe couple mins, but that doesn't match up with 06.25) - and no idea why certbot is also showing logs checking certificates at the other times... :S_

_I've looked through the crontab, nothing in there - also checked the cron directories and no mention of letsencrypt/certbot or anything that would restart apache at 06.25._

## Here is a Certbot log showing the issue (if available):

My (only) cron:

`10 3 * * * /usr/bin/certbot renew --quiet`

apcache logs showing restart time...

```
[Fri Oct 20 06:25:03.814934 2017] [mpm_prefork:notice] [pid 21054] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
```

and in the next apache log file...

```
[Fri Oct 20 06:25:04.493316 2017] [mpm_prefork:notice] [pid 21054] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Oct 20 06:25:04.493387 2017] [core:notice] [pid 21054] AH00094: Command line: '/usr/sbin/apache2'
```

lets encrypt / certbot log from 03.10 (the correct time from cron... assumed graceful restart would happen a couple mins later?)

```
2017-10-20 03:10:01,703:DEBUG:certbot.main:certbot version: 0.14.2
2017-10-20 03:10:01,704:DEBUG:certbot.main:Arguments: ['--quiet']
2017-10-20 03:10:01,704:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
```

lets encrypt / certbot log from 12 noon and 00:00 midnight (have no idea why it's firing then...)

```
2017-10-20 00:22:21,051:DEBUG:certbot.main:certbot version: 0.14.2
2017-10-20 00:22:21,051:DEBUG:certbot.main:Arguments: ['-q']
2017-10-20 00:22:21,051:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
```
```
2017-10-20 12:54:23,070:DEBUG:certbot.main:certbot version: 0.14.2
2017-10-20 12:54:23,071:DEBUG:certbot.main:Arguments: ['-q']
2017-10-20 12:54:23,071:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
``` 
I've only shown logs for 2017-10-20 but it happens every day, and I've only shown the first few lines of logs, if more are needed to help - let me know...

**Comment by bmw** [comment] 2017-10-20 17:58
> the letsencrypt logs show at 3am and then again at 12 noon and also midnight - why is that?

The Certbot packages on Debian based systems comes with a cron job/systemd timer to run Certbot at noon and midnight (with a 1 hour random offset from that time). The crontab is placed at `/etc/cron.d/certbot`. Can you provide a link to the documentation you were following that failed to mention this so we can try and get it updated?

> Why would the server restart at 06.25 (only) everyday 

I'm not sure about this one. As you pointed out, the long delay between Certbot running and Apache starting is very strange. Additionally, Certbot reloads your server only when it needs to which is when it renews your certificate. Most times when `certbot renew` is run, it should simply check the expiration date of your certs, see there's nothing to do, and exit.

A few questions for you:

1. Looking at your logs, can you tell if most runs of Certbot are issuing a new cert or just exiting as I described above? If the former, have you included `force-renewal` in a [Certbot configuration file](https://certbot.eff.org/docs/using.html#configuration-file)?
2. What is the closest timestamp in the Certbot logs to Apache restarting? This will probably be in your logs from 3.10 at the bottom of the file. In every case where we would restart Apache, more logging output should come after that, so I want to rule out the very unlikely possibility of Certbot taking 3+ hours to run.
3. Do you have old enough Apache logs to verify that Apache restarting at 6:25 came with the installation of Certbot and wasn't happening before?

**Comment by hozza** [comment] 2017-10-24 12:20
Thanks very much for the help, you're a life-saver! - found the default cron you mentioned, I did glance through the cron directories on a hunch previously - must have missed it, never did see this in the docs, although I may not have read every word perfectly, perhaps making it more obvious would be an idea? 

I was walking through these docs when trying to solve the issue... (the same?)

http://letsencrypt.readthedocs.io/en/latest/using.html#apache
https://certbot.eff.org/docs/using.html#apache

Setup using the Digital Ocean docs here (https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04) I'll ask them to mention the default crons.

The few answers:

1.  Most of the time a certificate is not renewed, I have about 20 certificates all created and require renewing at the same time roughly.
2. Looks like certbot generally takes fraction of a second to execute (even with renewals).
3. It's a relatively new server and ever since spin-up certbot has been running.

There must be something else causing the 06.25 restart... I'll remove the default cron and I'll look into the restarting further, thanks again for your help!

**Comment by hozza** [comment] 2017-10-24 12:38
accidental close, you may want to leave this open for the docs edit maybe? Your call! :)

**Comment by bmw** [comment] 2017-10-26 15:53
Glad I could help! After investigating further, if you think the 06.25 restart is caused by Certbot, please respond or open another issue.

I've also pinged people at Digital Ocean about getting this updated. I'll leave this issue open until this gets resolved to help make sure it happens!

**Comment by bmw** [comment] 2017-11-09 18:52
Closing this issue as the DigitalOcean article linked above has been fixed.

**Closed by bmw** 2017-11-09 18:52 UTC
Labels: area: apache, area: documentation, area: renewal, more-info
