### ISSUE TITLE
certbot-auto: Your system is not supported by certbot-auto anymore

### ISSUE THREAD

**Issue by ad0nis** [certbot/certbot#8535] opened 2020-12-14 22:32 UTC
Support removed without clear reason or instructions forward. The error message implies that my (operating system? python version? webserver ?  -- don't know because it doesn't say.) is longer supported by certbot, however there are (new) install instructions (https://certbot.eff.org/lets-encrypt/ubuntubionic-apache) which require that I use snap instead of installing from git. The version of certbot from snap then works just fine... Why are the snap vs git installs behaving so differently? Why can I no longer use the git repo successfully, as I've been using it this way for multiple years?

## My operating system is (include version):
Ubuntu Server 18.04.5

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git clone https://github.com/certbot/certbot /opt/letsencrypt

## I ran this command and it produced this output:

root@testbox:/opt/letsencrypt# ./certbot-auto --apache -d subdomain.mytestdomain.tld -n --register-unsafely-without-email --agree-tos
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.

## Certbot's behavior differed from what I expected because:
I've been using certbot-auto to generate/retrieve standalone certs for multiple years in an automation platform I maintain for my team. I expected that I could still keep using this command the same way I have been.

**Comment by aimnadze** [comment] 2020-12-15 07:59
To me this is an example of "when a product is free, then you are a product". On one server I was forced to install snap. On several others I managed to install it via Debian repository. Maybe you could do the same? Or wait for other to reply.

**Comment by fezie** [comment] 2020-12-15 08:12
Changelog says:

> certbot-auto was deprecated on all systems.

Can you please explain why? The git version was working fine until that change on my Debian buster system

**Comment by alexzorin** [comment] 2020-12-15 09:35
Hi all,

There is [a forum post](https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7) which provides a more detailed explanation of the deprecation. I think it will provide answers to each of the questions posted in this issue.

For those for whom installing Certbot from snap is unsuitable, #8422 will provide a way forward with a suitable alternative.

**Comment by MediaMaquina** [comment] 2020-12-30 16:22
It was too easy to use, this way certs issued will be reduced by 99%.

**Comment by adferrand** [comment] 2020-12-30 17:29
I would like to remind that GitHub issues are meant for discussions about improving Certbot or fixing bugs, not for unconstructive complaints.

Since this deprecation needs a constant effort of communication, I would like to remind one or two things about it here.

To build on the explanation linked by @alexzorin previously (https://community.letsencrypt.org/t/certbot-auto-no-longer-works-on-debian-based-systems/139702/7), one have to remind that the limited capacity of the Certbot dev team implies to make choices that will not please everyone. Deprecating certbot-auto that was just too complex to maintain is among these choices.

An expected behavior on this subject is to provide more help or guidance to the current ways to distribute Certbot, for both the ones maintained by the dev team (eg. snaps, https://github.com/certbot/certbot/issues/8422) or externally (eg. PPAs).

I feel that this issue will not contribute to add a new functionality or fix a bug, so I close it.

**Closed by adferrand** 2020-12-30 17:29 UTC
Labels: question

**Comment by akotulu** [comment] 2021-01-02 05:58
certbot-auto is 2000 lines long, conains no spagetty and is well written. Small team or what nat, just incompotent programmers.

**Comment by adferrand** [comment] 2021-01-02 10:21
Per our [code of conduct](https://www.eff.org/pages/eppcode), personal (and misguided) attacks against the project and the community are not tolerated.

I edited a comment because of this.
