### ISSUE TITLE
./letsencrypt-auto --help doesn't print help but starts installing sw without asking

### ISSUE THREAD

**Issue by richfelker** [certbot/certbot#2821] opened 2016-04-12 23:34 UTC
I just watched an otherwise-interested user trying to get started with letsencrypt decide the whole project was not trustworthy after having it start installing packages when asked to print usage information via (as shown in the `README`) `./letsencrypt-auto --help`. This is very bad initial UX. The `--help` option should work as documented (without modifying anything about the system it's run on) and there should either be a strong warning in the `README` that `letsencrypt-auto` invokes the system package manager to install packages, or it should interactively request permission to do so when run without arguments.

**Comment by bmw** [comment] 2016-04-12 23:46
Arguably a duplicate of #1903. If for some reason #1903 isn't fixed, however, we should still certainly update the documentation to make this behavior more clear.

**Comment by lonix** [comment] 2016-04-22 10:05
Experienced this, This is Awful UX, there should not be a warning in the readme, it should simply not behave this way.

**Comment by pde** [comment] 2016-05-10 01:11
Duplicate of #1903 (will be closed fixed in 0.6.0 though)

**Closed by pde** 2016-05-10 01:11 UTC
Labels: documentation, letsencrypt-auto, ui / ux
