### ISSUE TITLE
Can't install certificate due to syntax error in vhost even when no error in vhost

### ISSUE THREAD

**Issue by matthewcarlin** [certbot/certbot#5166] opened 2017-10-04 18:19 UTC
My operating system is Ubuntu 14.04

 I installed Certbot with  sudo add-apt-repository ppa:certbot/certbot, then sudo apt-get update then sudo apt-get install python-certbot-apache

 I ran this command sudo certbot --apache -d example.com  and it produced this output:

Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf.save on line 31: Syntax error',)
root@roastwinner:~# sudo certbot --apache -d roastwinner.co.uk -d www.roastwinner.co.uk -d cdn2.roastwinner.co.uk
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf.save on line 31: Syntax error',)

I'm not sure what's wrong with the syntax though as the server runs ok with that config, my vhost lines that it is referrring to is below if anyone can spot any errors

<files xmlrpc.php>
      order allow,deny
      deny from all
    </files>

Here is a Certbot log showing the issue (
2017-10-04 18:14:23,956:DEBUG:certbot.main:certbot version: 0.17.0
2017-10-04 18:14:23,956:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'roastwinner.co.uk', '-d', 'www.roastwinner.co.uk', '-d', 'cdn2.roastwinner.co.uk']
2017-10-04 18:14:23,956:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-10-04 18:14:23,976:DEBUG:certbot.log:Root logging level set at 20
2017-10-04 18:14:23,976:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-10-04 18:14:23,977:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-10-04 18:14:24,105:DEBUG:certbot_apache.configurator:Apache version is 2.4.7
2017-10-04 18:14:24,354:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf.save on line 31: Syntax error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 197, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/dist-packages/certbot_apache/augeas_configurator.py", line 79, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf.save on line 31: Syntax error
2017-10-04 18:14:24,355:DEBUG:certbot.plugins.selection:No candidate plugin
2017-10-04 18:14:24,355:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

**Comment by bmw** [comment] 2017-10-04 18:21
@joohoi, can you look at this?

**Comment by matthewcarlin** [comment] 2017-10-04 18:30
Am i correct in thinking that maybe if i remove the offending lines temporarily it might install correctly?

**Comment by joohoi** [comment] 2017-10-04 20:23
Looking at the stack trace, looks like the problem is Certbot parsing sites-available/* which includes apparently broken configuration file `000-default.conf.save`. This is fortunately fixed in the just released Certbot version 0.19, however it will most likely take a while to end up in the PPA.

Your workarounds for the issue right now would be:
1) Remove the file /etc/apache2/sites-available/000-default.conf.save
2) Run Certbot with parameter `--apache-vhost-root=/etc/apache2/sites-enabled/` to trick it out of parsing files in sites-available.

**Comment by matthewcarlin** [comment] 2017-10-04 20:33
Thanks for the reply.  I'd seen a similar issue raised and then the reply said it had been fixed in 0.19 but didn't know if that's the version i had installed from running my command.  Thanks for the help and workaround.

**Comment by joohoi** [comment] 2017-10-05 09:08
Glad that I could help! I'll close this issue for now, feel free to add more comments if experiencing similar problems with Certbot version >= 0.19, and I'll reopen the issue.

**Closed by joohoi** 2017-10-05 09:08 UTC
Labels: area: apache
