### ISSUE TITLE
Provide a PEM file that’s equivalent to $(cat privkey.pem fullchain.pem)

### ISSUE THREAD

**Issue by delan** [certbot/certbot#3789] opened 2016-11-13 10:57 UTC
This is normally how I keep all of my services up to date:

1. `chmod g+rx archive live`
2. `usermod -aG [Certbot group] [service user]` (`-G` on OpenBSD)
3. `ln -s live/…/… some/other/path.pem` where necessary

Many services ask you to provide the server’s certificate in two files: `fullchain.pem` (`$(cat cert.pem chain.pem)`) and `privkey.pem`. Dare I say most services? OpenLDAP is the only one, off the top of my head, that asks you to provide three files.

I’ve found at least two services ([ZNC](http://wiki.znc.in/Signed_SSL_certificate#General_advice) and [ejabberd](https://docs.ejabberd.im/admin/configuration/#options)) that ask you to provide this information in just one file, and in the same order (`$(cat privkey.pem cert.pem chain.pem)`).

To keep these services up to date, my cron job generates a `live/…/full.pem` by combining the other three files, and I’ve replaced their single PEM files with a symbolic link.

When I have some more free time, I’m open to writing a patch to make Certbot generate such a file, but for now, I’ll open this issue to find out whether or not it’s a desirable feature.

**Comment by maugsburger** [comment] 2016-11-13 11:37
probably duplicate of #1201

**Comment by pde** [comment] 2016-11-16 19:55
Yup, this is a duplicate.

**Closed by pde** 2016-11-16 19:55 UTC
Labels: duplicate
