### ISSUE TITLE
/var/log/letsencrypt/letsencrypt.log missing?

### ISSUE THREAD

**Issue by cedw93** [certbot/certbot#1091] opened 2015-10-23 11:30 UTC
I am attempting to generate a certificate for `*.test.local.com`

I am on Mac OS X Yosemite (10.10.4) and I am running the following:

`./letsencrypt-auto auth`

and I follow the prompts on screen and after I enter the domain `*.test.local.com` the following error pops up:

```
 An unexpected error occurred.
 Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax    error
 Please see the logfiles in /var/log/letsencrypt for more details.
```

But the contents of `/var/log/letsencrypt' is empty. 

I thought it might be a permission problem so I attempted to the as `sudo` however I got errors similar to the following:

```
The directory '/Users/intilery/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

So I added `-H` to the command and `brew` refused to run the application:

```
Bootstrapping dependencies for Mac OS X...
WARNING: Mac support is very experimental at present...
Error: Cowardly refusing to `sudo brew install`
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

Is this a known issue, or is there a solution?

**Comment by bmw** [comment] 2015-10-23 16:07
The syntax error is due to Let's Encrypt not currently supporting wildcard certificates. From the [FAQ](https://community.letsencrypt.org/t/frequently-asked-questions-faq/26):

> Will Let’s Encrypt issue wildcard certificates?
>
> We currently have no plans to do so, but it is a possibility in the future. Hopefully wildcards aren’t necessary for the vast majority of our potential subscribers because it should be easy to get and manage certificates for all subdomains.

As for the logs, the client should have errored out with a message like `IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'`. If that directory is empty, you could try deleting it and running the client again. A temporary workaround is to specify a different location for logfiles. To do this, simply include `--logs-dir /path/to/wherever` on the command line.

There is no need to run `letsencrypt-auto` as `sudo` (in fact, you shouldn't do it). The script knows which commands it executes require `sudo` and prompt you accordingly.

Sorry for the trouble! If you could try deleting `/var/log/letsencrypt`, running the client again, and reporting back if the logfiles are created, I'd appreciate it. It may be a new bug for Let's Encrypt OS X.

**Comment by cedw93** [comment] 2015-10-23 16:23
Hi thanks for the response, I tried deleting `/var/log/letsencypt` and reproduced the error above and the log directory remained empty.

**Comment by bmw** [comment] 2015-10-23 16:39
So the directory was recreated but without any logfiles? That's a new OS X bug for us. Thanks for the report @cedw93. I'll file an issue later today.

**Comment by kuba** [comment] 2015-10-23 17:36
@cedw93, could you please run `./letsencrypt-auto -vvvvv --text` and past the entire output? Somewhere there should be a line similar to this:

```
2015-10-21 20:02:55,690:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2
```

**Comment by cedw93** [comment] 2015-10-26 10:05
@kuba Sorry for the late reply had to go away this weekend here is the output:

```
./letsencrypt-auto auth  -vvvvv --text
-vvvvv
-n Updating letsencrypt and virtual environment dependencies...

Requirement already up-to-date: setuptools in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt-apache in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: zope.interface in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: acme==0.0.0.dev20151024 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: requests in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: six in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: mock in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: ConfigArgParse in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt-apache)
Requirement already up-to-date: pyasn1 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: werkzeug in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: enum34 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: idna>=2.0 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pycparser in /Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Running with virtualenv: sudo /Users/intilery/.local/share/letsencrypt/bin/letsencrypt auth -vvvvv --text
2015-10-26 09:58:28,887:DEBUG:letsencrypt.cli:Root logging level set at -20
2015-10-26 09:58:28,889:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-10-26 09:58:28,890:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151024
2015-10-26 09:58:28,890:DEBUG:letsencrypt.cli:Arguments: ['auth', '-vvvvv', '--text']
2015-10-26 09:58:28,891:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)

-------------------------------------------------------------------------------
This is a PREVIEW RELEASE of a client application for the Let's Encrypt
certificate authority and other services using the ACME protocol. The Let's
Encrypt certificate authority is NOT YET ISSUING CERTIFICATES TO THE PUBLIC.

Until publicly-trusted certificates can be issued by Let's Encrypt, this
software CANNOT OBTAIN A PUBLICLY-TRUSTED CERTIFICATE FOR YOUR WEB SERVER.  You
should only use this program if you are a developer interested in experimenting
with the ACME protocol or in helping to improve this software.  If you want to
configure your web site with HTTPS in the meantime, please obtain a certificate
from a different authority.

For updates on the status of Let's Encrypt, please visit the Let's Encrypt home
page at https://letsencrypt.org/.
-------------------------------------------------------------------------------
(A)gree/(C)ancel: a
2015-10-26 09:58:30,592:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-10-26 09:58:31,243:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache): 
Traceback (most recent call last):
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-10-26 09:58:31,267:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 50, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-10-26 09:58:31,267:DEBUG:letsencrypt.display.ops:Multiple candidate plugins: * manual
Description: Manual Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: manual = letsencrypt.plugins.manual:Authenticator
Initialized: <letsencrypt.plugins.manual.Authenticator object at 0x107796650>
Prep: True

* standalone
Description: Standalone Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x1077963d0>
Prep: True

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Manual Authenticator (manual)
2: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
2015-10-26 09:58:36,304:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.manual.Authenticator object at 0x107796650> and installer None
2015-10-26 09:58:36,418:DEBUG:letsencrypt.cli:Picked account: <Account(bce3e4604ea291fe08c5c5a0c35d47bc)>
2015-10-26 09:58:36,419:DEBUG:root:Sending GET request to https://acme-staging.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-10-26 09:58:36,465:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2015-10-26 09:58:37,175:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 279
2015-10-26 09:58:37,180:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '279', 'Expires': 'Mon, 26 Oct 2015 09:58:36 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 26 Oct 2015 09:58:36 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '7QB1TSC9ekNzFy_u6w9GVFuNXJ8yYkbOeoVJwVSctXI'}. Content: '{"new-authz":"https://acme-staging.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-26 09:58:37,180:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '279', 'Expires': 'Mon, 26 Oct 2015 09:58:36 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 26 Oct 2015 09:58:36 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '7QB1TSC9ekNzFy_u6w9GVFuNXJ8yYkbOeoVJwVSctXI'}): '{"new-authz":"https://acme-staging.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-staging.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-staging.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-staging.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-26 09:58:37,181:DEBUG:letsencrypt.display.ops:No installer, picking names manually
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel):*.ops.intilery.com
2015-10-26 09:58:48,573:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0012_key-letsencrypt.pem
2015-10-26 09:58:48,616:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0012_csr-letsencrypt.pem
2015-10-26 09:58:48,617:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0012_csr-letsencrypt.pem', data='0\x82\x02\x920\x82\x01z\x02\x01\x000\x1d1\x1b0\x19\x06\x03U\x04\x03\x0c\x12*.ops.intilery.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xbe\xa7\xcfjpf\x02$\x14\xfa_^oU@9]\xaf\xd3L6\xdd\x02}\xe6\xe1\xed\x13J\x83%\xbc\x93_\xfd\xc6/\x10\x93_\x06mF*\xb5LD\xfb\x14-\x031\xacp`\x17/n\xb7P\xbdM\xe6K-\n\xdf8\xedX|Y\x1c[6\x8a\x86\xc3\xf2\x8b\xf7\x88\xfe\xcc\xae\x16g\xbe\x887o\xc2\xb8\xfd_NS/=\xd0F\x93\xd8GLF\xd8C\xe1\xe0a\x88\xba\x13\x1a\xe1]<\xf7\x1f\xe1d\xec:\x07\x03@\x8a\xa5\x15\xb1\x81\xb5;\xa3\x8a\x01\x8c\x0f\x10\xed\xea\xfb\xaf\n\xc9\xddh3\xf6\x0b\xcf\xdd\x97\xf7\xc10\xa2\x9c\x98r}\x19\xe1|I\xb8\xff\xf5y\x17\xfd\n\xd8\x1f\x15\xcc\x1e\x80\xafQ\xd1\xdc\xcd\xd8\x1f\xd6\x1b\x18F\xc7\x14h\xfa\xe9\x19\x0c9Y\xb0m\xe8\xe5-\x03\xbe\x1a*\xbbi\xc7\x84y\xe5\x7f\x0fQ\x9e\xfdf\xa7\xa0\xd6\x9c\xa8\xf75+\xcc\xf7\xca\xcd+\xf4\x1f\xf1e(\xca\xbf\x0c\xf0"\xc74n\xdd\xdc\xa3\xcc\xf9\xe6\xd8X\xcd1\x02\x03\x01\x00\x01\xa000.\x06\t*\x86H\x86\xf7\r\x01\t\x0e1!0\x1f0\x1d\x06\x03U\x1d\x11\x04\x160\x14\x82\x12*.ops.intilery.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\x9d\x84\x1c\x14{:\xc7\xe9\x85\xcb-\xa5X\x9a\xe6X\x8cA*m\x02w\xbe\xb7X\xe1\x8a\xf4\xa8H\xc4\xf3t\xd3\'me\x9b\x8bDfL\xff\x10\xd9"E\xec\xfb\xf1\x99\x8e\xbd\x99\xf9\x97\xc3\xc5\xe5\x19Vn6\x10\xfa\x17\xf9dg\xeaB\xfc8\x8dR+\xd6\x08\xfe7\\E\xda`+:\xee\x82\x9b\x99\xee\xcc\x07>\xae]\x8bL\x1eT@\xa7\x06\xcb\xcd\x84\xd6\xc0\xde\x8c.\xb8\xd3M\x1d\xcf\x82T#jUhu\xa5\xf5\t+$\x86_\xcc\x94\xaf\xb2\x96\xfe\x0b\xe2\x84\xe3\x94\xbe\x02\xa0\xf2_\xe9M\xe6J\xcc]\xe0\xd2\xb4\xd1\x81\xc7<#\xb8#\x961b\x1e\xba\xb4\x1b\xe7F\x8dl\xd0\xd5\xca\x19\x0cy\xb65bIA\xa4\'d\xe6\xba\x88K\xfb\x8e\xec\xf0\xf4\x9a\xc9\xc0:84Q\x19\x14z5U\xd7{W!{\xf0&d\x9f\xf5i\x86\x03H3a>(\xb8&\xf1i\xfd3\xa0#O\x13\xd8\xbc\xf8\xe3\xeb\x12C\xfc\'\xdb\xc3`\xffL\xd3h\x9b\x85p\'', form='der'), domains: ['*.ops.intilery.com']
2015-10-26 09:58:48,618:DEBUG:root:Requesting fresh nonce
2015-10-26 09:58:48,618:DEBUG:root:Sending HEAD request to https://acme-staging.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-10-26 09:58:48,620:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2015-10-26 09:58:48,870:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-10-26 09:58:48,875:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'U3W36bUU68ikDRf7XuYWC6GC90SoISmB2cYmi3MQfvk'}. Content: ''
2015-10-26 09:58:48,875:DEBUG:acme.client:Storing nonce: 'Su\xb7\xe9\xb5\x14\xeb\xc8\xa4\r\x17\xfb^\xe6\x16\x0b\xa1\x82\xf7D\xa8!)\x81\xd9\xc6&\x8bs\x10~\xf9'
2015-10-26 09:58:48,876:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2015-10-26 09:58:48,876:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "*.ops.intilery.com"}, "resource": "new-authz"}
2015-10-26 09:58:48,877:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), jwk=None, alg=None, typ=None, x5t=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None
2015-10-26 09:58:48,880:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), x5t=None, typ=None, nonce=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None
2015-10-26 09:58:48,880:DEBUG:root:Sending POST request to https://acme-staging.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "zfJdlFAMB1Gnhy1t6jowfGnf6j35OntDWeo089eylLPIi7P4GwksQ8npmVF2cXQh--E8ff4-7LOZzornpGHFpJjrVpmKBO7UvypdZRNIA4CMR98mEC4qF-28xuIRBbhm65y6Ba7pVuHmkTNc1ybbw2HXhIyJCNgA47VjGYCgvJmE6FM4ZPlT6RnP2HXZ5NKOV2Saj1xGe8cVN1jTfjaLgVOnDYHYr0cL7sE1dullPeAlZtlb3WwzXMeAGL4smTd5kZ4tyv2qgPHIBE7ewIRCNH5HanlVW4DvGq0hSRlFSYX4-FIAG0fYgFzfyDVJiJS3EnpI7UWFaJMom0j1WrZyTQ"}}, "protected": "eyJub25jZSI6ICJVM1czNmJVVTY4aWtEUmY3WHVZV0M2R0M5MFNvSVNtQjJjWW1pM01RZnZrIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICIqLm9wcy5pbnRpbGVyeS5jb20ifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "Iq5SxPc8pp20VvZkYdYVQaYq2ankRnEDLC3ojh-VCOqarLH49dfuJrbXNbM6ywcDDrAXMAlNYund4XV34BukhjUaM5I1C-8ciBRjeK8C4eaHwEx9dYTTj3EFDQsAVzxxwB-aNdXjAa2SBeuXsQCe6oD3Fg7m_joRQ_i6U-7iWYvQfqpsqXapDKXRTuMTkHz-pZvDMF305EX729kUak0tlT7X1nArV9eiV1JIlDRWACjXlQBW9vM-4Y6bdAhUjTnEYL_m9ofYmOpAlL9p7UNHBOpWb3ApSJiBbGK1pGaWHimBG9w7ng0konl8IomYpsGQclh5sNTu-Oi0T1SgB0gpqA"}'}
2015-10-26 09:58:48,882:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2015-10-26 09:58:49,106:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 403 90
2015-10-26 09:58:49,111:DEBUG:root:Received <Response [403]>. Headers: {'Content-Length': '90', 'Expires': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'YHHxh6HW7qHyZtayPENDB1UgFEhpFRLUY0IjfJZX9pw'}. Content: '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Syntax error"}'
2015-10-26 09:58:49,111:DEBUG:acme.client:Storing nonce: '`q\xf1\x87\xa1\xd6\xee\xa1\xf2f\xd6\xb2<CC\x07U \x14Hi\x15\x12\xd4cB#|\x96W\xf6\x9c'
2015-10-26 09:58:49,111:DEBUG:acme.client:Received response <Response [403]> (headers: {'Content-Length': '90', 'Expires': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 26 Oct 2015 09:58:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'YHHxh6HW7qHyZtayPENDB1UgFEhpFRLUY0IjfJZX9pw'}): '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Syntax error"}'
2015-10-26 09:58:49,139:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/intilery/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1097, in main
    return args.func(args, config, plugins)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 473, in auth
    _auth_from_domains(le_client, config, domains, plugins)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 313, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/Users/intilery/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error

An unexpected error occurred.
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error
Please see the logfiles in /var/log/letsencrypt for more details.

```

I used a wildcard domain just to be consistent with the use case which caused this issue. As you can the line `2015-10-26 09:58:28,889:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log`.

It might be an issue my side and not with the client, I've had a few similar problems like that. My machine is set up weirdly and is pretty rubbish in performance.

**Comment by kuba** [comment] 2015-10-29 22:26
So despite this line, `/var/log/letsencrypt/` is empty? Can't be true! :(

**Comment by bmw** [comment] 2018-09-13 21:19
This shouldn't be possible now so I'm closing this issue. If anyone can reproduce with an up to date version of Certbot, please let me know!

**Closed by bmw** 2018-09-13 21:19 UTC
Labels: area: macOS, more-info

**Comment by hustontrevor** [comment] 2024-06-10 19:28
First Google hit for this.  I'm also missing the letsencrypt log file mentioned in the add-on's log tab.  
I can use File Editor to navigate to /var/log/ but it's empty.

I could not get my https working so I'm doing a fresh install on my Raspberry Pi 4.
I was hoping that would cause the log file to show up, but it's still not there. 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:16:45] INFO: Selected DNS Provider: dns-duckdns
[14:16:45] INFO: Use propagation seconds: 60
[14:16:46] INFO: Detecting existing certificate type for XXXXXXXX.duckdns.org
Saving debug log to /var/log/letsencrypt/letsencrypt.log
[14:16:49] INFO: No certificate found - using 'ecdsa' key type.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for XXXXXXXX.duckdns.org
All nameservers failed to answer the query XXXXXXXX.duckdns.org. IN TXT: Server Do53:127.0.0.11@53 answered SERVFAIL
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`
