### ISSUE TITLE
certbot renew `An authentication script must be provided with --manual-auth-hook`

### ISSUE THREAD

**Issue by moficodes** [certbot/certbot#7489] opened 2019-11-01 18:17 UTC
## My operating system is (include version):
MacOS Catalina

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
homebrew

## I ran this command and it produced this output:
`sudo certbot renew --force-renew`

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.dev.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
Attempting to renew cert (domain.dev) from /etc/letsencrypt/renewal/domain.dev.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.'). Skipping.
```

## Certbot's behavior differed from what I expected because:

I thought this command will renew the certs.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2019-11-01 14:08:00,323:DEBUG:certbot.main:certbot version: 0.39.0
2019-11-01 14:08:00,324:DEBUG:certbot.main:Arguments: ['--force-renew']
2019-11-01 14:08:00,324:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-11-01 14:08:00,363:DEBUG:certbot.log:Root logging level set at 20
2019-11-01 14:08:00,364:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-11-01 14:08:00,402:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x10ac66a50> and installer <certbot.cli._Default object at 0x10ac66a50>
2019-11-01 14:08:00,423:DEBUG:certbot.renewal:Auto-renewal forced with --force-renewal...
2019-11-01 14:08:00,423:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2019-11-01 14:08:00,427:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#manual): An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/plugins/manual.py", line 90, in prepare
    self.option_name('auth-hook')))
certbot.errors.PluginError: An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.
2019-11-01 14:08:00,428:DEBUG:certbot.plugins.selection:No candidate plugin
2019-11-01 14:08:00,428:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2019-11-01 14:08:00,428:INFO:certbot.main:Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
2019-11-01 14:08:00,429:WARNING:certbot.renewal:Attempting to renew cert (domain.dev) from /etc/letsencrypt/renewal/domain.dev.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.'). Skipping.
2019-11-01 14:08:00,431:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/renewal.py", line 449, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/main.py", line 1202, in renew_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/plugins/selection.py", line 235, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/local/Cellar/certbot/0.39.0/libexec/lib/python3.7/site-packages/certbot/plugins/selection.py", line 339, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
certbot.errors.PluginSelectionError: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not using soomething like this.

**Comment by alexzorin** [comment] 2019-11-01 22:27
Certificates that are created using `--manual` (and without an authentication hook) cannot be automatically renewed. This is because it involves you performing the the authorization steps by hand, which is not something that Certbot can automatically repeat at renewal time.

Usually you will want to use an authenticator other than the manual one (such as `--apache`, `--nginx`, `--webroot`, `--standalone`), so that Certbot can perform automatic renewal.

If you want to perform the manual authorization process again, then you will need to repeat the original command you used. For example:

    certbot certonly --manual -d domain.dev

If you would like further help with getting renewal working, please create a thread on https://community.letsencrypt.org .

**Comment by bmw** [comment] 2019-11-04 18:18
I think this is a duplicate of https://github.com/certbot/certbot/issues/7227 so I'm closing the issue.

**Closed by bmw** 2019-11-04 18:18 UTC
