### ISSUE TITLE
centos 6.8 / apache / unable to renew

### ISSUE THREAD

**Issue by bll123** [certbot/certbot#5272] opened 2017-11-28 21:10 UTC
## My operating system is (include version):

CentOS 6.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

It is version 0.19.0.  
The same error was produced with python 2.6; I installed python 2.7 and still the same.
Also tried version 0.16.0 as it appeared one other person had success with that version,
but the same error.

## I ran this command and it produced this output:

```
[root@shop ~]# ./certbot-auto renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/admin.goblanket.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for admin.goblanket.com
tls-sni-01 challenge for shop.goblanket.com
Cleaning up challenges
Attempting to renew cert (admin.goblanket.com) from /etc/letsencrypt/renewal/admin.goblanket.com.conf produced an unexpected error: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/admin.goblanket.com/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/admin.goblanket.com/fullchain.pem (failure)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

tail end of log file:
```
2017-11-28 20:45:55,461:DEBUG:certbot.reverter:Creating backup of /etc/httpd/conf/httpd.conf
2017-11-28 20:45:56,043:DEBUG:certbot_apache.configurator:Setting VirtualHost at 66.151.36.94:443 to be a name based virtual host
2017-11-28 20:45:56,046:DEBUG:certbot_apache.configurator:Setting 66.151.36.94:443 to be NameBasedVirtualHost
	Directive added to None

2017-11-28 20:45:56,621:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1919, in perform
    sni_response = chall_doer.perform()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/tls_sni_01.py", line 80, in perform
    self.configurator.make_addrs_sni_ready(addrs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 821, in make_addrs_sni_ready
    if not self.is_name_vhost(addr):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 675, in is_name_vhost
    self.parser.find_dir("NameVirtualHost", str(target_addr)))
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 358, in find_dir
    self._get_include_path(self.get_arg(match + "/arg")),
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 473, in _get_include_path
    self.parse_file(arg)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 526, in parse_file
    self.configurator.ensure_augeas_state()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 87, in ensure_augeas_state
    self.save()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 147, in save
    self.save_notes, temporary=temporary)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/plugins/common.py", line 135, in add_to_checkpoint
    raise errors.PluginError(str(err))
PluginError: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf

2017-11-28 20:45:56,622:DEBUG:certbot.error_handler:Calling registered functions
2017-11-28 20:45:56,622:INFO:certbot.auth_handler:Cleaning up challenges
2017-11-28 20:45:57,622:WARNING:certbot.renewal:Attempting to renew cert (admin.goblanket.com) from /etc/letsencrypt/renewal/admin.goblanket.com.conf produced an unexpected error: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf. Skipping.
2017-11-28 20:45:57,624:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/renewal.py", line 425, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 743, in renew_cert
    _get_and_save_cert(le_client, config, lineage=lineage)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 80, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/renewal.py", line 297, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1919, in perform
    sni_response = chall_doer.perform()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/tls_sni_01.py", line 80, in perform
    self.configurator.make_addrs_sni_ready(addrs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 821, in make_addrs_sni_ready
    if not self.is_name_vhost(addr):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 675, in is_name_vhost
    self.parser.find_dir("NameVirtualHost", str(target_addr)))
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 358, in find_dir
    self._get_include_path(self.get_arg(match + "/arg")),
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 473, in _get_include_path
    self.parse_file(arg)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/parser.py", line 526, in parse_file
    self.configurator.ensure_augeas_state()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 87, in ensure_augeas_state
    self.save()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 147, in save
    self.save_notes, temporary=temporary)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/plugins/common.py", line 135, in add_to_checkpoint
    raise errors.PluginError(str(err))
PluginError: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf

2017-11-28 20:45:57,624:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2017-11-28 20:45:57,625:ERROR:certbot.renewal:  /etc/letsencrypt/live/admin.goblanket.com/fullchain.pem (failure)
2017-11-28 20:45:57,705:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 797, in renew
    renewal.handle_renewal_request(config)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/renewal.py", line 443, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

[root@shop httpd]# pwd
/etc/httpd
[root@shop httpd]# egrep '^Name' conf/httpd.conf

conf.d/ssl-eclogue.conf:

```
# shop.goblanket.com
<VirtualHost 66.151.36.94:443>
  DocumentRoot "/home/www/apache/htdocs"
  ServerName 66.151.36.94:443

...

  SSLCertificateFile /etc/letsencrypt/live/admin.goblanket.com/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/admin.goblanket.com/privkey.pem
ServerAlias admin.goblanket.com
SSLCertificateChainFile /etc/letsencrypt/live/admin.goblanket.com/chain.pem
</VirtualHost>

# admin.goblanket.com
<VirtualHost 66.151.32.156:443>
  DocumentRoot "/home/www/apache/htdocs"
  ServerName 66.151.32.156:443

...

  SSLCertificateFile /etc/letsencrypt/live/admin.goblanket.com/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/admin.goblanket.com/privkey.pem
  ServerAlias shop.goblanket.com
SSLCertificateChainFile /etc/letsencrypt/live/admin.goblanket.com/chain.pem
</VirtualHost>

```

**Comment by SwartzCr** [comment] 2017-11-29 00:03
@joohoi do you think this is something you might have an idea about?

**Comment by joohoi** [comment] 2017-11-29 17:50
Certainly! Thanks for the bug report @bll123 . 

This definitely looks like a bug, and I know what's triggering it under the hood, however I'm unable to reproduce it in my test environment. If any way possible, could you send your Apache configuration to me: joona.hoikkala@eff.org to get a better understanding what's going on, to fix the bug and to provide you with a possible workaround.

**Comment by joohoi** [comment] 2017-11-30 14:48
Thank you for the configuration example! For some reason I'm still unable to reproduce, but have a fairly  good idea about the underlying issue, which I'll work to fix in the coming days.

**Comment by bll123** [comment] 2017-12-11 15:34
Workaround: version 0.15.0 worked.

**Comment by SwartzCr** [comment] 2017-12-13 23:47
That's great to hear @bll123 
@joohoi feel free to close this if you can't reproduce it or if you feel like you've solved the root cause

**Comment by joohoi** [comment] 2017-12-14 08:28
I prefer keeping it open for the time being to see if others might hit it. There has been many structural changes in between 0.15 and 0.19 and I have a looming fear of regression bug somewhere along the line, regardless of me being unable to reproduce the problem.

**Comment by sardanap** [comment] 2017-12-22 09:50
Hi  joohoi,

same problem here:
CentOS release 6.9 (Final)
python 34 (from CentOS SCL)

certbot-auto renew --dry-run --debug  
Traceback (most recent call last):
  File "/tmp/tmp.uzOIr6yoFA/fetch.py", line 23, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler
ImportError: No module named 'urllib2'
WARNING: unable to check for updates.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/accademiajuris.it.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for accademiajuris.it
tls-sni-01 challenge for cinziabini.it
tls-sni-01 challenge for dikegiuridica.it
tls-sni-01 challenge for diventareavvocato.com
tls-sni-01 challenge for diventareavvocato.it
tls-sni-01 challenge for diventaremagistrato.com
tls-sni-01 challenge for diventaremagistrato.it
tls-sni-01 challenge for geoide.dikegiuridica.it
tls-sni-01 challenge for ildirittopericoncorsi.it
tls-sni-01 challenge for ilnuovodirittoamministrativo.it
tls-sni-01 challenge for ilnuovodirittocivile.it
tls-sni-01 challenge for italiappalti.it
tls-sni-01 challenge for new.dikegiuridica.it
tls-sni-01 challenge for obiettivoavvocato.com
tls-sni-01 challenge for obiettivoavvocatura.com
tls-sni-01 challenge for obiettivoavvocatura.it
tls-sni-01 challenge for obiettivomagistratura.com
tls-sni-01 challenge for obiettivomagistratura.it
tls-sni-01 challenge for srv1021358-1.cloud.colt-engine.it
tls-sni-01 challenge for webmail.cinziabini.it
tls-sni-01 challenge for webmail.diventareavvocato.it
tls-sni-01 challenge for webmail.diventaremagistrato.it
tls-sni-01 challenge for webmail.ildirittopericoncorsi.it
tls-sni-01 challenge for webmail.ilnuovodirittocivile.it
tls-sni-01 challenge for webmail.italiappalti.it
tls-sni-01 challenge for webmail.new.dikegiuridica.it
tls-sni-01 challenge for www.accademiajuris.it
tls-sni-01 challenge for www.cinziabini.it
tls-sni-01 challenge for www.dikegiuridica.it
tls-sni-01 challenge for www.diventareavvocato.com
tls-sni-01 challenge for www.diventareavvocato.it
tls-sni-01 challenge for www.diventaremagistrato.com
tls-sni-01 challenge for www.diventaremagistrato.it
tls-sni-01 challenge for www.geoide.dikegiuridica.it
tls-sni-01 challenge for www.ildirittopericoncorsi.it
tls-sni-01 challenge for www.ilnuovodirittoamministrativo.it
tls-sni-01 challenge for www.ilnuovodirittocivile.it
tls-sni-01 challenge for www.italiappalti.it
tls-sni-01 challenge for www.new.dikegiuridica.it
tls-sni-01 challenge for www.obiettivoavvocato.com
tls-sni-01 challenge for www.obiettivoavvocatura.com
tls-sni-01 challenge for www.obiettivoavvocatura.it
tls-sni-01 challenge for www.obiettivomagistratura.com
tls-sni-01 challenge for www.obiettivomagistratura.it
Cleaning up challenges
Attempting to renew cert (accademiajuris.it) from /etc/letsencrypt/renewal/accademiajuris.it.conf produced an unexpected error: Attempting to overwrite challenge file - /etc/httpd/conf/httpd.conf. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/accademiajuris.it/fullchain.pem (failure)

-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/accademiajuris.it/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
-------------------------------------------------------------------------------
Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.7.0', 'console_scripts', 'letsencrypt')()
  File "/opt/eff.org/certbot/venv/lib/python3.4/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib/python3.4/site-packages/certbot/main.py", line 797, in renew
    renewal.handle_renewal_request(config)
  File "/opt/eff.org/certbot/venv/lib/python3.4/site-packages/certbot/renewal.py", line 443, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)
Please see the logfiles in /var/log/letsencrypt for more details.
[letsencrypt.log](https://github.com/certbot/certbot/files/1582113/letsencrypt.log)

I'll email you my complete http configuration

**Comment by joohoi** [comment] 2017-12-22 11:43
@sardanap The logs look somewhat confusing to me. You seem to have the recent version of certbot-apache plugin installed, and running, but 
`load_entry_point('letsencrypt==0.7.0', 'console_scripts', 'letsencrypt')()` in the logs suggests that the version being run is an really old version. 

Also the actual error you are receiving seems to complain about being unable to write to `/etc/httpd/conf/httpd.conf` so it could be an permission issue as well.

Have you tried installing certbot, or in this case letsencrypt previously using `pip`? If so, please uninstall that version to ensure integrity.

**Comment by sardanap** [comment] 2017-12-22 15:08
i did a clean up and deleted a "rogue" /etc/letsencrypt/renewal/accademiajuris.it.conf and now it works 👍

**Comment by fitzn** [comment] 2018-03-02 02:00
@joohoi Any update on this? I am hitting this as well. 
```
$ ./certbot-auto --version
Requesting to rerun ./certbot-auto with root privileges...
certbot 0.21.1
```

**Comment by fitzn** [comment] 2018-03-05 00:12
@bll123 Did you end up working-around this issue or are you still waiting for a fix?

**Comment by fitzn** [comment] 2018-03-05 02:15
Thanks, @bll123. I got it working with 0.15.0 as well, but it didn't work with `certbot-auto`. I sued the command directly:
```
sudo ./letsencrypt-auto --no-bootstrap --no-self-upgrade renew
```
And that worked. Thanks, again.

**Comment by bmw** [comment] 2019-04-18 18:44
I think there are many different issues occurring in the thread here. If you're still having trouble using Certbot, I recommend posting to https://community.letsencrypt.org where there is a large community of people familiar with the project who would be happy to help you.

**Closed by bmw** 2019-04-18 18:44 UTC
Labels: area: apache, bug, more-info
