### ISSUE TITLE
The error was: PluginError('There has been an error in parsing the file ...

### ISSUE THREAD

**Issue by wioxjk** [certbot/certbot#4025] opened 2017-01-11 21:30 UTC
Tried to install LE on one server.
Ubuntu 16.04 (already tried the packages "letsencrypt" from the repo)

Decided to try certbot.sh because it always works.
Got this error.

`2017-01-11 21:28:25,214:DEBUG:certbot.main:Root logging level set at 20
2017-01-11 21:28:25,216:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-01-11 21:28:25,217:DEBUG:certbot.main:certbot version: 0.10.0
2017-01-11 21:28:25,217:DEBUG:certbot.main:Arguments: ['--apache']
2017-01-11 21:28:25,218:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-01-11 21:28:25,218:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-01-11 21:28:25,695:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/sites-enabled/000-default.conf on line 47: Syntax error
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 191, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-enabled/000-default.conf on line 47: Syntax error
2017-01-11 21:28:25,697:DEBUG:certbot.plugins.selection:No candidate plugin
2017-01-11 21:28:25,697:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
`

**Comment by bmw** [comment] 2017-01-11 21:39
Our Apache plugin thinks there is a syntax error on like 47 of `/etc/apache2/sites-enabled/000-default.conf`. What is on that line?

**Comment by wioxjk** [comment] 2017-01-11 22:00
Only this:
`</VirtualHost>
`

**Comment by wioxjk** [comment] 2017-01-11 22:02
`VirtualHost *:80>
	ServerName subdomain.domaintld
	ServerAlias subdomain.domain.tld
	ServerAdmin email
	DocumentRoot /var/www/html
	ProxyRequests off
        RewriteEngine on
        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
        #Proxy for DYNMAP
        ProxyPass "/map"                "http://127.0.0.1:8123/"
        ProxyPass "/js"                 "http://127.0.0.1:8123/js/"
        ProxyPass "/js/minecraft"       "http://127.0.0.1:8123/js/minecraft/"
        ProxyPass "/js/map"             "http://127.0.0.1:8123/js/map/"
        ProxyPass "/css"                "http://127.0.0.1:8123/css/"
        ProxyPass "/standalone"         "http://127.0.0.1:8123/standalone"
        ProxyPass "/up/configuration"   "http://127.0.0.1:8123/up/configuration"
        ProxyPass "/up/sendmessage"     "http://127.0.0.1:8123/up/sendmessage"
        ProxyPass "/up/login"   "http://127.0.0.1:8123/up/login"
        ProxyPass "/up/register"        "http://127.0.0.1:8123/up/register"
        ProxyPass "/version.js"         "http://127.0.0.1:8123/version.js"
        ProxyPass "/images"             "http://127.0.0.1:8123/images/"
        ProxyPass "/tiles/world/t"      "http://127.0.0.1:8123/tiles/world/t"
        ProxyPass "/tiles"      "http://127.0.0.1:8123/tiles"
        ProxyPass "/tiles/world/ct"      "http://127.0.0.1:8123/tiles/world/ct"
        ProxyPass "/tiles/world/t_day"  "http://127.0.0.1:8123/tiles/world/t_day"
        ProxyPass "/tiles/world_nether/nt"      "http://127.0.0.1:8123/tiles/world_nether/nt"
        ProxyPass "/tiles/world_nether/flat"      "http://127.0.0.1:8123/tiles/world_nether/flat"
        ProxyPass "/tiles/world_the_end/st"      "http://127.0.0.1:8123/tiles/world_the_end/st"
        ProxyPass "/tiles/Amplified/ct"         "http://127.0.0.1:8123/tiles/Amplified/ct"
        ProxyPass "/tiles/Amplified/t"          "http://127.0.0.1:8123/tiles/Amplified/t"
        ProxyPass "/tiles/Amplified/t_day"              "http://127.0.0.1:8123/tiles/Amplified/t_day"
        ProxyPass "/up/world/world"     "http://127.0.0.1:8123/up/world/world"
        ProxyPass "/up/world/world_nether"     "http://127.0.0.1:8123/up/world/world_nether"
        ProxyPass "/up/world/world_the_end"     "http://127.0.0.1:8123/up/world/world_the_end"
        ProxyPass "/up/world/Amplified"         "http://127.0.0.1:8123/up/world/Amplified"
        ProxyPass "/mapimages"          "http://127.0.0.1:8123/mapimages/"
        ProxyPass "/tiles/_markers_"    "http://127.0.0.1:8123/tiles/_markers_"
        ProxyPass "/tiles/faces/16x16"  "http://127.0.0.1:8123/tiles/faces/16x16"
        ProxyPass "/tiles/faces/32x32"  "http://127.0.0.1:8123/tiles/faces/32x32"

        #Reverse Proxy for DYNMAP
        ProxyPassReverse "/map"         "http://127.0.0.1:8123/"
        ProxyPassReverse "/js"          "http://127.0.0.1:8123/js/"
        ProxyPassReverse "/js/minecraft""http://127.0.0.1:8123/js/minecraft/"
        ProxyPassReverse "/js/map"      "http://127.0.0.1:8123/js/map/"
        ProxyPassReverse "/css"         "http://127.0.0.1:8123/css/"
        ProxyPassReverse "/standalone"  "http://127.0.0.1:8123/standalone"
        ProxyPassReverse "/up/configuration"            "http://127.0.0.1:8123/up/configuration"
        ProxyPassReverse "/up/sendmessage"              "http://127.0.0.1:8123/up/sendmessage"
        ProxyPassReverse "/up/login"            "http://127.0.0.1:8123/up/login"
        ProxyPassReverse "/up/register"         "http://127.0.0.1:8123/up/register"
        ProxyPassReverse "/version.js"  "http://127.0.0.1:8123/version.js"
        ProxyPassReverse "/images"             "http://127.0.0.1:8123/images/"
        ProxyPassReverse "/tiles"             "http://127.0.0.1:8123/tiles"
        ProxyPassReverse "/tiles/world/t"             "http://127.0.0.1:8123/tiles/world/t"
        ProxyPassReverse "/tiles/world/ct"             "http://127.0.0.1:8123/tiles/world/ct"
        ProxyPassReverse "/tiles/world/t_day"             "http://127.0.0.1:8123/tiles/world/t_day"
        ProxyPassReverse "/tiles/world_nether/nt"      "http://127.0.0.1:8123/tiles/world_nether/nt"
        ProxyPassReverse "/tiles/world_the_end/st"      "http://127.0.0.1:8123/tiles/world_the_end/st"
        ProxyPassReverse "/tiles/Amplified/ct"          "http://127.0.0.1:8123/tiles/Amplified/ct"
        ProxyPassReverse "/tiles/Amplified/t"           "http://127.0.0.1:8123/tiles/Amplified/t"
        ProxyPassReverse "/tiles/Amplified/t_day"               "http://127.0.0.1:8123/tiles/Amplified/t_day"
        ProxyPassReverse "/up/world/world"   "http://127.0.0.1:8123/up/world/world"
        ProxyPassReverse "/up/world/world_nether"     "http://127.0.0.1:8123/up/world/world_nether"
        ProxyPassReverse "/up/world/world_the_end"     "http://127.0.0.1:8123/up/world/world_the_end"
        ProxyPassReverse "/up/world/Amplified"          "http://127.0.0.1:8123/up/world/Amplified"
        ProxyPassReverse "/mapimages"          "http://127.0.0.1:8123/mapimages/"
        ProxyPassReverse "/tiles/_markers_"    "http://127.0.0.1:8123/tiles/_markers_"
        ProxyPassReverse "/tiles/faces/16x16"  "http://127.0.0.1:8123/tiles/faces/16x16"
        ProxyPassReverse "/tiles/faces/32x32"  "http://127.0.0.1:8123/tiles/faces/32x32"

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`

**Comment by bmw** [comment] 2017-01-11 22:09
Line 47 of the file you just posted is:
```
        ProxyPassReverse "/js/minecraft""http://127.0.0.1:8123/js/minecraft/"
```
Adding a space between "/js/minecraft" and "http://127.0.0.1:8123/js/minecraft/" seems to fix the problem for me. If this syntax without a space is valid in Apache, we should file a bug upstream with the parser we use.

**Comment by bmw** [comment] 2017-01-11 22:33
This syntax appears to be valid and isn't fixed in the Augeas release in Debian Sid. @domcleal, are you aware of this issue?

**Comment by wioxjk** [comment] 2017-01-11 22:40
Thank you for pointing that out. I added a space on that row you specified but it seems I have got another problem.

```
2017-01-11 22:38:04,374:DEBUG:certbot.main:Root logging level set at 20
2017-01-11 22:38:04,376:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-01-11 22:38:04,377:DEBUG:certbot.main:certbot version: 0.10.0
2017-01-11 22:38:04,377:DEBUG:certbot.main:Arguments: ['--apache']
2017-01-11 22:38:04,378:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-01-11 22:38:04,379:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-01-11 22:38:04,868:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf on line 45: Syntax error
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 191, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-available/000-default.conf on line 45: Syntax error
2017-01-11 22:38:04,870:DEBUG:certbot.plugins.selection:No candidate plugin
2017-01-11 22:38:04,870:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

VirtualHost:

```
<VirtualHost *:80>
	ServerName subdomain.domain.tld
	ServerAlias subdomain.domain.tld
	ServerAdmin someemail@mail.com
	DocumentRoot /var/www/html
	ProxyRequests off
        RewriteEngine on
        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>
        #Proxy for DYNMAP
        ProxyPass "/map"                "http://127.0.0.1:8123/"
        ProxyPass "/js"                 "http://127.0.0.1:8123/js/"
        ProxyPass "/js/minecraft"       "http://127.0.0.1:8123/js/minecraft/"
        ProxyPass "/js/map"             "http://127.0.0.1:8123/js/map/"
        ProxyPass "/css"                "http://127.0.0.1:8123/css/"
        ProxyPass "/standalone"         "http://127.0.0.1:8123/standalone"
        ProxyPass "/up/configuration"   "http://127.0.0.1:8123/up/configuration"
        ProxyPass "/up/sendmessage"     "http://127.0.0.1:8123/up/sendmessage"
        ProxyPass "/up/login"   "http://127.0.0.1:8123/up/login"
        ProxyPass "/up/register"        "http://127.0.0.1:8123/up/register"
        ProxyPass "/version.js"         "http://127.0.0.1:8123/version.js"
        ProxyPass "/images"             "http://127.0.0.1:8123/images/"
        ProxyPass "/tiles/world/t"      "http://127.0.0.1:8123/tiles/world/t"
        ProxyPass "/tiles"      "http://127.0.0.1:8123/tiles"
        ProxyPass "/tiles/world/ct"      "http://127.0.0.1:8123/tiles/world/ct"
        ProxyPass "/tiles/world/t_day"  "http://127.0.0.1:8123/tiles/world/t_day"
        ProxyPass "/tiles/world_nether/nt"      "http://127.0.0.1:8123/tiles/world_nether/nt"
        ProxyPass "/tiles/world_nether/flat"      "http://127.0.0.1:8123/tiles/world_nether/flat"
        ProxyPass "/tiles/world_the_end/st"      "http://127.0.0.1:8123/tiles/world_the_end/st"
        ProxyPass "/tiles/Amplified/ct"         "http://127.0.0.1:8123/tiles/Amplified/ct"
        ProxyPass "/tiles/Amplified/t"          "http://127.0.0.1:8123/tiles/Amplified/t"
        ProxyPass "/tiles/Amplified/t_day"              "http://127.0.0.1:8123/tiles/Amplified/t_day"
        ProxyPass "/up/world/world"     "http://127.0.0.1:8123/up/world/world"
        ProxyPass "/up/world/world_nether"     "http://127.0.0.1:8123/up/world/world_nether"
        ProxyPass "/up/world/world_the_end"     "http://127.0.0.1:8123/up/world/world_the_end"
        ProxyPass "/up/world/Amplified"         "http://127.0.0.1:8123/up/world/Amplified"
        ProxyPass "/mapimages"          "http://127.0.0.1:8123/mapimages/"
        ProxyPass "/tiles/_markers_"    "http://127.0.0.1:8123/tiles/_markers_"
        ProxyPass "/tiles/faces/16x16"  "http://127.0.0.1:8123/tiles/faces/16x16"
        ProxyPass "/tiles/faces/32x32"  "http://127.0.0.1:8123/tiles/faces/32x32"

        #Reverse Proxy for DYNMAP
        ProxyPassReverse "/map"         "http://127.0.0.1:8123/"
        ProxyPassReverse "/js"          "http://127.0.0.1:8123/js/"
        ProxyPassReverse "/js/minecraft" "http://127.0.0.1:8123/js/minecraft/"
        ProxyPassReverse "/js/map"      "http://127.0.0.1:8123/js/map/"
        ProxyPassReverse "/css"         "http://127.0.0.1:8123/css/"
        ProxyPassReverse "/standalone"  "http://127.0.0.1:8123/standalone"
        ProxyPassReverse "/up/configuration"            "http://127.0.0.1:8123/up/configuration"
        ProxyPassReverse "/up/sendmessage"              "http://127.0.0.1:8123/up/sendmessage"
        ProxyPassReverse "/up/login"            "http://127.0.0.1:8123/up/login"
        ProxyPassReverse "/up/register"         "http://127.0.0.1:8123/up/register"
        ProxyPassReverse "/version.js"  "http://127.0.0.1:8123/version.js"
        ProxyPassReverse "/images"             "http://127.0.0.1:8123/images/"
        ProxyPassReverse "/tiles"             "http://127.0.0.1:8123/tiles"
        ProxyPassReverse "/tiles/world/t"             "http://127.0.0.1:8123/tiles/world/t"
        ProxyPassReverse "/tiles/world/ct"             "http://127.0.0.1:8123/tiles/world/ct"
        ProxyPassReverse "/tiles/world/t_day"             "http://127.0.0.1:8123/tiles/world/t_day"
        ProxyPassReverse "/tiles/world_nether/nt"      "http://127.0.0.1:8123/tiles/world_nether/nt"
        ProxyPassReverse "/tiles/world_the_end/st"      "http://127.0.0.1:8123/tiles/world_the_end/st"
        ProxyPassReverse "/tiles/Amplified/ct"          "http://127.0.0.1:8123/tiles/Amplified/ct"
        ProxyPassReverse "/tiles/Amplified/t"           "http://127.0.0.1:8123/tiles/Amplified/t"
        ProxyPassReverse "/tiles/Amplified/t_day"               "http://127.0.0.1:8123/tiles/Amplified/t_day"
        ProxyPassReverse "/up/world/world"   "http://127.0.0.1:8123/up/world/world"
        ProxyPassReverse "/up/world/world_nether"     "http://127.0.0.1:8123/up/world/world_nether"
        ProxyPassReverse "/up/world/world_the_end"     "http://127.0.0.1:8123/up/world/world_the_end"
        ProxyPassReverse "/up/world/Amplified"          "http://127.0.0.1:8123/up/world/Amplified"
        ProxyPassReverse "/mapimages"          "http://127.0.0.1:8123/mapimages/"
        ProxyPassReverse "/tiles/_markers_"    "http://127.0.0.1:8123/tiles/_markers_"
        ProxyPassReverse "/tiles/faces/16x16"  "http://127.0.0.1:8123/tiles/faces/16x16"
        ProxyPassReverse "/tiles/faces/32x32"  "http://127.0.0.1:8123/tiles/faces/32x32"

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by bmw** [comment] 2017-01-11 22:56
Taking that file as is, Certbot doesn't error for me. I'm also testing on Ubuntu 16.04. Most likely scenario is sanitizing the file for posting here fixed the error. Is there something in or around line 45 (which is the `ProxyPassReverse "/map"         "http://127.0.0.1:8123/"` line) that you think our imperfect parser might have trouble with?

**Comment by wioxjk** [comment] 2017-01-11 23:06
Hmm, that surely is strange.
I took the file which maybee have been "sanitized" here but the problem seems to persist.

Is it possible to "override" it somehow? Or is there any more information that you would like to have?

Everything is imperfect, that's because we can improve it :)

**Comment by bmw** [comment] 2017-01-11 23:21
To be explicit, removing your original file in `sites-enabled` and replacing it with the one above causes more or less identical output from Certbot?

There's no way to override it because if we can't properly parse your config, we can't be confident we won't make changes that break something when obtaining/installing your cert. If you want, you can play games like temporarily commenting out/deleting the lines Certbot doesn't like. The biggest problem with this though is it makes automatically renewing the certificate in the future a lot more difficult. Another workaround if you're comfortable installing the certificate yourself is to use the [webroot plugin](https://certbot.eff.org/docs/using.html#webroot).

Assuming I didn't misunderstand and you are using Ubuntu 16.04, what's the output of `certbot --version`. Perhaps you're using an older version of Certbot?

**Comment by wioxjk** [comment] 2017-01-12 08:24
Yes, I did remove the current virtualhost and replaced it with the one that supposed to work. Same problem persisted.

I also tried to comment out the rows caused the problem but certbot did cry anyway.
I also have no problem installing certifikates manually or in different ways, I just want to have an answer why the problem occured in the first place :)

I can try use the same certbot script from my other servers and see if there is any change.

Version:
```
root@caixa:/etc/apache2/ssl# ./certbot-auto --version
certbot 0.10.0
```

**Comment by wioxjk** [comment] 2017-01-12 08:34
Just one thought, why would certbot check the virtualhost in sites-available instead of sites-enabled?

**Comment by domcleal** [comment] 2017-01-12 08:49
> Adding a space between "/js/minecraft" and "http://127.0.0.1:8123/js/minecraft/" seems to fix the problem for me. If this syntax without a space is valid in Apache though, I'll file a bug upstream with the parser we use.

Filed as https://github.com/hercules-team/augeas/issues/435, it's not working in Augeas master either.

>  I took the file which maybee have been "sanitized" here but the problem seems to persist.

The sanitised file here also parses for me.

**Comment by wioxjk** [comment] 2017-01-12 09:16
The issue seems to only affect only me, even after modifying the row which caused problems in the first place. 
Does certbot by any chance look into which modules that is enable and parse the vhost file according to that?

**Comment by bmw** [comment] 2017-01-17 17:06
> why would certbot check the virtualhost in sites-available instead of sites-enabled?

The initial idea was that searching `sites-available` made Certbot a little more helpful as it was able to find and set up more vhosts for you. We're considering removing that "feature" though. See #3545.

>  Does certbot by any chance look into which modules that is enable and parse the vhost file according to that?

No it doesn't.

If you're still having trouble here, keep an eye on errors like this from Certbot:
```
PluginError: There has been an error in parsing the file /etc/apache2/sites-enabled/000-default.conf on line 47: Syntax error
```
They try to tell you exactly where we had a problem. I wonder if Certbot is now erroring on the original file that may be in `sites-available` or on a different file.

**Comment by joohoi** [comment] 2017-09-27 11:00
Is this issue still valid? 

About sites-available: 
sites-available/* parsing has been removed in master, and will be included in the next (0.19) release of Certbot.

**Comment by AtlasNova** [comment] 2017-11-07 15:49
I got a similiar error and mine is complaining about this line:
```
    RewriteCond ${makulerade:%1}   !=""
```

which is a part of this chain:
```
    RewriteMap mymap txt:/path/to/myfile/mymap.map
    RewriteCond %{HTTP_HOST}   ([a-zA-Z0-9_]+).mydomain.com.* [NC]
    RewriteCond ${mymap:%1}   !=""
    RewriteRule ^/.*         http://${mymap:%1}.mydomain.com [L,R=301]
```

The idea of the code is rewrite the subdomain if it exists in the rewritemap file. The code works fine, but certbot complains about it. Any idea?

**Comment by slavamas** [comment] 2017-11-24 01:38
certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/httpd/conf/httpd.conf on line 410: Syntax error',)
[root@XXXXX httpd]# httpd -f /etc/httpd/conf/httpd.conf -t
Syntax OK
#########
there used to be VirtualHost block configuration at indicated line number. I commented it out, however it did not fix the problem - error message is still the same. and make no sense to me as line 410 is a comment now. not to mention - apache is totally happy with conf file syntax.

**Comment by wioxjk** [comment] 2017-11-24 08:29
@joohoi 
I can't test this unfortunately

**Comment by joohoi** [comment] 2017-11-24 08:37
@AtlasNova looks like Augeas is failing to parse the condition with empty string comparison, which, as you noted is valid syntax. @domcleal do you have any pointers or ideas about this?

@slavamas could you paste the erroring line (`/etc/httpd/conf/httpd.conf` line 410) here to further understand the issue?

**Comment by slavamas** [comment] 2017-11-24 16:45
it is a VirtualHost definition in httpd.conf. line 410 is the end of file. so, I am guessing line 410 is NOT real place, certbot is angry about - it is somewhere before this line.
I commented it out, but certbot still complaining about the same line number, though this line number start with "#"
#</VirtualHost>
and again - apachectl -t   is totally happy with syntax of file. and systemctl runs apache just fine.

**Comment by slavamas** [comment] 2017-11-24 17:04
if that may help...
2017-11-24 17:01:36,407:DEBUG:certbot.main:Arguments: ['--apache']
2017-11-24 17:01:36,407:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-11-24 17:01:36,418:DEBUG:certbot.log:Root logging level set at 20
2017-11-24 17:01:36,418:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-11-24 17:01:36,419:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-11-24 17:01:36,566:DEBUG:certbot_apache.configurator:Apache version is 2.4.6
2017-11-24 17:01:36,660:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/httpd/conf/httpd.conf on line 410: Syntax error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 203, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/httpd/conf/httpd.conf on line 410: Syntax error
2017-11-24 17:01:36,661:DEBUG:certbot.plugins.selection:No candidate plugin
2017-11-24 17:01:36,661:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

**Comment by joohoi** [comment] 2017-11-24 18:20
I believe the line number is correct, Augeas should report it correctly. The parser used by Certbot parses the comment lines as well, while Apache doesn't. I have seen some errors resulting from special characters in comments previously too.

**Comment by slavamas** [comment] 2017-11-24 19:11
I am not sure I understand... if line is commented out, what is the point
to parse it? it is not being read, as it is commented out.

**Comment by slavamas** [comment] 2017-11-24 19:26
or, let me ask this, please - what do you see wrong in this block (which I
completely commented out)? this is what certbot is unhappy with. last line
is number 410
IP addresses and hostnames are replaced with "X"

#<VirtualHost XXX.XXX.X.XX:8000>

#ServerName git.XXXXX

#DocumentRoot /opt/gitlab/embedded/service/gitlab-rails/public

#

#  ProxyPreserveHost On

#  #AllowEncodedSlashes Off

#  AllowEncodedSlashes NoDecode

#

#  <Location />

#    Order deny,allow

#    Allow from all

#    ProxyPassReverse http://XXX.XXX.X.XX:8080

#    ProxyPassReverse http://git.XXXXX/

#  </Location>

#

#  RewriteEngine on

#  RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f

#  RewriteRule .* http://XXX.XXX.X.XX:8080%{REQUEST_URI} [P,QSA]

#</VirtualHost>

**Comment by slavamas** [comment] 2017-11-24 19:31
...and I simply removed this commented out block from httpd.conf, and
certbot now complains about last line of file, which is again a comment.
perhaps I don't understand something, but , I am sorry, it doesn't make
much sense to me.

**Comment by AtlasNova** [comment] 2017-11-24 21:49
@slavamas try removing ALL commented lines (maybe save a backup first!).
If the problem persists, you will probably have some new ideas to it.

**Comment by slavamas** [comment] 2017-11-24 22:25
mmm... I can certainly do it, but it won't fix the bug. ;)

**Comment by slavamas** [comment] 2017-11-24 22:39
well... guess what... EVEN this did not fix the problem with certbot.
I am wondering how other people are able to use it, and what I am doing
wrong (if I am).
...and if I am using certbot incorrectly - I think any program should be
designed in the way it simply doesn't let user to use it the wrong way, or
return appropriate and clearly stated reason.
the way it works now is lame. (I am sorry)...

certbot --apache

Saving debug log to /var/log/letsencrypt/letsencrypt.log

The apache plugin is not working; there may be problems with your existing
configuration.

The error was: PluginError('There has been an error in parsing the file
/etc/httpd/conf/httpd.conf on line 107: Syntax error',)

[root@XXXX conf]# grep "#" httpd.conf

[root@XXXX conf]#

**Comment by joohoi** [comment] 2017-11-25 08:48
So to make things clear here: You are not doing anything wrong @slavamas , this is certainly a bug. 

Let me elaborate a bit here:

Certbot uses a third party library for configuration management, Augeas. Augeas is used to build DOM tree that is convinient to search, pull and push values from/to. Augeas also parses the comment lines to be able to add / remove comments from the configuration. In Certbot, the configuration file is passed to Augeas, which then should return the traversable DOM element. Unfortunately in this case, Augeas fails parsing some of the lines in your configuration, and reports the line it failed on back to Certbot.

What I'm trying to do here, is to understand what character or sequence of characters caused the parsing error in Augeas in order to report it upstream or try to mitigate it somehow in Augeas parameters or configuration on Certbot end. For this however I'd need to know the actual content of the line it failed on.

Seems like GitHub markdown also messes up with the comment lines etc, so if possible, could you pastebin the problematic lines for me to take look at?

**Comment by slavamas** [comment] 2017-11-25 17:04
Hi, 
certainly. I pasting the entire httpd.conf below. I removed all the comments from file.  as I see it, certbot (or should I say the plugin probably) complains about very last line.
so, it is not about httpd.conf itself (which works fine).
so, currently 106 lines in httpd.conf
if I make new empty line (making it total 107 lines), certbot will be unhappy about line 107. so, it is not about particular line, but about file itself and (in my case) is about how domain name is formed.
I am running private server, so, domain name is  not FQDN, which is ok with me, but certbot is totally freaked out by this fact.
what I am doing wrong (or unexpected fo certbot) is trying to run "certbot --apache" for private server. the domain listed in httpd.conf is not publicly listed domain, and my guess is that is main cause of problem. another words, I am (was) doing the wrong things, attempting to use certbot to obtain cert for private server. and running "certbot certonly --standalone" will give back a bit more clear explanations of failure to create certificate.
certbot certonly --standalone
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel): hmb
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: DNS name does not have enough labels


########################
cat /etc/httpd/conf/httpd.conf
Include "/etc/httpd/conf.d/ssl.conf"
Include "/etc/httpd/conf.d/nss.conf"
ServerRoot "/etc/httpd"

Listen xxx.xxx.x.xx:80

Include conf.modules.d/*.conf

User apache
Group apache

ServerAdmin root@localhost

ServerName xxxx:80
<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "/var/www/html"

KeepAliveTimeout 500
<Directory "/usr/share/tomcat">
	AllowOverride None
	Require all granted
</Directory>
<Directory "/var/www">
    AllowOverride None
    Require all granted
</Directory>

<Directory "/var/www/html">
    Options Indexes FollowSymLinks

    AllowOverride None

    Require all granted
</Directory>

<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

<Files ".ht*">
    Require all denied
</Files>

ErrorLog "logs/error_log"

LogLevel debug

<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    <IfModule logio_module>
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>

    CustomLog "logs/access_log" combined
</IfModule>

<IfModule alias_module>
    Alias /tomcatdoc "/usr/share/tomcat"
    ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"

</IfModule>

<Directory "/var/www/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>

<IfModule mime_module>
    TypesConfig /etc/mime.types

    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    AddType application/x-httpd-php .php
    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml
</IfModule>

<IfModule mod_negotiation.c>
<IfModule mod_include.c>
    <Directory "/var/www/error">
        AllowOverride None
        Options IncludesNoExec
        AddOutputFilter Includes html
        AddHandler type-map var
        Order allow,deny
        Allow from all
        LanguagePriority en es de fr
        ForceLanguagePriority Prefer Fallback
    </Directory>

AddDefaultCharset UTF-8

<IfModule mime_magic_module>
    MIMEMagicFile conf/magic
</IfModule>

EnableMMAP off
EnableSendfile on

**Comment by enorazza** [comment] 2017-12-11 17:13
Hi, I have the same error.
Using CentOS 7, Apache 2.4, PHP 5.6.

`<IfModule mod_rewrite.c="">`
This line produce the error.
It is the first line in the file with the **.c=""** string, 
I suppose this string may be related to the parsing error.
[letsencrypt.log](https://github.com/certbot/certbot/files/1548706/letsencrypt.log)

**Comment by slavamas** [comment] 2017-12-11 18:03
I think there is no reason to check/validate the entire httpd.conf, as,
IMHO, certbot should only be concerned about lines related to certificate.
and the rest of httpd.conf should not be checked/validated by certbot, as
it has nothing to do with certificate. I think by validating/trying to the
entire httpd.conf, certbot setting itself in the trap and exposed itself to
unnecessary complications. my point is - checking in httpd.conf ONLY lines
related to certificate will make script much simpler and significantly more
robust... IMHO.

**Comment by schoen** [comment] 2019-02-26 00:25
Hi folks,

I don't think that we mean to have a generic GitHub issue for Apache configuration parsing problems (although we continue to be interested in finding and fixing them where they occur).

If anyone in this thread, or reading it, has a reproducible Apache parsing problem in the latest Certbot when using `--apache`, please open a new issue and include your Apache configuration as well as the Certbot logs. (We do know that continued bugs like this are quite possible, but we need to handle each such issue individually, and make sure that they're still problems in current versions of Certbot.)

In the future, we may also be switching away from Augeas entirely, which could make problems like this rarer; in the meantime, we'll still need to fix our parser or get Augeas to fix theirs (and we welcome new and updated individualized reports about parsing errors).

**Closed by schoen** 2019-02-26 00:25 UTC
Labels: area: apache, more-info

**Comment by JialuZhang** [comment] 2021-03-23 11:01
Hi folks,

In the posted configuration,
```
...
RewriteEngine On
...
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
