### ISSUE TITLE
LetsEncrypt fails to parse an Apache config file (IfVersion)

### ISSUE THREAD

**Issue by ogmueller** [certbot/certbot#7423] opened 2019-10-04 10:02 UTC
## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
PPA: deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main

```
# certbot --version
certbot 0.31.0
```

## I ran this command and it produced this output:
certbot -q renew

## Certbot's behavior differed from what I expected because:
it is exiting with an apache parse error, though there is no parse error in the configuration. apache linting is just fine.

## Here is a Certbot log showing the issue (if available):
```
2019-10-04 11:33:15,097:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2019-10-04 11:33:15,195:DEBUG:certbot_apache.configurator:Apache version is 2.4.29
2019-10-04 11:33:15,607:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apache2/sites-enabled/000-default.conf on line 9: Syntax error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 255, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python3/dist-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
certbot.errors.PluginError: There has been an error in parsing the file /etc/apache2/sites-enabled/000-default.conf on line 9: Syntax error
2019-10-04 11:33:15,608:DEBUG:certbot.plugins.selection:No candidate plugin
2019-10-04 11:33:15,608:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2019-10-04 11:33:34,542:DEBUG:certbot.main:certbot version: 0.31.0
2019-10-04 11:33:34,552:DEBUG:certbot.main:Arguments: []
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
   7 <VirtualHost *:443>
   8
   9   <IfVersion > 2.4.8>
  10     # Enable HTTP/2 whenever possible
  11     Protocols h2 http/1.1
  12   </IfVersion>
  13
```

As an XML doc this would be wrong, but Apache configuration is not pure XML and this configuration seems to be ok and as described in the documentation (https://httpd.apache.org/docs/2.4/mod/mod_version.html). Also apache linting is fine:
```
# apachectl -t
Syntax OK
```

I have seen this issue already on  https://github.com/certbot/certbot/issues/1294, but @domcleal pointed me here.

**Comment by joohoi** [comment] 2019-10-04 12:50
Thanks for opening the issue. This is indeed the same issue than #1294 you linked in the description. Unfortunately the issue lies within Augeas - a C library we currently use to parse the Apache configuration. We're in the process of replacing Augeas with a another parser and I think this won't be a problem in the new approach.

As the issue is duplicate to the previously linked one, I'm closing it. If however I missed something here, please feel free to comment and I'll reopen the issue.

**Closed by joohoi** 2019-10-04 12:50 UTC
Labels: area: apache, bug
