### ISSUE TITLE
On Gentoo with systemd, Certbot invokes the OpenRC control scripts (and thus fails)

### ISSUE THREAD

**Issue by Jarodiv** [certbot/certbot#3411] opened 2016-08-15 23:53 UTC
On Gentoo with systemd, calling `./certbot-auto --debug --apache certonly` (in the checkout dir, fresh apache 2.4 installation) results in a screen asking me for my domain (so far, so god). After that certbot runs into an error when restarting apache via apache2ctl. Thats not very surprising, since apache2ctl calls openrc which is not present on systemd systems.

```
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 91, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 237, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1637, in perform
    self.restart()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1547, in restart
    self._reload()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1558, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.

 * No permission to apply cgroup settings
 * You are attempting to run an openrc service on a
 * system which openrc did not boot.
 * You may be inside a chroot or you may have used
 * another initialization system to boot this system.
 * In this situation, you will get unpredictable results!
 * If you really want to do this, issue the following command:
 * touch /run/openrc/softlevel
```

**Comment by joohoi** [comment] 2016-08-17 19:35
@osirisinferi do you have insight on this? On the first glance this looks like it's actually apache package that's broken, but I need verification on this.

**Comment by osirisinferi** [comment] 2016-08-17 19:51
@joohoi Gentoo uses `OpenRC` by default, but `systemd` is also officially supported. Personally, I'm not familiar with `systemd`. But I'm sure it has something to do with the `apache2ctl gracefull` command, where `/usr/sbin/apache2ctl` is just a "forwarding script" towards `/etc/init.d/apache2`. Which, as far as I can tell, is indeed an `OpenRC` script, which are disabled when `systemd` is used.

So, I think there are two options: a) start supporting a non-supported init system (no clue how much work that will take) or b) check for the `systemd` init system and tell the user we're sorry, but are not supporting `systemd` currently.

**Comment by joohoi** [comment] 2016-08-17 19:58
Well, it's actually another way around. Other distros apache2ctl is systemd compatible.

**Comment by osirisinferi** [comment] 2016-08-20 21:18
Can't get `systemd` to compile I'm afraid, `util-linux` not compiling b/c of missing `libsystemd` and `systemd` not compiling without `util-linux`, or perhaps something else..

So no help here, sorry :disappointed:

**Comment by mstrache** [comment] 2016-11-06 14:03
@osirisinferi Any advances since then? Have you tried installing Gentoo in a VM? Worked perfectly for me with VirtualBox and I can (still) easily reproduce the error.

If you need support for the Gentoo installation, ask me. I can give you the (almost) complete set of instructions I used for installation. Another option may be using existing Vagrant boxes, for example this one: https://atlas.hashicorp.com/papercrane/boxes/gentoo-amd64-systemd. I haven't tested Gentoo in Vagrant yet, it should work as well.

**Comment by lvx0** [comment] 2017-02-05 20:37
Hi All,

I've run in the same problem is mention above. The systemd system is not supported in the "certbot --apache" option.

After some error checking I also stumbled on the constants.py file. I've changed this line:
`restart_cmd=['apache2ctl', 'graceful'],`

and changed it to:
`restart_cmd=['systemctl', 'reload', 'apache2.service'],`

This solved the problem for me, so maybe it's an option the either support systemd and openrc for gentoo. Or just switch to the native commands as an option.

best regards.

**Comment by noci2012** [comment] 2018-12-04 21:17
I think this is not a certbot problem as apachectl is installed with apache.
Was apache installed with systemd flags? 
apachectl is the "normal" way to control apache, so why would certbot need a different way?

IMHO personally i hope gentoo keeps systemd optional as i still see no improvement on systems running systemd, i do see questions elsewhere about how to get things to work or behave rationally.

**Comment by joohoi** [comment] 2018-12-05 08:03
Hi!

As of now, we strongly prefer using `apache2ctl`, as distributions are modifying it to fit their needs. Depending on distribution, it may have some distro specific parsing logic. For example, Gentoo reads the distro specific configuration file `/etc/conf.d/apache2` and modifies the apache2 startup command line accordingly. 

This logic actually resides in the OpenRC script, and in Gentoo `apache2ctl` acts as a passthrough. Initially it was a dummy wrapper for OpenRC script, but [got changed slightly](https://bugs.gentoo.org/634414) to provide means to call the Apache2 binary directly with the parsed distro specific configuration file options on the command line.

This is indeed a bug in `www-servers/apache` that makes it hard to run Apache2 on a Gentoo with systemd, using the Gentoo specific Apache configuration and should be filed to Gentoo bug tracker. I haven't checked, but based on this information there is no way to run the Apache2 with the Gentoo specific configuration under systemd as the distro specific configuration parser isn't run.

**Comment by ford-prefect** [comment] 2019-02-18 04:21
Does anyone know what the next steps are here or is some alternative being pursued? This is getting progressively more painful as the change in the override file is no-longer a one-liner.

**Comment by joohoi** [comment] 2019-02-18 09:09
> Does anyone know what the next steps are here or is some alternative being pursued? This is getting progressively more painful as the change in the override file is no-longer a one-liner.

Certbot is still only calling Apache control script that's provided by package `www-servers/apache`. That would be the correct place to fix any incompatibilities within the init system for Gentoo. The issue  being `apache2ctl` calling OpenRC init script behind the scenes.

**Comment by noci2012** [comment] 2019-02-18 15:28
This is a bug in the www-servers/apache setup on a systemd gentoo system. 
IF you have OpenRC then apach2ctl should call OpenRC...
IF you have systemd then apache2ctl should call systemd..
All other should use apache2ctl (IMHO).

Mentioning in the Bugzilla http://bugs.gentoo.org/ should get this fixed.

My personal opnion is i prefer OpenRC above systemd. for many reasons

**Comment by xvlvx0** [comment] 2019-02-18 19:04
Hi all,

I've scripted the acme-tiny directly and that is working for me.
I can target the specifics directly, without the struggle of certbot.
It is listed in the [gentoo wiki](https://wiki.gentoo.org/wiki/Let%27s_Encrypt).

**Comment by Jarodiv** [comment] 2019-02-19 09:44
> My personal opnion is i prefer OpenRC above systemd. for many reasons
Please do not make this a discussion about personal opinions. There are other places where the pros and cons of those two systems and/or others can be discussed.

Besides of that, I agree with @noci2012 in that this is a bug in the Gentoo package. A corresponding ticket has been created and is now waiting for its resolution.

Thanks @xvlvx0 for sharing your workaround.

**Comment by Jarodiv** [comment] 2019-04-02 21:56
f.y.i my bugfix to Gentoos `www-servers/apache` package now was accepted and merged.

I just successfully tested the resulting updated Apache package successfully with Certbot. For anyone interested: update to `>=www-servers/apache-2.4.39` and verify if it is working for you too. If you find any bugs, please report them to https://bugs.gentoo.org/673530

Imho this ticket finally can be closed.

**Comment by joohoi** [comment] 2019-04-03 10:15
That's awesome news! Thanks for fixing this upstream, and testing that the fix works for Certbot as well. Closing the issue - as noted - finally.

**Closed by joohoi** 2019-04-03 10:15 UTC
Labels: area: apache, area: gentoo
