### ISSUE TITLE
Certbot not recognizing individual .conf files from include directive in nginx.conf

### ISSUE THREAD

**Issue by Briscoooe** [certbot/certbot#6325] opened 2018-08-29 20:19 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager [using official instructions](https://certbot.eff.org/lets-encrypt/ubuntutrusty-nginx)
```
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-nginx 
```

## I ran this command and it produced this output:
`sudo certbot --nginx --nginx-server-root /opt/bitnami/nginx/conf/`
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel):
```

## Certbot's behavior differed from what I expected because:
I have a number of server blocks configured in individual `.conf` files that are being included in my `nginx.conf` from a specific directory. [See here](#nginxconf)

A typical `.conf` [can be seen here](#site1conf)

I know these `.conf` files are being successfully loaded by Nginx as I can access all of them using their server names, in this case `www.site1.com` or `site1.com` will successfully navigate to `http://site1.mydomain.com`. 

The problem is that certbot does not recognize any of the domains configured in the server blocks in the directory. The only way I can get a domain to show up when I run the `sudo certbot --nginx --nginx-server-root /opt/bitnami/nginx/conf/` is to include the contents of an individual `.conf` file directly in the `nginx.conf` file. This is not a viable option for me as I have many domains and including each of their configurations in the `nginx.conf` file would be messy.

### <a name="nginxconf">`nginx.conf`</a>
```
user  daemon daemon;
worker_processes  auto;

error_log  "/opt/bitnami/nginx/logs/error.log";

pid        "/opt/bitnami/nginx/logs/nginx.pid";


events {
    worker_connections  1024;
}


http {
    server_names_hash_bucket_size 128;

    /* typical nginx configurations */

    server {
        listen       80 default_server;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }

        include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";
        include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
    }

    include "/opt/bitnami/nginx/conf/sites/*.conf"; #This line includes the conf files

}
```
### <a name="site1conf">`site1.com.conf`</a>
```
server {
  listen 80;
  server_name www.site1.com site1.com;
  location / {
	access_log off;
	proxy_pass http://site1.mydomain.com;
  }
}
```

**Comment by sydneyli** [comment] 2018-08-29 22:06
@Briscoooe, thank you for reporting! This looks like an nginx parsing bug on our end. If you remove the quotations around the path (i.e. `include /opt/bitnami/nginx/conf/sites/*.conf`), does it work?

**Comment by sydneyli** [comment] 2018-08-29 23:27
I tested it out myself and the quoted include seem to be the issue. This is close to, but not exactly a duplicate of, #5543, which couldn't recognize quoted `server_name`s.

**Comment by Briscoooe** [comment] 2018-08-31 00:26
I've made a fix for this and [#5543](https://github.com/certbot/certbot/issues/5543). See [PR #6630](https://github.com/certbot/certbot/pull/6330)

**Comment by sydneyli** [comment] 2018-09-17 17:40
@ohemorange what do you think about hiding quotes using `UnspacedList`?

**Comment by ohemorange** [comment] 2018-09-18 23:16
Great idea! But rather, on the replacement to `UnspacedList`, so I'll get those reviews in.

**Comment by Henner** [comment] 2019-04-06 18:35
any news on this?
I have the same problem with the following part of my block:

    header_filter_by_lua_block {
        ngx.header["server"] = "my server"
    }

I am using: certbot 0.33.1

**Comment by ohemorange** [comment] 2019-04-24 18:34
After we finish with #5823 (currently being worked on), we should come back to this issue and its attached PR.

**Comment by mc0e** [comment] 2019-06-13 03:20
https://github.com/certbot/certbot/issues/5199 looksto be a specific case of this issue.

**Closed** 2022-07-13 16:23 UTC
Labels: bug, area: nginx, priority: significant

**Comment by mc0e** [comment] 2022-07-13 19:03
This is disappointing.  Was there a reason for not addressing this? 

It doesn't seem like it should be significantly more complicated than the case where files are included individually?

**Comment by ohemorange** [comment] 2022-07-13 19:43
The certbot team is very small and therefore needs to prioritize which issues we take on. If it's very important to you, we'd accept a minimal, thoroughly-tested PR.

**Comment by Briscoooe** [comment] 2022-07-14 08:40
I closed this as I assumed the fix was covered in one of the other two issues that were mentioned here. It's also been 4 years since I opened this PR, I was just closing it to clear up my issues tab. 

I already submitted a PR for this when i created the issue, does it not resolve the issue? If not I can improve

https://github.com/certbot/certbot/pull/6330
