### ISSUE TITLE
Installing acme with the py2 wheel on Python 2.6 doesn't install the right mock version.

### ISSUE THREAD

**Issue by Natim** [certbot/certbot#2178] opened 2016-01-14 09:50 UTC
```
$ pip --version
pip 7.1.2 from ~/.virtualenvs/py269/lib/python2.6/site-packages (python 2.6)
$ pip install acme
Collecting acme
  Using cached acme-0.1.1-py2-none-any.whl
$ pip freeze
mock==1.3.0
```

According to the [ACME setup.py](https://github.com/letsencrypt/letsencrypt/blob/v0.1.1/acme/setup.py#L26-L31) we should have ``mock < 1.1.0``

**Comment by Natim** [comment] 2016-01-14 09:52
This is probably not a really serious problem because ``mock`` in used only in tests and we probably don't use wheel when we need to run test on acme.

**Comment by bmw** [comment] 2016-09-29 18:55
This is caused by what I wrote up in #3455. I'm closing this issue in favor of that one simply because I was able to track down the problem.

**Closed by bmw** 2016-09-29 18:55 UTC
Labels: acme, pkging
