### ISSUE TITLE
Missing Installer attribute in commom module

### ISSUE THREAD

**Issue by alexlopespereira** [certbot/certbot#5215] opened 2017-11-01 20:40 UTC
## My operating system is (include version):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager.
sudo add-apt-repository ppa:certbot/certbot

## I ran this command and it produced this output:
Any command starting with certbot gives me the following erro:
$ certbot
An unexpected error occurred:
AttributeError: 'module' object has no attribute 'Installer'
Please see the logfile '/tmp/tmpI_VLqc' for more details.
ubuntu@ip-172-31-40-24:/var/www/revisao/server$ sudo cat /tmp/tmpI_VLqc
2017-11-01 19:41:17,618:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 722, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 193, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 40, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 65, in <module>
    class NginxConfigurator(common.Installer):
AttributeError: 'module' object has no attribute 'Installer'

How could I fix this? 

Thanks

**Comment by SwartzCr** [comment] 2017-11-08 00:42
I couldn't reproduce this on a fresh install. It seems like you might be missing some python things
You could try `apt-get install -f` to see if you can fix it, or uninstall certbot and then re-install it, or `apt-get install python-certbot-nginx`
Let me know if none of those work and we can try to debug the issue

**Comment by j0sh3rs** [comment] 2017-11-21 15:42
Ran into this same issue on a fresh install of certbot from the PPA.  Same distro, same release.  Prior to having the ppa on my system, I had manually installed certbot-auto:

```
[10:36:40] root:~ # certbot-auto --version
certbot 0.19.0
```
Looking into it, it seems that my local python 2.7.12 didn't have the certbot package, so it was failing to meet the requirements for certbot.common.

Running `pip install certbot` fixed my issue by installing the dependency packages for python.

**Comment by bmw** [comment] 2017-11-21 18:56
@j0sh3rs, what command did you run to install Certbot from the PPA?

**Comment by j0sh3rs** [comment] 2017-11-21 19:30
The exact steps that were on the certbot homepage for installing the PPA and certbot w/ Nginx:

```
656  apt-get install software-properties-common
657  add-apt-repository ppa:certbot/certbot
658  apt-get update
659  apt-get install python-certbot-nginx
```

**Comment by bmw** [comment] 2017-11-21 19:53
I'm unable to reproduce this on a fresh Ubuntu install. Also, if your error was the same as above, I don't think the `certbot` module wasn't missing as the traceback includes code from that module. Instead, your installation of Certbot was corrupted. Do you have any idea how that may have happened?

While I'm glad running `pip install certbot` worked around the problem, [we strongly advise against doing this](https://certbot.eff.org/docs/install.html#installing-from-source) as it can break Python packages on your system. Ideally, the problem should be resolved by using `pip uninstall` to remove any packages you installed this way and reinstalling the packages with `apt` as SwartzCr suggested above.

**Comment by adferrand** [comment] 2019-03-26 14:25
Since there is no response for more than one year, I close this issue. Do not update here if the issue is still relevant.

**Closed by adferrand** 2019-03-26 14:25 UTC
Labels: area: debian / ubuntu, area: pkging, debugging
