### ISSUE TITLE
windows: Investigate  "Controlled Folder Access" breaking Certbot

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9165] opened 2022-01-09 20:17 UTC
https://community.letsencrypt.org/t/certbot-fails-after-upgrade-to-windows-11-no-usable-temp-directory/169332/5

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide#windows-system-folders-are-protected-by-default

---- 

Further reports:

- https://community.letsencrypt.org/t/the-following-error-was-encountered-errno-13-permission-denied-c-certbot-log-letsencrypt-log-either-run-as-root-or-set-config-dir-work-dir-and-logs-dir-to-writeable-paths/172239?u=_az
- https://community.letsencrypt.org/t/certificate-key-stop-working-on-restart-of-node-js-on-windows-pc/172169?u=_az

**Comment by adferrand** [comment] 2022-01-09 20:25
Ok. Maybe it is time to properly implement some elements from https://github.com/certbot/certbot/issues/7872, https://github.com/certbot/certbot/issues/7881 and https://github.com/certbot/certbot/issues/7883, and manage temporary folders directly from the workdir of Certbot (this will have impact on all systems).

**Comment by bmw** [comment] 2022-01-18 22:13
How urgent is this? How should we prioritize this?

**Comment by alexzorin** [comment] 2022-01-25 22:27
I would want to find out whether it happens on a standard Windows 11 installation. Since we have not had other reports so far, I think it is okay to wait.

**Comment by SamLowryMOI** [comment] 2022-02-23 11:24
It happens on a standard Windows 10 Home. And it's very annoying. Therefore, it should be prioritized.

I don't know how exactly and why the ACLs are set like this. The inheritance is interrupted (several times I think). In any case, you have to use a crowbar to set the rights so that you as a user (and thus also the web server) can access the certificates.

The reason I believe is that the files and links are created by an account belonging to the Administrators group. A temporary (!) user (e.g. LogonSessionId_0_1252802911) can then read it. See [https://stackoverflow.com/questions/35468700/logonsessionid-account-assigned-read-access-in-new-certificates](https://stackoverflow.com/questions/35468700/logonsessionid-account-assigned-read-access-in-new-certificates) or google LogonSessionId.

After a restart, this user no longer exists. So no one can access the certificate anymore.

Maybe that helps, maybe I'm wrong. In any case, this should be fixed as soon as possible, otherwise certbot cannot be used under Windows. Please.

**Comment by bmw** [comment] 2022-02-24 22:08
@adferrand, do you have the time & interest to take a look at this? I'm not sure how urgent it is so we can wait if you think that's more appropriate, but apparently more people have been hitting this.

Alex thinks https://github.com/certbot/certbot/issues/9067 might be related, but he's not sure.

**Comment by SamLowryMOI** [comment] 2022-03-24 03:46
This is the assignment of rights for a newly installed Certbot with newly created certificates for a domain.

```
Item                                                Inherits Item's Directory                     Directory inherits
----                                                -------- ----------------                     ------------------
C:\Certbot\                                                  C:\

C:\Certbot\live                                     yes      C:\Certbot
C:\Certbot\live\itsme.example.com                   yes      C:\Certbot\live                      yes
C:\Certbot\live\README                              yes      C:\Certbot\live                      yes
C:\Certbot\live\itsme.example.com\cert.pem          yes      C:\Certbot\live\itsme.example.com    yes
C:\Certbot\live\itsme.example.com\chain.pem         yes      C:\Certbot\live\itsme.example.com    yes
C:\Certbot\live\itsme.example.com\fullchain.pem     yes      C:\Certbot\live\itsme.example.com    yes
C:\Certbot\live\itsme.example.com\privkey.pem       yes      C:\Certbot\live\itsme.example.com    yes
C:\Certbot\live\itsme.example.com\README            yes      C:\Certbot\live\itsme.example.com    yes

C:\Certbot\archive                                  yes      C:\Certbot
C:\Certbot\archive\itsme.example.com                yes      C:\Certbot\archive                   yes
C:\Certbot\archive\itsme.example.com\cert1.pem      yes      C:\Certbot\archive\itsme.example.com yes
C:\Certbot\archive\itsme.example.com\chain1.pem     yes      C:\Certbot\archive\itsme.example.com yes
C:\Certbot\archive\itsme.example.com\fullchain1.pem yes      C:\Certbot\archive\itsme.example.com yes
C:\Certbot\archive\itsme.example.com\privkey1.pem   yes      C:\Certbot\archive\itsme.example.com yes

--------------------------------------------------------------------------------------------------------------------
C:\Certbot\
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

--------------------------------------------------------------------------------------------------------------------
C:\Certbot\live
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

C:\Certbot\live\itsme.example.com
    Type           : Allow
    Name           : Everyone
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

C:\Certbot\live\README
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\live\itsme.example.com\cert.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\live\itsme.example.com\chain.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\live\itsme.example.com\fullchain.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\live\itsme.example.com\privkey.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\live\itsme.example.com\README
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

--------------------------------------------------------------------------------------------------------------------
C:\Certbot\archive
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

C:\Certbot\archive\itsme.example.com
    Type           : Allow
    Name           : Everyone
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : FullControl
    Inherited From : None
    Apply To       : This folder only

C:\Certbot\archive\itsme.example.com\cert1.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\archive\itsme.example.com\chain1.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\archive\itsme.example.com\fullchain1.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : LogonSessionId_0_192473
    Permission     : ReadAndExecute, Synchronize
    Inherited From : None

C:\Certbot\archive\itsme.example.com\privkey1.pem
    Type           : Allow
    Name           : NT-AUTHORITY\SYSTEM
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : BUILTIN\Administrators
    Permission     : FullControl
    Inherited From : None

    Type           : Allow
    Name           : MyPc\ItsMe
    Permission     : DeleteSubdirectoriesAndFiles, Write, Delete, Read, ChangePermissions, TakeOwnership, Synchronize
    Inherited From : None

```
This is the assignment of rights for a newly installed Certbot with newly created certificates for a domain.

What can we see?
All folders below C:\Certbot inherit, but do not inherit anything, since all rights only apply to the respective folder (Apply To: This folder only).
All files can inherit, but don't inherit anything because the folders don't inherit anything (see above).

For all files for which no user rights have been assigned (README, cert.pem, chain.pem, fullchain.pem), the user LogonSessionId_0_192473 (SID S-1-5-5-0-192473) has the rights ReadAndExecute, Synchronize . These were automatically granted by Windows.
This is a user created automatically by Windows, which is only valid for the current session. After a restart it no longer exists, a new one is then created with the SID S-1-5-5-xy (see https://docs.microsoft.com/en-us/windows/security/identity-protection/ access-control/security-identifiers). Therefore, after a reboot, no user can access the files, only the NT-AUTHORITY\SYSTEM and BUILTIN\Administrators accounts.

Rights for the user MyPc\ItsMe have been assigned to the files that should be protected best (privkey.pem). This was the registered user when the certificates were created. After a restart, the latter can access this - also write access. In my opinion this is unnecessary.

For the domain folder (itsme.example.com) rights have been assigned to Everyone. In my opinion this is unnecessary.

Rights for NT-AUTHORITY\SYSTEM, BUILTIN\Administrators and the user MyPc\ItsMe were assigned for all folders. In my opinion correct.

If the purpose of assigning rights is to give the user registered when the certificates were created (here MyPc\ItsMe) read rights to directories and files, I think the following makes more sense.

C:\Certbot
inherits: no retained
Maintain rights assignment for NT-AUTHORITY\SYSTEM, BUILTIN\Administrators and the logged in user (here MyPc\ItsMe), BUT

Instead of
    This folder only
    (Propagation: None, Inheritance: None)

Better
    This folder, subfolders and files
    (Propagation: None, Inheritance: ObjectInherit, ContainerInherit)

Since all folders and files below this folder inherit the rights, no further rights need to be assigned. Only inheritance needs to be enabled (SetAccessRuleProtection(false, false)).

I think that would have made it much easier to get where we are now. Another advantage would be that - if necessary - you can easily assign the appropriate rights to another user (under whose account a web server is running, for example) by simply granting him rights for the Certbot folder. Everything else is regulated by inheritance.

The user LogonSessionId_x_y should then no longer appear.

**Comment by bmw** [comment] 2022-08-31 01:01
It's possible it's a slightly different issue, but we got another report of this at https://github.com/certbot/certbot/issues/9379.

**Comment by SamLowryMOI** [comment] 2022-08-31 02:04
I think it's about the same issue.

> Therefore, after a reboot, no user can access the files, only the NT-AUTHORITY\SYSTEM and BUILTIN\Administrators accounts.

The solution is relatively simple:
> Each user who is to access the certificates is given read rights in the two folders live and archive with the value 'This folder, subfolders and files' for 'Apply To'.

It means that the user under whose account the web server is running must be granted read permissions in the directories mentioned above.

This is impossible for Certbot to know/decide. Therefore a manual (one-time) intervention is necessary. I therefore don't see it as a bug either. It prevents reading of the private keys.

However, the need for manual intervention under WIndows should be better documented.

**Comment by alystair** [comment] 2024-01-25 09:37
Experienced this in latest release of Windows 11 (23H2 22635.3066). I can confirm that folder access is broken after a restart, the solution to this was modifying the archive folder's permission entries to apply to `This folder , subfolders and files` instead of `This folder only` - however I accidentally wiped out the `LogonSessionId` user's rights - hopefully this won't bite me come renewal (although these are dev boxes, not prod - so it's not critical).

**Comment by zoracon** [comment] 2024-11-20 02:45
Closing due to our decision to discontinue our Beta distribution of the Windows Installer:
https://github.com/certbot/certbot/wiki/Architectural-Decision-Records#-certbot-discontinuing-windows-support

If you need alternatives. They are listed in this community forum post:
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101

**Closed by zoracon** 2024-11-20 02:45 UTC
Labels: more-info, area: windows, priority: unplanned
