### ISSUE TITLE
mktemp: too few X's in template `le'

### ISSUE THREAD

**Issue by Striatum6194** [certbot/certbot#2858] opened 2016-04-17 06:45 UTC
debian 7.8

mktemp_8.13-3.5_all.deb (backported, same issue with regular mktemp)

when executing letsencrypt-auto error message **mktemp: too few X's in template `le'**

sources git pulled today.

line 438

TempDir() {
  mktemp -d 2>/dev/null || mktemp -d -t 'le'  # Linux || OS X
}

mktemp reported as deprecated ?

**Comment by bmw** [comment] 2016-04-18 22:32
Strange. As suggested by the comment `mktemp -d 2>/dev/null` should work Linux and `mktemp -d -t 'le'` should work on OS X. I'm unable to reproduce this with Wheezy in docker.

What is the output of `mktemp -d 2>/dev/null`?

**Comment by Striatum6194** [comment] 2016-04-19 08:58
mktemp -d 2>/dev/null gives no error message, but the script execution this
morning after a git pull still gives mktemp: too few X's in 'le'

**Comment by bmw** [comment] 2016-04-19 10:07
So `mktemp -d 2>/dev/null` worked but `mktemp -d 2>/dev/null || mktemp -d -t 'le'` does not? What shell are you using (e.g. `bash`, `zsh`, `fish`, etc.)?

**Comment by Striatum6194** [comment] 2016-04-19 10:24
echo $SHELL gives me /bin/bash

**Comment by bmw** [comment] 2016-04-19 10:42
What about the output of `ps -p $$`? Sorry for all the questions, but I am unable to reproduce your problem.

**Comment by Striatum6194** [comment] 2016-04-19 12:34
No problem !!

10083 pts/0   00:00:00 bash

**Comment by bmw** [comment] 2016-04-19 13:01
Have you ran `mktemp -d 2>/dev/null || mktemp -d -t 'le'` outside of `letsencrypt-auto` and received the same error?

Also, what's the output of `bash --version`?

**Comment by Striatum6194** [comment] 2016-04-19 13:26
mktemp -d 2>/dev/null || mktemp -d -t 'le'  gives tmp/tmp.1iRKoZYcM

Bash version : 4.2.37(1)

**Comment by bmw** [comment] 2016-04-19 14:10
Progress!

If `mktemp -d 2>/dev/null || mktemp -d -t 'le'` works in your default shell, the problem is the shell used for `/bin/sh`. You can verify this by running `/bin/sh -c "mktemp -d 2>/dev/null || mktemp -d -t 'le'"`. If you'd like to debug this, see if you can determine which shell is used for `/bin/sh`. `/bin/sh --version` might work.

On the other hand, if you just want this to work, running `bash letsencrypt-auto` should fix your problem.

**Comment by robocoder** [comment] 2016-09-30 15:36
After upgrading to Ubuntu 16.04, I'm also getting this error.

With `/bin/sh` (i.e., `dash`):
```
root@ubuntu:~# /bin/sh -c "mktemp -d 2>/dev/null || mktemp -d -t 'le'"
mktemp: too few X's in template ‘le’
```

With `/bin/bash`:
```
root@ubuntu:~# mktemp -d 2>/dev/null || mktemp -d -t 'le'
mktemp: too few X's in template ‘le’
```

Dash version:
```
root@ubuntu:~# dpkg -l | grep dash
ii  dash                                0.5.8-2.1ubuntu2                     amd64        POSIX-compliant shell
```

Bash version:
```
root@ubuntu:~# bash --version
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mtorromeo** [comment] 2016-11-02 09:32
The error message is misleading. `mktemp -d -t 'le'` is being called simply because the first `mktemp -d` failed for whatever reason.

It might be because the tmp is full or read only or whatever...

If you remove `2>/dev/null` you will unmask the real problem.

**Comment by lbgATts** [comment] 2016-11-22 04:56
@mtorromeo    I agreed with you,but i don't know why, if  mktemp -d 2>/dev/null returns true,the last one won't be executed

And the tmp has lots of volume.....,why this happened?

**Comment by mtorromeo** [comment] 2016-11-22 13:04
The point is that it doesn't return true, and the /dev/null redirection is masking the problem.

Just replace the entire `mktemp -d 2>/dev/null || mktemp -d -t 'le'` line with just `mktemp -d` and you will see the actual error message.

**Comment by zapu** [comment] 2016-11-28 12:34
Another thing to check if someone ran into this issue - I had no disk space left on / (and therefore /tmp) and that's why `mktemp` was failing.

**Comment by hackjob83** [comment] 2017-01-10 03:28
For what it's worth - I had the same thing happen to me on Debian 8 (Jessie) and the problem ended up being that I needed to run it as root. Chances are that others may run into the same thing if their user doesn't have the needed permissions.

**Comment by sks1024** [comment] 2017-02-03 18:27
Same thing here.  Needed sudo and command worked fine.

**Comment by bmw** [comment] 2017-02-04 01:03
What happens if you run:
```mktemp -d || mktemp -d -t 'le'
```
yourself without `sudo`?

**Comment by sks1024** [comment] 2017-02-04 01:13
No permissions to run file.

**Comment by bmw** [comment] 2017-02-06 20:32
Interesting. Does your user not have permissions to run `mktemp` or is `mktemp` unable to create directories at the path it's configured to on your system?

What's the output of:
```
ls -l $(command -v mktemp)
```
```
echo $TMPDIR
```
```
TMPDIR=. mktemp -d
```
This last command should create a temporary directory in your current directory which can be deleted.

**Comment by ln3333** [comment] 2017-02-13 08:07
I encountered the problem as well, caused by insufficient physical memory.

**Comment by PaulWoods4422** [comment] 2017-10-02 07:39
I encountered this when the disk was full!

**Comment by HALtheWise** [comment] 2018-05-11 18:38
I encountered this when the disk had space, but there were so many folders in the /tmp/ directory that the filesystem couldn't support any more.

**Comment by schoen** [comment] 2019-02-26 00:49
@bmw, it looks like this error is basically a catch-all error for the case where `mktemp` can't create temporary directories due to *some* kind of system resource limitation. Should we try to catch the error and explain this, or should we suggest that this be fixed upstream in GNU coreutils in order to produce more specific error messages there?

**Comment by bmw** [comment] 2019-02-26 16:51
I think the latter is the best long term solution. We could potentially do the former as well, but since relatively few people have hit this issue and no one has reported doing so in a long time, it's certainly not a high priority and I think we could even close the issue until people start hitting it again.

**Closed** 2020-03-27 19:53 UTC
Labels: area: certbot-auto, more-info, needs-update
