### ISSUE TITLE
a NameError on using "certbot certonly"

### ISSUE THREAD

**Issue by CuteSheep233** [certbot/certbot#6403] opened 2018-10-02 03:11 UTC
`
[root@VM_0_11_centos ~]# certbot certonly
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2700, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2733, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2730, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/lib/python2.7/site-packages/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'python_implementation' is not defined
`

**Comment by sydneyli** [comment] 2018-10-02 21:44
Hi @CuteSheep233, thanks for reporting! For future reference, you can also post similar questions to the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help) since it's not clear yet whether this is a Certbot issue or something with your particular setup-- you can get faster help there, too, since there's a larger audience of people also familiar with the project. Also, make sure to fill out the issue template so we can help you debug faster.

I'm guessing you're on CentOS. Is this a fresh VM? How did you install Certbot? Did it only recently start breaking for you or is this the first time you've tried?

**Comment by sydneyli** [comment] 2018-10-10 18:54
> I just follow the Certbot Install guide to Install Certbot..
[This one](https://certbot.eff.org/lets-encrypt/centosrhel7-nginx)? There are also several ways to install certbot listed [here](https://certbot.eff.org/docs/install.html). Which one did you follow?

**Comment by sydneyli** [comment] 2018-10-17 22:03
Going to close this issue since the issue isn't clear and may be a problem with the installation method/user's setup. @CuteSheep233, I recommend asking at the [community forums](https://community.letsencrypt.org/c/help) if you're still having trouble! If it turns out that the root cause is a Certbot bug, feel free to create a new issue or ask me to reopen this one.

**Closed by sydneyli** 2018-10-17 22:03 UTC
Labels: area: fedora / redhat / CentOS, area: pkging, more-info
