### ISSUE TITLE
wrong ssl protocol in options-ssl-apache.conf

### ISSUE THREAD

**Issue by sbraaa** [certbot/certbot#8043] opened 2020-06-03 08:28 UTC
## My operating system is (include version):
Ubuntu 12.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto, python 2.7

## I ran this command 
./certbot-auto renew --no-self-upgrade

## Certbot's behavior differed from what I expected because:
since 2 month SSL protocol  in file options-ssl-apache.conf get updated with invalid value.
the correct value is : 
`SSLProtocol             all -SSLv2 -SSLv3`
but recently, after renew, the value became : 
`SSLProtocol             all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1`

(obviously also SSLCipherSuite differs)

this doesn't let apache to restart correctly so I must revert the original copy of options-ssl-apache.conf (I have a backup!).

How can I prevent this behaviour?

**Comment by alexzorin** [comment] 2020-06-03 11:18
Certbot does not support any release of Ubuntu older than 16.04/Xenial. An issue like this is not unexpected when running an EOL operating system.

>How can I prevent this behaviour?

If Certbot detects that `options-ssl-apache.conf` has been modified (such that [it does not match any of these digests](https://github.com/certbot/certbot/blob/9e3c348dff75e6db4c27ae3e343d9e151d50862e/certbot-apache/certbot_apache/_internal/constants.py#L14-L31)), it will avoid modifying the file. So, a simple way to achieve this might be to add a comment to contents of `options-ssl-apache.conf`, such as:

    # WARNING: This file has been modified by hand and will not be automatically upgraded by Certbot

Hopefully that workaround will suit you, as the issue is otherwise wontfix due to the age of your OS.

**Closed by alexzorin** 2020-06-03 11:18 UTC
