### ISSUE TITLE
Document and announce DNS plugin snaps

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8142] opened 2020-07-08 20:47 UTC
~~This is blocked on us having builds of our DNS plugin snaps available which is being tracked at https://github.com/certbot/certbot/issues/8041.~~

One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run `sudo snap set certbot trust-plugin-with-root=ok` before installing the DNS plugin and then the `sudo snap connect` command shouldn't be needed.

I also think we should:

- [x] Add documentation to certbot.eff.org which is being tracked at https://github.com/certbot/website/issues/603.
- [x] Briefly mention the availability of DNS plugin snaps in our docs in this repo under `certbot/docs`.
- [ ] Make an announcement about DNS plugin snaps on the community forum.

**Comment by ohemorange** [comment] 2020-07-15 22:43
> One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run sudo snap set certbot trust-plugin-with-root=ok before installing the DNS plugin and then the sudo snap connect command shouldn't be needed.

This should only be true for snaps published on the snap store because it's based on the publisher, right? It certainly doesn't do this for snaps I compiled myself.

**Comment by bmw** [comment] 2020-07-15 22:48
Yeah that's what I think is going on. I have the same behavior as you with snaps built locally.

**Comment by ohemorange** [comment] 2020-07-23 22:14
> One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run sudo snap set certbot trust-plugin-with-root=ok before installing the DNS plugin and then the sudo snap connect command shouldn't be needed.

We should also make sure to document this in case something happens and it's installed before they're run

**Comment by ohemorange** [comment] 2020-07-24 00:32
> We should also make sure to document this in case something happens and it's installed before they're run

Actually, thinking about this more, I'd rather have people set the variable then install the plugin again instead of manually specifying connections. That seems like the sort of thing people shouldn't have to do. We may want a separate guide for people building third-party dns plugin snaps to write their own instructions, which will be different, though. Probably in `certbot/docs`.

**Comment by ohemorange** [comment] 2020-07-24 21:03
Proposed announcement text is here; comments welcome: https://docs.google.com/document/d/16fMLTCAnPVaTrf6BFa0TYF55k3kSX2Axh3dtpdhx53A/edit?usp=sharing

**Comment by a14m** [comment] 2020-08-10 13:48
Thanks a lot @bmw, I can confirm that the following commands work (for installing the plugin from snap)

```
sudo snap install --classic certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install --channel latest/beta certbot-dns-route53
```

also via ansible
```
- name: "Install: certbot (letsencrypt)"
  become: yes
  snap:
    name: certbot
    classic: yes

- name: "Trust certbot plugin install"
  become: yes
  shell: "snap set certbot trust-plugin-with-root=ok"
  changed_when: false

- name: "Install: certbot_dns_route53"
  become: yes
  snap:
    name: certbot-dns-route53
    channel: latest/beta
```

**Comment by ErikSwan** [comment] 2020-08-13 02:50
I can also confirm that using the snap with the DNS plugins (or, the Linode DNS plugin, at least) works great for me on Ubuntu 20.04 LTS!

```bash
sudo snap install --classic certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install --beta certbot-dns-linode

# Enter API credentials
sudo vim /etc/letsencrypt/linode-api-credentials.ini
sudo chmod 600 /etc/letsencrypt/linode-api-credentials.ini

sudo certbot \
    --dns-linode \
    --dns-linode-credentials /etc/letsencrypt/linode-api-credentials.ini \
    --dns-linode-propagation-seconds 120 \
    -i nginx \
    -d example.com \
    -d *.example.com
```
Installing the snap was painless and everything above worked exactly how I would expect it to. Hopefully once the announcement is made and any bugs are ironed out, this will be the long-awaited resolution to #6770, #6053, and others.

**Comment by ohemorange** [comment] 2020-08-18 20:01
Now that https://github.com/certbot/website/pull/613 is merged, we should do this announcement. Since we already announced the other things, what do you think of using the text in the doc above?

**Comment by bmw** [comment] 2020-08-18 20:44
That text looks good to me!

I think you should feel free to go ahead and post it. I can also do it myself if you'd prefer.

**Comment by ohemorange** [comment] 2020-08-18 21:05
Posted! https://community.letsencrypt.org/t/dns-plugins-now-available-as-snaps/131453

I think that should be it for this issue, so I'm going to close.

**Closed by ohemorange** 2020-08-18 21:05 UTC
Labels: area: dns, area: documentation, area: snaps, priority: high

**Comment by ohemorange** [comment] 2020-08-18 21:07
(If/when greedy plugs get implemented, we'll update the site to remove the `connect` step.)

**Comment by a14m** [comment] 2020-08-19 10:01
for reference, I didn't need the connect step in general while testing it out

**Comment by ohemorange** [comment] 2020-08-19 18:22
> for reference, I didn't need the connect step in general while testing it out

Yeah, you shouldn't have to run it for the *first* DNS plugin you install, but if for some reason you install multiple DNS plugins, you will need to run it after installing the second and further ones. It doesn't hurt to run it though, so it's included in the instructions for simplicity's sake. We hope to remove the requirement to run it at all ever soon; for more information, see: https://github.com/certbot/website/pull/613#issuecomment-667298454
