### ISSUE TITLE
Certbot crashes in cleanup for manual CSR for multiple domains with same server root

### ISSUE THREAD

**Issue by dgatwood** [certbot/certbot#4184] opened 2017-02-08 06:01 UTC
Apparently, when certbot tries to validate multiple domains in a single pass (e.g. using a custom CSR), if multiple domains share the same root directory, certbot dies with an exception because it has already removed the temporary authorization files from the directory and then tries to remove them a second time and cannot do so.

I've solved this in my copy by changing auth_handler.py:280 from:

            self.auth.cleanup(achalls)

to:

            try :
                self.auth.cleanup(achalls)
            except :
                pass

however, I suspect there's a better way to fix this that would be obvious to somebody who is more familiar with the code.

**Comment by SwartzCr** [comment] 2017-02-08 21:15
Interesting! Would you be able to share what system and server software you're using?
@bmw this looks like an easy fix, I marked it as a volunteer task but feel free to assign someone

**Comment by bmw** [comment] 2017-02-09 00:39
@dgatwood, can you provide a full log of the issue? Logs are by default stored in `/var/log/letsencrypt`. Feel free to redact values such as domain names and e-mail/IP addresses as you feel appropriate.

**Comment by bmw** [comment] 2017-03-14 00:15
@dgatwood, are you able to provide a log here?

**Comment by SwartzCr** [comment] 2017-08-28 21:14
I am going to close this since we don't have a log and we can't reproduce it. If we get more issues with future people who are providing their own CSRs then we can address it then, or if someone shows up with a log we can re-open this issue.

**Closed by SwartzCr** 2017-08-28 21:14 UTC
Labels: bug
