### ISSUE TITLE
Running certbot --nginx results in a config file with inconsistent indentation

### ISSUE THREAD

**Issue by coreh** [certbot/certbot#5633] opened 2018-02-28 00:41 UTC
Hey there! First of all, I'd like to thank everyone currently working on this tool. I'm really impressed with how well it works. I just finished setting up HTTPS for a project and the whole process was even smoother than the last time I did it, only a couple months ago. Basically zero hickups! 👏 🙇 

I'd like to report a minor issue that I found, which is that certbot will produce a nginx config file with mixed tabs/spaces if your existing config file is indented with tabs. The resulting file also ended up missing the trailing newline.

## My operating system is:

Ubuntu 16.04

## I installed Certbot with:

OS package manager

## I ran this command and it produced this output:

```bash
sudo certbot --nginx
```

Resulting config file:

```nginx
server {

	server_name redacted.example.com;

	root /var/www/redacted;
	index index.php index.html index.htm;

	location / {
		try_files $uri $uri/ =404;
	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/redacted.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/redacted.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = redacted.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;

	server_name redacted.example.com;
    return 404; # managed by Certbot


}
```

## Certbot's behavior differed from what I expected because:

Ideally, certbot should detect and honor the existing indentation convention of the file.

## Here is a Certbot log showing the issue (if available):
N/A

## Here is the relevant nginx server block for the domain I am configuring:
See above

Thanks in advance!

**Comment by sydneyli** [comment] 2018-02-28 17:16
Thanks for the input! This behavior is something we're aware of-- and a duplicate of #5157, so closing this issue.

**Closed by sydneyli** 2018-02-28 17:16 UTC
Labels: area: nginx
