### ISSUE TITLE
cli.ini arguments for non-PREFIX_FREE_DISTRIBUTIONS aren't parsed by ConfigParseArg

### ISSUE THREAD

**Issue by matthubb** [certbot/certbot#6040] opened 2018-05-25 16:40 UTC
## Summary

Certbot's cli.ini file will not support the same config items as the renewal conf files because the former is read by `ConfigArgParse` and the latter is read by `configobj`. It is not possible to supply plugin configuration options in the cli.ini for plugins not covered by `PREFIX_FREE_DISTRIBUTIONS`.

- Certbot forces third party plugins to have colons in their configuration arguments as `prefix-name:plugin-name`.
- Certbot's cli configuration will not support arguments that include colons because `ConfigArgParse` treats these as key-value separators.
- Certbot also converts hyphens to underscores in plugin prefixes while configuration arguments are written to renewal configuration files, these are not recognised in the `cli.ini`.

## Environment

I installed Certbot 0.24.0 with virtualenv + pip on CentOS 7.3

We're developing an auth plugin for our local DNS environment. We're having difficulties with the configuration system, specifically involving the colon in the `PluginEntryPoint.name`.

Say our module dist key is `certbot-dns-local-acme`,  and our module name is `certbot_dns_local_acme`, and our entry point name is `dns-local-acme`. The `cli.ini` line to use this is: `authenticator = certbot-dns-local-acme:dns-local-acme`.

The plugin includes an option to change the propagation wait time and a credential file using the configuration methods from `dns-common`. I provided a credential file interactively and obtained a test certificate.

## Certbot produced a renewal config that included:
```
[renewalparams]
authenticator = certbot-dns-local-acme:dns-local-acme
certbot_dns_local_acme:dns_local_acme_credentials = /opt/certbot/local_acme.ini
```
## With the config line from the renewal config.
Thinking I could use that configuration line in the `cli.ini` file.

### Config
```certbot_dns_local_acme:dns-local-acme-credentials = /opt/certbot/local_acme.ini```
### Certbot response:
```
certbot: error: unrecognized arguments: --certbot_dns_local_acme dns-local-acme-credentials = /opt/certbot/local_acme.ini
```
### Config
```certbot-dns-local-acme:dns-local-acme-credentials = /opt/certbot/local_acme.ini```
### Certbot response
```
certbot: error: ambiguous option: --certbot-dns-local-acme could match --certbot-dns-local-acme:dns-local-acme-propagation-seconds, --certbot-dns-local-acme:dns-local-acme-credentials
```

## Horrible hack

I've dug through the sources for `ConfigArgParse` and determined that it's not possible to have a colon in a key.

Why not use a delimiter that will work on the CLI and isn't a separator for `ConfigArgParse`?

All of the prefix-colon configuration problems are resolved by a horrible hack to add our plugin to `PREFIX_FREE_DISTRIBUTION` by adding this to our `__init__.py` file:
```
import inspect

def _patch():
    for frame_obj, filename, line, func, _, _ in inspect.stack():
        if func == '__init__' and frame_obj.f_locals['self'].__class__.__name__ == 'PluginEntryPoint':
            frame_obj.f_locals['self'].name = frame_obj.f_locals['entry_point'].name
            module_name = frame_obj.f_locals['entry_point'].dist.key
            pre_free_dist = frame_obj.f_locals['self'].PREFIX_FREE_DISTRIBUTIONS
            if module_name not in pre_free_dist:
                pre_free_dist.append(module_name)

_patch()
```

**Comment by ohemorange** [comment] 2018-05-29 21:13
You're right, this is a problem. Do you have any suggestions for fixing this that maintain backwards-compatibility for people?

**Comment by matthubb** [comment] 2018-05-31 13:33
Would backwards-compatibility be just supporting extant renewal configurations, or the cli.ini and any dns credential files as well?

I've not dug deep enough to understand the hyphens-to-underscores in the renewal configuration and whether or not those configurations are currently viable.

Picking a different delimiter for the prefix that is shell and `ConfigArgParse` safe is one route and maintain backwards compatibility by pre-processing configuration(s) to replace `:` with the new delimiter might work.

**Comment by ohemorange** [comment] 2018-06-01 20:52
Essentially, the test for what backwards compatibility means is that we don't want people using or developing other third-party plugins who already have everything set up to have to do any manual updates upon updating Certbot.

Ideally, we also want forwards compatibility -- when people downgrade certbot versions, things continue to work.

**Comment by ohemorange** [comment] 2018-09-18 00:40
@psimonyi, I love this!

I'm actually a fan of the first option: "always add both versions to the parser and just allow them both to be listed in help."

Seems the cleanest to implement, plus we can edit the old one with a deprecation notice. Our help is long enough that it's more for grepping than reading the whole thing anyway.

I'd love to see a PR with this solution!

**Comment by ohemorange** [comment] 2018-09-18 23:05
Actually, looks like this is a duplicate of #4351, which has a PR now at #6372, so I'm going to close this issue. @psimonyi, any chance you'd be interested in giving #6372 a review?

**Closed by ohemorange** 2018-09-18 23:05 UTC
Labels: area: 3rd party, feature request

**Comment by somini** [comment] 2020-08-17 10:32
This was closed but #4351 did not fix this, am I seeing this wrong? I'm on v1.7.0.

I get the plugin on "certbot plugins", but the new arguments are not parsed.

**Comment by adferrand** [comment] 2020-08-17 11:03
Hello @somini? Which argument are you trying to pass in `cli.ini`?

Please remember that for DNS plugins, the authentication parameters of the plugin itself are not valid flags, and so cannot be set in `cli.ini`. What is possible is to pass the credential file path that will contain the authentication parameters.

If I take the `dns-cloudflare` plugin for instance, `dns_cloudflare_api_token` or `dns_cloudflare_email` + `dns_cloudflare_api_key` cannot be set in `cli.ini`. Instead you can set `dns-cloudflare-credentials` in the `cli.ini` file (for instance to /path/to/credentials.ini`), then the `credentials.ini` file contains `dns_cloudflare_api_token` or `dns_cloudflare_email` + `dns_cloudflare_api_key` values.

**Comment by somini** [comment] 2020-08-17 21:12
Yes, that was precisely what I wanted to use. On `certbot plugins` I see:

```
* dns-henet
Description: Obtain certificates using a DNS TXT record (if you are using he.net
DNS for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-henet = certbot_dns_henet.dns_henet:Authenticator
```

Which has an option `--certbot_dns_henet:dns_henet_credentials` pointing to a file. Neither with the colon, nor just `dns_henet_credentials` work.

That plugin is not on the [list of blessed plugins](https://github.com/certbot/certbot/blob/68b3b048b9572e3901c145861c9e1add659a4ad7/certbot/certbot/_internal/plugins/disco.py#L26-L44), I guess that's the error?

**Comment by adferrand** [comment] 2020-08-17 21:18
No it should work with unofficial plugins also.

Did you try `dns-henet-credentials`? From the doc, the flag is refered as `--certbot-dns-henet:dns-henet-credentials`, so with dashes, not underscores. And certbot 1.7.0 introduced the possibility to use dns plugins without the prefix (here `certbot-dns-henet`).

**Comment by somini** [comment] 2020-08-17 21:33
> Did you try `dns-henet-credentials`? From the doc, the flag is refered as `--certbot-dns-henet:dns-henet-credentials`, so with dashes, not underscores. And certbot 1.7.0 introduced the possibility to use dns plugins without the prefix (here `certbot-dns-henet`).

That does it! Many thanks @adferrand.

The credentials themselves are also used without the prefix, but that failed loudly.
