### ISSUE TITLE
Implement periodic fetching of OCSP responses in a cron job

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#956] opened 2015-10-12 05:36 UTC
In #950, I add OCSP stapling in Nginx using its own fetcher. However, this is best-effort and fails to staple a response on the first request after startup.

Instead, we should use [ssl_stapling_file](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_file), which allows us to prefetch an OCSP response for each certificate and store it in a file to be loaded by Nginx. This will increase reliability, which is very important since we would like to eventually be able to implement OCSP Must Staple.

The cron job that fetches the OCSP response should run about once an hour. Even though OCSP responses are currently only regenerated every three days, this ensures that if there is any downtime or slop, the server gets an updated version very soon after it is available.

**Comment by hlieberman** [comment] 2015-10-15 16:24
If you do this as a script, a la letsencrypt-renewer, we can ensure that it is installed with a cronjob on Debian and its derivatives as part of the letsencrypt-nginx package.

**Comment by centminmod** [comment] 2015-11-01 19:12
i'd also be mindful that some folks have load balanced web servers and not just a standalone web server

**Comment by terrycloth** [comment] 2017-01-11 11:43
Something similar to @jsha's pull request is the only thing that works for me. (The *actual* solution I'm currently using is based on Troon's shell script and Nginx config lines [from comment 19 in this Let's Encrypt forum thread](https://community.letsencrypt.org/t/will-does-the-letsencrypt-client-create-a-cert-chain-usable-with-ocsp-stapling/2072/19).)

The certbot documentation recommends setting the Nginx config variable `ssl_trusted_certificate` to your chain.pem file. However, I was still getting messages like this:

> nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org/"

...in systemd journal, and Nginx was not sending the stapled OCSP response. I tried many variations on the configurations recommended in the certbot and Nginx documentation. However prefetching an OCSP response and using that for Nginx `ssl_stapling_file`, as mentioned, were the only things to properly enable OCSP stapling on my server:

* Fedora 25 Server x86_64
* Nginx 1.10.2
* certbot 0.9.3
* OpenSSL 1.0.2j

If jsha's pull request never gets merged, I think at least the certbot documentation should probably be updated.

**Comment by jsha** [comment] 2017-01-11 16:48
> The certbot documentation recommends setting the Nginx config variable ssl_trusted_certificate to your chain.pem file. However, I was still getting messages like this:

> nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org/"

I'm pretty sure that's unrelated to `ssl_trusted_certificate`. Sounds like you were having some DNS problems?

`ssl_trusted_certificate` only has an effect if you also use [`ssl_stapling_verify`](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling_verify). Were you using that?

**Comment by terrycloth** [comment] 2017-01-11 23:09
> `ssl_trusted_certificate` only has an effect if you also use `ssl_stapling_verify`. Were you using that?

Yes. However, the "ssl_stapling ignored" error went away after adding `ssl_stapling_file` and OCSP stapling seems still to be working even after removing `ssl_trusted_certificate`.

**Comment by terrycloth** [comment] 2017-01-11 23:13
...I'd hoped only to add my support for the idea of prefetching OCSP responses. If I'm getting off topic, then I could start a new bug report.

**Comment by SnijderC** [comment] 2017-02-14 13:01
@jsha We just release this, still in Alpha but might be interesting: https://github.com/greenhost/ocspd

**Comment by jsha** [comment] 2017-02-14 19:43
@SnijderC that looks awesome. I think it might be suitable for incorporation into Certbot as-is, or we could pull out the code for fetching and storing responses, and make it part of `certbot renew`. I posted on your repo: would you mind adding a license file so we know if we can use the code? Thanks!

**Comment by SnijderC** [comment] 2017-02-15 18:15
@jsha ok, so as you have probably seen, I added a license, we chose the same license as Certbots for convenience, I had to take a dependency out because it was incompatible. 

We wrote this to run in a web hosting environment, so it's made to be scalable, you can run multiple processes and it runs lengthy/blocking processes in threads. It's meant to run 24/7/365, so it's a daemon with quite a bit of error handling to prevent it from locking up. It's also very efficient in that it only refreshes *n* hours (default=2hrs) before the current staple expires.

Having said that, I think this doesn't quite match up with the "average certbot" user's requirements. So the way I see it is there are 3 ways to incorporate this in certbot.

1. We include it as a daemon as-is. We set some sane defaults for small scale use, 1 or 2 threads should work perfectly fine and the application is still very lean so no harm done.
2. We extract the main logic and make this part of the renew process, this seams to make sense because it's the least invasive way of including OCSP stapling for the "average certbot" user, though probably not the most common use case (I suspect it's Apache).
3. Not really incorporating but maybe you could simply reference to our project from yours for NGiNX and HAProxy users.

Also please note that we have no unittests because it's an application that just combines already existing components for the most part (this is not an excuse, I still do want to - and/or should have included some unittests). But for this kind of application functional tests seems to make more sense, but we didn't do this yet because it involves running an ocsp server etc.. By the way, if anyone wants to contribute to that, more than welcome! The reason for this explanation is that "incorporation as-is" seems to conflict with the testing coverage of your project.

So please let me know, what you think, and what you would like to do. If you would like to do any of the options outlined above, or you have a suggestion of your own, I would be more than happy to help out as much as I can.

**Comment by jsha** [comment] 2017-02-16 02:06
> We extract the main logic and make this part of the renew process, this seams to make sense because it's the least invasive way of including OCSP stapling for the "average certbot" user, though probably not the most common use case (I suspect it's Apache).

This seems ideal to me. @bmw, @ohemorange?

As you say, this doesn't solve the Apache use case. For Apache the fix would be to use [SSLStaplingForceURL](https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslstaplingforceurl) and point it at a local OCSP proxy. However, I'd be pretty happy to solve this problem just for Nginx and HAProxy for now. It would be straightforward to later write a small OCSP proxy that reads files from /etc/letsencrypt for use with Apache.

**Comment by bmw** [comment] 2017-02-28 18:39
I agree option 2 is probably the best approach and we'd certainly be open to incorporating something like this into Certbot.

The biggest potential concern I have here are about dependencies. What additional dependencies would Certbot need to do this? I'm a bit worried about making negative progress on #1301, [requiring dependencies that aren't available in Debian yet](https://github.com/greenhost/ocspd#debian-package), [adding another crypto library](https://github.com/greenhost/ocspd/blob/master/setup.py#L19), or [going back on our promise to Debian about not adding any new non-optional dependencies](https://lists.eff.org/pipermail/certbot-dev/2016-November/000005.html). We can certainly work around some or all of these problems, but I'm curious what would be required here.

@jsha, one question for you is how often would you like this to run? In your original post you suggested every hour. Would you want us to change our renewal recommendations to run `certbot renew` every hour or do you think our current every 12 hour recommendation good enough for this?

**Comment by jsha** [comment] 2017-02-28 19:56
Good point about the non-Debian deps. At first I thought this would only need asn1crypto, which we've previously considered including, but it [looks like](https://github.com/greenhost/ocspd/blob/a4a7202bcecc00f63ee282e885bf4b697f9ced9b/requirements.txt) it also pulls in oscrypto and ocspbuilder. I haven't looked at those to see how heavyweight they are.

Stepping back a bit: I think you told me offline that pycryptography and PyOpenSSL don't have the necessary functions to fetch and validate OCSP. Is that accurate? If so, some choices:
 1. don't support any OCSP fetching because Debian forbids us new dependencies
 2. maintain a Debian fork that doesn't do OCSP fetching
 3. shell out to OpenSSL for OCSP fetching
 4. define an extension mechanism for things that happen at "renew" time, and put OCSP fetching in its own Python package, which wouldn't be included in the Debian build.

I'm fine with fetching OCSP every 12 hours. That's more than sufficient for the stapling use case. For the "reissue if revoked for key compromise" use case, more frequently would be better, but let's cross that bridge when we come to it.

**Comment by SnijderC** [comment] 2017-03-01 15:31
5. Consider using this dependency and ask @wbond if he wants to maintain debian packages?

That would also help a lot for the ocspd project.

We've considered using various openssl bindings etc., before building ocspd, none of them seem to handle anything ocsp related. ocspbuilder seems to be the only library that doesn't imply running subprocess all over the place in ocspd. Which is btw exactly what certbot is doing to check for an ocsp response in `ocsp.py` ([here](https://github.com/certbot/certbot/blob/master/certbot/ocsp.py#L24)). That could also be improved if certbot would use this library, maybe in other places too. 

One thing I can say about this library is that it's crazy fast and uses OS native crypto where possible (which can be both an advantage and a disadvantage I suppose).

But, just thinking out loud - if things would go that direction, maybe your team should decide whether you want to use this crypto library first.

**Comment by bmw** [comment] 2017-03-02 18:05
> I think you told me offline that pycryptography and PyOpenSSL don't have the necessary functions to fetch and validate OCSP. Is that accurate?

Yeah. We've asked `pyopenssl` to implement this (pyca/pyopenssl#306), but it hasn't seen much traction and even if they added it now, we couldn't (always) use it due to older versions of the package being used in different distros. As pointed out above, we're currently shelling out to `openssl` for OCSP fetching.

I'm not sure if having Certbot depend on `oscrypto` at this time is really feasible. The problem is much larger than just Debian as Certbot is packaged for most major UNIX-like operating systems and as far as I know, `oscrypto` isn't packaged in any of them. We could try to vendorize `oscrypto`, but most distros aren't exactly fond of that and usually remove the vendorized dependencies before packaging. Alternatively, we could optionally depend on `oscrypto` and only offer OCSP fetching when `oscrypto` is available, but we've actively avoided optional dependencies like this in the past and the feature wouldn't benefit large portions of Certbot users.

I will say I've exchanged messages with wbond in the past and plan to look into the possibility of switching Certbot to `oscrypto` entirely, but this isn't really possible at this time. Assuming `ocspd` needs `oscrypto` for the logic we were talking about extracting above, I think the best path forward to add this feature to Certbot right now is to shell out to `openssl`.

**Comment by wbond** [comment] 2017-03-02 18:16
I would be open to exploring how to make ocspbuilder (and the other modularcrypto packages) work without oscrypto. Most of them utilize oscrypto simply because it is a very portable, easy-to-install cryptography packages that can do RSA, DSA and ECC sign/verify operations.

The current discussion of using asn1crypto (the heavy-lifter behind ocspbuilder) with something other than oscrypto is at https://github.com/wbond/asn1crypto/issues/6. Primarily I would like to make a simple way ensure that when oscpbuilder is installed, it is ready to use. It seems there isn't a great way to deal with an either-or dependency with PIP, is there?

If anyone knows of a resource for info about packaging Python libraries for various distros, I wouldn't mind looking into it, but it seems using ocspbuilder with cryptography would be the simpler path forward.

On a related note, asn1crypto will be a dependency in the next version of cryptography, so I imagine there will be some movement in getting that available via package managers.

**Comment by andersk** [comment] 2018-11-14 10:40
@SnijderC ocspd (now renamed to stapled) doesn’t work for this because it has no way to reload nginx after updating the staple file, and nginx can’t be bothered to reread the staple file by itself. It also won’t fetch its own OCSP responses if a staple file is present. So, where an nginx without stapled fails at serving a must-staple certificate on the first request, an nginx with stapled will eventually fail at serving a must-staple certificate on *every* request after the certificate is renewed. Please teach stapled to reload nginx (see also greenhost/stapled#5)?

**Comment by SnijderC** [comment] 2018-11-28 13:30
> @SnijderC ocspd (now renamed to stapled) doesn’t work for this because it has no way to reload nginx after updating the staple file, and nginx can’t be bothered to reread the staple file by itself. Worse, nginx won’t fetch its own OCSP responses when using a staple file—so, where an nginx without stapled fails at serving a must-staple certificate on the first request, an nginx with stapled will eventually fail at serving a must-staple certificate on _every_ request after the certificate is renewed. Please teach stapled to reload nginx (see also [greenhost/stapled#5](https://github.com/greenhost/stapled/issues/5))?

I see two ways to go about this, either certbot can do the reload, or we can add a module that does nginx reloading to stapled, which is also suggested in the linked issue. If there is demand for it we could add it, or anyone can do a PR on the project.

At this point in time I see more blocking issues for this to work than the lack of a call to `nginx -s reload` in a module. Either way that could be added to make stapled more useful for nginx users, but doesn't help solve this issue entirely.

@wbond 
> If anyone knows of a resource for info about packaging Python libraries for various distros, I wouldn't mind looking into it, but it seems using ocspbuilder with cryptography would be the simpler path forward.

Stapled is packaged for debian, centos, etc. you could have a look [at the way we did that](https://github.com/greenhost/stapled/blob/master/Makefile#L35) since it's also a python project. It's not a very simple process but there are some tools (that unfortunately need some tlc) that help make it a bit easier. We used [stdeb](https://pypi.org/project/stdeb/), which seems to be a bit of a hack but it gets the job done.

**Comment by canton7** [comment] 2019-06-04 06:44
Still interested in seeing this resolved!

**Comment by petecooper** [comment] 2020-05-08 08:27
I'm also interested in seeing this resolved, please.

**Comment by tdelmas** [comment] 2020-05-08 08:35
Related: https://github.com/certbot/certbot/issues/1028

**Comment by petecooper** [comment] 2020-05-17 10:31
According to https://trac.nginx.org/nginx/roadmap (timestamped Wayback Machine link: http://web.archive.org/web/20200517102939/https://trac.nginx.org/nginx/roadmap), Nginx 1.19.0 includes "OCSP validation for the clients certificates". At the time of writing it is due in around two days. I'll check release notes at release time and see how this affects this issue, if at all.

**Comment by bmw** [comment] 2023-06-21 15:07
I don't think we're going to do this, especially not anytime soon, so I'm going to close this as unplanned for now.

**Closed by bmw** 2023-06-21 15:07 UTC
Labels: area: nginx, area: ocsp, needs-update, priority: significant
