### ISSUE TITLE
Can hooks be used with certonly and run?

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4103] opened 2017-01-23 23:15 UTC
The answer is yes but I don't think we say this anywhere.

**Comment by bmw** [comment] 2017-01-24 00:34
A minor caveat here is `--renew-hook` isn't run when the certificate is first created, however, it is run when it is renewed. This confusing behavior is going away once #3947 is resolved.

**Comment by osirisinferi** [comment] 2017-03-14 16:24
IMHO this should also be reflected in `cli.py` as the pre- and post-hook are used only in `main.py`[1] and not in `renewal.py` while `cli.py` now [only outputs the help text in the `renew` section](https://github.com/certbot/certbot/blob/master/certbot/cli.py#L1028-L1050).

1: https://github.com/certbot/certbot/blob/master/certbot/main.py#L71-L98

**Comment by SwartzCr** [comment] 2017-08-31 19:15
This seems like a duplicate of #4561 - or at least associated.

**Closed** 2022-11-18 18:26 UTC
Labels: area: documentation, area: hooks, priority: unplanned
