### ISSUE TITLE
setuptools pkg_resources pip wheel failed with error code 1

### ISSUE THREAD

**Issue by painhardcore** [certbot/certbot#2883] opened 2016-04-22 13:50 UTC
``` bash
./letsencrypt-auto --help
```

``` bash
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
dialog is already the newest version (1.3-20160209-1).
python-virtualenv is already the newest version (15.0.1+ds-3).
virtualenv is already the newest version (15.0.1+ds-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for new version...
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/administrator/...ncrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

OS Ubuntu 16.04 LTS
Clean os

**Comment by vincentcox** [comment] 2016-04-23 09:13
same issue!

**Comment by vincentcox** [comment] 2016-04-23 09:17
Some details: nginx installed and also php7.0 fpm, for the rest clean install

**Comment by vincentcox** [comment] 2016-04-23 17:04
I solved it: just use "apt-get install letsencrypt". Super lame, but it works now

**Comment by joost-van-weenen** [comment] 2016-04-30 20:11
Same issue on ubuntu 16.04 with the client from git

**Comment by asibin** [comment] 2016-05-01 10:37
I managed to get it working on Ubuntu 16.04 Server LTS. I deleted the apt-get installed setuptools, reinstalled with pip and it worked. If you get setuptools complaining about the locale, make sure you have locales set.

**Comment by kfchoong** [comment] 2016-05-03 03:35
I resolved the issue by setting the locale variables. Without these, the script seems to break.
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

**Comment by bbnnt** [comment] 2016-06-08 09:44
For those who might have a look at it, and compared to other configuration tasks to be initially done on ubuntu, configuring locales seems opaque. Which guide could one recommend ?

**Comment by evgenity** [comment] 2016-08-05 09:03
This helped me:
```bash
> locale-gen en_US en_US.UTF-8
> dpkg-reconfigure locales
```

**Comment by chani** [comment] 2016-11-29 13:41
same issue, `apt-get install letsencrypt ` does not help to resolve that. To resolve that issue I had to:

```
~ # apt-get install python-pip
~ # pip install setuptools
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

then

```
~ # export LC_ALL="en_US.UTF-8"
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
~ # export LC_CTYPE="en_US.UTF-8"
~ # pip install setuptools
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

... then ...

```
~ # pip install --upgrade setuptools     
Collecting setuptools
  Downloading setuptools-29.0.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 3.0MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 20.7.0
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed setuptools-29.0.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

now it works.

**Comment by StavrosHacker** [comment] 2017-01-27 15:53
@chani thank you :)

**Comment by inoyakaigor** [comment] 2017-03-17 11:51
Also works for ru_RU locale 🇷🇺
> This helped me:
> 
> > locale-gen en_US en_US.UTF-8
> > dpkg-reconfigure locales

**Comment by porimol** [comment] 2017-03-29 04:33
I followed the solution given by @evgenity  and its perfect work.

**Comment by cyphercolt** [comment] 2017-04-27 21:20
This thread was helpful, thank you! I couldn't create a Virtual Environment with virtualenv for Python because of pip/locale issues. To fix it I went through everything everyone posted on here (especially reconfiguring the locale and installing pip setuptools)

Thanks again!

**Comment by yan12125** [comment] 2017-04-28 07:38
Seems this is a duplicate of #2887

**Comment by knowThis** [comment] 2017-09-04 07:05
I've tried the above solutions without solving the same problem.but i find some solution in "lnmp" about aliyun host problems . https://bbs.vpser.net/thread-16253-1-1.html#pid50671.
`apt-get purge python-virtualenv python3-virtualenv virtualenv
pip install --upgrade pip
pip install virtualenv
vim /bin/lnmp
`
replace /bin/certbot certonly  to /bin/certbot --no-bootstrap certonly

**Comment by xratzh** [comment] 2017-09-06 09:56
locale-gen en_US en_US.UTF-8 & locale-gen

**Comment by leonardozhe** [comment] 2017-11-26 16:05
Ubuntu 16.04 x64 Fixed issue by 2 step:
1. apt-get install letsencrypt
2. exoprt below
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

thanks!

**Comment by neoedmund** [comment] 2017-12-28 02:33
Add `--no-bootstrap` to certbot command line helps for me.
It seems a problem with python versions. Python 2.7 works well on the whole process. So you should uninstall all python3 before running certbot. But some system use Python3 as default, and when you running `virtualenv` , Python3 and Python2 messed up.
I wonder why certbot use `virtualenv`? 
I also suggest cerbot don't try to install packages because you don't know what python version of packages will be installed actually. And bring your own dependence binaries. Because sometime dependence is hell.

**Comment by robguinness** [comment] 2018-01-24 17:27
Setting the locales also worked for me. Is this considered an actual bug in certbot, a documentation issue, or a user error???

**Comment by AjkP** [comment] 2018-02-04 05:35
+1 on getting this documented OR fixed.

**Comment by azzzdiggr** [comment] 2018-05-21 09:27
For me, It worked with this... Please read the error then follow any instructions.

$export LC_ALL="en_US.UTF-8"
$export LC_CTYPE="en_US.UTF-8"

$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $key
$ sudo apt-get update

Replace $key with the corresponding $key from your GPG error.

for SSL certificate Signing with certbot  using letsencrypt
$ certbot-auto certonly --standalone -d $DOMAIN --preferred-challenges http \
 --agree-tos -n -m $EMAIL --keep-until-expiring

**Comment by Ayms** [comment] 2018-06-18 14:18
```
Traceback (most recent call last):
  File "/tmp/tmp.03OPotGaYT/fetch.py", line 21, in <module>
    import ssl
  File "/usr/local/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /usr/local/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
WARNING: unable to check for updates.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pip wheel failed with error code 1
```

**Comment by Ayms** [comment] 2018-06-18 15:25
It looks to be working now after using the instructions in last comment of https://stackoverflow.com/questions/42189878/pythonsetuptools-pkg-resources-pip-wheel-failed-with-error-code-1-error/42189903

Don't get very well why something that is supposed to ease the life of everybody is so complicate to install, would be much easier with a simple nodejs module

**Comment by wwboy6** [comment] 2018-08-03 12:00
This error can be reproduced when index-url of pkg-resoures is set to the server without complete resources. This would happen to the user using cloud service with custom pip.conf. Update pip.conf would be a possible solution to this issue.
```
mv /root/.pip/pip.conf  /root/.pip/pip.conf.bk
vi /root/.pip/pip.conf 
```
insert following to pip.conf
```
[global]
#index-url=http://mirrors.aliyun.com/pypi/simple/
index-url = https://pypi.python.org/simple/
[install]
#trusted-host=mirrors.aliyun.com
trusted-host=pypi.python.org
```

Reference (Chinese website): https://blog.csdn.net/Tsinghua2MIT/article/details/79945625

**Comment by bmw** [comment] 2018-08-15 15:46
I closed #2887 as a duplicate of this, but wanted to keep a link to [yan12125's helpful comment](https://github.com/certbot/certbot/issues/2887#issuecomment-297930399).

**Comment by boyaziqi** [comment] 2018-12-28 06:34
I resolved the issue by following @wwboy6 answer.

**Comment by bote100** [comment] 2019-08-11 13:14
This commands solved my problem:

`sudo pip install --upgrade setuptools
sudo pip install --upgrade virtualenv
sudo pip install --upgrade pip`

**Comment by 1181406961** [comment] 2019-11-18 03:49
> This commands solved my problem:
> 
> `sudo pip install --upgrade setuptools`
> `sudo pip install --upgrade virtualenv`
> `sudo pip install --upgrade pip`

thanks。This method  solved my problem. The virtualenv's version is too old.

**Comment by bmw** [comment] 2019-11-20 00:01
I would strongly advise against running `sudo pip`. A few of the reasons why are described at https://pages.charlesreid1.com/dont-sudo-pip/.  Do not run the `sudo pip install` command at the top of that page on any system you care about.

**Comment by zvolsky** [comment] 2019-12-13 17:09
I've tried allmost everything here include:
@knowThis: I've tried the above solutions without solving the same problem but...
> `apt-get purge python-virtualenv python3-virtualenv virtualenv`
> `pip install virtualenv`
and this doesn't help me. But then I did:
`apt install python-virtualenv python3-virtualenv virtualenv`
and it works.
(/etc/debian_version: 9.9 - but maybe the system is not properly updated yet, I just confirmed new repos during `apt update`)

**Closed** 2021-01-20 04:42 UTC
Labels: area: certbot-auto, needs-update
