### ISSUE TITLE
privkey.pem readable by group & others

### ISSUE THREAD

**Issue by ea167** [certbot/certbot#2878] opened 2016-04-21 01:56 UTC
Hi,
First of all, congrats for the great work and the easiness of getting certificates!

The privkey.pem file generated has access rights that are too permissive:
-- in the keys/ directory, the private key rights are good
     `-rw-------. 1 root root 1704 Apr 21 01:20 0000_key-letsencrypt.pem`
-- but archive/dom.ain.name/privkey1.pem is readable by everyone
     `-rw-r--r--. 1 root root 1704 Apr 21 01:20 privkey1.pem`

We need to 
`chmod go-r archive/dom.ain.name/privkey{insert index here}.pem`

I'm using latest git version, on CentOS 7

Hope it helps!

**Comment by bmw** [comment] 2016-04-21 16:39
I agree that the permissions need to be changed. I think this is a duplicate of #1473 though.

**Comment by sydneyli** [comment] 2018-10-24 22:59
Closing as dup (just happened to come across this issue while digging)

**Closed by sydneyli** 2018-10-24 22:59 UTC
Labels: duplicate
