### ISSUE TITLE
ubuntu 12.04: broken pip

### ISSUE THREAD

**Issue by antirek** [certbot/certbot#6875] opened 2019-03-21 05:01 UTC
My OS: Ubuntu 12.04 
Certbot installed via instructions from https://certbot.eff.org/lets-encrypt/ubuntuother-other

run ./certbot-auto --renew
get error:
````
Creating virtual environment...
Installing Python packages...
/opt/eff.org/certbot/venv/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
Traceback (most recent call last):
  File "/tmp/tmp.lWVOP4tvNG/pipstrap.py", line 177, in <module>
    sys.exit(main())
  File "/tmp/tmp.lWVOP4tvNG/pipstrap.py", line 149, in main
    pip_version = StrictVersion(check_output([python, '-m', 'pip', '--version'])
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/opt/eff.org/certbot/venv/bin/python', '-m', 'pip', '--version']' returned non-zero exit status 1
`````

I reinstalled certbot, python, pip. But received this error again.

**Comment by adferrand** [comment] 2019-03-21 08:16
Hello! Indeed certbot-auto does not work anymore on EOL Linux distributions, and will not be fixed because we do not support distributions that reached their end of life. 

Explanations and temporary mitigations can be found on this issue #6824 and this Letsencrypt support topic https://community.letsencrypt.org/t/pip-error-with-certbot-auto/88200.

Closing as a duplicate of #6824.

**Closed by adferrand** 2019-03-21 08:16 UTC

**Comment by antirek** [comment] 2019-03-21 08:45
Thanks, Adrien. Now I fixed like in support topic, remove some code from certbot-auto )) . In next week I will upgrade this server to actual ubuntu. Thanks again, good day.
