### ISSUE TITLE
Docker image is broken - ContextualVersionConflict with idna

### ISSUE THREAD

**Issue by FireFart** [certbot/certbot#6563] opened 2018-12-05 23:08 UTC
The Docker image is currently broken:

```
[firefart@fedora ~]$ docker pull certbot/certbot
Using default tag: latest
latest: Pulling from certbot/certbot
Digest: sha256:c66f6446371b55c937b474c64bff13a19d20b1e45e0a66f80cebba78e3f129bc
Status: Image is up to date for certbot/certbot:latest

[firefart@fedora ~]$ docker run --rm -it certbot/certbot certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.8 (/usr/local/lib/python2.7/site-packages), Requirement.parse('idna<2.8,>=2.5'), set(['requests']))
```

**Comment by adamlundrigan** [comment] 2018-12-06 00:22
Same with certbot/dns-route53.  Manually pulling `v0.28.0` "fixed" it.

**Comment by bmw** [comment] 2018-12-06 02:07
Thanks for reporting this. This issue is fixed in the Certbot image and is propagating out to the images for the DNS plugins.

If you're curious, the issue was caused by https://github.com/requests/requests/issues/4890, https://github.com/pypa/pip/issues/988, and the lack of a workaround on our end for those problems.

**Closed by bmw** 2018-12-06 02:07 UTC
