### ISSUE TITLE
certbot restores old version of site config on renew

### ISSUE THREAD

**Issue by mechmind** [certbot/certbot#4375] opened 2017-03-18 09:17 UTC
## My operating system is (include version):
archlinux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
os package manager, version 0.12.0-1

## I ran this command and it produced this output:
certbot renew (updated successfully)

## Certbot's behavior differed from what I expected because:
certbot replaced current nginx config for server with old version of this config. The difference between configs are in some rewrites, letsencrypt part is not modified.

**Comment by pde** [comment] 2017-03-21 19:28
Hi @mechmind. That sounds rather bad! Would you be able to post your config file and the logs from your letsencrypt runs?

**Comment by mechmind** [comment] 2017-03-22 00:15
Config and logs (hostname redacted with sed): https://gist.github.com/mechmind/ecf7250ccb212ff2e227d4e44fd6e620

**Comment by mechmind** [comment] 2017-03-28 14:15
Any news?

**Comment by ohemorange** [comment] 2017-03-30 17:42
@mechmind, looking into this!

**Comment by ohemorange** [comment] 2017-04-04 21:20
Hi @mechmind, could you tell us exactly what the changes were? Also, when you first ran certbot for these sites (looks like there's two certificates that were renewed here), what flags did you use? Did you select "easy" or "secure" as a response to "Please choose whether HTTPS access is required or optional."?

**Comment by mechmind** [comment] 2017-04-05 13:02
certbot removes some locations from config (notably /dumps and /monitor). SSL options and includes are not touched. I use letsencrypt client since it was just `letsencrypt` command and nginx plugin was in beta, so i'm not sure if easy/secure option was even shown to me.

**Comment by ohemorange** [comment] 2017-04-05 20:29
Thanks for the info! I'm still having trouble reproducing this.

Would you mind posting the redacted contents of (if they exist):
```
/etc/letsencrypt/cli.ini
/etc/letsencrypt/renewal/<certs_that_got_renewed>.conf
```

You will want to remove any domains and account IDs.

Also, do you know if you first got your certs using `certonly`, or using `run` (which is the same as no subcommand)? It looks like you used the `--nginx` flag, can you confirm?

**Comment by mechmind** [comment] 2017-04-06 13:24
Here the renewal config and backup of nginx config i found in /var/lib/letsencrypt/backups . There are no /etc/letsencrypt/cli.ini in my system.

**Comment by ohemorange** [comment] 2017-04-06 19:06
Did running certbot also rearrange the directives towards the top of the server block back to the way they appear in the backup?

**Comment by mechmind** [comment] 2017-04-06 21:51
Seems like it just restores backup as is.

**Comment by ohemorange** [comment] 2017-04-06 22:12
Would you mind backing up your current config file and running `certbot renew` to see if it does it again? This should not renew your certs again, since they're still valid.

**Comment by mechmind** [comment] 2017-04-06 22:52
It does not touch configs nor certificates because it's too early for renew.

**Comment by mechmind** [comment] 2017-06-06 20:33
So time has come and i've performed another renewal. I updated certbot and certbot-nginx to 0.14.2 and ran `certbot --nginx`. Everything proceed fine and certbot patched only two lines in config related to ssl certs.

**Comment by bmw** [comment] 2017-06-07 20:54
Great! I'm glad it worked for you. I'm closing this for now because no one can reproduce it, but if anyone does, please comment and I'll reopen.

**Closed by bmw** 2017-06-07 20:54 UTC
Labels: area: nginx, area: renewal, bug, more-info
