### ISSUE TITLE
Failed to renew certificate with error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by HumanG33k** [certbot/certbot#9824] opened 2023-10-28 17:32 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Devuan 5

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Package manager => certbot 2.1.0

## I ran this command and it produced this output:
certbot renew -v

## Certbot's behavior differed from what I expected because:
It not renew my certificate.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
Renewing an existing certificate for domain.com and *.domain.com
Encountered exception during recovery: simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Failed to renew certificate domain.com with error: Expecting value: line 1 column 1 (char 0)
```
And the full traceback : 

```
1 column 1 (char 0)
2023-10-28 19:20:49,124:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/_internal/renewal.py", line 532, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1540, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 126, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3/dist-packages/certbot/_internal/renewal.py", line 395, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_ovh/_internal/dns_ovh.py", line 59, in _perform
    self._get_ovh_client().add_txt_record(domain, validation_name, validation)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common_lexicon.py", line 50, in add_txt_record
    self.provider.create_record(rtype='TXT', name=record_name, content=record_content)
  File "/usr/lib/python3/dist-packages/lexicon/providers/base.py", line 80, in create_record
    return self._create_record(rtype, name, content)
  File "/usr/lib/python3/dist-packages/lexicon/providers/ovh.py", line 111, in _create_record
    self._post('/domain/zone/{0}/refresh'.format(domain))
  File "/usr/lib/python3/dist-packages/lexicon/providers/base.py", line 145, in _post
    return self._request('POST', url, data=data, query_params=query_params)
  File "/usr/lib/python3/dist-packages/lexicon/providers/ovh.py", line 242, in _request
    return result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Only thing i see it can interfer t's the fact i had another specific subdomain with valid certificate : mysub.domain.com

I use for both the same config. (ovh and apache plugin) but i probably miss a step or something like that.

**Comment by bmw** [comment] 2023-10-31 15:17
I believe this is a duplicate of https://github.com/certbot/certbot/issues/9799. It's a problem in the dns-lexicon package Certbot depends on, caused by an API change by OVH, and was fixed in version 3.15.1 of dns-lexicon. [You could use Docker or pip](https://eff-certbot.readthedocs.io/en/latest/install.html) to get newer versions of the packages than your distro maintainers provide.

**Closed by bmw** 2023-10-31 15:17 UTC
