### ISSUE TITLE
Debian Linux - Command failed with error code 1

### ISSUE THREAD

**Issue by danger89** [certbot/certbot#3095] opened 2016-05-30 11:15 UTC
I really try to install let's encrypt under Debian Jessie Linux. Too bad the backports are also broken, so I tried wgetting the certbot-auto file. 

Running:
`./certbot-auto`

Gives me:
```
....
Fetched 6664 B in 5s (1260 B/s)          
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pip wheel failed with error code 1
```

I would expect that the installation succeed.

Kind regards,
Melroy van den Berg

**Comment by chriscroome** [comment] 2016-05-30 14:14
The client is available in `jessie-backports`, it has been renamed to `certbot` and the documentation has yet to be updated, see https://github.com/certbot/website/issues/120

**Comment by bmw** [comment] 2016-05-31 20:22
@danger89, if you're on Debian Jessie, the `certbot` packages in backports should be preferred. With that said, this is still a bug and `certbot-auto` should work on Debian.

This appears to be a duplicate of #2887 so I'm closing this issue.

**Closed by bmw** 2016-05-31 20:22 UTC

**Comment by danger89** [comment] 2016-06-09 14:47
I submitted a serious bug regarding the certbot package in the backport:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825830
