### ISSUE TITLE
Segfaults in openssl

### ISSUE THREAD

**Issue by hollaho** [certbot/certbot#5033] opened 2017-08-16 22:17 UTC
## My operating system is (include version):
Gentoo-current

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
emerge -avuDN =app-crypt/certbot-0.15.0

## I ran this command and it produced this output:
strace certbot -v certonly -d multiple -d valid -d domains
The same happens without strace of course, then without the trace output.

## Certbot's behavior differed from what I expected because:
It segfaulted:
certbot[4183]: segfault at 7f21ec4fe9b0 ip 00007f21ec4fe9b0 sp 00007ffdec8c2608 error 15 in _openssl.abi3.so[7f21ec4f7000+8000]

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
017-08-16 22:05:29,052:DEBUG:certbot.main:certbot version: 0.15.0
2017-08-16 22:05:29,054:DEBUG:certbot.main:Arguments: ['-v', '-d', 'xxxxx.net', '-d', 'cloud.xxxxx.net', '-d', 'dyn.xxxxx.net', '-d', 'imap.xxxxx.net', '-d', 'mail.xxxxx.net', '-d', 'xxxx.de', '-d', 'smtp.xxxxxx.net', '-d', 'static.xxxxxxxx.net', '-d', 'ldap.xxxxxxxxxxx.net', '-d', 'sql.xxxxxxxxx.net', '-d', 'www.xxxxxxxx.net']
2017-08-16 22:05:29,054:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-08-16 22:05:29,176:DEBUG:certbot.log:Root logging level set at 10
2017-08-16 22:05:29,179:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-08-16 22:05:29,182:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-08-16 22:05:29,515:DEBUG:certbot_apache.configurator:Apache version is 2.4.27
2017-08-16 22:05:30,806:DEBUG:certbot.plugins.selection:Multiple candidate plugins: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f02ce0a0860>
Prep: True

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f02ce0ae240>
Prep: True

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f02cd40fb70>
Prep: True
2017-08-16 22:05:36,596:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f02ce0a0860> and installer None
2017-08-16 22:05:36,781:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(new_authzr_uri='https://acme-v01.api.letsencrypt.org/acme/new-authz', body=Registration(agreement='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', contact=('mailto:www@xxxxx.net',), status=None, key=xxxxx(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0xxxxxxxx>)>)), terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', uri='https://acme-v01.api.letsencrypt.org/acme/reg/xxxxxxxx'), xxxxxxxxxxxx, Meta(creation_host='xxxxxx.xxxxx.net', creation_dt=datetime.datetime(2016, xx, xx, xx, xx, tzinfo=<UTC>)))>
2017-08-16 22:05:36,789:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-08-16 22:05:36,808:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
--> here it segfaults and stopped logging

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant as it happens also in webroot mode

## Here is the last lines from strace
getsockopt(10, SOL_SOCKET, SO_TYPE, [1], [4]) = 0
ioctl(10, FIONBIO, [1])                 = 0
getpeername(10, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("88.221.71.152")}, [16]) = 0
getrandom("\x0a\xcf\xa8\x11\x06\xb2\xc1\x39\xd7\x7a\x7a\x95\xfc\xf2\x7a\x80\xd4\xc9\x69\x15\xd4\xbb\xff\xd4\x49\xc6\x47\x07\x2b\x4b\x8c\x8a", 32, GRND_NONBLOCK) = 32
write(10, "\26\3\1\2\0\1\0\1\374\3\3\n\317\250\21\6\262\3019\327zz\225\374\362z\200\324\311i\25\324"..., 517) = 517
read(10, 0xf03d9ad240, 7)               = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=10, events=POLLIN}], 1, 45000) = 1 ([{fd=10, revents=POLLIN}])
read(10, "\26\3\3\0A\2\0", 7)           = 7
read(10, "\0=\3\3\370\36\322\324D\22\242\302\376\234\375\322\31\272\374\246\311\311\371\10\3404\36\246,\316<\317"..., 63) = 63
read(10, "\26\3\3\24\231", 5)           = 5
read(10, "\v\0\24\225\0\24\222\0\7\0230\202\7\0170\202\5\367\240\3\2\1\2\2\20\177\0\0\1\0\0\1"..., 5273) = 1373
read(10, 0xf03d9ad7a5, 3900)            = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=10, events=POLLIN}], 1, 45000) = 1 ([{fd=10, revents=POLLIN}])
read(10, "ttp://validation.identrust.com/c"..., 3900) = 2648
read(10, "#\33]3\23\22]\304\1%\3660\335\2]\237\340\325G\275\264\353\33\241\273II\330\237[\2\363"..., 1252) = 1252
read(10, "\26\3\3\1M", 5)               = 5
read(10, "\f\0\1I\3\0\27A\4b\324\357x\10V\1\236$4\32\321u\33?\225}7\v\305\36/\7"..., 333) = 191
read(10, 0xf03d9ad307, 142)             = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=10, events=POLLIN}], 1, 45000) = 1 ([{fd=10, revents=POLLIN}])
read(10, "\324\361\354\211\0058\205\373\205\343g\31\271P\rQ\37\275\263\230\372E\331\36;\261C\243\215b\6\317"..., 142) = 142
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f02ced1d9b0} ---
+++ killed by SIGSEGV +++

**Comment by Neliger** [comment] 2017-08-21 09:40
I have the same issue, and can't find any wordaround.

I currently have to replace some nearly expired Let's Encrypt certificate with traditional ones.

**Comment by SwartzCr** [comment] 2017-08-22 22:35
@bmw any thoughts?

**Comment by bmw** [comment] 2017-08-22 22:46
What version of Python are you using for Certbot?

On the system where Certbot is having trouble, what's the output of:
```
python -c 'from __future__ import print_function; import requests; print(requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45).text)'
```
where `python` is the same version of Python that you're using for Certbot?

**Comment by Neliger** [comment] 2017-08-22 22:51
Python 3.4.5 here.

`# python -c 'from __future__ import print_function; import requests; print(requests.Session().request("GET", "https://acme-v01.api.letsencrypt.org/directory", verify=True, timeout=45).text)'
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}`

**Comment by bmw** [comment] 2017-08-23 17:14
Interesting. Other than the `User-Agent` string, that should be identical to what Certbot is doing when it crashes.

Can you provide the full output of:
```
python -X faulthandler $(command -v certbot) --debug --verbose ...
```
Please add any other command line flags to the end of that command so you can reproduce the bug. Also, feel free to redact values like domains, email, and IP addresses as you feel is appropriate. Again, `python` should be the same version of Python that you're using for Certbot.

**Comment by Neliger** [comment] 2017-08-23 17:19
Thanks for your attention, hope this will help : 

# python -X faulthandler $(command -v certbot) --debug --verbose renew
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/<edited>.conf
-------------------------------------------------------------------------------
Requested authenticator <certbot.cli._Default object at 0x6c0715dab320> and installer <certbot.cli._Default object at 0x6c0715dab320>
Default Detector is Namespace(account=<certbot.cli._Default object at 0x6c0715d934e0>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x6c0715d937b8>, apache=<certbot.cli._Default object at 0x6c0715da9da0>, authenticator=<certbot.cli._Default object at 0x6c0715dab320>, break_my_certs=<certbot.cli._Default object at 0x6c0715da9978>, cert_path=<certbot.cli._Default object at 0x6c0715dad320>, certname=<certbot.cli._Default object at 0x6c0715d92eb8>, chain_path=<certbot.cli._Default object at 0x6c0715dabbe0>, checkpoints=<certbot.cli._Default object at 0x6c0715dabe10>, config_dir=<certbot.cli._Default object at 0x6c0715dab9b0>, config_file=None, configurator=<certbot.cli._Default object at 0x6c0715dab320>, csr=<certbot.cli._Default object at 0x6c0715dabb70>, debug=True, debug_challenges=<certbot.cli._Default object at 0x6c0715da9438>, dialog=None, dns_cloudflare=<certbot.cli._Default object at 0x6c0715da92e8>, dns_cloudxns=<certbot.cli._Default object at 0x6c0715da9128>, dns_digitalocean=<certbot.cli._Default object at 0x6c0715d93048>, dns_dnsimple=<certbot.cli._Default object at 0x6c0715d93358>, dns_google=<certbot.cli._Default object at 0x6c0715d93748>, dns_nsone=<certbot.cli._Default object at 0x6c0715d939e8>, dns_route53=<certbot.cli._Default object at 0x6c0715d93cc0>, domains=<certbot.cli._Default object at 0x6c0715d92be0>, dry_run=<certbot.cli._Default object at 0x6c0715d8ba20>, duplicate=<certbot.cli._Default object at 0x6c0715d93390>, eff_email=<certbot.cli._Default object at 0x6c0715e25128>, email=<certbot.cli._Default object at 0x6c0715dfc6d8>, expand=<certbot.cli._Default object at 0x6c0715d93e10>, force_interactive=<certbot.cli._Default object at 0x6c0715d92a20>, fullchain_path=<certbot.cli._Default object at 0x6c0715dabda0>, func=<function renew at 0x6c0715e07620>, hsts=<certbot.cli._Default object at 0x6c0715da9dd8>, http01_address=<certbot.cli._Default object at 0x6c0715da9898>, http01_port=<certbot.cli._Default object at 0x6c0715da97b8>, ifaces=<certbot.cli._Default object at 0x6c0715dad160>, init=<certbot.cli._Default object at 0x6c0715dabef0>, installer=<certbot.cli._Default object at 0x6c0715dab320>, key_path=<certbot.cli._Default object at 0x6c0715dabf98>, logs_dir=<certbot.cli._Default object at 0x6c0715dab668>, manual=<certbot.cli._Default object at 0x6c0715da9780>, manual_auth_hook=<certbot.cli._Default object at 0x6c0715e25320>, manual_cleanup_hook=<certbot.cli._Default object at 0x6c0715d8ba90>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0x6c0715d8bdd8>, must_staple=<certbot.cli._Default object at 0x6c0715da9b38>, nginx=<certbot.cli._Default object at 0x6c0715da9ac8>, no_bootstrap=<certbot.cli._Default object at 0x6c0715da9080>, no_self_upgrade=<certbot.cli._Default object at 0x6c0715d93080>, no_verify_ssl=<certbot.cli._Default object at 0x6c0715da9518>, noninteractive_mode=<certbot.cli._Default object at 0x6c0715d92828>, num=<certbot.cli._Default object at 0x6c0715daba20>, os_packages_only=<certbot.cli._Default object at 0x6c0715d93240>, post_hook=<certbot.cli._Default object at 0x6c0715dab5f8>, pre_hook=<certbot.cli._Default object at 0x6c0715dab518>, pref_challs=<certbot.cli._Default object at 0x6c0715dab438>, prepare=<certbot.cli._Default object at 0x6c0715dad048>, quiet=<certbot.cli._Default object at 0x6c0715da9160>, reason=<certbot.cli._Default object at 0x6c0715dabd30>, redirect=<certbot.cli._Default object at 0x6c0715da9c18>, register_unsafely_without_email=<certbot.cli._Default object at 0x6c0715d8b898>, reinstall=<certbot.cli._Default object at 0x6c0715e25240>, renew_by_default=<certbot.cli._Default object at 0x6c0715d93a58>, renew_hook=<certbot.cli._Default object at 0x6c0715dab6d8>, renew_with_new_domains=<certbot.cli._Default object at 0x6c0715d93908>, rsa_key_size=<certbot.cli._Default object at 0x6c0715da9a58>, server=<certbot.cli._Default object at 0x6c0715dab4a8>, staging=<certbot.cli._Default object at 0x6c0715da9240>, standalone=<certbot.cli._Default object at 0x6c0715da9940>, standalone_supported_challenges=<certbot.cli._Default object at 0x6c0715d92d30>, staple=<certbot.cli._Default object at 0x6c0715dab198>, strict_permissions=<certbot.cli._Default object at 0x6c0715dab358>, text_mode=<certbot.cli._Default object at 0x6c0715d92630>, tls_sni_01_address=<certbot.cli._Default object at 0x6c0715da96d8>, tls_sni_01_port=<certbot.cli._Default object at 0x6c0715da95f8>, tos=<certbot.cli._Default object at 0x6c0715d93668>, uir=<certbot.cli._Default object at 0x6c0715da9f98>, update_registration=<certbot.cli._Default object at 0x6c0715d8b8d0>, user_agent=<certbot.cli._Default object at 0x6c0715dabb38>, validate_hooks=<certbot.cli._Default object at 0x6c0715dab7b8>, verb='renew', verbose_count=True, webroot=<certbot.cli._Default object at 0x6c0715da94a8>, webroot_map=<certbot.cli._Default object at 0x6c0715d924a8>, webroot_path=<certbot.cli._Default object at 0x6c0715e254a8>, work_dir=<certbot.cli._Default object at 0x6c0715dab828>)
Should renew, less than 30 days before certificate expiry 2017-09-19 02:00:00 UTC.
Cert is due for renewal, auto-renewing...
Requested authenticator webroot and installer None
Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x6c0715d920b8>
Prep: True
Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x6c0715d920b8> and installer None
Picked account: <Account(RegistrationResource(uri='https://acme-v01.api.letsencrypt.org/acme/reg/9831683', body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x6c07256fc320>)>), status=None, contact=(), agreement='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'), terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', new_authzr_uri='https://acme-v01.api.letsencrypt.org/acme/new-authz'), a3cef16ef2c379b2bee5ec28c61f8e8a, Meta(creation_dt=datetime.datetime(2017, 2, 20, 16, 41, 19, tzinfo=<UTC>), creation_host='<edited>'))>
Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Fatal Python error: Segmentation fault

Current thread 0x00006c072581e700 (most recent call first):
  File "/usr/lib64/python3.4/ssl.py", line 807 in do_handshake
  File "/usr/lib64/python3.4/ssl.py", line 580 in __init__
  File "/usr/lib64/python3.4/ssl.py", line 362 in wrap_socket
  File "/usr/lib64/python3.4/site-packages/urllib3/util/ssl_.py", line 308 in ssl_wrap_socket
  File "/usr/lib64/python3.4/site-packages/urllib3/connection.py", line 289 in connect
  File "/usr/lib64/python3.4/site-packages/urllib3/connectionpool.py", line 831 in _validate_conn
  File "/usr/lib64/python3.4/site-packages/urllib3/connectionpool.py", line 352 in _make_request
  File "/usr/lib64/python3.4/site-packages/urllib3/connectionpool.py", line 595 in urlopen
  File "/usr/lib64/python3.4/site-packages/requests/adapters.py", line 423 in send
  File "/usr/lib64/python3.4/site-packages/requests/sessions.py", line 596 in send
  File "/usr/lib64/python3.4/site-packages/requests/sessions.py", line 475 in request
  File "/usr/lib64/python3.4/site-packages/acme/client.py", line 622 in _send_request
  File "/usr/lib64/python3.4/site-packages/acme/client.py", line 649 in get
  File "/usr/lib64/python3.4/site-packages/acme/client.py", line 71 in __init__
  File "/usr/lib64/python3.4/site-packages/certbot/client.py", line 44 in acme_from_config_key
  File "/usr/lib64/python3.4/site-packages/certbot/client.py", line 230 in __init__
  File "/usr/lib64/python3.4/site-packages/certbot/main.py", line 390 in _init_le_client
  File "/usr/lib64/python3.4/site-packages/certbot/main.py", line 639 in renew_cert
  File "/usr/lib64/python3.4/site-packages/certbot/renewal.py", line 419 in handle_renewal_request
  File "/usr/lib64/python3.4/site-packages/certbot/main.py", line 693 in renew
  File "/usr/lib64/python3.4/site-packages/certbot/main.py", line 743 in main
  File "<string>", line 11 in <module>
  File "/usr/bin/certbot", line 86 in <module>
Erreur de segmentation

**Comment by bmw** [comment] 2017-08-23 21:49
Thanks for the traceback.

Unfortunately, I'm unable to reproduce the problem when testing on an up to date Gentoo system using Python 3.4. Ideally, we should try to get a simple code snippet that can reliably reproduce this problem so we can report it to `requests`/`urllib3`.

**Comment by Neliger** [comment] 2017-08-23 21:52
I don't see this problem with all uptodate Gentoo, but only on the newest installs from this year, but I can't find what's the key difference.

**Comment by Neliger** [comment] 2017-08-29 11:01
I wish I could help find out the issue origin...

**Comment by daugustin** [comment] 2017-08-30 21:17
I'm seeing the same issue on a 1 week old Gentoo Installation. :(

**Comment by Neliger** [comment] 2017-08-31 09:03
Yep, here it only occur on fresh install, not the old ones (2016 and older), but I can't figure out what difference can make this bug alive.

**Comment by bmw** [comment] 2017-08-31 17:32
I've been doing my testing using the [gentoo/stage3-amd64](https://hub.docker.com/r/gentoo/stage3-amd64/) Docker image. If someone's able to provide instructions on how to reproduce using that (or another method), I can dig into it more.

We just need to be able to pinpoint the problem so we can fix our call causing the segfault and/or file an issue with our dependencies. The code I provided [here](https://github.com/certbot/certbot/issues/5033#issuecomment-324172615) should identical to the code being run when the segfault occurs except there's an added `print` statement and we're not setting the User-Agent string.

Perhaps setting the User-Agent string to any value will reproduce the problem? Alternatively, someone who can reproduce the problem can step through the code with a debugger and hopefully come up with a small code snippet that causes the problem that we can debug and fix.

**Comment by matt01** [comment] 2017-09-01 16:37
'Work around' that allowed me to easily renew certs was to just use python 2.7 ...

~ # certbot renew ...
Segmentation fault (core dumped)
~ # eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.4
  [2]   python2.7 (fallback)
~ # python -V 
Python 3.4.6
~ # eselect python set 2
~ # python -V
Python 2.7.13
~ # certbot renew ...
~ #

**Comment by Neliger** [comment] 2017-09-03 10:08
I confirm the workaround : It works using python 2.7

**Comment by Graf-Euler** [comment] 2017-09-06 12:55
The workaround worked for me too on an 'up-to-date' gentoo (did a world upgrade this morning, after I discovered the segfault). Using python 2.7.12 instead of 3.4.5 allowed me to renew my cert.

**Comment by staticglobal** [comment] 2017-09-08 15:56
I was also experiencing this issue while attempting to renew certs on some of our Gentoo systems, and I stumbled on a fix by accident. 
I got a core file and was attempting to use gdb to dig into the crash, but was missing debug symbols from dev-python/cryptography.  So I re-emerged cryptography to obtain debug symbols... and now certbot works fine.
Guessing: maybe cryptography hadn't been rebuilt since the switch to gcc-5, but python/openssl were, causing some sort of runtime mismatch?
At any rate, `emerge dev-python/cryptography` worked for me

**Comment by hollaho** [comment] 2017-10-22 13:55
Now after a few version updates for certbot and also for python/cryptography the issue has vanished also for me. So far so good.

**Comment by SwartzCr** [comment] 2017-10-31 18:30
awesome - it looks like it's working for people, so I'm going to close this issue

**Closed by SwartzCr** 2017-10-31 18:30 UTC
Labels: area: gentoo, bug, help wanted

**Comment by hydrapolic** [comment] 2019-09-28 08:54
Just for future reference: this is probably due to OpenSSL version being changed. It happened to me after upgrading to OpenSSL 1.1, this made it work again:

````
emerge -av1 dev-python/asn1crypto dev-python/cryptography
````
