### ISSUE TITLE
Ubuntu 20.04 has no package "python-virtualenv"

### ISSUE THREAD

**Issue by Virsacer** [certbot/certbot#8062] opened 2020-06-09 08:26 UTC
## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
$  certbot-auto --install-only
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://de.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate

## Certbot's behavior differed from what I expected because:
This should install package "python3-venv"

**Comment by bmw** [comment] 2020-06-09 20:25
Closing as a duplicate of https://github.com/certbot/certbot/issues/7941. I suggested a couple different alternatives to installing Certbot on the platform in that thread though.

**Closed by bmw** 2020-06-09 20:25 UTC
