### ISSUE TITLE
snap install certbot-dns-route53 produces error on factory fresh install debian 9

### ISSUE THREAD

**Issue by danielburrell** [certbot/certbot#8924] opened 2021-06-26 17:54 UTC
## My operating system is (include version):
Debian stretch (9)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

snap

## I ran this command and it produced this output:

```
root@kato:~# snap install core
core 16-2.51 from 'canonical' installed
root@kato:~# snap refresh core
snap "core" has no updates available
root@kato:~# snap install --classic certbot
Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.

certbot 1.16.0 from Certbot Project (certbot-eff✓) installed
root@kato:~# ln -s /snap/bin/certbot /usr/bin/certbot
root@kato:~# snap set certbot trust-plugin-with-root=ok
root@kato:~# snap install certbot-dns-route53
error: cannot perform the following tasks:
- Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin": 
-----
error: access denied
Only connect this interface if you trust the plugin author to have root on the system.
Run `snap set certbot trust-plugin-with-root=ok` to acknowledge this and then run this command again to perform the connection.
If that doesn't work, you may need to remove all certbot-dns-* plugins from the system, then try installing the certbot snap again.
-----)
```

## Certbot's behavior differed from what I expected because:

```
snap install certbot-dns-route53
```
produced an error 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

NA
```
 ls /var/log/letsencrypt
ls: cannot access '/var/log/letsencrypt': No such file or directory
```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
NA, no configuration

**Comment by alexzorin** [comment] 2021-06-26 21:02
Duplicate of #8922.

**Closed by alexzorin** 2021-06-26 21:02 UTC
