### ISSUE TITLE
CentOS: Certbot depends on Python 2.6, which is obsolete

### ISSUE THREAD

**Issue by starrychloe** [certbot/certbot#3984] opened 2017-01-08 01:24 UTC
Apparently it should use Python 2.7 instead.
http://superuser.com/a/1164657/130929

```
# /root/certbot-auto renew --quiet
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning

```

CentOS release 6.8 (Final)

**Comment by starrychloe** [comment] 2017-01-12 00:21
It still happens.


```
Upgrading certbot-auto 0.9.3 to 0.10.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
```

**Comment by starrychloe** [comment] 2017-01-15 01:29
It's still happening with the latest version.

```
Upgrading certbot-auto 0.10.0 to 0.10.1...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
```

**Comment by skorasaurus** [comment] 2017-01-20 21:31
Hi, 

I'm having the same problem as well on my host (a VPS, bluehost, centOS 6.8 that has python 2.6 installed) however I've found that the deprecation warning has already been reported at https://github.com/certbot/certbot/issues/3726 

however related to your question (that you asked at superuser), about using python 2.7 instead if it's installed, that, I believe is still tricky and being tracked at https://github.com/certbot/certbot/issues/2921

**Comment by bmw** [comment] 2017-01-23 17:39
We've been working with `cryptography` and they're not planning on dropping support for Python 2.6 until we no longer need it. We'd love it if we could reasonably get Python 2.7 installed on CentOS and RHEL 6, but as pointed out above, we've found it to be a bit tricky.

Closing as a duplicate of #3726.

**Closed by bmw** 2017-01-23 17:39 UTC

**Comment by mdyoung3** [comment] 2017-09-02 16:50
After upgrading to Pyhon 2.7, I still get the error.
