### ISSUE TITLE
Docker image for certbot/dns-digitalocean:v1.9.0 (current latest) raising ModuleNotFoundError: No module named 'certbot_dns_cloudxns'

### ISSUE THREAD

**Issue by tiangolo** [certbot/certbot#8355] opened 2020-10-07 18:46 UTC
## My operating system is (include version):

Remote Ubuntu 18.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Docker, using the image `certbot/dns-digitalocean:latest` or `certbot/dns-digitalocean:v1.9.0` :x: 

It seems `certbot/dns-digitalocean:v1.8.0` is fine. :heavy_check_mark: 

## I ran this command and it produced this output:

```console
$ sudo docker run -v /tmp/certbottmp:/tmp -it certbot/dns-digitalocean

An unexpected error occurred:
ModuleNotFoundError: No module named 'certbot_dns_cloudxns'
Please see the logfile '/tmp/tmp9z4sh_ay/log' for more details.
```

There's no need to pass any other parameters to replicate the issue.

It will try to import `certbot_dns_cloudxns` at some point while starting. I see is a different plugin than `certbot_dns_digitalocean`, but it seems it's been expected by `certbot/dns-digitalocean:v1.9.0`, but it's not installed in the system.

## Certbot's behavior differed from what I expected because:

It errors out immediately, after trying to import that module (which is for another plugin).

I expected it to run, and say something like:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2020-10-07 18:41:58,063:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1332, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 236, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 251, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/opt/certbot/src/certbot/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'certbot_dns_cloudxns'
2020-10-07 18:41:58,063:ERROR:certbot._internal.log:An unexpected error occurred:
2020-10-07 18:41:58,064:ERROR:certbot._internal.log:ModuleNotFoundError: No module named 'certbot_dns_cloudxns'
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

N/A, it crashes before anything else.

**Comment by bmw** [comment] 2020-10-07 22:40
Thanks for reporting this.

Our only DNS plugin Docker image that seems to be failing on simple commands like this is the image for the DigitalOcean plugin. For now, I changed the `latest` tags for this image back to the image from our 1.8.0 release and we'll look into finding and fixing the root cause here.

**Comment by tiangolo** [comment] 2020-10-08 07:04
Thanks for checking it and reporting back here!

**Comment by bmw** [comment] 2020-10-21 23:45
As a comment for ourselves, when fixing this I think it'd be nice to tackle https://github.com/certbot/certbot/issues/8202 for the AMD images. We could run each image with arguments like `plugins --prepare` and make sure it doesn't blow up.

I'm probably going to take a crack at this overall issue myself soon if no one else gets to it, but @adferrand, I think you may find this issue interesting if you're looking for something to work on.

**Comment by adferrand** [comment] 2020-10-22 15:46
I created #8396 to have a set of tests running on the Docker images. Once merged it will help to understand what happened here.

**Comment by bmw** [comment] 2020-10-22 18:18
To share more info about this issue here, Alex did some digging into this when it was first reported and shared what he found in [this thread in our public Mattermost instance](https://opensource.eff.org/eff-open-source/pl/9e7xn7y16i89fmbzshkha516zc).

**Comment by bmw** [comment] 2020-10-22 18:32
I also see that the tests you added in https://github.com/certbot/certbot/pull/8396 passed which I wasn't expecting after Alex was able to reliably reproduce the problem before.

If we can no longer reproduce the problem and we have tests to ensure it doesn't slip through again, while I am interested in what happened, I personally don't think we have to dig into it further.

**Comment by alexzorin** [comment] 2020-10-22 21:05
>If we can no longer reproduce the problem and we have tests to ensure it doesn't slip through again

When I run Adrien's branch locally, it's still busted (the cloudxns thing, and also a `dns-lexicon` versioning issue).

But I agree even if something is not working right in Docker layer caching (due to the local state of the build machine), this branch should at least save us from publishing a broken image.

**Comment by adferrand** [comment] 2020-10-22 21:46
I added `--no-cache` to the docker build command, and the digitalocean docker is still broken ..

**Comment by adferrand** [comment] 2020-10-22 21:51
Also, both digitalocean and cloudxns `.egg-info` directories are present under `/opt/certbot/src/plugin`.

**Comment by alexzorin** [comment] 2020-10-22 22:57
@adferrand I don't know if you noticed in Mattermost, but it's curious and might be a clue: reverting 55d411f1ebd9a8db5157ecac1c5ce8e1d542088c on top of your branch "fixes" the DigialOcean Docker build (found by bisect).

**Comment by adferrand** [comment] 2020-10-26 20:35
My hypothesis is that something behaves really badly in how buildkit handle its cache for layer building. In particular buildkit claims to have a really efficient cache and pull incremental changes.

Asking @bmw about why we needed buildkit in the first place, he redirected me to the inline comments in the build script, which explain that without buildkit, the build is failing with an error output like this: https://gist.github.com/2227a05622299ce17bff9b0da714a1ff

I find really interesting that the build without buildkit is failing about a layer not found at the same exact step than when buildkit is wrongly adding files from a previous build, both indicating some weird errors around layer caching.

**Comment by adferrand** [comment] 2020-10-26 20:37
I built locally the images without buildkit. Now the digital ocean image has the correct `setup.py` file, while it was not (consistently) with buildkit.

So far, there is really something wrong with buildkit. My docker version (client + server) is 18.09.5.

**Comment by adferrand** [comment] 2020-10-26 21:03
Azure Pipeline docker version (client + server) is 19.03.13+azure.

**Closed** 2020-10-26 22:20 UTC
Labels: area: docker, area: pkging, bug, priority: critical
