### ISSUE TITLE
__requires__: not found

### ISSUE THREAD

**Issue by okmkey45** [certbot/certbot#5226] opened 2017-11-06 20:41 UTC
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
command:
sudo sh /usr/bin/certbot renew --quiet --renew-hook "/bin/systemctl reload nginx"

output: 
/usr/bin/certbot: 3: /usr/bin/certbot: __requires__: not found
/usr/bin/certbot: 4: /usr/bin/certbot: import: not found
/usr/bin/certbot: 5: /usr/bin/certbot: import: not found
from: can't read /var/mail/pkg_resources
/usr/bin/certbot: 9: /usr/bin/certbot: Syntax error: "(" unexpected (expecting "then")

## Certbot's behavior differed from what I expected because:
I have been using Certbot for several months and so far it was working fine. I renewed three times before this error started to happen. I just expect to renew normally

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-11-05 03:15:02,314:DEBUG:certbot.main:certbot version: 0.14.2
2017-11-05 03:15:02,314:DEBUG:certbot.main:Arguments: ['--quiet', '--renew-hook', '/bin/systemctl reload nginx']
2017-11-05 03:15:02,314:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-11-05 03:15:02,324:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7fb491966350> and installer <certbot.cli._Default object at 0x7fb491966350>
2017-11-05 03:15:02,324:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7fb491962790>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7fb491962550>, apache=<certbot.cli._Default object at 0x7fb491966$
2017-11-05 03:15:02,338:DEBUG:certbot.log:Root logging level set at 30
2017-11-05 03:15:02,339:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-11-05 03:15:02,364:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2017-11-13 00:38:00 UTC.
2017-11-05 03:15:02,364:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2017-11-05 03:15:02,364:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2017-11-05 03:15:02,365:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#nginx): 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 120, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 151, in prepare
    raise errors.NoInstallationError
NoInstallationError
2017-11-05 03:15:02,368:DEBUG:certbot.plugins.selection:No candidate plugin
2017-11-05 03:15:02,369:DEBUG:certbot.plugins.selection:No candidate plugin
2017-11-05 03:15:02,369:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2017-11-05 03:15:02,369:INFO:certbot.main:Could not choose appropriate plugin: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()
2017-11-05 03:15:02,369:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/databig.co.conf produced an unexpected error: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError(). Skipping.
2017-11-05 03:15:02,372:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 418, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 634, in renew_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 196, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 271, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()

2017-11-05 03:15:02,375:INFO:certbot.renewal:Cert not yet due for renewal
2017-11-05 03:15:02,376:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.14.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 692, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 435, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

Thanks for any help

**Comment by SwartzCr** [comment] 2017-11-08 00:46
Can you let me know:
- What version of certbot you have? `certbot --version`
- What version of nginx you have? `dpkg -l nginx`
- What python packages you have installed via pip? `pip freeze`

**Comment by okmkey45** [comment] 2017-11-08 03:34
Certbot version:
certbot 0.19.0

Nginx Version:
1.10.3-0ubuntu0.16.

python packages:
I don´t have installed pip

**Comment by bmw** [comment] 2017-11-09 01:10
@okmkey45, I think the problem is the command you're running. `sudo sh /usr/bin/certbot` causes `/bin/sh` to try to interpret Certbot as a shell script when it's actually a Python program. Removing `sh` from this command should solve your problem.

**Comment by okmkey45** [comment] 2018-04-11 19:45
Hello

I haven´t been able to solve this problem. Anyone knows something? @bmw even if I run the command without sh I get the same error

**Comment by bmw** [comment] 2018-04-11 20:32
What is the exact command you are running and what are the contents of `/usr/bin/certbot`.

**Comment by okmkey45** [comment] 2018-04-11 21:46
inside my crontab I have this

```
15 3 * * * /usr/bin/certbot renew --quiet --post-hook "service nginx start"
```

and I was trying to execute from the console

```
sudo sh /usr/bin/certbot renew --quiet --post-hook "service nginx start"
```

When I execute with sh I get the error, but when I execute without sh, it doesn´t do anything

**Comment by bmw** [comment] 2018-04-11 22:09
> When I execute with sh I get the error, but when I execute without sh, it doesn´t do anything

Correct. `certbot renew` checks if you need to renew your certificates and if not, exits without doing anything else. Since you've included `--quiet` on the command line, it will only show error output which there probably isn't any. Try running:
```
sudo /usr/bin/certbot renew --post-hook "service nginx start"
````
This is the same command with `sh` and `--quiet` removed. You probably still want to include `--quiet` in your crontab though.

**Comment by okmkey45** [comment] 2018-04-13 17:14
ok, something really weird happened.

I did what you told me and this was the output:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/my_domain.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/my_domain.tk/fullchain.pem (skipped)
No renewals were attempted.
No hooks were run.

```

Maybe the restart of the server is not working through the crontab? I really didn´t know what happen

**Comment by bmw** [comment] 2018-04-13 18:53
That's expected behavior. `certbot renew` ran, determined your certificates don't need to be renewed yet , and exited. You weren't seeing this output before because you were running with `--quiet`.

If you'd like to simulate renewal to test it, add `--dry-run` to the command line.

**Comment by bmw** [comment] 2019-04-25 18:50
This issue hasn't seen any updates in over a year and I believe it has been resolved so I'm closing it. If you continue to have problems, I recommend posting at https://community.letsencrypt.org where there is a large community of people familiar with the project who would be happy to help you.

**Closed by bmw** 2019-04-25 18:50 UTC
Labels: area: debian / ubuntu, area: pkging, debugging
