### ISSUE TITLE
need help,Luadns

### ISSUE THREAD

**Issue by drx1x2** [certbot/certbot#8856] opened 2021-05-24 01:08 UTC
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

[5/24/2021] [9:03:31 AM] [Nginx ] › information_source info Reloading Nginx
[5/24/2021] [9:03:31 AM] [Express ] › warning warning Command failed: /opt/certbot/bin/certbot certonly --non-interactive --cert-name "npm-10" --agree-tos --email "mymail@gmail.com" --domains "domain" --authenticator dns-luadns --dns-luadns-credentials "/etc/letsencrypt/credentials/credentials-10" --dns-luadns-propagation-seconds 120

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-luadns, Installer None
Performing the following challenges:
dns-01 challenge for domain.com
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:

**Comment by alexzorin** [comment] 2021-05-24 01:19
Hey @drx1x2,

This was a breakage that was fixed in https://github.com/certbot/certbot/pull/8819 and will be part of the upcoming release of Certbot 1.16.0, in about a week.

In the meantime, you can downgrade the `dns-lexicon` package, which is described as a workaround in that above issue:

    /opt/certbot/bin/pip install dns-lexicon==3.5

I'm going to close this as a duplicate of the other issue, but please post back if that workaround doesn't work for you.

**Closed by alexzorin** 2021-05-24 01:19 UTC
