### ISSUE TITLE
acme library crashes processing Unicode strings in ACME error detail

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#4533] opened 2017-04-20 17:35 UTC
Based on https://community.letsencrypt.org/t/unicodeencodeerror-running-the-certbot/32422, I investigated a bit and concluded that the `acme` library is unsafe when the CA returns an error detail string containing non-ASCII characters; it crashes with a `UnicodeEncodeError` at

https://github.com/certbot/certbot/blob/master/acme/acme/messages.py#L39

(Imagine that `err` is `u"Errör message"`; calling `str()` on that is an error.)

In this case, a user had a 404 page containing Russian text and Certbot appeared to crash at the line above when trying to report a failed `webroot` authentication. I'm not certain that this is the only thing preventing Certbot from handling such an error properly, but if I've understood the problem properly, it's at least one obstacle.

**Comment by bmw** [comment] 2017-04-20 17:50
Duplicate of #4273.

**Closed by bmw** 2017-04-20 17:50 UTC
Labels: area: acme, area: error handling, bug
