### ISSUE TITLE
`certbot-auto --version` prints unprintable ASCII character

### ISSUE THREAD

**Issue by morxa** [certbot/certbot#6996] opened 2019-04-27 09:18 UTC
Running `certbot-auto --version` prints an unprintable ASCII character ` [?1034h`.

This leads to problems when piping that output into `mail`, because mailx interprets the input as binary data and thus sends emails that have no text body but only an attachment. You can test this with:
```
$ certbot-auto --version | mail -s "certbot-test" you@example.com
```

## My operating system is (include version):
CentOS 6.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ certbot-auto --version | xxd
0000000: 6365 7274 626f 7420 302e 3333 2e31 201b  certbot 0.33.1 .
0000010: 5b3f 3130 3334 680a                      [?1034h.
```

## Certbot's behavior differed from what I expected because:
The second line should not be there, that's a non-printable character (escape sequence?). [This blog post](https://incenp.org/notes/2012/python-term-smm-fix.html) seems to provide some context and may hint to a fix.

**Comment by morxa** [comment] 2019-04-27 09:30
This issue does not occur on CentOS 7 with certbot installed from the epel repository:
```
$ certbot --version | xxd
certbot 0.29.1
```
After updating certbot:
```
$ certbot --version | xxd
certbot 0.31.0
```

**Comment by schoen** [comment] 2019-04-30 00:56
@bmw, do you know how this could happen? Could it be a vestige of our prior use of ncurses somehow?

**Comment by schoen** [comment] 2019-04-30 01:04
Or perhaps a behavior of some command-line program that we call in `certbot-auto` but not in `certbot` itself?

**Comment by bmw** [comment] 2019-04-30 17:09
Googling around, this seems to be a problem in older versions of the Python standard library. See https://bugs.python.org/issue19884.

I was able to reproduce this on CentOS 6 after installing Python 3.4 from EPEL and the `vim-common` package by running:
```
# TERM=xterm python3 -c 'import readline' | xxd
0000000: 1b5b 3f31 3033 3468                      .[?1034h
```

Unsetting `TERM` solves the problem. I could not reproduce this problem on CentOS 7 regardless of how Python (or Certbot) was installed.

**Comment by schoen** [comment] 2019-04-30 17:22
So, I imagine this might be difficult for us to work around in Certbot itself.

**Comment by bmw** [comment] 2019-04-30 18:03
I think that's right so I'm going to close this but please let me know if you think we should reconsider!

The only workaround I found was unsetting `TERM` (or maybe changing its value). Unfortunately, it appears the same problem is present in all of the versions of Python from SCL as well.

**Closed by bmw** 2019-04-30 18:03 UTC
Labels: area: ui / ux
