### ISSUE TITLE
Implement a --non-root flag?

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3267] opened 2016-07-08 23:56 UTC
We could have a flag that sets `--config-dir`, `--logs-dir,` and `--work-dir` to some sensible current directory value, rather than forcing people to set all three.

**Comment by pde** [comment] 2016-07-08 23:56
If implementing, also update the message from #3265 to suggest this new flag.

**Comment by bmw** [comment] 2016-07-08 23:57
Dupe of #3079.

**Closed by bmw** 2016-07-08 23:57 UTC
Labels: Good Volunteer Task, ui / ux
