### ISSUE TITLE
Windows: Scheduled Renewal Task Should Not Require User To Be Logged in.

### ISSUE THREAD

**Issue by thenewguy** [certbot/certbot#8420] opened 2020-10-30 17:18 UTC
I wrote a message at https://community.letsencrypt.org/t/certbot-windows-renewal-task-not-running/137210 but this really seems like a more appropriate location.

I noticed I was getting emails from LetsEncrypt about expiring certificates.  Turns out the renewal task is configured so that it only runs if a user is logged in.  It would be better if it ran without requiring a user to be logged in.

For example, I have a dedicated virtual machine for running certbot to manage certificates.  It never has a user logged in.  It uses network shares for the certificates and the tokens.  The web server runs on another machine and serves the tokens to Lets Encrypt from the network share.  Certbot should ideally operate without user interaction.  The default task caused certificates to expire in this scenario.

![1b35ff3b6226d9533c5c58e76749c8cc7cc441bf](https://user-images.githubusercontent.com/77731/97736359-f365ca00-1ab1-11eb-8007-8b0d001ee55d.png)

**Comment by mikenor** [comment] 2021-02-08 20:08
I don't think that's the actual cause of the task not running, because if you edit the task, you will see that the choice of `Run only when user is logged on` or `Run whether user is logged on or not` is greyed out. I.e., that setting is not relevant (since there is no valid user selected).

I've been chasing down a recurring problem with the task working initially for a long time, but eventually it just suddenly stops being executed. Like Task Scheduler doesn't even attempt to run it all of the sudden. Re-installing Certbot to re-create the task fixes it for a while. Let me track down Certbot and OS versions involved, it's been at least a couple machines I've been seeing this on......

Not so sure about the task having `Administrators` as the assigned "user account". Seems unusual to me. `Administrators` is a group, not a user account.

**Comment by adferrand** [comment] 2021-02-08 21:21
Technically everything (including groups and users) are just accounts for Windows, and any account can be associated to a task. Also this precise UI is read-only so the Security options are always greyed out, but in the edition UI, where this could be modified, is still greyed out since "Administrators" is not an account that you can use to log in.

However we need to verify if the task actually runs when nobody is logged in. It is entirely possible that another problem is hidden here, so do not hesitate to troubleshoot @mikenor in your environment.

**Comment by mikenor** [comment] 2021-02-08 21:37
I was very certain the task was working with nobody logged in, but now that I look at the timestamps of the log files, I am not so sure. It appears it mostly ran at times when possibly there could have been someone.

I currently have a machine with task that stopped running a few weeks ago, I'm going to try staying logged in as part of my troubleshooting.

**Comment by mikenor** [comment] 2021-03-03 21:58
I guess the Task Scheduler UI fooled me... after closer inspection, it was indeed only running when a user was logged in. Seems that was my actual issue with unreliable task all along.

As a workaround, I changed the task to run as `SYSTEM` instead of `Administrators` - seems to be working.

**Comment by adferrand** [comment] 2021-03-03 22:11
In my initial design the task was running under SYSTEM indeed. LOCALSERVICE would be a good candidate also.

At some point we moved to Administrators. I will look at the history to see why, but I think it is related to how rights are set for sensitive files in this case and may need some workaround in this case.

**Comment by mikenor** [comment] 2021-06-30 22:27
@adferrand I think you are correct. I've just discovered that running the renewal task as `SYSTEM` causes logfiles to be saved with permissions such that no human administrators can access them. Then it becomes impossible for human administrators to use the `certbot` command at all, due to error about logfile permissions:

> `←[31mThe following error was encountered:`
> `[Errno 13] Permission denied: 'C:\\Certbot\\log\\letsencrypt.log'`
> `Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.←[0m`

The workaround I used was to re-install the latest version, delete all the logfiles, run my desired `certbot` commands, and then change the scheduled task back to `SYSTEM` and hope that this is fixed by the next time I need to manually run `certbot` commands again. ;-)

**Comment by thenewguy** [comment] 2022-08-30 13:06
Perhaps a simple workaround would be allowing the task to run as a GMSA?

**Comment by thenewguy** [comment] 2022-11-28 15:54
Has anyone used any workarounds they like? I am still having trouble with this. The certbot machine wasn't logged in and certificates expired again. Any suggestions (that keep domain access for shuffling certificates to a network share) would be appreciated

**Comment by thatwill** [comment] 2023-12-14 13:31
I can confirm this still occurs on the current stable version (2.8.0).

The scheduled task is created as the "Administrators" user group which means the service will not run if the user is not actively logged in.  
If you manually change the task's user to SYSTEM, it appears to run. However, it causes SYSTEM to take sole ownership of the certbot log files which means that you cannot review the log files or use certbot, until you manually change back the file ownership/permissions.

**Comment by zoracon** [comment] 2024-11-20 02:43
Closing due to our decision to discontinue our Beta distribution of the Windows Installer:
https://github.com/certbot/certbot/wiki/Architectural-Decision-Records#-certbot-discontinuing-windows-support

If you are looking at alternatives. They are in this community forum:
https://community.letsencrypt.org/t/certbot-discontinuing-windows-beta-support-in-2024/208101

**Closed by zoracon** 2024-11-20 02:43 UTC
Labels: bug, area: renewal, area: windows, priority: significant
