### ISSUE TITLE
Missing directory should ideally fail earlier

### ISSUE THREAD

**Issue by dehnert** [certbot/certbot#3552] opened 2016-09-28 07:05 UTC
I discovered that my cert wasn't getting renewed on schedule, and certbot has the following in the log file:

```
2016-09-27 16:11:22,569:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/[domain].conf produced an unexpected error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for exact set of domains: [domains]. Skipping.
2016-09-27 16:11:22,585:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 346, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 91, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 237, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 258, in obtain_certificate
    return (self.obtain_certificate_from_csr(domains, csr, authzr=authzr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 228, in obtain_certificate_from_csr
    authzr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 319, in request_issuance
    headers={'Accept': content_type})
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 656, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 572, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: Too many certificates already issued for exact set of domains: [domains]
2016-09-27 16:11:22,605:INFO:certbot.renewal:Cert not yet due for renewal
2016-09-27 16:11:22,607:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 584, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 363, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

(END)
```

The directory doesn't exist because I originally used the wrong name (see also #3551) -- I updated the paths that I noticed were wrong, but missed this one. certbot seems to have requested the cert first, and only then tried to write it to disk. That falied, and certbot quit. Unfortunately, because I'm running it twice a day ([as recommended](https://certbot.eff.org/all-instructions/)), I've hit the renewal frequency rate limit, so now I can't easily renew it, even though I've moved the missing directory.

It would be nice if certbot checked for the existence of the directories it needs before contacting the CA, and errored out sooner, so that rate-limiting wouldn't be impacted.

**Comment by bmw** [comment] 2016-09-28 21:17
I'm sorry you encountered this problem. Thanks for taking the time to report it.

What was the directory that was missing? There are multiple directories in `/etc/letsencrypt` named after the first requested domain name. It's highly likely this was already fixed in `master` by #3533 but I'd like to test and make sure.

**Comment by dehnert** [comment] 2016-09-29 16:24
The relevant path was `/etc/letsencrypt/archive/[domain]/privkey2.pem`.

```
2016-09-27 08:55:13,775:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/[domain].conf produced an unexpected error: [Errno 2] No such file or directory: '/etc/letsencry    pt/archive/[domain]/privkey2.pem'. Skipping.
2016-09-27 08:55:13,780:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 346, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 91, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 248, in renew_cert
    lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, renewal_conf)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/storage.py", line 863, in save_successor
    with open(target["privkey"], "w") as f:
IOError: [Errno 2] No such file or directory: '/etc/letsencrypt/archive/[domain]/privkey2.pem'
```

**Comment by bmw** [comment] 2016-09-29 20:15
Thanks for the full traceback. You make my job easy.

I'm glad I checked. This was not fixed by #3533. I thought it would have been because we now check both `/etc/letsencrypt/archive/<domain>` and `/etc/letsencrypt/live/<domain>` before requesting a cert, however, this logic isn't triggered during renewal. It should be.

**Comment by bmw** [comment] 2016-09-29 23:27
To add more context for whoever works on this, I thought this would be fixed with a call to `has_pending_deployment` before requesting the cert from the CA, however, that function doesn't seem to make assumptions about the name of the directory. `save_successor` does this causing the problem. We should be consistent here.

**Comment by bmw** [comment] 2017-03-19 02:22
I think this has been fixed. A couple of us tried for a while to reproduce this but had no luck. If you're still having the problem, please follow up with exact instructions on how to reproduce and I'll reopen.

**Closed by bmw** 2017-03-19 02:22 UTC
Labels: area: renewal, area: ui / ux, easy-fix, Good Volunteer Task, sf-python-sprint
