### ISSUE TITLE
--chain-path does not yield proper chain at given path, generates 0000_chain.pem in cwd instead

### ISSUE THREAD

**Issue by Majkl578** [certbot/certbot#4331] opened 2017-03-12 02:19 UTC
#### My operating system is (include version):
Debian 8

#### I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.12.0
Cloned from GitHub, now using certbot-auto.

#### I ran this command and it produced this output:
```
certbot-auto certonly --webroot -w <path> --expand --force-renewal --csr "$1" --cert-path "$2" --chain-path "$3"
```
Using CSR in $1 to generate the certificate.
This correctly generates the certificate iself and places it at path $2.
It fails to create proper chain certificate at path $3, it only contains the certificate itself without intermediate. Chain certificate is instead created in current working directory in 0000_chain.pem file.

#### Certbot's behavior differed from what I expected because:
Given that --chain-path was suppled, 0000_chain.pem file should not be created and proper chain certificate should be created at $3.

**Comment by SwartzCr** [comment] 2017-03-17 17:44
@Majkl578 
Weird, do you think you'd be able to provide a log of this? I'll ask around and see if anyone can reproduce this

**Comment by Majkl578** [comment] 2017-03-17 19:15
Checking again and it looks like there is 3rd option, `--fullchain-path` which I completely missed, because it's listed in entirely different section in the `--help all` output. Why the hell is that under `install` and not under `paths` section? 😕 
So the solution is to **also** use `--fullchain-path` together with `--chain-path` and `--cert-path`.

Not a bug, but I'm leaving this open as a documentation problem for now. ☺️

**Comment by SwartzCr** [comment] 2017-03-21 23:34
@Majkl578 do you think you could either paste below the various outputs that you got in the help and documentation that list these things separately or open a new ticket specifically for the documentation problem so that we can accurately address it?

**Comment by jethrogb** [comment] 2017-03-23 18:39
Ran into same issue.

```
$ certbot --version
certbot 0.12.0
$ certbot --help all
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

*snip 183 lines*

paths:
  Arguments changing execution paths & servers

  --cert-path CERT_PATH
                        Path to where cert is saved (with auth --csr),
                        installed from, or revoked. (default: None)
  --key-path KEY_PATH   Path to private key for cert installation or
                        revocation (if account key is missing) (default: None)
  --chain-path CHAIN_PATH
                        Accompanying path to a certificate chain. (default:
                        None)
  --config-dir CONFIG_DIR
                        Configuration directory. (default: /etc/letsencrypt)
  --work-dir WORK_DIR   Working directory. (default: /var/lib/letsencrypt)
  --logs-dir LOGS_DIR   Logs directory. (default: /var/log/letsencrypt)
  --server SERVER       ACME Directory Resource URI. (default:
                        https://acme-v01.api.letsencrypt.org/directory)

*snip 108 lines*

install:
  Options for modifying how a cert is deployed

  --fullchain-path FULLCHAIN_PATH
                        Accompanying path to a full certificate chain (cert
                        plus chain). (default: None)

*snip 104 lines*
```

**Comment by SwartzCr** [comment] 2017-03-24 16:11
@ohemorange or @schoen do you want to take on moving this from install to paths?

**Comment by ohemorange** [comment] 2017-03-27 19:20
Hm, that's weird:

```
add(["install", "paths"], "--fullchain-path", default=default_cp, type=os.path.abspath,
        help="Accompanying path to a full certificate chain (cert plus chain).")
```

Looks like this is either a bug or a feature of the `--help all` output, where it chooses which of the relevant sections it should be under by some subtle and unintuitive mechanism.

We may want to decide if that's a feature or a bug. Either way, switching the order of `"install"` and `"paths"` prioritizes `"paths"` to fix this particular instance.

**Comment by SwartzCr** [comment] 2017-03-28 21:09
should be solved now - feel free to reopen if you don't thinks so!

**Closed by SwartzCr** 2017-03-28 21:09 UTC
Labels: area: csr, area: documentation, area: webroot, more-info
