### ISSUE TITLE
Problem with create ssl on amazon-linux

### ISSUE THREAD

**Issue by moroadmin** [certbot/certbot#5180] opened 2017-10-09 12:17 UTC
## My operating system is (include version):
Amazon Linux AMI 2016.09

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.19.0
manual install:
git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt

## I ran this command and it produced this output:
./letsencrypt-auto certonly --webroot -w /var/www/xzv.com -d xzv.com

## Certbot's behavior differed from what I expected because:
After  automatic upgrade  certbot 0.17.0 to certbot 0.19.0. I don't create new ssl certifikcate.

## Here is a Certbot log showing the issue (if available):
2017-10-09 11:56:36,239:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 786, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 66, in get_authorizations
    self.authzr[domain] = self.acme.request_domain_challenges(domain)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 191, in request_challenges
    response = self.net.post(self.directory.new_authz, new_authz)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 682, in post
    return self._post_once(*args, **kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 691, in _post_once
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 671, in _get_nonce
    self._add_nonce(self.head(url))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 649, in head
    return self._send_request('HEAD', *args, **kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/acme/client.py", line 627, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 246, in recv
    [self.socket], [], [], self.socket.gettimeout())
error: (4, 'Interrupted system call')
2017-10-09 11:56:36,241:ERROR:certbot.log:An unexpected error occurred:

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
For NGINX 1.12.1

**Comment by joohoi** [comment] 2017-10-10 13:56
Looks like this is a duplicate of #4871 and the work is tracked there, closing this issue to not to split the discussion between multiple issues.

**Closed by joohoi** 2017-10-10 13:56 UTC
