### ISSUE TITLE
Have install not require `--cert-path`, `--fullchain-path` or `--key-path` parameters

### ISSUE THREAD

**Issue by jpluimers** [certbot/certbot#3412] opened 2016-08-16 12:15 UTC
Feature request as this won't work without `--cert-path`, `--fullchain-path` or `--key-path` parameters:

```
./certbot-auto install --noninteractive --apache --domains pcm.4delphi.com
```

But this will request and install without any extra parameters:

```
./certbot-auto --noninteractive --apache --domains pcm.4delphi.com
```

And this will request without any extra parameters:

```
./certbot-auto certonly --noninteractive --apache --domains pcm.4delphi.com
```

So please make `install` as smart as `certonly` or no command at all that somehow figure out the correct locations of the certificates.

--jeroen

**Comment by bmw** [comment] 2016-08-16 19:52
I believe this is a duplicate of #1231. If you disagree, please comment explaining the difference and I'll reopen.

**Closed by bmw** 2016-08-16 19:52 UTC

**Comment by jpluimers** [comment] 2016-08-17 00:51
That one didn't turn up in my search, probably of the very terse formulation in it.

It also misses `--fullchain-path` which is now required and is named `--install` instead of `install`.

Do you want me to add the first comments to it so it becomes more clear?

**Comment by bmw** [comment] 2016-08-17 00:55
@jpluimers, that'd be great!
