### ISSUE TITLE
Certbot failing to contact ACME server in https

### ISSUE THREAD

**Issue by Amodio** [certbot/certbot#6278] opened 2018-08-02 01:56 UTC
## My operating system is (include version):
Linux Alpine 3.7.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`docker pull certbot/certbot`

## I ran this command and it produced this output:
`certbot --config /etc/letsencrypt/configs/default.conf certonly`

## Certbot's behavior differed from what I expected because:
PaX does not allow python to request using https

## Fix from https://community.letsencrypt.org/t/letsencrypt-docker-image-not-starting-with-cryptical-python-error/55500/9?u=patches
`apk add --no-cache --virtual .pax-deps attr && setfattr -n user.pax.flags -v "emr" /usr/local/bin/python2.7 && apk del .pax-deps`

## Here is a Certbot log showing the issue (if available):
```
2018-08-02 01:53:13,744:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x64e2a4e4bf90> and installer None
2018-08-02 01:53:13,744:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2018-08-02 01:53:14,280:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2018-08-02 01:53:14,284:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2018-08-02 01:53:14,289:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/main.py", line 1238, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/opt/certbot/src/certbot/main.py", line 641, in _init_le_client
    acc, acme = _determine_account(config)
  File "/opt/certbot/src/certbot/main.py", line 520, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/opt/certbot/src/certbot/client.py", line 180, in register
    acme = acme_from_config_key(config, key)
  File "/opt/certbot/src/certbot/client.py", line 50, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/opt/certbot/src/acme/acme/client.py", line 744, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/opt/certbot/src/acme/acme/client.py", line 1078, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 1027, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 344, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 297, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/usr/local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 403, in verify_mode
    _verify_callback
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1108, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 333, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: error return without exception set
2018-08-02 01:53:14,295:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by bmw** [comment] 2018-08-02 23:34
I think this is a duplicate of #5737.

**Closed by bmw** 2018-08-02 23:34 UTC

**Comment by Amodio** [comment] 2018-08-04 18:57
I think the official docker image should contain the fix, so that would work on Alpine Linux until someone has written a wrapper to not using pyopenssl directly.

**Comment by bmw** [comment] 2018-08-06 21:35
I'm not sure we want to turn off memory protections for all of Python to fix this.
