### ISSUE TITLE
'utf8' codec can't decode byte 0xf6

### ISSUE THREAD

**Issue by Vikab-Hakan** [certbot/certbot#5211] opened 2017-10-30 10:49 UTC
## My operating system is (include version):
Ubuntu 16.04.3 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
N/A

## I ran this command and it produced this output:
sudo certbot --apache -d www.dalumsmekaniska.se

## Certbot's behavior differed from what I expected because:
It has worked up till now.

## Here is a Certbot log showing the issue (if available):
2017-10-30 10:03:21,368:DEBUG:certbot.log:Root logging level set at 20
2017-10-30 10:03:21,369:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-10-30 10:03:21,370:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-10-30 10:03:21,567:DEBUG:certbot_apache.configurator:Apache version is 2.4.18
2017-10-30 10:03:27,150:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 685, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 189, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 25, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 248, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 206, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 624, in get_virtual_hosts
    new_vhost = self._create_vhost(path)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 600, in _create_vhost
    self._add_servernames(vhost)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 551, in _add_servernames
    servername, serveraliases = self._get_vhost_names(host.path)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 539, in _get_vhost_names
    servername = self.parser.get_arg(servername_match[-1])
  File "/usr/lib/python2.7/dist-packages/certbot_apache/parser.py", line 372, in get_arg
    value = self.aug.get(match)
  File "/usr/lib/python2.7/dist-packages/augeas.py", line 147, in get
    return dec(value.value)
  File "/usr/lib/python2.7/dist-packages/augeas.py", line 65, in dec
    return st.decode(AUGENC)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 13: invalid start byte
2017-10-30 10:03:27,152:ERROR:certbot.log:An unexpected error occurred:

**Comment by bmw** [comment] 2017-10-30 19:44
@joohoi, can you take a look at this?

**Comment by joohoi** [comment] 2017-10-30 20:57
Seems like Augeas is stumbling to some charset problem in one of the configuration files.
@Vikab-Hakan could you post the output of `grep -Ri ServerName /etc/apache2` here so we could try to figure out which ServerName statement could be in question.

**Comment by Vikab-Hakan** [comment] 2017-10-31 08:40
Hi, I am not sure what the Your purpose with ServerName is... This is a shared server with hundreds of webs on it.

**Comment by joohoi** [comment] 2017-10-31 10:45
The Certbot Apache plugin scans through your Apache configuration in order to find the correct `VirtualHost` directive to enable HTTPS for. In this error case it seems that the configuration parser breaks while trying to read in one of the `ServerName` statements in one of the configuration files. What I would like to do here, would be to find out what is the exact `ServerName` statement that breaks the parser, and try to figure out if: 
1) There's something we can do to fix this problem in Certbot code for all potential users with similar problem.
2) Help you to fix/work around the problem in order to be able to use Certbot for your needs.

**Comment by Vikab-Hakan** [comment] 2017-10-31 11:10
There is 479 .conf files... It is like looking for a needle in a haystack (c: The certbot maybe could say wich file it finds hard to read.

**Comment by joohoi** [comment] 2017-10-31 11:52
That's true, we'll implement that in the future versions.

**Comment by Vikab-Hakan** [comment] 2017-11-01 14:53
Now I have read all 479 conf-files but every one is ASCII-encoded with no invalid characters. Can it be a limit in the number of files?

**Comment by lutter** [comment] 2017-11-11 00:17
Not sure if this helps, but augeas does not deal in UTF8 - it always operates on byte strings, and so wouldn't get confused by invalid UTF8 sequences. I just noticed that the python-augeas bindings do things with utf8 encoding, but I don't understand why (partly due to my unfamiliarity with how this is usually done in Python).

**Comment by simonarons** [comment] 2018-05-01 20:34
This is probably not the exact same issue, but I also got this very same error message and noticed that the ServerName in the apache virtual host file was literally
`#ServerName www.example.com`
i.e. the default, un-configured conf file with ServerName commented out.

Setting the ServerName directive did solve this issue for me.

**Comment by bmw** [comment] 2019-05-03 00:01
This issue hasn't seen any updates in a long time. Other than the previous post about a commented out `ServerName` where our Apache plugin doesn't seem to have any issues, there are no config snippets to see if this issue has been resolved. Because of this, I'm closing this issue.

If you're still hitting this, please comment or open a new issue, ideally with instructions on how to reproduce the problem.

**Closed by bmw** 2019-05-03 00:01 UTC
Labels: area: apache
