### ISSUE TITLE
DNS label too long message is inaccurate

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3699] opened 2016-10-27 16:54 UTC
Steps to reproduce:

`certbot -d .foo.com`

`Requested domain .foo.com is not a FQDN because label  is too long.`

Problems:

Initial label is actually too short (zero length).
Two spaces after `label` and before `is too`.
We should probably say, instead of FQDN, "is not a valid domain name."

Maybe just remove this check altogether? The server does this check pretty early on.

```
    # FQDN checks according to RFC 2181: domain name should be less than 255
    # octets (inclusive). And each label is 1 - 63 octets (inclusive).
    # https://tools.ietf.org/html/rfc2181#section-11
    msg = "Requested domain {0} is not a FQDN because ".format(domain)
    labels = domain.split('.')
    for l in labels:
        if not 0 < len(l) < 64:
            raise errors.ConfigurationError(msg + "label {0} is too long.".format(l))
    if len(domain) > 255:
        raise errors.ConfigurationError(msg + "it is too long.")
```

**Comment by bmw** [comment] 2016-10-27 19:26
Dupe of #3347. The cause is slightly different, however, the fix is the same.

**Closed by bmw** 2016-10-27 19:26 UTC
