### ISSUE TITLE
Python error during setup

### ISSUE THREAD

**Issue by Si1kIfY** [certbot/certbot#1718] opened 2015-12-04 07:16 UTC
Ran `./letsencrypt-auto --help` and ran into a error during setup

```
~/letsencrypt# ./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies......Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-YwiHgG/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1vX4Zv-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-YwiHgG/cryptography
```

OS Ubuntu 14.04

**Comment by roydejong** [comment] 2015-12-04 09:17
I got this error as well when I was running letsencrypt-auto on a droplet with 512mb of RAM. I was able to fix this by enabling swap.

**Comment by bmw** [comment] 2015-12-10 20:37
Is this a dupe of #1081?

**Closed** 2016-06-02 22:16 UTC
Labels: duplicate
