### ISSUE TITLE
"no valid AAAA records found" error - unnecessary or at least undocumented requirement

### ISSUE THREAD

**Issue by php4fan** [certbot/certbot#9248] opened 2022-03-26 17:56 UTC
## My operating system is (include version):
Debian 10.2

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
I don't remember

## I ran this command and it produced this output:
```
$ certbot certonly --apache -d mydomain.com -d myotherdomain.com -d yetanotherdomain.com (....)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/xxxxx.com.conf)

It contains these names: [...]

You requested these names for the new certificate: [... ...]

Do you want to expand and replace this existing certificate with the new
certificate?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(E)xpand/(C)ancel: e

Renewing an existing certificate
Performing the following challenges:
http-01 challenge for xxxx.xxx
http-01 challenge for xxxy.xxx
http-01 challenge for xxxz.xxx
http-01 challenge for xxxw.xxx
http-01 challenge for www.xxxxx.xxx
http-01 challenge for www.xxxxy.xxx
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. xxxx.xxx (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for xxxx.xxx - check that a DNS record exists for this domain; no valid AAAA records found for xxxx.xxx, www.xxxx.xxx (http-01): urn:ietf:params:acme:error:dns :: During secondary validation: DNS problem: NXDOMAIN looking up A for www.xxxx.xxx - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.xxxx.xxx - check that a DNS record exists for this domain

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: xxxx.xxx
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up A for xxxx.xxx - check
   that a DNS record exists for this domain; no valid AAAA records
   found for xxxx.xxx

   Domain: www.xxxx.xxx
   Type:   None
   Detail: During secondary validation: DNS problem: NXDOMAIN looking
   up A for www.xxxx.xxx - check that a DNS record exists for this
   domain; DNS problem: NXDOMAIN looking up AAAA for www.xxxx.xxx -
   check that a DNS record exists for this domain

```

## Certbot's behavior differed from what I expected because:

Indeed, the domain that failed has an `A` record but no `AAAA` records. I don't see why that should be an issue. 
Why shouldn't I be able to issue a certificate for a domain that only has an IPv4 address and not an IPv6 one? 

So I checked https://eff-certbot.readthedocs.io/en/stable/using.html#certbot-command-line-options because surely there must be an option to tell certbot to only use IPv4, or if there's not, it will certainly say that having both an IPv4 and IPv6 address is required and perhaps even explain why.

But no. The section about the Standalone authenticator does mention some IPv4/IPv6 stuff that I don't fully understand but does seem to assume that both addresses exist; either way that's specific about the Standalone authenticator and I'm using the Apache authenticator.

BTW now I'm looking at this: https://letsencrypt.org/docs/ipv6-support/

> When making outbound domain validation requests **for a domain that has both IPv4 and IPv6 addresses (e.g. both A and AAAA records)** Let’s Encrypt will always prefer the IPv6 addresses for the initial connection. If the IPv6 connection fails at the network level (e.g. there is a timeout) and there are IPv4 addresses available then we will retry the request with one of the IPv4 addresses.

(emphasis added) This phrasing strongly suggests that having an AAAA record is not required, just as I initially expected, and yet if tere is none Certbot fails. So in the end this **does look like just a plain bug.**

**Comment by alexzorin** [comment] 2022-03-26 18:37
Sorry, it's too hard to guess what's happening from a list of redacted domains. 

You will see the NXDOMAIN error from the Certificate Authority if your domain has neither an A nor AAAA record. If you have a valid record of either type and it's visible in public DNS, the error shouldn't happen.

It is ultimately not Certbot which is validating the challenges. That is the Certificate Authority, which in this case is Let's Encrypt's https://github.com/letsencrypt/boulder software. That is where the DNS records are evaluated and error messages are produced.

I'm going to close this issue and suggest you post your question on https://community.letsencrypt.org/.  I don't think there is a bug here, but it's possible that once your problem is better understood, that there might be some way to improve the wording of the error messages to clarify things.

**Comment by php4fan** [comment] 2022-03-26 21:01
> Sorry, it's too hard to guess what's happening from a list of redacted domains.

No it isn't. The error message is there, what domain it refers to is irrelevant. Anyway, the two errors are for one domain and its www. subdomain.

> You will see the NXDOMAIN error from the Certificate Authority if your domain has neither an A nor AAAA record. If you have a valid record of either type and it's visible in public DNS, the error shouldn't happen.

And yet it does. Ok so the expected behavior is what I initially thought. 

Later I added the AAAA record and everything worked. 

> It is ultimately not Certbot which is validating the challenges. That is the Certificate Authority, which in this case is Let's Encrypt's https://github.com/letsencrypt/boulder software. 

Oh ok, I'll report the bug there, thank you.

**Comment by osirisinferi** [comment] 2022-03-26 21:36
> Oh ok, I'll report the bug there, thank you.

This is with up to 100&nbsp;% certainty not an issue in Boulder too.

You should open a thread on the Community, as suggested and linked to by @alexzorin. Note that it is mandatory to list your domain name there to get help, as it is almost impossible to debug such issues without it.

**Comment by php4fan** [comment] 2022-03-26 21:53
> This is with up to 100 % certainty not an issue in Boulder too.

Isn't that who prints the error message "no valid AAAA records  found for ..."?
Whoever prints that message has a bug, either for failing a validation that should succeed (because there was a A record) or for printing a wrong or insufficient error message (if there was something else actually wrong with the domain).

**Comment by osirisinferi** [comment] 2022-03-27 09:46
> Isn't that who prints the error message "no valid AAAA records found for ..."?

Yes.

> Whoever prints that message has a bug, either for failing a validation that should succeed (because) or for printing a wrong or insufficient error message (if there was something else actually wrong with the domain). The absence of a AAAA record, alone, is no cause for failure (unless the documentation is wrong), and the error message doesn't point out any other issue.

With 2 billion succesful certificates issued daily by Let's Encrypt/Boulder, I'm pretty sure (but not 100&nbsp;% of course) that this is not a bug in Boulder too, but another reason why Boulder returns these error messages.

In any case, it's not a Certbot issue, so no need to discuss it further in this repository. You're still welcome to come over to the Community to discuss this further.

**Comment by TonyGravagno** [comment] 2022-03-28 00:57
I'm having the same issue discussed here. It just started. I have a server with multiple domains, each with subdomains. I run my own DNS and have A/IPv4 and AAAA/IPv6 addresses defined in the zone.

I have a primary domain for which there are existing certs for subdomains. I just created new subdomains and am getting this error. 

Please keep this ticket open, simply for discussion as we coordinate feedback. I'll look around as directed, but *something* new is up *somewhere*, and it will be helpful now to aggregate related info wherever we can, regardless of where the new fault exists.

Thanks!

**Comment by alexzorin** [comment] 2022-03-28 01:01
This is a bug tracker for Certbot, it's not the place to have this discussion. Please open a thread on https://community.letsencrypt.org/.

**Closed by alexzorin** 2022-03-28 01:01 UTC

**Comment by php4fan** [comment] 2022-03-28 12:29
@TonyGravagno I'm not sure if your issue is the same that I experienced but you may want to watch this:
https://github.com/letsencrypt/boulder/issues/6018

**Comment by TonyGravagno** [comment] 2022-03-29 00:02
Friends - this is not a Certbot issue. @alexzorin thanks for your patience.

@php4fan I've been seeing weird server responses where the same page is reported by LE as both missing (404) and access denied (403). So as noted in the Boulder thread, there **are** messaging issues upstream from Certbot that we can pursue outside of this repo.

In my systems I have ISPConfig loaded which issues certs through Certbot for us. Inbound requests for .well-known/acme-challenge are redirected to  /usr/local/ispconfig/interface/acme/, which is why inbound HTTP requests show a 404 when even hand-created files in .well-known/acme-challenge are clearly there.

I don't know if you use ISPConfig. That's not my point. My point is that something else is probably redirecting your inbound requests, and the challenge files correctly written by certbot are not being seen by LE.

Modify your .conf file(s) with `LogLevel trace6` and restart Apache.  
cat /dev/null > error.log  
Now issue a certbot request (probably with --dry-run).  
Now 'more error.log' and look at the detail to see what files it's attempting to read, the actual folder names, and the results being generated.

If that doesn't help, manually create .well-known/acme-challenge/index.html in your site root, check folder/file permissions and ownership. and see if you can see the file with a manual browser query. Again, clear and check the error.log to see exactly what's happened.

Reset the LogLevel when done!

At this point its best for us not to bother the certbot audience any further on this. Check your logs. Pursue this as a question about Apache. Look more deeply into your configs and what might be intercepting requests.

HTH

**Comment by dagelf** [comment] 2022-11-08 11:02
.well_known files don't affect A or AAAA records.
