### ISSUE TITLE
Long domain name fails with error "string too long"

### ISSUE THREAD

**Issue by caluml** [certbot/certbot#1915] opened 2015-12-16 19:19 UTC
Hello there,
I have a domain name which, with tld is 66 characters long. It is 62 characters long excluding the .com
I have obtained certificates successfully for other domains, but trying to obtain a certificate for the long one fails with:

An unexpected error occurred:
Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]
Please see the logfiles in /var/log/letsencrypt for more details.

Please support longer domain names.

**Comment by AustinPaquette** [comment] 2015-12-16 19:32
I unfortunately don't have any insight to offer on the subject but out of _pure curiosity_, what is this domain name if you don't mind me asking?

**Comment by bmw** [comment] 2015-12-16 21:53
The crypto library we use is throwing an error saying the name is too long. To explain what's going on, the Let's Encrypt client takes the list of domains it's given and puts the first domain name in the `commonName` field of the CSR. According to the [RFC](https://tools.ietf.org/html/rfc5280#appendix-A.1), the CN of X509 certs has a maximum length of 64 characters, hence the error.

Perhaps we could put something else in the CN. Not sure what that'd be though.

**Comment by bmw** [comment] 2015-12-16 22:11
While we look into a longer term fix, there are a couple of things you can do.

As alluded to by my first comment, if you're requesting a cert with multiple domains, list the shorter domain name first. It will be put into the CN of the CSR, avoiding the problem.

Another alternative is to use your own CSR and specify it on the command line with `--csr`. Note, this CSR must be given in DER format and have a Subject Alternative Name field for every domain you want.

**Comment by kuba** [comment] 2015-12-23 12:55
FTR the code in question is likely `letsencrypt.crypto_util.init_save_csr`

**Comment by caluml** [comment] 2016-01-10 20:49
Hey bmw.

I'll try the CSR route, and see if I can work around it for now. Not sure how automated it'll be though.

C

**Comment by caluml** [comment] 2016-01-14 22:04
Unfortunately, I can't generate a CSR with openssl.

I get the following error:
problems making Certificate Request
3555938678416:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:158:maxsize=64

Is this a bug in OpenSSL? From Wikipedia:
"A label may contain zero to 63 characters". Add on .com to that, and you have 67 characters.

**Comment by bmw** [comment] 2016-01-19 22:19
@caluml, this is not a bug in OpenSSL. I said [here](https://github.com/letsencrypt/letsencrypt/issues/1915#issuecomment-165262834), that domain is longer than what is allowed in the common name field of a X509 cert.

You should put something else as the common name and put the long domain as a subject alternative name. There are a number of tutorials online about how to do this using OpenSSL. Also, remember:
> Note, this CSR must be given in DER format and have a Subject Alternative Name field for every domain you want.

**Comment by Kohera** [comment] 2016-07-06 21:29
You can have around 255 characters as Subject Alternative Name. Only the first name (commonName) has this restriction of 64 characters.

$ ./certbot-auto --domain 64charactersdomainsdfjklsdfjklsdfjsldkfjskdlfmnxvrtjrtnmsfk.com --domain 255charactersdomainsfdjklw4nrksfdjilsdjflkjaernmdsfjlksdfjoikldsfkljsdfilj9jkdfnvekfmxvjioemndfjsdfioerkdfndfsnlsdfjlksdfjoijerkneksdfndslfjijerdskfndsfdjfijerkklmdfsjdsfjioerkdsfjldfhkjeresfjnkdfhjdsfjhdfjhdfjhdjfhjdfhjoiuerjknfnlerudfjkdnfjkdfdfile.com

**Comment by tdelmas** [comment] 2017-08-02 18:14
Any update/progress/ETA on this issue? Shouldn't it be a https://github.com/letsencrypt/boulder issue?

For reference: https://community.letsencrypt.org/t/ssl-for-a-63-character-max-number-of-characters-domain-name-s/36387

**Comment by zxzeigler** [comment] 2018-03-15 23:19
Is there a short version of the answer where I do not have to become an expert on the subject to get this to work?

**Comment by AustinPaquette** [comment] 2018-03-16 02:00
@zxzeigler not sure if they will be a fix for your case, but perhaps it may be helpful.

>As alluded to by my first comment, if you're requesting a cert with multiple domains, list the shorter domain name first. It will be put into the CN of the CSR, avoiding the problem.
>
>Another alternative is to use your own CSR and specify it on the command line with --csr. Note, this CSR must be given in DER format and have a Subject Alternative Name field for every domain you want.

**Comment by hycday** [comment] 2018-08-09 19:49
i had same issue; it was due to country code : it needs to be 2 characters, like FR or DE for example

**Comment by schoen** [comment] 2018-10-01 23:51
This is effectively an upstream problem with the Let's Encrypt certificate issuance policy. It's been discussed a number of times on the Let's Encrypt Community Forum and there is some research in progress to figure out whether Let's Encrypt could stop putting domain names into the X.509 `CN` field at all. If so, this problem would go away; until then, it will continue to be a problem and it can't be entirely fixed by Certbot. We could nonetheless give a more useful error message, and we probably should.

I'm going to close this issue in favor of a new one suggesting that Certbot should attempt to reorder names in the requested certificate, when possible, in order to work around this server-side limitation.

https://github.com/certbot/certbot/issues/6402

If people are interested in following the server-side policy aspect, you can discuss it at https://community.letsencrypt.org/ or https://github.com/letsencrypt/boulder.

**Closed by schoen** 2018-10-01 23:51 UTC
Labels: feature request

**Comment by nexusguy59** [comment] 2021-11-13 11:32
I am getting this issue regardless of name in common name. I have an empty common name and it stills states that the string is too long.

![image](https://user-images.githubusercontent.com/4959383/141642223-0dd37528-8901-45f8-940f-5523abb0cfa6.png)



Creating certificate failed!
problems making Certificate Request 6870340:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2

problems making Certificate Request
6870340:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:a_mbstr.c:154:maxsize=2
