### ISSUE TITLE
Error after doing `certbot certonly` in OSX

### ISSUE THREAD

**Issue by westoque-gv** [certbot/certbot#3413] opened 2016-08-16 13:47 UTC
Ran `certbot certonly` and got an error.

```
$ certbot certonly
An unexpected error occurred:
OSError: [Errno 13] Permission denied: '/etc/letsencrypt'
Please see the logfile 'certbot.log' for more details.
```

but doing `which letsencrypt` returns `/usr/local/bin/letsencrypt`

Using OSX 10.11.6 and installed using `certbot` using homebrew.

**Comment by DomT4** [comment] 2016-08-16 15:34
See https://github.com/certbot/certbot/issues/3132. This was made clearer in https://github.com/certbot/certbot/pull/3265, but that's not available in a release currently.

**Comment by bmw** [comment] 2016-08-16 19:54
Yes this is a duplicate of #2306 which has been resolved in `master` and will be included in our next release. Sorry for the confusion!

**Closed by bmw** 2016-08-16 19:54 UTC
