### ISSUE TITLE
Use our Apache/Nginx TLS configuration file without using our installers

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7584] opened 2019-11-22 18:18 UTC
Proposed by @joohoi, one feature we could add to Certbot would be to automatically put our Apache/Nginx TLS configuration file in a well defined location and ensure it's being updated even if you're not using the Apache/Nginx installer. We don't currently have this because we haven't clearly documented where this file will be created and when it's updated. The file is currently only updated when the Apache/Nginx plugin is used.

This may be beneficial for people who can't use our plugin (for example mod_macro users) or just want to install their certificates themselves for whatever reason.

**Comment by Kixunil** [comment] 2020-03-13 05:50
Hi, I need this feature (using mustache to generate nginx configuration) and I'm willing to implement it. I'm not sure when the file is updated. Is it with the package, if package manager is used? If yes, then I'd suggest to just statically place the file to `/usr/share/letsencrypt/tls-options/apache.conf`/`/usr/share/letsencrypt/tls-options/nginx.conf`. If the file is updated from certbot itself then it should go to `/srv/letsencrypt/tls-options/`, if my understanding of Linux Filesystem Hierarchy Standard is correct. (`/usr/share/` is for architecture-independent files managed by package managers, `/srv/` is for files managed by the package, where the files are part of the interface - the files are not internal to the package)

But, maybe, if the files should be managed by package managers, then we should contact them instead. In that case, I'm willing to handle the communication with Debian maintainers, as that's the platform I'm using.

I need this soon, ideally in a few days, so I'd kindly ask to increase the priority of this. I offer my full support implementing this, I pretty much only need enough information to know how to do it.

**Comment by bmw** [comment] 2020-03-13 16:53
Hi @Kixunil. Thanks for your interest in contributing to Certbot.

This is actually a bit tricky because there isn't a single set of TLS options that a version of Certbot uses with Apache or Nginx. Instead, we follow the recommendations from https://ssl-config.mozilla.org/ and the options we use change depending on the version of the web server and OpenSSL on the system.

At least partially because of that, this file is not handled by the OS packages. Instead, when Certbot's Apache or Nginx plugins first run, they determine your software versions and install/update files in Certbot's configuration directory which is `/etc/letsencrypt` by default. The files created are `options-ssl-apache.conf`, `options-ssl-nginx.conf`, and `ssl-dhparams.pem` depending on the plugin being used. (We could discuss the validity of this location with regards to the Linux FHS, but I think it's important that the directories used by Certbot are configurable and do not think it's worth adding yet another directory someone has to configure to do something like run Certbot without root privileges.)

You may be able to get the behavior you want by simply running `certbot plugins --prepare` which will cause Certbot's Apache/Nginx plugins to create/update the files in `/etc/letsencrypt` if the plugins are installed. (It's probably worth noting that while we have no plans to change things here and probably never will, I wouldn't consider the behavior or location of these files as stable and they may change in the future. See https://certbot.eff.org/docs/compatibility.html).

If that doesn't work for you, this is going to be a fair bit of work. I think we'd need to extend Certbot's plugin API in a backwards compatible way to give Certbot a way to call into the plugins to install/update these files when something like `certbot renew` is run which should be preconfigured to run every 12 hours on most systems. The current APIs for plugins are defined at https://certbot.eff.org/docs/api/certbot.interfaces.html and https://certbot.eff.org/docs/api/certbot.plugins.enhancements.html. This should include a system so these files are only created if the user is using these plugins or requested the feature being discussed in the PR.

If you do this, we can try to work with you, but our time to devote to this is a bit limited right now as the Certbot team is stretched pretty thin and we only do releases on first Tuesday of each month so this feature certainly will not be available in the next few days. I'd also recommend proposing an API design first and getting a +1 from us on that before spending a bunch of time implementing a specific proposal.

**Comment by Kixunil** [comment] 2020-03-14 13:04
Thanks a lot for your reply! `certbot plugins --prepare` will definitely solve it for me, I missed the option in the docs and by this issue being open after googling I assumed, it's not implemented. I wonder why the issue is open. :)

The Debian package doesn't use the option by default, so I will suggest it to the maintainers. Debian has a very nice feature called triggers that allows any package to run a script after another package is updated. Running the script when nginx or OpenSSL is updated should be possible. Another nice thing is that I can do it myself without *depending* on the change in the official package, but could be useful for others.

Finally, I realize, the interface doesn't have to be super-stable as the packages are tested anyway and a change would likely lead to a very obvious bug caught during testing. Having it in `/etc/letsencrypt`  is good now. In the worst case, the file paths can be fixed by adding symlinks. The only requirement is that there's always a way to generate the files (without modifying other configuration).

I will let you, and whoever else stumbles upon this issue, know about the result of communication with Debian maintainers.

**Comment by Kixunil** [comment] 2020-03-16 09:13
Harlan Lieberman-Berg said it's  good idea and asked me to file a bug. I filed the bug here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954067

**Comment by bmw** [comment] 2021-02-01 19:54
Harlan asked me to take a look at this issue and share my thoughts. Rereading everything here and the linked bug report, I'm honestly pretty hesitant to make any changes to either Certbot or its Debian package to better support this right now. This seems like a very niche feature as only one user having expressed interest in it, there is a workaround of running `certbot plugins --prepare`, and I think implementing it comes with a number of downsides such as:

1. The Certbot team would need to commit to more well defined behavior for these files.
2. As discussed on the Debian issue, really doing this properly would require updating the file when Apache, nginx, or OpenSSL change in the future which seems somewhat complex.
3. I think there is a small potential to break things as if the user had configured Certbot to install the certificate with a version of Apache or nginx not installed by the package manager, different versions could be used, and a call to `certbot plugins --prepare` that doesn't specify the path to that other installation could incorrectly update the file.

All of this is to say is that for now what I recommend is for Harlan to close https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954067 as wontfix referencing this issue and if people want to see this implemented, add a +1 reaction to my initial post or post a comment if you have more to add than a simple show of support for this change.

**Comment by Kixunil** [comment] 2021-02-01 20:34
Thanks for looking into it!

I've implemented it for myself in the meantime by having a custom package with triggers interest on all the relevant packages which should do the right thing. Your response may indicate a problem with my approach so I'd like to ask for clarifications

1. do you anticipate some specific changes that could cause breakage in the future? I personally don't care about a little breakage as long as I can react to it reasonably.
2. Calling that command on update of any of these packages is trivial in Debian - it's just one line per package in triggers file. Maybe you mean  some other problem I didn't consider?
3. This thankfully doesn't apply to me. Users mixing system packages with custom builds should be aware they're playing with fire. A configuration option to turn off this behavior should not be hard to implement if someone needs it.

Closing the bug as wontfix doesn't affect me until there's at least one other package in the system that needs this. So don't worry about me and feel free to close. I'd just really like to see this implemented if the situation changes in the future.

**Comment by bmw** [comment] 2021-02-01 22:12
Thanks for being so understanding!

> do you anticipate some specific changes that could cause breakage in the future? I personally don't care about a little breakage as long as I can react to it reasonably.

We probably won't make any changes here, especially in the next couple years, however, you're technically relying on undocumented behavior from Certbot that we may change at any point. We try to describe in detail what backwards compatibility people can expect at https://certbot.eff.org/docs/compatibility.html and any behavior outside of that technically should not be considered stable.

> Calling that command on update of any of these packages is trivial in Debian - it's just one line per package in triggers file. Maybe you mean some other problem I didn't consider?

Getting this trigger added to the different packages that are maintained by others sounds a little annoying to me personally, but I know very little about `.deb` packaging so this was likely just a naive assumption on my part.

**Comment by Kixunil** [comment] 2021-02-02 08:42
> We probably won't make any changes here, especially in the next couple years, however, you're technically relying on undocumented behavior from Certbot that we may change at any point.

Can I at least somehow subscribe to a notification of such change being planned if it ever happens? Even a simple ping would be very helpful to not be surprised when it breaks. I don't mind adapting my code to handle it, just want to know. Would be even nicer if it was part of semver (thanks for using semver, BTW!) but I understand you don't want to bump it just because it breaks one person.

> Getting this trigger added to the different packages that are maintained by others sounds a little annoying to me 

It can be done in a single package - the certbot one. That's the beauty of Debian packaging. :)

**Comment by bmw** [comment] 2021-02-02 18:47
This is a bit awkward and I'm not sure how the people who work on Certbot with me will react to this idea, but what if we added a code comment where the path to these files is defined and where they are set up when plugins are "prepared" referencing this issue and saying it'd be nice to update this thread to give people a heads up if we're changing either of these things?

**Comment by Kixunil** [comment] 2021-02-02 18:56
That'd work for me.

**Comment by bmw** [comment] 2021-02-02 23:22
I opened https://github.com/certbot/certbot/pull/8635 for this.

**Closed** 2022-11-18 18:27 UTC
Labels: feature request, area: nginx, area: apache, priority: unplanned
