### ISSUE TITLE
TypeError: finalize_order() got an unexpected keyword argument 'fetch_alternative_chains'

### ISSUE THREAD

**Issue by tacerus** [certbot/certbot#8758] opened 2021-04-01 05:29 UTC
## My operating system is (include version):
openSUSE Leap 15.3 Alpha

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip 20.0.2 (python 3.6)

## I ran this command and it produced this output:
certbot certonly -d tried.with.two.different.domains --key-type ecdsa --elliptic-curve secp384r1 --dns-rfc2136 --dns-rfc2136-propagation-seconds 15 --dns-rfc2136-credentials /etc/letsencrypt/certbot-dnsupdate

## Certbot's behavior differed from what I expected because:
Expected Certbot to generate a certificate, as all prerequisites were met, as confirmed by a certificate generation on a different machine for a different domain, which shared the same setup, except for the operating system.

## Here is a Certbot log showing the issue (if available):
https://hugz.io/tyy6jh/letsencrypt12042021 (I only showed output upon reinstalling certbot and testing with the seen example domain. The previous logs using the other tested domain name showed the same error).

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
I am not doing that.

## Additional troubleshooting steps which I performed
- uninstalled the DNS plugin's as well as Certbot's pip package
- removed /etc/letsencrypt
- made sure no operating system certbot packages were installed
- made sure all operating system packages were up to date
- reinstalled the pip packages 

## "Solution"
More a workaround, but I am now able to generate my certificates. I altered the file /usr/lib/python3.6/site-packages/certbot/_internal/client.py and changed line 291/292 from
```
        orderr = self.acme.finalize_order(orderr, deadline,
                                          fetch_alternative_chains=get_alt_chains)
```
to
```
        orderr = self.acme.finalize_order(orderr, deadline
                                          )
```

**Comment by alexzorin** [comment] 2021-04-01 08:03
Hello!

If installing Certbot using `pip` rather than the snap or openSUSE packages, it is strongly advised to use a virtual environment per the `pip` instructions: https://certbot.eff.org/lets-encrypt/pip-other.

This problem is caused by an incompatible mix of Python packages being installed (a new-ish version of `certbot` but a too-old version of `acme`).

It is an unfortunate part of `pip` that it's quite easy to accidentally break the globally-installed packages.

I'm going to tentatively close this, but please try the instructions linked above. If  you have trouble with them, I'd be happy to look into it.

**Closed by alexzorin** 2021-04-01 08:03 UTC
