### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'add'

### ISSUE THREAD

**Issue by lj2007331** [certbot/certbot#4662] opened 2017-05-14 07:15 UTC
## My operating system is (include version):
CentOS7.3
certbot-0.14.0
Python2.7.13 or 3.5.3
2017-05-14 15:13:31,096:DEBUG:certbot.main:certbot version: 0.14.0
2017-05-14 15:13:31,097:DEBUG:certbot.main:Arguments: []
2017-05-14 15:13:31,098:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-05-14 15:13:31,101:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/python/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python3.5/site-packages/certbot/main.py", line 729, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/usr/local/python/lib/python3.5/site-packages/certbot/cli.py", line 1089, in prepare_and_parse_args
    helpful.add_deprecated_argument("--agree-dev-preview", 0)
  File "/usr/local/python/lib/python3.5/site-packages/certbot/cli.py", line 741, in add_deprecated_argument
    self.parser.add_argument, argument_name, num_args)
  File "/usr/local/python/lib/python3.5/site-packages/certbot/util.py", line 479, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'

**Comment by yan12125** [comment] 2017-05-14 07:55
This is caused by the new ConfigArgParse. See #4648.

**Comment by bmw** [comment] 2017-05-15 22:51
I'm closing this as a duplicate.

The bug has been fixed in `master` and we'll release Certbot 0.14.1 containing the fix shortly.

**Closed by bmw** 2017-05-15 22:51 UTC
