### ISSUE TITLE
cerbot-auto upgrade error v0.25.1/letsencrypt-auto-source/letsencrypt-auto. HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by eqms** [certbot/certbot#6108] opened 2018-06-13 19:34 UTC
## My operating system is (include version):
debian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git clone https://github.com/certbot/certbot

## I ran this command and it produced this output:
./certbot-auto certonly --standalone --rsa-key-size 4096 -d mydomain.de

## Here is a Certbot log showing the issue (if available):

augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
libssl-dev is already the newest version.
openssl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Upgrading certbot-auto 0.25.0 to 0.25.1...
Couldn't download https://raw.githubusercontent.com/certbot/certbot/v0.25.1/letsencrypt-auto-source/letsencrypt-auto. HTTP Error 404: Not Found

**Comment by bmw** [comment] 2018-06-13 19:37
Sorry for the trouble!

This is a duplicate of #6107. The problem has been fixed now. Rerunning `certbot-auto` will solve the problem.

**Closed by bmw** 2018-06-13 19:37 UTC
