### ISSUE TITLE
Provide more help in the terminal UI for plugin question (and other questions?)

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4029] opened 2017-01-12 02:46 UTC
```
How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Apache Web Server plugin - Beta (apache)
2: Place files in webroot directory (webroot)
3: Spin up a temporary webserver (standalone)
-------------------------------------------------------------------------------
```

It turns out that `1` is `tls-sni-01 (443)`
and that `2` is `http-01 (80)`
whereas `3` is `http-01 (80) or tls-sni-01 (443)`
As documented here: http://letsencrypt.readthedocs.io/en/latest/using.html

Possible approaches:
1. Include a link to relevant documentation sections at each prompt (I actually think this might be the right answer)
1. Indicate the port and acme protocol in the labels

The reason I care is that my first server (a test server) automatically managed to make this work (apparently by doing `1`).

My second server, I didn't want to mess with the apache service, so, `2` seemed appealing. Since I have access to the webroot (in theory).

But, my server isn't reachable via :80, so `2` wasn't going to work.

Normal users don't read "webserver" and think "oh, that's :80", and "apache" and think, "oh, that's :443". To me, webserver and apache are fairly interchangable, in that they both can listen to :80/:443.

**Comment by pde** [comment] 2017-01-12 22:39
Great idea about adding that doc link to the prompt. Previously (0.9.3 and before) we were constrained by the Dialog UI, but at least had a help section. Now we should probably add extra hint information, or 

Note that on your production server, doing `certbot certonly --apache` (ie picking 1) will only make temporary/transient changes to your Apache config, so it's less of a risk than `certbot --apache`.

**Comment by jsoref** [comment] 2017-01-12 22:53
I couldn't pick 1 because I had two virtual hosts in my config file, one for *:80 and one for *:443, which resulted in the Apache agent giving up.

That's why I tried two. 

On 1, I spent a while trying to figure out if I could teach it how to handle my case, but it's pretty hard to work through. Ideally you'd collect the hosts that are :443 and subtract them from the ones that are :80 and only consider messing with the remainder. 

Anyway, I was able to get past that by commenting out the :80 host (which is unreachable due to a firewall anyway).

**Comment by pde** [comment] 2017-01-12 23:28
By "teach it", do you mean modify the apache plugin, or change your config so that the plugin could work with it?

**Comment by jsoref** [comment] 2017-01-13 04:06
yes modify the plugin.

**Comment by pde** [comment] 2017-01-18 19:55
This is closely related to and perhaps even a duplicate of #3872...

**Comment by jsoref** [comment] 2017-08-25 15:19
@pde: that path was closed (removing code). I'm open to writing this stuff, but I'm not even sure there's a particularly good place to link to. Anyone have suggestions (text/urls)?

**Comment by adferrand** [comment] 2019-03-12 09:10
With tls-sni-01 been removed in the next days, I think this issue is not relevant anymore. If not, do not hesitate to reopen an issue with updated info about its context.

**Closed by adferrand** 2019-03-12 09:10 UTC
Labels: area: ui / ux
