### ISSUE TITLE
add a commandline option to `--register-only`

### ISSUE THREAD

**Issue by jvanasco** [certbot/certbot#2980] opened 2016-05-13 01:39 UTC
I'm not sure if this is a dupe of #2446 , which has no description 

The intent of this ticket is that the certbot program would have a switch that will (only) create a new account (with TOS registration, etc).

There are at least 2 reasons for this:

1. a user may want to create an account / accept the TOS on "machine 1", but run certbot on "machine 2"
2. a user may want to use another client, but that client does not offer the account creation/management - and expects the account to be created on the official client. 

full disclosure: i wrote a client that I'm opensourcing and we're the second case.

**Comment by bmw** [comment] 2016-05-13 15:23
Yes, this is a dupe of #2446. I'll quote what you said here and add it to the issue.

**Closed by bmw** 2016-05-13 15:23 UTC
