### ISSUE TITLE
Revoking ECDSA certificate with error.

### ISSUE THREAD

**Issue by sugitach** [certbot/certbot#9026] opened 2021-09-09 05:22 UTC
when revoke I got following error.

```
josepy.errors.DeserializationError: Deserialization error: Could not decode 'jwk' ({'x': 'hKuvTg07naYihTf65bBZyEb0qZHNzYBHyglV3j4tclg', 'y': '2YZ5xmOV5wzaqoyk899c2bTKec06wzobF5EtVRSsoA', 'crv': 'P-256', 'kty': 'EC'}): Deserialization error: Expected parameter "y" to be range(32, 33) bytes after base64-decoding; got 31 bytes instead
```

command line is...

```
certbot revoke --no-delete-after-revoke --cert-path [certificate-filename] --key-path [key-filename] -c [ini-filename]
```

ini-file contains...

```
authenticator = manual
installer = null
no-eff-email = true
agree-tos = true

register-unsafely-without-email = true
server = https://dummy.origin:14000/dir   # this is pebble server
config-dir = /var/data/certbot/config
work-dir = /var/data/certbot/work
logs-dir = /var/log/certbot/
non-interactive = true

manual-auth-hook = /var/service/oke/okeapp/bin/certbot_pre_auth.pl
manual-cleanup-hook = /var/service/oke/okeapp/bin/certbot_post_auth.pl
```

I use certbot 1.18.0, and ACME test server is pebble (https://github.com/letsencrypt/pebble)

I got a same error when use a same certificate.

Any Idea?

**Comment by alexzorin** [comment] 2021-09-09 06:26
Could you please post the full log file related to this error?

It's not clear to me how you managed to make this error happen, since Certbot does not support ECDSA account keys. Trying to revoke by an ECDSA certificate private key is not supported either, but it results in a different error message (see #8569).

Thank you.

**Comment by sugitach** [comment] 2021-09-09 08:34
thank you to reply.
full log is followed.

```
2021-09-09 04:21:27,622:DEBUG:certbot._internal.main:certbot version: 1.18.0
2021-09-09 04:21:27,622:DEBUG:certbot._internal.main:Location of certbot entry point: /var/service/oke/bin/certbot
2021-09-09 04:21:27,622:DEBUG:certbot._internal.main:Arguments: ['-c', '/var/service/oke/okeapp/etc/certbot.ini', '--no-delete-after-revoke', '--cert-path', '/var/data/certbot/exec/revoke_141344.crt', '--key-path', '/var/data/certbot/exec/revoke_141344.key']
2021-09-09 04:21:27,622:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-09-09 04:21:27,643:DEBUG:certbot._internal.log:Root logging level set at 30
2021-09-09 04:21:27,643:DEBUG:certbot._internal.main:Revoking /var/data/certbot/exec/revoke_141344.crt using certificate key /var/data/certbot/exec/revoke_141344.key
2021-09-09 04:21:27,644:DEBUG:acme.client:Sending GET request to https://dummy.origin:14000/dir.
2021-09-09 04:21:27,645:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dummy.origin:14000
2021-09-09 04:21:27,655:DEBUG:urllib3.connectionpool:https://dummy.origin:14000 "GET /dir HTTP/1.1" 200 421
2021-09-09 04:21:27,656:DEBUG:acme.client:Received response:
HTTP 200
Cache-Control: public, max-age=0, no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Sep 2021 19:21:27 GMT
Content-Length: 421

{
   "keyChange": "https://dummy.origin:14000/rollover-account-key",
   "meta": {
      "externalAccountRequired": false,
      "termsOfService": "data:text/plain,Do%20what%20thou%20wilt"
   },
   "newAccount": "https://dummy.origin:14000/sign-me-up",
   "newNonce": "https://dummy.origin:14000/nonce-plz",
   "newOrder": "https://dummy.origin:14000/order-plz",
   "revokeCert": "https://dummy.origin:14000/revoke-cert"
}
2021-09-09 04:21:27,656:DEBUG:certbot._internal.main:Reason code for revocation: 0
2021-09-09 04:21:27,656:DEBUG:acme.client:Requesting fresh nonce
2021-09-09 04:21:27,656:DEBUG:acme.client:Sending HEAD request to https://dummy.origin:14000/nonce-plz.
2021-09-09 04:21:27,659:DEBUG:urllib3.connectionpool:https://dummy.origin:14000 "HEAD /nonce-plz HTTP/1.1" 200 0
2021-09-09 04:21:27,659:DEBUG:acme.client:Received response:
HTTP 200
Cache-Control: public, max-age=0, no-cache
Link: <https://dummy.origin:14000/dir>;rel="index"
Replay-Nonce: 4lPyxcUqtOwLxVCPWSwoLg
Date: Wed, 08 Sep 2021 19:21:27 GMT


2021-09-09 04:21:27,659:DEBUG:acme.client:Storing nonce: 4lPyxcUqtOwLxVCPWSwoLg
2021-09-09 04:21:27,660:DEBUG:acme.client:JWS payload:
b'{\n  "certificate": "MIIDDDCCAfSgAwIBAgIIf4KfNxMyA80wDQYJKoZIhvcNAQELBQAwKDEmMCQGA1UEAxMdUGViYmxlIEludGVybWVkaWF0ZSBDQSA1MjM4NDkwHhcNMjEwOTA4MTkxNjI0WhcNMjYwOTA4MTkxNjI0WjAmMSQwIgYDVQQDExthdXRvY2VydDI4NDA0LWE1LmV4YW1wbGUuanAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQybytHT0ztuJOSUHEQSrICL00Fmfr1KBk1Q0A0USwrdwB7-JTngHmNSDxRU6YBJkKH9iBPbiZui_abgxCRGRk7o4IBBTCCAQEwDgYDVR0PAQH_BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTckCxpGECrjB3SsQmA5mMh45sEyTAfBgNVHSMEGDAWgBR9XGWJJMKbCzPYQArKBwwl9bL6ezCBgQYDVR0RBHoweIIbYXV0b2NlcnQyODQwNC1hNS5leGFtcGxlLmpwghthdXRvY2VydDI4NDA0LWE1LmV4YW1wbGUuanCCPGF1dG9jZXJ0Mjg0MDQtYTUuZXhhbXBsZS5qcC5pZDEwMDAwMDAxNjEub2tlY2RuLmlwY2FzdGluZy5qcDANBgkqhkiG9w0BAQsFAAOCAQEAVkGFQtOSxLIV5EMGUs2GN71ZaP6HMfso8sLdjWw0cjTmkexmgDxdxmaaFnNQcqEUblQE2d4eXefvxxLZJO8xKDNaBBuap6VV4-H7hp3bhmPkn1jMVSLSpYe9MoMXepb9h5wQKozSqv1276mAFSVlHrFk5ix4LV7uPKoaH9Fk03cYbDKarHRZIiUhwu5xWKSUqBSnh7qIksUorS5aOUjVhE9rPLFCZ3Lwdci-QoR2OFzLI3PowN3HefjJXLy3PYo8UfPc9KrFDaeqZwbpVgkKxqnaotYfYq37M5V9FL9J4lHiIzG5eoJWtIG9ZmadxN2QPXAANedrW9ddCdW6M9Gbxg",\n  "reason": 0\n}'
2021-09-09 04:21:27,660:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/var/service/oke/lib/python3.8/site-packages/josepy/json_util.py", line 281, in fields_from_json
    fields[slot] = field.decode(value)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/json_util.py", line 87, in decode
    return self.fdec(value)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/json_util.py", line 480, in from_json
    return type_cls(**type_cls.fields_from_json(jobj))
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jwk.py", line 350, in fields_from_json
    x, y = (cls._decode_param(jobj[n], n, expected_length) for n in ('x', 'y'))
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jwk.py", line 350, in <genexpr>
    x, y = (cls._decode_param(jobj[n], n, expected_length) for n in ('x', 'y'))
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jwk.py", line 289, in _decode_param
    raise errors.DeserializationError(
josepy.errors.DeserializationError: Deserialization error: Expected parameter "y" to be range(32, 33) bytes after base64-decoding; got 31 bytes instead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/service/oke/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/var/service/oke/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/var/service/oke/lib/python3.8/site-packages/certbot/_internal/main.py", line 1566, in main
    return config.func(config, plugins)
  File "/var/service/oke/lib/python3.8/site-packages/certbot/_internal/main.py", line 1238, in revoke
    acme.revoke(jose.ComparableX509(cert), config.reason)
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 948, in revoke
    return self.client.revoke(cert, rsn)
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 779, in revoke
    return self._revoke(cert, rsn, self.directory['revokeCert'])
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 216, in _revoke
    response = self._post(url,
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 87, in _post
    return self.net.post(*args, **kwargs)
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 1213, in post
    return self._post_once(*args, **kwargs)
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 1223, in _post_once
    data = self._wrap_in_jws(obj, self._get_nonce(url, new_nonce_url), url, acme_version)
  File "/var/service/oke/lib/python3.8/site-packages/acme/client.py", line 1041, in _wrap_in_jws
    return jws.JWS.sign(jobj, **kwargs).json_dumps(indent=2)
  File "/var/service/oke/lib/python3.8/site-packages/acme/jws.py", line 53, in sign
    return super().sign(payload, key=key, alg=alg,
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jws.py", line 266, in sign
    cls.signature_cls.sign(payload=payload, **kwargs),))
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jws.py", line 230, in sign
    return cls(protected=protected, header=header, signature=signature)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jws.py", line 165, in __init__
    kwargs = self._with_combined(kwargs)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/jws.py", line 176, in _with_combined
    combined = header + cls.header_cls.json_loads(protected)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/interfaces.py", line 178, in json_loads
    return cls.from_json(loads)
  File "/var/service/oke/lib/python3.8/site-packages/josepy/json_util.py", line 290, in from_json
    return cls(**cls.fields_from_json(jobj))
  File "/var/service/oke/lib/python3.8/site-packages/josepy/json_util.py", line 283, in fields_from_json
    raise errors.DeserializationError(
josepy.errors.DeserializationError: Deserialization error: Could not decode 'jwk' ({'x': 'Mm8rR09M7biTklBxEEqyAi9NBZn69SgZNUNANFEsK3c', 'y': 'e_iU54B5jUg8UVOmASZCh_YgT24mbov2m4MQkRkZOw', 'crv': 'P-256', 'kty': 'EC'}): Deserialization error: Expected parameter "y" to be range(32, 33) bytes after base64-decoding; got 31 bytes instead
2021-09-09 04:21:27,664:ERROR:certbot._internal.log:An unexpected error occurred:
2021-09-09 04:21:27,664:ERROR:certbot._internal.log:josepy.errors.DeserializationError: Deserialization error: Could not decode 'jwk' ({'x': 'Mm8rR09M7biTklBxEEqyAi9NBZn69SgZNUNANFEsK3c', 'y': 'e_iU54B5jUg8UVOmASZCh_YgT24mbov2m4MQkRkZOw', 'crv': 'P-256', 'kty': 'EC'}): Deserialization error: Expected parameter "y" to be range(32, 33) bytes after base64-decoding; got 31 bytes instead
```

**Comment by sugitach** [comment] 2021-09-09 08:37
I don't use ECDSA account keys.
I use ECDSA key on certificate private key only.
My account key is made from certbot internally.

**Comment by alexzorin** [comment] 2021-09-09 12:26
Thanks a lot for posting the log. I can confirm that this is a separate bug to the one I linked. I've filed an issue on the josepy project for this.

That said, revocation of ECDSA using the certificate key is simply not supported in Certbot yet, per #8569.  For now, omit the `--key-path` and let Certbot use the ACME account key to revoke ECDSA certificates.

**Comment by sugitach** [comment] 2021-09-09 19:40
I forgot to say with the patched that was in # 8569.
Can I `--key-path` even if I apply this patch?

**Comment by alexzorin** [comment] 2021-09-09 19:52
If you have both the patch from #8569 and also a patched version of `josepy` (or wait for a new release of `josepy` which should be soon), yes, I guess it should work.

**Comment by sugitach** [comment] 2021-09-09 19:57
Thank you. I try it.

**Comment by sugitach** [comment] 2021-09-09 21:09
I try to patch https://github.com/certbot/josepy/commit/c1ba6ca9b05989724b4436efb2d91246d2ebaa5c .
It seems that it works well now. thank you.

**Comment by alexzorin** [comment] 2021-09-09 21:33
Great to hear. I'm going to close this because the underlying issues are already tracked by #8569 and the josepy work.

**Closed by alexzorin** 2021-09-09 21:33 UTC
Labels: area: cert management, area: 3rd party, priority: significant
