### ISSUE TITLE
Encoding must be an item from encoding enum

### ISSUE THREAD

**Issue by whitj00** [certbot/certbot#3503] opened 2016-09-16 16:29 UTC
I get this issue on ubuntu 16.04 with apache

Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 660, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 206, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 191, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 127, in register
    acc = account.Account(regr, key)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/account.py", line 60, in __init__
    format=serialization.PublicFormat.SubjectPublicKeyInfo)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 604, in public_bytes
    self._rsa_cdata
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 2208, in _public_key_bytes
    raise TypeError("encoding must be an item from the Encoding enum")
TypeError: encoding must be an item from the Encoding enum

**Comment by Dunky13** [comment] 2016-10-02 11:52
I have the same problem...

**Comment by dollarklavs** [comment] 2016-10-16 11:30
Same setup and same problem for me.

**Comment by Dunky13** [comment] 2016-11-02 11:25
Bump?

**Comment by thijskh** [comment] 2016-11-19 12:32
I had this on debian-jessie and it was the result of some wrong package combination, possibly related to backports. Because I was a bit in a hurry I removed `certbot` and all its `python-*` dependencies completely, and then freshly installed it all with apt. Sorry that I was not able to pinpoint it further, but maybe this helps someone.

**Comment by Dunky13** [comment] 2016-11-23 11:45
Tried the same thing, accidentally removed all my certificates and ssl options... Crap... Had to re-install every certificate, but again I got the enum error. Somehow I had a working certbot-auto stored in my home directory that did work. Nonetheless it still doesn't work properly for me

**Comment by Dunky13** [comment] 2016-12-17 16:08
Bump?

**Comment by pde** [comment] 2016-12-19 22:34
These kinds of errors are usually caused by a mismatch between the versions of `python-cryptography` and `openssl` / `libssl` on your system. However in this case it looks like you might be using the Xenial packages for all of those things, which makes this a little unusual. Was there a recent Xenial update to either `libssl` or `python-cryptography`?

**Comment by Dunky13** [comment] 2016-12-19 22:37
For me what seems to be working is the certbot-auto that seems comparable to the letsencrypt-auto in the master gist repository. But the certbot that must load sub code doesn't.

Hope this helps?

**Comment by alex** [comment] 2016-12-19 22:42
This wouldn't be caused by the `openssl` package, this is something specific to `cryptography` itself, and I really have no idea beyond that.

**Comment by reaperhulk** [comment] 2016-12-19 23:20
This error arises from an isinstance check that looks for a member of a specific enum. If (somehow, bear with me this is gonna be hand-wavey) the enum it was looking for and the enum passed were from different versions of cryptography that were somehow both loaded that could account for this issue...

**Comment by alex** [comment] 2017-02-23 02:50
Is there any more info here about a way to reproduce this?

**Comment by Thynix** [comment] 2017-07-11 05:42
Same issue on Debian Stretch:

* apache 2.4.25
* certbot 0.10.2-1
* python-certbot-apache 0.10.2-1
* python-cryptography 1.7.1-3

This box was upgraded from Debian Jessie, where I used the `jessie-backports` version, and might have also used a more manual installation method earlier: I had an outdated `zope.interface` installed with `pip`,

**Comment by rickyhan** [comment] 2017-07-21 21:16
same issue here

**Comment by reissmann** [comment] 2018-05-03 14:02
same issue

**Comment by bmw** [comment] 2019-05-09 18:05
It's been almost a year since this issue has seen any activity so I'm closing it. If you're still hitting this, please comment or open a new issue.

**Closed by bmw** 2019-05-09 18:05 UTC
Labels: area: debian / ubuntu, area: pkging

**Comment by goma1256** [comment] 2021-11-01 15:58
Just for the record and anyone out there, also happened to me using : 
- Python 3.6.1 (using Spyder on Windows 10 - please don't judge)
- Fresh install of sshtunnel (0.4.0)
- Cryptography 3.4.7 already installed

Solved by updating Cryptography to 35.0.0 using pip.

Hope this helps!
