### ISSUE TITLE
Bug causing errors 'Namespace' object has no attribute 'auth_chain_path'

### ISSUE THREAD

**Issue by shimmi2** [certbot/certbot#9685] opened 2023-04-26 16:29 UTC
Hello guys. I believe I have found the bug in certbot code, which is causing issues like #9562,  and fixed it.

Its in __init__.py, near end of file (line number depends on version) in `set_by_cli` at line 
`in line if not isinstance(getattr(detector, var), _Default):`

Execution seems not running over this line with unset attribute, but in my case it apparently hapened. Execution failing on test condition, which should check presence, is error in principe. So I won't bother You with additiobal info (i used [certbot-pdns](https://github.com/robin-thoni/certbot-pdns) auth from commandline, like guy in reffered issue).

I just added simple exception handling as remedy.

``` 
try:
        if not isinstance(getattr(detector, var), _Default):
            logger.debug("Var %s=%s (set by user).", var, getattr(detector, var))
            return True
    except AttributeError:
        logger.debug("Var %s (unsset by user, catched AttributeError).", var);
        return False
```

Please, someone consider adding to code. Pardon me for not doing this myself by correct way - pull request.

Thank You for Your work guys

**Comment by osirisinferi** [comment] 2023-04-26 18:13
Can you perhaps provide some kind of (real life) example on how to trigger this bug? Because in the issue you've linked it was not reproducable.

**Comment by alexzorin** [comment] 2023-04-26 21:32
I think this is most likely caused by the `certbot-pdns` clobbering the configuration object used by Certbot.

1. Certbot has an existing variable called `auth_chain_path`.
2. PowerDNS [advertises an entrypoint called `auth`](https://github.com/robin-thoni/certbot-pdns/blob/e6d1b193a5f11d1c71812499e82fdbb02ae58450/setup.py#L70).
3. Something bad is happening with the configuration namespaces due to the overlap.

I don't believe the fix you are suggesting is the right thing to do. It may mask the problem, but fundamentally the namespace conflict is the cause and should be the thing that is fixed.

I think most likely, the `certbot-pdns` plugin will need to abandon the `auth` entrypoint and rename it to something like `dns-pdns`, which would conform with convention.

I am going to mark this as wontfix.

**Closed by alexzorin** 2023-04-26 21:32 UTC

**Comment by shimmi2** [comment] 2023-04-27 00:30
Understood. What You wrote seems stripping the problem and pulling to light :)
My solution work perfect for me, so I will keep it locally.
And You boys maybye adopt or write support for PowerDNS info certbot as native in future. Its one of [top DNS servers](https://blog.dnsimple.com/2015/02/top-dns-servers/)

**Comment by jvanasco** [comment] 2023-08-07 18:16
This seems to be a duplicate of #9562 - same error, and same powerdns plugin
