### ISSUE TITLE
How to set `ssl_trusted_certificate` in nginx configuration file?

### ISSUE THREAD

**Issue by zwl1619** [certbot/certbot#5098] opened 2017-09-10 11:22 UTC
I use `Mozilla SSL Configuration Generator`(https://mozilla.github.io/server-side-tls/ssl-config-generator/) to generate a nginx configuration file.   

There are three items about certificate,as follow :   

```
ssl_certificate /path/to/signed_cert_plus_intermediates;
ssl_certificate_key /path/to/private_key;
ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;
```

I use certbot(https://github.com/certbot/certbot) to apply certificate，but I can not find `ssl_trusted_certificate`,how to generate it ?

**Comment by SwartzCr** [comment] 2017-09-11 21:51
Ah, I believe that's what we call the fullchain, it should be in the same directory as the rest of the files under the name `fullchain.pem`
Let me know if that works!

**Comment by mnordhoff** [comment] 2017-09-21 19:08
`ssl_trusted_certificate` wants "trusted CA certificates" for verifying client certs (irrelevant) or OCSP responses (relevant).

https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate

Setting "`ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;`" currently works. I'm not sure if there are downsides to not including the DST or ISRG root, but it seems to work...

**Comment by SwartzCr** [comment] 2017-09-25 18:59
Sounds like this is chain.pem works, so I'm going to close this.
Feel free to open a new issue or post on the community forums if you have more questions about certificate structure!
https://community.letsencrypt.org/

**Closed by SwartzCr** 2017-09-25 18:59 UTC
Labels: area: cert management, debugging

**Comment by ryan2clw** [comment] 2018-04-06 19:32
I wanted to comment on `ssl_certificate` vs `ssl_trusted_certificate`.  I put my website's cert on top and the intermediate 2 certs that came with my commodo purchase labeled "ca-bundle" underneath.  Both lines of code point to the same combined cert file.  You don't really need software to do that, just sudo cat file1 file2 > fullChain.pem from the command line, or cut/paste it together.
<img width="1079" alt="screen shot 2018-04-05 at 6 48 48 pm" src="https://user-images.githubusercontent.com/17858514/38440233-c6247de8-39ae-11e8-9872-624b923c2fdf.png">
HMU on my website if you have other deployment issues.

**Comment by Capricorn1** [comment] 2020-01-02 22:48
This still works. After trying several variations of pointing to my site cert and the signer's cert chain, just setting both `ssl_certificate` and `ssl_trusted_certificate` to point to my bundled cert just worked. The error message 

> nginx: [emerg] SSL_CTX_load_verify_locations("/certs/crt/intermediate.crt") failed (SSL: error:0B084088:x509 certificate routines:X509_load_cert_crl_file:no certificate or crl found)

could be a lot better. It made me think I was having a permissions issue reading the certs.

**Comment by mconigliaro** [comment] 2020-03-07 17:23
This is what I've been using (confirmed working via https://www.ssllabs.com/ssltest/analyze.html?d=mail.conigliaro.org):

    ssl_certificate /etc/letsencrypt/live/mail.conigliaro.org/fullchain.pem
    ssl_certificate_key /etc/letsencrypt/live/mail.conigliaro.org/privkey.pem
    ssl_trusted_certificate /etc/letsencrypt/live/mail.conigliaro.org/chain.pem

It doesn't seem to matter whether you set `ssl_trusted_certificate` to `chain.pem` or `fullchain.pem`, but I think that's because `fullchain.pem` contains `chain.pem`.

**Comment by rileypeterson** [comment] 2022-08-19 21:40
I had to use `fullchain.pem` instead of `chain.pem` to get this working using [NGINX Config](https://www.digitalocean.com/community/tools/nginx)

else I got:

```
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: mydomain.com
  Type:   connection
  Detail: 11.22.333.100: Fetching http://mydomain.com/.well-known/acme-challenge/s_VA-POXpHZI: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.
```
