### ISSUE TITLE
nginx wildcard matching seems to be broken

### ISSUE THREAD

**Issue by SwartzCr** [certbot/certbot#4726] opened 2017-05-24 00:40 UTC
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
from the ppa

## I ran this command and it produced this output:
certbot renew --nginx

the nginx config has the line `server_name *.*;`
But certbot returns `Attempting to renew cert from /etc/letsencrypt/renewal/qqq.example.com produced an unexpected error: Cannot find a VirtualHost matching domain qqq.example.com.. Skipping.`
When it should find that that's a valid config.
as @ohemorange pointed out it works with `server_name ~.*;`

**Comment by pde** [comment] 2017-05-25 23:31
We should figure out: is this a regression? How serious is it? Should it block the Ubuntu SRU of 0.14.1?

**Comment by ohemorange** [comment] 2017-05-25 23:46
Closing this, because `*.*` is not actually valid Nginx -- only one `*` is allowed.

**Closed by ohemorange** 2017-05-25 23:46 UTC
Labels: area: nginx
