### ISSUE TITLE
Renew only renewed partially, claims other certificates are not due for renewal

### ISSUE THREAD

**Issue by etiago** [certbot/certbot#3499] opened 2016-09-15 04:50 UTC
Recently I received e-mails from Letsencrypt regarding certificate expiration. Because I have certbot set up as a cronjob with the 'renew' argument, some of my certificates in the fullchain were automatically renewed, yet I noticed that some other certificates in the fullchain simply refused to renew. Even when I ran the command manually, I would get the following:

```
tiago@yyyyyyyy:/usr/local/certbot$ sudo /usr/local/certbot/certbot-auto renew

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/xxxxxxxx.com.conf
-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/xxxxxxxx.com/fullchain.pem (skipped)
No renewals were attempted
```

This was really strange, since some of those certificates would expire soon, on October 1st and certbot didn't realize this. In the end I manually forced it with `--force-renewal` and all the certificates were renewed (less than ideal, since now my other certificates which had also recently been renewed, got renewed once more - not a problem, more of a nuisance).

Anyone else faced this issue? Is it a bug or just a problem in my configs?

**Comment by bmw** [comment] 2016-09-16 00:22
Do you remember if you checked if `/etc/letsencrypt/live/xxxxxxxx.com/fullchain.pem` had actually been renewed or if Certbot just said it was? There's a known issue causing the behavior you're describing (see  #3497) but none of the four files in `/etc/letsencrypt/live/xxxxxxxx.com` are updated.

**Comment by etiago** [comment] 2016-09-19 09:36
@bmw I didn't actually check but I'm inclined to believe it was, since *some* of the certificates in the chain *did* get renewed...

**Comment by bmw** [comment] 2016-09-19 19:39
The bug in #3497 causes your certificate to be properly renewed and written to `/etc/letsencrypt/archive`. The problem is that the symlinks in `/etc/letsencrypt/live` are never updated to point to the new certificate.

**Comment by limonte** [comment] 2016-10-01 16:41
Same issue here. My certificate expires in 26 days, but when I'm trying to update it with `certbot-auto renew` I'm getting `The following certs are not due for renewal yet` notification which is wrong.

**Comment by bmw** [comment] 2016-10-03 19:52
@limonte, as described above, you should be able to fix this problem by adding `--force-renewal` to the command line, however, please don't do that yet if you haven't already.

Before you do, can you answer these two questions for me:

1. What is the output of `sudo ls -l /etc/letsencrypt/archive/<domain> /etc/letsencrypt/live/<domain>`, where `domain` is one of the names of the certificate you're trying to renew?
2. Do you have a logfile in `/var/log/letsencrypt` detailing how your configuration got into this state? Probably the easiest way to check this is to run `sudo grep -r "Exiting abnormally" /var/log/letsencrypt/`. If any file matches, it would be very useful if you posted the full contents of the file. This file may contain your e-mail address and the domain names you're requesting though. Feel free to redact this information as you feel appropriate.

**Comment by limonte** [comment] 2016-10-03 20:47
Sure, I'm glad to help!

> What is the output of sudo ls -l /etc/letsencrypt/archive/<domain> /etc/letsencrypt/live/<domain>, where domain is one of the names of the certificate you're trying to renew?

```
/etc/letsencrypt/archive/<domain>:
total 48
-rw-r--r-- 1 root root 1834 May 31 01:36 cert1.pem
-rw-r--r-- 1 root root 1834 Jul 30 12:45 cert2.pem
-rw-r--r-- 1 root root 1834 Sep 29 05:05 cert3.pem
-rw-r--r-- 1 root root 1647 May 31 01:36 chain1.pem
-rw-r--r-- 1 root root 1647 Jul 30 12:45 chain2.pem
-rw-r--r-- 1 root root 1647 Sep 29 05:05 chain3.pem
-rw-r--r-- 1 root root 3481 May 31 01:36 fullchain1.pem
-rwxrwxrwx 1 root root 3481 Jul 30 12:45 fullchain2.pem
-rw-r--r-- 1 root root 3481 Sep 29 05:05 fullchain3.pem
-rw-r--r-- 1 root root 1708 May 31 01:36 privkey1.pem
-rw-r--r-- 1 root root 1704 Jul 30 12:45 privkey2.pem
-rw-r--r-- 1 root root 1704 Sep 29 05:05 privkey3.pem

/etc/letsencrypt/live/<domain>:
total 0
lrwxrwxrwx 1 root root 41 Sep 29 05:05 cert.pem -> ../../archive/english-online.rs/cert3.pem
lrwxrwxrwx 1 root root 42 Sep 29 05:05 chain.pem -> ../../archive/english-online.rs/chain3.pem
lrwxrwxrwx 1 root root 46 Sep 29 05:05 fullchain.pem -> ../../archive/english-online.rs/fullchain3.pem
lrwxrwxrwx 1 root root 44 Sep 29 05:05 privkey.pem -> ../../archive/english-online.rs/privkey3.pem
```

> Do you have a logfile in /var/log/letsencrypt detailing how your configuration got into this state? Probably the easiest way to check this is to run sudo grep -r "Exiting abnormally" /var/log/letsencrypt/. If any file matches, it would be very useful if you posted the full contents of the file

I have the `/var/log/letsencrypt/letsencrypt.log` log file, but there's no "Exiting abnormally" substrings in it, here's the whole content of that file:

```
cat /var/log/letsencrypt/letsencrypt.log
2016-10-03 20:42:19,279:DEBUG:certbot.main:Root logging level set at 30
2016-10-03 20:42:19,280:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-03 20:42:19,281:DEBUG:certbot.main:certbot version: 0.8.1
2016-10-03 20:42:19,281:DEBUG:certbot.main:Arguments: []
2016-10-03 20:42:19,281:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-10-03 20:42:19,342:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f35af69c910> and installer <certbot.cli._Default object at 0x7f35af69c910>
2016-10-03 20:42:19,343:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7f35af68fb90>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7f35af68f950>, apache=<certbot.cli._Default object at 0x7f35af69ca10>, apache_challenge_location=<certbot.cli._Default object at 0x7f35af69cdd0>, apache_ctl=<certbot.cli._Default object at 0x7f35af69c5d0>, apache_dismod=<certbot.cli._Default object at 0x7f35af6a0090>, apache_enmod=<certbot.cli._Default object at 0x7f35af69cf50>, apache_handle_modules=<certbot.cli._Default object at 0x7f35af69cad0>, apache_handle_sites=<certbot.cli._Default object at 0x7f35af69c7d0>, apache_init_script=<certbot.cli._Default object at 0x7f35af69c290>, apache_le_vhost_ext=<certbot.cli._Default object at 0x7f35af6a01d0>, apache_server_root=<certbot.cli._Default object at 0x7f35af6a0310>, apache_vhost_root=<certbot.cli._Default object at 0x7f35af6a0410>, authenticator=<certbot.cli._Default object at 0x7f35af69c910>, break_my_certs=<certbot.cli._Default object at 0x7f35af6924d0>, cert_path=<certbot.cli._Default object at 0x7f35af696dd0>, chain_path=<certbot.cli._Default object at 0x7f35af69c110>, checkpoints=<certbot.cli._Default object at 0x7f35af6968d0>, config_dir=<certbot.cli._Default object at 0x7f35af69c210>, config_file=None, configurator=<certbot.cli._Default object at 0x7f35af69c910>, csr=<certbot.cli._Default object at 0x7f35af6967d0>, debug=<certbot.cli._Default object at 0x7f35af6920d0>, dialog_mode=<certbot.cli._Default object at 0x7f35af6e3f50>, domains=<certbot.cli._Default object at 0x7f35af68f490>, dry_run=<certbot.cli._Default object at 0x7f35af68f090>, duplicate=<certbot.cli._Default object at 0x7f35af68fc90>, email=<certbot.cli._Default object at 0x7f35af68f390>, expand=<certbot.cli._Default object at 0x7f35af68f690>, fullchain_path=<certbot.cli._Default object at 0x7f35af696fd0>, func=<function renew at 0x7f35afc80320>, hsts=<certbot.cli._Default object at 0x7f35af6929d0>, http01_port=<certbot.cli._Default object at 0x7f35af6923d0>, ifaces=<certbot.cli._Default object at 0x7f35af696bd0>, init=<certbot.cli._Default object at 0x7f35af6969d0>, installer=<certbot.cli._Default object at 0x7f35af69c910>, key_path=<certbot.cli._Default object at 0x7f35af696ed0>, logs_dir=<certbot.cli._Default object at 0x7f35af69c410>, manual=<certbot.cli._Default object at 0x7f35af69cd10>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0x7f35af696a50>, manual_test_mode=<certbot.cli._Default object at 0x7f35af696c50>, must_staple=<certbot.cli._Default object at 0x7f35af6926d0>, nginx=<certbot.cli._Default object at 0x7f35af69cb10>, no_self_upgrade=<certbot.cli._Default object at 0x7f35af68fe90>, no_verify_ssl=<certbot.cli._Default object at 0x7f35af6921d0>, noninteractive_mode=<certbot.cli._Default object at 0x7f35af6e3e50>, num=<certbot.cli._Default object at 0x7f35af6965d0>, os_packages_only=<certbot.cli._Default object at 0x7f35af68fd90>, post_hook=<certbot.cli._Default object at 0x7f35af696210>, pre_hook=<certbot.cli._Default object at 0x7f35af696110>, prepare=<certbot.cli._Default object at 0x7f35af696ad0>, quiet=<certbot.cli._Default object at 0x7f35af68ff90>, redirect=<certbot.cli._Default object at 0x7f35af6927d0>, register_unsafely_without_email=<certbot.cli._Default object at 0x7f35af68f190>, reinstall=<certbot.cli._Default object at 0x7f35af68f590>, renew_by_default=<certbot.cli._Default object at 0x7f35af68f850>, renew_hook=<certbot.cli._Default object at 0x7f35af696310>, rsa_key_size=<certbot.cli._Default object at 0x7f35af6925d0>, server=<certbot.cli._Default object at 0x7f35af69c510>, staging=<certbot.cli._Default object at 0x7f35af69c610>, standalone=<certbot.cli._Default object at 0x7f35af69cc10>, standalone_supported_challenges=<certbot.cli._Default object at 0x7f35af69c090>, staple=<certbot.cli._Default object at 0x7f35af692dd0>, strict_permissions=<certbot.cli._Default object at 0x7f35af692fd0>, text_mode=<certbot.cli._Default object at 0x7f35af6e3d50>, tls_sni_01_port=<certbot.cli._Default object at 0x7f35af6922d0>, tos=<certbot.cli._Default object at 0x7f35af68fa90>, uir=<certbot.cli._Default object at 0x7f35af692bd0>, update_registration=<certbot.cli._Default object at 0x7f35af68f290>, user_agent=<certbot.cli._Default object at 0x7f35af6966d0>, validate_hooks=<certbot.cli._Default object at 0x7f35af696410>, verb='renew', verbose_count=<certbot.cli._Default object at 0x7f35af6e3c90>, webroot=<certbot.cli._Default object at 0x7f35af69ce10>, webroot_map=<certbot.cli._Default object at 0x7f35af696e50>, webroot_path=<certbot.cli._Default object at 0x7f35af69cf10>, work_dir=<certbot.cli._Default object at 0x7f35af69c310>)
2016-10-03 20:42:19,377:INFO:certbot.renewal:Cert not yet due for renewal
2016-10-03 20:42:19,384:INFO:certbot.renewal:Cert not yet due for renewal
2016-10-03 20:42:19,388:DEBUG:certbot.renewal:no renewal failures
```

**Comment by limonte** [comment] 2016-10-03 21:17
Yeah, `--force-renewal` helped in my case too :+1: (I ran it after my previous comment).

**Comment by bmw** [comment] 2016-10-03 21:42
One more question for you @limonte, what's the output of:
`sudo openssl x509 -in /etc/letsencrypt/archive/<domain>/cert3.pem -noout -enddate`

**Comment by limonte** [comment] 2016-10-03 21:45
```
notAfter=Dec 28 02:05:00 2016 GMT
```

**Comment by bmw** [comment] 2016-10-03 21:54
Progress! So before you ran Certbot with `--force-renewal`, you had a certificate which doesn't expire for approximately 3 months in `/etc/letsencrypt/archive` and pointed to in `/etc/letsencrypt/live`. What made you think your certificate was close to expiration? Was an older one still being served by your webserver? If so, what webserver are you running? If you're using Apache with the Apache Certbot plugin, can you post the contents of `/etc/letsencrypt/renewal/<domain>.conf`? As usual, feel free to redact information as you wish.

**Comment by limonte** [comment] 2016-10-03 22:02
daaaamn, I think I realised where is my mistake - should I reload nginx after cert renewal?

**Comment by bmw** [comment] 2016-10-03 22:06
You should! We should also update our documentation to make the need to do this more clear. Most webservers, like Nginx, read the certificate once when starting and never read them again. To pick up the new certificate, they need to be restarted.

You can automate this step with the `--post-hook` flag with something like `--post-hook "service nginx reload"`. See the output of `certbot --help renew` for more information.

**Comment by limonte** [comment] 2016-10-03 22:09
Thanks a lot for this clarification!

**Comment by etiago** [comment] 2016-10-04 03:57
@bmw I'm fairly sure this wasn't my issue though, because part of the domains in my chain were renewed and some weren't (after I had issued the nginx reload) - and all the certificates are requrested in a single command that requests them all in one go (which, as I understand, means that all the certificates will be in a single certificate chain and the client, though SNI, figures things out).

My guess is that I will face this again around December 14... so I can come back and give more feedback then :)

**Comment by bmw** [comment] 2018-11-29 19:08
This issue hasn't seen any activity since 2016 so I'm closing it. If anyone still has this issue, please comment or open a new issue.

**Closed by bmw** 2018-11-29 19:08 UTC
Labels: area: renewal, more-info
