### ISSUE TITLE
Remove e-mail address from registration

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#3162] opened 2016-06-13 18:31 UTC
The subcommand `certbot update_account` allows users to update the email address in their ACME account. Currently, Certbot does not allow users to remove all email addresses from a registration. See the code for [update_account](https://github.com/certbot/certbot/blob/df1ca726f975b4f2cf96ada29785a4d35027e5f9/certbot/certbot/_internal/main.py#L684-L727).

We should allow users to do this, probably by reusing the `--register-unsafely-without-email` flag since it is usually a bad idea to have a Let's Encrypt account with no contact information.

This issue relies on https://github.com/certbot/certbot/issues/5129 being resolved which you may want to do in a PR before this one.

EDIT: My original description of this issue was very sparse and vague so I rewrote it to provide more information.

**Comment by chefscott** [comment] 2017-07-19 23:23
Could you provide a little bit more guidance like which files to edit? Is it just `certbot/cli.py`?

**Comment by bmw** [comment] 2017-07-20 17:48
You'd at least have to modify [certbot.main.register](https://github.com/certbot/certbot/blob/bb6a22b9853cfab2a06cb020ddf57dd5a6ae8eba/certbot/main.py#L455) and potentially the code called there so updating a registration without an email address works.

**Comment by bmw** [comment] 2019-06-11 17:51
This is still an issue.

**Comment by cpu** [comment] 2019-06-11 17:54
@bmw Is this a duplicate of https://github.com/certbot/certbot/issues/5129 or is 5129 for `acme` and 3162 is for the end user `certbot` tool?

**Comment by bmw** [comment] 2019-06-11 18:07
Thanks for the ping @cpu. I remembered seeing you comment on a similar issue somewhere in my inbox which I hadn't got to yet.

These issues could be combined, but you're right that it was previously my intention for this issue to track the Certbot work and #5129 to track the `acme` work.

**Comment by aeturnum** [comment] 2020-07-31 00:07
Hi, I was looking for a first issue, but I thought I should double check before working on this.

Is this issue still valid and correctly described? The code in [certbot.internal.client](https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/client.py#L154) allows this with the --register-unsafely-without-email (though it hasn't been updated since 2015). However, the cli interface at [cerbot.internal.cli.__init__](https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/cli/__init__.py#L171)  (just updated in february of 2020) specifies that flag should be provided if you wish to register without email. That made me think the current behavior might be the desired one.

**Comment by bmw** [comment] 2020-07-31 15:53
Hi @aeturnum :wave:

Thanks for taking a look at our open issues.

I updated https://github.com/certbot/certbot/issues/3162#issue-160015326 to provide more information here.

**Closed** 2020-08-26 22:22 UTC
Labels: feature request, good first issue, has pr, priority: significant
