### ISSUE TITLE
parse tabs from previous line and copy it instead of hard coded tabs.

### ISSUE THREAD

**Issue by cjwijtmans** [certbot/certbot#7448] opened 2019-10-13 01:10 UTC
##  My operating system is (include version):
gentoo

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
portage

## I ran this command and it produced this output:
sudo certbot --nginx

## Certbot's behavior differed from what I expected because:
It prefixed the line with several spaces, although i prefix lines with tabs in my config files. Can easily be resolved by copying the prefix of previous line instead of hard coding whitespaces.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name www.ertwertw.ewrt .erwtwert.ewrt;
        include snippets/gwert.conf;
}
```

**Comment by sydneyli** [comment] 2019-10-17 00:54
Thanks for the report! I think this is a duplicate of #5157, so closing. Let me know if that bug doesn't fully capture your issue, and I can re-open this bug.

**Closed by sydneyli** 2019-10-17 00:54 UTC
