### ISSUE TITLE
No handlers could be found for logger "certbot.crypto_util"

### ISSUE THREAD

**Issue by PatrickHeppler** [certbot/certbot#3148] opened 2016-06-10 11:41 UTC
I'm using this python script for a while to renew certs and update TLSA records in DNS:
https://gist.github.com/PatrickHeppler/064f6463d14fcf7d7a99f18f68a10684

But now certbot errors out: No handlers could be found for logger "certbot.crypto_util" which "triggers" my error handling. The certificates are signed, that's not the problem. But my script sees an error from letsencrypt and stops processing. I could disable the check, but that's a bad idea.

How to fix this? Missing package maybe?

**Comment by bmw** [comment] 2016-06-10 20:32
The issue is in our processing in our processing of the `--csr` flag. While processing the value, we attempt to log information but in this case, the logging hasn't been set up yet.

We can fix the problem on our end, but in the mean time you may want to make your error handling a little more lenient until this is fixed.

**Comment by PatrickHeppler** [comment] 2016-06-10 20:52
Okay, I have changed my error handling to check for this specific error and ignore it.
Could you please leave a comment here when it's fixed?

**Comment by bmw** [comment] 2016-06-10 20:56
Will do. We'll leave this issue open and close it once it's resolved.

**Comment by pombredanne** [comment] 2016-08-10 10:56
Using the latest from Pypi  https://pypi.python.org/pypi/certbot/0.8.1 I get `No handlers could be found for logger "certbot.plugins.disco"` ... Would this be related? I am not using certbot as a lib but from the command line. I am quite familiar with Python logging though, so I can chip in alright.

**Comment by bmw** [comment] 2016-08-11 17:58
It's almost certainly related. In general, the problem is that Certbot sometimes attempts to log information while processing and post-processing its arguments, however, the logging handlers cannot be setup until we've processed the arguments that affect logging settings.

There are at least three solutions to the problem:
1. Stop logging during argument processing/post-processing
2. Move setting up logging to be the first thing that happens during post-argument processing.
3. Have a simple argument parser that just parses the logging arguments. After this parser has run, we can set up logging and then do normal argument parsing.

I personally don't think 1 is a good idea. There's actually lot of work that goes on while processing/post-processing our arguments and losing logging info there would be unfortunate. An argument could be made that this work should be moved elsewhere which might be a good idea in the long term, however, I don't think this is necessary to fix such a simple problem.

I don't have a strong preference between 2 and 3. 3 is more robust, but also more elaborate and more work. Post-processing happens [here](https://github.com/certbot/certbot/blob/master/certbot/cli.py#L375) and logging setup is [here](https://github.com/certbot/certbot/blob/master/certbot/main.py#L739). Main argument parsing begins [here](https://github.com/certbot/certbot/blob/master/certbot/main.py#L729), however, if we went with approach 3, we could probably move the logging setup before the `plugins = plugins_disco...` line.

If you're interested in working on this, we'd certainly accept a PR. If you have any more questions, feel free to comment on this issue or join us in `#letsencrypt-dev` on Freenode.

**Comment by pombredanne** [comment] 2016-08-11 22:18
@bmw I wonder if there would be a fourth way. You could set up first a minimal error-only default logging handler when processing arguments and then establish the actual requested logger once you processed them. Since arguments processing is not really part of a library-style usage it would not rob a library user to setup their own handlers?

**Comment by pombredanne** [comment] 2016-08-11 22:21
Something like setup a first handler early in `main()` then setting up again in earnest like it is there https://github.com/certbot/certbot/blob/d05f53bd53082832583a5dcfefc2241fd21386e9/certbot/main.py#L743

**Comment by bmw** [comment] 2016-08-13 00:15
Something like that might work. The one downside I see to an approach like that is non-error logging information is lost.

**Comment by JPRuehmann** [comment] 2017-02-18 15:31
I get this error message to will be a Version without available in the Future?

**Closed** 2017-04-13 20:42 UTC
Labels: area: error handling, area: ui / ux, bug
