### ISSUE TITLE
Syntax error during apache configuration

### ISSUE THREAD

**Issue by Kritzefitz** [certbot/certbot#2267] opened 2016-01-22 20:24 UTC
I tried to obtain and install a staging certificate on an apache2 server. My OS is Debian Jessie.

Is used the command `./letsencrypt-auto --apache`.

After accepting the Terms & Conditions and selecting a certificate for all my three domains I got the following error:

```
apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 7 of /etc/apache2/sites-enabled/static-le-ssl.conf: Expected </VirtualHost> but saw </VirtualHost></IfModule>
```

**Comment by pde** [comment] 2016-01-23 01:05
Hi.  What version of the client are you running?  Can you please post your full apache config?

**Comment by Kritzefitz** [comment] 2016-01-25 19:34
The client version is 0.2.0.

I would like to avoid posting the full configuration, but I found out, that the syntax error is caused by a missing newline at the end of a file in `/etc/apache2/sites-enabled/`. I hope this is enough information to fix this.

**Comment by pde** [comment] 2016-01-25 20:30
@domcleal does that make sense to you?  I thought we'd squashed all these newline parsing bugs by [0.2.0](https://github.com/letsencrypt/letsencrypt/blob/e59fcf7ddd58ce85a94435b166209c61460e26d1/letsencrypt-apache/letsencrypt_apache/augeas_lens/httpd.aug) but perhaps not?

**Comment by domcleal** [comment] 2016-01-26 08:02
Could you share the outline of the file, even if you don't include the details?  Specifically I'm interested in which sections were in there, as I can't reproduce this with just a file containing `<VirtualHost>\n</VirtualHost>` (no ending \n).

**Comment by Kritzefitz** [comment] 2016-01-27 18:59
It's roughly like this:

    [some options]

    IncludeOptional mods-enabled/*.load
    IncludeOptional mods-enabled/*.conf

    [some more options]

    IncludeOptional conf-enabled/*.conf
    IncludeOptional sites-enabled/*.conf

This sticks mostly to the configuration shipped with the Debian package.

`mods-enabled` contains configuration for enabled modules. `conf-enabled` contains various snippets.

`sites-enabled` contains two virtual hosts, which include the actual configuration for the host from `virtuals/<virtual-host-name>/main.conf`. One of the hosts was defined in a file called `static.conf`, which was missing a newline at the end. I think this caused the generated `static-le-ssl.conf` to be generated with `</VirtualHost></IfModule>` on the last line, without any whitespace between the two tags.

**Comment by domcleal** [comment] 2016-02-04 09:45
I think what you're describing is that the original VirtualHost is copied and wrapped with `<IfModule mod_ssl.c>...</IfModule>`, and the appending of `</IfModule>` happens without whitespace between the closing VirtualHost and IfModule lines.

An input file like this, with no trailing EOF:

<pre>
&lt;VirtualHost *:80>
    Include /etc/apache2/virtuals/foo/main.conf
&lt;/VirtualHost>
</pre>

ends up like this:

<pre>
&lt;IfModule mod_ssl.c>
&lt;VirtualHost *:80>
    Include /etc/apache2/virtuals/foo/main.conf
&lt;/VirtualHost>&lt;/IfModule>
</pre>

This seems to be a bug in [_copy_create_ssl_vhost_skeleton](https://github.com/letsencrypt/letsencrypt/blob/a280539f2a24f1fceb43be1771bc8ed4d7468f20/letsencrypt-apache/letsencrypt_apache/configurator.py#L775) which should probably check if the line ended with a \n and if not, append one.  It looks like this method's responsible for generating the vhost rather than Augeas.

**Comment by pde** [comment] 2016-12-20 18:57
I can't reproduce this in modern versions of Certbot. Please reopen/refile if you can!

**Closed by pde** 2016-12-20 18:57 UTC
Labels: apache, bug

**Comment by soulhunter123** [comment] 2017-03-19 21:57
I'm having this issue on Centos 6. Trying to add certs for domains whose vhost conf files _don't_ end with a blank line causes the error.

Workaround is to manually add a blank line at the end of the conf files then run certbot.
