### ISSUE TITLE
Certbot run bootstrap only

### ISSUE THREAD

**Issue by koljakutschera** [certbot/certbot#5142] opened 2017-09-27 12:27 UTC
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git

## I ran this command and it produced this output:
/opt/certbot/certbot-auto --no-self-upgrade  --noninteractive certonly ...

## Certbot's behavior differed from what I expected because:
Certbot shows: Bootstrapping dependencies for Debian-based OSes... and takes some minutes....

## Here is a Certbot log showing the issue (if available):
Bootstrapping dependencies for Debian-based OSes...

Hi,

iam using certbot in a docker-container but cant cache certbot dependencies in docker-image. Is there any way to trigger certbot bootstrap(installation of deps) only without getting a cert. Something like: /opt/certbot/certbot-auto --justbootstrapandquit would be very helpful. 

Thx,
K

**Comment by bmw** [comment] 2017-09-28 19:50
I believe this is a duplicate of #4741.

In the meantime, you can use `certbot-auto --version` to get this functionality.

**Closed by bmw** 2017-09-28 19:50 UTC
