### ISSUE TITLE
Nginx parser errors when the domain starts with ‘0x’

### ISSUE THREAD

**Issue by CloverGit** [certbot/certbot#7963] opened 2020-05-01 04:21 UTC
## My operating system is (include version):
CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 1.3.0

## I ran this command and it produced this output:
certbot-auto
>2 (nginx)
>1 (select a domain start with '0x' )
## Output
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for 0xr.ink
Cleaning up challenges
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 1: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.

**Obviously, certbot-auto treated my domain as a hexadecimal character and caused an error**

**Comment by osirisinferi** [comment] 2020-05-02 13:03
Could you please share the contents of `/var/log/letsencrypt/letsencrypt.log`? I'm especially interested in the trace around the error, not so much all the ACME traffic debugging.

**Comment by CloverGit** [comment] 2020-05-04 15:52
> Could you please share the contents of `/var/log/letsencrypt/letsencrypt.log`? I'm especially interested in the trace around the error, not so much all the ACME traffic debugging.

I’m sorry to see your message so late.
This is the informaion in the letsencrypt.log .
I have solved the problem by modifying the python default encoding.


2020-05-01 11:04:00,777:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/configurator.py", line 1116, in perform
    http_response = http_doer.perform()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/http_01.py", line 57, in perform
    self.configurator.save("HTTP Challenge", True)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/configurator.py", line 1051, in save
    self.parser.filedump(ext='')
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/parser.py", line 245, in filedump
    out = nginxparser.dumps(tree)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/nginxparser.py", line 140, in dumps
    return str(RawNginxDumper(blocks.spaced))
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/nginxparser.py", line 104, in __str__
    return ''.join(self)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 1: ordinal not in range(128)

**Comment by alexzorin** [comment] 2020-05-14 11:18
Hi @CloverGit,

I tried to reproduce your issue in the same environment, with the suggested culprit (a `server_name` leading with `0x`) and Certbot behaves properly.

However, if I do something like this (which does not render, appears as whitespace):

    python -c 'print("#" + chr(0xe9))'  >> /etc/nginx/nginx.conf

then your issue is reproducible.

I believe that in your case, the Unicode sequence is coming from somewhere else within the nginx configuration. 

If you still have a configuration where this issue is reproduced, could you please confirm the above, perhaps by:

    grep -RP "\xe9" /etc/nginx/

If not, I think this could be closed as a duplicate of #5337, which was fixed in Certbot 1.4.0 (not yet available in EPEL at the time of this comment, but submitted to EPEL testing yesterday).

**Closed** 2020-05-19 03:54 UTC
Labels: area: nginx, bug, priority: significant
