### ISSUE TITLE
support multiple vhosts per file

### ISSUE THREAD

**Issue by abstratt** [certbot/certbot#1042] opened 2015-10-20 13:14 UTC
My Apache configuration declares multiple vhosts in one site configuration file. letsencrypt [currently does not handle that](https://community.letsencrypt.org/t/error-should-only-be-one-vhost-in-etc-apache2/).

```
Error: should only be one vhost in /etc/apache2/sites-available/000-default.conf
```

**Comment by pde** [comment] 2015-10-20 18:25
I think this is a dupe of #809 ?

**Comment by bmw** [comment] 2015-10-20 18:54
@pde, this is not a dupe.

This refers to the fact that the Apache plugin currently doesn't allow multiple vhosts per file. #809 refers to a specific problem with multiple vhosts when using `install`. The example I gave in #809 has each vhost in a separate file.

**Comment by sjau** [comment] 2015-10-25 21:46
This is not the problem I have.

As you can see, the vhost of apache has 4 entries. One entry each for ipv4/6 and for non-/ssl. The first time I let letsencrypt create a certificate for such domain it works.

When I then remove all letsencrypt data files and stuff and re-try to create new cert. Then it fails.

**Comment by SwartzCr** [comment] 2015-11-03 23:23
I'm going to take a look at this tomorrow, @jdkasten do you have any advice for me?

**Comment by pde** [comment] 2015-11-12 19:30
(if we aren't getting this done by launch, we could kick this ticket out of the milestone with a PR to make the error message more friendly).

**Comment by bmw** [comment] 2015-11-24 00:46
I just made the simple change to improve this error message while we're working on this. If we decide we need to kick this out of the 1.0 milestone, we can do so without further changes to the code.

**Comment by pde** [comment] 2015-11-24 01:08
I think yes, let's kick it out of the milestone.  We have a bunch of compelling apache tickets, it's not really clear this is the most important of them.

**Comment by hrstoyanov** [comment] 2015-12-07 16:34
This is a showstopper for folks who do the right thing - place each domain into a separate conf file. Will come back to letsencrypt when this is solved, but no go for me at this point, sigh ...

**Comment by bmw** [comment] 2016-03-01 20:57
More information (as well as a sample vhost) provided in #2574.

**Comment by samwilson** [comment] 2016-03-10 01:07
+1

**Comment by antoinemichea** [comment] 2016-03-11 20:05
+1

**Comment by jayshields** [comment] 2016-05-01 18:55
+1

**Comment by acdha** [comment] 2016-05-12 14:57
If you've previously obtained a cert and followed the last couple decades of Apache practice by having a simple redirect block in the same file, both `certonly` or `--standalone` also fail in addition to the default process. Even if there's a harder general problem handling complex files, it should be possible to write an renewed certificate either way.

```
<VirtualHost *:80>
    ServerName example.org
    RedirectPermanent / https://example.org/
</VirtualHost>
<VirtualHost *:443>
    ServerName example.org
</VirtualHost>
```

**Comment by paradite** [comment] 2016-05-16 18:03
I had similar issue for my DO VPS, even when only having one vhost in the default conf file `apache2.conf`:

`Error: should only be one vhost in /etc/apache2/apache2.conf`

I fixed it by creating another conf file using 
`sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/mysite.com.conf` 
moving the vhost block to the new conf file and running
`sudo a2ensite mysite.com.conf`

I've also written a post on this issue, if it helps: https://paradite.com/2016/04/09/apache2-config-for-letsencrypt-digitalocean-wordpress/

**Comment by pde** [comment] 2016-07-15 20:56
Discussing with @SwartzCr: this ticket is biting a lot of people, and we should be able to fix it, so making it an architectural target for the 0.10.0 release.

**Comment by Cirromulus** [comment] 2017-01-11 20:25
Bump! If each Site has its .conf with vhost:80 and vhost:433, even renewal fails... 
If you have 8 different Sites, you dont want to duplicate your files...

**Comment by m-mohr** [comment] 2017-01-13 15:33
We are also waiting for this.

**Comment by falzard** [comment] 2017-02-06 21:49
Yep, very very very very very very annoying, I don't even know how I'm gonna do with all these vhosts I must renew

**Comment by sjefen6** [comment] 2017-02-06 22:14
--certonly should work

**Comment by falzard** [comment] 2017-02-06 22:30
Not with the dry run

**Comment by SwartzCr** [comment] 2017-03-01 02:54
@joohoi is working on this currently.
I'd like to point out that people should be able to +1 the top post rather than expressing their excitement for this in individual comments and that I'd also prefer that as it'll keep this message log clean. If you have specific needs or recommendations still feel free to share them, but let's try to keep traffic on this down as we've already prioritized it :D

**Comment by zenny** [comment] 2017-03-06 17:38
I am having the similar problem with nginx.

I have four domains pointing to the same site. I tried to obtain certificate manually, yet one of the alias domain fails as of below:

​​[QUOTE]
# certbot certonly -n --text --agree-tos --authenticator webroot --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --email noreply@SECOND-DOMAIN.COM -d FIRST-DOMAIN.ORG -d www.FIRST-DOMAIN.ORG -d FIRSTDOMAIN.ORG -d www.FIRSTDOMAIN.ORG -d SECOND-DOMAIN.COM -d www.SECOND-DOMAIN.COM -d SECONDDOMAIN.COM -d www.SECONDDOMAIN.COM  --webroot-path /usr/local/ispconfig/interface/acme
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for FIRST-DOMAIN.ORG
http-01 challenge for www.FIRST-DOMAIN.ORG
http-01 challenge for FIRSTDOMAIN.ORG
http-01 challenge for www.FIRSTDOMAIN.ORG
http-01 challenge for SECOND-DOMAIN.COM
http-01 challenge for www.SECOND-DOMAIN.COM
http-01 challenge for SECONDDOMAIN.COM
http-01 challenge for www.SECONDDOMAIN.COM
Using the webroot path /usr/local/ispconfig/interface/acme for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Unable to clean up challenge directory /usr/local/ispconfig/interface/acme/.well-known/acme-challenge
Failed authorization procedure. FIRSTDOMAIN.ORG (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to www.FIRSTDOMAIN.ORG

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: FIRSTDOMAIN.ORG
   Type:   connection
   Detail: Could not connect to www.FIRSTDOMAIN.ORG

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.[/QUOTE]

**Comment by craigarno** [comment] 2017-05-02 21:00
If it will help this effort I will share one of my multiple vhost files I use for our homeowners association.  It basically has to solve these usecase issues:

1.  Provide HTTPS/SSL security
2. Provide regular HTTP access when there are SSL issues, redirect when not.
3. Provide redirection for users who will type "www." in front of whatever domain name you give them for both HTTP and HTTPS vhosts. (easier than trying to modify 80+ households behaviors).
4. More vhost redirection for other related sites like FACEBOOK.hoa.mydomain.com and www.FACEBOOK.hoa.mydomain.com
5. Some additional simple access restrictions, like needing a username/password for access to certain areas of the site.

This requires at least 6 "vhosts" in the file to accomplish.

I already added my +1 for this issue at the top of this page.

**Comment by bmw** [comment] 2017-05-03 00:56
Fixed in #4607 (which is really #4390).

**Closed by bmw** 2017-05-03 00:56 UTC
Labels: area: apache, has pr, high priority, soccer ball

**Comment by SwartzCr** [comment] 2017-05-03 15:10
!!!!!!!!!!!!!!!!! :tada: :tada: :tada: !!!!!!!!!!!!!!!!!

**Comment by mhow2** [comment] 2017-10-09 06:53
Thanks ! But what about debian packages in Stretch ? They still run a rather old version (0.10.0)
