### ISSUE TITLE
certbot fails to renew certificate from previous letsencrypt with "EntryPoint" error

### ISSUE THREAD

**Issue by noccio** [certbot/certbot#3140] opened 2016-06-09 09:47 UTC
I have a working certificate made for my domain with previous letsencrypt on my debian 8.0.

Newly installed certbot fails to renew with this error:

`2016-06-09 11:32:11,731:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/bbs.cybervalley.org.conf produced an unexpected error: 'EntryPoint' object has no attribute 'resolve'. Skipping.`

This is the complete log from this try:

`2016-06-09 09:32:10,842:DEBUG:certbot.main:Root logging level set at 30

2016-06-09 09:32:10,843:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log

2016-06-09 09:32:10,843:DEBUG:certbot.main:certbot version: 0.8.0

2016-06-09 09:32:10,843:DEBUG:certbot.main:Arguments: ['--dry-run']

2016-06-09 09:32:10,844:DEBUG:certbot.main:Discovered plugins: 
PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)

2016-06-09 09:32:10,857:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f8a7d29e390> and installer <certbot.cli._Default object at 0x7f8a7d29e390>

2016-06-09 09:32:10,857:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7f8a7d26e710>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7f8a7d26e510>, apache=<certbot.cli._Default object at 0x7f8a7d29e490>, apache_challenge_location=<certbot.cli._Default object at 0x7f8a7d298c10>, apache_ctl=<certbot.cli._Default object at 0x7f8a7d298410>, apache_dismod=<certbot.cli._Default object at 0x7f8a7d29ead0>, apache_enmod=<certbot.cli._Default object at 0x7f8a7d29e9d0>, apache_handle_modules=<certbot.cli._Default object at 0x7f8a7d298910>, apache_handle_sites=<certbot.cli._Default object at 0x7f8a7d298610>, apache_init_script=<certbot.cli._Default object at 0x7f8a7d2980d0>, apache_le_vhost_ext=<certbot.cli._Default object at 0x7f8a7d29ec10>, apache_server_root=<certbot.cli._Default object at 0x7f8a7d29ed50>, apache_vhost_root=<certbot.cli._Default object at 0x7f8a7d298dd0>, authenticator=<certbot.cli._Default object at 0x7f8a7d29e390>, break_my_certs=<certbot.cli._Default object at 0x7f8a7d294050>, cert_path=<certbot.cli._Default object at 0x7f8a7d298850>, chain_path=<certbot.cli._Default object at 0x7f8a7d298b50>, checkpoints=<certbot.cli._Default object at 0x7f8a7d298350>, config_dir=<certbot.cli._Default object at 0x7f8a7d298c50>, config_file=None, configurator=<certbot.cli._Default object at 0x7f8a7d29e390>, csr=<certbot.cli._Default object at 0x7f8a7d298250>, debug=<certbot.cli._Default object at 0x7f8a7d26ec10>, dialog_mode=<certbot.cli._Default object at 0x7f8a7d267a50>, domains=<certbot.cli._Default object at 0x7f8a7d6d8510>, dry_run=True, duplicate=<certbot.cli._Default object at 0x7f8a7d26e810>, email=<certbot.cli._Default object at 0x7f8a7d6d8690>, expand=<certbot.cli._Default object at 0x7f8a7d26e250>, fullchain_path=<certbot.cli._Default object at 0x7f8a7d298a50>, func=<function renew at 0x7f8a7ebc92a8>, hsts=<certbot.cli._Default object at 0x7f8a7d294550>, http01_port=<certbot.cli._Default object at 0x7f8a7d26ef10>, ifaces=<certbot.cli._Default object at 0x7f8a7d298650>, init=<certbot.cli._Default object at 0x7f8a7d298450>, installer=<certbot.cli._Default object at 0x7f8a7d29e390>, key_path=<certbot.cli._Default object at 0x7f8a7d298950>, logs_dir=<certbot.cli._Default object at 0x7f8a7d298e50>, manual=<certbot.cli._Default object at 0x7f8a7d29e790>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0x7f8a7d294910>, manual_test_mode=<certbot.cli._Default object at 0x7f8a7d294b10>, must_staple=<certbot.cli._Default object at 0x7f8a7d294250>, nginx=<certbot.cli._Default object at 0x7f8a7d29e590>, no_self_upgrade=<certbot.cli._Default object at 0x7f8a7d26ea10>, no_verify_ssl=<certbot.cli._Default object at 0x7f8a7d26ed10>, noninteractive_mode=<certbot.cli._Default object at 0x7f8a7d267710>, num=<certbot.cli._Default object at 0x7f8a7d298050>, os_packages_only=<certbot.cli._Default object at 0x7f8a7d26e910>, post_hook=<certbot.cli._Default object at 0x7f8a7d294d50>, pre_hook=<certbot.cli._Default object at 0x7f8a7d294c50>, prepare=<certbot.cli._Default object at 0x7f8a7d298550>, quiet=<certbot.cli._Default object at 0x7f8a7d26eb10>, redirect=<certbot.cli._Default object at 0x7f8a7d294350>, register_unsafely_without_email=<certbot.cli._Default object at 0x7f8a7d267ed0>, reinstall=<certbot.cli._Default object at 0x7f8a7d26e150>, renew_by_default=<certbot.cli._Default object at 0x7f8a7d26e410>, renew_hook=<certbot.cli._Default object at 0x7f8a7d294e50>, rsa_key_size=<certbot.cli._Default object at 0x7f8a7d294150>, server=<certbot.cli._Default object at 0x7f8a7d298f50>, staging=<certbot.cli._Default object at 0x7f8a7d29e090>, standalone=<certbot.cli._Default object at 0x7f8a7d29e690>, standalone_supported_challenges=<certbot.cli._Default object at 0x7f8a7d294ed0>, staple=<certbot.cli._Default object at 0x7f8a7d294950>, strict_permissions=<certbot.cli._Default object at 0x7f8a7d294b50>, text_mode=<certbot.cli._Default object at 0x7f8a7d267510>, tls_sni_01_port=<certbot.cli._Default object at 0x7f8a7d26ee10>, tos=<certbot.cli._Default object at 0x7f8a7d26e610>, uir=<certbot.cli._Default object at 0x7f8a7d294750>, update_registration=<certbot.cli._Default object at 0x7f8a7d6d8810>, user_agent=<certbot.cli._Default object at 0x7f8a7d298150>, verb='renew', verbose_count=<certbot.cli._Default object at 0x7f8a7d2671d0>, webroot=<certbot.cli._Default object at 0x7f8a7d29e890>, webroot_map=<certbot.cli._Default object at 0x7f8a7d294d10>, webroot_path=<certbot.cli._Default object at 0x7f8a7d294f10>, work_dir=<certbot.cli._Default object at 0x7f8a7d298d50>)

2016-06-09 09:32:10,864:DEBUG:parsedatetime:parse (top of loop): [30 days][]

2016-06-09 09:32:10,876:DEBUG:parsedatetime:CRE_UNITS matched

2016-06-09 09:32:10,877:DEBUG:parsedatetime:parse (bottom) [][30 days][][]

2016-06-09 09:32:10,877:DEBUG:parsedatetime:weekday False, dateStd False, dateStr False, time False, timeStr False, meridian False

2016-06-09 09:32:10,877:DEBUG:parsedatetime:dayStr False, modifier False, modifier2 False, units True, qunits False

2016-06-09 09:32:10,877:DEBUG:parsedatetime:_evalString(30 days, time.struct_time(tm_year=2016, tm_mon=6, tm_mday=9, tm_hour=9, tm_min=32, tm_sec=10, tm_wday=3, tm_yday=161, tm_isdst=0))

2016-06-09 09:32:10,877:DEBUG:parsedatetime:_buildTime: [30 ][][days]

2016-06-09 09:32:10,877:DEBUG:parsedatetime:units days --> realunit days

2016-06-09 09:32:10,877:DEBUG:parsedatetime:return

2016-06-09 09:32:10,877:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2016-06-30 05:59:00 UTC.

2016-06-09 09:32:10,878:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...

2016-06-09 09:32:10,878:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache

2016-06-09 09:32:11,727:DEBUG:certbot.plugins.selection:Single candidate plugin: \* apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f8a7d298290>
Prep: True

2016-06-09 09:32:11,729:DEBUG:certbot.plugins.selection:Single candidate plugin: \* apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f8a7d298290>
Prep: True

2016-06-09 09:32:11,730:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f8a7d298290> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f8a7d298290>

2016-06-09 09:32:11,731:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/bbs.cybervalley.org.conf produced an unexpected error: 'EntryPoint' object has no attribute 'resolve'. Skipping.

2016-06-09 09:32:11,732:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 345, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)

  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 549, in obtain_cert
    le_client = _init_le_client(config, auth, installer)

  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 359, in _init_le_client
    acc, acme = _determine_account(config)

  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 323, in _determine_account
    accounts = account_storage.find_all()

  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 160, in find_all
    accounts.append(self.load(account_id))

  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 173, in load
    regr = messages.RegistrationResource.json_loads(regr_file.read())

  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 180, in json_loads
    return cls.from_json(loads)

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 297, in from_json
    return cls(**cls.fields_from_json(jobj))

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 288, in fields_from_json
    fields[slot] = field.decode(value)

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 92, in decode
    return self.fdec(value)

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 297, in from_json
    return cls(**cls.fields_from_json(jobj))

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 288, in fields_from_json
    fields[slot] = field.decode(value)

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 92, in decode
    return self.fdec(value)

  File "/usr/lib/python2.7/dist-packages/acme/jose/json_util.py", line 489, in from_json
    return type_cls(**type_cls.fields_from_json(jobj))

  File "/usr/lib/python2.7/dist-packages/acme/jose/jwk.py", line 226, in fields_from_json
    key = public_numbers.public_key(default_backend())

  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/**init**.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())

  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/**init**.py", line 22, in _available_backends
    "cryptography.backends"

AttributeError: 'EntryPoint' object has no attribute 'resolve'``

**Comment by bmw** [comment] 2016-06-10 19:30
How did you install `certbot`? According to pyca/cryptography#2838, the issue is do to an older version of `setuptools`.

**Comment by noccio** [comment] 2016-06-11 21:35
yes, the problem came from a mixed debian installation stable-testing: upgrading setuptool (python-setuptool package) to testing version (package version 20.10.1-1) certbot works normally.

Thanks a lot

**Comment by sbiella** [comment] 2016-08-30 12:36
Hi I still have the same problem, when I trying to renew the certificate, I got a:
AttributeError: 'EntryPoint' object has no attribute 'resolve'
but python-setuptools is 20.10.1-1.1~bpo8+1 and python-certbot is 0.8.1-2~bpo8+1
(debian8 with jessie-backports)

**Comment by sargue** [comment] 2016-09-23 12:39
I am experiencing this problem in Debian 8. Tried to install python-setuptools from testing as suggested in the [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825619) but same result.

This is what I get:

```
$ sudo certbot renew
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/vader.sargue.net.conf
-------------------------------------------------------------------------------
2016-09-23 09:54:57,923:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/vader.sargue.net.conf produced an unexpected error: 'EntryPoint' object has no attribute 'resolve'. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/vader.sargue.net/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
```

Package versions:

```
ii  certbot                     0.8.1-2~bpo8+1     all                automatically configure HTTPS using Let's Encrypt
ii  python-certbot-apache       0.8.1-1~bpo8+1     all                Apache plugin for Certbot
ii  python-setuptools           27.1.2-1           all                Python Distutils Enhancements
```

**Comment by bmw** [comment] 2016-09-23 17:40
My thought is the problem is mixed packages from PyPI and Debian. Any thoughts @hlieberman?

**Comment by hlieberman** [comment] 2016-09-23 22:46
I agree. This is definitely indicative of a mixed installation.

@sargue, if you run `python -d -c "import certbot"` it should spew out a ton of verbose output. In there, look for something starting with /usr/local/.

**Comment by sbiella** [comment] 2016-09-24 09:45
you info,
I've found a workaround, using the debian7 certbot wrapper, I can renew
the certificate without problem.

**Comment by sargue** [comment] 2016-09-24 10:38
@hlieberman that command outputs just nothing at all

```
sargue@sr:~$ python -d -c "import certbot"
sargue@sr:~$ sudo python -d -c "import certbot"
sargue@sr:~$
```

But your comment and @bmw 's one made me think that before using the debian packaged `certbot` I used in this computer the wrapper (back went it was `letsencrypt-auto`). So I'm checking the root home folder and I've found traces of python and pip packages.

```
/root/.cache/pip
/root/.local/share/letsencrypt/lib/python
```

I deleted it but the error remains.

Now trying the wrapper approched commented by @sbiella. I see from the output that is installing some python packages and creating a virtual python environment. That's probably the root cause?

And.... it worked!

This is the output:

```
root@sr:~# ./certbot-auto renew
Bootstrapping dependencies for Debian-based OSes...
Hit http://debian.mirrors.ovh.net jessie-backports InRelease
Ign http://debian.mirrors.ovh.net stable InRelease
Hit http://debian.mirrors.ovh.net stable-updates InRelease
Hit http://security.debian.org stable/updates InRelease
Hit http://security.debian.org testing/updates InRelease
Hit http://debian.mirrors.ovh.net stable Release.gpg
Hit http://debian.mirrors.ovh.net stable Release
Get:1 http://httpredir.debian.org jessie-backports InRelease [166 kB]
Get:2 http://httpredir.debian.org stable-updates InRelease [142 kB]
Get:3 http://debian.mirrors.ovh.net jessie-backports/main i386 Packages/DiffIndex [27.8 kB]
Ign http://httpredir.debian.org stable InRelease
Get:4 http://debian.mirrors.ovh.net jessie-backports/main Translation-en/DiffIndex [27.8 kB]
Get:5 http://debian.mirrors.ovh.net stable-updates/main i386 Packages/DiffIndex [5,440 B]
Hit http://debian.mirrors.ovh.net stable-updates/contrib i386 Packages
Get:6 http://debian.mirrors.ovh.net stable-updates/non-free i386 Packages/DiffIndex [736 B]
Hit http://debian.mirrors.ovh.net stable-updates/contrib Translation-en
Get:7 http://debian.mirrors.ovh.net stable-updates/main Translation-en/DiffIndex [2,704 B]
Get:8 http://debian.mirrors.ovh.net stable-updates/non-free Translation-en/DiffIndex [736 B]
Hit http://httpredir.debian.org stable Release.gpg
Hit http://security.debian.org stable/updates/main i386 Packages
Hit http://security.debian.org stable/updates/contrib i386 Packages
Hit http://security.debian.org stable/updates/non-free i386 Packages
Hit http://security.debian.org stable/updates/contrib Translation-en
Hit http://httpredir.debian.org stable Release
Hit http://security.debian.org stable/updates/main Translation-en
Hit http://security.debian.org stable/updates/non-free Translation-en
Hit http://security.debian.org testing/updates/main i386 Packages
Hit http://security.debian.org testing/updates/contrib i386 Packages
Hit http://security.debian.org testing/updates/non-free i386 Packages
Hit http://security.debian.org testing/updates/contrib Translation-en
Hit http://security.debian.org testing/updates/main Translation-en
Hit http://debian.mirrors.ovh.net stable/main i386 Packages
Hit http://debian.mirrors.ovh.net stable/contrib i386 Packages
Hit http://debian.mirrors.ovh.net stable/non-free i386 Packages
Hit http://debian.mirrors.ovh.net stable/contrib Translation-en
Hit http://debian.mirrors.ovh.net stable/main Translation-en
Hit http://debian.mirrors.ovh.net stable/non-free Translation-en
Hit http://security.debian.org testing/updates/non-free Translation-en
Get:9 http://httpredir.debian.org stable-updates/main i386 Packages/DiffIndex [5,440 B]
Get:10 http://httpredir.debian.org stable-updates/contrib i386 Packages [32 B]
Get:11 http://httpredir.debian.org stable-updates/non-free i386 Packages/DiffIndex [736 B]
Get:12 http://httpredir.debian.org stable-updates/contrib Translation-en [14 B]
Get:13 http://httpredir.debian.org stable-updates/non-free Translation-en/DiffIndex [736 B]
Get:14 http://httpredir.debian.org stable-updates/main Translation-en/DiffIndex [2,704 B]
Get:15 http://httpredir.debian.org jessie-backports/main i386 Packages/DiffIndex [27.8 kB]
Hit http://httpredir.debian.org stable/main i386 Packages
Get:16 http://httpredir.debian.org jessie-backports/main Translation-en/DiffIndex [27.8 kB]
Hit http://httpredir.debian.org stable/non-free i386 Packages
Hit http://httpredir.debian.org stable/contrib Translation-en
Hit http://httpredir.debian.org stable/main Translation-en
Hit http://httpredir.debian.org stable/non-free Translation-en
Hit http://httpredir.debian.org stable/contrib i386 Packages
Get:17 http://httpredir.debian.org jessie-backports/main i386 2016-09-24-0316.31.pdiff [841 B]
Get:18 http://httpredir.debian.org jessie-backports/main i386 2016-09-24-0316.31.pdiff [841 B]
Fetched 440 kB in 21s (20.5 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl-dev is already the newest version.
augeas-lenses is already the newest version.
augeas-lenses set to manually installed.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating virtual environment...
Installing Python packages...
Installation succeeded.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/vader.sargue.net.conf
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
new certificate deployed with reload of apache server; fullchain is
/etc/letsencrypt/live/vader.sargue.net/fullchain.pem
-------------------------------------------------------------------------------

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/vader.sargue.net/fullchain.pem (success)
```

Thanks everyone for the support.

**Comment by jpptinsley** [comment] 2016-11-10 13:09
+1 seeing this. Again swapping to the wrapper version was a functional workaround. 
`python -d -c "import certbot"` is giving me nothing as well.
Have `python-setuptools 20.10.1-1.1~bpo8+1` and certbot/python-certbot/python-certbot-apache `0.9.3-1~bpo8+1`

**Comment by olivierb2** [comment] 2017-05-11 20:16
I think this can be closed. If you get this error, just install python-certbot-nginx as certbot package doesn't support nginx without this additional package.

**Comment by jpptinsley** [comment] 2017-05-12 10:17
I'm not trying to use the nginx module, I'm trying to use certonly.

**Comment by bmw** [comment] 2019-02-07 18:55
This issue hasn't seen any updates in almost 2 years so I'm closing it. If people continue to have this issue, please comment or open a new issue.

**Closed by bmw** 2019-02-07 18:55 UTC
Labels: area: debian / ubuntu, more-info
