### ISSUE TITLE
The server experienced an internal error :: Error creating new authz with third-party MX 

### ISSUE THREAD

**Issue by Hirbod** [certbot/certbot#3912] opened 2016-12-14 14:54 UTC
Hi,

I've seen that this issue was supplied multiple times, but I don't have any idea how to fix this. My customer is using a third-party MX (Avira Cloud Anti-Vir) which scans mails for spam and viruses.

So the MX is not the same as the server-ip. Is there any way to get a cert for it nontheless?

```log
2016-12-14 14:45:13,539:DEBUG:certbot.main:Root logging level set at 30
2016-12-14 14:45:13,540:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-12-14 14:45:13,540:WARNING:certbot.cli:You are running with an old copy of letsencrypt-auto that does not receive updates, and is less reliable than more recent versions. We recommend upgrading to the latest certbot-auto script, or using native OS packages.
2016-12-14 14:45:13,540:DEBUG:certbot.main:certbot version: 0.8.1
2016-12-14 14:45:13,540:DEBUG:certbot.main:Arguments: ['-n', '--text', '--agree-tos', '--expand', '--authenticator', 'webroot', '--server', 'https://acme-v01.api.letsencrypt.org/directory', '--rsa-key-size', '4096', '--email', 'postmaster@shoptest.ingo-maurer.com', '--domains', 'shoptest.ingo-maurer.com', '--webroot-path', '/usr/local/ispconfig/interface/acme']
2016-12-14 14:45:13,540:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-12-14 14:45:13,540:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-12-14 14:45:13,542:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7efca0ebeb50>
Prep: True
2016-12-14 14:45:13,542:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7efca0ebeb50> and installer None
2016-12-14 14:45:13,613:DEBUG:certbot.main:Picked account: <Account(c0aff626febd7347ce66b64b844fbd6a)>
2016-12-14 14:45:13,613:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-12-14 14:45:13,615:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-12-14 14:45:13,826:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 352
2016-12-14 14:45:13,827:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '352', 'Expires': 'Wed, 14 Dec 2016 14:45:13 GMT', 'Boulder-Request-Id': 'T-GiogBNxAgq2JP0jzvdjM4VOrNoZmL3Qy0-JEZrQaE', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 14 Dec 2016 14:45:13 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '8tkth98x8Bh_Gl7HTfEnJzHLL3GPmCOCohE6lqEZiX4'}. Content: '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-12-14 14:45:13,828:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '352', 'Expires': 'Wed, 14 Dec 2016 14:45:13 GMT', 'Boulder-Request-Id': 'T-GiogBNxAgq2JP0jzvdjM4VOrNoZmL3Qy0-JEZrQaE', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 14 Dec 2016 14:45:13 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '8tkth98x8Bh_Gl7HTfEnJzHLL3GPmCOCohE6lqEZiX4'}): '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-12-14 14:45:13,845:DEBUG:root:Requesting fresh nonce
2016-12-14 14:45:13,845:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2016-12-14 14:45:14,034:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2016-12-14 14:45:14,035:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': '6JjY1kmugE_t9KdrAnGkwHAUXMjRyrxfH6Up531-uKw', 'Expires': 'Wed, 14 Dec 2016 14:45:14 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 14 Dec 2016 14:45:14 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'tmGekpF2VlHVnqA42-9adKcqGl0MyV-o2XmSQ8R3PW0'}. Content: ''
2016-12-14 14:45:14,035:DEBUG:acme.client:Storing nonce: '\xb6a\x9e\x92\x91vVQ\xd5\x9e\xa08\xdb\xefZt\xa7*\x1a]\x0c\xc9_\xa8\xd9y\x92C\xc4w=m'
2016-12-14 14:45:14,037:DEBUG:acme.jose.json_util:Omitted empty fields: status=None, combinations=None, expires=None, challenges=None
2016-12-14 14:45:14,037:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "shoptest.ingo-maurer.com"}, "resource": "new-authz"}
2016-12-14 14:45:14,041:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, alg=None, jku=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None, jwk=None
2016-12-14 14:45:14,048:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, nonce=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None
2016-12-14 14:45:14,048:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "tPMNdqCeVDJSCdmvA89VP0kOncK571QJ2IBwtCAV9FmiOBn7-MyRFeqYtwZ-69tWo-ytT2QLYZakclgSyUMxy08h8CH6esTkvY_M3-MtSOlPGhY0jzFvRHg9THVbvjJMilSiidHDyWTrVt3rT0BzUn53PpMiHWLG7QgxOWjiXSls0bEEFPjIgflVWJmbC6UoyCCShBC9AC7SVINUY3V4bMTB5LCeQmCp04nzwCNN3Bg7Rt3CrhVYzP1-nuWczyP8b2dL-p-cO_-M2bzBPnLGrm7O9c-JqeJzp3hlZuE2x3gQd0TxTE86Fi6oXd1RHRtyYU85C8ZNAMX4ZrV10ky1S8tducNYb-QaK9uZ1CrpZ0eiRY7Cr4uF46ThNMs4vVnskMpcAYOLwqhS2ZBqejdVEZBj9HBY-St6_7vQlEYgXTxlVPYhuOMISNUBP5kEcO2PCHxmmmuYfqqxBaMtkU4R8Gxx3sOGnGoQIbXW7q1dOcIyTM4q0yfGzG0l0OyFTHvC0iuJEEKsS9J_Vp82XMrOtPnhmUNF_bNjZ2peJ1rp4Qz0g2JWQ2RlzOUBglLeizGdM-xcWETHqZ1Wz9iDKolnElYp2nd9RHse4coRgXmEo-f3WXRQqNb1xboq2mH_nHHyQkg5IVC0HIrkzeAlTGcvZlUF7wBLArJz5AjcZpu-MPU"}}, "protected": "eyJub25jZSI6ICJ0bUdla3BGMlZsSFZucUE0Mi05YWRLY3FHbDBNeVYtbzJYbVNROFIzUFcwIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJzaG9wdGVzdC5pbmdvLW1hdXJlci5jb20ifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "deajV4RJUV_qqD6fy6dZWwC6KVtb-colkaDpVC7Gv0rPwo7HsGPBIIhQ7MU9GJV3dOJOcuP4ho9eubP9nT8JzViBgPtnuedm4gATvt5ll2XDt2mEe_6sn2RfeCGZe9GhE9Z2tGabkJF9oqM7Vog9Pnn48CMbKth1Dk2h00izaPokKLdjQAzmgAHgAQx5D9u6ZnfQANM200zxhXx3X0-E_ZF59CRuZccDepyPXHj74dlOV_40WJX1EStpBVDSMOUp-FjX_TuZEbrtAdja8RnygP3acOJ1T0KPOsqliFd8i3CK2j9CgAg-Age-2Gum7sXirTwyKyosTC5MiwfeT_Y3q-TUSpMbZazLXHZi9CAJbQWGaFHsSDc9361wYx-6Jqwhbaeml6et1rRxTmkoilIpkq76KY1nPNdZST3-HuRSqGr7Lk6ha-JjHbieL9NDSRRDh_Oe3Ud6BjnCtuA0R29T2ImEeBf6rzCspCzKlHxjuIXgNscEeJTSXlOQFqeVaQjmwk4YHr5ICkPwhN3cYcWABIGbgv2jmW7w3jMdjzdGWHm2j-4hT80Xq-8bRw7IjtxRdvOJ7TXz5CTvrlkhB6639WqRK6fEksmyx769CfgmsO313s6za5RSMOxJSbktVDvdPD-Z84ZD9wyzJ_AjeArdOoSejx00P9oEZvmBA1hXKL0"}'}
2016-12-14 14:45:20,273:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 500 102
2016-12-14 14:45:20,276:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '102', 'Boulder-Request-Id': 'tODs8rN3PQr7ZM9reJ3dgNmjbk1M0_lkXFz-yiDSjYk', 'Expires': 'Wed, 14 Dec 2016 14:45:20 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '3141979', 'Date': 'Wed, 14 Dec 2016 14:45:20 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '8xPRgtINVhJ50B3JFjCAumAezHElrpf1Ob14eLYC87M'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new authz",\n  "status": 500\n}'
2016-12-14 14:45:20,277:DEBUG:acme.client:Storing nonce: '\xf3\x13\xd1\x82\xd2\rV\x12y\xd0\x1d\xc9\x160\x80\xba`\x1e\xccq%\xae\x97\xf59\xbdxx\xb6\x02\xf3\xb3'
2016-12-14 14:45:20,278:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '102', 'Boulder-Request-Id': 'tODs8rN3PQr7ZM9reJ3dgNmjbk1M0_lkXFz-yiDSjYk', 'Expires': 'Wed, 14 Dec 2016 14:45:20 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '3141979', 'Date': 'Wed, 14 Dec 2016 14:45:20 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '8xPRgtINVhJ50B3JFjCAumAezHElrpf1Ob14eLYC87M'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new authz",\n  "status": 500\n}'
2016-12-14 14:45:20,279:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 94, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 276, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 64, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 217, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 197, in request_challenges
    new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 656, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 572, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new authz
```

**Comment by pde** [comment] 2016-12-19 22:48
I don't think this was caused by or related to your customer's email address. Thoughts @cpu @rolandshoemaker @jsha ?

**Comment by jsha** [comment] 2016-12-19 22:56
I agree this probably isn't caused by your customer's MX. Could you re-post with details on https://community.letsencrypt.org/ for more detailed discussion with a broader audience? Thanks!

**Comment by bmw** [comment] 2019-01-03 22:44
This hasn't seen any updates since 2016 so I'm closing this issue.

**Closed by bmw** 2019-01-03 22:44 UTC
Labels: area: boulder
