### ISSUE TITLE
Option to exclude options-ssl-nginx.conf

### ISSUE THREAD

**Issue by PatrickHeppler** [certbot/certbot#574] opened 2015-06-30 13:36 UTC
If one has already setup SSL the letsencrypt options-ssl-nginx.conf will prevent nginx restart.
In my case it's the ssl_session_cache which is already defined in my config.

**Comment by kuba** [comment] 2015-06-30 14:37
Duplicate of #543?

**Comment by diracdeltas** [comment] 2015-06-30 17:36
The letsencrypt configurator assumes you are starting from a config that doesn't support SSL; thinking about this more, it would be useful to have an option that essentially says, "I have set up SSL but just want to use a cert from letsencrypt." (As opposed to having options-ssl-nginx.conf overwrite the existing SSL configuration, which is the other way to fix the nginx restart bug.)

**Comment by PatrickHeppler** [comment] 2015-06-30 18:00
I think a lot of people will be "switchers" which already have ssl. 

Sent from Nine

Von: Yan Zhu <notifications@github.com>
Gesendet: 30.06.2015 19:37
An: letsencrypt/letsencrypt
Cc: PatrickHeppler
Betreff: Re: [letsencrypt] Option to exclude options-ssl-nginx.conf (#574) 

The letsencrypt configurator assumes you are starting from a config that doesn't support SSL; thinking about this more, it would be useful to have an option that essentially says, "I have set up SSL but just want to use a cert from letsencrypt." (As opposed to having options-ssl-nginx.conf overwrite the existing SSL configuration, which is the other way to fix the nginx restart bug.)

---

**Comment by jdkasten** [comment] 2015-09-11 18:02
Trying to cleanup the repo: Does anyone know if this has been fixed?

For reference, the Apache plugin will just edit the cert/key parameters if HTTPS is already deployed.

**Comment by jsha** [comment] 2015-10-14 21:55
Pretty sure this is still an issue.

One approach would be to parse whatever's in the options-ssl-nginx.conf and compare them to the virtualhost being ssl-enabled. If there are any conflicts, we could either (a) leave out the include or (b) ask whether to remove the conflicting entries.

**Comment by 0xPoly** [comment] 2015-10-26 08:57
@jdkasten could you please point me to where the apache HTTPS deployment detection logic is located?

**Comment by jdkasten** [comment] 2015-10-26 09:04
This is orthogonal to the original issue.  I assume you mean which virtual host the plugin should operate on?  That would be here... https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L238

Note... it could still use some refinement.

**Comment by 0xPoly** [comment] 2015-10-26 10:18
>either (a) leave out the include or (b) ask whether to remove the conflicting entries

@jsha I think option (a) would be better for usability, however, I'm worried that letsencrypt cloud retain (for example) an insecure cipher list.

> option that essentially says, "I have set up SSL but just want to use a cert from letsencrypt."

@diracdeltas could this be automated? letencrypt-nginx would only copy over `options-ssl-nginx.conf` if no SSL-enabled vhosts are found before installation.

**Comment by aprescott** [comment] 2015-12-04 03:55
I think this is the source of weirdness I'm seeing with v0.1.0.

I have `/etc/nginx/nginx.conf` which has these sections in its `http {}` (among other configuration):

```
ssl_prefer_server_ciphers   on;
ssl_ciphers  DEFAULT:!aNULL:!eNULL:!ADH:!RC4:!RC2:!DES:+HIGH:+MEDIUM:!LOW:!SSLv2:!EXP:!MD5:!DSS:!PSK;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

(Note this existing configuration is a default in a `http {}` block in `/etc/nginx/nginx.conf`, not specific to any individual `server {}`.)

It then uses

```
include sites-enabled/*.conf;
```

to pull in `/etc/nginx/sites-enabled/example.com.conf`, which defines an existing SSL-enabled server:

```
server {
  server_name www.example.com;
  rewrite ^ https://example.com$request_uri? permanent;
}

server {
  # ...

  listen 443 ssl spdy;
  server_name example.com;

  ssl                  on;
  ssl_certificate      ssl/foo-cert.pem;
  ssl_certificate_key  ssl/foo-key.key;

  ssl_session_cache    shared:SSL:5m;
  ssl_session_timeout  5m;
  # ...
}
```

After accounting for #921 (which causes problems because of the `ssl_session_cache`) I found that `letsencrypt --nginx -d example.com` will correctly update the `example.com.conf` file to have the correct `ssl_certificate` and `ssl_certificate_key` values. It _doesn't_, however, seem to include `options-ssl-nginx.conf` anywhere. (Before touching anything to do with `letsencrypt`, I did a `git init .` in my `/etc/nginx` directory, which has let me `git diff` on the file changes.)

I'm not sure what I was expecting, though. I guess I thought that the `server {}` block in `example.com.conf` would get the `include options-ssl-nginx.conf`. Does that override the SSL configuration for _only_ `https://example.com`, and leave the `/etc/nginx/nginx.conf` default? Is that actually expected because of `-d example.com`?

**Comment by aprescott** [comment] 2015-12-04 03:57
Actually, sorry, that might be a different thing. Should I open a new issue?

**Comment by jsha** [comment] 2015-12-04 07:03
@aprescott: That is an interesting, and a surprising result! I think it differs from this issue. A new issue would be great!

**Comment by aprescott** [comment] 2015-12-04 15:30
:+1: opened #1743.

**Comment by pde** [comment] 2016-01-09 00:47
This is closely related to #1123.

**Comment by pde** [comment] 2016-01-09 00:50
Probably ciphersuite tuning should change from being an implicit behaviour of plugins to being a security enhancement with its own cli flag, even if that enhancement is turned on in both "Easy" and "Secure" modes.

**Closed** 2016-08-18 21:11 UTC
Labels: nginx
