### ISSUE TITLE
Nginx restoring older backups than it should 

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#940] opened 2015-10-10 18:54 UTC
Bug #921 keeps coming back to plague me. When I first ran Nginx, I had an /etc/nginx/conf.d/ssl.conf with the directive:

`ssl_session_cache shared:SSL:10m;`

However, as documented in #921, that causes a conflict with Nginx's own configuration. We should fix this conflict, but this bug is about another issue: My ssl.conf keeps getting overwritten with that original version.

I edited /etc/nginx/conf.d/ssl.conf to comment out the ssl_session_cache line, and next time I run the letsencrypt client, the line becomes uncommented.

It seems like I have a copy of ssl.conf stuck in /var/lib/letsencrypt/IN_PROGRESS/ssl.conf_2, and on each run that copy gets written to /etc/nginx/conf.d/ssl.conf before the restart for DVSNI. That causes a failure to restart, and the challenge fails.

**Comment by olabini** [comment] 2016-01-26 17:31
AFAICT from the code, this is something that happens based on the Reverter, not the Nginx plugin - and there have been many changes to it since Oct 10. Do you still see this behavior with the current version?

**Comment by jsha** [comment] 2016-01-26 20:43
I haven't verified recently. At the time I filed this bug, the Nginx plugin would `sys.exit()` if there was a config problem, and I changed it to raise a MisconfigurationException instead. That may have triggered the proper reverter code.

It should be easy to test by messing up one of the directives inserted by the nginx plugin so it becomes invalid. The see if /var/lib/letsencrypt/IN_PROGRESS exists after a run.

**Comment by iapazmino** [comment] 2016-01-26 21:58
we have tried to reproduce this error and was not possible.
I think this issue should be closed.

**Comment by Danpiel** [comment] 2016-03-14 10:07
Removing /var/lib/letsencrypt/IN_PROGRESS after failed config_emerge fixes issue

**Comment by pde** [comment] 2016-06-25 00:09
bmw: if this wasn't addressed in #3204, want to take it?

**Comment by bmw** [comment] 2016-06-27 19:50
This has been resolved. I removed the "has PR" label because I wanted to investigate and test before closing the issue. In the form described above, this issue was resolved by #814. In a more extreme case, the error is still possible due to #1456, but its enough of a pathological case that I feel comfortable closing this issue.

To provide more details, what occurred when this issue was written was the Nginx plugin raised an exception due to #921, however, due to issue #395, the client didn't rollback changes it made to your configuration. This is the piece that was resolved by #814. The client now catches all exceptions and most fatal signals to roll back your configuration before exiting, avoiding this issue.

Why wouldn't the client rollback your configuration? Great question Brad. When this issue was written, this always happened if the plugin had a problem, but now it could happen if the client raised an exception while rolling back your config (there's no known issue) or a signal like SIGINT or SIGKILL interrupted the error handler. While this later case is certainly possible, there is only so much we can do to stop the user from shooting themselves in the foot. Based on recent discussion with Peter, I opened #3215 to look into this issue.

With all that said, suppose the client failed to rollback your configuration. In this case, the client has a backup that it failed to restore saved on disk. The next time the client runs, it will attempt to restore this backup. If the user makes changes to their config before running the client again, however, these changes will be lost as described in #1456. I made #3216 to track the general issue of whether or not we should automatically attempt to restore backups if we previously failed to do so.

Despite just describing scenarios where the problem identified here can still happen, it only occurs in pathological cases and the problem is resolved when following the steps outlined in the original post. I'm closing this issue in favor of #3215 and #3216 which specifically address the pathological cases so they can be discussed and resolved on a more general level.

**Closed by bmw** 2016-06-27 19:50 UTC
Labels: nginx
