### ISSUE TITLE
When installing certbot-dns-cloudflare through pip, argparse.ArgumentError occurs

### ISSUE THREAD

**Issue by enugentdt** [certbot/certbot#7633] opened 2019-12-07 03:59 UTC
## My operating system is (include version): 
Mac OS X 10.14
## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
pip
## I ran this command and it produced this output:
`certbot renew`

```
An unexpected error occurred:
argparse.ArgumentError: argument --webroot-path/-w: conflicting option string: -w
Please see the logfile '/var/folders/tp/gcrtlv2s0cs_m5fvc5c67k8r0000gn/T/tmp7s2e2beg/log' for more details.
```

## Certbot's behavior differed from what I expected because:
Well, theoretically, this shouldn't crash on a fresh install.

## Here is a Certbot log showing the issue (if available):
```
019-12-06 22:53:06,334:DEBUG:certbot._internal.main:certbot version: 1.0.0
2019-12-06 22:53:06,335:DEBUG:certbot._internal.main:Arguments: []
2019-12-06 22:53:06,335:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#-:dns-cloudflare,PluginEntryPoint#-ertbot-dns-cloudflare:dns-cloudflare,PluginEntryPoint#-ertbot:manual,PluginEntryPoint#-ertbot:null,PluginEntryPoint#-ertbot:standalone,PluginEntryPoint#-ertbot:webroot,PluginEntryPoint#dns-cloudflare,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-12-06 22:53:06,359:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/space/Library/Python/3.7/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/main.py", line 14, in main
    return internal_main.main(cli_args)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/main.py", line 1327, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/cli.py", line 1243, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/cli.py", line 1456, in _plugins_parsing
    helpful.add_plugin_args(plugins)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/cli.py", line 832, in add_plugin_args
    plugin_ep.plugin_cls.inject_parser_options(parser_or_group, name)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/plugins/common.py", line 82, in inject_parser_options
    return cls.add_parser_arguments(add)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/plugins/webroot.py", line 51, in add_parser_arguments
    help="public_html / webroot path. This can be specified multiple "
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/plugins/common.py", line 81, in add
    *args, **kwargs)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/cli.py", line 313, in add_argument
    self._parser.add(self._topic, *args, **kwargs)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/certbot/_internal/cli.py", line 762, in add
    self.parser.add_argument(*args, **kwargs)
  File "/Users/space/Library/Python/3.7/lib/python/site-packages/configargparse.py", line 889, in add_argument
    action = self.original_add_argument_method(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --webroot-path/-w: conflicting option string: -w
2019-12-06 22:53:06,359:ERROR:certbot._internal.log:An unexpected error occurred:
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not applicable

I'm honestly tearing my hair out - I've uninstalled and reinstalled it probably twenty times, through pip, pip3, and brew, at least twice on each. This issue occurs only when I install certbot-dns-cloudflare, though, not when I have just plain certbot installed.

Thanks!

**Comment by alexzorin** [comment] 2019-12-07 08:00
>Well, theoretically, this shouldn't crash on a fresh install.

Is this in a truly fresh install, or do you have an existing `/etc/letsencrypt/` directory with data in it? Do you have any files in `/etc/letsencrypt/renewal/`, and if so, could you include their contents in the issue?

**Comment by Tugzrida** [comment] 2019-12-10 14:02
Do you have any active certificates on that machine? If it’s a completely clean install then `certbot renew` won’t do anything anyway. I’ll try and replicate tomorrow.

**Comment by enugentdt** [comment] 2019-12-10 20:36
I admit, I do have active certificates on the machine. However, I can't even run `certbot` without the issue appearing, nevermind `certbot renew`. I looked through the source to try to understand where the issue might be coming from, but couldn't really find anything obvious.

**Comment by alexzorin** [comment] 2019-12-10 20:55
I was also unable to reproduce it a few days ago.

What might help is trial-and-error to identify which `/etc/letsencrypt/renewal/*.conf` file causes the crash (if any, but I suspect there is one). For example, by trying `certbot renew` when only one file at a time is present.

If it exists `/etc/letsencrypt/cli.ini` may contain a hint too.

**Comment by Tugzrida** [comment] 2019-12-11 03:08
Is the error when running `certbot` with no args the same as above?

If yes, do there happen to be any `webroot` options in `/etc/letsencrypt/cli.ini`?

**Comment by enugentdt** [comment] 2019-12-11 03:54
The error is when running `certbot` with no args

Unfortunately, I don't have an `/etc/letsencrypt/cli.ini` file. Granted, I am on OS X at the moment, but I can give this a shot on other platforms

**Comment by Tugzrida** [comment] 2019-12-11 11:19
I just tested on OSX and can't seem to replicate the issue so it's likely specific to your machine.

Could you please also give the output of:
- `pip -V`
- `type certbot`

I was only interested in `cli.ini` in case that weird webroot option was set there.

Looking at that error trace a bit more, it almost looks like multiple python installs are crossing over. What you may need to do is making a backup of any live certificates you need, temporarily pointing your server software to the backup location, then finding and deleting all folders and files to do with `certbot` or `letsencrypt`, then re-installing and re-issuing your certs.

**Comment by bmw** [comment] 2019-12-12 22:16
Unfortunately [we don't officially support installations through pip](https://certbot.eff.org/docs/install.html#installing-from-source) because of the many possible pitfalls and the Certbot package in Homebrew doesn't offer the DNS plugins (see https://github.com/certbot/certbot/issues/5680 for a discussion of that issue and the various attempts to add this feature to Homebrew).

For that reason, I'm closing this issue. If you want additional help to get Certbot working in this way, you can try posting to https://community.letsencrypt.org where there is a large community of people familiar with the project and server administration that may be able to help.

If you want to use our DNS plugins in a way supported by the Certbot team, you can [run them in Docker](https://certbot.eff.org/docs/install.html#running-with-docker).

**Closed by bmw** 2019-12-12 22:16 UTC

**Comment by ntwrick** [comment] 2020-06-18 19:53
Just encountered this same issue with a new install of certbot from git. I found that pip left an incomplete `cd certbot && pip install -U -e .` in site-packages with the names `\~ertbot*`. You can see them with `cd /path/to/site-packages && ll \~ertbot*`.  Remove these directories and you're good to reinstall without the extra phantom `-ertbot:webroot` plugins that are overloading the `argparse -w` arguments.

**Comment by Moonzie** [comment] 2020-10-30 23:13
LP BBB still 
 M
