### ISSUE TITLE
Cannot locate wrapped file

### ISSUE THREAD

**Issue by sharok** [certbot/certbot#4356] opened 2017-03-16 08:38 UTC
## My operating system is (include version):
 Ubuntu 14.04.5 LTS
Welcome to the Bitnami MEAN 3.2.9-0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto

## I ran this command and it produced this output:
I have two AWS machines, they were created from one image. The first machine works fine, but the second one doesn't. 
I get error on every command:
> Cannot locate wrapped file 

For example:  `sudo ./certbot-auto certificates -v`

> Bootstrapping dependencies for Debian-based OSes...
> Ign http://us-east-1.ec2.archive.ubuntu.com trusty InRelease
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates InRelease
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports InRelease
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release.gpg
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release
> Ign http://dl.google.com stable InRelease
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Sources
> Hit http://security.ubuntu.com trusty-security InRelease
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted amd64 Pack                       ages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packag                       es
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse amd64 Pack                       ages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse Translatio                       n-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted Translatio                       n-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-                       en
> Hit http://security.ubuntu.com trusty-security/main Sources
> Hit http://dl.google.com stable Release.gpg
> Hit http://security.ubuntu.com trusty-security/universe Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe Sources
> Hit http://dl.google.com stable Release
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main amd64 Packages
> Hit http://security.ubuntu.com trusty-security/main amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted amd64 Pa                       ckages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe amd64 Pack                       ages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse amd64 Pa                       ckages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main Translation-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse Translat                       ion-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted Translat                       ion-en
> Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe Translatio                       n-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse Sources
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main amd64 Packages
> Hit http://security.ubuntu.com trusty-security/main Translation-en
> Hit http://security.ubuntu.com trusty-security/universe Translation-en
> Hit http://ppa.launchpad.net trusty InRelease
> Hit https://apt-mo.trafficmanager.net trusty InRelease
> Hit http://dl.google.com stable/main amd64 Packages
> Hit https://apt-mo.trafficmanager.net trusty/main amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages
> Get:1 https://apt-mo.trafficmanager.net trusty/main Translation-en_US
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse amd64 Packages
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Translation-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse Translation-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted Translation-en
> Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Translation-en
> Ign https://apt-mo.trafficmanager.net trusty/main Translation-en_US
> Ign https://apt-mo.trafficmanager.net trusty/main Translation-en
> Hit http://ppa.launchpad.net trusty InRelease
> Ign http://us-east-1.ec2.archive.ubuntu.com trusty/main Translation-en_US
> Ign http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse Translation-en_US
> Ign http://us-east-1.ec2.archive.ubuntu.com trusty/restricted Translation-en_US
> Ign http://us-east-1.ec2.archive.ubuntu.com trusty/universe Translation-en_US
> Hit http://ppa.launchpad.net trusty/main amd64 Packages
> Hit http://ppa.launchpad.net trusty/main Translation-en
> Hit http://ppa.launchpad.net trusty/main amd64 Packages
> Ign http://dl.google.com stable/main Translation-en_US
> Hit http://ppa.launchpad.net trusty/main Translation-en
> Ign http://dl.google.com stable/main Translation-en
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> gcc is already the newest version.
> python is already the newest version.
> python-dev is already the newest version.
> augeas-lenses is already the newest version.
> ca-certificates is already the newest version.
> libaugeas0 is already the newest version.
> libffi-dev is already the newest version.
> libssl-dev is already the newest version.
> openssl is already the newest version.
> python-virtualenv is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.
> Creating virtual environment...
> Running virtualenv with interpreter /opt/bitnami/python/bin/python2.7
> PYTHONHOME is set.  You *must* activate the virtualenv before using it
> New python executable in /home/bitnami/.local/share/letsencrypt/bin/python2.7
> Also creating executable in /home/bitnami/.local/share/letsencrypt/bin/python
> Cannot locate wrapped file
> ERROR: The executable /home/bitnami/.local/share/letsencrypt/bin/python2.7 is no                       t functioning
> ERROR: It thinks sys.prefix is u'/home/bitnami' (should be u'/home/bitnami/.loca                       l/share/letsencrypt')
> ERROR: virtualenv is not compatible with this system or executable

**Comment by bmw** [comment] 2017-03-21 18:13
So I'm not familiar with Bitnami, but the problem is `virtualenv` isn't working properly on your system. This [forum thread](https://community.bitnami.com/t/some-questions-about-bitnami-django-stack-1-8-2-in-aws/31783) might be useful to you.

**Comment by bmw** [comment] 2019-02-07 18:49
This issue hasn't seen any updates in almost 2 years so I'm closing it. If you're still having problems, please comment or open a new issue.

**Closed by bmw** 2019-02-07 18:49 UTC
Labels: area: certbot-auto, area: debian / ubuntu, area: pip
