### ISSUE TITLE
Loss of webroot_map config when running certbot certonly --webroot --webroot-path

### ISSUE THREAD

**Issue by arosl** [certbot/certbot#7499] opened 2019-11-04 21:46 UTC
## My operating system is (include version):
Ubuntu 16.04.6 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

## I ran this command and it produced this output:
(I have redacted the actual domain names and account hash)
```
clsaro@web01:/etc/letsencrypt/renewal$ cat removed.com.conf
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/removed.com
cert = /etc/letsencrypt/live/removed.com/cert.pem
privkey = /etc/letsencrypt/live/removed.com/privkey.pem
chain = /etc/letsencrypt/live/removed.com/chain.pem
fullchain = /etc/letsencrypt/live/removed.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
account = x
server = https://acme-v01.api.letsencrypt.org/directory
post_hook = /bin/systemctl restart apache2
[[webroot_map]]
www.removed.com = /var/www/html
removed.com = /var/www/html
clsaro@web01:/etc/letsencrypt/renewal$ sudo certbot certonly --webroot --webroot-path /var/www/html -d removed.com -d www.removed.com -d removed.com.mx -d www.removed.com.mx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/removed.com.conf)

It contains these names: removed.com, www.removed.com

You requested these names for the new certificate: removed.com,
www.removed.com, removed.com.mx, www.removed.com.mx.

Do you want to expand and replace this existing certificate with the new
certificate?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(E)xpand/(C)ancel: E
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for removed.com.mx
http-01 challenge for www.removed.com.mx
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
- Congratulations! Your certificate and chain have been saved at:
/etc/letsencrypt/live/removed.com/fullchain.pem
Your key file has been saved at:
/etc/letsencrypt/live/removed.com/privkey.pem
Your cert will expire on 2020-02-02. To obtain a new or tweaked
version of this certificate in the future, simply run certbot
again. To non-interactively renew *all* of your certificates, run
"certbot renew"
- If you like Certbot, please consider supporting our work by:

Donating to ISRG / Let's Encrypt: https://letsencrypt.org/donate
Donating to EFF: https://eff.org/donate-le

clsaro@web01:/etc/letsencrypt/renewal$ cat removed.com.conf
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/removed.com
cert = /etc/letsencrypt/live/removed.com/cert.pem
privkey = /etc/letsencrypt/live/removed.com/privkey.pem
chain = /etc/letsencrypt/live/removed.com/chain.pem
fullchain = /etc/letsencrypt/live/removed.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
account = x
server = https://acme-v01.api.letsencrypt.org/directory
webroot_path = /var/www/html,
[[webroot_map]]
www.removed.com.mx = /var/www/html
removed.com.mx = /var/www/html

...

clsaro@web01:~$ sudo certbot certonly --webroot --webroot-path /var/www/html -d removed.com -d www.removed.com -d removed.com.mx -d www.removed.com.mx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/removed.com.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/removed.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/removed.com/privkey.pem
   Your cert will expire on 2020-02-02. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

clsaro@web01:~$ cat /etc/letsencrypt/renewal/removed.com.conf
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/removed.com
cert = /etc/letsencrypt/live/removed.com/cert.pem
privkey = /etc/letsencrypt/live/removed.com/privkey.pem
chain = /etc/letsencrypt/live/removed.com/chain.pem
fullchain = /etc/letsencrypt/live/removed.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
account = x
server = https://acme-v01.api.letsencrypt.org/directory
webroot_path = /var/www/html,
[[webroot_map]]
clsaro@web01:~$
```

## Certbot's behavior differed from what I expected because:
The command removed my already configured webroot_map config and replaced it with ONLY the new domains thus removing the update config for the original domains for this cert. Forcing the command to run a second time removed all webroot_map config.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring
:

**Comment by arosl** [comment] 2019-11-05 00:47
Possible a dup of  #7048

**Comment by bmw** [comment] 2019-11-08 00:33
Yeah I think this is a duplicate of #7048 and due to #6770. I'm hoping we can resolve #6770 soon. (If you know anyone who is experienced with Ubuntu packaging and would like to help, please let me know!)

**Closed by bmw** 2019-11-08 00:33 UTC
