### ISSUE TITLE
Generated certificates doesn't respect given order anymore, affecting Canonical Name

### ISSUE THREAD

**Issue by silverkorn** [certbot/certbot#9659] opened 2023-04-05 17:14 UTC
## My operating system is (include version):
Windows 10 using Docker & `certbot/certbot:latest` 
(certbot --version -> certbot **2.5.0**)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Docker

## I ran this command and it produced this output:
```
certbot
  -d 'company.com,*.company.com'
  -d 'adivision.com,*.adivision.com'
  -d 'bdivision.com,*.bdivision.com'
  -d 'cdivision.com,*.cdivision.com'
  --manual
  --non-interactive
  --manual-auth-hook "bin/hooks/authenticator.sh"
  --manual-cleanup-hook "bin/hooks/cleanup.sh"
  --deploy-hook "bin/hooks/deploy.sh"
  --preferred-challenges dns
  --key-type rsa
  --agree-tos
  --email "webmaster@company.com"
certonly
```

## Certbot's behavior differed from what I expected because:
Certbot was respecting the given domain list order from the command line arguments when generating the certificates so "**company.com**" was the first name set and appeared first in the certificate as the main CN.

Now, it sorts the given list by it's own, putting "***.adivision.com**" as the certificate's main CN.

The last proper certificate was generated on January 30th 2023 using **certbot/certbot:latest** (certbot 2.2.0).

**Comment by alexzorin** [comment] 2023-04-05 22:24
Duplicate of #9543.

**Closed by alexzorin** 2023-04-05 22:24 UTC
