### ISSUE TITLE
[Question] Plugins without weird namespacing

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#6066] opened 2018-06-04 03:11 UTC
Checked out master w/ venv to try see how plugins are developed.

Following the [instructions here](https://certbot.eff.org/docs/contributing.html#writing-your-own-plugin) for installing the example plugin, `certbot plugins` results in:

```
* certbot-example-plugins:example_authenticator
Description: Example Authenticator plugin
Interfaces: IAuthenticator, IPlugin
Entry point: example_authenticator = certbot_example_plugins:Authenticator

* certbot-example-plugins:example_installer
Description: Example Installer plugin
Interfaces: IInstaller, IPlugin
Entry point: example_installer = certbot_example_plugins:Installer
```

which means you have to use `-a certbot-example-plugins:example_installer`, `--certbot-example-plugins:example_installer-confoption blah` etc.

What I should be able to do is just use `-a example_authenticator`, right?

This effect also happens against my own plugin which I stick in a directory at the root of the repo.

I can't figure out why this is happening or how to tune `setup.py` to stop the prefixing from happening like with the plugins that ship with the repo.

Any hints?

Thanks!

**Comment by schoen** [comment] 2018-06-04 23:26
@bmw, could you comment on this issue?

**Comment by bmw** [comment] 2018-06-04 23:37
Unfortunately, there is no way for 3rd party plugins to change it as this was done by design, however, I want to change it. See #4351. I think that issue captures your problem here so I'm going to close this in favor of it, however, if you think I'm missing something, please comment and I'll reopen.

**Closed by bmw** 2018-06-04 23:37 UTC
Labels: area: 3rd party, area: documentation

**Comment by alexzorin** [comment] 2018-06-04 23:43
Neat.

For future visitors: adding the plugin to `PREFIX_FREE_DISTRIBUTIONS` in `disco.py` is the mechanism.
