### ISSUE TITLE
--post-hook runs always? Way to only run if renewal was successful

### ISSUE THREAD

**Issue by Flow86** [certbot/certbot#3047] opened 2016-05-21 08:24 UTC
Hi,

the pre/post-hook seems to run always.

sometimes an option to "only run if somethings changed" would be nice:

current behaviour:

```
# ./certbot-auto renew --rsa-key-size 4096 --webroot --webroot-path /srv/www  --post-hook /root/bin/certbot-posthook
The following certs are not due for renewal yet:
  /etc/letsencrypt/live/mydomain.com/fullchain.pem (skipped)
No renewals were attempted.
... Posthook run here ...
```
any way to not run the hooks if renewal was not successful?

**Comment by schoen** [comment] 2016-05-21 20:58
Duplicate of #2984 (fixed in forthcoming release by #2992).

**Closed by schoen** 2016-05-21 20:58 UTC
