### ISSUE TITLE
allow for java keystore as output format ".jks"

### ISSUE THREAD

**Issue by ralfhauser** [certbot/certbot#5212] opened 2017-10-30 10:53 UTC
## My operating system is (include version):
Debian stable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yes

Manually, I use openssl to convert the pem into a .pfx / .p12 and then I import it manually with
http://keystore-explorer.org/ into a java keystore

Goal: if java is installed, the certbot should offer to do this automatically

**Comment by bmw** [comment] 2017-10-30 19:48
This is very closely related to #506 and #1701.

**Comment by schoen** [comment] 2018-09-25 00:33
I'll consider this a duplicate of #1701.

**Closed by schoen** 2018-09-25 00:33 UTC
Labels: feature request
