### ISSUE TITLE
Unable to renew certificate using DNS-01

### ISSUE THREAD

**Issue by adrianmihalko** [certbot/certbot#5308] opened 2017-12-07 20:21 UTC
I have obtained letsencrypt certificate using DNS-01 (because my server is not availalbe at :80, :443) , but now I am unable to renew it: 

## My operating system is (include version):

Ubuntu 17.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

OS package manager

## I ran this command and it produced this output:

sudo certbot renew

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
$ sudo certbot renew
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.21.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/x.y.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',)
Attempting to renew cert (x.y.com) from /etc/letsencrypt/renewal/x.y.com.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/x.y.com/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/x.y.com/fullchain.pem (failure)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)
```

My /etc/letsencrypt/renewal/x.y.com.conf:

```
# renew_before_expiry = 30 days
version = 0.17.0
archive_dir =
cert = 
privkey =
chain =
fullchain = 

# Options used in the renewal process
[renewalparams]
authenticator = manual
installer = None
account = 
pref_challs = dns-01,
manual_public_ip_logging_ok = True
```

How can I renew my current certificate?

**Comment by SwartzCr** [comment] 2017-12-07 23:51
Ew, this looks like a python dependency issue, can you share with me the outputs of:
`pip freeze`
`certbot --version`
`dpkg -l | grep python` 
If the output of the last command is too verbose you could share the output of:
`dpkg -l | grep 'python.*urll\|python.*req\|python.*char'`

**Comment by josph2001** [comment] 2017-12-28 09:37
It seems, I'm facing the same issue. But my system hasn't installed `pip` yet.

Here is the output of the other two commands:   
```
# certbot --version
certbot 0.19.0

# # dpkg -l | grep 'python.*urll\|python.*req\|python.*char'
ii  python-chardet                             3.0.4-1+ubuntu16.04.1+certbot+2              all          universal character encoding detector for Python2
ii  python-ndg-httpsclient                     0.4.2-1+certbot~xenial+1                     all          enhanced HTTPS support for httplib and urllib2 using PyOpenSSL for Python2
ii  python-requests                            2.18.1-1+ubuntu16.04.1+certbot+1             all          elegant and simple HTTP library for Python2, built for human beings
ii  python-urllib3                             1.21.1-1+ubuntu16.04.1+certbot+1             all          HTTP library with thread-safe connection pooling for Python
ii  python3-chardet                            3.0.4-1+ubuntu16.04.1+certbot+2              all          universal character encoding detector for Python3
ii  python3-requests                           2.18.1-1+ubuntu16.04.1+certbot+1             all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-urllib3                            1.21.1-1+ubuntu16.04.1+certbot+1             all          HTTP library with thread-safe connection pooling for Python3
```

Do you need something else?

**Comment by SwartzCr** [comment] 2018-01-05 17:51
Can you share your error log with me? It'll help with finding the route cause

**Comment by josph2001** [comment] 2018-01-08 00:39
```
Attempting to renew cert [...] produced an unexpected error: None of the preferred challenges are supported by the selected plugin. Skipping.
```
For my case, I think it is due to this reason. As of now, I'm using DNS challenge for issuing the cert, but it is not supported by nginx plugin. We can close the ticket. I've switch to tls-sni. Thanks!

**Comment by W7PEA** [comment] 2018-08-07 21:46
I have also hit this issue, and I think the problem is not a python dependencies issue, but instead it looks this may be a dupe of Issue #6280

**Closed** 2019-06-20 09:59 UTC
Labels: area: debian / ubuntu, area: pkging, area: python, area: renewal, debugging, needs-update

**Comment by jerrychong25** [comment] 2019-10-12 16:27
> ```
> Attempting to renew cert [...] produced an unexpected error: None of the preferred challenges are supported by the selected plugin. Skipping.
> ```
> 
> For my case, I think it is due to this reason mentioned in the log. At that time, I had used DNS challenge for issuing the cert, but it is not supported by nginx plugin. I've switched to tls-sni. We can close the ticket then. Thanks!

I fixed this "None of the preferred challenges are supported by the selected plugin" error using official DNS plugins mentioned in https://certbot.eff.org/docs/using.html#dns-plugins section.

Other methods all are not working.
