### ISSUE TITLE
Fedora 26 doesn't have development tools handy

### ISSUE THREAD

**Issue by bobstrecansky** [certbot/certbot#4966] opened 2017-07-27 01:06 UTC
(I'll be happy to fix this if someone else isn't working on it):

## My operating system is (include version):
Fedora 26

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
n/a

## I ran this command and it produced this output:
➜  certbot git:(master) sudo ./certbot-auto --os-packages-only                                                                                 1   master 

Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
dnf is /bin/dnf
Last metadata expiration check: 2:29:22 ago on Wed 26 Jul 2017 06:35:13 PM EDT.
Package gcc-7.1.1-3.fc26.x86_64 is already installed, skipping.
Package augeas-libs-1.8.0-1.fc26.x86_64 is already installed, skipping.
Package openssl-1:1.1.0f-7.fc26.x86_64 is already installed, skipping.
Package openssl-devel-1:1.1.0f-7.fc26.x86_64 is already installed, skipping.
Package ca-certificates-2017.2.14-1.0.fc26.noarch is already installed, skipping.
Package python2-2.7.13-11.fc26.x86_64 is already installed, skipping.
No package python27-devel available.
No package python27-virtualenv available.
No package python27-tools available.
No package python27-pip available.
Error: Unable to find a match
Could not install OS dependencies. Aborting bootstrap!

## Certbot's behavior differed from what I expected because:
The OS dependencies should be installed

**Comment by bmw** [comment] 2017-07-27 19:22
I came across this recently when trying to test one of my PRs. The problem is the packages we want have the prefix `python2` which is a new change in Red Hat based systems starting with Fedora 26.

This also affects `certbot-auto` users on this system although there aren't (m)any because we have native packages available.

Working on this would be valuable. The file to modify is `letsencrypt-auto-source/pieces/bootstrappers/rpm_common.sh`. Make sure you read https://certbot.eff.org/docs/contributing.html#updating-certbot-auto-and-letsencrypt-auto as well.

**Comment by bobstrecansky** [comment] 2017-07-29 20:12
Cool, I'll get rolling on this in the upcoming week.

**Comment by bobstrecansky** [comment] 2017-08-07 02:52
Working on this here: https://github.com/certbot/certbot/pull/4997

**Comment by bmw** [comment] 2017-08-09 20:21
Fixed in #4997.

**Closed by bmw** 2017-08-09 20:21 UTC
Labels: area: certbot-auto, area: fedora / redhat / CentOS
