### ISSUE TITLE
certbot-auto --apache fails to parse config

### ISSUE THREAD

**Issue by kstubb** [certbot/certbot#3702] opened 2016-10-28 05:24 UTC
I had this happen to me today and found the issue to be lines with a pound sign (#) only, which I had a comment on, but deleted and left the pound sign.

ie.
`# mod_rewrite
<IfModule mod_rewrite>
...
</IfModule>`

to 

`#                                      <-------- fails parsing here
<IfModule mod_rewrite>
...
</IfModule>`

caused 
"The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/conf-enabled/000-default.conf', u'Syntax error'),)"

I hope you can figure out what I mean as I can't figure out how to make the code tags above hold formatting and not place everything on one line.

**Comment by SwartzCr** [comment] 2017-03-17 18:52
@joohoi know if this is a dupe of another issue? I know we've been talking a lot about parsing comments

**Comment by SwartzCr** [comment] 2017-08-28 20:38
@joohoi want to better categorize this - or put it in a milestone?

**Comment by joohoi** [comment] 2017-08-29 08:18
This is an old issue, and I think it's fixed already, but will look into this and try to reproduce.

**Comment by joohoi** [comment] 2017-09-27 11:18
This seems fixed, I wasn't able to reproduce against current master. Closing as fixed.

**Closed by joohoi** 2017-09-27 11:18 UTC
Labels: area: apache, area: ui / ux
