### ISSUE TITLE
Question with one answer

### ISSUE THREAD

**Issue by OlafvdSpek** [certbot/certbot#4994] opened 2017-08-04 11:26 UTC
```
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for ln0

Select the webroot for ln0
-------------------------------------------------------------------------------
1: Enter a new webroot
-------------------------------------------------------------------------------
Press 1 [enter] to confirm the selection (press 'c' to cancel): 
```

It'd be simpler to skip questions with just a single answer option. ;)

**Comment by bmw** [comment] 2017-08-04 15:22
I think this is a duplicate of #4136. Thanks for taking the time to make the issue though!

**Closed by bmw** 2017-08-04 15:22 UTC
