### ISSUE TITLE
DNS Authenticator: Support additional parameter with GCP project name

### ISSUE THREAD

**Issue by kasiakepka** [certbot/certbot#7193] opened 2019-06-26 13:05 UTC
One GCP account can be used across many projects, it would be useful to have additional parameter to [dns_google.py](https://github.com/certbot/certbot/blob/master/certbot-dns-google/certbot_dns_google/dns_google.py) where we could specify project name where authentication should happen.

**Comment by sydneyli** [comment] 2019-06-26 15:31
Thanks for submitting an issue!
@bmw might be able to correct me on this since I'm not familiar with the Google Cloud API, but it seems [service accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount) are created on a per-project basis.

**Comment by bmw** [comment] 2019-06-26 16:21
I think this is a duplicate of https://github.com/certbot/certbot/issues/6225 so I'm closing this, but if you think I've misunderstood the issue, please comment and I'll take another look!

**Closed by bmw** 2019-06-26 16:21 UTC
Labels: area: dns, more-info
