### ISSUE TITLE
wildcard subdomain considered invalid by certbot

### ISSUE THREAD

**Issue by niklas-studer** [certbot/certbot#3557] opened 2016-09-28 18:18 UTC
I do understand that letsencrypt does not support issuance of certificates to a wildcard subdomain while other CA's might.
Since according to cerbots documentation you can point it to any CA i would appreciate if it would be possible to accept wildcard subdomain requests (i.e. through enabling a flag).
Thank you

**Comment by pde** [comment] 2016-09-28 21:36
If another CA tells us they'd like that change, we will prioritise it. In the mean time, are you interested in this because you're planning to run your own ACME server?

**Comment by bmw** [comment] 2016-09-28 21:38
dupe of #3233

**Closed by bmw** 2016-09-28 21:38 UTC
Labels: acme, enhancement
