### ISSUE TITLE
Certbot is broken after Ubuntu 20.04

### ISSUE THREAD

**Issue by Kapiroto** [certbot/certbot#8032] opened 2020-05-29 14:23 UTC
root@terrance-ubuntu:~/certbot# ./certbot-auto --version
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://archive.canonical.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Hit:3 http://mariadb.mirror.globo.tech/repo/10.5/ubuntu focal InRelease
Get:4 http://ubuntu.bhs.mirrors.ovh.net/ubuntu focal InRelease [265 kB]
Get:5 http://ubuntu.bhs.mirrors.ovh.net/ubuntu focal-updates InRelease [107 kB]
Get:6 http://ubuntu.bhs.mirrors.ovh.net/ubuntu focal-backports InRelease [98.3 kB]
Fetched 577 kB in 1s (691 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate

**Comment by jfoliveira** [comment] 2020-06-02 18:21
I have the same issue and tried a workaround of setting `USE_PYTHON_3` before invoking certbot-auto:
```node
USE_PYTHON_3=1 /opt/certbot/certbot-auto --install-only
```
It seems to keep using python 2 as the error message says:

> Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'

Any workaround to have `certbot-auto` working with Ubuntu 20?

**Comment by bmw** [comment] 2020-06-03 19:34
Closing as a duplicate of https://github.com/certbot/certbot/issues/7941. I suggested a couple different alternatives to installing Certbot on the platform in that thread though.

**Closed by bmw** 2020-06-03 19:34 UTC
