### ISSUE TITLE
certbot-auto reports python2.6 is not supported

### ISSUE THREAD

**Issue by kartagis** [certbot/certbot#4604] opened 2017-05-02 08:33 UTC
## My operating system is (include version):

Centos 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 30: invalid continuation byte

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-05-02 08:32:12,861:DEBUG:certbot.log:Root logging level set at 20
2017-05-02 08:32:12,861:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-05-02 08:32:12,862:DEBUG:certbot.main:certbot version: 0.13.0
2017-05-02 08:32:12,862:DEBUG:certbot.main:Arguments: []
2017-05-02 08:32:12,862:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-05-02 08:32:12,863:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-05-02 08:32:13,086:DEBUG:certbot_apache.configurator:Apache version is 2.2.15
2017-05-02 08:32:14,087:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 755, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 584, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/selection.py", line 184, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/selection.py", line 25, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/disco.py", line 228, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 196, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 581, in get_virtual_hosts
    (vhost_path, parser.case_i("VirtualHost"))))
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/augeas.py", line 423, in match
    ctypes.c_char_p).value))
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/augeas.py", line 65, in dec
    return st.decode(AUGENC)
  File "/root/.local/share/letsencrypt/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 30: invalid continuation byte

**Comment by SwartzCr** [comment] 2017-05-03 15:14
While it's true that we plan to stop supporting python 2.6 - I'm not sure that's what the problem is in this case.
My first question would be is if there are any non ascii characters in your virtualhosts.
Also if you'd like, there are ways to upgrade to python 2.7 on your system, which I'd be happy to walk you through

**Comment by SwartzCr** [comment] 2017-08-28 23:20
@kartagis have you managed to get your version of certbot to work?

**Comment by kartagis** [comment] 2017-09-26 12:56
Hello @SwartzCr,

It works, but I'm still getting the message.

**Comment by joohoi** [comment] 2019-03-15 20:28
Certbot-auto should install and use Python3 nowadays, so closing this issue.

**Closed by joohoi** 2019-03-15 20:28 UTC
Labels: area: fedora / redhat / CentOS, more-info
