### ISSUE TITLE
Python CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by srfn8kd** [certbot/certbot#10050] opened 2024-11-10 14:42 UTC
## My operating system is (include version):  

Red Hat Enterprise Linux release 8.10 (Ootpa)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Certbot is installed with snap

## I ran this command and it produced this output:

/usr/bin/certbot -n certificates

Saving debug log to /var/log/letsencrypt/letsencrypt.log
/snap/certbot/4182/lib/python3.12/site-packages/certbot/ocsp.py:238: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to this_update_utc.
  if not response_ocsp.this_update:
/snap/certbot/4182/lib/python3.12/site-packages/certbot/ocsp.py:240: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to this_update_utc.
  if response_ocsp.this_update > now + timedelta(minutes=5):
/snap/certbot/4182/lib/python3.12/site-packages/certbot/ocsp.py:242: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to next_update_utc.
  if response_ocsp.next_update and response_ocsp.next_update < now - timedelta(minutes=5):

## Here is a Certbot log showing the issue (if available):

2024-11-10 06:40:04,266:DEBUG:urllib3.connectionpool:http://localhost:None "GET /v2/connections?snap=certbot&interface=content HTTP/1.1" 200 97
2024-11-10 06:40:04,385:DEBUG:certbot._internal.main:certbot version: 3.0.0
2024-11-10 06:40:04,385:DEBUG:certbot._internal.main:Location of certbot entry point: /snap/certbot/4182/bin/certbot
2024-11-10 06:40:04,385:DEBUG:certbot._internal.main:Arguments: ['-n', '--preconfigured-renewal']
2024-11-10 06:40:04,385:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-11-10 06:40:04,438:DEBUG:certbot._internal.log:Root logging level set at 30
2024-11-10 06:40:04,447:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): e5.o.lencr.org:80
2024-11-10 06:40:04,466:DEBUG:urllib3.connectionpool:http://e5.o.lencr.org:80 "POST / HTTP/1.1" 200 346
2024-11-10 06:40:04,466:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/live/tweaker.caltech.edu/cert.pem is signed by the certificate's issuer.
2024-11-10 06:40:04,467:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/live/tweaker.caltech.edu/cert.pem is: OCSPCertStatus.GOOD
2024-11-10 06:40:04,471:DEBUG:certbot._internal.display.obj:Notifying user: Found the following certs:

**Comment by telnetdoogie** [comment] 2024-11-10 18:36
Duplicate of #9967

**Comment by osirisinferi** [comment] 2024-11-10 19:54
Closing in favor of #9967 indeed.

**Closed by osirisinferi** 2024-11-10 19:54 UTC
