### ISSUE TITLE
"Permission Denied" on FreeBSD as root

### ISSUE THREAD

**Issue by DavidCWGA** [certbot/certbot#2457] opened 2016-02-12 04:41 UTC
I'm attempting to run letsencrypt in a FreeBSD 9.3 jail on FreeNAS as root. Root has permission to use sudo. (Even though this shouldn't be necessary, it looks like the script tries to use sudo all the time.) I get a "permission denied" error.

```
# uname -a
FreeBSD sharetool 9.3-RELEASE-p31 FreeBSD 9.3-RELEASE-p31 #0 r288272+33bb475: Wed Feb  3 02:19:35 PST 2016     root@build3.ixsystems.com:/tank/home/stable-builds/FN/objs/os-base/amd64/tank/home/stable-builds/FN/FreeBSD/src/sys/FREENAS.amd64  amd64

# whoami
root

# sudo whoami
root

# ./letsencrypt-auto --debug
Bootstrapping dependencies via FreeBSD...
./letsencrypt-auto: : Permission denied

# ./letsencrypt-auto-source/letsencrypt-auto --os-packages-only --debug
Bootstrapping dependencies via FreeBSD...
./letsencrypt-auto-source/letsencrypt-auto: : Permission denied
```

**Comment by PariahVi** [comment] 2016-02-16 07:07
I can confirm that I am having the same problem.

**Comment by landaire** [comment] 2016-02-17 00:08
Same here. This was working before.

**Comment by rawzone** [comment] 2016-02-24 19:27
Also a problem on my end...

**Comment by landaire** [comment] 2016-02-24 19:29
Any of you guys tried the `python27-letsencrypt` pkg? That worked fine for me.

**Comment by rawzone** [comment] 2016-02-24 19:32
> Any of you guys tried the python27-letsencrypt pkg? That worked fine for me.
Nope - But will test it out at once - Thanks for the heads up!

**Comment by PawnTakesQueen** [comment] 2016-02-27 08:08
I can confirm as well.  Fixed in my case.

**Comment by bmw** [comment] 2018-10-26 01:03
If you're on FreeBSD, I'd definitely recommend using the official packages over `certbot-auto`. In general, you can always find the up to date instructions for how we recommend you install Certbot on your system at https://certbot.eff.org.

As for this issue, how `certbot-auto` gets root permissions has been completely rewritten since this issue was created. Since we haven't seen any activity here since Feb. 2016, I'm closing this issue. If anyone is continuing to struggle with this, please comment or open a new issue.

**Closed by bmw** 2018-10-26 01:03 UTC
Labels: area: certbot-auto
