### ISSUE TITLE
How to Install On Raspberry Pi 3

### ISSUE THREAD

**Issue by liberodark** [certbot/certbot#3150] opened 2016-06-10 13:10 UTC
Hello,

How to install certbot 0.8.0 on RPi 3 Debian 8 ?

Cordialy

**Comment by bmw** [comment] 2016-06-10 20:48
`certbot` has never been tested on or developed for the Raspberry Pi so that's a good question. While there are `certbot`/`letsencrypt` packages in Debian/Ubuntu, I'm assuming there are no `certbot` packages available on Raspbian? Have you tried using `certbot-auto`? If so, what was the problem?

**Comment by wyrias** [comment] 2016-06-19 17:26
i'm trying it right now and as far as i can understand it, the process stops at this point
![auswahl_097](https://cloud.githubusercontent.com/assets/10499002/16178813/89d46c64-3653-11e6-959c-7f44a15c46aa.png)

i was not able to figure out why. in the logfiles it says, that the process was interrupted manually. but that was not the point. :/

**Comment by bmw** [comment] 2016-06-21 00:12
Can you provide the log of this? By default, logs are stored in `/var/log/letsencrypt`. Feel free to redact any domains or e-mail addresses contained in the log as you see fit.

**Comment by liberodark** [comment] 2016-06-21 09:00
For me have nginx but is not work

**Comment by liberodark** [comment] 2016-06-21 09:01
On Appache is Work Fine !

**Comment by patricktokeeffe** [comment] 2016-10-29 03:43
I am unable to get `certbot-auto --apache` to work for me on Pi3 (apache2 installed as part of mediawiki package). As mentioned in #3007, I've made sure to satisfy `libaugeas0` and `augeas-lenses`. 

Could it be related to the non-existent path `/files/etc/apache2/apache2.conf`? I've run the process twice and twice my log (`/var/log/letsencrypt/letsencrypt.log`) contains a block similar this one. You'll have to scroll rightwards to see it:

```
...
2016-10-29 03:10:26,479:INFO:certbot_apache.configurator:Enabled Apache socache_shmcb module                                                           
2016-10-29 03:10:26,806:INFO:certbot_apache.configurator:Enabled Apache ssl module                                                                     
2016-10-29 03:10:28,368:DEBUG:certbot_apache.tls_sni_01:Adding Include /etc/apache2/le_tls_sni_01_cert_challenge.conf to /files/etc/apache2/apache2.co$
2016-10-29 03:10:28,369:DEBUG:certbot_apache.tls_sni_01:writing a config file with text:                                                               
 <IfModule mod_ssl.c>                                                                                                                                  
<VirtualHost 127.0.0.1:443>                                                                                                                            
    ServerName 9fe95657619f8d43ae3345ee431ef7d0.8778bfa6153f27ee022cb685cee053d9.acme.invalid                                                          
    UseCanonicalName on                                                                                                                                
    SSLStrictSNIVHostCheck on                                                                                                                          
...                                                                                                                                                       
```

I used the "Apache on Debian (Other)" method to obtain certbot. Before installing it, I backed up my apache2 conf directory and then I ran `diff -r` against the post-certbot apache2 conf... no changes detected. 

The final error I see is:

```
FailedChallenges: Failed authorization procedure. my.redacted.domain.tld (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to MY.REDACTED.IP.ADDR:443 for TLS-SNI-01 challenge
```

**Comment by patricktokeeffe** [comment] 2016-10-29 05:27
Well, my first problem turned out to be no mod_ssl, which I fixed by issuing `a2enmod ssl`. I still wasn't able to use `--apache` but the mediawiki conf files warn about incompatibility with VirtualHost. Alternate method `--webroot certonly -w /var/www/html` worked great.

**Comment by jsimaoisel** [comment] 2017-02-25 19:28
When running the certbot-auto on a raspberry pi 3 (Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux) I have the following error message:

```
[...]
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.RSTxwlU5K8/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.RSTxwlU5K8/pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "/tmp/tmp.RSTxwlU5K8/pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

Any idea about the cause of the problem?

Thanks.

**Comment by drakerui** [comment] 2017-04-24 13:12
Getting the same error as jsimaoisel.

Aditianaly I'm able to manualy download the files before running certbot, but after running it I can no longer manualy download, the server just shuts me out.

**Comment by FrancYescO** [comment] 2017-06-03 13:18
https://github.com/certbot/certbot/issues/2673#issuecomment-286276081

**Comment by bmw** [comment] 2019-02-14 21:49
There are a bunch of different issues in this thread and it hasn't been updated in almost 2 years. If anyone is still having trouble here, please open a new issue or make a post at https://community.letsencrypt.org.

**Closed by bmw** 2019-02-14 21:49 UTC
Labels: area: pkging, more-info
