### ISSUE TITLE
Docker image fails with an error about a writable folder

### ISSUE THREAD

**Issue by stevenroose** [certbot/certbot#6088] opened 2018-06-11 16:00 UTC
When trying to use the Docker image in this repo (from Docker Hub), I get the following error:

```
letsencrypt_1    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
letsencrypt_1    | The following error was encountered:
letsencrypt_1    | [Errno 13] Permission denied: '/etc/letsencrypt/.certbot.lock'
letsencrypt_1    | Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

However, both (1) the certbot executable inside the docker is executed as root (this is Docker default), and (2) the config-dir, work-dir and logs-dir are writable. As it's specifically about the `/etc/letsencrypt` directory, it's mapped to a folder with a `rw` volume.

**Comment by schoen** [comment] 2018-06-12 00:37
Hi @stevenroose,

Is this effectively a duplicate of #6087, or are there some specific things about Docker image documentation or common Docker practice that also means that this aspect should be addressed separately?

**Comment by stevenroose** [comment] 2018-06-15 15:32
I still haven't solved this problem.

I simplified my setup to just have this volumes in docker-compose:
```
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt:rw
      - ./data/logs/letsencrypt:/var/log/letsencrypt:rw
```
And when I run docker-compose, I get that error. 

I tried both creating those two directories (`./data/letsencrypt` and `./data/logs/letsencrypt`) using root and using the normal user. I also tried not creating them and have docker-compose do it for me.

I know it's not a certbot issue probably, but a docker-compose one. But it looks like the certbot container is the only one that has this issue.

**Comment by larssb** [comment] 2018-10-10 13:53
I'm having the same issue. 

Error: 

```txt
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The following error was encountered:
[Errno 13] Permission denied: '/etc/letsencrypt/.certbot.lock'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
```

I'm using the [cloudflare-dns-plugin](https://hub.docker.com/r/certbot/dns-cloudflare/) docker  image. 

The cmdline I execute is:

```docker
sudo docker run -it --rm --name certbot \
-v "/private/etc/letsencrypt:/etc/letsencrypt" \
-v "/private/var/lib/letsencrypt:/var/lib/letsencrypt" \
certbot/dns-cloudflare sudo certonly \
--dry-run --dns-cloudflare \
--dns-cloudflare-credentials /etc/letsencrypt/config/CloudFlare/cloudflare.ini \
--cert-name my.certificate.io
```

I'm on MacOS, that. is the reason for the `/private` reference in the `-v` specifications.

Am I doing something wrong or is this a bug?

Thank you.

**Comment by bmw** [comment] 2019-06-13 18:34
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.

**Closed by bmw** 2019-06-13 18:34 UTC
Labels: more-info, needs-update

**Comment by gabx** [comment] 2019-08-17 15:58
same issue on Fedora Atomic 29.
```
# podman run -it --rm --name certbot -p 80:80 -p 443:443 -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" certbot/certbot certonly --standalone --email MyEmail -d "*.example.com"

Saving debug log to /var/log/letsencrypt/letsencrypt.log
The following error was encountered:
[Errno 13] Permission denied: '/etc/letsencrypt/.certbot.lock'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.

% ls -alZ /etc/letsencrypt 
total 12K
drwxr-xr-x.  2 root root unconfined_u:object_r:etc_t:s0    6 Aug 16 17:03 ./
drwxr-xr-x. 89 root root system_u:object_r:etc_t:s0     8.0K Aug 16 17:03 ../
``` 

Apart from SELinux issue, there is no reason why this directory is not writable.
