### ISSUE TITLE
urllib2 import build_opener, HTTPHandler, HTTPSHandler - Debian 9.2 on AWS

### ISSUE THREAD

**Issue by dertin** [certbot/certbot#5325] opened 2017-12-14 13:02 UTC
## Operating system is:
Debian 9.2 on AWS

## I installed Certbot with:
https://github.com/dertin/lemp-stack-debian/blob/develop/install.sh#L1081

## I have the following error:
```
# ./certbot-auto --config /etc/letsencrypt/configs/dertin.ml.conf certonly

Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://cdn-aws.deb.debian.org/debian stretch InRelease        
Hit:3 http://cdn-aws.deb.debian.org/debian stretch-updates InRelease
Hit:4 http://cdn-aws.deb.debian.org/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version (1.8.0-1+deb9u1).
libaugeas0 is already the newest version (1.8.0-1+deb9u1).
ca-certificates is already the newest version (20161130+nmu1).
gcc is already the newest version (4:6.3.0-4).
libffi-dev is already the newest version (3.2.1-6).
libssl-dev is already the newest version (1.1.0f-3+deb9u1).
openssl is already the newest version (1.1.0f-3+deb9u1).
python is already the newest version (2.7.13-2).
python-dev is already the newest version (2.7.13-2).
python-virtualenv is already the newest version (15.1.0+ds-1).
virtualenv is already the newest version (15.1.0+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Traceback (most recent call last):
  File "/tmp/tmp.9JnU7HuLAe/fetch.py", line 23, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler
ImportError: cannot import name HTTPSHandler
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.57g3ctcJzm/pipstrap.py", line 52, in <module>
    from urllib.request import build_opener, HTTPHandler, HTTPSHandler
ImportError: No module named request

```

# python --version
`Python 2.7.13`

# openssl version
`OpenSSL 1.1.0g  2 Nov 2017`

# curl -V
```
curl 7.57.0 (x86_64-pc-linux-gnu) libcurl/7.57.0 OpenSSL/1.1.0g zlib/1.2.11 libssh2/1.8.0 nghttp2/1.28.0
Release-Date: 2017-11-29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```

# nginx -V
```
nginx version: nginx/1.13.7
built by gcc 6.3.0 20170516 (Debian 6.3.0-18) 
built with OpenSSL 1.1.0g  2 Nov 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --user=www-data --group=www-data --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_uwsgi_module --without-http_scgi_module --without-http_memcached_module --with-http_ssl_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_v2_module --with-ipv6
```

Thank you.

**Comment by bmw** [comment] 2017-12-14 19:30
Both errors are actually due to the problem `from urllib2 import build_opener, HTTPHandler, HTTPSHandler`. The other error is a [fall back](https://github.com/certbot/certbot/blob/master/letsencrypt-auto-source/pieces/pipstrap.py#L49) for the same problem and is trying to use code that works in Python 3, but `certbot-auto` doesn't use Python 3 (unless you're setting the environment variable `LE_PYTHON` and doing other work yourself).

`urllib2.HTTPSHandler` is part of the [Python standard library](https://docs.python.org/2/library/urllib2.html#urllib2.HTTPSHandler). It's possible these files may be corrupted on your system. Have you installed any software on this server using `pip`?

To see if you can reproduce the problem outside of Certbot, can you run:
```
VENV_DIR=$(mktemp -d)
virtualenv --no-site-packages -p $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) "$VENV_DIR"
"$VENV_DIR/bin/python" -c 'from urllib2 import build_opener, HTTPHandler, HTTPSHandler'
rm -rf "$VENV_DIR"
```

**Comment by dertin** [comment] 2017-12-14 19:53
Hi @bmw,

I can not do the import.

```
$ "$VENV_DIR/bin/python" -c 'from urllib2 import build_opener, HTTPHandler, HTTPSHandler'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name HTTPSHandler

```
What can affect is the compilation of OpenSSL. I suspect this line.

https://github.com/dertin/lemp-stack-debian/blob/ff40d350e2622f3127f45ff6c854eeee5aa20914/install.sh#L214

I would have to find the correct way to solve it. The OpenSSL developers recommended me to remove that line.

I'm going to try reinstalling python...

**Comment by dertin** [comment] 2017-12-14 20:01
It did not work reinstall python2.7 from APT. There must be some problem with the OpenSSL 1.1.0g and Python 2.7. libraries

**Comment by bmw** [comment] 2017-12-14 20:40
It might be that the fact that the Python libraries from APT come precompiled against a different version of OpenSSL. If you need/want to use that version of OpenSSL, you may have to compile your own Python as well or make sure that Python correctly links to the version of OpenSSL from APT.

Unfortunately, I'm unable to help you debug a general issue with your Python installation so I'm closing this issue. If you encounter any Certbot specific problems, please open another issue and we'll be happy to help.

**Closed by bmw** 2017-12-14 20:40 UTC
Labels: area: certbot-auto, more-info

**Comment by dertin** [comment] 2017-12-14 20:44
@bmw Thank you.
