### ISSUE TITLE
NameVirtualHost *:80 has no VirtualHosts

### ISSUE THREAD

**Issue by oni319** [certbot/certbot#4348] opened 2017-03-15 15:39 UTC
## My operating system is (include version):
CentOS 6.6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Installed with certbot-auto

Service httpd cannot be restarted after certbot-auto, there is this following errors :+1: 
[warn] NameVirtualHost *:80 has no VirtualHosts

which worked normally before certbot install.

Any help will be more appreciate.

Thank you for your time

**Comment by SwartzCr** [comment] 2017-03-17 00:32
Hmmm, would you be able to attach the certbot log? And if possible show the resulting apache config that certbot generated?

**Comment by hudson6666** [comment] 2017-04-07 12:58
Hello! I have the exactly same issue and situation as this
https://community.letsencrypt.org/t/how-to-successfully-install-certbot-on-apache-on-centos-6/17069
however, the solution provided there doesn't work for me. I think it is the same problem @oni319 has.

The config file generated for me
http://paste.ubuntu.com/24333854/
http://paste.ubuntu.com/24333860/
The certbot exited with no error nor log file.

Thanks for your help! If there's any information needed please let me know.

**Comment by SwartzCr** [comment] 2017-04-11 02:29
Can you try deleting the NameVirtualHost 0.0.0.0:80 line from your le-ssl.conf vhost file? or you can change it to 0.0.0.0:443 as suggested in that forum thread.
Though I'm curious if @joohoi knows why it's including that line (incorrectly)

**Comment by hudson6666** [comment] 2017-04-14 14:28
I changed it to 443 and it's working now! Thanks! You really helped!

**Comment by SwartzCr** [comment] 2017-04-14 18:47
Awesome - glad it worked for you! I'm going to close this, but it's possible we should still investigate this issue (@joohoi)

**Closed by SwartzCr** 2017-04-14 18:47 UTC
Labels: area: apache, area: fedora / redhat / CentOS, more-info

**Comment by pde** [comment] 2017-05-16 18:30
Believed to be a duplicate of #4223 but @joohoi should probably double check that.
