### ISSUE TITLE
Apache may be picking the right default vhost as a model for the wrong reasons

### ISSUE THREAD

**Issue by devdan** [certbot/certbot#3358] opened 2016-07-30 20:46 UTC
When using certbot-auto on Ubuntu 14.04 with Apache the path of the website will change from /var/www to /var/www/html

Certbot should respect and keep the already established path for the website.

**Comment by joohoi** [comment] 2016-07-31 10:05
Certbot doesn't actually rewrite the paths, it copies the configuration from original file. Please do a double check if you possibly have a duplicate configuration for the virtualhost in question. If this is not the case, could you post your virtualhost configuration files, so I can see if I'm able to reproduce the problem.

**Comment by devdan** [comment] 2016-07-31 10:37
You are completely right. I have one file called 000-default.conf which has /var/www/html as document root and another one called default-ssl.conf which has /var/www as document root.

Before using certbot, it used the document root of default-ssl and after running certbot, it takes the document root of 000-default.

Wouldn't you expect that for ssl the path is taken from default-ssl or is this an unusual configuration to have both files?

**Comment by joohoi** [comment] 2016-07-31 10:45
It actually is an usual configuration (and default in many distributions), however usually they both point to the same document root, as they effectively serve on the same domain, HTTP and HTTPS respectively.

**Comment by devdan** [comment] 2016-07-31 10:53
I think I let the 000-default point to the then non-existing /html to forbid http-traffic completey. Apparently, certbot uses another way of doing that. 

Still, wouldn't it make more sense to take the document root from default-ssl at least if you check the option in certbot that you want to forbid http-traffic?

**Comment by joohoi** [comment] 2016-07-31 10:58
> Still, wouldn't it make more sense to take the document root from default-ssl at least if you check the option in certbot that you want to forbid http-traffic?

It would, and we actually have that in place for other-than-default virtualhosts, eg. anything that has ServerName defined. I think this is because the default-ssl (without defined ServerName) configuration isn't active per default, so users are more likely to have customized default HTTP virtualhost.

**Comment by pde** [comment] 2016-08-02 20:33
Yes, I think this is probably one of those situations where it's going to be really hard to tell what the user would have wanted. Maaaybe we should pick the default HTTPS vhost, maybe we should pick the HTTP one, maybe we should ask, maybe we should ask but only if we can explicitly tell that they're different (which is quite hard to do)...

@joohoi I'm inclined to close this ticket, unless someone has a specific proposal to change vhost selection that they're quite sure is an improvement...

**Comment by pde** [comment] 2016-08-03 18:14
Discussing this on today's weekly call, we tentatively concluded:
* Certbot is currently doing the least-worst thing, but for the wrong reasons
* The heuristic documented in the plugin *would* pick the TLS wildcard host, but
* Because the plugin doesn't comprehend `_default_` correctly, it falls back to the HTTP vhost, which is the right outcome for the wrong reasons.

**Comment by pde** [comment] 2016-08-03 18:15
(So at some point we should change the heuristic, and fix the implementation, but it's a lowish-priority task).

**Comment by joohoi** [comment] 2018-01-26 13:27
Possible issue here with CentOS 6 / Apache 2.2:
https://community.letsencrypt.org/t/new-certificate-not-working/50885/14

**Closed** 2020-07-18 06:18 UTC
Labels: area: apache, needs-update
