### ISSUE TITLE
Ubuntu 16.04 and nginx

### ISSUE THREAD

**Issue by vecna** [certbot/certbot#4283] opened 2017-03-02 20:01 UTC
## My operating system is (include version):
Ubuntu 16.04 (xenial) 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`sudo apt-get install letsencrypt`

## I ran this command and it produced this output:
```
# letsencrypt certonly -w /var/www/html -d collector.facebook.tracking.exposed 
   [scrubbed ncurses]
An unexpected error occurred:
KeyError: 'server'
Please see the logfiles in /var/log/letsencrypt for more details.
```
## Here is a Certbot log showing the issue (if available):
```
2017-03-02 19:52:34,669:DEBUG:letsencrypt.cli:Root logging level set at 30
2017-03-02 19:52:34,671:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-03-02 19:52:34,672:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.1
2017-03-02 19:52:34,672:DEBUG:letsencrypt.cli:Arguments: ['-w', '/var/www/html', '-d', 'collector.facebook.tracking.exposed']
2017-03-02 19:52:34,673:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2017-03-02 19:52:34,678:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2017-03-02 19:52:34,823:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /var/www/html/.well-known/acme-challenge
2017-03-02 19:52:34,824:DEBUG:letsencrypt.display.ops:Multiple candidate plugins: * webroot
Description: Webroot Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0x7f746de5a9d0>
Prep: True

* standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7f746de5a990>
Prep: True
2017-03-02 19:52:36,307:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7f746de5a990> and installer None
2017-03-02 19:52:36,336:DEBUG:letsencrypt.cli:Picked account: <Account(4a30e40cea267809438c98197aaff346)>
2017-03-02 19:52:36,343:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2017-03-02 19:52:36,350:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-03-02 19:52:36,587:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2017-03-02 19:52:36,590:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Thu, 02 Mar 2017 19:52:36 GMT', 'Boulder-Request-Id': 'ST4wYbJROz_qjzLnkjf9B6hcUAOmA0UkoYVdQH6oDvw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 02 Mar 2017 19:52:36 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'jfwbDff1-F-6cgV6lN_C_UQ-7uEg4qZzHERZF2iSiLk'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-03-02 19:52:36,591:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Thu, 02 Mar 2017 19:52:36 GMT', 'Boulder-Request-Id': 'ST4wYbJROz_qjzLnkjf9B6hcUAOmA0UkoYVdQH6oDvw', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 02 Mar 2017 19:52:36 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'jfwbDff1-F-6cgV6lN_C_UQ-7uEg4qZzHERZF2iSiLk'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-03-02 19:52:36,598:DEBUG:parsedatetime:parse (top of loop): [30 days][]
2017-03-02 19:52:36,608:DEBUG:parsedatetime:CRE_UNITS matched
2017-03-02 19:52:36,609:DEBUG:parsedatetime:parse (bottom) [][30 days][][]
2017-03-02 19:52:36,609:DEBUG:parsedatetime:weekday False, dateStd False, dateStr False, time False, timeStr False, meridian False
2017-03-02 19:52:36,609:DEBUG:parsedatetime:dayStr False, modifier False, modifier2 False, units True, qunits False
2017-03-02 19:52:36,609:DEBUG:parsedatetime:_evalString(30 days, time.struct_time(tm_year=2017, tm_mon=3, tm_mday=2, tm_hour=19, tm_min=52, tm_sec=36, tm_wday=3, tm_yday=61, tm_isdst=0))
2017-03-02 19:52:36,609:DEBUG:parsedatetime:_buildTime: [30 ][][days]
2017-03-02 19:52:36,609:DEBUG:parsedatetime:units days --> realunit days
2017-03-02 19:52:36,609:DEBUG:parsedatetime:return
2017-03-02 19:52:36,610:DEBUG:letsencrypt.storage:Should renew, less than 30 days before certificate expiry 2017-02-27 11:53:00 UTC.
2017-03-02 19:52:36,610:INFO:letsencrypt.cli:Cert is due for renewal, auto-renewing...
2017-03-02 19:52:36,611:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 453, in _auth_from_domains
    original_server = lineage.configuration["renewalparams"]["server"]
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'

```

**Comment by bmw** [comment] 2017-03-02 20:05
Sorry for the trouble and thanks for taking time to file an issue. This is caused by taking configuration files from a newer version of `certbot/letsencrypt` and using them with `letsencrypt` 0.4.1 in Ubuntu. The problem has been fixed in newer versions of Certbot, but while we're waiting for Ubuntu to upgrade their `letsencrypt` package, I posted a workaround [here](https://github.com/certbot/certbot/issues/2750#issuecomment-238983818).

**Closed by bmw** 2017-03-02 20:05 UTC
