### ISSUE TITLE
pip installation requires 'bdist_wheel' install

### ISSUE THREAD

**Issue by mdhomer** [certbot/certbot#9062] opened 2021-10-07 17:06 UTC
## My operating system is (include version):
Ubuntu 20.04_LTS

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
`pip` from python3.8 package installation.

## I ran this command and it produced this output:
`pip install certbot==1.20.0`
```
2021-10-07T16:32:16.4140051Z ##[section]Starting: Install certbot dependency using python/pip
2021-10-07T16:32:16.4441358Z ==============================================================================
2021-10-07T16:32:16.4442530Z Task         : Bash
2021-10-07T16:32:16.4442986Z Description  : Run a Bash script on macOS, Linux, or Windows
2021-10-07T16:32:16.4443569Z Version      : 3.189.0
2021-10-07T16:32:16.4444046Z Author       : Microsoft Corporation
2021-10-07T16:32:16.4444508Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-10-07T16:32:16.4445012Z ==============================================================================
2021-10-07T16:32:18.1636885Z Generating script.
2021-10-07T16:32:18.1668263Z ========================== Starting Command Output ===========================
2021-10-07T16:32:18.1705800Z [command]/usr/bin/bash --noprofile --norc /agent/_work/_temp/6a43a49e-2d63-4215-bb96-935765214c45.sh
2021-10-07T16:32:23.1103060Z Collecting certbot==1.20.0
2021-10-07T16:32:23.1387653Z   Downloading certbot-1.20.0-py2.py3-none-any.whl (260 kB)
2021-10-07T16:32:23.4680925Z Collecting zope.interface
2021-10-07T16:32:23.4748978Z   Downloading zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
2021-10-07T16:32:23.5531570Z Requirement already satisfied: setuptools>=39.0.1 in ./worker_venv/lib/python3.8/site-packages (from certbot==1.20.0) (44.0.0)
2021-10-07T16:32:23.5831218Z Collecting ConfigArgParse>=0.9.3
2021-10-07T16:32:23.5888060Z   Downloading ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
2021-10-07T16:32:23.6280854Z Collecting parsedatetime>=2.4
2021-10-07T16:32:23.6341010Z   Downloading parsedatetime-2.6-py3-none-any.whl (42 kB)
2021-10-07T16:32:23.6772040Z Collecting zope.component
2021-10-07T16:32:23.6844792Z   Downloading zope.component-5.0.1-py2.py3-none-any.whl (68 kB)
2021-10-07T16:32:23.8385998Z Collecting pytz
2021-10-07T16:32:23.8465397Z   Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
2021-10-07T16:32:23.9722498Z Collecting josepy>=1.9.0
2021-10-07T16:32:23.9779752Z   Downloading josepy-1.10.0-py2.py3-none-any.whl (29 kB)
2021-10-07T16:32:24.0252724Z Collecting distro>=1.0.1
2021-10-07T16:32:24.0313549Z   Downloading distro-1.6.0-py2.py3-none-any.whl (19 kB)
2021-10-07T16:32:24.0645780Z Collecting configobj>=5.0.6
2021-10-07T16:32:24.0699979Z   Downloading configobj-5.0.6.tar.gz (33 kB)
2021-10-07T16:32:24.4292603Z Collecting acme>=1.20.0
2021-10-07T16:32:24.4641700Z   Downloading acme-1.20.0-py2.py3-none-any.whl (44 kB)
2021-10-07T16:32:24.8265060Z Collecting cryptography>=2.1.4
2021-10-07T16:32:24.8330013Z   Downloading cryptography-35.0.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
2021-10-07T16:32:25.0660937Z Collecting pyrfc3339
2021-10-07T16:32:25.0714775Z   Downloading pyRFC3339-1.1-py2.py3-none-any.whl (5.7 kB)
2021-10-07T16:32:25.1046284Z Collecting zope.event
2021-10-07T16:32:25.1096442Z   Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
2021-10-07T16:32:25.1823861Z Collecting zope.hookable>=4.2.0
2021-10-07T16:32:25.1888513Z   Downloading zope.hookable-5.1.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (28 kB)
2021-10-07T16:32:25.2763230Z Collecting PyOpenSSL>=0.13
2021-10-07T16:32:25.2825053Z   Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
2021-10-07T16:32:25.3354129Z Collecting six
2021-10-07T16:32:25.3413263Z   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
2021-10-07T16:32:25.3800027Z Collecting requests-toolbelt>=0.3.0
2021-10-07T16:32:25.3861061Z   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
2021-10-07T16:32:25.4694307Z Collecting requests>=2.14.2
2021-10-07T16:32:25.4750183Z   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
2021-10-07T16:32:25.7081636Z Collecting cffi>=1.12
2021-10-07T16:32:25.7141347Z   Downloading cffi-1.14.6-cp38-cp38-manylinux1_x86_64.whl (411 kB)
2021-10-07T16:32:25.7764005Z Collecting idna<4,>=2.5; python_version >= "3"
2021-10-07T16:32:25.7826423Z   Downloading idna-3.2-py3-none-any.whl (59 kB)
2021-10-07T16:32:25.8324824Z Collecting charset-normalizer~=2.0.0; python_version >= "3"
2021-10-07T16:32:25.8384261Z   Downloading charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
2021-10-07T16:32:25.9129670Z Collecting urllib3<1.27,>=1.21.1
2021-10-07T16:32:25.9191489Z   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
2021-10-07T16:32:25.9877900Z Collecting certifi>=2017.4.17
2021-10-07T16:32:25.9962910Z   Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
2021-10-07T16:32:26.1166463Z Collecting pycparser
2021-10-07T16:32:26.1223198Z   Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
2021-10-07T16:32:26.1436486Z Building wheels for collected packages: configobj
2021-10-07T16:32:26.1445879Z   Building wheel for configobj (setup.py): started
2021-10-07T16:32:26.2806932Z   Building wheel for configobj (setup.py): finished with status 'error'
2021-10-07T16:32:26.2808563Z   Running setup.py clean for configobj
2021-10-07T16:32:26.2809250Z   ERROR: Command errored out with exit status 1:
2021-10-07T16:32:26.2811068Z    command: /agent/_work/2/s/worker_venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-502tnhuo/configobj/setup.py'"'"'; __file__='"'"'/tmp/pip-install-502tnhuo/configobj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-944p2zbv
2021-10-07T16:32:26.2812546Z        cwd: /tmp/pip-install-502tnhuo/configobj/
2021-10-07T16:32:26.2813210Z   Complete output (6 lines):
2021-10-07T16:32:26.2813892Z   usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
2021-10-07T16:32:26.2814749Z      or: setup.py --help [cmd1 cmd2 ...]
2021-10-07T16:32:26.2815543Z      or: setup.py --help-commands
2021-10-07T16:32:26.2816311Z      or: setup.py cmd --help
2021-10-07T16:32:26.2816874Z   
2021-10-07T16:32:26.2817580Z   error: invalid command 'bdist_wheel'
2021-10-07T16:32:26.2819010Z   ----------------------------------------
2021-10-07T16:32:26.2819909Z   ERROR: Failed building wheel for configobj
2021-10-07T16:32:26.4198710Z Failed to build configobj
2021-10-07T16:32:26.5660519Z Installing collected packages: zope.interface, ConfigArgParse, parsedatetime, zope.event, zope.hookable, zope.component, pytz, pycparser, cffi, cryptography, six, PyOpenSSL, josepy, distro, configobj, idna, charset-normalizer, urllib3, certifi, requests, requests-toolbelt, pyrfc3339, acme, certbot
2021-10-07T16:32:28.0440983Z     Running setup.py install for configobj: started
2021-10-07T16:32:28.5283904Z     Running setup.py install for configobj: finished with status 'done'
2021-10-07T16:32:28.9722071Z Successfully installed ConfigArgParse-1.5.3 PyOpenSSL-21.0.0 acme-1.20.0 certbot-1.20.0 certifi-2021.5.30 cffi-1.14.6 charset-normalizer-2.0.6 configobj-5.0.6 cryptography-35.0.0 distro-1.6.0 idna-3.2 josepy-1.10.0 parsedatetime-2.6 pycparser-2.20 pyrfc3339-1.1 pytz-2021.3 requests-2.26.0 requests-toolbelt-0.9.1 six-1.16.0 urllib3-1.26.7 zope.component-5.0.1 zope.event-4.5.0 zope.hookable-5.1.0 zope.interface-5.4.0
2021-10-07T16:32:29.0742456Z ##[error]Bash wrote one or more lines to the standard error stream.
2021-10-07T16:32:29.0778033Z ##[error]  ERROR: Command errored out with exit status 1:
   command: /agent/_work/2/s/worker_venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-502tnhuo/configobj/setup.py'"'"'; __file__='"'"'/tmp/pip-install-502tnhuo/configobj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-944p2zbv
       cwd: /tmp/pip-install-502tnhuo/configobj/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for configobj

2021-10-07T16:32:29.0891914Z ##[section]Finishing: Install certbot dependency using python/pip
```

## Certbot's behavior differed from what I expected because:
I think the setup.cfg/setup.py scripts should indicate that `wheel` is required for installation & pull this down.

My fix was to `pip install wheel` prior to running the certbot install, however I think this should be indicated in the package configuration.

This could be specified in `setup_requires`? or similar.
https://github.com/certbot/certbot/blob/master/certbot/setup.py#L43

Looks like there is a different recommendation for PEP 517 style standards:
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html?highlight=install_requires#build-system-requirement
```
[build-system]
requires = ["setuptools", "wheel"]
```

## Here is a Certbot log showing the issue (if available):
n/a

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
n/a

**Comment by bmw** [comment] 2021-10-08 19:42
Thanks for taking the time to look into this a bit and write this up.

I don't think us declaring a setup/build dependency on `wheel` will fix the problem unfortunately though. This is because [pip uses build isolation when building dependencies](https://pip.pypa.io/en/stable/cli/pip/#pep-517-and-518-support). What this means is that when building packages, each package is built in a separate, clean environment before being installed in the target environment. The error you're seeing here happens when building `configobj` so even if we declared a dependency on `wheel`, it wouldn't be available in the isolated environment used when building `configobj`. I tested this on Ubuntu 20.04 and confirmed this behavior.

I started to suggest we could update our documentation [here](https://certbot.eff.org/lets-encrypt/pip-other) to include this step, but upgrading `pip` seems to already take care of it. On top of that, I think the real problem here was in a package like `pip` or `setuptools` or Debian's version of it as I've never been able to reproduce problems like this outside of a Debian based system. Luckily, the problem seems to be fixed in newer versions of the packages, including those in Debian.

Because of all this, I'm not sure there's anything we can really do here. It might be useful for someone to track down the cause of the problem and try to get LTS Debian based distros to backport a fix, however, since Certbot's `pip` instructions avoid the problem and fixing it is out of our control, I'm closing this issue. If you think I'm missing something, please leave a comment and I'll reconsider.

**Closed by bmw** 2021-10-08 19:42 UTC
