### ISSUE TITLE
Apache SSL only 1 updated

### ISSUE THREAD

**Issue by bmanth60** [certbot/certbot#1868] opened 2015-12-11 18:37 UTC
Hi, This might be due to my specific configs, but I have SSL enabled on two separate ports. It successfully updated one port, but the other didn't update. I expected both ports to update.

**Comment by schoen** [comment] 2018-10-01 23:35
I'm going to close this issue because of its age, but if you still have problems or if you can provide examples of the affected Apache configurations, please post on the Let's Encrypt Community Forum at https://community.letsencrypt.org/ including the associated configuration and we can discuss what we think the expected behavior is or should be.

Thanks!

**Closed by schoen** 2018-10-01 23:35 UTC
Labels: area: apache, feature request
