### ISSUE TITLE
Bind on a specific interface

### ISSUE THREAD

**Issue by rfnx** [certbot/certbot#1515] opened 2015-11-16 03:59 UTC
Hello,

On my server I have to shutdown multiple processes completly unrelated to HTTPS, because they use the 443 port.

Is it possible to give the user an option to bind on a specific interface ?

**Comment by rfnx** [comment] 2015-11-16 22:36
I think you misunderstood the issue.

I understand binding on port 443 is mandatory for ACME spec. I'm just asking not to bind on 0.0.0.0 (ALL interfaces available) and instead provide an option to bind on a specific IP (not port!)

**Comment by bmw** [comment] 2015-11-16 23:28
I did misunderstand the issue! Thanks for correcting me.

**Comment by hrabbach** [comment] 2015-11-19 10:53
Yes, this is indeed a rather annoying issue. In fact, it causes lots of problems if you want to create a certificate for the host server and are running lots of VPSs. In fact it looks like the code only checks for processes that are already bound to port 80/443, but doesn't even try to bind to 0.0.0.0 - on my VPS host, it could successfully bind to 0.0.0.0:443, but it won't because in the pslist it finds processes that are in VPSs (OpenVZ) that bind to that port (on interfaces only available within the VPS).

**Comment by kuba** [comment] 2015-12-23 15:45
This should probably be fixed somewhere in `acme.standalone` - labeling as `acme`.

**Comment by sbraz** [comment] 2016-03-08 13:43
If anyone is interested, I use this hackish workaround with Python's http.server module:
```bash
cd /var/tmp/webroot/ || exit
python -m http.server --bind xx.xx.xx.xx 80 &
pid=$!
letsencrypt certonly --webroot /var/tmp/webroot/ […]
kill $pid
sleep 0.5
kill -0 $pid && kill -9 $pid
```

**Comment by Marqin** [comment] 2016-05-17 09:34
isn't this duplicate of #255 ?

**Comment by bmw** [comment] 2016-05-17 22:44
@Marqin, you're right. This looks like a duplicate of #255.

**Closed by bmw** 2016-05-17 22:44 UTC
Labels: acme
