### ISSUE TITLE
No IPv4 addresses found

### ISSUE THREAD

**Issue by wytcld** [certbot/certbot#3192] opened 2016-06-20 19:33 UTC
Failed authorization procedure. abc.xyz.net (tls-sni-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for abc.xyz.net.

In fact abc.xyz.net (not real domain here) resolves just fine, both by DNS A record and locally since it's in the hosts file on the webserver. And it resolves to an IPv4 address. Is this because that address is in a private range (e.g. 172.16.x.x)? Are we not to be allowed valid certs for servers only reachable on our LAN? Whatever, the error message appears wrong.

**Comment by ccppuu** [comment] 2016-06-20 19:42
@wytcld You're correct - the error message is caused by the address being in a private range. You're also correct that the message is misleading. This was fixed in boulder with https://github.com/letsencrypt/boulder/pull/1934 but it hasn't been deployed to production yet. This should happen in the next week or so.

I'm going to close this issue - other than wait for the fix to hit production there isn't anything for the certbot devs to do. Thanks for reporting!

**Closed by ccppuu** 2016-06-20 19:42 UTC

**Comment by schoen** [comment] 2016-06-20 19:45
Note that the discussion of the problem (leading to the fix @ccppuu mentions) apparently took place in https://github.com/letsencrypt/boulder/issues/1790 (in case you want to see the history or add anything).
