### ISSUE TITLE
Post-Hook not executed and log has no timestamps

### ISSUE THREAD

**Issue by ffittschen** [certbot/certbot#3486] opened 2016-09-09 10:27 UTC
Hi,

I'm using a cron job to automatically run the renewal (with certbot 0.8.1) using:
`30 2 * * 1 certbot renew --post-hook "systemctl reload nginx" >> /var/log/letsencrypt/renew-cronjob.log`

First of all: It seems like the post-hook has not been executed. I set a reminder to take a look at the website 2 days before the certificate expires and I'm glad I did this! My browser showed that the certificate expires in 2 days. So I went to the `/etc/letsencrypt/live/website.com` folder and the timestamp of the files were quite new, so after running `systemctl nginx reload` manually, my browser showed the new certificate with the new expiration date.

Second:
Looking at the logs trying to determine if there was an error message I couldn't tell if and when the certificate has been updated, since there are no timestamps in the log... 

The log just shows this repeatedly:

```
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/website.com.conf
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/subdomain.website.com.conf
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/mail.website.com.conf
-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/website.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/subdomain.website.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/mail.website.com/fullchain.pem (skipped)
No renewals were attempted.
```

Sadly the letsencrypt.log files are already overwritten/deleted from the time where the certificate has been renewed and the error should have popped up. But I'll take a look at the logs in 2 months.

Have you experienced the issue with the post-hook not being executed before? And is there anything I might have misconfigured?

**Comment by pde** [comment] 2016-09-13 19:56
The pre- and post- hooks are only run when a cert is actually being renewed.  Since your cert isn't due for renewal, nothing is happening and no hooks are run.

To test things out, you could temporarily edit your crontab to add `--force-renewal`.  Just remember to remove the flag again once you've confirmed it's working as intended!

Closing for now, please reopen if the cert is being renewed and the hook isn't running.

**Comment by ffittschen** [comment] 2016-09-13 20:40
@pde I think there is a misunderstanding: My cert has been renewed, but the post-hook did not run! 

The extract of the log was just to display that it is hard to determine from when this statement is. (I should have opened a seperate issue for that)

**Comment by pde** [comment] 2016-09-13 21:20
One thing to watch out for, by the way, is that cron typically uses a very minimal PATH.  Where is `systemctl` on your machine?

**Comment by ffittschen** [comment] 2016-11-06 15:42
Sorry, I was busy due to university.. `systemctl` is located at `/bin/systemctl` on my machine. I'll change my cronjob to use the full absolute path and take a look at the next renewal.

**Comment by pde** [comment] 2016-12-12 23:16
OK, closing as a duplicate of that.

**Closed by pde** 2016-12-12 23:16 UTC
Labels: duplicate, renewal
