### ISSUE TITLE
--dry-run does not work but --force-renewal does

### ISSUE THREAD

**Issue by StarlordSTRX** [certbot/certbot#3570] opened 2016-10-02 00:57 UTC
Sorry this might just be me being stupid but when i preform  `./certbot-auto renew --force-renewal` it works and returns
 `Congratulations, all renewals succeeded. The following certs have been renewed:
 /etc/letsencrypt/live/mydomain.tld-0001/fullchain.pem (success)
 /etc/letsencrypt/live/mydomain.tld/fullchain.pem (success)`

but when i preform `./certbot-auto renew --dry-run` it doesn't work and returns errors

`Processing /etc/letsencrypt/renewal/mydomain.tld-0001.conf`
`2016-10-02 02:35:31,688:WARNING:certbot.renewal:Attempting to renew cert from` `/etc/letsencrypt/renewal/mydomain.tld-0001.conf produced an unexpected error: Failed authorization` `procedure. mydomain.tld (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to 213.113.115.232:443 for TLS-SNI-01 challenge. Skipping.`

When I use renew without any flags it  says that the certs are not due for renewal yet (as it should) but I'm unsure if the command will work when i set it up as a automated task. I'm using Apache/2.4.10 on my raspberry pi running raspbian jessie. Again sorry in advance for missing something obvious.

**Comment by bmw** [comment] 2016-10-03 19:56
This looks like a bug. Thank you for taking the time to report the issue.

Can you provide a log file where you fail to renew with `--dry-run`? Ideally, it would be nice to also see a log file where renewal is successful so we can compare the logs and see what is different.

These logs may contain your e-mail and domain names, however. Feel free to redact this information as you deem appropriate.

**Comment by StarlordSTRX** [comment] 2016-10-03 20:36
Here are some log files for both a failed dry run and a successful force renewal. (ip address and domain has been redacted to 000.000.000.000 and domain.tld respectively.)
[--dry-run_failure-log.txt](https://github.com/certbot/certbot/files/507150/--dry-run_failure-log.txt)
[--force-renewal_success-log.txt](https://github.com/certbot/certbot/files/507151/--force-renewal_success-log.txt)

**Comment by bmw** [comment] 2016-10-04 00:13
Thanks for the logs @StarlordSTRX. The `--force-renewal` log doesn't seem to be from a run where `--force-renewal` was used though. A the top you can see:
```
Arguments: ['--apache']
```
and further down you can see
```
Cert not yet due for renewal
```
which [isn't displayed when --force-renewal is used](https://github.com/certbot/certbot/blob/master/certbot/renewal.py#L197).

Do you happen to have another log?

**Comment by StarlordSTRX** [comment] 2016-10-04 06:49
Whoops! My misstake, seems like i uploaded the wrong log. Here is the real `--force-renewal` log
[--force-renewal-success-log-actual-log.txt](https://github.com/certbot/certbot/files/507810/--force-renewal-success-log-actual-log.txt)

**Comment by bmw** [comment] 2016-10-05 23:40
Thanks for the logs. Certbot's behavior is more or less identical in each file until you pass/fail the challenge. I am not certain I know what the problem is, but I have a strong hunch.

I suspect this problem is due to [authorization reuse](https://community.letsencrypt.org/t/upcoming-change-valid-authz-reuse/16982) by Let's Encrypt. Basically, before Certbot can get a certificate from Let's Encrypt, it needs to prove that you control the domain you requested. Once you have done this, Let's Encrypt remembers that you are authorized for that domain for a period of time based on their current policies. The result of this is if you ask for a certificate again while you still have a valid authorization, the authorization is reused and they give you a certificate without actually checking that you performed the challenge properly.

When running Certbot with `--dry-run`, Certbot talks to [Let's Encrypt staging server](https://letsencrypt.org/docs/staging-environment/) which does not share authorizations with the production server. I suspect Certbot is failing to complete the challenge, but you have a valid authorization on the production server so Let's Encrypt isn't actually checking that you've solved the challenge correctly.

If this is the case, you should take some time to investigate these errors as `certbot renew --force-renewal` will fail in the future when your authorization expires. To start with, I would check the things suggested in Certbot's output in your `--dry-run` log:

"To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided."

**Comment by mathewparet** [comment] 2016-12-22 11:42
I think I know why this is happening. When initially the certificate is created the system tries to do the authorization using the domain name. 

But later when we try dry-run instead of authorising using the domain name it tries to authorise using the **DNS A** entry. This won't work in cases where your website is hosted in a cloud. For example, when using Google App Engine the DNS A record where your domain points to might be used by other domains as well. In such cases, fetching https://<**dns a ip**>:443 may not return anything. I think this is what's causing the failure.

Can someone test my concept and confirm?

**Comment by bmw** [comment] 2019-01-03 22:44
The way LE looks up DNS records should be identical.

I think the problem here is authorization reuse which I explained in my previous post so I'm closing this issue. If you continue to have problems, please comment on this issue or open a new one.

**Closed by bmw** 2019-01-03 22:44 UTC
Labels: area: apache, area: renewal, more-info
