### ISSUE TITLE
'--allow-subset-of-names' issues new certificates even if validated domains didn't change

### ISSUE THREAD

**Issue by mejo-** [certbot/certbot#5996] opened 2018-05-15 10:06 UTC
## My operating system is (include version):
Debian 9 Stretch, certbot 0.10.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt install certbot` (from Debian 9 Stretch)

## I ran this command and it produced this output:

I requested a certificate for two domains `test1.example.org` and `test2.example.org`:

```
certbot certonly --webroot --webroot-path /var/www/html --cert-name testcert --domains test1.example.org,test2.example.org --keep-until-expiring --allow-subset-of-names --non-interactive --agree-tos
```

`test1.example.org` was validated, `test2.example.org` was not. Thus, the issued certificate was only for `test1.example.org` (as expected).

## Certbot's behavior differed from what I expected because:
When I run the same command from above again and again, certbot each time issues a new certificate, even if the list of validated domains didn't change in the meantime. Therefore, I run into the ["duplicate certificate" rate limit](https://letsencrypt.org/docs/rate-limits/) after five consecutive runs of the command.

## Here is a Certbot log showing the issue (if available):
```
2018-05-15 09:29:52,218:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-cert HTTP/1.
1" 429 242
2018-05-15 09:29:52,219:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Content-Type: application/problem+json
Content-Length: 242
Boulder-Requester: 33387741
Replay-Nonce: vgT07FWPVlMudUBSy409ljLrqVZGdsChoWw52tynhHA
Expires: Tue, 15 May 2018 09:29:52 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 15 May 2018 09:29:52 GMT
Connection: close

{
  "type": "urn:acme:error:rateLimited",
  "detail": "Error creating new cert :: too many certificates already issued for exact set of domains: test1.example.org: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
2018-05-15 09:29:52,219:DEBUG:acme.client:Storing nonce: vgT07FWPVlMudUBSy409ljLrqVZGdsChoWw52tynhHA
2018-05-15 09:29:52,426:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 626, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 103, in _auth_from_available
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 296, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 272, in obtain_certificate
    return (self.obtain_certificate_from_csr(domains, csr, authzr=authzr)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 243, in obtain_certificate_from_csr
    authzr)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 318, in request_issuance
    headers={'Accept': content_type})
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 671, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 684, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 570, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: test1.example.org: see https://letsencrypt.org/docs/rate-limits/
```

**Comment by mnordhoff** [comment] 2018-05-15 10:12
> Debian 9 Stretch, certbot 0.10.2

I just reproduced this using certbot-auto 0.24.0 on Ubuntu 16.04 with:

`sudo -H certbot certonly --allow-subset-of-names --keep-until-expiring --staging --webroot -w /srv/www/certbot -d 28192.clover.letsencrypt.mattnordhoff.net -d negative.mattnordhoff.net`

**Comment by schoen** [comment] 2018-05-15 23:07
So technically the reason for this is that Certbot doesn't know that the subsequent request for the certificate with both names will still fail, so it attempts it again, because *the requested certificate is different from the existing certificate*. (Since the requested certificate is different from the existing certificate, the expiry time isn't checked at all!)

That is, when you have a certificate for `test1.example.org` (only), and then you run `certbot -d test1.example.org -d test2.example.org`, with or without `--allow-subset-of-names`, Certbot says "OK, I have a certificate for only one of those names, I was asked to get a certificate for both, I'll try to do that".

And then it fails, but because of the `--allow-subset-of-names`, the renewal is still performed.

In particular, we don't have logic for "the subset of names that succeeded is a match for the existing certificate which is not near expiry". It might be better for rate limits if we did introduce something like that.

In defense of the current behavior, I would say "please don't run Certbot with `-d` options unless you actively, specifically want it to make a renewed effort to get coverage for those names". (Note that `certbot renew` would *not* show the same behavior here, because it would take the list of desired names from the existing certificate.) However, maybe we could be cleverer about rate limits in this particular situation.

Right now the "should we try to renew/issue" logic happens very early in the process. Once the renewal attempt is triggered, we never second-guess that decision and say "oh, I guess we actually shouldn't have tried to issue this certificate after all". Instead, we just look at whether the issuance succeeded or failed, and save the new certificate if the issuance succeeded. In this case it seems like you're looking for a later decision like "OK, we tried to obtain a new certificate as requested by the user *but it turned out in practice* that the specific new certificate that we would get wouldn't be particularly useful, so we don't actually want to issue it".

We could try to implement logic of that sort, but I'd point out that you can probably still hit the failed authorization rate limit (rather than the duplicate certificate issuance limit) by rerunning the command, because Certbot will never stop trying to get the authorizations for the `test2.example.org` name (it never knows ahead of time that that attempt is going to fail just because it failed before). So you would never get to a situation where repeatedly running `certonly --allow-subset-of-names` with specific `-d` options for previously-failed validations doesn't result in an attempt to get new authorizations or thereby eventually run into a rate limit. Admittedly, it could be a gentler rate limit than the one that is currently hit.

**Comment by schoen** [comment] 2018-05-15 23:09
I added a lot of tags to this issue because the behavior here arguably related to all of those topics. :slightly_smiling_face:

**Comment by bmw** [comment] 2019-05-09 17:56
I'm tempted to argue that this is expected behavior for the reason schoen described but it'd be nice if we could do something for people who hit this. A couple ideas would be:

1. Deprecate `--allow-subset-of-names` entirely. It's often used for the wrong reasons.
2. Deprecate `--allow-subset-of-names` outside of the `renew` subcommand. You should be using `certbot renew` for renewal and if you're failing to initially obtain the certificate at setup, that's probably an issue you should know about.

**Comment by bmw** [comment] 2020-05-13 20:28
Closing in favor of https://github.com/certbot/certbot/issues/7929.

**Closed by bmw** 2020-05-13 20:28 UTC
Labels: area: cert management, area: documentation, area: policy, area: renewal, area: ui / ux, help wanted, needs-update
