### ISSUE TITLE
Apache plugin suggests wildcard domains and proceeds with auth.

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1683] opened 2015-12-03 20:01 UTC
```
19:58 < dbanet> Kuba I just ran ./letsencrypt-auto and it had two checkbox options there checked already: smei.tk and *.smei.tk
```

Full log:

```
2015-12-04 03:43:56,831:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-12-04 03:43:56,833:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-04 03:43:56,835:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0
2015-12-04 03:43:56,835:DEBUG:letsencrypt.cli:Arguments: ['--apache']
2015-12-04 03:43:56,836:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-04 03:43:56,841:DEBUG:letsencrypt.cli:Requested authenticator apache and installer apache
2015-12-04 03:43:57,171:DEBUG:letsencrypt.display.ops:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0xb655674c>
Prep: True
2015-12-04 03:43:57,173:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt_apache.configurator.ApacheConfigurator object at 0xb655674c> and installer <letsencrypt_apache.configurator.ApacheConfigurator object at 0xb655674c>
2015-12-04 03:44:00,075:DEBUG:letsencrypt.cli:Picked account: <Account(fcb1fd7031b0207eb8ce7d3faab50f4b)>
2015-12-04 03:44:00,078:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-12-04 03:44:00,082:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 03:44:00,622:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-12-04 03:44:00,626:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Thu, 03 Dec 2015 19:50:02 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:02 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '5HWYrym1duSOt1ZKiK58EsA-XBLsSxXzKEHC9_yaA_o'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-12-04 03:44:00,627:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Thu, 03 Dec 2015 19:50:02 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:02 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '5HWYrym1duSOt1ZKiK58EsA-XBLsSxXzKEHC9_yaA_o'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-12-04 03:44:12,556:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0003_key-letsencrypt.pem
2015-12-04 03:44:12,565:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0003_csr-letsencrypt.pem
2015-12-04 03:44:12,566:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0003_csr-letsencrypt.pem', data='0\x82\x02\x870\x82\x01o\x02\x01\x000\x121\x100\x0e\x06\x03U\x04\x03\x0c\x07smei.tk0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xd6A\x82\xc0\x82\x88\xd2\x02\xb4\xefIlO(H\x88\x0b\xa4\xe0\xe7\x97\xf3\xe3\xf1\x902\xb1\x07di\xe6\x91\x80W\x06\x12\xfd$0KR\xe0T\xc0A\xe4\xe6\x96\x1bi\x97\xfe\x9a\xe3\n\x85\xea\x19T\xd9\xc4\x04\xd89\x8e\xfc\xf3\xfe\x95\xeb\x0b\xa3\x8f{\rE\x0b\xb0\xc7\xdcA\xf7\x8f\xe1pRwbf\xab\xd5~\x9d\xb2\x94\x00\xa9!\r^\xbcHE(\x1f\x90\xbc\xe94\x93_|\xcc\xfd7\x19\x97\xfeV#\xd8z\x9aB{\xd9Pp\x82\x94N\xc7\xff\x0b?\xd1(q\xc5\xb1\xdf7\xafc\xf8\x89\x86\xce"\xbd\xa3i*\xa7.\xb0T8\x98*\xd1\xfc~HY\xe7\x92\xde\x99\xa1T\xa9`\xcbk3\x1f\x94\x02\xf3<\xedM`I=`_\xe0J~\xec\xb0\x84\xe4\xa9;\x8b\xf5\xb6\x1aG\xa0>Hu\x1b.\xda\xd7 \xe4nP\xb4\x08\r\xf6\xcc\n\xf6h\x16N\x94\x9d\x99\xf2}\x07\xb6S\xfc\xf4\x9c]\x1a\x96\xe3\x1a\xbb\x00\xce\x876]\x1b\x13\xb3\x93!J\xf0\xc6\xfe+\x02\x03\x01\x00\x01\xa000.\x06\t*\x86H\x86\xf7\r\x01\t\x0e1!0\x1f0\x1d\x06\x03U\x1d\x11\x04\x160\x14\x82\x07smei.tk\x82\t*.smei.tk0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\x0e\xbc\xf5\x98\xe1\xa5\xc9\x8b\xc8\xaf\xbc\x01\xbe\x8b\xd1\xa9W\xc2\x10tn\x10\xff\xb1\xefl\x83\xe1cT\x98>\xd0\xab\xcf\x91V5\xe7kF\x8c\xea\x91\x82\xf8\x99\xd38F\rKZ\xf2QY\x0b4U\xb5t\xfba\xe2\xb6$Fy\xfe\x95\x02Af\x8b\x85#\xd6\x9b|\xf7/]T\xc3:@\x93r\xd6\x1a\x96\xe2b\x98N\xff\xc1\xb8\x18e\x0c\x9d\xec\x16\xc3_e\x0e\x97\xca\xc8\xe6/\xde\x8ePJ1\xe6+\xa8\x1b\xf6N\xb0\xf1+=\xc06\xbbB\x01j4\xe9\xfd\nI67H\xdf\x82%\xb4Z\xc2\x1a\xf3*\x0b\xa8\x08\xae\x1f\x19\xc3\xf4S\xe9#\x8b\x82\x86\x86\x8c\xd0v\xf9\xd6\xc1\x9b\xc5\x1c\x19D-F\x15\x9d\xd1\x86\xef\x88\x9a<\xa4 \xb1\xcdas\x00\xee\xde\xaf\x1dS\x9b\xb8\x0f\xee6c\xc1\xc0}\xcb\xb5\xbe\xcfn\xbc\x04\xe5\xb9\x886\'\x1and\x932Gu\xd4\x7f\xb0\x1a\x94R!u\xdah\xc8\xbfq\xc5~\x99\x02\'s\x0c\x03f\xdc*\xfd\x9e:d\'', form='der'), domains: ['smei.tk', '*.smei.tk']
2015-12-04 03:44:12,567:DEBUG:root:Requesting fresh nonce
2015-12-04 03:44:12,567:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-12-04 03:44:12,568:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 03:44:12,923:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-12-04 03:44:12,926:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Thu, 03 Dec 2015 19:50:15 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:15 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '01ARimANbnr3XNtuEP35NBAKxlsOBhLAyS4W1XQavuk'}. Content: ''
2015-12-04 03:44:12,927:DEBUG:acme.client:Storing nonce: '\xd3P\x11\x8a`\rnz\xf7\\\xdbn\x10\xfd\xf94\x10\n\xc6[\x0e\x06\x12\xc0\xc9.\x16\xd5t\x1a\xbe\xe9'
2015-12-04 03:44:12,927:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, status=None, combinations=None, challenges=None
2015-12-04 03:44:12,927:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "smei.tk"}, "resource": "new-authz"}
2015-12-04 03:44:12,929:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jwk=None, x5u=None, kid=None, alg=None, cty=None, x5tS256=None, jku=None, x5t=None
2015-12-04 03:44:12,937:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, x5u=None, kid=None, cty=None, x5tS256=None, jku=None, x5t=None, nonce=None
2015-12-04 03:44:12,937:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "lypYxYh7yCRl5v5fzLYoJKr1mmaMteWGon6vANs6XUkjfjPjX3yqYpqyhpmR8xeZvPWEsrYZS84M8butc4c3gnaetjIzpV_6mUB3i8mMBdSt84LluMoMgduPfnvMbOI_9_1BofY6zDpV2Oh_XOzTr-R7HjoeNLPKX9-JH-Qa8oNvWKTuBJ-IVUPOSJSz1kT70p6Acom1Cm4IVG5r-3gEtmkjXBfjp8HCrAXeiLm5KKNpaqp2vSC-3m4mbyK0iw2sr_MrlWEeTk88-A03y57baDUKq_6KalRMIo59bKXgQzZuPLZqNn4wLlWLfkd2Q_xVNDUNwVqSBtemlw6cmv2ihw"}}, "protected": "eyJub25jZSI6ICIwMUFSaW1BTmJucjNYTnR1RVAzNU5CQUt4bHNPQmhMQXlTNFcxWFFhdnVrIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJzbWVpLnRrIn0sICJyZXNvdXJjZSI6ICJuZXctYXV0aHoifQ", "signature": "OZitSDTrPFZ8lznMskDCFyATPXXspTsJR77wCp6z6_jQCsS-xEJgWawtmM7qF9ksjPGHO8epUUgiUaqNEMdKWaZSj_9nOPM973JkVlBYu-SR8gOKBQbsoH0jP6-EAgsMj6PLsQmrc2N6UgORj0bcM-OpdqiBPqJA0T29m7Ox0GAkXpZFyoOL1110N9vK_OBPDB3xDdX-v9UcQI07OuhdXG7UcEKp3518weLnU5r5JMAms2Wlt9POFB0ZW2jfHrr-ipFoCxcANY_bEQtNcaLIc3RNqtU4upGRjdJNLjfP-8umtMebzCSw12tM61DaKOl49sOeYe4rwC1-Dcj_ST5mEg"}'}
2015-12-04 03:44:12,938:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 03:44:13,312:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 558
2015-12-04 03:44:13,316:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '558', 'Expires': 'Thu, 03 Dec 2015 19:50:15 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:15 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '6ie0nSjCOHfgYYu5GxfqDWXAbY7RrcpTkBZGEoYP--I'}. Content: '{"identifier":{"type":"dns","value":"smei.tk"},"status":"pending","expires":"2015-12-10T19:50:15.567013088Z","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw/560111","token":"QDfg1Uz6X3fQ0YdxQ8_bM2MwqQbYJ9ZNtc3hGQ8yexQ"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw/560112","token":"IWLFyXoS5VP8gemcVtc_Ima4atmHebE1dOcLZA_QM2c"}],"combinations":[[1],[0]]}'
2015-12-04 03:44:13,316:DEBUG:acme.client:Storing nonce: "\xea'\xb4\x9d(\xc28w\xe0a\x8b\xb9\x1b\x17\xea\re\xc0m\x8e\xd1\xad\xcaS\x90\x16F\x12\x86\x0f\xfb\xe2"
2015-12-04 03:44:13,316:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '558', 'Expires': 'Thu, 03 Dec 2015 19:50:15 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:15 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '6ie0nSjCOHfgYYu5GxfqDWXAbY7RrcpTkBZGEoYP--I'}): '{"identifier":{"type":"dns","value":"smei.tk"},"status":"pending","expires":"2015-12-10T19:50:15.567013088Z","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw/560111","token":"QDfg1Uz6X3fQ0YdxQ8_bM2MwqQbYJ9ZNtc3hGQ8yexQ"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/a61uJvEfCyr5VxaJukXuinxYmJg8-KjBcsHWQs9wztw/560112","token":"IWLFyXoS5VP8gemcVtc_Ima4atmHebE1dOcLZA_QM2c"}],"combinations":[[1],[0]]}'
2015-12-04 03:44:13,317:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, status=None, combinations=None, challenges=None
2015-12-04 03:44:13,318:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "*.smei.tk"}, "resource": "new-authz"}
2015-12-04 03:44:13,319:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jwk=None, x5u=None, kid=None, alg=None, cty=None, x5tS256=None, jku=None, x5t=None
2015-12-04 03:44:13,327:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, x5u=None, kid=None, cty=None, x5tS256=None, jku=None, x5t=None, nonce=None
2015-12-04 03:44:13,327:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "lypYxYh7yCRl5v5fzLYoJKr1mmaMteWGon6vANs6XUkjfjPjX3yqYpqyhpmR8xeZvPWEsrYZS84M8butc4c3gnaetjIzpV_6mUB3i8mMBdSt84LluMoMgduPfnvMbOI_9_1BofY6zDpV2Oh_XOzTr-R7HjoeNLPKX9-JH-Qa8oNvWKTuBJ-IVUPOSJSz1kT70p6Acom1Cm4IVG5r-3gEtmkjXBfjp8HCrAXeiLm5KKNpaqp2vSC-3m4mbyK0iw2sr_MrlWEeTk88-A03y57baDUKq_6KalRMIo59bKXgQzZuPLZqNn4wLlWLfkd2Q_xVNDUNwVqSBtemlw6cmv2ihw"}}, "protected": "eyJub25jZSI6ICI2aWUwblNqQ09IZmdZWXU1R3hmcURXWEFiWTdScmNwVGtCWkdFb1lQLS1JIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICIqLnNtZWkudGsifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "bjU1jwzZ9-W_WOlNZxck-gGFmXTn5DJQwKbZSE5hLI6ps67ZAJMzqI4qDZRFEAME-iT5cwa1Oj7fO7QPYFETd_XIPSgLIzCgfRlmujHPYJ97pjr1mqEl_dxHOYHiZO--DBb9W63CnYrZPYkUCnneNc-gJ0Y2ncdxpebMiK-hp47TP9w2KJF2lqm20OyG2YAXmPA36bDWIY4UeYPfhaiChLg7GKZ8wKOhLJdSf57Od5vwNI750YDaJQmdnPn28kylNiog9NZ2c4Q3IvrgActDYILwwGUVgDurUTllWQSXeudEpv2BWX25fNa27fZCvmyLotk2v-64hHNL3xV7_BUEyg"}'}
2015-12-04 03:44:13,328:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 03:44:13,659:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 400 117
2015-12-04 03:44:13,663:DEBUG:root:Received <Response [400]>. Headers: {'Content-Length': '117', 'Expires': 'Thu, 03 Dec 2015 19:50:16 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:16 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'neZdq64UtoKYbRwW3D6R8xRlTjZB1OIu8xDM8vrIeJ8'}. Content: '{"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Invalid character in DNS name","status":400}'
2015-12-04 03:44:13,664:DEBUG:acme.client:Storing nonce: '\x9d\xe6]\xab\xae\x14\xb6\x82\x98m\x1c\x16\xdc>\x91\xf3\x14eN6A\xd4\xe2.\xf3\x10\xcc\xf2\xfa\xc8x\x9f'
2015-12-04 03:44:13,664:DEBUG:acme.client:Received response <Response [400]> (headers: {'Content-Length': '117', 'Expires': 'Thu, 03 Dec 2015 19:50:16 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Dec 2015 19:50:16 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'neZdq64UtoKYbRwW3D6R8xRlTjZB1OIu8xDM8vrIeJ8'}): '{"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Invalid character in DNS name","status":400}'
2015-12-04 03:44:13,666:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 470, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 323, in _auth_from_domains
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 634, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 550, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Invalid character in DNS name
```

Two problems:
- why wildcard name was suggested?
- why code for detecting wildcard domain names wasn't triggered?

**Comment by dbanet** [comment] 2015-12-03 20:03
You can address me in this issue ticket directly if any additional information is required or for any other reasons necessary.

**Comment by bmw** [comment] 2016-08-25 22:43
Dupe of #822

**Closed by bmw** 2016-08-25 22:43 UTC
Labels: apache
