### ISSUE TITLE
webroot plugin can't handle unicode webroot paths

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#5512] opened 2018-01-29 05:04 UTC
## My operating system is (include version):
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
# ./certbot-auto --version
certbot 0.21.1
```

## I ran this command and it produced this output:
```
$ sudo ~/Downloads/certbot-auto certonly --authenticator webroot -w "/tmp/montaña.com" --installer none  -d a.foo.monkas.xyz --dry-run                                                                             
Saving debug log to /var/log/letsencrypt/letsencrypt.log                                                
Plugins selected: Authenticator webroot, Installer None                                                 
Obtaining a new certificate                                                                             
Performing the following challenges:                                                                    
http-01 challenge for a.foo.monkas.xyz                                                                  
Using the webroot path /tmp/montaña.com for all unmatched domains.                                      
Cleaning up challenges                                                                                                                                                                                             
Encountered exception during recovery                                                                   
'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)                                                                                                                                     
Traceback (most recent call last):                                                                      
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered                                                                                           self.funcs[-1]()                                                                                    
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges                                                                                         self.auth.cleanup(achalls)                                                                          
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 215, in cleanup                                                                                              
    validation_path = self._get_validation_path(root_path, achall)                                      
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 189, in _get_validation_path                                                                                     return os.path.join(root_path, achall.chall.encode("token"))                                        
  File "/opt/eff.org/certbot/venv/lib/python2.7/posixpath.py", line 73, in join                                                                                                                                        path += '/' + b                                                                                     
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)                                                                                                                 
An unexpected error occurred:                                                                           
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)                                                                                                                 Please see the logfiles in /var/log/letsencrypt for more details.                                       
```

## Certbot's behavior differed from what I expected because:
Certbot should handle unicode paths without an issue.

See https://community.letsencrypt.org/t/problem-with-special-characters/51629 for original report

Applying `.decode('utf-8')` to `root_path` in the webroot plugin seems to take care of it but perhaps there are other code paths that should be looked at as well.

**Comment by SwartzCr** [comment] 2018-01-29 21:58
Closing as a duplicate of #5236
The overall utf-8 issue is #4516 which I think should be prioritized for the next milestone

**Closed** 2018-01-29 21:59 UTC
Labels: area: code health, duplicate
