### ISSUE TITLE
Ensure image is automatically built on Docker Hub

### ISSUE THREAD

**Issue by robwithhair** [certbot/certbot#6244] opened 2018-07-19 13:06 UTC
The docker hub version is still at v0.26.0 not v0.26.1

**Comment by bmw** [comment] 2018-07-19 18:03
Thanks for pointing this out @robwithhair. 0.26.1 versions of each image are building now.

I'm not sure why this happened though since we have automated builds set up which trigger anytime a new tag is pushed. This has worked in the past, however, someone other than me committed and pushed the tag for 0.26.1 which may have caused the problem.

I may have fixed it, but I'm not sure. @ohemorange, sometime I'd like to see if we hit this issue again when you do another release. I'm putting this issue in this milestone so we see it for now, but we can workout when and how to do this later.

@ohemorange as a small test, can you see if a "rolling" build is triggered at https://hub.docker.com/r/certbot/certbot/builds/ the next time you merge a PR?

**Comment by ohemorange** [comment] 2018-07-23 18:37
Does "the next time I merge a PR" mean "I click the squash merge button on github" or "a PR authored by me is merged"?

**Comment by ohemorange** [comment] 2018-07-23 18:47
Yes, unless something else triggered a rolling build at the exact same time as I merged a PR, me merging PRs does seem to trigger a rolling build.

**Comment by bmw** [comment] 2018-07-23 19:04
Nice! I meant when you click the squash and merge button on GH.

Since the issue could be caused by Docker being set up through my account rather than the organization, it'd be good to see if you (or anyone else besides me) merging a PR that I didn't write triggers a build too if you remember to check.

**Comment by ohemorange** [comment] 2018-07-30 23:33
Checks out, PR I authored triggers rolling build.

**Comment by bmw** [comment] 2018-07-30 23:57
Nice! I'm feeling pretty good that this is fixed, but we should verify the non-rolling build is triggered the next time you push a release tag.

**Comment by bmw** [comment] 2018-09-05 23:56
This has been fixed.

**Closed by bmw** 2018-09-05 23:56 UTC
Labels: area: pkging
