### ISSUE TITLE
old problem, see as interface bug, the stop to renew by "Cert not yet due for renewal"

### ISSUE THREAD

**Issue by ppKrauss** [certbot/certbot#5065] opened 2017-08-31 14:00 UTC
After `service nginx restart` ok, `certbot renew --dry-run` ok... Try `certbot renew` and "Cert not yet due for renewal" message. No clues about what to do. It is an interface/communication bug. No objective clue at forum [here](https://community.letsencrypt.org/t/renew-says-cert-not-yet-due-for-renewal-though-it-is-more-than-30-days-old/21182) or [here](https://community.letsencrypt.org/t/renew-says-cert-not-yet-due-for-renewal-though-it-is-more-than-30-days-old/21182).

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/oficial.news.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/oficial.news/fullchain.pem (skipped)
No renewals were attempted.
```

**Comment by SwartzCr** [comment] 2017-08-31 15:31
I feel like this is a duplicate of #5045
which is meant to add more clarity to skipped renewals.
I'm going to close this as a duplicate, but you should feel free to suggest more clarification in  that issue.

**Closed by SwartzCr** 2017-08-31 15:31 UTC
