### ISSUE TITLE
certbot 0.9.3: renew-hook is not called from cli

### ISSUE THREAD

**Issue by apircalabu** [certbot/certbot#3943] opened 2016-12-21 02:50 UTC
Or maybe I'm missing something. When trying to test the hooks during renewal I couldn't get --renew-hook to work, no matter what.
Using certbot-0.9.3-1.el7.noarch on CentOS 7 installed from EPEL repository. See below the command output, pre & post hooks are called, but renew isn't.

```
time /usr/bin/certbot renew --pre-hook "echo In pre-hook: Hi" --post-hook "echo In post-hook: Ho" --renew-hook "echo In renew_hook: RENEWED_LINEAGE=${RENEWED_LINEAGE} RENEWED_DOMAINS=${RENEWED_DOMAINS}"
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/dom1.net.au.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Running pre-hook command: echo In pre-hook: Hi
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for dom1.net.au
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /etc/letsencrypt/keys/0014_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0014_csr-certbot.pem

-------------------------------------------------------------------------------
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/dom1.net.au/fullchain.pem
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/dom2.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/dom2.net.au/fullchain.pem (skipped)
Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/dom1.net.au/fullchain.pem (success)
Running post-hook command: echo In post-hook: Ho

real	0m7.679s
user	0m2.034s
sys	0m0.302s
```

What further information should I provide?
Thanks.

**Comment by pde** [comment] 2016-12-21 20:05
In Certbot 0.9.3, you need to provide `--renew-hook` on the command line to the `renew` command (that will be fixed in 0.10.0; see #3394 ), and note that it doesn't generate a log message when it runs (it should, and that's fixed in 0.10.0), and that it doesn't run unless something is actually renewed (which is a feature, not a bug ;)).

**Closed by pde** 2016-12-21 20:05 UTC

**Comment by apircalabu** [comment] 2016-12-22 00:11
Thanks for looking into it. Unfortunately I'm afraid I still can't get the renew-hook right, see below. Am I using the wrong command line options? Whatever I tried, I just couldn't get the renew-hook to "echo" or "touch" anything, very hard to test the renewal hook.

```
time /usr/bin/certbot renew --renew-hook "echo In renew_hook: RENEWED_LINEAGE=${RENEWED_LINEAGE} while^CENEWED_DOMAINS=${RENEWED_DOMAINS}"
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww5.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww4.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww7.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww6.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww8.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww2.dom.net.au.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for ww2.dom.net.au
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0072_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0072_csr-certbot.pem

-------------------------------------------------------------------------------
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/ww2.dom.net.au/fullchain.pem
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww3.dom.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/ww2.quick.net.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/ww5.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww4.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww7.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww6.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww8.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww3.dom.net.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/ww2.quick.net.au/fullchain.pem (skipped)
Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/ww2.dom.net.au/fullchain.pem (success)
```

**Comment by apircalabu** [comment] 2016-12-22 00:17
If this helps: I'm testing the renewal by forcing "renew_before_expiry = 130 days" in /etc/letsencrypt/renewal/ww2.dom.net.au.conf, while the default setting is afaik 30 days. Could this cause the renew hook to not run?
