### ISSUE TITLE
certbot homebrew install on osx generating broken shebangs

### ISSUE THREAD

**Issue by gmatty** [certbot/certbot#3464] opened 2016-08-29 14:02 UTC
The shebang in file: /usr/local/Cellar/certbot/0.8.1/libexec/bin/certbot  is:

> # !/usr/bin/python

when it should be: 

> # !/usr/bin/env  python

This is causing a variety of unexpected behaviors for those who are not using the supplied OSX python install as pip is not installing dependancies there. So while the system is reporting the dependancies are present, certbot is running from a python without them or with older versions.

For some myself this manifested as:

> AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by cowlicks** [comment] 2016-08-30 01:00
Could you try updating to 9.0?

**Comment by bmw** [comment] 2016-09-14 22:17
Any thoughts @DomT4?

**Comment by DomT4** [comment] 2016-09-15 04:13
I'm a little confused unless they can provide a little more comprehensive a reproduction process, to be honest.

All formulae in Homebrew that use Python resources _(are supposed to)_ install those resources into `libexec/vendor` under [the old](https://github.com/Homebrew/homebrew-core/blob/e4f74167c8f13f775a0f74735c48c603f1b3fa12/Formula/certbot.rb#L20-L182) vendoring system, and just `libexec` under [our newer virtualenv-based](https://github.com/Homebrew/homebrew-core/blob/d9f460671a4c87ae9e28120227fe3bb706b60c40/Formula/certbot.rb#L21-L166) system. As far as I'm aware we're missing no resources there that would cause a fallback to a globally user-installed one if available.

Those resources don't live outside the keg, aren't "publicly" available _(by design)_, and install in the same way regardless of whether using Homebrew's Python or the system Python. Changing a shebang shouldn't fix anything about the way `certbot` runs in Homebrew, unless you've done something like fun like remove `/usr/bin/python`.

I'm not really sure what to recommend unless OP can provide a bit more information.

**Comment by bmw** [comment] 2018-11-16 00:50
Since we never got more info about this and this issue hasn't seen any updates since 2016, I'm closing it. If anyone is still hitting this, please comment or open a new issue, potentially one against Homebrew.

**Closed by bmw** 2018-11-16 00:50 UTC
Labels: area: macOS, more-info
