### ISSUE TITLE
urllib2 ImportError: cannot import name HTTPSHandler

### ISSUE THREAD

**Issue by fiee** [certbot/certbot#2757] opened 2016-04-04 16:13 UTC
Calling letsencrypt-auto fails with:

```
Checking for new version...
Traceback (most recent call last):
  File "/tmp/tmp.FrWBbDP9Fu/fetch.py", line 20, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler, HTTPError
ImportError: cannot import name HTTPSHandler
```

If I call Python and issue the same import statement, I get no errors. How can I make sure which Python binary letsencrypt uses?

System: Ubuntu Trusty with Python 2.7.11 from ppa:fkrull/deadsnakes-python2.7

**Comment by fiee** [comment] 2016-04-04 16:36
With `--no-self-upgrade` it becomes:
```
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2339, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
```
But seems to upgrade anyway.

**Comment by pde** [comment] 2016-04-04 16:38
There's an environment variable called `LE_PYTHON` that letsencrypt-auto uses to create a virtualenv on first run, and to upgrade the virtualenv if a new release has occurred (CC: @erikrose I'm not sure that's a sensible state of affairs... maybe it use that variable only at first run and save it afterwards, or always use it?).

Try setting that, though I suspect you'll need to delete your venv in `~/.local/share/letsencrypt`, and let us know if that works.

**Comment by fiee** [comment] 2016-04-04 16:59
Thank you. `LE_PYTHON` was not set, and setting it doesn’t change anything.

I deleted the venv already several times, also tried to install it myself, but that didn’t help.
The venv is incomplete, the path might be a problem:
```
$ ~/.local/share/letsencrypt/lib/python2.7# which pip
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/usr/local/bin/pip
```
If I setup a new venv in a different location, it’s complete.
Can I change LE’s venv path (without touching the sources)?

**Comment by fiee** [comment] 2016-04-04 17:09
Next step: I created a new venv in `~/testenv` and activated it. Now I get as far as
```
# ./letsencrypt-auto --config /etc/letsencrypt/configs/fiee.conf --debug certonly
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --config /etc/letsencrypt/configs/fiee.conf --debug certonly
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1993, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 690, in obtain_cert
    le_client = _init_le_client(config, authenticator, installer)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 214, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 183, in __init__
    acme = acme_from_config_key(config, self.account.key)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 41, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 627, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 574, in _check_response
    raise errors.ClientError(response)
ClientError: <Response [502]>
```

**Comment by pde** [comment] 2016-04-07 19:02
Suggestion from @erikrose: try setting PATH such that the python you want to use comes first.

**Comment by AronNovak** [comment] 2016-05-03 13:46
I can reproduce this on CentOS 6.7 Python 2.6:
```
1993 packages excluded due to repository priority protections
Package 1:mod_ssl-2.2.15-47.el6.centos.4.x86_64 already installed and latest version
Nothing to do
Checking for new version...
Traceback (most recent call last):
  File "/tmp/tmp.4JBN6LuhiJ/fetch.py", line 20, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler, HTTPError
ImportError: cannot import name HTTPSHandler
```

I tried with master branch, also with v0.4.0 tag, with the same result.

**Comment by fiee** [comment] 2016-05-30 10:09
With the latest version, it still works for me only if I activate a virtual environment first that is not below `.local`

**Comment by Xarkam** [comment] 2016-06-08 17:42
Hello, 
I have exactly same error on ubuntu 14.04.4

**Comment by Elronnd** [comment] 2016-11-20 07:42
I had this issue on FreeBSD, and it had to do with python being linked incorrectly.  Reinstalling OpenSSL and python fixed it.

**Comment by bmw** [comment] 2018-12-07 02:02
We haven't seen any reports of this problem since 2016 so I'm closing this issue. If someone is still hitting it, please comment or open a new issue.

**Closed by bmw** 2018-12-07 02:02 UTC
Labels: area: certbot-auto, question
