### ISSUE TITLE
Certbot delete might delete all certificates

### ISSUE THREAD

**Issue by gnd** [certbot/certbot#6218] opened 2018-07-13 11:01 UTC
I was recently cleaning up some certificates using `certbot-auto delete` and ran into an issue by involuntarilly pressing Enter, which immediately started deleting all certificates. I think this is a pretty bad UX decision to have [Enter] as a "delete-all". 

My exact situation was that i was using screen and had to go up the buffer to see a specific number of a certificate to be deleted (by using screens ctrl + a +[). On return from the buffer i usually press enter several times, this resulted in deleting a lot of certificates. (Older certbot versions did not have enter as a delete-all)

Could you please consider to 

- a, either have the user type 'all' to delete all certificates
- b, to use [Enter] but have user confirm the action ? 

Thanks !

**Comment by schoen** [comment] 2018-07-16 22:47
@ohemorange, could I get you to opine on what you think the right behavior here would be? Do you think the current approach is reasonable or that it ought to be reworked somehow?

**Comment by ohemorange** [comment] 2018-07-30 23:36
@schoen sounds like this is a good subject for running usability tests with different versions!

**Comment by bmw** [comment] 2019-06-13 18:34
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.

**Comment by beret** [comment] 2019-12-05 01:24
This issue/enhancement is still relevant and unresolved in the current PPA codebase. An explicit wildcard selection may be more suited to provide delete all.

As it stands, an errant <enter> can efficiently wreck an environment.

**Comment by osirisinferi** [comment] 2020-12-17 17:55
Hasn't this been fixed in #8349?

**Comment by bmw** [comment] 2020-12-17 18:09
Indeed it was! Thanks for pointing that out and for writing the PR that fixed this issue.

**Closed by bmw** 2020-12-17 18:09 UTC
Labels: area: cert management, area: ui / ux, feature request, usability-test-candidate

**Comment by mj2015** [comment] 2022-12-30 11:26
Well, this is interesting. Yesterday, I used a remote control tool to go in to delete a single certificate on a machine that has about 40 certificates. Due to a glitch in the remote control software, it sent my enter key more than once. So the `sudo certbot delete` `Enter` got sent as multiple `Enter` keys. The prompt is "select the domains or press Enter for all, so it went ahead and deleted all of the certificate information. I don't believe I saw a confirmation for this.

Looking at the "fix" it appears that the default on the confirmation is Y, so even if it was "confirmed", it would go ahead anyway. That's poor user interface. Far better to default to No and then sit waiting for the next action - someone who really wants to delete all their certificates can repeat easily. To get my certificates back, I had to edit all the nginx files to remove the certificate information and then start over.

So, to me, this is something that still needs fixing, as the ability to just press Enter repeatedly (accidentally or deliberately) should not delete all certificates without some further different key press confirmation.

**Comment by schoen** [comment] 2022-12-30 19:11
@mj2015 I just made a pull request for this at https://github.com/certbot/certbot/pull/9524 (not sure how the current developers will view this).

**Comment by alexzorin** [comment] 2022-12-30 20:39
I can't reproduce this anecdote. What version of Certbot was it from?

    $ sudo -E certbot delete
    Saving debug log to /var/log/letsencrypt/letsencrypt.log

    Which certificate(s) would you like to delete?
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    1: example.com
    2: example.org
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Select the appropriate numbers separated by commas and/or spaces, or leave input
    blank to select all options shown (Enter 'c' to cancel):

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    The following certificate(s) are selected for deletion:

      * example.com
      * example.org

    WARNING: Before continuing, ensure that the listed certificates are not being
    used by any installed server software (e.g. Apache, nginx, mail servers).
    Deleting a certificate that is still being used will cause the server software
    to stop working. See https://certbot.org/deleting-certs for information on
    deleting certificates safely.

    Are you sure you want to delete the above certificate(s)?
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o:
    (Y)es/(N)o: ^CExiting due to user request.

The default on this line:

https://github.com/certbot/certbot/blob/b81ef33f33d69451f1ab981583240a1bac79f7c0/certbot/certbot/_internal/cert_manager.py#L110-L111

only controls the behavior when Certbot is running in `--non-interactive` mode. The user is forced to type `y` or `n` otherwise.

>So, to me, this is something that still needs fixing, as the ability to just press Enter repeatedly (accidentally or deliberately) should not delete all certificates without some further different key press confirmation.

Agreed, and it doesn't.

**Comment by schoen** [comment] 2022-12-30 20:57
I didn't actually do this experiment, so if the behavior is as you
describe, my PR is probably not worthwhile to merge. :-)  (as the existing
behavior would be appropriate for noninteractive, in my opinion)

**Comment by mj2015** [comment] 2022-12-30 21:01
Just checked and certbot —version gives 0.40.0. This is on Ubuntu 20.04 LTS.Perhaps certbot isn’t updated in the normal way?Matthew JonesSent from my iPadOn 30 Dec 2022, at 20:39, alexzorin ***@***.***> wrote:﻿
I can't reproduce this anecdote. What version of Certbot was it from?
$ sudo -E certbot delete
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which certificate(s) would you like to delete?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: example.com
2: example.org
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The following certificate(s) are selected for deletion:

  * example.com
  * example.org

WARNING: Before continuing, ensure that the listed certificates are not being
used by any installed server software (e.g. Apache, nginx, mail servers).
Deleting a certificate that is still being used will cause the server software
to stop working. See https://certbot.org/deleting-certs for information on
deleting certificates safely.

Are you sure you want to delete the above certificate(s)?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o:
(Y)es/(N)o: ^CExiting due to user request.

The default on this line:
https://github.com/certbot/certbot/blob/b81ef33f33d69451f1ab981583240a1bac79f7c0/certbot/certbot/_internal/cert_manager.py#L110-L111
only controls the behavior when Certbot is running in --non-interactive mode. The user is forced to type y or n otherwise.

So, to me, this is something that still needs fixing, as the ability to just press Enter repeatedly (accidentally or deliberately) should not delete all certificates without some further different key press confirmation.

Agreed, and it doesn't.

**Comment by osirisinferi** [comment] 2022-12-30 21:05
The feature which fixed this issue has only been part of Certbot since version 1.10.0, so would not have been around yet in your version 0.40.0. In that version, no confirmation was required at all.

To upgrade Certbot, it's probably a good idea to use `snap` to install Certbot. See https://certbot.eff.org/ for more details.
