### ISSUE TITLE
'ascii' codec can't encode characters in position 307-309

### ISSUE THREAD

**Issue by 978740431** [certbot/certbot#4775] opened 2017-06-04 04:48 UTC
`certbot renew --dry-run`

`Attempting to renew cert from /etc/letsencrypt/renewal/www.goodinvoice.com.conf produced an unexpected error: 'ascii' codec can't encode characters in position 307-309: ordinal not in range(128). Skipping.`

I use  
CentOS Linux release 7.3.1611 (Core)

Linux ip-172-31-1-162 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by schoen** [comment] 2017-06-04 04:57
Hi @978740431, this is probably an instance of a known bug (although I'm not positive whether it's been reported here yet) where Certbot can't display the error message that the certificate authority returned because it quotes non-ASCII text from your own web site. This is normally encountered when your web site sends a 404 not found error in response to a renewal of a certificate originally obtained with `--webroot`, and the 404 page contains non-ASCII text which the CA quotes in the error message.

This normally means that your webroot directory was incorrectly specified or has changed somehow. (Of course, we need to fix Certbot to show a more useful error message in this case instead of the Unicode error.)

**Comment by schoen** [comment] 2017-06-04 05:00
This bug is most often due to

https://github.com/certbot/certbot/blob/master/certbot/errors.py#L59

where we implicitly assume that the CA's error message is ASCII-only (which is not required by the spec and is not true in practice when the CA describes some HTTP-01 challenge failures).

**Comment by ynasser** [comment] 2017-06-14 21:20
Yes, this seems to be the same as #4273.

**Comment by schoen** [comment] 2017-06-14 21:28
Oops! Thanks for catching that.

**Comment by billionaire** [comment] 2017-06-14 23:03
Hi. I have similar error:
`An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 257-266: ordinal not in range(128)`
How can i get certificate?
CentOS 6.8 (x64).
Python 2.6.
certbot version: 0.15.0.

**Comment by schoen** [comment] 2017-06-14 23:47
Hi @billionaire,

This is a known bug in Certbot where an error message is displayed incorrectly. @ynasser is in the process of fixing this bug, so a future version of Certbot will give a more useful error message in this case.

This error message normally occurs when you're trying to get a certificate using the `--webroot` method, but when the certificate authority connects to your web server to verify that you control the domain name, it receives an error (such as a 404 not found error). The bug in Certbot results when the error message from your web server contains a non-ASCII character; then Certbot is unable to correctly show you exactly what your server said instead of the expected text.

This generally happens because of a mis-specified webroot path (with `-w`) or an incorrectly configured web server. The directory that you specify with `-w` should be the directory where you would put content in order for it to appear on the top level of your web site. For example, if you were trying to get a certificate for www.example.com and you specified `-w /var/www/html`, that means you're saying that a file created at `/var/www/html/example.txt` will be visible to the public on the web at the URL http://www.example.com/example.txt.

**Comment by schoen** [comment] 2017-06-14 23:49
I'm going to close this particular bug because it's a duplicate of #4273.

@billionaire, if you need any more help figuring out the `-w` option and your web server configuration, please feel free to join us over on the Let's Encrypt Community Forum at https://community.letsencrypt.org/, and we'll do our best to figure out how to help you.

**Closed by schoen** 2017-06-14 23:49 UTC
Labels: area: code health, area: error handling, area: spec-compliance, bug
