### ISSUE TITLE
Could not find ssl_module;

### ISSUE THREAD

**Issue by DevDorrejo** [certbot/certbot#8072] opened 2020-06-11 23:29 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Opensuse TW - 20200610

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
zypper in python3-certbot python3-certbot-apache

## I ran this command and it produced this output:
$ certbot
$ certbot --apache

## Certbot's behavior differed from what I expected because:
show this message: ***Could not find ssl_module; not disabling session tickets.***

## Here is a Certbot log showing the issue (if available):
cat letsencrypt.log
2020-06-11 19:27:43,080:DEBUG:certbot._internal.main:certbot version: 1.4.0
2020-06-11 19:27:43,081:DEBUG:certbot._internal.main:Arguments: ['--apache']
2020-06-11 19:27:43,081:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-06-11 19:27:43,094:DEBUG:certbot._internal.log:Root logging level set at 20
2020-06-11 19:27:43,094:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-06-11 19:27:43,095:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
2020-06-11 19:27:43,203:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.43
2020-06-11 19:27:43,501:WARNING:certbot_apache._internal.configurator:Could not find ssl_module; not disabling session tickets.
2020-06-11 19:27:43,502:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
Initialized: <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7fda9b975b80>
Prep: True
2020-06-11 19:27:43,502:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7fda9b975b80> and installer <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7fda9b975b80>
2020-06-11 19:27:43,502:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2020-06-11 19:27:43,505:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/88336967', new_authzr_uri=None, terms_of_service=None), feac06fadef10b8cabf9523f0f040323, Meta(creation_dt=datetime.datetime(2020, 6, 9, 1, 25, 59, tzinfo=<UTC>), creation_host='static'))>
2020-06-11 19:27:43,505:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-06-11 19:27:43,507:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-06-11 19:27:44,048:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-06-11 19:27:44,048:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 11 Jun 2020 23:27:44 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
"_PcQ5wlirSo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
"keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
"meta": {
"caaIdentities": [
"letsencrypt.org"
],
"termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
"website": "https://letsencrypt.org"
},
"newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
"newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
"newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
"revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-06-11 19:27:45,090:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
File "/usr/bin/certbot", line 11, in <module>
load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
return internal_main.main(cli_args)
File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1347, in main
return config.func(config, plugins)
File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1095, in run
domains, certname = _find_domains_or_certname(config, installer)
File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 422, in _find_domains_or_certname
raise errors.Error("Please specify --domains, or --installer that "
certbot.errors.Error: Please specify --domains, or --installer that will help in domain names autodiscovery, or --cert-name for an existing certificate name.

**Comment by jflopezfernandez** [comment] 2020-06-12 14:55
Hi, @DevDorrejo, do you have `mod_ssl` enabled in your apache configuration file?

**Comment by DevDorrejo** [comment] 2020-06-12 16:17
![image](https://user-images.githubusercontent.com/7697566/84523654-aa4dde80-aca6-11ea-802c-d667f1d2968b.png)

![image](https://user-images.githubusercontent.com/7697566/84523676-b6d23700-aca6-11ea-8c15-d3da76164a39.png)

@jflopezfernandez

**Comment by alexzorin** [comment] 2020-06-12 21:04
This is reproducible in `master`. 

Minor difference: there it is incorrectly detecting the module as being statically linked due to the fallback behavior added in #8007, but the cause and result are otherwise identical.

The root cause seems to be that `self.find_dir("LoadModule")` is coming up with zero matches, which in turn is caused by the parser not processing `/etc/apache2/loadmodule.conf`.

`loadmodule.conf` is only loaded conditionally:

    # generated from default value of APACHE_MODULES in /etc/sysconfig/apache2
    <IfDefine !SYSCONFIG>
      Include /etc/apache2/loadmodule.conf
    </IfDefine>

I believe that this can be fixed by overriding `update_runtime_variables` in `override_suse.py`, similar to what has been done [for other distributions](https://github.com/certbot/certbot/blob/961c573864106f44f352bb6cf1e286f4aea0d172/certbot-apache/certbot_apache/_internal/override_centos.py#L172-L182).

I wonder if openSUSE was always using sysconfig and the issue has only surfaced since Certbot stared sniffing mod_ssl, or whether openSUSE changed their packaging recently?

**Comment by alexzorin** [comment] 2020-06-12 21:31
Ah, that fix would not be right. Certbot's Apache parser is right to not load that file - note the inversion on the `IfDefine`.

What openSUSE is doing in its startup script is prepending `loadmodule.conf` via `-C`:

    exec $apache_bin $server_flags \
            -C "PidFile $pid_file" \
            -C "Include $sysconfd_dir/loadmodule.conf" \
            -C "Include $sysconfd_dir/global.conf" \
            -f $httpd_conf \
            -c "Include $sysconfd_dir/include.conf" \
            "${sysconfig_setting[@]}" \
            $@

We would have to do the same in the the distro-specific overrides for openSUSE.

**Comment by DevDorrejo** [comment] 2020-06-13 02:42
Ok, nice you did found a solution.

**Comment by radoeka** [comment] 2021-02-28 14:17
I've the same issue (using openSUSE too).  What is the solution?

I tried to find the solution referred to above, but I don't see, sorry.
I checked the file mentioned above, found them eventuelly, reviewed the other issues too, but I've still no clue how I can prevent the error/warning message.

Would you/someone be so kind to explain what to do in this case?

**Comment by DevDorrejo** [comment] 2021-03-01 01:46
> I've the same issue (using openSUSE too). What is the solution?
> 
> I tried to find the solution referred to above, but I don't see, sorry.
> I checked the file mentioned above, found them eventuelly, reviewed the other issues too, but I've still no clue how I can prevent the error/warning message.
> 
> Would you/someone be so kind to explain what to do in this case?

use the certbot version from snap or from pip.

**Comment by radoeka** [comment] 2021-03-02 21:00
> use the certbot version from snap or from pip.

I prefer to use the package provided by the distribution.  From #8124 I can conclude, that the version must be newer 1.5.0 or later.  As version 1.11.0 is available, I'll try it with that one.

Just tried it now, unexpected, but I'm still getting the warning :(

```
# certbot --version
certbot 1.11.0

# certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/<fqdn>.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
**Could not find ssl_module; not disabling session tickets.**
Plugins selected: Authenticator apache, Installer apache
Simulating renewal of an existing certificate for
```

Open a new bug report?

**Comment by DevDorrejo** [comment] 2021-03-02 23:34
the new version have this issue fixed, and for those using the pip version this issue non exist.

**Comment by DevDorrejo** [comment] 2021-03-02 23:34
how ever i moved to MicroOS + Podman on the servers and using snap with certbot, is a big solution.

**Comment by radoeka** [comment] 2021-03-03 08:06
> the new version have this issue fixed
What is the new version?  I thought I'm running the latest one (1.11.0).  Is there (even) a newer version?

**Closed** 2021-03-06 03:57 UTC
Labels: area: SUSE, area: apache, bug, priority: significant

**Comment by radoeka** [comment] 2021-03-09 20:00
Please advise: I installed and use certbot 1.13 (released about a week ago, I think), and I still obtain the same warning/output:

```
 # certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/<fqdn>.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
>>>>>>>>>>>   Could not find ssl_module; not disabling session tickets.  <<<<<<<<<<
Plugins selected: Authenticator apache, Installer apache
```
The warning is still there (I added the >>> and <<< markers).

Do I need to change something?
Open a new ticket?

**Comment by DevDorrejo** [comment] 2021-03-10 17:25
create a new ticket

**Comment by BuckDuane** [comment] 2021-07-22 21:23
I am finding the same problem On Mac OS Big Sur 11.5
