### ISSUE TITLE
The nginx plugin is not working;The error was NoInstallationError()

### ISSUE THREAD

**Issue by ray0324** [certbot/certbot#5920] opened 2018-05-03 02:01 UTC
## My operating system is (include version):
CentOS 7 x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-nginx

## I ran this command and it produced this output:

```
crontab -e

01 00 * * * certbot renew --dry-run &> /var/log/certbot.cronlog

```

![fail](https://user-images.githubusercontent.com/5204198/39557163-2f665ab0-4eb8-11e8-9df7-7197d3b8c4f0.jpg)

## I ran this command and it  produced this output:

```
certbot renew --dry-run
```
![ok](https://user-images.githubusercontent.com/5204198/39557213-7d6c512e-4eb8-11e8-9f7a-59fad0d59313.jpg)

**Comment by bmw** [comment] 2018-05-03 17:02
The problem is the `nginx` executable isn't in your `PATH` in your cron environment.

**Comment by bmw** [comment] 2018-05-03 21:52
I'm going to close this issue because resolving that should solve your problem, but feel free to comment if you'd like me to reopen.

**Closed by bmw** 2018-05-03 21:52 UTC
