### ISSUE TITLE
Trouble parsing Apache configuration or updating via git

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#3686] opened 2016-10-24 21:07 UTC
https://community.letsencrypt.org/t/cant-renew-certs-letsencrypt-auto-renew-parsing-error-w-apache2-conf/21640

It's not clear whether this is a current problem with the Apache parser, or something that's been fixed but where the fix couldn't be applied because the user couldn't update via git.

**Comment by underarock** [comment] 2016-10-25 16:25
Here's the same info in Gist: https://gist.github.com/underarock/14fda2f4c1d84006897f1fcf88bfba80

One cert expires soon. Any recommendation for a fix?

**Comment by bmw** [comment] 2016-10-26 00:15
This is strange. We use Augeas to parse Apache configuration files and it is reporting an error when parsing `apache2.conf`. However, I took your `apache2.conf` file, used it on an Ubuntu 16.04 system with Apache 2.4 and successfully renewed and obtained certificates with Certbot. Perhaps it's catching errors in another file referenced by `apache2.conf`, but reporting them here? I've never seen this before.

Any thoughts @domcleal?

@underarock, ideally we can get this problem fixed for you before your cert expires, but if not, I have a workaround for you assuming Apache is serving files out of a document root for each domain in the certificate that expires soon. If this is the case, you can run `opt/letsencrypt/certbot-auto certonly --webroot` and it will walk you through the process of renewing the cert. When prompted for domains, enter **every domain name** in the certificate that is about to expire. When asked for webroots, provide the path to the directory that Apache is serving files out of for that domain.

After Certbot exists, you should have your renew certificate. Run `sudo apache2ctl -k graceful` to have Apache start using your new certificates.

**Comment by underarock** [comment] 2016-10-26 02:36
@bmw Thanks for the workaround. Tried it on the first domain (for which the cert had just expired) and it said it worked. However, the cert was created in `/etc/letsencrypt/live/website.com-0001` instead of the original `/etc/letsencrypt/live/website.com`. Updated the SSL statements in `/etc/sites-available/website.com.conf` to reflect the -0001 and that worked.

I remember seeing the -0001 issue somewhere in LetsEncrypt support (haven't re-searched for it), so not sure what the implications of that are, nor what should be done to 'fix' it, if anything.

**Comment by domcleal** [comment] 2016-10-26 09:23
> This is strange. We use Augeas to parse Apache configuration files and it is reporting an error when parsing apache2.conf. However, I took your apache2.conf file, used it on an Ubuntu 16.04 system with Apache 2.4 and successfully renewed and obtained certificates with Certbot. Perhaps it's catching errors in another file referenced by apache2.conf, but reporting them here? I've never seen this before.
> 
> Any thoughts @domcleal?

Sorry, no. I downloaded the raw file from the gist, ran it against the lens in master (`augtool -I certbot-apache/certbot_apache/augeas_lens/ -t 'Httpd incl /tmp/cb' print /files/tmp/cb`) and it parses fine.

I can only conclude that the file in the gist isn't identical to what's on the system (e.g. line endings which might not be preserved via a gist, or it's been edited in some way, such as removing comments) or certbot's not up to date. The latest change to the Augeas lens was in v0.9.1.

**Comment by underarock** [comment] 2016-10-26 16:55
**Thanks @bmw and @domcleal for your help.**

@bmw I think you may well be onto it when you said:
> Perhaps it's catching errors in another file referenced by apache2.conf, but reporting them here?

There is a conf file that would be included in the `IncludeOptional sites-enabled/*.conf` for an unused subdomain that incorrectly had its A record removed, now re-added.

I'll post back here whether this fixes the error or not. Assuming it will, any way to have the error more 'accurately' reflect the cause or source? (And my bad for not picking up on the referenced files in the first place!)

**Comment by bmw** [comment] 2016-10-26 17:40
> EDIT: I see what likely caused the -0001 was that I included the domain and one subdomain, but left out www #unforcedError

Yes, this is what caused the problem. Making sure you use the existing path will be easier in our next release. See #3615 if you're curious.

> There is a conf file that would be included in the IncludeOptional sites-enabled/*.conf for an unused subdomain that incorrectly had its A record removed, now re-added.

I unfortunately doubt this is the problem. Augeas knows nothing about A records. It simply parses Apache configuration files.

> I'll post back here whether this fixes the error or not. Assuming it will, any way to have the error more 'accurately' reflect the cause or source? (And my bad for not picking up on the referenced files in the first place!)

On Certbot's end, not that I'm aware of. We're simply reporting the error given to use by Augeas.

**Comment by underarock** [comment] 2016-10-26 18:07
**Fixed! Thanks to your comment, @domcleal:**
> I can only conclude that the file in the gist isn't identical to what's on the system (e.g. line endings which might not be preserved via a gist, or it's been edited in some way, such as removing comments)

Indeed, comments had been stripped out as some were internal/not safe to post. Removing all comment lines and running `/opt/letsencrypt/certbot-auto renew` successfully renewed all expiring certs.

Have NO idea what in the comments would have caused this error. There were no trailing spaces and every comment line began with `# `. Will investigate to see what was wrong there.

**Again, thank you @bmw and @domcleal for your help!**

**Comment by underarock** [comment] 2016-10-26 18:30
BTW, `apachectl configtest` both before and after stripping comments from the apache2.conf file returned, `Syntax OK`. Not sure what bearing that might have on the error, but may be worth noting.

**Comment by bmw** [comment] 2016-10-26 18:41
@underarock, I'm glad you figured it out! If you can provide an example of a comment that causes the error, we'll look into getting it fixed.

**Comment by underarock** [comment] 2016-10-26 19:31
Not sure if it will help, but here are all the removed comment lines with [a-z] and [0-9] replaced with 'a' and '8' respectively: https://gist.github.com/underarock/43638dfbf687b7170513dee6ba297e01

Hopefully it's just a Luddite error on my part that's easy to spot.

**Comment by bmw** [comment] 2016-10-26 20:17
Nothing stands out to me and that change seems to have fixed the problem as Augeas seems to be able to parse the file without issue.

**Comment by domcleal** [comment] 2016-10-27 07:10
It's likely a combination of comments and the original file contents - not _just_ comments, or _just_ the directives. The two together in their original format.

**Comment by underarock** [comment] 2016-10-27 20:23
Gist updated to included original file content + regexed comments: https://gist.github.com/underarock/43638dfbf687b7170513dee6ba297e01

Not critical that I understand what was wrong, though it might prove helpful since, as far as I can tell, the file was OK per Apache standards...

**Comment by domcleal** [comment] 2016-10-28 07:03
Thanks, that was much more helpful. I reproduced it and it fails on line 213 which contains a comment ending in a backslash followed by a blank line. If it's followed by another comment then it parses fine, but not with the blank line.

I opened https://github.com/hercules-team/augeas/issues/423 to track a fix in Augeas.

**Comment by underarock** [comment] 2016-10-28 15:04
Fantastic, glad to know the cause. **Thanks very much for following through**, especially given the piecemeal way I provided the info. :-(

Maybe this will help someone else avoid the headache, self-induced or otherwise.

**Comment by joohoi** [comment] 2017-09-27 11:21
Is this issue still relevant or should we close it?

**Comment by underarock** [comment] 2017-09-27 15:21
Close it, please. Thanks.

**Closed** 2017-09-27 21:10 UTC
Labels: area: apache, area: certbot-auto
