### ISSUE TITLE
Can't import _io (requires deleting old virtualenv)

### ISSUE THREAD

**Issue by schoen** [certbot/certbot#2332] opened 2016-02-01 19:58 UTC
Someone on the community forums came across a problem with Python refusing to import `_io` a while ago:

https://community.letsencrypt.org/t/cant-use-letsencrypt-auto-importerror-no-module-named--io/2345/3

The solution required deleting and recreating the virtualenv. Unfortunately, people are still running into this; someone reported #2329 today which was exactly the same problem (with the same solution). Why does this happen, and how can we make it so that people don't have to recreate their virtualenvs?

**Comment by pde** [comment] 2016-02-02 22:41
@erikrose any insight into the causes here.  The real solution is to ship the new leauto, which we might be able to do quite soon if test reports haven't been indicating too much breakage...

**Comment by erikrose** [comment] 2016-02-02 23:47
I'm confident in the new le-auto and recommend we ship it with 0.4.0. At this point, it's much better than the old one, we can patch up most anything that goes wrong with it because it's self-updating, and we've vetted it on our test farm and on a variety of real-world systems. The only bugs we've found to fix since 0.3.0 have been a cosmetic thing and a few py2.6 packages that got left out due to pip caching bugs and the evils of conditional dependencies.

Out of 11 tests this round, we found no solid evidence of regressions. 9 worked great. 1 found a deficiency in our FreeBSD bootstrapper that also exists in the old le-auto. The only real failure is something on a beta version of OS X 10.11 that required the user to remove their venv, after which it worked, even to the point of actually installing a certificate. (I requested logs but haven't heard back yet.)

Let's ship the sucker!

**Comment by erikrose** [comment] 2016-02-02 23:53
My guess at this fellow's `_io` problem is that something crashed midway through creating his original virtualenv, and he never got the io module linked in. Of course, it's impossible to tell for sure now: the evidence is destroyed, and we have no logs. So I move we ship the new le-auto and close this.

**Comment by erikrose** [comment] 2016-02-09 18:06
With the merge of #2383, the new le-auto, which recreates venvs as necessary, will ship with 0.4.0. le-auto will recreate the venv with each new version of LE, bulldozing through any bad state. It's still conceivable that a bad venv could persist *until* a new version comes out, iff venv setup fails *after* the letsencrypt script is installed, but it's unlikely, since only letsencrypt-apache and mock are installed after it. To close that gap, we should add `rm -rf "$VENV_PATH"` to the `if` clause that handles peep errors.

**Comment by schoen** [comment] 2016-02-11 05:03
Well, the new le-auto was just shipped in 0.4.0 so I'll regard this as resolved for the time being. Thanks @erikrose for your work on that.

**Comment by erikrose** [comment] 2016-02-11 21:08
Actually, let's keep this open, and we'll use it to track automatic deletion of incompletely built venvs.

**Comment by prusswan** [comment] 2017-03-31 10:14
automatic deletion does not work. had to manually purge the old virtualenv in `~/.local/share/letsencrypt`

**Comment by erikrose** [comment] 2017-03-31 14:49
Let's at least get this under test.

**Closed** 2020-07-18 07:18 UTC
Labels: has pr, needs-update, question
