### ISSUE TITLE
Revoke by key should check keys

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4805] opened 2017-06-08 20:27 UTC
You can revoke a certificate using the corresponding private key by passing `--key-path` to the `revoke` subcommand. However, Certbot doesn't check that the key matches the certificate. It should do so.

**Comment by ynasser** [comment] 2017-06-09 19:12
This can be accomplished using `crypto_util.verify_cert_matches_priv_key`.

Since this is a fairly self-contained task, I'm marking it as volunteer-friendly. If it needs to be done sooner for some reason, lmk and I'll take it.

**Comment by Baeumla** [comment] 2017-07-01 10:26
Since the function accepts a `storage.RenewableCert` object as a parameter, I assume that I'll have to create this object within the if statement `if config.key_path is not None:` to be able to call `crypto_util.verify_cert_matches_priv_key` to check if the key matches the certificate?

Just want to make sure that this is the right way to do it. I'm new to the project so I'm sorry if this is kind of a stupid question.

**Comment by ynasser** [comment] 2017-07-05 19:37
Hi @Baeumla 

When I originally wrote my previous comment, I wasn't paying super close attention to the types the functions accepted and didn't notice what you've pointed out. It is hypothetically possible to construct a `storage.RenewablwCert` object given only the `config` parameter, but I would not suggesting going down that path. It's much more complex than it seems :/

Instead, I think a better way to accomplish this is to modify `crypto_util.verify_cert_matches_priv_key` (and everywhere that calls it) to just accept a certificate path and private key path. That way you can call `crypto_util.verify_cert_matches_priv_key` in `main.revoke` (under the `if config.key_path is not None` branch) with just `crypto_util.verify_cert_matches_priv_key(config.cert_path[0], config.key_path[1])`.

Also, your question is not at all stupid, and please feel free to ask as many questions as you need! And sorry for the delayed response, we've all been on vacation for the past few days.

Thanks for working on this! Would it be OK if I assigned the issue to you?

**Comment by Baeumla** [comment] 2017-07-06 06:31
Okay I already thought about that but I assumed that a less-invasive method would be more appreciated. But it absolutely makes sense to do it that way. 

Yes you can assign this issue to me. I'd be happy to assist in this awesome project. I'll try to create the PR for this over the weekend.

**Comment by ynasser** [comment] 2017-07-06 18:13
OK, it turns out I can't assign the issue to you because of permissions-related reasons, but the issue is yours nonetheless :)

Thanks for helping out!

**Closed** 2017-07-17 22:55 UTC
Labels: easy-fix, Good Volunteer Task
