### ISSUE TITLE
Augeas fails to parse: <ifmodule mod_rewrite.c="">

### ISSUE THREAD

**Issue by FatalMerlin** [certbot/certbot#3281] opened 2016-07-12 13:18 UTC
As it seems, certbot-auto will detect a syntax error in the latter of the two config files even if the syntax is correct, proven by `apachectl configtest`.

Output:

```
root@DOMAIN1:/root# certbot/certbot-auto renew --dry-run --apache

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/DOMAIN2.conf
-------------------------------------------------------------------------------
2016-07-12 14:46:23,074:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/DOMAIN2.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/webmail.DOMAIN2.conf', u'Syntax error'),). Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/mail.DOMAIN1.conf
-------------------------------------------------------------------------------
2016-07-12 14:46:23,448:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/mail.DOMAIN1.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/webmail.DOMAIN2.conf', u'Syntax error'),). Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/webmail.DOMAIN1.conf
-------------------------------------------------------------------------------
2016-07-12 14:46:23,918:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/webmail.DOMAIN1.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/webmail.DOMAIN2.conf', u'Syntax error'),). Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/DOMAIN1.conf
-------------------------------------------------------------------------------
2016-07-12 14:46:24,315:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/DOMAIN1.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/webmail.DOMAIN2.conf', u'Syntax error'),). Skipping.

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/mail.DOMAIN2.conf
-------------------------------------------------------------------------------
2016-07-12 14:46:24,692:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/mail.DOMAIN2.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/webmail.DOMAIN2.conf', u'Syntax error'),). Skipping.
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/DOMAIN2/fullchain.pem (failure)
  /etc/letsencrypt/live/mail.DOMAIN1/fullchain.pem (failure)
  /etc/letsencrypt/live/webmail.DOMAIN1/fullchain.pem (failure)
  /etc/letsencrypt/live/DOMAIN1/fullchain.pem (failure)
  /etc/letsencrypt/live/mail.DOMAIN2.de/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
5 renew failure(s), 0 parse failure(s)
```

As you can see, disregarding the mentioned config, it always fails on webmail.DOMAIN2.conf which uses the same cert as webmail.DOMAIN1.conf, because they are in the same chain, on the same machine and using the same webmail installation.

If necessary I can provide the full configuration files and (if required) without altering the domain names.

**Comment by bmw** [comment] 2016-07-13 17:58
This error is generated because the Apache configuration parser built in to Certbot failed to parse that file. Could you provide the contents of `/etc/apache2/sites-enabled/webmail.DOMAIN2.conf`? Please don't delete any directives, but feel free to redact information as you wish.

**Comment by MeerLin** [comment] 2016-07-13 18:22
It might be that using one cert file while having multiple domains in the chain does not work, as i got a certificate error on DOMAIN2.

If so, I'm sorry for an unnecessary issue. 

```

<VirtualHost *:80>
	#See default files for comments

	ServerAdmin admin@DOMAIN2
	ServerName webmail.DOMAIN2
	Redirect permanent / https://webmail.DOMAIN2
</VirtualHost>

<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		#See default files for comments
		
		ServerAdmin admin@DOMAIN2
		ServerName webmail.DOMAIN2
		DocumentRoot /var/www/webmail/roundcubemail-1.2.0
		
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		SSLEngine on

		SSLCertificateFile	/etc/letsencrypt/live/webmail.DOMAIN1/cert.pem
		SSLCertificateKeyFile /etc/letsencrypt/live/webmail.DOMAIN1/privkey.pem

		SSLCertificateChainFile /etc/letsencrypt/live/webmail.DOMAIN1/chain.pem

		SSLCACertificateFile /etc/letsencrypt/live/webmail.DOMAIN1/fullchain.pem

		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

		SSLProtocol All -SSLv2 -SSLv3
		SSLCompression off
		SSLHonorCipherOrder On
		SSLCipherSuite EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA
		Header add Strict-Transport-Security "max-age=15768000"
	</VirtualHost>
</IfModule>
```

**Comment by pde** [comment] 2016-07-13 21:40
This is a duplicate of #1042 , I believe?

**Comment by pde** [comment] 2016-07-13 21:41
@MeerLin you can have multiple domains per config file, but not multiple vhost blocks.  So you may need to split the SSL portion of the file out in to a separate file?

**Comment by bmw** [comment] 2016-07-14 01:15
@pde, I don't think this is a dupe. I think it's an Augeas bug. This exception is shown because Augeas errored while trying to parse the file (raised in `augeas_configurator.AugeasConfigurator.check_parsing_errors`).

My understanding of the multiple vhost problem isn't that Augeas can't parse it, it's that we haven't written the logic to use Augeas to deal with that case.

**Comment by MeerLin** [comment] 2016-07-14 01:27
@pde Absolutly no problems with the mixed vhost blocks. I'm using this in a lot of configs, also for the DOMAIN1.conf.

@bmw ok, I'm glad I didn't report an issue that was one of my own.

If you need further information about my setup, just tell me.

**Comment by pde** [comment] 2016-08-13 01:38
Oh, we should probably have bounced this to @domcleal ...

**Comment by domcleal** [comment] 2016-08-15 07:30
Thanks. I'm unable to reproduce a parse error with the file above, it might be that something Augeas failed on has been deleted (such as some comments), or something much more subtle, like line endings.  There is one fix unreleased since 0.8.1 to parse multi-line comments (#2735), so if the original file contains them then it could be that issue.

Any chance you can provide the original file, perhaps for download rather than pasted?

**Comment by MeerLin** [comment] 2016-08-15 08:37
@domcleal 

For sure, if it'll help you!

I did not censor the files this time, maybe this makes it less confusing than before with DOMAIN1 and 2 as placeholders.

[DOMAIN1](https://github.com/certbot/certbot/files/417740/webmail.fataldream.com.conf.txt)
[DOMAIN2](https://github.com/certbot/certbot/files/417741/webmail.timophillip.de.conf.txt)

Hope it helps!

**Comment by domcleal** [comment] 2016-08-15 08:42
Perfect, I can reproduce the issue now. The problem comes from this line:

    <ifmodule mod_rewrite.c="">

Augeas can't parse the `=""`. I'm a little unsure if this is the correct Apache syntax, I suspect it should just be `<ifmodule mod_rewrite.c>` - though if Apache accepts it, Augeas should of course handle it, so I'll attempt to fix it. You should be able to get certbot working by removing the `=""` from these lines.

    <ifmodule mod_rewrite.c>

**Comment by MeerLin** [comment] 2016-08-15 08:48
That is weird, because it was always parsing the first file well, and was only failing on the second.

Sadly I'm unable to test this right now, as I'm at work.

**Comment by domcleal** [comment] 2016-11-11 08:37
I've tested with Apache 2.4.6 and it doesn't load `ifmodule` sections with the extra `==""`, so I'd suggest we just close this ticket as it's unlikely that the `==""` is useful/correct in any way.

**Comment by pde** [comment] 2016-12-01 08:52
Closing at @domcleal's request.

**Comment by pde** [comment] 2016-12-01 08:53
(he also confirmed that Apache doesn't process sections with the `=""` syntax)

**Closed by pde** 2016-12-01 08:52 UTC
Labels: apache
