### ISSUE TITLE
Breaking extra "Listen 0.0.0.0:443" created in httpd.conf during renewal in certbot's apache plugin

### ISSUE THREAD

**Issue by archon810** [certbot/certbot#3967] opened 2016-12-30 17:17 UTC
I've run into this several times now on OpenSUSE 42.1, using apache 2.4. httpd.conf doesn't include `Listen` directives on its own but rather `Include /etc/apache2/listen.conf`.

What happens is that certbot, seemingly unaware of this, ends up adding this at the end of httpd.conf:
```
<IfModule mod_ssl.c>
Listen 0.0.0.0:443
Listen 0.0.0.0:443
</IfModule>
```

Note that it happens twice too (perhaps because I'm renewing a cert for 2 domains). Regardless, this breaks apache because it can't bind to port 443 more than once, so it doesn't start at all.

Sample command used:
`certbot --test-cert --break-my-certs --webroot --installer apache --webroot-path /srv/www/htdocs/site.com -d dev.site.com -d dev2.site.com --post-hook "/usr/sbin/rcapache2 reload; /usr/sbin/rcnginx reload"`

I believe this also happened in much simpler renewal commands too when I was testing, but, interestingly, not always - for example, it didn't happen during the initial certificate installation.

**Comment by archon810** [comment] 2016-12-30 17:25
I'm going to run certbot with certonly since all the changes are already in the apache and nginx configs, and they don't need to be touched, but you guys may want to have this checked out anyway.

**Comment by pde** [comment] 2017-01-04 20:55
I think this a dupe of #3364 ?

**Comment by pde** [comment] 2017-01-04 20:55
Although perhaps the `Listen` statement being added has changed?

**Comment by archon810** [comment] 2017-01-04 21:35
I ended up giving up on using "apache" entirely and will just do certonly from now on. This way, nothing gets touched.

**Comment by ms502040** [comment] 2017-06-23 11:23
Have same problem when renew certificates in OpenSUSE 13.1 and Apache 2.6.4
is some option to not modify httpd.conf when certbot renew certificates? because ssl is running and all .conf files from vhosts.d/*.conf are included.

**Comment by bmw** [comment] 2017-07-10 22:00
@joohoi, what would you like us to do with this issue?

**Comment by jpluimers** [comment] 2017-11-21 12:08
@archon810 can you verify the diff is indeed different from what I see in ..., as the diff there using 0.19 is this one:

```
[root@revue:/etc] # git diff /etc/apache2/httpd.conf | more
diff --git a/apache2/httpd.conf b/apache2/httpd.conf
index 7d2750f..a0f2184 100644
--- a/apache2/httpd.conf
+++ b/apache2/httpd.conf
@@ -230,3 +230,6 @@ IncludeOptional /etc/apache2/vhosts.d/*.conf
 #<IfModule mod_ssl.c>
 #Listen 443
 #</IfModule>
+<IfModule mod_ssl.c>
+Listen 443
+</IfModule>
```

See related https://github.com/certbot/certbot/issues/3364#issuecomment-346007462

**Comment by jpluimers** [comment] 2017-11-22 10:14
@archon810 no problem, I was contemplating to do the same, but will test the possible resolution at https://github.com/certbot/certbot/issues/3364#issuecomment-345779603 later this week.

**Comment by joohoi** [comment] 2017-12-07 18:39
This was fixed in #5202 by giving Certbot visibility over loaded modules in OpenSUSE.

**Closed by joohoi** 2017-12-07 18:39 UTC
Labels: area: apache, area: SUSE, duplicate

**Comment by jpluimers** [comment] 2017-12-07 20:59
[Verified to work](https://github.com/certbot/certbot/issues/3364#issuecomment-350092252). Thanks @joohoi

**Comment by joohoi** [comment] 2017-12-07 21:19
Awesome, thanks!

**Comment by dtonhofer** [comment] 2018-07-22 13:08
This problem is live in `certbot-0.25.1-3.fc28.noarch`

In `httpd.conf` (which on my system is very nonstandard)

```
<IfModule mod_ssl.c>
   Include "conf/vhosts.ssl.conf"
</IfModule>
```

is morphed by `certbot renew --apache` into

```
<IfModule mod_ssl.c>
   Listen 443
Include "conf/vhosts.ssl.conf"
</IfModule>
```

upon which restart of httpd breaks.

**Comment by joohoi** [comment] 2018-07-22 17:00
@dtonhofer Where in your configuration do you have the pre-existing `Listen 443` at?  I'm curious why Certbot wasn't able to find it.

**Comment by ms502040** [comment] 2018-07-22 21:55
listen.conf:
````
<IfDefine SSL>
    <IfDefine !NOSSL>
        <IfModule mod_ssl.c>
            Listen 443
        </IfModule>
    </IfDefine>
</IfDefine>
````

**Comment by dtonhofer** [comment] 2018-07-22 23:02
@joohoi  It might be difficult to find, one has to pull in a tree of files:

`/etc/httpd/conf/httpd.conf ` declares:

```
<IfModule mod_ssl.c>
   Include "conf/vhosts.ssl.conf"
</IfModule>
```
`/etc/httpd/conf/vhosts.ssl.conf ` declares:

`Listen 443`

However, `mod_ssl` is only activated if variable `SSL` has been declared.

Also included from `/etc/httpd/conf/httpd.conf `, via `Include "conf.modules.d/*.conf"` is file `/etc/httpd/conf.modules.d/00-ssl.conf` with this content:

```
<IfDefine SSL>
LoadModule ssl_module modules/mod_ssl.so
</IfDefine>
```
And finally, `SSL` is declared in `/etc/systemd/system/httpd.service.d/override.conf` as the Justified Ancients of Systemd demand:

```
[Service]
Environment=OPTIONS=-DSSL
```
