### ISSUE TITLE
certbot-auto only run renew_hook of the cli.ini, ignores per-lineage renew_hook's

### ISSUE THREAD

**Issue by pepoluan** [certbot/certbot#4323] opened 2017-03-10 18:45 UTC
## My operating system is (include version):
Ubuntu 16.04.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`wget https://dl.eff.org/certbot-auto`

## I ran this command and it produced this output:
```
# certbot-auto renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/some.obfuscated.domain.com.conf
-------------------------------------------------------------------------------
Cert not due for renewal, but simulating renewal for dry run
Running pre-hook command: iptables -t nat -I PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 44033
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for some.obfuscated.domain.com
tls-sni-01 challenge for some.obfuscated.aliasdomain.com
Waiting for verification...
Cleaning up challenges
Generating key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
Dry run: skipping renewal hook command: iptables-save

-------------------------------------------------------------------------------
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/some.obfuscated.domain.com/fullchain.pem
-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/some.obfuscated.domain.com/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
Running post-hook command: iptables -t nat -D PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 44033
```

**Note:** `iptables-save` here is just a "test hook" in `/etc/letsencrypt/cli.ini`. The conf file `/etc/letsencrypt/renewal/some.obfuscated.domain.com.conf` has a different hook.

## Certbot's behavior differed from what I expected because:
I defined a "global" `renew-hook` in `/etc/letsencrypt/cli.ini`, and a per-lineage `renew-hook` in `/etc/letsencrypt/renewal/$LINEAGE.conf`, and apparently it only runs the renew-hook in cli.ini and ignores renew-hook in the per-lineage conf.

I originally thought that both hooks will run, or at least the per-lineage one will override the 'global' one.

Is this by design? What if I need different post-processing for different lineages?

By not preferring per-lineage hook over the global hook, I am forced to create a script that consolidates handling of all lineages. This greatly increase complexity of a configuration management system.

**Comment by SwartzCr** [comment] 2017-03-17 18:03
This is a pretty good plug for finishing #4152 - since we have a lot of diversified configuration files that don't all work together in the ways you'd expect. @schoen since you're on a documentation kick, do you think you'd want to take this?

**Comment by bmw** [comment] 2019-03-14 20:19
Yes this expected behavior. If you want a global renew-hook that runs after every certificate renewal, put an executable file which runs the code you want in `/etc/letsencrypt/renewal-hooks/deploy`.

Improving our documentation around this is covered by #4152 so I'm closing this issue, but if you think I missed something, please comment or open a new issue.

**Closed by bmw** 2019-03-14 20:19 UTC
Labels: area: documentation, area: renewal, help wanted
