### ISSUE TITLE
certbot-auto doesn't know that "renew" should be non-interactive

### ISSUE THREAD

**Issue by kiranmr** [certbot/certbot#4484] opened 2017-04-10 15:26 UTC
## My operating system is (include version): 
OS: Ubuntu 14.04.2 LTS, Trusty Tahr
certbot: 0.13.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
certbot-auto downloaded from https://dl.eff.org/certbot-auto

## I ran this command and it produced this output: 
Command: `certbot-auto renew --pre-hook "docker ps -q -f name=web|xargs docker stop"` from a cronjob
Output: Script got stuck in apt-get 
```
 \_ /bin/sh /usr/local/sbin/certbot-auto renew --pre-hook docker stop Controller_contro
     \_ apt-get install --no-install-recommends python python-dev python-virtualenv gcc
```

apt-get is ran without -y  option, so its stuck waiting for user input.

## Certbot's behavior differed from what I expected because:
I expected cert-bot to install required packages non-interactively and continue. `-auto` suffix should  have ensured that apt-get is called with `-y` option

## Root cause
I analysed code of script https://github.com/certbot/certbot/blob/master/certbot-auto
`ASSUME_YES` flag is set only if script name is `letsencrypt-auto`
```shell
if [ $BASENAME = "letsencrypt-auto" ]; then
  # letsencrypt-auto does not respect --help or --yes for backwards compatibility
  ASSUME_YES=1
  HELP=0
fi
```

I think above code should be changed to include `certbot-auto` also.

**Comment by SwartzCr** [comment] 2017-04-11 19:37
I'm not entirely sure that's the problem, but I agree that this seems like a bug. Maybe it has to do with the newly added NO_BOOTSTRAP option?
Tagging @bmw and @ohemorange to see what their thoughts are

**Comment by ohemorange** [comment] 2017-04-11 21:13
Hi @kiranmr. How did you get a cert without having those packages installed? We assume that all packages are properly installed before running certbot from from the crontab. We don't want to be automatically installing packages silently on the user's behalf.

**Comment by SwartzCr** [comment] 2017-04-11 21:27
I wonder if it's due to the dependency @erikrose added for argparse? https://github.com/certbot/certbot/pull/2249/files

**Comment by ohemorange** [comment] 2017-04-11 22:49
Looks like it's getting stuck on os package install, not python dependencies.

**Comment by SwartzCr** [comment] 2017-04-12 21:16
maybe @bmw can puzzle this out?
It was mentioned (in conversation between me and @ohemorange) that this means that we can never include a new OS level dependency, since certbot-auto doesn't default to yes

**Comment by SwartzCr** [comment] 2017-04-12 21:17
also @kiranmr while your PR would /technically/ fix this issue, we don't want to be in the position where we're installing OS level dependencies for people without their agreement.
That said - it definitely shouldn't be trying to install any on renew, so this seems like an issue.

**Comment by kiranmr** [comment] 2017-04-13 14:43
@ohemorange  
1. Certbot was installed using https://dl.eff.org/certbot-auto
2. Initial certificates were generated using command 
`certbot-auto certonly --standalone --preferred-challenges http-01 
              -d {{domain_name}} --email {{domain_email}} --non-interactive --agree-tos`
3.  A weekly cronjob was scheduled to check for renewal.  This got stuck. Following command was used.
```
certbot-auto renew --pre-hook "docker ps -q -f name=web|xargs docker stop"
```
Not sure why some missing packages were trying to get installed in step 3.   Step 2 worked well. Are all dependent packages expected to get installed during step1 or step2?

@SwartzCr  Closing my PR is fine. My thinking was that certbot-auto was drop-in replacement for letsencrypt-auto. So modified  to set  ASSUME_YES for certbot-auto also. Looks like there are more things to be considered.

Let me know if any more details are needed.

**Comment by pde** [comment] 2017-04-13 22:12
`certbot-auto` runs `apt-get` without the `-y` flag intentionally, so that users are not surprised by changes to their system.  `certbot-auto` looks for the `-n` or `--non-interactive` flags and adds `-y` to the apt call in those cases.  However it doesn't currently look for the `renew` subcommand which also implies `-n`.  It should do that.

Also, we should possibly avoid re-running `apt-get` if we've already done that and the packages are present (which would have mitigated the problem that motivated #3955 too).

**Comment by bmw** [comment] 2017-04-14 17:51
@kiranmr, I suspect the cause of the problem is differences in the value of the `HOME` environment variable when you ran `certbot-auto` yourself vs. when it ran from cron. You can verify this by seeing if you have two installations of Certbot on your system. Assuming you didn't customize where Certbot is installed using environment variables, one should be in `${XDG_DATA_HOME:-~/.local/share}/letsencrypt` if you're logged in as the non-root user that you originally ran `certbot-auto` with and the other is probably in `/root/.local/share/letsencrypt`. If this isn't the case, `certbot-auto` may have tried to update from `cron` and failed to do so, but this is much less likely.

We'll definitely fix this, however, I'd also like to encourage you to stop using `certbot-auto` and switch to our PPA. Prebuilt packages offer a much better user experience and even come with a cron job so you don't have to set one up yourself. You can find instructions for how to do this [here](https://certbot.eff.org/#ubuntutrusty-other). 

To fix this for `certbot-auto` users though, the easiest fix is the one implemented in #4500. A fix with a slightly larger scope is to put the Certbot installation somewhere like `/opt` so it can be shared. The downsides of doing this is we'd need to add a lock to `certbot-auto` and any installed 3rd party plugins would be shared by all users rather than just an individual one. This latter would avoid problems where a 3rd party plugin is available when running as a non-root user, but isn't available when running as root from cron though. The fix with the largest scope is to kill `certbot-auto` entirely which we will certainly do in the future, but I'm not sure it's feasible right now due to it's popularity, constraints on time, and political issues.

cc @erikrose, @ohemorange as I'm curious your thoughts.

**Comment by ohemorange** [comment] 2017-04-14 18:35
Preference:
1. Kill certbot-auto (so we can stop having new, exciting issues to keep fixing one by one, but obviously a harder problem)
2. Renew implies non_interactive (we already make this assumption in the codebase, as mentioned in comments. Ideally we should also set non_interactive to true during parsing when it's renew as well, instead of checking both manually.)
3. Shared installation (allowing certbot to possibly be run as non-sudo is nice to even vaguely kind of support-ish, and moving farther from that seems sad)

**Comment by bmw** [comment] 2017-04-14 18:58
Happy to work towards 1 ASAP, but I don't think it should be the solution to this problem.

I'll also point out that for 3, `certbot-auto` forces you to run Certbot as root unless you set `LE_AUTO_SUDO` to an empty string which is only documented inside the script itself. I suppose some people could be using it though. Another con against 3 though is some people may be reaching into the venv directly to run Certbot and moving its location may break things. We used to tell people to do this a long time ago to prevent updates before we had `--no-self-upgrade`.

With that in mind, I'm leaning towards 2 because it's the simplest solution to a problem with a distribution method we want to deprecate.

**Comment by ohemorange** [comment] 2017-04-14 19:34
> With that in mind, I'm leaning towards 2 because it's the simplest solution to a problem with a distribution method we want to deprecate. Let's not spend unnecessary engineering effort here if we have a simple solution that works.

:+1:  :+1:  :+1: :+1:

**Closed** 2017-04-17 18:41 UTC
Labels: area: certbot-auto, bug, has pr
