### ISSUE TITLE
letsencrypt-auto issue traceback on centos 7 server when running "renew" job

### ISSUE THREAD

**Issue by lpallard1** [certbot/certbot#4074] opened 2017-01-18 01:24 UTC
On a centos 7 server, letsencrypt-auto issues the following traceback when running via cron to perform a check if cert is due to renew:

Traceback (most recent call last):
  File "/tmp/tmp.QI3WlVxieD/fetch.py", line 126, in <module>
    exit(main())
  File "/tmp/tmp.QI3WlVxieD/fetch.py", line 114, in main
    print latest_stable_version(get)
  File "/tmp/tmp.QI3WlVxieD/fetch.py", line 71, in latest_stable_version
    'https://pypi.python.org/pypi/certbot/json')))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Cert seems to be successfully renewed when due for renewal, but each time the cron job runs, I get an email from CRON with the output above...

**Comment by bmw** [comment] 2017-01-18 18:35
On CentOS 7 we have up to date [OS packages](https://certbot.eff.org/#centosrhel7-other) available in EPEL which are likely to provide a better experience than `letsencrypt-auto`.

With that said, `letsencrypt-auto` should still work. What's happening here is `letsencrypt-auto` is trying to check if it is up to date and failing to do so. What is a few lines of the output of `curl https://pypi.python.org/pypi/certbot/json` on your server?

**Comment by lpallard1** [comment] 2017-01-22 18:21
OK I have installed the OS packages from EPEL following the instructions of "https://certbot.eff.org/#centosrhel7-other"

I believe what happened with LE was probably a firewall misconfig.  When you mentioned "letsencrypt-auto is trying to check if it is up to date and failing to do so" it sounded to me like a blocked communication issue.

I will see once certbot tries to check for a newer cert if it fails and post back here.  I also found a misconfig in my apache config and firewall DNS forwarding so....  Lets hope now it works but nevertheless it was a good cleanup !

Thanks BMW!

**Comment by bmw** [comment] 2017-01-23 20:15
> I believe what happened with LE was probably a firewall misconfig. When you mentioned "letsencrypt-auto is trying to check if it is up to date and failing to do so" it sounded to me like a blocked communication issue.

That's quite likely. Trying to reproduce the problem locally, I get errors like:
```
Couldn't download https://pypi.python.org/pypi/certbot/json. <urlopen error [Errno -3] Temporary failure in name resolution>
```
```
Couldn't download https://pypi.python.org/pypi/certbot/json. <urlopen error [Errno 101] Network is unreachable>
```
```
Traceback (most recent call last):
  File "fetch.py", line 126, in <module>
    exit(main())
  File "fetch.py", line 114, in main
    print latest_stable_version(get)
  File "fetch.py", line 71, in latest_stable_version
    'https://pypi.python.org/pypi/certbot/json')))
  File "fetch.py", line 56, in get
    return self._opener.open(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 838, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 272, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'pypi.python.org' doesn't match either of ...
```
```
Couldn't download https://pypi.python.org/pypi/certbot/json. HTTP Error 503: Service Unavailable
```
depending on how I set things up.

If you can provide instructions on how to reproduce this problem, I can look into improving the error message. At the same time, it might not be worth the engineering effort as there are hundreds of thousands `letsencrypt-auto` users out there, this is the first report of the problem, and you suggested it was due to a misconfigured service.

> I will see once certbot tries to check for a newer cert if it fails and post back here.

The code that was causing the error is `certbot-auto` specific so if you have a problem, this is likely a different issue and you should probably open a new ticket.

With all this in mind, I'm closing the issue for now. If you're interested in looking into it, feel free to comment about how to reproduce the problem and I'll consider reopening. I'm glad you got it working!

**Closed by bmw** 2017-01-23 20:15 UTC
Labels: certbot-auto, more-info
