### ISSUE TITLE
CertBot creates world-readable private key

### ISSUE THREAD

**Issue by starrychloe** [certbot/certbot#3982] opened 2017-01-07 00:25 UTC
```
# ls -l /etc/letsencrypt/live/host.net/privkey.pem
lrwxrwxrwx. 1 root root 39 Jan  6 23:12 /etc/letsencrypt/live/host.net/privkey.pem -> ../../archive/host.net/privkey1.pem
# ls -l /etc/letsencrypt/archive/host.net/
total 16
-rw-r--r--. 1 root root 1805 Jan  6 23:12 cert1.pem
-rw-r--r--. 1 root root 1647 Jan  6 23:12 chain1.pem
-rw-r--r--. 1 root root 3452 Jan  6 23:12 fullchain1.pem
-rw-r--r--. 1 root root 1704 Jan  6 23:12 privkey1.pem
```

It shouldn't do that. It should be readable only to root.

**Comment by nickfong** [comment] 2017-01-07 02:16
This issue is a duplicate of #1473.  

The permissions of the parent directory should prevent reading of the private key until a patch for #1473 is applied.

**Comment by pde** [comment] 2017-01-07 23:57
Yes, this is a duplicate. A PR for #1473 would be welcome, but it's quite an intricate task.

**Closed by pde** 2017-01-07 23:57 UTC
Labels: duplicate
