### ISSUE TITLE
Apache plugin error -- syntax error in configuration file

### ISSUE THREAD

**Issue by louischau** [certbot/certbot#3716] opened 2016-10-31 12:04 UTC
Hi,
I am getting an error about the parsing the apache configuration file on Ubuntu 16.04

Error message:
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/apache2.conf', u'Syntax error'),)

And it was caused by the following rewrite rule
RewriteCond %{THE_REQUEST} /([^?\ ]+)

When I removed the rule, I'd successfully run the command:
letsencrypt --apache

**Comment by pde** [comment] 2016-11-02 19:13
@domcleal thoughts on this?

**Comment by domcleal** [comment] 2016-11-03 07:58
I can't reproduce an issue with only that line in a config file - would you mind providing a gist of the context? Particularly important may be any comments on the line, blank lines around the line in question etc. Is `%{THE_REQUEST}` literal or is it obfuscated?

**Comment by pde** [comment] 2016-11-11 07:06
@louischau can you post your full config?

**Comment by louischau** [comment] 2016-11-11 13:44
The configuration under 'Directory /var/www/' is as follow:


        Options FollowSymLinks
        AllowOverride None
        Require all granted

        RewriteEngine On
        RewriteCond %{THE_REQUEST} /([^?\ ]+)
        RewriteRule ^html/show/(.*)$ html/show.php/%1 [L]
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(([A-Za-z0-9\-]+/)*[A-Za-z0-9\-]+)?$ $1.php [L]


Other configuration is left as default

**Comment by domcleal** [comment] 2016-11-11 14:00
The new snippet also parses without errors for me (https://gist.github.com/domcleal/24968a56c6a0e885336aeaf6f4eca5cd), so I'm unsure why you'd be getting an error.

Ensure you're on the latest version of certbot, but otherwise I think I'd need the original configuration file to reproduce the issue to help any further. Sorry!

The command in the gist may help you create a reproducer.

**Comment by louischau** [comment] 2016-11-11 15:01
Please find the full configuration file in the gist

[https://gist.github.com/louischau/2cf76fae036bd2134a49274f58ed9f6e](https://gist.github.com/louischau/2cf76fae036bd2134a49274f58ed9f6e)

**Comment by domcleal** [comment] 2016-11-11 15:04
Thanks, though it's still parsing without any issues on certbot master: https://gist.github.com/domcleal/9dcc5eacecd91ab5ac700e1ac1e97433

Does the command the previous gist help? Does it raise an error on your local copy of the file?

**Comment by pde** [comment] 2017-01-18 20:08
Closing this as unreproducible; please reopen if anyone can get a clean repro with git master.

**Closed by pde** 2017-01-18 20:08 UTC
Labels: apache, cannot reproduce, more-info
