### ISSUE TITLE
Error: duplicate listen options for [::]:443

### ISSUE THREAD

**Issue by hackuun** [certbot/certbot#5550] opened 2018-02-07 17:33 UTC
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`sudo apt-get install python-certbot-nginx`

## I ran this command and it produced this output:
`nginx: [emerg] duplicate listen options for [::]:443 in /etc/nginx/sites-enabled/example.online:29
`

## Certbot's behavior differed from what I expected because:
It should be no errors

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
server {
  listen 80;
  listen [::]:80;

  server_name example.online;

  root /home/example/deploy;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name www.example.online;
  return 301 $scheme://example.online$request_uri;
}

```

**Comment by neoadventist** [comment] 2018-02-09 08:39
@iamdubx did you figure this out? I'm having the same issue.

**Comment by quen2404** [comment] 2018-02-09 12:04
Same issue... It works for my default site, but not for custom sub domain

**Comment by varunyellina** [comment] 2018-02-09 13:55
I'm having the same issue.

I do have a config to catch multiple domains though.

```
server {
  listen 80;
  listen [::]:80;

  root /home/primarydomain/public;
  index index.html index.htm;

  server_name domain1.com *.domain1.com domain2.com *.domain2.com domain3.com *.domain3.com domain4.com *.domain4.com;

  return 302 $scheme://primarydomain.com$request_uri;

  access_log /var/log/nginx/others.access.log;
  error_log /var/log/nginx/others.error.log;

  location / {
    try_files $uri $uri/ /index.html =404;
  }
}
```

I get `nginx: [emerg] duplicate listen options for [::]:443 in /etc/nginx/sites-enabled/others:19` for this config.

Any help?

**Comment by amattn** [comment] 2018-02-09 20:09
Same problem.  

I ran the command: `certbot --redirect --nginx -d readacted.com -d www.redacted.com`

my original conf file looks like: 

```
    server {
        server_name redacted.com;
        location / {
        root   /home/redacted/www;
        index  index.html;
      }
    }

    server {
        listen 80;
        listen [::]:80;
        server_name www.redacted.com;
        return 301 $scheme://redacted.com$request_uri;
    }
```

according to /var/log/letsencrypt/letsencrypt.log I see certbot is trying to do this:

```
    server {
        server_name redacted.com;
        location / {
        root   /home/redacted/www;
        index  index.html;
      }

        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/redacted.com-0001/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/redacted.com-0001/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    }

    server {
        listen 80;
        listen [::]:80;
        server_name www.redacted.com;
        return 301 $scheme://redacted.com$request_uri;

        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/www.redacted.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/www.redacted.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    }
```

nginx complains that on the line `listen [::]:443 ssl ipv6only=on; # managed by Certbot`

the actual error message:

`nginx: [emerg] duplicate listen options for [::]:443 in /etc/nginx/sites-enabled/redacted.com:23`

a quick google brought up this page from 2010:

http://www.serverphorums.com/read.php?5,203912

which suggests that nginx gets confused due to some internal implementation detail.

I'm not an nginx expert, but I've tested that the following seems to work:

```
    server {
        server_name redacted.com;
        location / {
        root   /home/redacted/www;
        index  index.html;
      }

        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/redacted.com-0001/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/redacted.com-0001/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    }

    server {
        listen 80;
        listen [::]:80;
        server_name www.redacted.com;
        return 301 http://redacted.com$request_uri;

        listen [::]:443; # manually changed
        ssl on;  #manually changed
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/www.redacted.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/www.redacted.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    }
```

**Comment by schoen** [comment] 2018-02-13 00:54
@ohemorange, do you know if we have an existing issue tracking this? It feels familiar to me but I don't remember whether or not it's something that we've looked into before.

**Comment by ohemorange** [comment] 2018-02-13 01:23
I have never seen this before. Looks like they fixed the original bug, except when you're using IPv6. And since we just launched IPv6 support, that's why people are hitting this. The solution above will work; I'll see if there's a reason this hasn't been fixed in Nginx for IPv6 yet.

**Comment by ohemorange** [comment] 2018-02-13 22:37
Actually, you don't even have to do the `ssl on` change -- removing `ipv6only=on` from either or both fixes the problem.

@joohoi, we probably want to fix this by either removing `ipv6only=on` completely or only putting it in once per unique address line that we add. Do you have a sense of what would be best here?

**Comment by rushilsrivastava** [comment] 2018-02-14 04:29
Having the same issue here. Everything was fine for my first domain. The second domain started having these issues.

**Comment by joohoi** [comment] 2018-02-14 08:07
It looks like Certbot is unable to detect ipv6only directive completely for some reason. Removing that would fix the issue for *most* of the users. This can cause some issues with really old Nginx versions, as the behavior of ipv6only and the defaults have changed over the time.

**Comment by attie-argentum** [comment] 2018-02-14 18:41
Apologies for the nasty patch, but this fixed it for me, hopefully there will be a proper fix soon!

```patch
--- /usr/lib/python3/dist-packages/certbot_nginx/configurator.py.orig	2018-02-14 18:38:30.380863045 +0000
+++ /usr/lib/python3/dist-packages/certbot_nginx/configurator.py	2018-02-14 18:38:01.501018553 +0000
@@ -507,10 +507,10 @@ class NginxConfigurator(common.Installer
                           '[::]:{0}'.format(self.config.tls_sni_01_port),
                           ' ',
                           'ssl']
-            if not ipv6info[1]:
-                # ipv6only=on is absent in global config
-                ipv6_block.append(' ')
-                ipv6_block.append('ipv6only=on')
+            #if not ipv6info[1]:
+            #    # ipv6only=on is absent in global config
+            #    ipv6_block.append(' ')
+            #    ipv6_block.append('ipv6only=on')
 
         if vhost.ipv4_enabled():
             ipv4_block = ['\n    ',
```

**Comment by lt100** [comment] 2018-02-23 00:48
Same issue. Will this be addressed?

**Comment by joohoi** [comment] 2018-02-23 10:28
Sorry for the wall of text, but here we go. 

To shed some light on the issue:
ipv6only option is used to be able to handle multiple listen statements per socket. Unfortunately it can only be used once in the server configuration for the socket. So Nginx will fail to start in case of:
```
server {
    ...
    server_name first.example.org;
    listen [::]:80 ipv6only=on;
    listen 80;
} 
server {
    ...
    server_name second.example.org;
    listen [::]:80 ipv6only=on;
    listen 80;
}
```
With the recent versions of Nginx this problem does not exist if the `ipv6only` setting is omitted completely, as the default value of the variable is `ipv6only=on`. So the following is valid and working configuration in Nginx versions >= 1.3.4:
```
server {
    ...
    server_name first.example.org;
    listen [::]:80;
    listen 80;
} 
server {
    ...
    server_name second.example.org;
    listen [::]:80;
    listen 80;
}
```
However the default value of `ipv6only` variable in Nginx versions prior to 1.3.4 was `ipv6only=off`, so older versions will fail with the following configuration:
```
server {
    ...
    server_name first.example.org;
    listen [::]:80;
    listen 80;
} 
```

Currently the situation with distribution packaging is that the only distribution that ships with older version of Nginx would be Debian Wheezy (Debian 7), which ships version 1.2.1 of Nginx from the default repositories.

If we would remove the `ipv6only` detection and setting completely from Certbot, this would break for all users on Debian Wheezy. Fortunately EOL date for Wheezy is set for [May 2018](https://wiki.debian.org/DebianReleases#Production_Releases), so we're close to being able to remove this additional complexity from Certbot code altogether.

The current functionality of Certbot is parsing the complete Nginx configuration, detecting `ipv6only=on` setting already present in one of the `server{}` blocks and omitting addition of it if so. If however the value was not found, Certbot would then add it. This issue boils down to Certbot not being able to detect this already existing variable from some block of the users current configuration, and hence tries to add it to the `server{}` block that's being configured.

To make decision of the route to fix this issue, we'd need a complete example configuration where Certbot fails in the way described above to be able to improve the detection of an already existing `ipv6only=on`variable if we decide to fix it that way instead of removing this functionality altogether.

**Comment by plethoradesign** [comment] 2018-02-23 16:21
Thanks for the patch; that worked for me. FWIW, I'm on Ubuntu 17.

**Comment by chilion** [comment] 2018-02-27 11:38
I had to remove all the 

    listen [::]:80;
    listen 80;

To make it work

**Comment by davidkartuzinski** [comment] 2018-02-28 15:27
https://github.com/chilion - thanks!  removing: 

listen [::]:80;
listen 80;

worked for me as well.

I have two domains on one Ubuntu server.  The first one worked no problem.  Then I got the error as above. Your solution worked for me.  I just installed nginx on a fresh server with fresh everything.

Thank you.

**Comment by jevets** [comment] 2018-02-28 22:43
removing `listen [::]:80` but leaving `listen 80;` worked for me for installation on non-default domain

**Closed** 2018-03-01 23:08 UTC
Labels: area: nginx, bug

**Comment by OscarZhou** [comment] 2018-08-21 22:15
I comment listen [::]:443 in the subdomain setting, then it works. Is it okay

**Comment by JFossey** [comment] 2019-04-11 04:58
I just bumped into this issue. Any body trying to make sense of the the different `listen` directives and `ipv6only`. 
 
I highly recommend this blog post, until I found this article I was not sure what do with all the different advice I was finding on the web.

https://stefanchrist.eu/blog/2015_01_21/Using%20ipv6only%20in%20Nginx.xhtml

**Comment by BonBonSlick** [comment] 2019-07-28 00:57
Still exists, after purge  python, reinstall this error thrown.

**Comment by sakaruk** [comment] 2019-09-02 20:14
In case of multiple domains

Instead of 
listen [::]:443 ssl http2 ipv6only=on;

Use 
listen example.com:443 ssl http2 ipv6only=on;

**Comment by souvik-networth-corp** [comment] 2019-11-02 10:51
Omit the `listen` directive in all your server blocks.

**Comment by AlexTies** [comment] 2019-11-18 11:59
This error shows up when there are two server blocks listening on the same domain with the same port.
Check all your configuration files in the sites-available folder for the duplicate listener. In my case certbot created a listener for 443 in the default file.

**Comment by bmw** [comment] 2019-11-20 00:03
If you can provide configuration files to reproduce this with an up-to-date version of Certbot, I'd be interested to see them.

**Comment by KrisRoofe** [comment] 2020-04-22 08:17
[nginx: [emerg] a duplicate default server for](https://stackoverflow.com/a/61360297/6521116)

**Comment by ohemorange** [comment] 2020-06-22 23:36
We don't set it in Certbot. When we create a server block, we copy some directives from the existing default server block, or other template server block, including the listen directive along with its options. This lets Certbot work even if Nginx is behind a proxy or other type of port forwarding. We explicitly *delete* `ipv6only=on` from the duplicated server block because the documentation indicates it can only be used once.

Ideally, we would do the same for all options that we know can't be duplicated in this way, but leave other options that the user might specifically want all their server blocks to have. To do that, we have to know which options are repeatable, which the documentation does not seem to indicate, and which we only seem to discover through people coming to us on issues like this one.

**Comment by OverStruck** [comment] 2020-10-06 04:36
Thanks @joohoi
Your explanation & solution worked for me on Ubuntu 20 with nginx version: 1.18.0

**Comment by maitrungduc1410** [comment] 2020-11-21 07:38
I have 2 VPS: 1 is Ubuntu runs Nginx 1.10 works fine, the other is Centos runs Nginx 1.16 and has this error. Weird

**Comment by heylix** [comment] 2021-03-16 10:57
I also ran into that issue and think that autogenerated stuff like this should be prevented by adding an `nginx -t` check before writing the configuration. Automated backups somewhere would also be a nice touch…

**Comment by hak33m16** [comment] 2021-08-07 21:00
Looks like this is still an issue. This comment was the solution for me: https://github.com/certbot/certbot/issues/5550#issuecomment-365429316

What's interesting is that I didn't hit this until I added the 4th site to my `/etc/nginx/sites-available` folder. I have two domains running out of the same box, and each of those have their own `dev.<site>.com` sites-available config as well

I have zero issues with the first domain that I added the `dev.` subdomain for, but the second is what kicked this off

Versions:
```
$> lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$> nginx -V
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020

$> certbot --version
certbot 0.40.0
```

**Comment by hardikhari96** [comment] 2021-09-19 19:34
> I solved issue , 
It's occur when you trying to install certificate with certbot. 

So what happens, certbot automatically add its own `listen 443`; so if your script had already that ,it will throw error that `duplicate listen 443`

**Comment by schevenin** [comment] 2022-07-06 19:55
> Sorry for the wall of text, but here we go.
> 
> To shed some light on the issue: ipv6only option is used to be able to handle multiple listen statements per socket. Unfortunately it can only be used once in the server configuration for the socket. So Nginx will fail to start in case of:
> 
> ```
> server {
>     ...
>     server_name first.example.org;
>     listen [::]:80 ipv6only=on;
>     listen 80;
> } 
> server {
>     ...
>     server_name second.example.org;
>     listen [::]:80 ipv6only=on;
>     listen 80;
> }
> ```
> 
> With the recent versions of Nginx this problem does not exist if the `ipv6only` setting is omitted completely, as the default value of the variable is `ipv6only=on`. So the following is valid and working configuration in Nginx versions >= 1.3.4:
> 
> ```
> server {
>     ...
>     server_name first.example.org;
>     listen [::]:80;
>     listen 80;
> } 
> server {
>     ...
>     server_name second.example.org;
>     listen [::]:80;
>     listen 80;
> }
> ```
> 
> However the default value of `ipv6only` variable in Nginx versions prior to 1.3.4 was `ipv6only=off`, so older versions will fail with the following configuration:
> 
> ```
> server {
>     ...
>     server_name first.example.org;
>     listen [::]:80;
>     listen 80;
> } 
> ```
> 
> Currently the situation with distribution packaging is that the only distribution that ships with older version of Nginx would be Debian Wheezy (Debian 7), which ships version 1.2.1 of Nginx from the default repositories.
> 
> If we would remove the `ipv6only` detection and setting completely from Certbot, this would break for all users on Debian Wheezy. Fortunately EOL date for Wheezy is set for [May 2018](https://wiki.debian.org/DebianReleases#Production_Releases), so we're close to being able to remove this additional complexity from Certbot code altogether.
> 
> The current functionality of Certbot is parsing the complete Nginx configuration, detecting `ipv6only=on` setting already present in one of the `server{}` blocks and omitting addition of it if so. If however the value was not found, Certbot would then add it. This issue boils down to Certbot not being able to detect this already existing variable from some block of the users current configuration, and hence tries to add it to the `server{}` block that's being configured.
> 
> To make decision of the route to fix this issue, we'd need a complete example configuration where Certbot fails in the way described above to be able to improve the detection of an already existing `ipv6only=on`variable if we decide to fix it that way instead of removing this functionality altogether.

Removing ipv6only=on; fixed the issue!

**Comment by GitBobCat** [comment] 2024-08-21 19:20
Sorry: Me too. I'm sure I am driving things wrong but my Pi got broke.

I had one domain that was working...

server {
     server_name example.co.uk www.example.co.uk;

     root /var/www/example.co.uk/public_html;

     index index.html index.htm;

     location / {
          try_files $uri $uri/ =404;
     }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.co.uk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.co.uk/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.example.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = example.co.uk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


     listen 80;
     listen [::]:80;
     server_name example.co.uk www.example.co.uk;
     return 404; # managed by Certbot
}

I tried to get another two up and running with different conf files and stuff as explained in,

https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-configure-multiple-domains-with-nginx-on-ubuntu/

Then used,

https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

to install certificates for them which worked but I landed on the Nginx is installed rather than the index pages.

No doubt I borked something along the way but being a grunt I copied the, still working, example.co.uk.conf file over to the other .conf files and changed all mentions of the domain names to match and ended up with the [::}433 error using,

systemctl status nginx.service

So I arrived here and, being a grunt, thought that if I commented out the [::}433 line, I do not have an entry for IPV6 in my DNS, things might work. Did not happen.

Now systemctl status nginx.service says,

[warn] 923#923: conflicting server name "example2.co.uk" on [::]:80, ignored
[warn] 923#923: conflicting server name "www.example2.co.uk" on [::]:80, ignored
[warn] 923#923: conflicting server name "example3.co.uk" on [::]:80, ignored
[warn] 923#923: conflicting server name "www.example3.co.uk" on [::]:80, ignored
[warn] 923#923: conflicting server name "example2.co.uk" on 0.0.0.0:443, ignored
[warn] 923#923: conflicting server name "www.example2.co.uk" on 0.0.0.0:443, ignored
[warn] 923#923: conflicting server name "example3.co.uk" on 0.0.0.0:443, ignored
[warn] 923#923: conflicting server name "www.example3.co.uk" on 0.0.0.0:443, ignored
[notice] 923#923: signal process started
Aug 21 19:47:21 MrBlobby systemd[1]: Reloaded nginx.service - A high performance web server and a reverse proxy server.

I'm not sure if that adds anything or is of any help because I have no idea how I broke stuff and would be unlikely to be able to recreate the route to it being broken so I guess my best bet would be to nuke the everything from orbit, hope I don't miss any aliens, and start from new.

**Comment by Znuff** [comment] 2024-08-30 16:39
Please stop using this github issue as your personal blog.

This issue is closed, fixed -- and every time you post here you notify 30+ people via e-mail (_for which I am also now guilty, and I apologize to everyone_).

Might I suggest you start a blog to write your stories.

**Comment by GitBobCat** [comment] 2024-08-30 20:35
"This issue is closed, fixed -- and every time you post here you notify 30+ people via e-mail (for which I am also now guilty, and I apologize to everyone)."

Sorry about that. The issue matched my recent problem and this page turned up on a search so I had a burble. OK my nuke fix for an issue that is supposedly fixed and closed that matched my problem might not be the best but someone else might have a Pi 4 and take a punt on it.

I just had a quick check and having broken my mail server I did not put my GitHub alias back in so that might explain why I did not receive notifications. I may even have blocked GitHub using IPTables as a result.

I am so useless. Apparently there are others like me who suffer the slings and arrows of those who know how this stuff works. Sorry for asking.

As an aside perhaps GitHub has an unsubscribe from thread feature for when you are no longer interested. That would be Kool.

Just to be even more snidey perhaps a closed thread should no longer accept posts but I'll take a guess that it is still open for posts because, although I may not have been much help, stuff might still happen.
