### ISSUE TITLE
certbot selected the wrong domain as the subject

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#5011] opened 2017-08-09 20:53 UTC
## My operating system is (include version):
debian 9.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot 0.17.0 (certbot-auto)

## I ran this command and it produced this output:
```sh
# ~/bin/certbot-auto
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: unrelated.example.org
2: www.unrelated.example.org
3: a.example.com
4: b.example.com
5: c.example.com
6: build.example.com
7: e.example.com
8: e.example.com
9: f.example.com
10: g.example.com
11: h.example.com
12: i.example.com
13: j.example.com
14: zhost.example.com
15: l.example.com
16: m.example.com
17: n.example.com
18: o.example.com
19: atest.site.example.com
20: p.atest.site.example.com
21: q.atest.site.example.com
22: r.atest.site.example.com
23: s.atest.site.example.com
24: zhost.site.example.com
25: t.site.example.com
26: u.example.com
27: v.example.com
28: z.example
29: a.unrelated2.example.org
30: www.a.unrelated2.example.org
31: b.unrelated2.example.org
32: c.unrelated2.example.org
33: www.c.unrelated2.example.org
34: unrelated3.example.org
35: unrelated4.example.org
36: www.unrelated3.example.org
37: www.unrelated4.example.org
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 14 24 19
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for zhost.site.example.com
tls-sni-01 challenge for atest.site.example.com
tls-sni-01 challenge for zhost.example.com
Waiting for verification...
Cleaning up challenges
Deploying Certificate for zhost.site.example.com to Virtualzhost /etc/apache2/sites-available/proxy-zhost-ssl.conf
Deploying Certificate for atest.site.example.com to Virtualzhost /etc/apache2/sites-available/proxy-zhost-ssl.conf
Deploying Certificate for zhost.example.com to Virtualzhost /etc/apache2/sites-available/proxy-zhost-ssl.conf
```
## Certbot's behavior differed from what I expected because:

I expected the subject to be the one from the first domain listed (14, zhost.example.com)
Instead, it, for reasons I can't explain, picked the second domain (24, zhost.site.example.com)

Note: the real domains, if sorted alphabetically, would be ordered:
* atest.site.example.com (this is alphabetically first)
* zhost.example.com
* zhost.site.example.com (this is alphabetically last)

## Here is the relevant nginx server block or Apache virtualzhost for the domain I am configuring:
```
<Virtualzhost *:443>
	ServerAdmin webmaster@localzhost
	DocumentRoot /var/www
        ServerName zhost.example.com
        ServerAlias zhost
        ServerAlias zhost.site.example.com
        ServerAlias atest
        ServerAlias atest.site.example.com
...
</Virtualzhost>
```

**Comment by SwartzCr** [comment] 2017-08-14 20:22
Let me just make sure I fully understand what you mean:
The certificate was issued with a subject name you didn't expect? Can you share that part of the certificate with me?
Also what is the name of the lineage for this certificate? i.e. what folder in `/etc/letsencrypt/live` is it in?

**Comment by SwartzCr** [comment] 2017-08-14 20:23
Let me just make sure I fully understand what you mean:
The certificate was issued with a subject name you didn't expect? Can you share that part of the certificate with me?
Also what is the name of the lineage for this certificate? i.e. what folder in `/etc/letsencrypt/live` is it in?

**Comment by jsoref** [comment] 2017-08-15 17:50
The folder picked matches the subject:
`/etc/letsencrypt/live/zhost.site.example.com`
```
        Subject: CN = zhost.site.example.com
            X509v3 Subject Alternative Name:
                DNS:atest.site.example.com, DNS:zhost.example.com, DNS:zhost.site.example.com
```
Based on the names above, I would have wanted it to use:
`/etc/letsencrypt/live/zhost.example.com` (this directory exists, so possibly adding a -1/.1, or asking me if I wanted to replace it or something)
```
        Subject: CN = zhost.example.com
            X509v3 Subject Alternative Name:
                DNS: zhost.example.com, DNS:zhost.site.example.com, DNS:atest.site.example.com
```

Note: I expected the first item in the
```
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):
```
response (`14`) to be used as the subject (and folder name), and for the `X509v3 Subject Alternative Name` to be filled out in the order I specified subjects (`14 24 19`)

Instead, it picked the second item (`24`) as the subject, and effectively ordered it (`19 14 24`) -- which really doesn't make any sense to me.

**Comment by SwartzCr** [comment] 2017-08-15 23:01
Of note with this is that there was already a lineage for the name jsoref expected this to have as the subject name. But even in that case it should have just appended -001 to the lineage.
@bmw do you think you could look into this?
@jsoref do you think you could reproduce this with a higher logging level and share the logs with us?

**Comment by jsoref** [comment] 2017-08-15 23:11
Probably. Provide instructions and I'll see about allocating some time.
(In general, I'm unlikely to post unsanitized logs the github, but happy to share on irc...)

**Comment by bmw** [comment] 2017-08-21 18:01
I think this is a duplicate of #3189.

**Comment by bmw** [comment] 2019-03-08 01:16
Certbot no longer puts any domains in the subject of the CSR as doing so is deprecated so I'm closing this issue.

**Closed by bmw** 2019-03-08 01:16 UTC
Labels: area: cert management, area: ui / ux
