### ISSUE TITLE
Failed to generate certificate on Ubuntu 16.04 with gcc 5.3.1 20160413

### ISSUE THREAD

**Issue by vinaykrsharma** [certbot/certbot#3129] opened 2016-06-06 11:04 UTC
Running command:

    ./letsencrypt-auto certonly -a webroot --webroot-path=/usr/share/nginx/html \
    -d xxx.example.com

Actually this error is from pip while installing cryptography. There is something wrong with **"cryptography"**, which is not compatible with `gcc 5.3.1 20160413`

Installing `cryptography` directly, also throwing same errors on console:

    pip install cryptography

But not this one:

    pip install cryptography==1.2.3

Partial output:

    ...
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/_build'
      warning: no previously-included files matching '*' found under directory 'vectors'
      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
      creating build/temp.linux-x86_64-2.7
      generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
      generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
      building '_openssl' extension
      creating build/temp.linux-x86_64-2.7/build
      creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
      x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
      x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
      Please submit a full bug report,
      with preprocessed source if appropriate.
      See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

      ----------------------------------------
      Failed building wheel for cryptography
      Running setup.py clean for cryptography
    ...

**Comment by bmw** [comment] 2016-06-06 18:31
This may due to memory issues (see #1081).

**Comment by vinaykrsharma** [comment] 2016-06-07 07:01
Could be, but #1081 helped me after reading it could be a memory issue!

I stopped some other services to release memory like PostgreSQL, Django/Gunicorn, then tried and it's done! After that it was only 115MB memory uses of 489MB!

I'm using DO droplet with 512MB.

**Comment by bmw** [comment] 2016-06-07 21:14
I'm glad you got it to work. I'll close this as a duplicate of #1081.

The memory problems come from having to compile one of our dependencies to link against `openssl`. While OS packaging helps this, we're still trying to find a better way to mitigate this problem.

**Closed by bmw** 2016-06-07 21:14 UTC
Labels: certbot-auto
