### ISSUE TITLE
certbot-auto fails under python3 on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by HippoMan** [certbot/certbot#8397] opened 2020-10-22 18:15 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

```
# uname -a
Linux HOSTNAME-DELETED 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

```
# cd /opt/eff.org/certbot

# /usr/bin/python3 --version
3.8.5

# virtualenv -p /usr/bin/python3 venv
created virtual environment CPython3.8.5.final.0-64 in 224ms
  creator CPython3Posix(dest=/opt/eff.org/certbot/venv, clear=False, global=False)
  seeder FromAppData(download=False, retrying=latest, urllib3=latest, CacheControl=latest, msgpack=latest, chardet=latest, pep517=latest, pkg_resources=latest, wheel=latest, progress=latest, contextlib2=latest, ipaddr=latest, pip=latest, distlib=latest, distro=latest, pytoml=latest, idna=latest, certifi=latest, pyparsing=latest, six=latest, html5lib=latest, lockfile=latest, appdirs=latest, webencodings=latest, setuptools=latest, colorama=latest, requests=latest, packaging=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivato

# . ./venv/bin/activate

# USE_PYTHON_3=1 ./bin/certbot-auto -v renew
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://archive.canonical.com/ubuntu focal InRelease                                                 
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease                                          
Hit:6 https://deb.opera.com/opera-beta stable InRelease
Hit:7 https://deb.opera.com/opera-developer stable InRelease
Hit:8 https://deb.opera.com/opera-stable stable InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```
Note that this version of Ubuntu does not offer a `python-virtualenv` package ... only `python3-virtualenv`

## Certbot's behavior differed from what I expected because:

`certbot-auto` didn't properly detect my python3 environment and it didn't seem to do anything.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

No logs were produced, becaue `certbot-auto` didn't appear to do anything.

**Comment by HippoMan** [comment] 2020-10-22 18:18
Note that I get the same results whether or not I prepend `USE_PYTHON_3=1` to the certbot-auto command invocation.

**Comment by bmw** [comment] 2020-10-23 17:19
Closing as a duplicate of #7941. I suggested a couple different alternatives to installing Certbot on the platform in that thread though.

**Closed by bmw** 2020-10-23 17:19 UTC
