### ISSUE TITLE
certbot 0.28.0 wrongly split the chain obtained via acmev2 if the chain has CRLF lineending

### ISSUE THREAD

**Issue by szjozsef** [certbot/certbot#7875] opened 2020-04-02 09:05 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian 9.12 (stretch) 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager 0.28.0-1~deb9u2

## I ran this command and it produced this output:
certbot certonly --webroot -w /var/www/example.com/public_html/ -d example.com -d www.example.com --server 'https://api.buypass.com/acme/directory'

## Certbot's behavior differed from what I expected because:
The ACME v2 api server from buypass.com returns the pem-certificate-chain with CRLF lineending.
The certificate is extracted correctly and get's correctly converted to LF line ending.
The cain file get extracted with a wrong offset, containing a few charactes (in my case up to 35 characters) from the chain file, including the text: "-----END CERTIFICATE-----" and with CRLF linending
Also the fullchain.pem file is reconstructed by appending the cert file and the extracted chain file, resuling in a mixed lineending file, which contains extraneous characters between the certificate and the chain file.
Like this:
xxxxxxxxxxxxxxxxxxxxxxxxxxxAVbdrquLF
-----END CERTIFICATE-----LF
AVbdrquCRLF
-----END CERTIFICATE-----CRLF
-----BEGIN CERTIFICATE-----CRLF
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCRLF
...

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
the certbot logs as everyting is OK, without error

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by alexzorin** [comment] 2020-04-02 11:56
The behavior is reproducible on master. I think an effort should be made to make this more robust (i.e. don't assume that load and dump are going to produce exactly the same byte buffer for the same certificate), because it's caused issues before (#7625). 

Log including the cert response: [letsencrypt.log](https://github.com/certbot/certbot/files/4420754/letsencrypt.log)

The resulting `fullchain.pem` is mangled:

    -----BEGIN CERTIFICATE-----
    MIIGQTCCBCmgAwIBAgIKKYpamf8RmbntxDANBgkqhkiG9w0BAQsFADBLMQswCQYD
    VQQGEwJOTzEdMBsGA1UECgwUQnV5cGFzcyBBUy05ODMxNjMzMjcxHTAbBgNVBAMM
    FEJ1eXBhc3MgQ2xhc3MgMiBDQSA1MB4XDTIwMDQwMjExNDAzN1oXDTIwMDkyOTIx
    NTkwMFowADCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ7zq0phdfxa
    64pdVrpAXfU1p4AXto1dCeolJ9N+4R12CmKd7Dxz/8fIjLabFK7jvtSyyy2Qd6Jy
    4Pdz6sfpPaAsOAQqDWBbqzrMHxa2vOiOmo9tgVRtUf1nUNZkEu+xm3Oiae7W06qN
    lA6PcdjA66Sc+I05LpsPEKNiGgMu5V5yiI444kavEcZITTxq2sSb8BzR+oA9y3QL
    yq0YTyOkZl2Nr1K8GJMVJqXlyK5sTlAH3/MWIgz4GsXovXucghLTaNkjOpdwPeJe
    7fkFOpsA4ShhpbkPqbo3j1g5gnZxi3/r8t3E1pBzXR422smF3SQCFj4GvurVf+Xo
    gn7VZyAB6QECAwEAAaOCAnAwggJsMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUJ1Kk
    by0qq0CTkOzWacv+fGE7fEIwHQYDVR0OBBYEFJ3cy8umx1CV7AlF2HtIHPSLwr+/
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    HwYDVR0gBBgwFjAKBghghEIBGgECBzAIBgZngQwBAgEwOgYDVR0fBDMwMTAvoC2g
    K4YpaHR0cDovL2NybC5idXlwYXNzLm5vL2NybC9CUENsYXNzMkNBNS5jcmwwHwYD
    VR0RAQH/BBUwE4IRZjcxMDVkZmYubmdyb2suaW8wagYIKwYBBQUHAQEEXjBcMCMG
    CCsGAQUFBzABhhdodHRwOi8vb2NzcC5idXlwYXNzLmNvbTA1BggrBgEFBQcwAoYp
    aHR0cDovL2NydC5idXlwYXNzLm5vL2NydC9CUENsYXNzMkNBNS5jZXIwggEEBgor
    BgEEAdZ5AgQCBIH1BIHyAPAAdgC72d+8H4pxtZOUI5eqkntHOFeVCqtS6BqQlmQ2
    jh7RhQAAAXE6sXB3AAAEAwBHMEUCIBiAni8JdwL1xRmiuFjJS78J2TlaiWfm42QV
    tF+LPxrkAiEAo2G84qVVjjkYaUWUMK4UroyMzmalWQ8TNFezHwC1ftYAdgBvU3as
    MfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAXE6sXBNAAAEAwBHMEUCIQCO
    lh2oub5LvnoLSO3nCtPbi9RuuLMS/kql7I4EcID7dwIgDWY9stH/QM6IfanV/U/Q
    Vd6XLFhIA4amdmCLwbLn0lwwDQYJKoZIhvcNAQELBQADggIBAAow2hhq8i5bntcY
    u4w2YQrzni+XWF8zc+Bd4Pp+6YgyZZIcslaTjak2IBFIz3TeGt9S/jKz55nGp9np
    e0rCwqah7dQ4KhW8YSMcWKoPCFbQF/S9xQDdqguLHmB2m7gpUXo8QAY1hq4s3REZ
    k+NWzirRzgvB8HoCKIfSh/72GPRXeb8322hq/WnrOD/5cpYgiJXVgRfKE7l0ZwP8
    kMDeo42p7MbN4Q0dlTW5Djanv6sW8u3mdPFBSCP9zt8efFLUX5Y6pyRKQHCLahgN
    lRb+fUZyuzACnP4YoeOF6wSw1NILRKcGm2BKcooypgz+shs6jSt2mre/WEPpkfVF
    jXbvGEQqHapbfqV1laCHzWgMWdZ8uny3g7LhCtzEdr9FQ634e8nxwcZp2u6vq3dp
    V4PEl+YsrmpFfVCTnZDFk6wrhMyfomJ9tqApbKPogzCODkAIs1l5fya8qFFwoGYH
    KYcmqb83LLiWG9+i25RoopLDf/vrKsRd136Ee8VeS017LgzBV5ywKoLMvRhtUYMr
    ejAMk2+RMDd60hMI7Gi6SL3h+u92Rr2Qiqdn9Uo5Az+HOsb5p/a8OW937Z5d1LqH
    pIHSLCdlbsaydcQBanqZqxkn39lfsa9z6nWMHhB9iUk7IXRLq2GORwKHq06o078K
    IlV+YOkJt4xBc+elm9B5BKCPp+36
    -----END CERTIFICATE-----
    KCPp+36
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGFjCCA/6gAwIBAgIJMvoIN2vyPCATMA0GCSqGSIb3DQEBCwUAME4xCzAJBgNV
    BAYTAk5PMR0wGwYDVQQKDBRCdXlwYXNzIEFTLTk4MzE2MzMyNzEgMB4GA1UEAwwX
    QnV5cGFzcyBDbGFzcyAyIFJvb3QgQ0EwHhcNMTcwNTIzMTI1NzM4WhcNMjcwNTIz
    MTI1NzM4WjBLMQswCQYDVQQGEwJOTzEdMBsGA1UECgwUQnV5cGFzcyBBUy05ODMx
    NjMzMjcxHTAbBgNVBAMMFEJ1eXBhc3MgQ2xhc3MgMiBDQSA1MIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEAu5hBKP7+r8dtoZT14U1OKtTBSzI+U3nUC4p5
    ht3kD/DR9hWPB6/2Kljii7Ft4AXTSxS30YGwBpqEtIHzxjfgf/fuTb/eBx5wWhxz
    v0RWosEhUwyQqYX0lVEqHruRV6rjlkvtNYkhdEU2kmQs6j4T66p8AbgZLZSq42k+
    lEU3hGQ8NpDiKSvxX5aVorxsRel98AP0VaRVMZfeMYI5DkTcfWkTMrD+dDqGejOB
    S3V1+EstPV1Auf85LiUo0jbwy1ZOppVFftUczMyBwOENOrUwfjDyQnQrn4qhq+TD
    qAMua2/2+gX0jHZ/wwdP4mhSPjmlpNejMmzXbykDu74BJqWfBvz9fpG6C344M0Hv
    WZ4QLOTP5dKwMVTGF6S/QK3jJb8SdB0cDMCzsLBagC/F56+cLMntOXsv4DOvD3HG
    rmrEZKsjJB+0XWIVwdPif4ItQm6MJZq4rGkPymaKsaKAes7OpFflFj7ruQIuc380
    l7c98uVpIuszMTak3L8CaPN6nrpmIUGAaOT1fDdfANKnb5vVosSr6W/ETkF8gFsP
    Ljy09wzrUKH/Gnk7EdoBNwdy5zwP8z1F99j8QUjVVQwckBO/YsgJI6MOXoHqeHS3
    LVT18dZ66FJLYZTIXZQTtLDo3eQ6eL+vSNnakxMjO4nH90BQGy6l0CRPCIi0+a0A
    8HaUbA8CAwEAAaOB+TCB9jAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFMmA
    d+BikoL1RpzzuvdMw964o605MB0GA1UdDgQWBBQnUqRvLSqrQJOQ7NZpy/58YTt8
    QjAOBgNVHQ8BAf8EBAMCAQYwHwYDVR0gBBgwFjAKBghghEIBGgECBzAIBgZngQwB
    AgEwPQYDVR0fBDYwNDAyoDCgLoYsaHR0cDovL2NybC5idXlwYXNzLm5vL2NybC9C
    UENsYXNzMlJvb3RDQS5jcmwwMwYIKwYBBQUHAQEEJzAlMCMGCCsGAQUFBzABhhdo
    dHRwOi8vb2NzcC5idXlwYXNzLmNvbTANBgkqhkiG9w0BAQsFAAOCAgEAvrrbRl50
    56kq5vOKuWUcazLEHuJlVyjr1QBpLoq1dZNjpmIFLjOmG7LLMv83Hs2d5Ww0H6Sg
    NlloNjp9JYo5PCruL+djEb5Ct787d0dD+sQ9wkEQNK/fgQ6hqef4Z/lYxmtNqCyR
    xxuK8LcgvMG5D3W9CLZYIqCyGgKZqAE0FtWyinPTzCdvxzCMRZz2dYJLN+2nejMs
    z1+FswjSnOyva0XegBZnjhrHNI3ZyB7nPILephet0AiYyXpXUuEvBXa6qVkeK8mf
    6uGgq+zTXqK52cKu2woOa9TV2/oyC1DzVNoZbfOgJ0Geh2TWeJn8rL+W4VrvxT6K
    w2+lk/YeyXgFd6km3FgEQk4pRnzuV3OtDErdQRW2lssR3gl9u2DF9IJYbzoRiVvy
    7wTHuchTygpG8n/K9ajaWDdEL7+jSvPjU5+HBcHwgcxDSYF3QSLNIsOaBS5O1Hob
    440ryhvw5lGgzqkVsToXJCaaSziOmqbzzNPHgQ0HM+vzvDTzC0Z6ikF0LGjkPSML
    a4qKpyJzIjLOjqPVnI51920yg/zZuN5nz1lQcH+0q7GVeoRaHE2iFyJnHXR+Ljl9
    2SHWMrw1jbhk7D5/u1XmtsS0r1oeHgbF7zi7ESOVLFs2Zcm5kewkPDljznSJTE94
    1YS4d5yABnRwkq6PSaKEvBRshdl84c/Fd7Y=
    -----END CERTIFICATE-----

**Comment by adferrand** [comment] 2020-04-02 13:17
So there are two problems: a wrong offset, and the `CRLF` line endings.

I will say here that I had some troubles in the past with the PEM encoding because of `CRLF` line endings when porting Certbot on Windows. I fixed that by always emitting cryptographic material with `LF` line endings. On top of this, Boulder explicitly refuses `CRLF` line endings: https://github.com/letsencrypt/boulder/issues/3557

In #7625, issue has been considered as won't fix, because the CA Server was not following the official specifications defined in RFCs. I would say that the wrong offset fall in the same category, and the fix should be from BuyPass.

However. For the `CRLF` line endings, I could not find any clear indication that a PEM file *should* be formated with `LF` line endings. It seems to be a *de facto* standard because historically, all there cryptographic tools have been developped for Unix systems first ...

At the very minimum BuyPass should conform to the usual `LF` line endings, because it will cause very bad time to users in various situation. But we may also handle that on our side, because I seems to me that it is not a violation of specifications to use `CRLF` line endings here.

What do you think @bmw?

**Comment by szjozsef** [comment] 2020-04-02 15:01
I already discussed with buypass CA regarding this (prior to open this issues here).
https://community.buypass.com/t/x2hhvnf/chainfullchain-file-contains-unexpected-characters
It seems that in the referenced RFC (https://tools.ietf.org/html/rfc7468#section-3) the eol is defined as:   eol        = CRLF / CR / LF
So it seems the any mentioned combination should be considered as valid.

**Comment by bmw** [comment] 2020-04-02 17:32
Thanks for all the info!

Regardless of what Buypass does, I think this is something we should fix on our end since per the links szjozsef provided, the spec allows for CRLF line endings.

The code that needs to be updated is [here](https://github.com/certbot/certbot/blob/4ca86d9482cbb9bca04335bfb7dbd892cefe91c8/certbot/certbot/crypto_util.py#L481-L493) if anyone wants to take a crack at it.

**Comment by alexzorin** [comment] 2020-04-02 21:50
How about the regex-based approach as appears in this pure-Python `pem` library: 

https://github.com/hynek/pem/blob/f35fe54bbb8cc2c038814ec33ca1d3b72a323fc7/src/pem/_core.py#L202-L225

I took a quick go at this approach in this commit: https://github.com/certbot/certbot/commit/edc6eb2974ca4a58f84c4ccd0f22998572e93f02 , lmk if you're interested in a PR.

**Comment by bmw** [comment] 2020-04-02 23:29
That seems like an excellent approach to me personally.

You're right that we should be a little careful with whitespace. According to https://tools.ietf.org/html/rfc8555#section-9.1, the values should be `stricttextualmsg` from https://tools.ietf.org/html/rfc7468#section-3 which does not allow whitespace, however, maybe it's possible for it to creep in [here](https://github.com/certbot/certbot/blob/4ca86d9482cbb9bca04335bfb7dbd892cefe91c8/acme/acme/client.py#L896-L900)? If so, we could alternatively fix that problem there.

If you're interested in looking into this whitespace problem a bit and proposing a solution, a PR would be great!

**Closed** 2020-04-07 23:19 UTC
Labels: area: spec-compliance, bug, priority: high
