### ISSUE TITLE
Certbot not recognizing certbot-cloudflare-dns plugin even though its installed

### ISSUE THREAD

**Issue by RandomGuy70hz** [certbot/certbot#9589] opened 2023-02-21 01:41 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows Server 2019

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
OS Package manager (also tried the pip install).

## I ran this command and it produced this output:
C:\Users\Administrator>certbot certonly --dns-cloudflare --dns-cloudflare-credentials C:/cloudflare.ini -d [mysite]
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-cloudflare-credentials C:/cloudflare.ini

C:\Users\Administrator>

C:\Users\Administrator>certbot plugins
Saving debug log to C:\Certbot\log\letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

## Certbot's behavior differed from what I expected because:
It's not recognizing the plugin. Ive added certbot to path and have tried installing the plugin via GitHub and pip. It installs but still not being recognized.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
cannot locate log on this windows machine as its not in C:\Program Files\Certbot

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
I am using IIS 10

**Comment by alexzorin** [comment] 2023-02-21 09:51
Plugins aren't supported on Windows, sorry!

Closing as a dupe of #8048.

**Closed** 2023-02-21 10:12 UTC

**Comment by osirisinferi** [comment] 2023-02-21 12:31
Not supported, agreed, but it *should* be possible to install a third party plugin on Windows. See e.g. https://github.com/certbot/certbot/issues/9222 for more info (saw it linked by Github on #8048).

**Comment by ciedema** [comment] 2023-09-20 03:36
> Not supported, agreed, but it _should_ be possible to install a third party plugin on Windows. See e.g. #9222 for more info (saw it linked by Github on #8048, so OP should have been able to find out on their own, but thought I'd just mention it anyway 🙂).

After looking the "instructions" above I did the following

What I've done is the following using the above post:

- Download the wheel ("Built Distribution", file with .whl extension) from https://pypi.org/project/certbot-dns-cloudflare/#files
- Unpack the wheel file, which is just a ZIP file, into C:\Program Files (x86)\Certbot\pkgs
(Obviously if you've installed Certbot somewhere else, you should unzip the file in the appropriate directory.)
You can just rename the .whl file to .whl.zip if necessary

- You now should have the directories certbot_dns_cloudflare and certbot_dns_cloudflare-2.6.0.dist-info in the pkgs dir, among all the other packages

- Edit the file METADATA in the certbot_dns_cloudflare-2.6.0.dist-info directory using WordPad (NotePad doesn't recognise the newlines correctly): Look for the line containing Requires-Dist: cloudflare and remove it

- Download the python-cloudflare Module from https://github.com/cloudflare/python-cloudflare and copy the C:\Program Files (x86)\Certbot\pkgs
