### ISSUE TITLE
Installation error on Fedora Core 23

### ISSUE THREAD

**Issue by zopyx** [certbot/certbot#1676] opened 2015-12-03 12:15 UTC
Running FC 23

(letsencrypt)[root@vmd9666 letsencrypt]# uname -a
Linux vmd9666.contabo.host 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

(letsencrypt)[root@vmd9666 letsencrypt]# ./letsencrypt-auto
Updating letsencrypt and virtual environment dependencies......Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ouX3F6/cffi

(fresh checkout as of 2015/12/03)

**Comment by oleid** [comment] 2015-12-03 14:48
try running letsencrypt-auto with "-v" to get more information on what's wrong.

**Comment by levskaya** [comment] 2015-12-03 14:58
Hmm. I just double-checked and confirmed that ./letsencrypt-auto works on a clean install of Fedora Cloud 23 on an AWS EC2 instance as default user 'fedora'.

There's a potentially informative discussion of this problem here: 
https://community.letsencrypt.org/t/python-setup-py-egg-info-failed-with-error-code-1/2786/7  
that suggests it might be caused by compilation problems while building cffi

**Comment by oleid** [comment] 2015-12-03 21:22
I guess this might be the same issue than #1677.

**Comment by schoen** [comment] 2018-09-25 00:40
I'm going to hypothesize that @oleid was right to suspect this is a duplicate of #1677. We've continued to have a bunch of problems when compiling on low-memory systems (most notably Raspberry Pis, but also other systems).

If the problem persists today in a new environment with a large amount of RAM, please re-open this issue or open a new one. (A workaround is also to use OS packages instead of `certbot-auto`; we've made some progress on getting more up-to-date ones out there for many environments.)

**Closed by schoen** 2018-09-25 00:40 UTC
Labels: area: certbot-auto, area: fedora / redhat / CentOS
