### ISSUE TITLE
Nginx fails to deploy cert

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5419] opened 2018-01-12 01:10 UTC
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Dev instructions (I was on commit 5d58a3d847f5a93b8eaaaea482063fae69d2b2d7 so this is unrelated to HTTP01 support in Nginx)

## I ran this command and it produced this output:

Starting with the default Nginx config on this system I ran:

```
sudo certbot -a webroot -w /var/www/html/ -d example.org -i nginx --no-redirect
sudo certbot -a webroot -w /var/www/html/ -d abc.example.org  -d def.example.org -i nginx --no-redirect
```
which gave me:
```
nginx: [emerg] duplicate listen options for [::]:443 in /etc/nginx/sites-enabled/default:200
Encountered exception:
Traceback (most recent call last):
  File "/home/bmw/src/certbot/certbot/client.py", line 462, in deploy_certificate
    self.installer.restart()
  File "/home/bmw/src/certbot/certbot-nginx/certbot_nginx/configurator.py", line 687, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/home/bmw/src/certbot/certbot-nginx/certbot_nginx/configurator.py", line 919, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
MisconfigurationError: nginx restart failed:



Calling registered functions
Rolling back to previous server configuration...
Reporting to user: We were unable to install your certificate, however, we successfully restored your server to its prior configuration.
```

**Comment by elkhan** [comment] 2018-01-19 09:42
What helped me was deleting `ipv6only=on` from `listen [::]:443 ssl` - `nginx/sites-available/whatever.com`

**Comment by owalerys** [comment] 2018-01-24 03:22
Also having this issue, certs issued with v0.19.0 Ubuntu client are fine because they are missing the listen [::]:443 line, but certs issued with v0.21.0 certbot-auto client have problems due to the ipv6only=on line.

**Comment by owalerys** [comment] 2018-01-24 15:02
It seems like `ipv6only=on` is the default configuration for this setting now for nginx in its current version (even as of 2 years ago), so omitting the line from the certbot nginx plugin would solve this issue.

**Comment by ohemorange** [comment] 2018-03-01 21:04
This looks like a duplicate of https://github.com/certbot/certbot/issues/5550, reopen if it's not.

**Closed by ohemorange** 2018-03-01 21:04 UTC
Labels: area: nginx
