### ISSUE TITLE
Creating Virtual Environment - "No module named site" on Ubuntu 14.04

### ISSUE THREAD

**Issue by hanakemt** [certbot/certbot#3220] opened 2016-06-28 11:16 UTC
When running certbot-auto for the first time on Ubuntu 14.04 the error  'Creating Virtual Environment - "No module named site"' stops the installation process. You should run certbot-auto as root (e.g. 'sudo certbot-auto') to be successful.

**Comment by cowlicks** [comment] 2016-06-28 15:07
@hanakemt did you try running `sudo certbot-auto`?

**Comment by hanakemt** [comment] 2016-06-28 15:36
@cowlicks: Yes, I did and succeeded (see also in my entry above). I have shared it as it may be useful for others.

**Comment by cowlicks** [comment] 2016-06-28 17:55
Oh sorry, I thought that was part of the error message.

**Comment by bmw** [comment] 2016-06-29 00:28
`site` is [part of the Python standard library](https://docs.python.org/2.7/library/constants.html#constants-added-by-the-site-module). This implies there is a broken install of in your user's path, which in your case, is avoided when using `sudo`. Have you used `pip` to install Python packages on your system before?

**Comment by hanakemt** [comment] 2016-06-29 13:13
@bmw: I mostly used aptitude. It may be that I added some python packages later with pip, don't remember. If I run python (2.7.6, without and with sudo), and import site, then help(site) delivers the same result. So site is accessible. What else can be wrong? (I've installed certbot-auto also on debian 7, and there it works well with python 2.7.3).

**Comment by bmw** [comment] 2016-06-29 20:40
While verbose, try running this command which should be equivalent to what `certbot-auto` is trying to do at this step:
```
virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) $(mktemp -d)
```

If that works, I recommend deleting `~/.local/share/letsencrypt` and trying again. If it doesn't work, it suggests a problem with `virtualenv` or maybe the Python found at `$(command -v python2.7 || command -v python27 || command -v python2 || command -v python)`.

**Comment by hanakemt** [comment] 2016-06-30 06:22
@bmw: Thank you for your suggestions, I tried them.

1) 'virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python -vvvvv' worked well.

2) I deleted '~/.local/share/letsencrypt' that was owned by root, then run 'sudo ./certbot-auto' again. I noticed this warnings:

"The directory '/home/myhome/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/myhome/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag."

3) As next steps, I deleted ~/.local/share/letsencrypt/, ~/.cache/pip/, and also /root/.local/share/letsencrypt/ and /root/.cache/pip/.

4) Then I ran 'sudo -u myusername -H ~/net/letsencrypt/bin/certbot-auto'. It installed cerbot-auto again, created ~/.local/share/letsencrypt/ and ~/.cache/pip/ with myusername as owner, without problem, without warning.

5) However, '~/net/letsencrypt/bin/certbot-auto' alone still complains: "Creating virtual environment... ImportError: No module named site".

**Comment by bmw** [comment] 2016-07-01 21:08
Hm. It's definitely not clear to me what the problem is. To try and get more information out of the script, can you try the following:

1. Change the first line of the file to `#!/bin/sh -x`.
2. Run `certbot-auto` again but make sure to include `--no-self-upgrade` and `--verbose` on the command line.

**Comment by hanakemt** [comment] 2016-07-02 09:02
When executed the original 'certbot-auto -v' again, I got now these error messages:
"ERROR: The executable /home/myhome/net/letsencrypt/bin/:/usr/local/monodevelop-3.0.3.5/share/letsencrypt/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/myhome/net/letsencrypt/bin' (should be u'/home/myhome/net/letsencrypt/bin/:/usr/local/monodevelop-3.0.3.5/share/letsencrypt')
ERROR: virtualenv is not compatible with this system or executable"

Then I deleted all letsencrypt folders, and got the same errors. It seems virtualenv conflicts with mono on my computer.

Then I went to a virtual machine, also with Ubuntu 14.04, and installed certbot-auto there, without problems.

How can I delete / rebuild the virtualenv?

**Comment by bmw** [comment] 2016-07-05 17:46
The virtual environment created by `certbot-auto` is in `~/.local/share/letsencrypt` so I believe you've deleted that multiple times. As for the actual `virtualenv` executable, `certbot-auto` installs one through `apt` but it's possible you have another one on your system (from something like `pip`). Is there a difference in the output of `which virtualenv`, running the command once with `root` and once without? If not, you can try reinstalling the package from `apt`.

Two more questions:

1. Following the instructions I wrote [here](https://github.com/certbot/certbot/issues/3220#issuecomment-230047686), where does that error occur?
2. What's the value of `PATH` before calling the script.

**Comment by hanakemt** [comment] 2016-07-06 10:06
Thanks again for the suggestions. As virtualenv and PATH had produced the same output with and without 'sudo -u hanak', I uninstalled virtualenv by pip and purged python-virtualenv by aptitude (apt-get). Then I ran './certbot-auto --no-self-upgrade --verbose' that failed in the well-known error, and then 'sudo -u hanak ./certbot-auto --no-self-upgrade --verbose' that succeeded. I have noticed a slight difference at the end of the outputs. This was produced with 'sudo -u ...':

python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/hanak/.local/share/letsencrypt/bin/python2.7
Also creating executable in /home/hanak/.local/share/letsencrypt/bin/python
Installing setuptools, pip...done.
Installing Python packages...
Installation succeeded.

And this without 'sudo -u ...':

python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in :/usr/local/monodevelop-3.0.3.5/share/letsencrypt/bin/python2.7
Also creating executable in :/usr/local/monodevelop-3.0.3.5/share/letsencrypt/bin/python
ImportError: No module named site
ERROR: The executable :/usr/local/monodevelop-3.0.3.5/share/letsencrypt/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/home/hanak/net/letsencrypt/bin' (should be u'/home/hanak/net/letsencrypt/bin/:/usr/local/monodevelop-3.0.3.5/share/letsencrypt')
ERROR: virtualenv is not compatible with this system or executable

So it seems to me that with 'sudo -u ...' it creates the ~/.local/share/letsencrypt/ folder while without it it creates the letsencrypt folder in <current_folder>/:/usr/local/monodevelop-3.0.3.5/share/, with incorrect content (I compared the two folders).

Purging mono-devel, mono-runtime and related packages did not help.

Then I copied the missing folders and files from ~/.local/share/letsencrypt/ to '<current_folder>/:/usr/local/monodevelop-3.0.3.5/share/letsencrypt/, and cert-autobot started to work!

So, now the question is this: why is the folder letsencyrpt created in the folder ':/usr/local/monodevelop..." wihtout sudo instead of the folder '~/.local/share/'?

**Comment by bmw** [comment] 2016-07-06 20:49
Ah! I omitted this detail earlier because it has never been relevant in the past. `certbot-auto` creates the virtual environment in `${XDG_DATA_HOME:-~/.local/share}/letsencrypt`. In other words, if the `XDG_DATA_HOME` environment variable is set, we use that, otherwise, we use `~/.local/share`.

**Comment by hanakemt** [comment] 2016-07-07 11:11
Indeed, ${XDG_DATA_HOME} is set to ":/usr/local/monodevelop-3.0.3.5/share". Comparing the non-working and working installations, here are the differences:

hanak@gondola:~/net/letsencrypt/bin$ diff -rq ":/usr/local/monodevelop-3.0.3.5/share/letsencrypt/" ~/.local/share/letsencrypt/
Only in /home/hanak/.local/share/letsencrypt/bin: activate
Only in /home/hanak/.local/share/letsencrypt/bin: activate.csh
Only in /home/hanak/.local/share/letsencrypt/bin: activate.fish
Only in /home/hanak/.local/share/letsencrypt/bin: activate_this.py
Only in /home/hanak/.local/share/letsencrypt/bin: certbot
Only in /home/hanak/.local/share/letsencrypt/bin: easy_install
Only in /home/hanak/.local/share/letsencrypt/bin: easy_install-2.7
Only in /home/hanak/.local/share/letsencrypt/bin: jws
Only in /home/hanak/.local/share/letsencrypt/bin: letsencrypt
Only in /home/hanak/.local/share/letsencrypt/bin: ndg_httpclient
Only in /home/hanak/.local/share/letsencrypt/bin: pbr
Only in /home/hanak/.local/share/letsencrypt/bin: pip
Only in /home/hanak/.local/share/letsencrypt/bin: pip2
Only in /home/hanak/.local/share/letsencrypt/bin: pip2.7
Only in /home/hanak/.local/share/letsencrypt/bin: unit2
Only in /home/hanak/.local/share/letsencrypt/bin: wheel
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: _abcoll.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: abc.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: codecs.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: copy_reg.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: distutils
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: fnmatch.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: genericpath.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: linecache.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: locale.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: os.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: posixpath.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: re.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: acme
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: acme-0.8.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: argparse-1.4.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: argparse.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: argparse.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: augeas.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: augeas.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: certbot
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: certbot-0.8.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: certbot_apache
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: certbot_apache-0.8.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: cffi
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: cffi-1.4.2-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: _cffi_backend.so
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ConfigArgParse-0.10.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: configargparse.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: configargparse.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: configobj-5.0.6-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: configobj.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: configobj.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: cryptography
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: cryptography-1.2.3-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: dialog.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: dialog.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: easy_install.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: easy_install.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: enum
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: enum34-1.1.2-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: funcsigs
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: funcsigs-0.4.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: idna
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: idna-2.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ipaddress-1.0.16.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ipaddress.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ipaddress.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: letsencrypt
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: letsencrypt-0.7.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: linecache2
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: linecache2-1.0.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: mock-1.0.1-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: mock.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: mock.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ndg
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ndg_httpsclient-0.4.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ndg_httpsclient-0.4.0-py2.7-nspkg.pth
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: OpenSSL
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ordereddict-1.1-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ordereddict.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: ordereddict.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: parsedatetime
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: parsedatetime-2.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pbr
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pbr-1.8.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pip
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pip-8.0.3-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pkg_resources
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: psutil
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: psutil-3.3.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pyasn1
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pyasn1-0.1.9.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pycparser
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pycparser-2.14-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pyOpenSSL-0.15.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pyrfc3339
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pyRFC3339-1.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: python2_pythondialog-3.3.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: python_augeas-0.5.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pytz
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: pytz-2015.7.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: requests
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: requests-2.9.1.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: setuptools
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: setuptools-20.2.2-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: six-1.10.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: six.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: six.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: traceback2
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: traceback2-1.4.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: unittest2
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: unittest2-1.1.0.dist-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: validate.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: validate.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: _version.py
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: _version.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: wheel
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: wheel-0.29.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.component-4.2.2-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.component-4.2.2-py2.7-nspkg.pth
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.event-4.1.0-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.event-4.1.0-py2.7-nspkg.pth
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.interface-4.1.3-py2.7.egg-info
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7/site-packages: zope.interface-4.1.3-py2.7-nspkg.pth
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: site.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: sre_compile.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: sre_constants.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: sre_parse.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: stat.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: types.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: UserDict.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: warnings.pyc
Only in /home/hanak/.local/share/letsencrypt/lib/python2.7: _weakrefset.pyc
Only in /home/hanak/.local/share/letsencrypt/: local
Only in /home/hanak/.local/share/letsencrypt/: pip-selfcheck.json

Lots of files are missing from the ${XDG_DATA_HOME}/letsencrypt/ folder! Perhaps the use of ${XDG_DATA_HOME is inconsequent in the certbot-auto script?

**Comment by bmw** [comment] 2016-07-07 18:09
Looks this is a known issue upstream if a colon is in the directory path (see pypa/virtualenv#395). Until that is resolved, you can either continue running `certbot-auto` as root or set the `VENV_PATH` environment variable to where you'd like `certbot-auto` to create the virtual environment.

**Comment by hanakemt** [comment] 2016-07-08 04:52
@bmw: After copying the missing files from ~/.local/share/letsencypt to ${XDG_DATA_HOME}/letsencrypt/ certbot-auto works well, so it can be started without sudo, too. However, certbot-auto still needs sudo-right when it updates the apt-repo, so the gain is small. :-)

Strange that the issue with the colon has been known since early 2013, and it is still unsolved (see pypa/virtualenv#395).

Thank you for helping me in finding a temporary solution.

**Comment by ohemorange** [comment] 2018-11-07 01:13
Closing in favor of #3079

**Closed by ohemorange** 2018-11-07 01:13 UTC
Labels: area: certbot-auto
