### ISSUE TITLE
urn:acme:error:connection error when when going through multiplexer

### ISSUE THREAD

**Issue by andrewmh20** [certbot/certbot#4214] opened 2017-02-13 22:17 UTC
I am using a port multiplexer, sslh, to use 443 for multiple services. For that to work, I need any services listening on 443 to only listen on localhost. sslh listens to 443 "outside" and forwards traffic to the appropriate port. 

When I set the ports.conf file to show: 
<IfModule ssl_module>
        Listen 127.0.0.1:443
</IfModule>

cerbot fails with the urn:acme:error:connection even though the server can be accessed, on port 443 (using a browser and curl). 

Once I change ports.conf to the default of listening on every IP at port 443, it works.

The renew process also fails with this issue.

**Comment by andrewmh20** [comment] 2017-02-13 22:23
It seems to fail any time it goes through the multiplexer, it's not per se about the ports.conf file

**Comment by andrewmh20** [comment] 2017-02-13 22:27
Possibly, probably, same issue: #341

**Comment by SwartzCr** [comment] 2017-02-14 20:35
@schoen do you think you could help with this?

**Comment by schoen** [comment] 2017-02-14 20:47
@andrewmh20, do you know the basis on which the port multiplexer decides where to forward connections? And do you understand how the TLS-SNI-01 validation method is working?

The CA is trying to make an inbound connection using a custom self-signed certificate for a custom name ending in `.acme.invalid` — so, would the multiplexer be OK with that and would it forward that connection to the right place in this case?

Where is this ports.conf from and what is its effect?

**Comment by andrewmh20** [comment] 2017-02-14 21:04
This is the multiplexer https://github.com/yrutschle/sslh .
It says it does some sort of analysis based on the beginning of the packets---I do not know how the validation method works....but if it is not coming in as a normal looking ssl packet then I suppose it would not in fact be forwarded...I didn't actually think of that....

Sorry for not fully giving all details---ports.conf I'm using is the default apache2 file, listening on 443 and 80. The problem arises when I have the multiplexer on and modify ports.conf to not listen on 443 from any ip.

**Comment by schoen** [comment] 2017-02-15 01:20
So the sslh and Certbot are running on the same machine in this case and have a conflict with trying to bind port 443? Is that where the trouble comes in? So if Certbot could just listen on localhost, then sslh could forward HTTPS traffic to localhost:443 and SSH traffic to localhost:22?

**Comment by andrewmh20** [comment] 2017-02-15 05:41
That sounds correct

**Comment by schoen** [comment] 2017-02-24 22:35
(I added the nginx category just because in principle this will affect nginx in the same way. So there should probably be a generic mechanism.)

**Comment by schoen** [comment] 2017-02-24 22:37
Is there maybe a way, as a workaround, to ask Certbot to listen on a nonstandard port and then use a kernel firewall rule or userspace port forwarder to forward localhost:443 to that port? Like set `--tls-sni-01-port` to 4443 and then have a listener on localhost:443 that forwards everything to localhost:4443?

**Comment by SwartzCr** [comment] 2017-08-28 21:23
I'm going to close this as a duplicate of #341, but we should try to address that issue if we can

**Closed by SwartzCr** 2017-08-28 21:23 UTC
Labels: area: apache, area: nginx, area: standalone, feature request
