### ISSUE TITLE
Nginx plugin crashes when non-ascii configuration file read

### ISSUE THREAD

**Issue by g6123** [certbot/certbot#5337] opened 2017-12-18 20:33 UTC
## My operating system is (include version):

Arch Linux ARM 4.9.69-1-ARCH

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

OS package manager (`pacman -S certbot-nginx`)

## I ran this command and it produced this output:

I ran this command:

`sudo certbot --nginx`

and it produced this:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10453: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:

I found that the error comes from `/etc/nginx/mime.types` which was included in the default nginx package. If there is any non-ascii encoded file in the nginx configuration path, the same error occurs.

## Here is a Certbot log showing the issue:

<details>
<summary>Click to expand</summary>

```
2017-12-18 20:21:34,224:DEBUG:certbot.main:certbot version: 0.20.0
2017-12-18 20:21:34,235:DEBUG:certbot.main:Arguments: ['--nginx']
2017-12-18 20:21:34,243:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-12-18 20:21:34,417:DEBUG:certbot.log:Root logging level set at 20
2017-12-18 20:21:34,427:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-12-18 20:21:34,434:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2017-12-18 20:21:34,742:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.20.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 685, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 189, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 25, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 248, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 248, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3.6/site-packages/certbot_nginx/configurator.py", line 156, in prepare
    self.parser = parser.NginxParser(self.conf('server-root'))
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 35, in __init__
    self.load()
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 42, in load
    self._parse_recursively(self.config_root)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 63, in _parse_recursively
    self._parse_recursively(subentry[1])
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 53, in _parse_recursively
    trees = self._parse_files(filepath)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 203, in _parse_files
    parsed = nginxparser.load(_file)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/nginxparser.py", line 122, in load
    return loads(_file.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10453: ordinal not in range(128)
2017-12-18 20:21:34,759:ERROR:certbot.log:An unexpected error occurred:
```

</details>

**Comment by g6123** [comment] 2017-12-18 20:37
And this is how I dealt with the issue: https://github.com/g6123/certbot/commit/e74505968ba24a364a5be70ef86bbe20620d17db#diff-b2dab7e6fe39d3a1bf642d561d045633L1.

**Comment by SwartzCr** [comment] 2017-12-19 23:29
This looks to be essentially a duplicate of #5236
The parent issue for all of these UTF-8 problems is #4516
I think we'd be happy to take a PR of the changes you made, but should also prioritize making progress on total UTF-8 compliance

**Comment by g6123** [comment] 2017-12-20 11:48
Okay, I went through the relavant issues you linked. The whole UTF-8 compatibility issues seem more complicated than I thought, so I'd like to make a new PR just for this little change first, and then look into the other codebase when I'm afford to.

**Comment by g6123** [comment] 2017-12-20 11:55
I opened the PR #5341.

**Comment by diversemix** [comment] 2018-04-08 18:59
@ohemorange ... any progress on this? I found the issue is to do with when it reads "/etc/nginx/mime.types" ... as it does this without the correct encoding.  (line 205 of parser.py) ... the only solution I can think of is that if it throws opening as the default encoding then to retry using utf8. Dunno what your thoughts are?

**Comment by ohemorange** [comment] 2018-04-10 14:58
@diversemix working on a larger overhaul to fix these problems in the codebase. keep an eye out!

**Comment by xueyongg** [comment] 2018-06-27 04:14
What is the progress to this issue, if i may ask?

**Comment by ohemorange** [comment] 2018-06-27 21:32
Follow along with our progress here: https://github.com/certbot/certbot/projects/2

**Comment by tilda** [comment] 2018-06-29 20:10
I'm currently having this same issue, and it's reproducible in the Python interpreter: ![](https://outlaw-techno.psychobitch.club/i/5mn5.png)

**Comment by da3020** [comment] 2018-09-18 12:30
Hi! The reason is that if you have some non ascii letters in nginx config (even in comments!!!) it will not work.

**Comment by Finesse** [comment] 2018-09-18 22:50
I had the same problem. I've found the following workaround (on Ubuntu):

1. Run in a console:
    ```bash
    sudo locale-gen "en_US.UTF-8"
    sudo dpkg-reconfigure locales
    ```
2. Add line `LC_ALL="en_US.UTF-8"` to the file `/etc/default/locale`.
3. Reconnect SSH.

After that, running `cerbot --nginx` doesn’t fail.

**Comment by ohemorange** [comment] 2020-02-05 22:50
Keeping this open.

**Closed** 2020-03-14 00:07 UTC
Labels: area: error handling, area: nginx, has pr
