### ISSUE TITLE
wget needs valid certificate store to download certbot-auto

### ISSUE THREAD

**Issue by CBiX** [certbot/certbot#7140] opened 2019-06-10 16:56 UTC
On my freshly installed instance of Debian 8, wget 1.16 can't verify LE certificates. It might be a good idea to update the [guide](https://certbot.eff.org/lets-encrypt/debianjessie-nginx) to include curl or a more recent version of wget.

## My operating system is (include version):
Debian 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
As mentioned in [this guide](https://certbot.eff.org/lets-encrypt/debianjessie-nginx):

    root@u:~# wget https://dl.eff.org/certbot-auto
    converted 'https://dl.eff.org/certbot-auto' (ANSI_X3.4-1968) -> 'https://dl.eff.org/certbot-auto' (UTF-8)
    --2019-06-10 18:50:50--  https://dl.eff.org/certbot-auto
    Resolving dl.eff.org (dl.eff.org)... 2a04:4e42:9::201, 151.101.120.201
    Connecting to dl.eff.org (dl.eff.org)|2a04:4e42:9::201|:443... connected.
    ERROR: The certificate of 'dl.eff.org' is not trusted.
    ERROR: The certificate of 'dl.eff.org' hasn't got a known issuer.

## Certbot's behavior differed from what I expected because:
The guide is for Debian 8 and it doesn't work with wget 1.16

**Comment by mphilipps** [comment] 2019-06-11 08:19
Works for me, do you have ca-certificates installed?

**Comment by CBiX** [comment] 2019-06-11 08:46
That might have been the issue, because after pushing certbot-auto using scp and then running it (hence having its dependencies installed), the wget command worked, so ca-certificates could have been the missing dependency. Just thought you should mention it in the guide :)

**Comment by sydneyli** [comment] 2019-06-13 17:12
Thanks @CBiX ! I changed the title to be a bit more specific and will take a quick look at this later today.

**Comment by sydneyli** [comment] 2019-06-13 20:52
Hmm, I wasn't able to reproduce this issue-- a vanilla install of Debian 8 should have either DST or LE's cert in the root store... I'm going to close this issue for now.

If you're having similar problems, please first ask about it in the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help)! You'll get help faster there, there's a larger community of people familiar with both Let's Encrypt and Certbot.

**Closed by sydneyli** 2019-06-13 20:52 UTC
Labels: area: certbot-auto, area: documentation

**Comment by CBiX** [comment] 2019-06-14 06:56
Ok, thanks for taking the time and testing it. Might have been my VPS provider's fault then... Anyway, a workaround for everyone encountering this issue would be to use wget --no-check-certificate and then check the file's hash manually.

**Comment by sydneyli** [comment] 2019-06-14 17:57
We also publish a PGP signature at https://dl.eff.org/certbot-auto.asc that people can verify. Instructions to do that: https://certbot.eff.org/docs/install.html#certbot-auto
