### ISSUE TITLE
Setting a "flag" in `cli.ini` to "False" results in an error

### ISSUE THREAD

**Issue by osirisinferi** [certbot/certbot#4490] opened 2017-04-11 09:43 UTC
## My operating system is (include version):
Gentoo profile 13.0

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`emerge app-crypt/certbot-9999` (= latest git master commit)

## I ran this command and it produced this output:
First, I ran `certbot` with `must-staple = True` in `cli.ini (by setting `--must-staple` on the CLI).

After that, I wanted to remove the Must Staple feature, so I explicitely set the value to `False`. This is the result:

```
server ~ # certbot -vv renew --force-renewal --staging --cert-name example.com
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
cert.
certbot: error: must-staple is a flag but is being set to 'False'
```

## Certbot's behavior differed from what I expected because:
I expected `certbot` to run, but now without the `must-staple` option set to true.

IMO it is strange that setting the variable to `True` is possible, but `False` generates an error.

## Here is a Certbot log showing the issue (if available):
There's no log generated. The above is all `certbot` is outputting, even with `-vv`.

**Comment by zjs** [comment] 2017-04-11 17:49
> IMO it is strange that setting the variable to `True` is possible, but `False` generates an error.

This is, for better or worse, standard Python behavior. `must-staple` is a flag. Flags are command line arguments whose mere presence modifies the operation of a command; they aren't intended to take a value. For whatever reason (I can't find one documented), a value of `true` will be ignored. Other values (including `false`) are treated as errors.

**Comment by SwartzCr** [comment] 2017-04-11 20:49
So it seems that the best way to get your intended behavior is to remove that line from your cli.ini file.
This would be a good thing to add to #4152  wrt what we should document about our CLI files

**Comment by SwartzCr** [comment] 2017-04-12 21:20
This also happens to be a duplicate of #4407 which @bmw mentions is a bug in argparse which he's filed an issue for at https://github.com/bw2/ConfigArgParse/issues/87

**Comment by bmw** [comment] 2017-04-13 18:56
The thing that's a little different here is the value `False` is causing Certbot to error out here rather than just add the flag like it was set to `True`.

@osirisinferi, I can't repro this and I have no idea where that error message comes from. Any ideas? For example, can you list the version of Python and `configargparse` that you're using?

**Comment by zjs** [comment] 2017-04-14 18:01
The error comes from `configargparse.convert_setting_to_command_line_arg` as of [0.9.3](https://github.com/bw2/ConfigArgParse/blob/0.9.3/configargparse.py#L335):

```
        if value.lower() == "true":
            # ...
        elif value.startswith("[") and value.endswith("]"):
            # ...
        else:
            if type(action) in ACTION_TYPES_THAT_DONT_NEED_A_VALUE:
                self.error("%s is a flag but is being set to '%s'" % (key, value))
```

and [0.10.0](https://github.com/bw2/ConfigArgParse/blob/0.10.0/configargparse.py#L478).

**Comment by zjs** [comment] 2017-04-14 18:09
Looks like the behavior was changed in this commit: https://github.com/bw2/ConfigArgParse/commit/42d5c7a6a123d9e3792d1b01df9e058a216c57c1

It really seems like this block:
```
            if value.lower() in ("true", "false", "yes", "no"):
                args.append( command_line_key )
            else:
                self.error("Unexpected value for %s: '%s'. Expecting 'true', "
                           "'false', 'yes', or 'no'" % (key, value))
```

Should be more like:
```
            if value.lower() in ("true", "yes"):
                args.append( command_line_key )
            elif value.lower() in ("false", "no"):
                pass
            else:
                self.error("Unexpected value for %s: '%s'. Expecting 'true', "
                           "'false', 'yes', or 'no'" % (key, value))
```

**Comment by SwartzCr** [comment] 2017-04-14 19:09
Nice detective work @zjs! 
Two questions (maybe @bmw can answer)
Considering we're saving things to the cli.ini file with capital pythonic booleans, why are we .lower()ing?
If the value that was set is False, why is it hitting this error block? It seems to me that it should pass the first case and append it to the args.
Either way, wanna make a PR?

**Comment by osirisinferi** [comment] 2017-04-14 19:13
Well, @zjs is exactly right: I was sporting configargparse-0.10.0 and upgrading to 0.11.0 resolved this issue.

**Comment by SwartzCr** [comment] 2017-08-03 23:10
Closing this in favor of #4407 which is also tracking this pinned dependency

**Closed by SwartzCr** 2017-08-03 23:10 UTC
Labels: area: documentation, area: ui / ux
