### ISSUE TITLE
Trying to create certs

### ISSUE THREAD

**Issue by Jexxio** [certbot/certbot#3535] opened 2016-09-25 05:37 UTC
i'm trying to create a cert, with `./letsencrypt-auto certonly --standalone` and get the following output:

```
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

I stopped nginx already. what could be causing this? 
i'm using ubuntu server 16.04.1

PS: I've created several certs a few weeks ago using the same method.

**Comment by bmw** [comment] 2016-09-26 17:05
This is a duplicate of #2883. There are a number of posts there from people who were able to fix the problem. Additionally, there is a `letsencrypt` package on Ubuntu 16.04 that we are currently [recommending over letsencrypt-auto](https://certbot.eff.org/#ubuntuxenial-other).

**Closed by bmw** 2016-09-26 17:05 UTC
