### ISSUE TITLE
got  does not support any combination of challenges that satify CA

### ISSUE THREAD

**Issue by lugt** [certbot/certbot#5426] opened 2018-01-13 16:07 UTC
## My operating system is (include version):
CentOS 7.3 

Version:    : core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
installed certbot-auto last year,
just got an update to 0.20,
sha1sum of certbot-auto file is 73a0b6b473faf4cd71b6844d8fc597f6b13b347c
size of certbot-auto file is 57381

## I ran this command and it produced this output:
./certbot-auto certonly --preferred-challenges=tls-sni -d git.niimei.com -d score.niimei.com

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
```

## Certbot's behavior differed from what I expected because:

One thing you might want to know before reading the following was that I am running this server with port 80 inaccessible to the internet,  and only port 443 and those greater than 8000 reachable.

I was trying to obtain a cert by implementing the tls-sni challenge,

Usually, the above line of command would open a menu to choose my authentication method
and after entering the number 2 and enter pressed, 
it would have automatically created my certificate.

 only it didn't happen this time,
instead, reported the following:

Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-01-13 15:57:49,742:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 729
2018-01-13 15:57:49,743:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 729
Boulder-Requester: 23156514
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/aCXZmEg21AyqcR3j7nRQX7kA-e_hFBbSfVqqMraMc7I
Replay-Nonce: CJgsPCV7M1psv-O38X0keELrU1T9UXW71yDqR_jnLM4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 13 Jan 2018 15:57:49 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 13 Jan 2018 15:57:49 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "git.niimei.com"
  },
  "status": "pending",
  "expires": "2018-01-20T15:57:49.578842175Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/aCXZmEg21AyqcR3j7nRQX7kA-e_hFBbSfVqqMraMc7I/3079056987",
      "token": "JY_5aW73NYFXTQy76iVLD_jU4hIax41BkfwfWvdb3ik"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/aCXZmEg21AyqcR3j7nRQX7kA-e_hFBbSfVqqMraMc7I/3079056988",
      "token": "nJmOWCCJjas7nVmMDEqtqeBlYQ1oqdktTmqDmOdpPpg"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      0
    ]
  ]
}
2018-01-13 15:57:49,744:DEBUG:acme.client:Storing nonce: CJgsPCV7M1psv-O38X0keELrU1T9UXW71yDqR_jnLM4
2018-01-13 15:57:49,744:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "score.niimei.com"
  },
  "resource": "new-authz"
}
2018-01-13 15:57:49,747:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "protected": "eyJub25jZSI6I###",
  "payload": "ewogICJpZGVudGl###",
  "signature": "DaHexx6TaPrIrBSU3zGFA###"
}
2018-01-13 15:57:50,069:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 1221
2018-01-13 15:57:50,069:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 1221
Boulder-Requester: 23156514
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/rdKKj7K16ad7Zfxot-v2sUQg3ZzNLbjwyNdosKkYrp8
Replay-Nonce: 3fd0GMQFZGK0fJnZ_7rTu7rTkDp2ogvyjgwj6n__G3s
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 13 Jan 2018 15:57:50 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 13 Jan 2018 15:57:50 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "score.niimei.com"
  },
  "status": "valid",
  "expires": "2018-02-12T15:48:35Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/rdKKj7K16ad7Zfxot-v2sUQg3ZzNLbjwyNdosKkYrp8/3078993394",
      "token": "TGGvvX_5ZzasakBuYMUCFERYJ5UFBuFbhNJW6XqLuqA"
    },
```
```
    {
    "type": "http-01",
    "status": "valid",
```
```
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/rdKKj7K16ad7Zfxot-v2sUQg3ZzNLbjwyNdosKkYrp8/3078993395",
      "token": "sK512j50DWKohEmgtZTnKVhkJM1r0t###",
      "keyAuthorization": "sK512j50DWKohEmgtZTnKVhkJM1r0tp6nQZVj67KpDs###g552A",
      "validationRecord": [
        {
          "url": "http://score.niimei.com/.well-known/acme-challenge/sK512j50DWKohEmgtZTnKVhkJM1r0tp6nQZVj67KpDs",
          "hostname": "score.niimei.com",
          "port": "80",
          "addressesResolved": [
            "120.78.134.129"
          ],
          "addressUsed": "120.78.134.129",
          "addressesTried": []
        }
      ]
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ]
  ]
}
2018-01-13 15:57:50,070:DEBUG:acme.client:Storing nonce: 3fd0GMQFZGK0fJnZ_7rTu7rTkDp2ogvyjgwj6n__G3s
2018-01-13 15:57:50,070:INFO:certbot.auth_handler:Performing the following challenges:
2018-01-13 15:57:50,071:CRITICAL:certbot.auth_handler:Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
2018-01-13 15:57:50,071:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 786, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 68, in get_authorizations
    self._choose_challenges(domains)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 103, in _choose_challenges
    self.authzr[dom].body.combinations)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 374, in gen_challenge_path
    return _find_smart_path(challbs, preferences, combinations)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 411, in _find_smart_path
    _report_no_chall_path()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 442, in _report_no_chall_path
    raise errors.AuthorizationError(msg)
AuthorizationError: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

```

**Comment by lugt** [comment] 2018-01-13 16:10
My propensity was to only use the 443 port for the challenge. I'm wondering if the log file indicated that the server had already implemented a check using the port 80?  



by viewing the following::

```
{
"type": "http-01",
"status": "valid",
"uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/rdKKj7K16ad7Zfxot-v2sUQg3ZzNLbjwyNdosKkYrp8/3078993395",
"token": "sK512j50DWKohEmgtZTnKVhkJM1r0t###",
"keyAuthorization": "sK512j50DWKohEmgtZTnKVhkJM1r0tp6nQZVj67KpDs###g552A",
"validationRecord": [
{
"url": "http://score.niimei.com/.well-known/acme-challenge/sK512j50DWKohEmgtZTnKVhkJM1r0tp6nQZVj67KpDs",
"hostname": "score.niimei.com",
"port": "80",
"addressesResolved": [
"120.78.134.129"
],
"addressUsed": "120.78.134.129",
"addressesTried": []
```

**Comment by schoen** [comment] 2018-01-13 17:21
Please see

https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983

**Comment by bmw** [comment] 2018-01-13 17:35
Closing as a duplicate of #5405.

**Closed by bmw** 2018-01-13 17:35 UTC

**Comment by lugt** [comment] 2018-01-14 13:37
thx.
