### ISSUE TITLE
With --csr, handle CSRs that have a CN but no SANs

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#2970] opened 2016-05-11 23:51 UTC
certbot/cli.py:
```
        if not domains:
            # TODO: add CN to domains instead:
            raise errors.Error(
                "Unfortunately, your CSR %s needs to have a SubjectAltName for every domain"
                % parsed_args.csr[0])
```

**Comment by bmw** [comment] 2016-05-11 23:53
Dupe of #1076.

**Closed by bmw** 2016-05-11 23:53 UTC
