### ISSUE TITLE
[WISHLIST]Certificate for courier-imap

### ISSUE THREAD

**Issue by schlabs2** [certbot/certbot#5643] opened 2018-03-01 14:37 UTC
Courier-imap use a combined certificate, and is not generated by certboot.
The combined certificate can be generated with following command:

cat fullchain.pem  privkey.pem >combined.pem

I think that is not hard to add this funcionality

**Comment by strugee** [comment] 2018-03-05 16:33
Duplicate of #5087

**Comment by schoen** [comment] 2018-03-05 21:05
I've noted the benefit of this for courier-imap in #5087 and I'll close this one as a duplicate.

**Closed by schoen** 2018-03-05 21:05 UTC
Labels: duplicate, feature request

**Comment by stokito** [comment] 2023-08-22 06:23
https://github.com/svarshavchik/courier/issues/10
