### ISSUE TITLE
DialogError should come with --text instructions

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3324] opened 2016-07-24 00:08 UTC
During my workshop today, someone got a DialogError. It wasn't immediately clear what was wrong, but the message was pretty cryptic. We should give instructions to run with `--text` whenever a DialogError is thrown.

Alternately, maybe we should remove the dialog dependency entirely?

**Comment by bmw** [comment] 2016-09-19 19:35
Removing dialog fixes errors like #3511, simplifies our code, makes shipping Certbot for Python 3 easier, etc. The only downside is a potential usability loss. I know @pde and @schoen feel that dialog provides a significantly better UI for the user in some scenarios. For example:

Dialog:
![screenshot from 2016-09-19 12-33-59](https://cloud.githubusercontent.com/assets/6504915/18646217/6a8701fa-7e65-11e6-969a-8ec3df2e8992.png)

Text:
```
Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: example.org
2: example.net
3: example.com
4: www.example.org
5: www.example.net
6: www.example.com
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces (Enter 'c' to
cancel):
```
Do you guys feel that benefits like this are worth keeping dialog around?

**Comment by bmw** [comment] 2016-09-23 17:52
Another argument for removing dialog. #2025 has been around for a while and we don't know the cause or how to fix it (it is almost certainly a longstanding bug in `dialog`).

**Comment by jsha** [comment] 2016-09-23 17:56
I think if the name selection interface is the only argument for keeping dialog, it is not a strong enough argument. We can make the `--text` version more convenient, for instance by treating "enter" as "select all."

**Comment by ohemorange** [comment] 2016-10-11 23:40
Hey, I think the time has come to remove dialog. Anyone opposed?

**Comment by bmw** [comment] 2016-10-12 17:20
@ohemorange, as I mentioned above, @schoen and @pde were the main people opposed when this was discussed in person. If you work on this, you may want to:

1. Make sure they're okay with such a change being merged.
2. Chat with me about the best way to do this. I think we can dramatically simplify our code by removing `dialog`. All of this work could be done in different PRs, but I think removing `dialog` could remove ~1000 LOC from the project.

**Comment by jsha** [comment] 2016-10-12 17:25
I believe when we talked to @pde in person about this a few weeks ago he was convinced that it made sense as a post-0.9.0 change. But probably worthwhile to get a final thumbs-up. :-)

**Comment by pde** [comment] 2016-10-13 18:40
Yes we can do this for 0.10.0 if we make "all" the default answer to the domain selection question.

**Comment by pde** [comment] 2016-10-13 18:41
And maybe also figure out a plan for telling the people who like dialog, how to get it back with `--dialog`.

**Comment by bmw** [comment] 2016-10-13 18:46
@pde, this isn't about changing the default, it's about removing `dialog` entirely.

**Comment by pde** [comment] 2016-10-13 18:52
@bmw because it's yet another optional dependency?

**Comment by pde** [comment] 2016-10-13 18:53
Related: #3629.

**Comment by ohemorange** [comment] 2016-10-13 18:55
Because it's an optional dependency, and adds complexity.

**Comment by ohemorange** [comment] 2016-10-13 18:56
And is hard to use and makes figuring out what happened hard.

**Comment by ohemorange** [comment] 2016-11-02 18:37
Dialog is no longer a dependency.

**Closed by ohemorange** 2016-11-02 18:37 UTC
Labels: code health, error handling, ui / ux
