### ISSUE TITLE
--cert-name does only work for renew

### ISSUE THREAD

**Issue by koljakutschera** [certbot/certbot#4275] opened 2017-02-28 23:02 UTC
Ubuntu 16.04
I installed Certbot via cloning the master repo

It seems that --cert-name does only work for renew. Not for creating new certs. Bug or feature?

The output when i try to create a non existing cert with: /opt/certbot/certbot-auto certonly --cert-name myname ... is something like the file in /etc/letsencrypt/myname... does not exist and then it stops - but why not create a new one if it not exists?

**Comment by SwartzCr** [comment] 2017-03-01 03:04
the --cert-name flag is meant to handle what are called 'lineages' which are what are used to track and renew certificate files once you've gotten a cert by running certbot initially.
You shouldn't ever need to specify these names - and by default they'll use the name of the domain you're fetching a cert for.
You should omit this flag when fetching a cert for the first time. I'm going to close this, but feel free to re-open it if you think I misunderstood.

**Closed by SwartzCr** 2017-03-01 03:04 UTC
Labels: area: cert management, area: documentation, area: ui / ux

**Comment by koljakutschera** [comment] 2017-03-02 15:24
For automation of letsencrypt it would be good to make it possible to set the name of the cert independent from domain. Maybe theres a multi-domain app running in future or the domain just changed. The reason why i would like to have this feature is - if i assign the cert to nginx-configs for multiple apps in multi-user environment automaticaly. The seems not to be futureproof so cant be used as something like a unique-identifier. If the name of the cert cant be changed i dont need to write a new nignx-conf just because of a changing cert.

**Comment by bmw** [comment] 2017-03-02 18:18
Sorry for the confusion @koljakutschera. Creating the cert with requested name is the intended behavior of `--cert-name`, but there was a bug in this feature causing the error you're seeing. This issue is a duplicate of #4233 which has been resolved in `master` and we're planning on doing a release today including a fix for the problem.

Sorry for the trouble!

**Comment by pkruithof** [comment] 2017-04-07 10:55
This fix was included in 0.12, but the Ubuntu ppa currently has version `0.11.1`. When can we expect the latest version in this repository?

**Comment by SwartzCr** [comment] 2017-04-10 21:21
oh wow, I was really wrong there, wasn't I
Sorry @koljakutschera for getting that mixed up, thanks @bmw for correcting me
@pkruithof I think maybe @hlieberman has an idea of when the Ubuntu PPA will get updated
