### ISSUE TITLE
Check OCSP as part of determining if the certificate is due for renewal

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#1028] opened 2015-10-19 23:08 UTC
There is [logic in `certbot/storage.py` to say that a certificate needs to renewed if it has been revoked](https://github.com/certbot/certbot/blob/d75908c645e0d13827b60c4c94491e0c41859ad4/certbot/storage.py#L936), but the [`storage.py` function that determines if a certificate revoked always returns `False`](https://github.com/certbot/certbot/blob/d75908c645e0d13827b60c4c94491e0c41859ad4/certbot/storage.py#L902). We have code in `certbot/ocsp.py` to obtain the OCSP status of the certificate and we should make use of it.

I think we should be careful here to only say that a certificate needs to be renewed if we can verify that the certificate is revoked. If we fail to obtain/validate the OCSP response for example, we should not say the certificate needs to be renewed. We probably also do not want to crash Certbot in this case.

**Comment by pde** [comment] 2016-01-28 19:59
Suggestion: at revocation time, ask a question about deleting the renewal conf.

**Comment by bmw** [comment] 2017-03-09 20:07
We now have the ability to check OCSP in `certbot.ocsp`. This may be as simple as calling the functions there from `storage.py`, but we should make sure we're happy with the approach taken in `ocsp.py` and that it works well here.

**Comment by SwartzCr** [comment] 2017-09-08 23:26
related to #728

**Comment by ohemorange** [comment] 2019-06-10 21:20
You know, we don't actually ever get people complaining this. I think we can close this.

**Comment by bmw** [comment] 2019-06-11 18:47
I think point 2 of my original post is irrelevant and we won't have time to get to this for a while regardless, but I still personally think it'd be a good idea to check the OCSP status when determining whether certificates need to be renewed. Without it, I think the certificate could be revoked due to a problem CA side and Certbot won't reissue the certificate. Because of this, I'd personally like to reopen this issue and edit my original post or create a new issue to track this work.

Do you disagree @ohemorange?

**Comment by ohemorange** [comment] 2019-06-12 00:10
I think it's a good idea in theory, but is not something that comes up in practice, so I don't see much need to prioritize it. If something changed and we did want to prioritize it, the issue is still here.

**Comment by bmw** [comment] 2019-06-12 00:54
I worry that we could find ourselves in the future scrambling to implement this in response to mass revocation CA side and wishing we would have done it sooner. I personally think it's worth doing this in the next year or so especially since we already have the ability to make OCSP requests.

**Comment by bmw** [comment] 2019-06-12 18:45
After talking about this out of band, we decided to reopen this. I updated my original comment to better describe what needs to be done here.

**Comment by tdelmas** [comment] 2020-03-03 13:30
> I worry that we could find ourselves in the future scrambling to implement this in response to mass revocation CA side and wishing we would have done it sooner

The time has come. https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864/15

**Comment by Chaz6** [comment] 2020-03-03 14:30
Please consider adding this soon!

**Comment by tdelmas** [comment] 2020-03-03 14:43
@bmw Any opinion about an ACME entry point to check if the certificate needs to be renewed? It could solve the problem of the OCSP cache and allow the renewals **before** the effective revocation.

**Comment by pgporada** [comment] 2020-03-03 15:29
There is the possibility that sidestepping the cache and hitting our origin directly will cause massive service degradation. The OCSP cache offload is ~90% - 95% of the traffic (depending on month) at our CDN which equates to hundreds of terabytes that don't hit our loadbalancers. There was an incident back in May of 2017 where the OCSP cache was purged and we had quite the painful incident.

**Comment by tdelmas** [comment] 2020-03-03 17:36
(sorry for the off-topic) Also, fetching OCSP for stapling may help: https://twitter.com/caddyserver/status/1234874273724084226 that way, when an OCSP response fetched says "revoked" there is still time to renew the cerficate until the previous OCSP response is expired, so no downtime!

**Comment by bmw** [comment] 2020-03-03 18:27
> > I worry that we could find ourselves in the future scrambling to implement this in response to mass revocation CA side and wishing we would have done it sooner
>
> The time has come. https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864/15

Yeah. I spent this morning doing more scrambling than I wish I would have had to, but I have a PR to add this feature at https://github.com/certbot/certbot/pull/7829.

> @bmw Any opinion about an ACME entry point to check if the certificate needs to be renewed? It could solve the problem of the OCSP cache and allow the renewals before the effective revocation.

Because of the reasons mentioned by Phil and because I believe it would require hardcoding some URLs that are not generalizable and could change in the future, I personally don't think we should bypass the cache in our code.

We could maybe provide code snippets on https://community.letsencrypt.org to help people here if people have ideas beyond what Let's Encrypt wrote at https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864, but since changing Certbot code is often difficult because it gets entombed in various Linux distros, I personally don't think we should do anything dramatic or specific for this issue in Certbot itself.

> (sorry for the off-topic) Also, fetching OCSP for stapling may help: https://twitter.com/caddyserver/status/1234874273724084226 that way, when an OCSP response fetched says "revoked" there is still time to renew the cerficate until the previous OCSP response is expired, so no downtime!

Good idea! I think between my PR and #7649, we may have this pretty soon in Certbot as well at least for Apache users who enable OCSP prefetching.

**Comment by jsha** [comment] 2020-03-03 18:47
tdelmas> Any opinion about an ACME entry point to check if the certificate needs to be renewed? It could solve the problem of the OCSP cache and allow the renewals before the effective revocation.
phil> There is the possibility that sidestepping the cache and hitting our origin directly will cause massive service degradation. 

I think you two are talking about different things. I believe tdelmas is talking about specifying, and implementing, a new request type that can be used to tell clients *in advance of revocation* that they need to renew. I think this is a great idea.

I think Phil is talking about making requests directly to our OCSP origins, which I think we are all in agreement is not a good idea.

**Comment by tdelmas** [comment] 2020-03-03 18:51
>  I believe tdelmas is talking about specifying, and implementing, a new request type that can be used to tell clients in advance of revocation that they need to renew. 
@jsha Yes, in advance (or not): I think the cost is inferior to an OCSP response. I'm too against the bypass of the OCSP cache. #7649 will reduce the problem but to fully avoid downtime, clever OCSP stapling or that API is needed in my opinion.

**Closed** 2020-03-03 19:07 UTC
Labels: area: cert management, area: renewal
