### ISSUE TITLE
Impossible to provide 3rd party plugin configurations in cli.ini

### ISSUE THREAD

**Issue by Fluepke** [certbot/certbot#7681] opened 2020-01-14 16:37 UTC
## My operating system is (include version):
Arch Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

## I ran this command and it produced this output:
`certbot certonly --domain example.com`

## Certbot's behavior differed from what I expected because:
`cat /etc/letsencrypt/cli.ini`
```ini
; redacted for privacy reasons
authenticator=certbot-dns-powerdns:dns-powerdns
certbot-dns-powerdns:dns-powerdns-credentials=/etc/certbot-dns-powerdns/pdns-credentials.ini
```

I would expect this to provide the `--certbot-dns-powerdns:dns-powerdns-credentials` flag to `certbot`.

But it does not apparently:
```
certbot: error: ambiguous option: --certbot-dns-powerdns=dns-powerdns-credentials=/etc/certbot-dns-powerdns/pdns-credentials.ini could match --certbot-dns-powerdns:dns-powerdns-propagation-seconds, --certbot-dns-powerdns:dns-powerdns-credentials
```

This issue is related to 
* #6504
* #4351

**Comment by bmw** [comment] 2020-01-14 18:50
Thanks for the detailed issue @Fluepke.

I think this is a duplicate of https://github.com/certbot/certbot/issues/6040 which was closed in favor of https://github.com/certbot/certbot/issues/4351.

For that reason, I'm going to close this issue. We have a couple PRs for that issue though and we're planning on catching up on PRs from open source contributors in the next few weeks so hopefully this problem will be resolved soon.

**Closed by bmw** 2020-01-14 18:50 UTC

**Comment by norbusan** [comment] 2020-01-24 02:32
Hi @bmw 
this is a sad story - the problem is known since more than a year, the pull request was not merged back then, and is not working with current master branch.

That means, that till now, after at least 1.5 years (since at least June 2018), there is still no way to configure third-party plugins via config files.

Why do you close this issue? It is neither resolved, not partly resolved, nor any progress since June 2018.

**Comment by adferrand** [comment] 2020-01-24 09:55
Hello @norbusan, @bmw closed only the issue for issue management purpose only, and not because this goal expressed of the issue would be out of scope. It is just that #4351 is already tracking the problem.

About solving this, is definitely in the scope, and we hope we will have the time to fix it ASAP.

**Comment by norbusan** [comment] 2020-01-24 10:34
THanks @adferrand , tha tis very much appreciated. I have rebased the original PR onto the current master and adjusted it so that it loads, but it didn't work at all, unfortunately.
