### ISSUE TITLE
URLLIB3 virtual env python environment error

### ISSUE THREAD

**Issue by anthonychung14** [certbot/certbot#3300] opened 2016-07-19 15:17 UTC
When trying to run the command ./letsencrypt-auto -v

I get the following call-stack

It looks like there is an issue with the dependencies installed in the virtual env setup

what choices do I have? available?

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
augeas-lenses is already the newest version.
ca-certificates is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.
Creating virtual environment...
Running virtualenv with interpreter /home/tony/anaconda/bin/python2.7
New python executable in /home/tony/.local/share/letsencrypt/bin/python2.7
Also creating executable in /home/tony/.local/share/letsencrypt/bin/python
Installing setuptools, pip...done.
Installing Python packages...
Had a problem while installing Python packages:
Traceback (most recent call last):
  File "/home/tony/.local/share/letsencrypt/bin/pip", line 9, in <module>
    load_entry_point('pip==8.0.3', 'console_scripts', 'pip')()
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/tony/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

**Comment by bmw** [comment] 2016-07-19 19:02
What OS are you on?

If you run:
```
virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
./temp_venv/bin/pip install requests==2.9.1
```
do you get the same error? What if you remove the `==2.9.1` from the end of the 2nd line?

After running those commands there will be a `temp_venv` directory in your current working directory which can be deleted with `rm -rf temp_venv`.

**Comment by bmw** [comment] 2016-07-19 23:57
Looks like this is a duplicate of #2902. Closing this issue in favor of that one.

**Closed by bmw** 2016-07-19 23:57 UTC
Labels: certbot-auto, more-info
