### ISSUE TITLE
Enhancement: logging level (CLI/config file option)?

### ISSUE THREAD

**Issue by sphakka** [certbot/certbot#3481] opened 2016-09-07 09:44 UTC
Maybe I'm missing something, but I can't find a way to change the logging level -- no CLI/configuration file option? My logs are full of DEBUG lines...
As a workaround I can use '--quiet', though a more fine-grained way would be better.

**Comment by bmw** [comment] 2016-09-15 22:09
There is no way to control the logging level of the files in `/var/log/letsencrypt`. These files include all logging output.

As for the logging you see on the terminal, the default level should be WARNING/INFO (depending on your version of Certbot) with `-v`/`--verbose` allowing you to show messages from a lower logging level. Make sure you're not including that flag on the command line or in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file).

If you're not including either flag, can you please post the contents of any configuration files as well as the command line you're using?

**Comment by sphakka** [comment] 2016-09-18 15:27
I usually call

    $ certbot -q renew

and no `verbose` option is set in the related config file.

However @ `certbot.main.setup_logging:642` changing this

    root_logger.setLevel(logging.DEBUG)

into 

    root_logger.setLevel(logging.INFO)

works around the issue (on my Debian instance: certbot-0.8.0-1~bpo8+2). IMHO, that should be configurable via the `cli.ini` file.

**Comment by sphakka** [comment] 2016-09-18 15:31
Anyway, since the code also says:

    INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log

another option could be to send all debugging to a separate file, whose existence should be controlled via config option|file.

**Comment by bmw** [comment] 2016-09-19 19:37
Are you seeing `DEBUG` level logging messages in the terminal or just the logs in `/var/log/letsencrypt`?

**Comment by nomoon** [comment] 2016-09-20 07:07
Came here searching for the issue as well. I'm getting DEBUG messages in my logs (and lots of them). I have only installed the package and run certbot (using webroot) for two certificates. It seems that this happens whenever the renewal cron task runs.

**Comment by sphakka** [comment] 2016-09-20 13:00
@bmw, DEBUG messages only appear in the logs. On the console, calling `certbot`
gives only informational (?) messages with no prefix; with '-q' nothing is printed at all.

**Comment by bmw** [comment] 2016-09-21 18:37
Ah this is the current expected behavior. Certbot logs everything to the files in `/var/log/letsencrypt` (or whatever directory you set `--logs-dir` to) with no way to reduce that output. The only current mechanisms for making output more/less verbose are for output printed to stdout/stderr.

We could look into setting up a method to control the amount of data written to log files in the future.

**Comment by nyetwurk** [comment] 2018-04-07 00:49
This is a fundamental feature of almost every single other program that keeps logs.

**Comment by gmkey** [comment] 2018-06-26 16:22
May I add my 2 cents. I don't know of any program that just creates a new logfile every time it runs. That to me seems like eating inodes. For all I care it adds to a single log-file per day, or a single logfile per month but this seems like a waste of resources.

**Comment by OrangeDog** [comment] 2019-06-10 11:09
> I don't know of any program that just creates a new logfile every time it runs.

This also completely ruins logrotate e.g. in the official Ubuntu repos.
Despite being configured to keep 12 files and compress them, you still get thousands of uncompressed log files that slip through the cracks.

**Comment by OrangeDog** [comment] 2019-06-10 11:21
@gmkey you can stop that with `--mx-log-backups 0`.

**Comment by ovk** [comment] 2019-06-22 15:26
Flooding logs with DEBUG messages is definitely an issue. In my logs, almost 80% of the content is unnecessary DEBUG information. There absolutely should be a way to set log level.

**Comment by mister2d** [comment] 2020-05-27 07:03
Wow, this is still ongoing with 1.4.0 in 2020.

How is it possible for certbot to emit DEBUG and INFO without the user having control over the level?

Why is the default behavior to create a new log file every time the program runs.

Use case: If you are creating a custom certbot container image, you don't want log files written to disk during period runs. You want stdout/stderr.

**Comment by n-rodriguez** [comment] 2020-08-20 00:14
Hi there! Any news?

**Comment by Nebucatnetzer** [comment] 2020-08-27 14:36
This would be really great because when one uses a syslog server and reads the messages directly from the file it creates a new message for each line.
The normal logs are working just fine but the DEBUG messages are creating tons of messages sometimes just with a single character in them.

**Comment by mle-ii** [comment] 2021-02-04 00:33
Here commenting as we discovered debug logs in our graylog logs showing information that should definitely not be showing up there.  We need to control what level these logs show up as, we don't want debug logs in our graylog but it is useful to see the other logs to know what our systems are doing.

**Comment by bcdady** [comment] 2021-04-15 00:14
Perhaps @alexzorin or @ohemorange could elaborate on if / how logging control improvements are part of the 'terminal revamp project' I see listed under [projects](https://github.com/certbot/certbot/projects) - UX

**Comment by ohemorange** [comment] 2021-04-27 22:38
We [recently](https://github.com/certbot/certbot/pull/8765) did an audit of our logging calls. Our overall goal with the *log file* is to help users who provide one to debug their code. So, debug messages aren't "programmer writing code" debug, but rather "information that might be useful when trying to figure out what went wrong." As for the default logging level, that's was bumped to warning in the same PR, so info-level things that a user shouldn't need to know about won't be printed to the terminal by default. Given that we recently did this overhaul, I'm closing this issue. As for creating a new log file, again, it's meant to help users who are having issues debug by allowing them to just submit a single file. More advanced users who have filesystem constraints should use the `--max-log-backups` flag as described above. Thank you for your input everyone!

**Closed by ohemorange** 2021-04-27 22:38 UTC
Labels: area: ui / ux, feature request

**Comment by gomanuke** [comment] 2021-06-05 07:33
> @gmkey you can stop that with `--max-log-backups 0` (or equivalent in cli.ini).

# Because we are using logrotate for greater flexibility, **disable the
# internal certbot logrotation.**
max-log-backups = 0

But ehat's about tones of DEBUG lines in /var/log/letsencrypt?
