### ISSUE TITLE
CertBot crush if there is more than one certificate for the update

### ISSUE THREAD

**Issue by pastushenkofx** [certbot/certbot#5831] opened 2018-04-05 07:46 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04.4 LTS
GNU/Linux 4.4.0-116-generic x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot renew

Renew first cert, and crush whitout restart apache

## Certbot's behavior differed from what I expected because:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 221, in perform
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 221, in <listcomp>
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 228, in _try_perform_single
    _handle_perform_error(error)
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 226, in _try_perform_single
    return self._perform_single(achall)
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 234, in _perform_single
    servers, response = self._perform_tls_sni_01(achall)
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 251, in _perform_tls_sni_01
    servers = self.servers.run(port, challenges.TLSSNI01, listenaddr=addr)
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 67, in run
    raise errors.StandaloneBindError(error, port)
certbot.errors.StandaloneBindError: Problem binding to port 443: Could not bind to IPv4 or IPv6.

2018-04-04 10:10:31,921:DEBUG:certbot.error_handler:Calling registered functions
2018-04-04 10:10:31,922:INFO:certbot.auth_handler:Cleaning up challenges
2018-04-04 10:10:31,922:WARNING:certbot.renewal:Attempting to renew cert (template.rcscommunication.com) from /etc/letsencrypt/renewal/template.rcscommunication.com.conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.
2018-04-04 10:10:31,922:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/standalone.py", line 62, in run
    servers = acme_standalone.TLSSNI01DualNetworkedServers(address, self.certs)
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 133, in __init__
    BaseDualNetworkedServers.__init__(self, TLSSNI01Server, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/standalone.py", line 94, in __init__
    raise socket.error("Could not bind to IPv4 or IPv6.")
OSError: Could not bind to IPv4 or IPv6.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2018-04-04 14:38:59,647:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/issuer-cert.
2018-04-04 14:38:59,851:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /acme/issuer-cert HTTP/1.1" 200 1174
2018-04-04 14:38:59,852:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/pkix-cert
Content-Length: 1174
Replay-Nonce: SFeYr59Fk7rRV3uB8ibsUITvPN7TQh4QeJuqm7Nfk5g
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Wed, 04 Apr 2018 14:38:59 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 04 Apr 2018 14:38:59 GMT
Connection: keep-alive

2018-04-04 14:38:59,853:DEBUG:chardet.charsetprober:SHIFT_JIS Japanese prober hit error at byte 2
2018-04-04 14:38:59,853:DEBUG:chardet.charsetprober:EUC-JP Japanese prober hit error at byte 1
2018-04-04 14:38:59,853:DEBUG:chardet.charsetprober:GB2312 Chinese prober hit error at byte 2
2018-04-04 14:38:59,853:DEBUG:chardet.charsetprober:EUC-KR Korean prober hit error at byte 1
2018-04-04 14:38:59,853:DEBUG:chardet.charsetprober:CP949 Korean prober hit error at byte 2
2018-04-04 14:38:59,854:DEBUG:chardet.charsetprober:Big5 Chinese prober hit error at byte 1
2018-04-04 14:38:59,854:DEBUG:chardet.charsetprober:EUC-TW Taiwan prober hit error at byte 1
2018-04-04 14:38:59,862:DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.04025180677792795
2018-04-04 14:38:59,862:DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.0
2018-04-04 14:38:59,862:DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.02918497978583681
2018-04-04 14:38:59,862:DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.04514191986865063
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.05157078240745495
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.027529907939475486
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.12189915743514936
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.1323781201284265
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:ISO-8859-5 Bulgairan confidence = 0.037557321486345316
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.043096077988372
2018-04-04 14:38:59,863:DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.02568934298576919
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.23832112651927498
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.050703173091617086
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.04056253847329366
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:windows-1251 Russian confidence = 0.04025180677792795
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:KOI8-R Russian confidence = 0.0
2018-04-04 14:38:59,864:DEBUG:chardet.charsetprober:ISO-8859-5 Russian confidence = 0.02918497978583681
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:MacCyrillic Russian confidence = 0.04514191986865063
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:IBM866 Russian confidence = 0.05157078240745495
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:IBM855 Russian confidence = 0.027529907939475486
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:ISO-8859-7 Greek confidence = 0.12189915743514936
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:windows-1253 Greek confidence = 0.1323781201284265
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:ISO-8859-5 Bulgairan confidence = 0.037557321486345316
2018-04-04 14:38:59,865:DEBUG:chardet.charsetprober:windows-1251 Bulgarian confidence = 0.043096077988372
2018-04-04 14:38:59,866:DEBUG:chardet.charsetprober:TIS-620 Thai confidence = 0.02568934298576919
2018-04-04 14:38:59,866:DEBUG:chardet.charsetprober:ISO-8859-9 Turkish confidence = 0.23832112651927498
2018-04-04 14:38:59,866:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.0
2018-04-04 14:38:59,866:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.050703173091617086
2018-04-04 14:38:59,866:DEBUG:chardet.charsetprober:windows-1255 Hebrew confidence = 0.04056253847329366
2018-04-04 14:38:59,867:DEBUG:certbot.storage:Writing new private key to /etc/letsencrypt/archive/myDomain/privkey2.pem.
2018-04-04 14:38:59,868:DEBUG:certbot.storage:Writing certificate to /etc/letsencrypt/archive/myDomain/cert2.pem.
2018-04-04 14:38:59,868:DEBUG:certbot.storage:Writing chain to /etc/letsencrypt/archive/myDomain/chain2.pem.
2018-04-04 14:38:59,868:DEBUG:certbot.storage:Writing full chain to /etc/letsencrypt/archive/myDomain/fullchain2.pem.
2018-04-04 14:38:59,896:DEBUG:certbot.storage:Writing new config /etc/letsencrypt/renewal/myDomain.conf.new.
2018-04-04 14:39:00,067:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:00,073:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:00,074:DEBUG:certbot.renewal:no renewal failures
2018-04-04 14:39:00,074:INFO:certbot.hooks:Running post-hook command: apachectl -k start
2018-04-04 14:39:00,132:INFO:certbot.hooks:Output from apachectl:
httpd (pid 32623) already running

2018-04-04 14:39:10,566:DEBUG:certbot.main:certbot version: 0.22.2
2018-04-04 14:39:10,567:DEBUG:certbot.main:Arguments: []
2018-04-04 14:39:10,568:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-04-04 14:39:10,579:DEBUG:certbot.log:Root logging level set at 20
2018-04-04 14:39:10,580:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-04-04 14:39:10,591:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7ff3aca25c18> and installer <certbot.cli._Default object at 0x7ff3aca25c18>
2018-04-04 14:39:10,602:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,607:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,610:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,614:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,618:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,622:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,627:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,630:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,634:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,638:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,643:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,647:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,651:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,654:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,659:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,663:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,666:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:10,667:DEBUG:certbot.renewal:no renewal failures
2018-04-04 14:39:35,335:DEBUG:certbot.main:certbot version: 0.22.2
2018-04-04 14:39:35,336:DEBUG:certbot.main:Arguments: []
2018-04-04 14:39:35,337:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-04-04 14:39:35,348:DEBUG:certbot.log:Root logging level set at 20
2018-04-04 14:39:35,349:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-04-04 14:39:35,360:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f096eb78c18> and installer <certbot.cli._Default object at 0x7f096eb78c18>
2018-04-04 14:39:35,371:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,376:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,380:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,383:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,387:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,391:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,396:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,399:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,403:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,407:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,411:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,415:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,419:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,423:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,427:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,431:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,435:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 14:39:35,436:DEBUG:certbot.renewal:no renewal failures
2018-04-04 22:13:02,306:DEBUG:certbot.main:certbot version: 0.22.2
2018-04-04 22:13:02,307:DEBUG:certbot.main:Arguments: ['-q']
2018-04-04 22:13:02,308:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-04-04 22:13:02,319:DEBUG:certbot.log:Root logging level set at 30
2018-04-04 22:13:02,320:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-04-04 22:13:02,331:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7efe818b1dd8> and installer <certbot.cli._Default object at 0x7efe818b1dd8>
2018-04-04 22:13:02,342:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,346:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,350:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,354:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,358:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,361:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,365:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,369:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,373:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,377:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,381:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,385:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,389:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,392:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,396:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,400:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,403:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-04 22:13:02,404:DEBUG:certbot.renewal:no renewal failures

**Comment by bmw** [comment] 2018-04-05 21:36
This is a duplicate of #2419. See my comment at https://github.com/certbot/certbot/issues/5555#issuecomment-376296665 about how to work around the problem.

**Closed by bmw** 2018-04-05 21:36 UTC
