### ISSUE TITLE
Renewal failed with HTTP to HTTTPS redirection

### ISSUE THREAD

**Issue by stylersnico** [certbot/certbot#3361] opened 2016-08-01 11:56 UTC
Hi everyone,

Renewal fail if I use a HTTP to HTTPS redirection like this:

``` nginx
        if ($http_host = abyssproject.net){
            return 303 https://www.abyssproject.net$request_uri;
        }
        if ($scheme != "https") {
            rewrite ^ https://$http_host$request_uri? permanent;
        }
```

``` bash
root@webhost:/etc/letsencrypt/live-ecdsa/abyssproject.net/letmp# /etc/letsencrypt/letsencrypt-auto certonly -a webroot --email contact@nsweb.solutions --webroot-path /var/www/abyssproject.net/web/ --csr /etc/letsencrypt/live-ecdsa/abyssproject.net/csr-p384.der --renew-by-default --agree-tos
Failed authorization procedure. www.abyssproject.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://www.abyssproject.net/.well-known/acme-challenge/wx6qmXvRpYLuhy6zvuGdA0J9NRCmgrWCxYjRdxD1YCo, abyssproject.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://abyssproject.net/.well-known/acme-challenge/0z-LBu09KKMA1Rmv2loakculeGNnMk057LG7YRaZzGI

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.abyssproject.net
   Type:   connection
   Detail: Could not connect to
   http://www.abyssproject.net/.well-known/acme-challenge/wx6qmXvRpYLuhy6zvuGdA0J9NRCmgrWCxYjRdxD1YCo

   Domain: abyssproject.net
   Type:   connection
   Detail: Could not connect to
   http://abyssproject.net/.well-known/acme-challenge/0z-LBu09KKMA1Rmv2loakculeGNnMk057LG7YRaZzGI

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

I can access http://abyssproject.net/.well-known/acme-challenge/test perfectly from HTTPS (or HTTP) but the client fail every time.

And it works everytime with the `--dry-run` option, no error ...

How can I solve that?

(I use P-384 ECDSA certs)

Thanks

**Comment by pde** [comment] 2016-08-03 00:14
Are you using `--webroot`, or the experimental Nginx plugin?

**Comment by pde** [comment] 2016-08-03 00:15
(I presume the answer is `--webroot`... what do your server logs show during the authentication attempt?  Can you post the Certbot log from `/var/log/letsencrypt/` too?)

**Comment by stylersnico** [comment] 2016-08-03 06:25
Webroot as showed in my previous log.

Here is the full log: 

[letsencrypt.log.txt](https://github.com/certbot/certbot/files/398769/letsencrypt.log.txt)

**Comment by tblake84** [comment] 2016-08-04 13:25
Has this been resolved?  I am having the same exact issue.

**Comment by stylersnico** [comment] 2016-08-06 06:51
The problem is still the same...

**Comment by bmw** [comment] 2016-08-10 17:32
@tblake84, I think your error is different. The biggest thing here is stylersnico succeeds with `--dry-run` but fails without the flag. Python 2.6 or the deprecation warning shouldn't have anything to do with it. The best advice I can give you is the output given by the client when it sees similar errors:
```
   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```
If you're still having the problem after verifying that information, please open a new issue.

@stylersnico, I've actually never seen Certbot succeed with the `--dry-run` flag but fail without it. To isolate that as the problem, can you do the following:

1. Write the command line you want to use to obtain your certificate. This can be the same as the one you used in the log above. Include the `--dry-run` flag and run the client.
2. If step 1 succeeded, try running again without the `--dry-run` flag, being sure not to change any other command line options.
3. If step 2 failed, temporarily move `/etc/letsencrypt` to another location. Run the command line from step 2 again but include `--staging` on the command line. After this is done, you can remove the `/etc/letsencrypt` directory that was created and restore the original directory.

If step 3 succeeded, you have a very interesting problem. I talked to the boulder team (Let's Encrypt's server) and they told me that there is a timeout on the production server that is not present in staging. It's possible that your server isn't responding "fast enough" for production. If you're still having the problem, please let me know and I'll see what I can do to help.

**Comment by jsha** [comment] 2016-08-10 19:15
> timeout on the production server that is not present in staging

I think we may have had a miscommunication here. Fetch timeouts are the same in both production and staging.

One of the main things currently different in staging is the "Automatic recycling of authorization objects" from https://community.letsencrypt.org/t/upcoming-api-changes/17947. It's possible that validation would fail on both prod and staging, but you already have a valid authorization on staging so when you use `--dry-run` (which uses staging), there is no need to re-validate, and it succeeds regardless.

I'm not sure why there would be a timeout on either staging or prod, though, since your server appears to respond fine. Are you able to try again with some random subdomain pointed at the same server? E.g. example.abyssproject.net? That would avoid triggering the "automatic recycling of authorization objects" on staging, so we could verify whether the behavior is the same on prod vs staging.

**Comment by stylersnico** [comment] 2016-08-11 06:21
Ok, just got it.

It seems to be coming from your server / client.

I've just renewed 20+ domains this morning and for some of them I have to launch the command again and again for the renewal to work. Sometimes more than 5 times ...

For example:

```bash
root@webhost:/etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp# /etc/letsencrypt/letsencrypt-auto certonly -a webroot --email contact@nsweb.solutions --webroot-path /var/www/ultimatemag.net/web/ --csr /etc/letsencrypt/live-ecdsa/ultimatemag.net/csr-p384.der --renew-by-default --agree-tos
Failed authorization procedure. www.ultimatemag.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://www.ultimatemag.net/.well-known/acme-challenge/Gs8QJJuSHYPTjbNVGDuIBHQmwCClGgsbRmxkWTvepCo, ultimatemag.net (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://ultimatemag.net/.well-known/acme-challenge/n3jevLcCJnH32SgOgLxlt0G1hjTeWEy2uuDlOZ46zuE

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.ultimatemag.net
   Type:   connection
   Detail: Could not connect to
   http://www.ultimatemag.net/.well-known/acme-challenge/Gs8QJJuSHYPTjbNVGDuIBHQmwCClGgsbRmxkWTvepCo

   Domain: ultimatemag.net
   Type:   connection
   Detail: Could not connect to
   http://ultimatemag.net/.well-known/acme-challenge/n3jevLcCJnH32SgOgLxlt0G1hjTeWEy2uuDlOZ46zuE

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
root@webhost:/etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp# nano /etc/nginx/sites-enabled/100-ultimatemag.net.vhost
root@webhost:/etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp# nano /etc/nginx/sites-enabled/100-ultimatemag.net.vhost
root@webhost:/etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp# /etc/letsencrypt/letsencrypt-auto certonly -a webroot --email contact@nsweb.solutions --webroot-path /var/www/ultimatemag.net/web/ --csr /etc/letsencrypt/live-ecdsa/ultimatemag.net/csr-p384.der --renew-by-default --agree-tos

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp/0001_chain.pem.
   Your cert will expire on 2016-11-09. To obtain a new or tweaked
   version of this certificate in the future, simply run
   letsencrypt-auto again. To non-interactively renew *all* of your
   certificates, run "letsencrypt-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

root@webhost:/etc/letsencrypt/live-ecdsa/ultimatemag.net/letmp#
```

**Comment by Lofesa** [comment] 2016-12-14 19:30
Hi to all
I come here from https://community.letsencrypt.org/t/certbot-renew-fail-with-status-400/24136/3
The user @cpu recomment to post here a log file.
The issue is that I can´t renew certificate from the command line, no scripts.
Can see in the log file that server can´t connect with client with status 400.
Is 1 certificate with 7 alternate names. Some times fail with 2, 3,4.... of the alternates names some times with all
Have redirections from port 80 to port 443 in these sites.

Thx in advance

[letsencrypt.txt](https://github.com/certbot/certbot/files/652662/letsencrypt.txt)

**Comment by Lofesa** [comment] 2016-12-14 21:39
I can confirm, the issue was the redirections from port 80 to the port 443.
I have commented the lines that does the redirection in server config and renewal was succesfull.

**Comment by garygreen** [comment] 2016-12-16 18:33
This really needs more attention. It's a strong recommendation that you redirect port 80 (non ssl connections) to ssl connections, if you do this it essentially breaks the webroot challenge method.

@pde any news on this?

**Comment by ArchangeGabriel** [comment] 2016-12-16 22:28
I didn’t take the time to read all of this, but what I’ve been doing from the beginning for the webroot challenge to work with that https redirection is the following (nginx MWE):
```
http {
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location /.well-known/acme-challenge/ {
            access_log /var/log/nginx/acme_access.log;
            error_log /var/log/nginx/acme_error.log;
            root /var/lib/letsencrypt/acme/;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
```

**Comment by larssn** [comment] 2017-01-12 22:52
@ArchangeGabriel This wont work however, behind a service like CloudFlare.

**Comment by ArchangeGabriel** [comment] 2017-01-12 23:35
@larssn Sure, I wasn’t taking into account case such as CDNs…

**Comment by dvlprs** [comment] 2017-02-09 22:45
Here's a NGINX configuration that worked for me (@ArchangeGabriel's didn't for some reason): 

    server {
        listen 443 ssl;
        # relevant https configuration
        location /.well-known/acme-challenge/ {
            return 301 http://$server_name$request_uri;
        }
    }
    server {
        listen 80;
        # relevant http configuration
        location / {
            return 301 https://$server_name$request_uri;
        }
        location /.well-known/acme-challenge/ {}
    }

Not obvious: the order of the sever directives is important.

**Comment by TimHandy** [comment] 2018-11-26 21:19
For others stumbling across this... I had the same, though it was because certbot added it's own http > https redirect section at the top of my nginx site config file. I commented out my original redirect, restarted nginx and  `sudo certbot renew --dry-run` worked ok.

**Comment by ArchangeGabriel** [comment] 2019-06-04 08:49
Yes, this is still an issue.

**Comment by jsha** [comment] 2019-06-04 23:32
@ArchangeGabriel we made some changes recently to fix validation when there's a non-Certbot-controlled redirect from HTTP to HTTPS (e.g. a CDN). I suspect the details of what's going wrong for you are probably quite different than the original issue that was opened in 2016. To keep the issues list up-to-date, I'm going to close this one out. Would you please file a fresh issue with your Certbot version, command line, and log output from a failed validation? Thanks!

**Closed by jsha** 2019-06-04 23:32 UTC
Labels: area: webroot, more-info

**Comment by ArchangeGabriel** [comment] 2019-06-05 08:44
@jsha Do you mean that [this special case handling](https://github.com/certbot/certbot/issues/3361#issuecomment-267711444) is not necessary anymore?

**Comment by jsha** [comment] 2019-06-05 20:33
I don't think so, no.

**Comment by marcinx** [comment] 2020-03-19 15:54
@jsha I think it might be still failing. 

My certbot gives a 400 "connection refused" in the logs when I redirect with 301. This error code was very confusing at first because I could not find it in my nginx logs, only the 301. There were no subsequent hits to the server after LetsEncrypt saw the 301, so I guess it's simply ignoring the redirect and writing a 400 into its own logs. It works without the HTTP to HTTPS redirect. This is on version: 1.0.0 on CentOS 7.

**Comment by jsha** [comment] 2020-03-19 23:44
Hi @marcinx - there's a good chance that you're experiencing a different issue. Could you please post at http://community.letsencrypt.org/new-topic and fill out the template with details (what command, what version, what output, etc)?

**Comment by MattrCoUk** [comment] 2020-06-25 16:43
I think I had a similar issue on my Apache server. Certbot was receiving the 302 (which is the http to https redirection I assume) and failed to create certificate (Timeout during connect (likely firewall problem)). when I disable the redirection, all went well.

**Comment by jsha** [comment] 2020-06-25 19:23
Thanks for the report @MattrCoUk!

Since this issue is accumulating a variety of reports that probably don't all have the same root cause, I'm going to lock it. I encourage anyone experiencing symptoms like these to post at http://community.letsencrypt.org/new-topic and fill out the template with details (what command, what version, what output, etc). If after some debugging in the forum, you conclude there is a Certbot bug, please post it as a new issue on this repo. Thanks!
