### ISSUE TITLE
Nginx fails if ssl_session_cache already defined

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#921] opened 2015-10-08 00:38 UTC
Steps to reproduce:
1. Put `ssl_session_cache shared:SSL:10m;` in your Nginx configs somewhere.
2. Run letsencrypt with the nginx authenticator.

Expected results: works

Actual results:

`2015-10-08 00:30:17,856:ERROR:letsencrypt_nginx.configurator:Nginx Restart Failed!

nginx: [emerg] the size 1048576 of shared memory zone "SSL" conflicts with already declared size 10485760 in /etc/letsencrypt/options-ssl-nginx.conf:1`

Contents of /etc/letsencrypt/options-ssl-nginx.conf:

```
ssl_session_cache shared:SSL:1m;
ssl_session_timeout 1440m;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;

# Using list of ciphers from "Bulletproof SSL and TLS"
ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA256 DHE-RSA-AES256-SHA256 EDH-RSA-DES-CBC3-SHA";
```

**Comment by jsha** [comment] 2015-10-08 00:42
Correction: It looks like the `ssl_session_cache` directive is placed in both /etc/nginx/conf.d/ssl.conf and  /etc/letsencrypt/options-ssl-nginx.conf by letsencrypt, which causes the conflict. I noticed this because I tried editing the line out of ssl.conf and re-running, but found that ssl.conf was restored to its previous value.

**Comment by jsha** [comment] 2015-10-08 00:45
BTW, after removing the contents of  /etc/letsencrypt/options-ssl-nginx.conf it wasn't recreated. I'm guessing it was created by an earlier run of letsencrypt, then the location of the config file was changed, and no code got added to clean up old ones? We should add code to make sure we clean up old config files we may have generated.

Also we should try and check for ssl_session_cache in all included config files before attempting to add it, or we will get a conflict.

**Comment by jsha** [comment] 2015-10-10 18:35
I wound up deleting /etc/letsencrypt/options-ssl-nginx.conf, and once it was gone, the next letsencrypt run re-created it. So it looks like the client is indeed creating two ssl config files, with conflicting session cache directives.

**Comment by stapelberg** [comment] 2015-11-07 15:23
I’ve had the same problem. https://cipherli.st/ actually recommends `ssl_session_cache`, so I expect this to be a fairly common directive for people who switch to letsencrypt.

**Comment by TheNavigat** [comment] 2016-01-30 01:50
Faced that error here as well.

I think this needs to be pushed a bit up the priority list.

**Comment by Sawtaytoes** [comment] 2016-03-24 07:17
Same here as well. Ubuntu 14.04.

**Comment by silverwind** [comment] 2017-02-14 13:44
Was this fixed? I'm running 0.11.1 and seeing

```
nginx restart failed:

2017/02/14 14:38:28 [emerg] 27639#27639: the size 10485760 of shared memory zone "SSL" conflicts with already declared size 1048576 in /etc/nginx/nginx.conf:68
```

`/etc/nginx/nginx.conf` contains `ssl_session_cache shared:SSL:10m;`.

**Comment by HLFH** [comment] 2017-02-15 08:21
@silverwind  You have ssl_session_cache shared:SSL:10m twice. And maybe in /etc/letsencrypt/options-ssl-apache.conf. So fix it and correct the value.

**Comment by silverwind** [comment] 2017-02-15 09:57
It's once with 10M in my config and once with 1M in `/etc/letsencrypt/options-ssl-nginx.conf` (which I never touched and which is the same as [the one in this repo](https://github.com/certbot/certbot/blob/b1826d657ffc7c278041cc0c8e14dc2ba23f95e3/certbot-nginx/certbot_nginx/options-ssl-nginx.conf)).

If I change it to 1M in my config, nginx no longer complains about the conflict. Shouldn't this be handled in the plugin?

**Comment by jsha** [comment] 2017-02-15 16:00
Agreed this case should be handled by the plugin. @silverwind, what version of Certbot are you using?

**Comment by silverwind** [comment] 2017-02-15 16:03
0.11.1 from the [Arch repo](https://www.archlinux.org/packages/community/any/certbot/).

**Comment by SwartzCr** [comment] 2017-04-27 21:06
@ohemorange is this sorted now?

**Comment by ohemorange** [comment] 2017-04-27 21:26
@silverwind are you sure `/etc/letsencrypt/options-ssl-nginx.conf` is precisely the one linked above? If it says `ssl_session_cache shared:le_nginx_SSL:1m;` and it's still breaking, that's definitely a problem. If it says `ssl_session_cache shared:SSL:1m;`, then read on.

Some more info on what I expect is happening:

Those modifications were created by an earlier version of certbot. Once a server block has been made ssl, certbot doesn't touch it anymore. So what you're seeing here is caused by having run certbot before we fixed this. Actually, this entire method of including `/etc/letsencrypt/options-ssl-nginx.conf` no longer happens for new certificate installs.

Oddly enough, I'm currently bringing that method of doing things back, and plan to include functionality for updating the contents of `/etc/letsencrypt/options-ssl-nginx.conf`.

Some options:
- Make sure that `/etc/letsencrypt/options-ssl-nginx.conf` precisely matches `https://github.com/certbot/certbot/blob/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf`
- wait for 0.14.0 (hopefully), which should automatically fix this for you.

**Comment by silverwind** [comment] 2017-04-27 23:09
You're right, `/etc/letsencrypt/options-ssl-nginx.conf` is slightly different:

```
ssl_session_cache shared:SSL:1m;
```

While on master, the cache has another name, which I think avoids the conflict:

```
ssl_session_cache shared:le_nginx_SSL:1m;
```
So I guess this must be a packaging issue of sorts, right? I don't see a corresponding `.pacsave` file, so it I guess the package manager never attempted to update that file.

**Comment by ohemorange** [comment] 2017-04-27 23:17
We write that file manually in our own code on first run of the plugin, and haven't yet implemented anything to update it after it's first written (but keep an eye on #4559!). Probably ideally the package manager would handle that file.

I'm super relieved to hear that's the case; manually fixing the file on your machine should solve this problem.

I'm going to close this issue in favor of the other ones mentioned.

**Closed by ohemorange** 2017-04-27 23:17 UTC
Labels: area: nginx, bug

**Comment by Matrix7867** [comment] 2017-11-13 12:58
Hi!, 

OS: Ubuntu 16.04.1 LTS
certbot 0.19.0

I'm getting 
`nginx: [emerg] the shared memory zone "le_nginx_SSL" is already declared for a different use in /etc/letsencrypt/options-ssl-nginx.conf:7
Cleaning up challenges
Attempting to renew cert (xyzca.com) from /etc/letsencrypt/renewal/xyzca.com.conf produced an unexpected error: nginx restart failed

. Skipping.
All renewal attempts failed. The following certs could not be renewed:`

For workaround I have gone to `/etc/letsencrypt/options-ssl-nginx.conf:7` and commented out this line
`#ssl_session_cache shared:le_nginx_SSL:1m;`

Will it affect mine renewal process when the certificate will be expiring nearby and mine SSL session? 
I have just configured Letsencrypt past 10 days back and I was doing a `dry-run` with the certbot command. Any help would be appreciated.

**Comment by jsha** [comment] 2017-11-13 19:57
Nope, you should be fine. The `ssl_session_cache` line is not critical.

**Comment by april** [comment] 2019-05-29 18:16
This is fixed in the newest version of the generator, which uses a custom name (`MozSSL`) and describes how many sessions it can store.

https://mozilla.github.io/ssl-config-generator/

**Comment by CanadianJeff** [comment] 2021-11-01 03:03
hrmmmmmmm I just ran into this bug in 2020 come on guys
