### ISSUE TITLE
"certbot-auto --help" should not upgrade/call out to the internet

### ISSUE THREAD

**Issue by mk270** [certbot/certbot#7847] opened 2020-03-13 09:09 UTC
Using the commandline "--help" option shouldn't cause certbot-auto to do its "automatically upgrade" routine; that's not what people are expecting, and implies that help might be unavailable if the update servers aren't contactable.

**Comment by schoen** [comment] 2020-03-16 19:12
Duplicate of https://github.com/certbot/certbot/issues/1903?

**Comment by mk270** [comment] 2020-03-16 20:37
Indeed. I made a conscientious but unsuccessful search for duplicates before filing.

**Comment by schoen** [comment] 2020-03-16 20:56
Hi @mk270,

On further discussion we've realized that the solution to #1903 is narrower than what you're looking for, so it seems like it's still appropriate to have this issue open!

**Comment by mk270** [comment] 2020-03-16 21:36
fair enough

**Comment by mk270** [comment] 2020-05-07 04:42
I was clearly wrong to close it. Get a lot of this:

```
root@gaitskell:~# certbot-auto --help
Upgrading certbot-auto 1.3.0 to 1.4.0...
Replacing certbot-auto...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/main.py", line 6, in <module>
    import logging.handlers
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
root@gaitskell:~#
```

**Comment by bmw** [comment] 2021-07-21 21:17
certbot-auto has been deprecated, will error out on new systems, and existing installations are no longer receiving updates so I'm closing this.

**Closed by bmw** 2021-07-21 21:17 UTC
Labels: area: certbot-auto, area: ui / ux, feature request
