### ISSUE TITLE
Crash on starting certbot-nginx with a clean nginx install UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10453: ordinal not in range(128)

### ISSUE THREAD

**Issue by GLaDTheresCake** [certbot/certbot#5657] opened 2018-03-03 16:24 UTC
## My operating system is (include version):
4.15.6-1-ARCH

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pacman -S certbot-nginx

## I ran this command and it produced this output:
sudo certbot --nginx

Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10453: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.

## Certbot's behavior differed from what I expected because:
I would have expected a clean install of nginx and certbot to give me a certificate without problem, but for some reason it crashes, and I can't figure out why.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2018-03-03 15:33:11,925:DEBUG:certbot.main:certbot version: 0.21.1
2018-03-03 15:33:11,926:DEBUG:certbot.main:Arguments: ['--nginx']
2018-03-03 15:33:11,927:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-03-03 15:33:11,947:DEBUG:certbot.log:Root logging level set at 20
2018-03-03 15:33:11,948:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-03-03 15:33:11,950:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2018-03-03 15:33:11,998:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1240, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 981, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 189, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 25, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 248, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 248, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3.6/site-packages/certbot_nginx/configurator.py", line 131, in prepare
    self.parser = parser.NginxParser(self.conf('server-root'))
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 38, in __init__
    self.load()
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 45, in load
    self._parse_recursively(self.config_root)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 66, in _parse_recursively
    self._parse_recursively(subentry[1])
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 56, in _parse_recursively
    trees = self._parse_files(filepath)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/parser.py", line 206, in _parse_files
    parsed = nginxparser.load(_file)
  File "/usr/lib/python3.6/site-packages/certbot_nginx/nginxparser.py", line 123, in load
    return loads(_file.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10453: ordinal not in range(128)
2018-03-03 15:33:12,000:ERROR:certbot.log:An unexpected error occurred:

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
I am using the standard configuration of nginx as a test environment right now, there is no change in configuration from the standard nginx or certbot package from the arch repositories.

**Comment by schoen** [comment] 2018-03-05 20:50
Hi @GLaDTheresCake ,

I think this is a duplicate of https://github.com/certbot/certbot/issues/5646 or one of the other Unicode issues mentioned there. This is definitely a bug in Certbot.

A likely workaround is to remove non-ASCII Unicode characters such as ö or ñ from comments and/or filenames in your nginx configuration file. In the future, Certbot should be fixed so it doesn't crash when encountering these. Sorry for the inconvenience!

See also my comment related to this at

https://community.letsencrypt.org/t/certbot-unicodedecodeerror/52020/2

**Closed by schoen** 2018-03-05 20:50 UTC
Labels: duplicate

**Comment by Ariel-Rodriguez** [comment] 2018-07-08 19:44
Hello there,
I've been running the same issue, and i found this tread by "googleing". 
So, besides this issue is duplicated and closed already, i just want to share my solution that worked for me:

I could reproduce the issue because, LLC was not set on my remote server, so whenever i connected through SSH i saw this at console:
```
manpath: can't set the locale; make sure $LC_* and $LANG are correct
```

I followed stackoverflow's answer:
https://stackoverflow.com/questions/45995530/manpath-cant-set-the-locale-make-sure-lc-and-lang-are-correct

```
sudo locale-gen "en_US.UTF-8"
sudo dpkg-reconfigure locales
and in file /etc/default/locale add line LC_ALL="en_US.UTF-8" and relogin to you server
```

After this, finish and start your ssh session again. Ensure that warning log is gone.
Now `sudo certbot --nginx` is working fine form me.

I hope this does help to others as well.

**Comment by egberts** [comment] 2018-08-26 13:00
Found mind in

    /etc/letsencrypt/options-ssl-nginx.conf:        # The following CSP directives don't use default-src as

**Comment by adriennn** [comment] 2019-07-04 18:31
The crazy thing i that certbot was failing for me due to a hidden char in a non-enabled site configuration file (not in sites-enabled) ...

**Comment by timsengit** [comment] 2020-03-02 08:39
In my situation，the case is chinese character in nginx config file ,so remove them help me

**Comment by xfuturomax** [comment] 2022-07-18 13:52
Hi everyone!

I have similar issue. I tried to find invalid characters but without success:
`sudo grep -r -P '[^\x00-\x7f]' /etc/apache2 /etc/letsencrypt /etc/nginx` it shows nothing

Also i cheked locale, an it's ok. 

This is my error and log:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1591: invalid continuation byte`
and certbot log:
```
2022-07-18 15:48:31,113:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1076, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 225, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 25, in pick_configurator
    (interfaces.IAuthenticator, interfaces.IInstaller))
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 106, in pick_plugin
    verified.prepare()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 251, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 251, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 152, in prepare
    self.parser = parser.NginxParser(self.conf('server-root'))
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 38, in __init__
    self.load()
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 45, in load
    self._parse_recursively(self.config_root)
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 66, in _parse_recursively
    self._parse_recursively(subentry[1])
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 56, in _parse_recursively
    trees = self._parse_files(filepath)
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 207, in _parse_files
    parsed = nginxparser.load(_file)
  File "/usr/lib/python3/dist-packages/certbot_nginx/nginxparser.py", line 123, in load
    return loads(_file.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1591: invalid continuation byte
2022-07-18 15:48:31,115:ERROR:certbot.log:An unexpected error occurred:
```

It would be great if someone could help me with this issue.
