### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by MarcJose** [certbot/certbot#3142] opened 2016-06-09 20:21 UTC
After changing from the old letsencrypt-client to certbot and renewing the certificates I am getting SSL_ERROR_RX_RECORD_TOO_LONG for all my domains now.
Looking at the vhost-files (apache/ubuntu 14) I cannot see any changes there:

```
SSLEngine on
SSLProtocol All -SSLv2 -SSLv3
SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
SSLHonorCipherOrder     on
SSLCompression          off
SSLCertificateFile      /etc/letsencrypt/live/www.my-domain.tk/cert.pem
SSLCertificateKeyFile   /etc/letsencrypt/live/www.my-domain.tk/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/www.my-domain.tk/chain.pem
```

**Comment by schoen** [comment] 2016-06-10 00:09
This often indicates that HTTP is being used instead of HTTPS on that port. If you run

`curl http://www.my-domain.tk:443/`

do you see content from your site? (The expected behavior if HTTPS is being served would be an error, whereas if HTTP is being served on port 443, you would see something like the site's home page.)

I'm not sure why that would happen, but it would help explain more about what the problem is.

**Comment by MarcJose** [comment] 2016-06-10 11:49
No I didn't see any content. But I found the reason I guess: When I tried to validate the certificates they were all marked as invalid and having a look at them they don't look right at all. So I am currently installing a backup and going back to the old letsencrypt. I will test this behavior inside a VM first before trying again :)

**Comment by SwartzCr** [comment] 2017-03-17 19:58
Looks like this has been resolved, so I'm going to close it. Let me know if you're still having issues and I'll be happy to reopen it

**Closed by SwartzCr** 2017-03-17 19:58 UTC
