### ISSUE TITLE
unauthorized with invalid response

### ISSUE THREAD

**Issue by leon1995** [certbot/certbot#9059] opened 2021-10-05 18:22 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Debian GNU/Linux 11 (bullseye)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Docker through https://nginxproxymanager.com/

## I ran this command and it produced this output:
```
certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-9" --agree-tos --authenticator webroot --email "mail@mydomain.tld" --preferred-challenges "dns,http" --domains "sub.mydomain.tld"
```

## Certbot's behavior differed from what I expected because:
N certificate is generated

## Here is a Certbot log showing the issue (if available):
```
2021-10-05 17:50:33,312:DEBUG:certbot._internal.main:certbot version: 1.19.0
2021-10-05 17:50:33,312:DEBUG:certbot._internal.main:Location of certbot entry point: /opt/certbot/bin/certbot
2021-10-05 17:50:33,312:DEBUG:certbot._internal.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-10', '--agree-tos', '--authenticator', 'webroot', '--email', 'mail@leonbudnick.de', '--preferred-challenges', 'dns,http', '--domains', 'sub.mydomain.tld']
2021-10-05 17:50:33,313:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-cloudflare,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-10-05 17:50:33,324:DEBUG:certbot._internal.log:Root logging level set at 30
2021-10-05 17:50:33,325:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-10-05 17:50:33,327:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f0d059758d0>
Prep: True
2021-10-05 17:50:33,327:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f0d059758d0> and installer None
2021-10-05 17:50:33,327:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-10-05 17:50:33,334:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/226047420', new_authzr_uri=None, terms_of_service=None), 17ee7b27c0f523a37e1b07489898c734, Meta(creation_dt=datetime.datetime(2021, 10, 4, 15, 19, 22, tzinfo=<UTC>), creation_host='470309e4c8a8', register_to_eff=None))>
2021-10-05 17:50:33,335:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-10-05 17:50:33,337:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-10-05 17:50:33,951:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-10-05 17:50:33,952:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:33 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "YxIrA6a3BMk": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-10-05 17:50:33,952:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for sub.mydomain.tld
2021-10-05 17:50:33,955:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0009_key-certbot.pem
2021-10-05 17:50:33,958:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0009_csr-certbot.pem
2021-10-05 17:50:33,959:DEBUG:acme.client:Requesting fresh nonce
2021-10-05 17:50:33,959:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-10-05 17:50:34,112:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-10-05 17:50:34,113:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:34 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002SqRdNBb0WFSy5jaSHO-aKhwiSxl1FNUFyyxTtpjBWPA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-10-05 17:50:34,113:DEBUG:acme.client:Storing nonce: 0002SqRdNBb0WFSy5jaSHO-aKhwiSxl1FNUFyyxTtpjBWPA
2021-10-05 17:50:34,113:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "sub.mydomain.tld"\n    }\n  ]\n}'
2021-10-05 17:50:34,115:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI2MDQ3NDIwIiwgIm5vbmNlIjogIjAwMDJTcVJkTkJiMFdGU3k1amFTSE8tYUtod2lTeGwxRk5VRnl5eFR0cGpCV1BBIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "gNIhAtkjZPWqbpZmTFKq7flcbG6cu2Zkwx5PGfsT_X6NT64lQtSax9czfMc3-oQMVsE5gez71KC3XIvrS1yMF7V-3rRp-TCU6facParmSWa7rBCSJsGh3DAYiBJjs6znm6XH5Po1TPZKZVcMUBt8vMsbHZfm4Fp2pwQI37rNFkPuhcG6nhZwSJMMkdODgFipbJN6CEI7LIZUtCfaU_I2rGraBno4TD6kg-icR-Pix-xEP4KLOJm2Q7xXe79q1wBerLQC3hish0LJt3NG0q4gtkqt1r6zcgxB5WIf1Om1VM8dFNtFmKdsBFfDujbl10X9toGz3kWD3435niZ6cHhl8g",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImNsb3VkLmxlb25idWRuaWNrLmRlIgogICAgfQogIF0KfQ"
}
2021-10-05 17:50:34,316:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 343
2021-10-05 17:50:34,317:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Tue, 05 Oct 2021 17:50:34 GMT
Content-Type: application/json
Content-Length: 343
Connection: keep-alive
Boulder-Requester: 226047420
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/226047420/29680496400
Replay-Nonce: 0001_5toXCffg4mP_qLNONgADlOyCphbDTqrtPl9KaaPfVk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-10-12T17:50:34Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "sub.mydomain.tld"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/37298286410"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/226047420/29680496400"
}
2021-10-05 17:50:34,317:DEBUG:acme.client:Storing nonce: 0001_5toXCffg4mP_qLNONgADlOyCphbDTqrtPl9KaaPfVk
2021-10-05 17:50:34,317:DEBUG:acme.client:JWS payload:
b''
2021-10-05 17:50:34,319:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/37298286410:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI2MDQ3NDIwIiwgIm5vbmNlIjogIjAwMDFfNXRvWENmZmc0bVBfcUxOT05nQURsT3lDcGhiRFRxcnRQbDlLYWFQZlZrIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8zNzI5ODI4NjQxMCJ9",
  "signature": "abmpEmQ1V2pO0rdOg7em21z3LBeyzVioQlFQ4tQRHk5oQ1VVbCWp4Ece4JyWoB8PwmTsHxsHw53glUIgbyhjO1rmkaQHeZe71nMMuLM1oZsmqLVN2189qcPj7SIsz_4xz7Z6o3zheElc6ES8g8MsR-PrCDnz32eSRAZlwfP1YZQeZf5Gb4tnPJHGz-dQyJ_Dr7cgTEDVW7rJU2HFank_w_Gu_EmZvq-BgXVAUYNdbAELNKQDRuRVUQbwXjv5lyB9kPFKpa0faLDjXjOCd6EJYm16v06QEU0I0bunUdY7v2SRa5aVZee4ZTQZjv5X8UKYvd7Z7dzsKKhSL_4oloaUJg",
  "payload": ""
}
2021-10-05 17:50:34,485:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/37298286410 HTTP/1.1" 200 801
2021-10-05 17:50:34,485:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:34 GMT
Content-Type: application/json
Content-Length: 801
Connection: keep-alive
Boulder-Requester: 226047420
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002IIC_S-3JzQb0m1CLvugAEu-nc9nV2HE3O-3jM9q9wZA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sub.mydomain.tld"
  },
  "status": "pending",
  "expires": "2021-10-12T17:50:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/zAFz7Q",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/djY8BQ",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    }
  ]
}
2021-10-05 17:50:34,485:DEBUG:acme.client:Storing nonce: 0002IIC_S-3JzQb0m1CLvugAEu-nc9nV2HE3O-3jM9q9wZA
2021-10-05 17:50:34,486:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-10-05 17:50:34,486:INFO:certbot._internal.auth_handler:http-01 challenge for sub.mydomain.tld
2021-10-05 17:50:34,486:INFO:certbot._internal.plugins.webroot:Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
2021-10-05 17:50:34,486:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /data/letsencrypt-acme-challenge/.well-known/acme-challenge
2021-10-05 17:50:34,487:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /data/letsencrypt-acme-challenge/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs
2021-10-05 17:50:34,488:DEBUG:acme.client:JWS payload:
b'{}'
2021-10-05 17:50:34,489:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI2MDQ3NDIwIiwgIm5vbmNlIjogIjAwMDJJSUNfUy0zSnpRYjBtMUNMdnVnQUV1LW5jOW5WMkhFM08tM2pNOXE5d1pBIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8zNzI5ODI4NjQxMC9BVUlQYWcifQ",
  "signature": "KmVUz_eg_LiD2hVR7xyX1F9Z6kXAE5j-5h3igBkT6YpR9fmCqMaEISLy6MflTAsSrRQSDzZM5EgujJKBLG74GoaF5Ohdo8ovqtNjh_tfxCH4xtPeqyULBnqy_9D8OwqdemdJED2y7RQ3gWL6Y6sl4BpPh7VnZXiHDjBoofSs2wFD4UJS15xc2vXo6lCH-2NrtyAuWvN_WaUOuSuRdVL9Ard8nDGiUWDaX-dREhedlqUg4ov5dNYH-wjt-FZNNgNB2HfQJGriBeFRnmDYddXG156tw8_9tMGu-u0LolRcW58XeDyHLrLFs5ebN2C2Bnz7KstXBX9zA2g_lJXJCYm7iQ",
  "payload": "e30"
}
2021-10-05 17:50:34,652:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/37298286410/AUIPag HTTP/1.1" 200 186
2021-10-05 17:50:34,653:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:34 GMT
Content-Type: application/json
Content-Length: 186
Connection: keep-alive
Boulder-Requester: 226047420
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/37298286410>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag
Replay-Nonce: 0002JOSqLKHyMQgn7_HscAP39SDfptOdaWt9r-jcR7NA_Q0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag",
  "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
}
2021-10-05 17:50:34,653:DEBUG:acme.client:Storing nonce: 0002JOSqLKHyMQgn7_HscAP39SDfptOdaWt9r-jcR7NA_Q0
2021-10-05 17:50:34,653:INFO:certbot._internal.auth_handler:Waiting for verification...
2021-10-05 17:50:35,654:DEBUG:acme.client:JWS payload:
b''
2021-10-05 17:50:35,656:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/37298286410:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI2MDQ3NDIwIiwgIm5vbmNlIjogIjAwMDJKT1NxTEtIeU1RZ243X0hzY0FQMzlTRGZwdE9kYVd0OXItamNSN05BX1EwIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8zNzI5ODI4NjQxMCJ9",
  "signature": "oAkykMfO1FiEQ4i3foPc7D9wbj5V37sNxCnGueBpfNDCiGfZauonL_8SIuwFDd5MuqdlgnrQjrRkhQ1p12CLOFlC-0wXRRykj03uSKRySzaBioGVcztdVFr1waoei28j5PYkukpkNZAmaE3TegDBE4ZHdGWWLF9HMbGptGOeCcUz5jjWNgHnI374iudfY6bEFDK8Syfv9uj8e_h5g36HJhB-YqlJ1mfB2HDw6f728Xz00xiLJ4L_8msJ9eId9WnQWwukmeITMN5q7wk_SzggpGxhClM2NZsGAnT6gyiBYBZwb4nEKyr0BumVcs1QqCmSW737G6ynxUjl8-izChidow",
  "payload": ""
}
2021-10-05 17:50:35,819:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/37298286410 HTTP/1.1" 200 801
2021-10-05 17:50:35,820:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:35 GMT
Content-Type: application/json
Content-Length: 801
Connection: keep-alive
Boulder-Requester: 226047420
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002AU-9DurTvPMSnnpTRQbZ0-Ek8ZuHOaoUHEtRxcL7LrI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sub.mydomain.tld"
  },
  "status": "pending",
  "expires": "2021-10-12T17:50:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/zAFz7Q",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/djY8BQ",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs"
    }
  ]
}
2021-10-05 17:50:35,820:DEBUG:acme.client:Storing nonce: 0002AU-9DurTvPMSnnpTRQbZ0-Ek8ZuHOaoUHEtRxcL7LrI
2021-10-05 17:50:38,823:DEBUG:acme.client:JWS payload:
b''
2021-10-05 17:50:38,826:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/37298286410:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI2MDQ3NDIwIiwgIm5vbmNlIjogIjAwMDJBVS05RHVyVHZQTVNubnBUUlFiWjAtRWs4WnVIT2FvVUhFdFJ4Y0w3THJJIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8zNzI5ODI4NjQxMCJ9",
  "signature": "i3YO6_VTnCqECfZdCqq6H-20F7sOV_iIaXk0FRDhpslSSz96tb3eGVftAzRh55lav__HaF-4YXBrprmAB42C3fqP962bYEMMrJMTZGKHZEZsKLigvabkte_nZaUSZMwLBxnlmv78S3B7N1zs9kkwBzOJAiFC4lS_6WEsODQptCFCreLemmfD3oFB5SLmQapAHLLrn6xmLSMbtuLQ52sSPsSvztvx-_Ph4W6XJN55m0NIhuVMJGqh1SSrTLibbvY6OR959fLNpkPkQmzQ_Bp52f8jpywJuTD5TfXCIZuVI5qtNgEm29-Pu0zzJMcSJVEWl4J7YGMA_NhGy9PveFouRA",
  "payload": ""
}
2021-10-05 17:50:38,996:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/37298286410 HTTP/1.1" 200 1832
2021-10-05 17:50:38,996:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Tue, 05 Oct 2021 17:50:38 GMT
Content-Type: application/json
Content-Length: 1832
Connection: keep-alive
Boulder-Requester: 226047420
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002e4ciHOPxjqadW9nGi8RT796SLiyVact1KkVO1OgDoUk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "sub.mydomain.tld"
  },
  "status": "invalid",
  "expires": "2021-10-12T17:50:34Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from https://sub.mydomain.tld/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs [2606:4700:3037::6815:eb8]: \"\u003c!DOCTYPE html\u003e\\n\u003c!--[if lt IE 7]\u003e \u003chtml class=\\\"no-js ie6 oldie\\\" lang=\\\"en-US\\\"\u003e \u003c![endif]--\u003e\\n\u003c!--[if IE 7]\u003e    \u003chtml class=\\\"no-js \"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/37298286410/AUIPag",
      "token": "aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs",
      "validationRecord": [
        {
          "url": "http://sub.mydomain.tld/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs",
          "hostname": "sub.mydomain.tld",
          "port": "80",
          "addressesResolved": [
            "104.21.14.184",
            "172.67.160.36",
            "2606:4700:3037::6815:eb8",
            "2606:4700:3036::ac43:a024"
          ],
          "addressUsed": "2606:4700:3037::6815:eb8"
        },
        {
          "url": "https://sub.mydomain.tld/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs",
          "hostname": "sub.mydomain.tld",
          "port": "443",
          "addressesResolved": [
            "172.67.160.36",
            "104.21.14.184",
            "2606:4700:3037::6815:eb8",
            "2606:4700:3036::ac43:a024"
          ],
          "addressUsed": "2606:4700:3037::6815:eb8"
        }
      ],
      "validated": "2021-10-05T17:50:34Z"
    }
  ]
}
2021-10-05 17:50:38,997:DEBUG:acme.client:Storing nonce: 0002e4ciHOPxjqadW9nGi8RT796SLiyVact1KkVO1OgDoUk
2021-10-05 17:50:38,997:INFO:certbot._internal.auth_handler:Challenge failed for domain sub.mydomain.tld
2021-10-05 17:50:38,997:INFO:certbot._internal.auth_handler:http-01 challenge for sub.mydomain.tld
2021-10-05 17:50:38,997:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: sub.mydomain.tld
  Type:   unauthorized
  Detail: Invalid response from https://sub.mydomain.tld/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs [2606:4700:3037::6815:eb8]: "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js "

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2021-10-05 17:50:38,998:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 178, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-10-05 17:50:38,998:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-10-05 17:50:38,998:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-10-05 17:50:38,998:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs
2021-10-05 17:50:38,999:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-10-05 17:50:38,999:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1572, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1432, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 133, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 454, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 384, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 434, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 178, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-10-05 17:50:39,001:ERROR:certbot._internal.log:Some challenges have failed.
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
I am using cloudflare with the proxy. However, I was able to create certificates before I recreated the lxc where nginx proxy manager is running in.

EDIT: its working using a dns challenge with a cloudflare api token. However I prefere not to use the api token

**Comment by alexzorin** [comment] 2021-10-06 07:48
Based on this output:

> Detail: Invalid response from https://sub.mydomain.tld/.well-known/acme-challenge/aOT3Q2vz38an1fXkXFVJLQsOtmQ2QWpaZsnvGbR5fUs [2606:4700:3037::6815:eb8]: "<!DOCTYPE html>\n\n<!--[if IE 7]>    <html class=\"no-js "

I would say that, at the time of this log file, Cloudflare was serving up an Origin Error page for your domain, which would prevent Certbot's webroot authenticator from working, since no HTTP requests would successfully make it to your server.

I'm going to close this issue as it's not a bug or feature request, but please ask for help on https://community.letsencrypt.org if you continue to have problems.

**Closed by alexzorin** 2021-10-06 07:48 UTC
