### ISSUE TITLE
Explicit specify cert storage location(remove use of automatic -0001 suffixes)

### ISSUE THREAD

**Issue by hultqvist** [certbot/certbot#2128] opened 2016-01-09 11:52 UTC
# Scenario

I start with generating a single cert for "example.com, www.example.com, test.example.com", this is stored in `/etc/letsencrypt/archive/example.com`

Later I generate a new cert with "example.com, www.example.com"
This will be stored in `/etc/letsencrypt/archive/example.com-0001`
# Problems

At this stage it is unclear whether the user intended to remove `test.example.com` or to generate a new cert.

The risks are that one might not notice the suffix and assume that the new certs are in the original location.
I'm not suggesting silently replacing the cert in the original location.

**The location of the generated certs should be known before running the client.**
# Suggestion

With this issue I suggest removal of the automatic suffix generation.

The algorithm that triggers the use of prefix should still be in use but once triggered I suggest the following approach.

When triggered an error will occur.
The error message will instruct that one of the following approaches is required.
1. Indicate that you want to modify the domains in the current cert. This feature is suggested in #2071 
2. Choose a new alias for the storage using an option like `--alias`

With option 2 the use of `--alias example2` would store the certs in `/etc/letsencrypt/archive/example2`

These two options can work independently and combined.
# Examples

If your intention was to remove `test.example.com` then you use 1

If you intention was to generate another different cert then use 2

If you want to further modify the domain list for the cert in the new location you must use both 1 and 2.

**Comment by bmw** [comment] 2016-01-12 00:51
I actually think this is a duplicate of #1882. Both address the problem of requesting a certificate whose names are a subset of those an existing certificate. With that said, I appreciate you taking the time to write up such a detailed post with both suggestions and examples.

The approach we're likely to take to solve #1882 mirrors how we handled the opposite situation. This is where you are requesting a certificate whose names are a superset of those in an existing certificate. In this case, assuming you provided nothing on the command line, you'll see the following:
```
-------------------------------------------------------------------------------
You have an existing certificate that contains a portion of the domains you
requested (ref: /etc/letsencrypt/renewal/example.com.conf)

It contains these names: example.com, www.example.com

You requested these names for the new certificate: example.com,
www.example.com, test.example.com

Do you want to expand and replace this existing certificate with the new
certificate?
-------------------------------------------------------------------------------
(E)xpand/(C)ancel: 
```

You can also skip this prompt by providing command line flags. If you provide `--expand`, on the command line, the symlinks for the existing certificate will be updated to point to the certificate with the new name.

If, however, you provide `--duplicate`, a new directory will be created to store your certificate. The name of this directory is determined by the first domain name that you entered. If there is another directory with that name, it will append a four digit number so that the name is unique. Otherwise, it uses the domain name with no suffix.

I believe this approach gets you all of the behavior you want with the exception of being able specify to specify the name of the new directory on the command line. If you think this would be useful, let me know and I'll create a new issue (or feel free to do it yourself). Alternatively, if you feel that this is a different problem than the one expressed in #1882, let me know and I'll reopen.

**Comment by hultqvist** [comment] 2016-01-12 21:37
One concern I have with your suggested dialog is that it makes the client interactive and could lock up the process calling it. Is there an issue # for what you described?

I consider #1882 and #2071 basically the same feature request, to modify the list of domains whether one is to add domains and the other is to remove.

My intention with this issue was tangential to those, but as I [wrote in a comment to #2071](https://github.com/letsencrypt/letsencrypt/issues/2071#issuecomment-171041891) I begin to suspect that any change in the list of domains to an existing folder would require one to specify which folder to modify.
The suggestion here would be one way to solve that.

My main argument in this issue is still the request to know where the certs will be stored before running the client. Thus avoiding having to parse the output of the client to determine where it placed the certs.

**Comment by bmw** [comment] 2016-01-19 18:20
Good point @hultqvist. Sorry for prematurely closing this issue.

Currently, `letsencrypt` is designed to be run interactively so prompting the user is consistent with the rest of the project. With that said, we're working on providing non-interactive ways of running the client such as the approach proposed by #2078.

We need a way for the user to choose which lineage gets modified, however, such as what you proposed with `--alias`. Using `--expand` or the proposed `--shrink` can be ambiguous or update lineages other than what the user intended.

**Comment by cybernet** [comment] 2016-03-31 20:26
+1

**Comment by dentm42** [comment] 2016-04-17 19:39
What if the LINEAGE and list of DOMAINS were exposed to the --post-hook script in the same way $RENEWED_LINEAGE and $RENEWED_DOMAINS are exposed to the --renew-hook script.  This would allow users to create scripts to change symlinks, copy certificates/keys, or even change web server configs without LE needing to pre-guess how a user would want things to behave - they could just get it to behave however they desired by using the --post-hook POST_HOOK.

**Comment by jvanasco** [comment] 2016-04-26 21:12
On a slightly related note, in #2880 i suggest that a `.txt` file is added into the certificate storage that lists the domain names on the certificate.  this would allow users to more easily see what domains are where, and use `grep` on the directory structure.

**Comment by McLive** [comment] 2016-06-11 21:44
I thought --expand would disable the creation of --0001 folders? It doesn't work for me...

**Comment by bmw** [comment] 2016-06-13 19:17
@McLive, it should if the set of domains you're requesting is a superset of the domains already found in your existing certificate. For example, if you have a certificate for `example.com` and `other.example.com` found in `/etc/letsencrypt/live/example.com`, running:
```
certbot -d example.com -d yet.another.example.com --expand
```
will result in `/etc/letsencrypt/live/example.com-0001`.

If, however, you include all existing domains as well as the new ones like so:
```
certbot -d example.com -d other.example.com -d yet.another.example.com --expand
```
this will expand the existing certificate.

If this isn't the behavior your experiencing, please open a new issue with more details to help track that problem.

NOTE: If you provide a set of domains which is a superset of more than one certificate, the one that gets expanded is undefined. See #2128 for more info.

**Comment by peterthomassen** [comment] 2016-10-06 22:42
The `--alias` approach would indeed solve several problems:

In my web server configuration, there is one certificate per virtual host. A customer can own one or more virtual hosts. Let's say he has domains `a.com`, `b.com` in one virtual host, and  `c.com` in another. The lineage names will be `a.com` for the first two domains and `c.com` for the third domain.

Now, assume that the customer moves `a.com` from the first to the second virtual host. If new certs were generated from scratch, we would now get lineage `b.com`  for one virtual host, and `a.com` for the other (which also has `c.com` as an additional domain in the certificate). All of this has to be dealt with using appropriate `--expand` and `--duplicate` flags (and possibly `--shrink` in the future).

However, the easiest solution would be to assign a name per virtual host using `--alias`. In that case, I could just extract the list of domains associated to the virtual host, and tell certbot to go and replace _that_ `--alias`ed certificate with whatever is the list of domains right now, regardless of whether it is shrinking, expanding, whatever.

(An obvious choice for the alias would be something related to the virtual host document root, for example the FTP user name.)

**Comment by peterthomassen** [comment] 2016-10-13 18:51
See https://github.com/certbot/certbot/issues/3615

**Closed** 2019-06-21 19:59 UTC
Labels: area: cert management, area: ui / ux, feature request, needs-update
