### ISSUE TITLE
TypeError: unorderable types: NoneType() < NoneType()

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#6652] opened 2019-01-10 04:03 UTC
## My operating system is (include version):

Ubuntu 16.04.5 LTS (xenial)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt
certbot                          0.28.0-1+ubuntu16.04.1+certbot+4           
python3-certbot                  0.28.0-1+ubuntu16.04.1+certbot+4           
python3-certbot-apache           0.28.0-1+ubuntu16.04.1+certbot+3           

## I ran this command and it produced this output:
```
# certbot
...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache

Please choose an account
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
...
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
...
Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
...
blank to select all options shown (Enter 'c' to cancel): 3
An unexpected error occurred:
TypeError: unorderable types: NoneType() < NoneType()
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:

It crashed

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2019-01-10 03:58:23,452:DEBUG:certbot.storage:No matches for target cert.
2019-01-10 03:58:23,452:DEBUG:certbot.storage:No matches for target privkey.
2019-01-10 03:58:23,452:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1089, in run
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 286, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 313, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 264, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 194, in _handle_identical_cert_request
    if not lineage.ensure_deployed():
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 794, in ensure_deployed
    if self.has_pending_deployment():
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 813, in has_pending_deployment
    smallest_current = min(self.current_version(x) for x in ALL_FOUR)
TypeError: unorderable types: NoneType() < NoneType()
2019-01-10 03:58:23,453:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by jsoref** [comment] 2019-01-10 04:13
I had set up:
`/etc/letsencrypt/live/example.com/cert.pm` -> `/etc/letsencrypt/archive/example.com/cert.pem`
etc.

The code expected a number between `cert` and `.pem` in the archive side.

**Comment by bmw** [comment] 2019-01-10 17:58
Yeah. The structure of `/etc/letsencrypt` is very sensitive to user changes.

We should clean up that error message though.

**Comment by schoen** [comment] 2019-02-04 20:52
Maybe a duplicate of #775, then?

**Comment by bmw** [comment] 2019-02-04 20:54
Yeah I think so. Let's close this and link to this issue as a specific instance of #775.

**Closed by bmw** 2019-02-04 20:54 UTC
Labels: area: error handling
