### ISSUE TITLE
Apache: If not included in the wizard domain's https config deleted

### ISSUE THREAD

**Issue by Cactucs** [certbot/certbot#1542] opened 2015-11-17 20:26 UTC
I was adding cert for another domain on my Apache server, where I have another domain. I inputed only new domain in the process. The the old generated config was deleted and thus the server was "misconfigured" and let's encrypt wasn't able to do anything. I had to delete symlink from site-enabled and run letsencrypt-auto once more, but with inputing both domains.

**Comment by bmw** [comment] 2015-11-18 00:34
Thanks for the bug report @Cactucs. I have a few questions for you that would help us track down the cause of this problem:

1) When you ran `letsencrypt`, did you specify a subcommand like `certonly`, `auth`, or `install` on the command line?
2) Did you modify your configuration between runs of Let's Encrypt?
3) What OS are you running?
4) What version of Apache are you using?
5) Can you send us all/part of your Apache configuration? One thing you can try is running `letshelp-letsencrypt`. Assuming you cloned this repo, there is a Python script in `letshelp-letsencrypt/letshelp_letsencrypt/apache.py` that will package your Apache config in a tarball, excluding potentially sensitive information like crypto keys, passwords, comments, etc. After this tarball is created, you could upload here for us to take a look. Alternatively, you can choose which files to include yourself.

Thanks for any additional info!

**Comment by SwartzCr** [comment] 2017-08-31 22:52
closing due to lack of more info to allow us to debug

**Closed by SwartzCr** 2017-08-31 22:52 UTC
Labels: area: apache, more-info
