### ISSUE TITLE
A simpler way to add a domain is needed

### ISSUE THREAD

**Issue by paolobenve** [certbot/certbot#6532] opened 2018-11-26 22:20 UTC
As long as I know, in order to add a domain to a certificate you need to specify all the "old" domains plus the new one in the -d parameter. This way a mistake is easily made.

A simpler way to add a domain is needed: another parameter, e.g. --add-domain, which permits to add a domain to an existing certificate.

**Comment by schoen** [comment] 2018-11-26 22:35
@ohemorange, did you have any long-term post-CMIP thinking about the merits of this kind of feature? Should there be a *CMIP 2: Revenge of the CMIP*?

**Comment by ohemorange** [comment] 2018-11-26 22:51
This is a duplicate of #4410, see discussion there.

**Closed by ohemorange** 2018-11-26 22:51 UTC
Labels: area: cert management, area: ui / ux, feature request
