### ISSUE TITLE
How to disable debug log?

### ISSUE THREAD

**Issue by jarmo** [certbot/certbot#3680] opened 2016-10-24 06:40 UTC
I'm getting debug log even though I have not set it from command line (as much I'm aware of).

Here's the output:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Cert not yet due for renewal
Keeping the existing certificate
```

This is how I'm running certbot-auto right now:
```
./certbot-auto certonly --text --non-interactive --webroot -w /var/www/public/ -d mydomain.com -d www.mydomain.com --keep-until-expiring --expand --agree-tos --email jarmo.p@gmail.com >/dev/null
```

Why is it output to STDOUT? How to disable it completely?

**Comment by bmw** [comment] 2016-10-24 19:27
You want to use `-q/--quiet`. From our help:
```
  -q, --quiet           Silence all output except errors. Useful for
                        automation via cron. Implies --non-interactive.
                        (default: False)
```

**Comment by jarmo** [comment] 2016-10-25 06:43
Thanks!

Nevertheless it still does not make sense to a) have debug mode enabled by default; b) log out to STDERR.

**Comment by bmw** [comment] 2016-10-25 23:32
> a) have debug mode enabled by default

This is not a debug mode. Certbot was designed to be run interactively and these are status messages telling the user what's going on. If you want a quiet, non-interactive version of Certbot, you should use the `-q/--quiet` flag.

> b) log out to STDERR

This issue is described by #3666.

I'm closing this issue because I believed I've answered your question and covered your concerns, either by explaining the design decision or linking to another issue. If you disagree, please comment and I'll reopen.

**Closed by bmw** 2016-10-25 23:32 UTC
Labels: question

**Comment by jarmo** [comment] 2016-10-26 09:31
1) I recommend to omit word "debug" from that log statement so it would be more obvious that this is a normal logging mode not a debug mode. Otherwise it's kind of misleading, which made me think that somekind of a debug mode is enabled.

Thanks again!

**Comment by tomtastic** [comment] 2017-10-25 20:09
'-q' doesn't seem to work?

`2017-10-25 11:55:59,021:DEBUG:certbot.main:certbot version: 0.17.0
2017-10-25 11:55:59,022:DEBUG:certbot.main:Arguments: ['-q']
2017-10-25 11:55:59,023:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-10-25 11:55:59,112:DEBUG:certbot.log:Root logging level set at 30
2017-10-25 11:55:59,114:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-10-25 11:55:59,164:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f67f7bea550> and installer <certbot.cli._Default object at 0x7f67f7bea550>
2017-10-25 11:55:59,164:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7f67f7beabd0>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7f67f7bea5d0>, apache=<certbot.cli._Default object at 0x7f67f7bde8d0>, apache_challenge_location=<certbot.cli._Default object at 0x7f67f7ba5310>, apache_ctl=<certbot.cli._Default object at 0x7f67f7ba5710>, apache_dismod=<certbot.cli._Default object at 0x7f67f7ba1d10>, apache_enmod=<certbot.cli._Default object at 0x7f67f7ba1c10>, apache_handle_modules=<certbot.cli._Default object at 0x7f67f7ba5490>, apache_handle_sites=<certbot.cli._Default object at 0x` etc, etc, etc...

**Comment by tomtastic** [comment] 2017-10-25 20:16
@bmw Can you suggest why /var/log/letsencrypt/letsencrypt.log is still being filled with DEBUG info despite '-q' being used?

**Comment by tomtastic** [comment] 2017-10-25 21:50
Well, it looks like there is no actual nice way to stop this DEBUG log, so I set --max-log-backups to 0 and then forcibly clobbered the log file by issuing an os.remove in /usr/lib/python2.7/dist-packages/certbot/log.py
`
116     logger.debug('Root logging level set at %d', level)
117     logger.info('Saving debug log to %s', file_path)
118     os.remove(file_path)
`

**Comment by bmw** [comment] 2017-10-26 18:31
`-q` only affects output printed to terminal and Certbot still includes this information its log files. If you want absolutely no logs from Certbot (which isn't recommended), you could make:
`/var/log/letsencrypt/letsencrypt.log` a symlink to `/dev/null` and include `--max-log-backups 0` on the command line.

**Comment by nyetwurk** [comment] 2018-04-07 00:48
This makes absolutely no sense.

**Comment by nyetwurk** [comment] 2018-04-07 00:54
https://github.com/certbot/certbot/issues/3481

**Comment by nodesocket** [comment] 2018-05-08 00:50
Even doing `--max-log-backups 0` just appends to the single log file. Really there should be a way to say no logging to files.

**Comment by gmkey** [comment] 2018-06-26 16:16
I have to concur. There is a business case where I do want the command output to screen, but don't want to be bothered with a unnecessary log message. 

I am using certbot certificates in a bash script because I want to be able to validate specific certs, but the problem is, this generates console messages that I don't need.
-q prevents me from using the output.

**Comment by DimaVIII** [comment] 2018-08-25 13:10
@gmkey Your question is offtopic but here is the magic, this is the way to block direct script output to the console and save the output message of the certbot in $CERTBOTOUTPUT for further use.  

```
	COMMAND="run -n --quiet --nginx --preferred-challenges http --cert-name $DOMAIN -d $DOMAIN,www.$DOMAIN"

	# run certbot
	CERTBOTOUTPUT=$(( /scripts/certbot-auto $COMMAND ) 2>&1)
	if [[ $? -eq 1 ]]; then # IF ERROR
	    echo $CERTBOTOUTPUT
    	    exit 1
	fi
```

**Comment by sombra2eternity** [comment] 2019-02-14 18:53
> You want to use `-q/--quiet`. From our help:
> 
> ```
>   -q, --quiet           Silence all output except errors. Useful for
>                         automation via cron. Implies --non-interactive.
>                         (default: False)
> ```

```certbot certificates
```

Generating log when just listing certs, top feature

**Comment by nadirlc** [comment] 2019-11-05 04:12
The certbot --help command does not show the option "-q, --quiet". I am using certbot version 0.28.0

**Comment by darkotodic** [comment] 2024-06-04 17:32
You can configure logrotate to keep only 2 files.

**Comment by tomtastic** [comment] 2024-06-04 17:35
Holy issue necromancy!
