### ISSUE TITLE
certbot timeout on fresh nginx install, requires manual "listen 443 ssl"

### ISSUE THREAD

**Issue by rptb1** [certbot/certbot#5292] opened 2017-12-03 15:44 UTC
## My operating system is (include version):

Ubuntu Desktop 16.04.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt-get, exactly as instructed at https://certbot.eff.org/#ubuntuxenial-nginx

## I ran this command and it produced this output:

```
sudo certbot --nginx
```
...
```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: [recated]
   Type:   connection
   Detail: Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

## Certbot's behavior differed from what I expected because:

I thought it would configure automatically for a fresh nginx installation with a simple vhost.  My vhost was a direct copy of the nginx example from nginx config file.

I fixed the problem by adding `listen 443 ssl` (just that, no certs) to the config and re-running `certbot --nginx`. certbot was then able to get in touch with the server and finish the installation.

I suggest that the certbot scripts ought to detect this case and add their own 443 line (and possibly `listen [::]:443`).

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Redacted log attached.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
server {
	listen 80;
	listen [::]:80;
	server_name [reacted];
	root /var/www/[redacted];
	index index.html;
	location / {
		try_files $uri $uri/ =404;
	}
}
```

[letsencrypt.log.txt](https://github.com/certbot/certbot/files/1524901/letsencrypt.log.txt)

**Comment by SwartzCr** [comment] 2017-12-04 21:55
Hmm - @ohemorange is this expected behavior?

**Comment by ohemorange** [comment] 2017-12-04 22:13
This report is very strange to me, because we do add that `listen 443 ssl` line. You can see in the log that we temporarily add it, then roll back the changes when it fails to connect:

```
server {
	listen 80;
	listen [::]:80;

	server_name www.[redacted];

	root /var/www/www.[redacted];
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /var/lib/letsencrypt/snakeoil/0003_cert.pem; # managed by Certbot
    ssl_certificate_key /var/lib/letsencrypt/snakeoil/0003_key.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

Did it just fail once, or could it be a flaky error?

**Comment by rptb1** [comment] 2017-12-05 10:00
I'll see if I can reproduce it on a fresh VM and get back to you.

**Comment by bmw** [comment] 2019-03-28 22:27
This bug was about the support for the TLS-SNI-01 challenge which is no longer supported by Certbot or Let's Encrypt so I'm closing this issue.

**Closed by bmw** 2019-03-28 22:27 UTC
Labels: area: nginx, area: ui / ux
