### ISSUE TITLE
certbot ignores my vhost file

### ISSUE THREAD

**Issue by poizan42** [certbot/certbot#3247] opened 2016-07-06 17:06 UTC
Here I have run `./certbot --domains poizan.dk`:
![image](https://cloud.githubusercontent.com/assets/308129/16627131/3c6f5fcc-43ac-11e6-8634-a1ae41974d1b.png)

This is the content of /etc/apache2/sites-available and sites-enabled:
![image](https://cloud.githubusercontent.com/assets/308129/16627204/891347bc-43ac-11e6-8015-7cfdf4d4fd84.png)

Why is poizan.dk.conf missing from the listing?

**Comment by pde** [comment] 2016-07-06 19:48
Can you post the contents of the `poizank.dk.conf` configuration file?

**Comment by pde** [comment] 2016-07-06 19:49
And also possibly the main `/etc/apache2/apache2.conf` file...

**Comment by poizan42** [comment] 2016-07-07 00:27
See http://poizan.dk/stuff/poizan.dk.conf and http://poizan.dk/stuff/apache2.conf

**Comment by pde** [comment] 2016-07-08 00:22
@joohoi, any chance you have time to look at this?

**Comment by joohoi** [comment] 2016-07-08 15:52
I'm pretty time restricted currently, but took a quick peek. @poizan42 certbot doesn't currently support multiple virtualhosts per config file, so could you please split your VirtualHost statements to a separate files and try again (currently poizan.dk.conf has two <VirtualHost> segments)?

**Comment by pde** [comment] 2016-07-08 20:15
@joohoi oops sorry I should have spotted that!

Duplicate of: #1042

**Closed by pde** 2016-07-08 20:15 UTC
Labels: apache, duplicate
