### ISSUE TITLE
Hooks do not get stored in renewal config file

### ISSUE THREAD

**Issue by maddes-b** [certbot/certbot#3394] opened 2016-08-11 09:42 UTC
OS: Debian 8 "Jessie" with all current updates (as of 2016-08-10)
Package: certbot 0.8.1-2~bpo8+ from jessie-backports

When getting a new cert via certonly then the hook definitions are not executed and stored in the renewal config file.
Used certonly with --config for domain specific stuff and the hook definitions did not get executed and are missing in the renewal config file.
Also checked with a fresh setup and defining the hook on the command line with "--post-hook 'systemctl reload apache2'", but no difference.
Expected behaviour after reading the docs was that the post hook gets executed on certonly and also stored in the renewal config file.
Getting the certifcate and renewal itself works fine.

My setup:
- File /etc/letsencrypt/cli.ini contains just registration config
- File /home/root/setup_files/files_letsencrypt/letsencrypt/letsencrypt.www.example.ltd.conf contains the domain config for the initial certonly call
- Executed certbot certonly --noninteractive --test-cert --config /home/root/setup_files/files_letsencrypt/letsencrypt/letsencrypt.www.example.ltd.conf
- Renewal file /etc/letsencrypt/renewal/www.example.ltd.conf was created

Following is the content of those file. The content was changed to only have example.ltd instead of the original multiple domains and webroots.

1) /etc/letsencrypt/cli.ini

```
email = someone@example.ltd
agree-tos
update-registration
```

2) /home/root/setup_files/files_letsencrypt/letsencrypt/letsencrypt.www.example.ltd.conf

```
authenticator = webroot

post-hook = systemctl reload apache2

### results will be in /etc/letsencrypt/live/<1st domain>
### here: /etc/letsencrypt/live/www.example.ltd/[cert|fullchain].pem and privkey.pem

### use domain to define the first domain (only works 100% on initial request)
domain = www.example.ltd

### in config file have to use webroot-map for multiple webroot-paths
### webroot-map must be a single line (as of 0.8.1)
webroot-map = {"www.example.ltd,example.ltd":"/home/maddes/www/example.ltd/httpdocs/" }

### ATTENTION!!!
### csr will make the cert not renewable via renew command, but can still be renewed via certonly
#csr = /etc/ssl/private/services-4096.www.example.ltd.sha512.csr
### paths are ignored when *not* called with csr
#cert-path = /etc/ssl/certs/services-4096.www.example.ltd.sha256.letsencrypt.crt
#fullchain-path = /etc/ssl/certs/services-4096.www.example.ltd.sha256.letsencrypt-chain.crt
#chain-path = /tmp/services-4096.www.example.ltd.sha256.letsencrypt-dummy.crt
```

3) /etc/letsencrypt/renewal/www.example.ltd.conf

```
# renew_before_expiry = 30 days
version = 0.8.1
cert = /etc/letsencrypt/live/www.example.ltd/cert.pem
privkey = /etc/letsencrypt/live/www.example.ltd/privkey.pem
chain = /etc/letsencrypt/live/www.example.ltd/chain.pem
fullchain = /etc/letsencrypt/live/www.example.ltd/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
installer = None
account = 617630c4c6dc6937564c6450602deb92
server = https://acme-staging.api.letsencrypt.org/directory
[[webroot_map]]
example.ltd = /home/maddes/www/example.ltd/httpdocs
www.example.ltd = /home/maddes/www/example.ltd/httpdocs
```

**Comment by pde** [comment] 2016-08-12 23:36
The problem is that we forgot to add the hook variables to the list of configuration variables saved [here](https://github.com/certbot/certbot/blob/master/certbot/renewal.py#L32).

Aside: what else have we forgotten to add there?

**Comment by bmw** [comment] 2016-08-12 23:37
First of all, thank you for such a detailed bug report. You make my job easy.

As for the hooks not getting called, they are only called when your certificate is actually due for renewal. If you run `certbot renew` or `certbot certonly --non-interactive`, your certificate will not be renewed until it approaches expiration (30 days prior to expiration by default). If Certbot decides your certificate is not due for renewal, it exits without calling `--pre-hook`, `--renew-hook`, or `--post-hook`.

**Comment by pde** [comment] 2016-08-12 23:55
@bmw points out that the current code would run the `pre-hook` of the first lineage it's renewing, and then the `post-hook` of the last one, if there is one, after all renewals are done.  Possibly what should happen is:

* If a pre-hook isn't in the `set()` you've already run, run it when that lineage comes up for renewal, even if you've already run some pre-hook for some other lineage
* At the end, run the `set()` of all post-hooks for all lineages you've renewed.

That has the disadvantage that if the user spelled "service nginx stop" slightly differently, it will get run twice.

**Comment by bmw** [comment] 2016-08-13 00:10
Other possibilities:

1. Walk all lineages first determining their pre and post hooks. Run all pre-hooks before renewing any lineage. Run all post-hooks after renewing all lineages.
2. Run `pre-hook` and `post-hook` directly before and after renewing a lineage. This reduces the value of `--renew-hook`  (which is perhaps a good things -- yay fewer flags and less complexity!) but will be slightly complicated if pre and post hooks are also specified on the command line. In this case, we could run hooks specified on the command line at the beginning and end of the entire run, with lineage specific hooks directly before and after renewing that lineage.

A downside to running all pre and post-hooks together is it becomes impossible to mix renewals using both the Apache and standalone plugins. The lineage that uses the standalone plugin could specify `apache2ctl -k stop` and `apache2ctl -k start` as the pre and post hook respectively, but if the following sequence of events occurs, the renewal won't work

1. Run `apache2ctl -k stop`.
2. Renew the lineage using the Apache plugin which will restart Apache.
3. Try to use standalone which will fail.
4. Run `apache2ctl -k start` and get an error message that Apache is already started.

Maybe we don't care because when we attempt to renew the `standalone` lineage the next time, the renewal will succeed, but this seems to limit some of the options of things that can be done with hooks.

**Comment by pde** [comment] 2016-08-13 00:26
Calling my plan 3, I'd say the strengths/weaknesses are:

1. 
  * - Runs hooks for lineages that aren't being renewed, and which may be quite particular to them
2. 
  * - Does a lot of redundant stuff. 
  * + has clean semantics 
  * + helps with the apache/standalone problem (though #2305 will also help with that shortly).
0. 
  * + Is "conceptually minimal" 
  * - May do strange things if the user creates multiple lineages with equivalent commands that are encoded in slightly different hook strings

**Comment by bmw** [comment] 2016-08-13 00:53
For plan 1, I don't think we should run hooks for lineages that aren't renewed. We could walk the list and only run pre/post hooks to the lists of commands to run if the lineage is due for renewal.

**Comment by pde** [comment] 2016-08-13 01:32
Oh then I think 1 and 3 are the same thing?

**Comment by pde** [comment] 2016-08-13 01:32
Kicking this out of 0.9.0, unless someone shows up with a pull request!

**Comment by bmw** [comment] 2016-08-13 02:05
Difference is whether you run the `--pre-hook` flag right before you renew that specific lineage or all at once at the beginning. In the end, it probably doesn't matter and doing it right before is easier and faster for us.

**Comment by maddes-b** [comment] 2016-08-13 11:28
Uh, so much to read after a single night (I'm on CEST).
I let your comments sink in for an hour, and here are my two cents.
If I did get something wrong, then please bear with me.

What I would expect from certbot is the following:

1. If anything fails in the process, then protocol, remember that result for the final RC and continue with the next authenticator, cert or installer. Goal is too renew as much certs as possible.
2. Determine if any cert has to be created or renewed. If none, just exit with RC 0.
3. Group to-be-created/renewed certs by authenticator
4. Loop: Process certs per authenticator (or even by auth/pre-hook/post-hook combo)
  1. Run pre-hook of authenticator
  2. Renew certs and run renew hook for each cert
  3. Run post-hook of authenticator
  4. Next iteration with certs of next authenticator
5. Group renewed certs by installer
6. Loop: Process certs per installer.

Questions:
* Better to group by by auth/pre-hook/post-hook combo, instead of just auth?
* Do installer need hooks too?
* Should authenticator and installer config be separated from cert definition?<br>
e.g. /etc/letsencrypt/authenticator/webroot with hooks, webroot paths and maybe more<br>

Thanks for your time and effort. Much appreciated.
Maddes

@bmw: You're welcome. I'm a programmer myself, so I know that a how-to-reproduce is highly important. :)

**Comment by maddes-b** [comment] 2016-09-14 20:22
My current workaround for Debian 8 is a modified cron job that defines the hooks on the command line.
The hooks are separate scripts to avoid cluttering the line even further, also gives you the ability to use custom variables. Imporant is that you exit with a code of 0 if everything went right.

/etc/cron.d/certbot
`0 */12 * * * root test -x /usr/bin/certbot && perl -e 'sleep int(rand(3600))' && certbot -q renew --pre-hook /usr/local/bin/letsencrypt_pre-hook.sh --renew-hook /usr/local/bin/letsencrypt_renew-hook.sh --post-hook /usr/local/letsencrypt_post-hook.sh`

/usr/local/bin/letsencrypt_pre-hook.sh & /usr/local/bin/letsencrypt_renew-hook.sh
```
#!/bin/sh

exit 0
```

/usr/local/letsencrypt_post-hook.sh
```
#!/bin/sh

[ -x /usr/sbin/apache2 ] && /bin/systemctl reload apache2
[ -x /usr/sbin/postfix ] && /bin/systemctl reload postfix

exit 0
```

**Comment by gilou** [comment] 2016-11-01 13:29
Hi,
I just got bitten by this, so adding my 2 cents, but it seems to me that the global idea is to replace whatever parameters more specific whenever they occur in renewal configs, but I may be mistaken.. Adding those to STR_CONFIG_ITEMS would fit the bill for me, at least for the renew hooks...

**Comment by pde** [comment] 2016-11-05 00:44
@gilou's PR #3394 stores renew hooks in renewal conf files, which I think is correct, and addresses the most central core of this problem, so we have a pr for part of this.

But I think @bmw talked offline about what happens when the user had five different lineages, each with different renew hooks, and then supplies another renew hook on the command line.  As #3394 is written, the one on the command line will replace all the others. We might instead want to accumulate hooks from renewal conf files and the command line and run them all? Although that would create horrible special cases in the way renewal conf files are managed...

We may also still need some handling for pre- and post- hooks.

**Comment by ffittschen** [comment] 2017-01-04 23:31
As I originally filed https://github.com/certbot/certbot/issues/3486 that resolved as a duplicate of this issue, I'm happy to see that a PR has been merged and is scheduled for the next release 👍🏻

@pde regarding the accumulation of multiple hooks: How about giving `--before-all` and `--after-all` options? I know the behaviour from the `before_all` and `before_each` blocks in [fastlane](https://github.com/fastlane/fastlane) as explained in their [Advanced docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md). The scripts specified with `--before-all` or `--after-all` would be run before all renewals and after all renewals, while each stored hook will still be run for the specific lineage (this would be similar to the `before_each` option in  fastlane)

**Comment by maddes-b** [comment] 2017-01-05 19:31
@ffittschen 
Also had to learn by trying that the hooks are for the active renewal process only, and that pre/post-hook just allow the authenticator/installer to work (e.g. change www config, stop/start some services).

As a simple solution for --after-all (besides using a wrapper script in the cron tab) I touch a file when a certificate has been renewed and a separate hourly cron job will reload Apache or Postfix if necessary.
As renewals are done several days before the old certificate expires I find that an hourly cron job is fast enough. 
Additionally I'm missing that the renew-hook is executed also on the certonly command (see #3947). 

/etc/cron.d/certbot
```
0 */12 * * * root test -x /usr/local/bin/certbot-auto && perl -e 'sleep int(rand(3600))' && certbot-auto -q renew --renew-hook /usr/local/bin/letsencrypt_renew-hook.sh
```

/usr/local/bin/letsencrypt_renew-hook.sh
```
#!/bin/sh

#{
#  echo "--- $(date +%Y%m%d_%H%M%S) ${0}"
#  env | grep -e 'RENEWED'
#  echo "----------------------------------------"
#} >>/tmp/letsencrypt.renew-hook.txt


[ -z "${RENEWED_DOMAINS}" ] || {
  touch "${RENEWED_LINEAGE}/renewed"

  ### Workaround that CertBot does not save renew-hook in renewal configuration file
  ## Get first/main domain of certificate
  for DOMAIN in ${RENEWED_DOMAINS}
   do
    break
  done

  ## Act on main domain
  [ -z "${DOMAIN}" ] || {
    case "${DOMAIN}" in
     ### www.example1.net
     (www.example1.net)
      /usr/local/bin/letsencrypt_renew_www.example1.net.sh
      break
      ;;
     ### www.example2.com
     (www.example2.com)
      /usr/local/bin/letsencrypt_renew_www.example2.com.sh
      break
      ;;
    esac
  }
}

exit 0
```

/etc/cron.hourly/letsencrypt_reload_apache2 (important: no dots in script name)
```#!/bin/sh
BASEDIR='/etc/letsencrypt/live'
CERTDOMAINS='www.example1.net www.example2.com'

[ -d "${BASEDIR}" ] || exit 0
[ -x /usr/sbin/apache2 ] || exit 0
[ -n "${CERTDOMAINS}" ] || exit 0

### Check if Apache has to reload configuration incl. certificates
RELOAD=0
#
for DOMAIN in ${CERTDOMAINS}
 do
  CERTDIR="${BASEDIR}/${DOMAIN}"
  [ -f "${CERTDIR}/renewed" ] || continue
  RELOAD=1
  rm "${CERTDIR}/renewed"
done
#
[ "${RELOAD:-0}" -eq 0 ] || /bin/systemctl reload apache2

exit 0
```

**Closed** 2017-01-05 19:43 UTC
Labels: bug, has pr, renewal

**Comment by nonadz** [comment] 2017-01-09 13:35
Is this issue yet fixed?

**Comment by maddes-b** [comment] 2017-01-09 18:29
The current release is still 0.9.3, see https://dl.eff.org/certbot-auto
Development looks promising.

**Comment by bmw** [comment] 2017-01-09 18:30
We're releasing Certbot 0.10.0 this morning which includes this fix. Stay tuned!

**Comment by maddes-b** [comment] 2017-01-14 23:46
Note that the renewal conf files do not get updated automatically, e.g. via an re-issued certonly command.
You have to add the renew hook manually. Also add the new archive_dir setting for a complete 0.10.1 renewal definition.

Example:
```
# renew_before_expiry = 30 days
version = 0.10.1
archive_dir = /etc/letsencrypt/archive/yourdomain
cert = /etc/letsencrypt/live/yourdomain/cert.pem
...

# Options used in the renewal process
[renewalparams]
account = ...
renew_hook = /usr/local/bin/letsencrypt_deploy-hook_yourdomain.sh
```

**Comment by bmw** [comment] 2017-01-17 18:25
@maddes-b, testing on `master` (which should be basically the same as 0.10.1 at this point), renewal conf files are updated automatically when using `certonly` if a new certificate is actually issued. If your certificate is not actually due for renewal and you answer 1 to this question:
```
You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/example.org.conf)

What would you like to do?
-------------------------------------------------------------------------------
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel):
```
or have `--keep-until-expiring`, `--keep`, or `--reinstall` set on the command line or in a [configuration file](https://certbot.eff.org/docs/using.html#configuration-file), the renewal conf file will not be updated.

If you're still having this problem, I'd love a log of this issue. Feel free to redact e-mail/IP addresses and domain names as you feel appropriate.

**Comment by maddes-b** [comment] 2017-01-18 00:03
@bmw:
I assume this didn't work as my script uses 
> certbot-auto certonly **--noninteractive** --config "${CONFIGFILE}"

Already deleted the old certificates/keys and created new ones from scratch, so not able to reproduce again - sorry.
