### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by bjorn-l** [certbot/certbot#4302] opened 2017-03-06 01:27 UTC
Running certbot-0.11.1-2 from EPEL repository, on Centos-7 system.

Under the default location for the certificates, the private keys are world-readable:
`ls -l /etc/letsencrypt/archive/*/privkey*.pem`

It would appear that mode bits of 600 would be much better.

**Comment by bmw** [comment] 2017-03-07 02:19
This is a duplicate of #1473.

**Closed by bmw** 2017-03-07 02:19 UTC
