### ISSUE TITLE
Add command line option to trigger the deploy-hook without actually renewing the certificate for testing purposes

### ISSUE THREAD

**Issue by Flowdalic** [certbot/certbot#5658] opened 2018-03-03 18:53 UTC
It appears that it is not possible to trigger the deploy-hook without a full renewal. But when debugging the deploy-hook, this may trigger the rate limit.

It would be great if there where something like `--test-deploy-hook` so that

```
certbot --test-deploy-hook
```

runs the deploy hook without actually contacting the LE API attempting to renew the certificate .

**Comment by schoen** [comment] 2018-03-05 20:21
This would be a good solution for #5660.

However, it seems like many deploy hooks actually do something with the new certificate, so I'm not sure how well you can do a realistic test with the dry run, where there is no new certificate saved to disk. For example, if your deploy script does a `cp` or `scp` to copy the new certificate somewhere else, it's not going to be able to do that with a dry run. So you can probably only get a realistic test of a deploy hook that (1) exclusively uses our symlinks in `/etc/letsencrypt/live` (OK, that's reasonable behavior) or (2) just notifies someone about the renewal. Anyway, I suppose it all depends on which kind of deployment functionality the user wants to test.

**Comment by Flowdalic** [comment] 2018-03-06 07:12
> However, it seems like many deploy hooks actually do something with the new certificate, so I'm not sure how well you can do a realistic test with the dry run,

The deploy hook would simply re-deploy the non-renewed current certificate right (it is not really a dry run, as the deploy hook is actually executed). You would see if there are any errors in your (usually updated/changed) deploy hook.

> For example, if your deploy script does a cp or scp to copy the new certificate somewhere else, it's not going to be able to do that with a dry run.

Why not? It would probably copy the same file over, but you could see that something happened by looking at the destinations mtime.

**Comment by johnny-bit** [comment] 2018-03-11 15:10
> For example, if your deploy script does a cp or scp to copy the new certificate somewhere else, it's not going to be able to do that with a dry run

If certificate is not renewed, it's contents didn't change, so why not let cp/scp run? The only downside I'd see is if deploy-hook script restarts servers, but then if we're testing it shoundn't matter. 

I'm all for trigger testing deploy hooks.

**Comment by minfrin** [comment] 2018-03-23 16:49
Also ran into this one - I have to update a deploy hook, but have no way to test it.

Without an ability to do basic testing, certbot isn't something ready for production use :(

**Comment by andrew-vant** [comment] 2018-06-01 22:47
I'd like this, too.

**Comment by illz** [comment] 2018-08-06 21:33
How am I supposed to develop a deploy script with no way to test it without waiting 3 months for a renewal? Am I missing something? There must be a test mechanism...?

**Comment by aramhakobyan** [comment] 2018-09-05 14:48
+1

**Comment by urajio** [comment] 2018-10-03 08:29
It will be useful.

**Comment by m-o-e** [comment] 2018-12-17 03:42
I'm surprised this fundamental functionality is still missing.
Without a way to test deploy hooks, how are we supposed to use them?

Crossing fingers and "hoping" it will work as intended is
not an option in a production environment.

**Comment by gnorbsl** [comment] 2019-01-03 09:45
It's pretty annoying that this feature doesn't exist. The only option so far is to force a renew and test everything. The problem here is, that you get blocked after a few tries for pulling too many certs. Why implement a feature that you can't test?

**Comment by woj-tek** [comment] 2019-05-20 22:56
Just run into same problem so a huge 👍 

In my case I'm testing the hook from console and it works well, but for some reason certbot complains about syntax. Currently it's virtually impossible to figure out what's the problem (especially that it works outside of certboot scope)

**Comment by jmb12686** [comment] 2019-05-21 12:56
I am using certbot in a docker container, and it's difficult to accurately test the deploy hook script in isolation due to volume mount paths and user/group permissions w/in a container.  This feature request would be helpful for me as well to be able to one-off test the deploy hook script.

**Comment by m-o-e** [comment] 2019-05-21 13:03
How is it possible that is still is not fixed?
Does nobody at letsencrypt use certbot themselves?

In our org we have stopped using the hook mechanism because it's so brittle
and untestable. Instead we run a custom script after certbot, which is annoying
because it's an additional thing to maintain.

**Comment by adferrand** [comment] 2019-05-21 14:03
I do. As an integrator of certbot for my Docker solution `adferrand/letsencrypt-dns` and as a developer of certbot. And I did not need to have a special purpose flags for testing hooks (or other function by the way) because either:
* I use a locally deployed acme server (Boulder or Pebble) 
* or the staging server of LetsEncrypt where I never reached (so far) rates limits that are significantly relaxed compared to production. 

I think it is more generally the best suitable solution, as it uses the normal logic of Certbot to have the most significant user acceptance testing.

I am personally quite against the implementation of specific logic in certbot main workflow for exclusive test purpose only. Because this kind of logic is still code, and as any other code, could have defects on their own that could be biased to what will really happen on user side. 

In particular, I never use the dry run features of Certbot to develop or integrate, because if I think it can have some usage for a user, it is certainly not the case for a developer for the reasons I explained above.

In my opinion, the best action to do here to ease the development would be to improve documentation and usability of the example I described above (local acme, staging server). In fact for the local acme, some of the work I did on integration testing will hopefully help a lot to deploy quickly a suitable environment to develop and integrate around certbot.

**Comment by vith** [comment] 2019-05-21 14:19
As a user, here's the approximate sequence of events that happened for me:

1. Use certbot to acquire a cert
2. Manually copy the cert files where I need them, chown, etc
3. Look up the deploy-hook docs/example, write my deploy-hook
4. Look for the flag to test it, find that there isn't one
5. 90 days later, find out there's a problem when the first cert expired
6. Attempt to fix the script without testing again
7. 90 days later, find out it's still broken
8. repeat a few more times
9. find and thumbs-up this issue

**Comment by m-o-e** [comment] 2019-05-21 14:24
@adferrand 
Thanks for your detailed reply, much appreciated!

I do have to disagree with your conclusion, though.
While the above workflow sounds sensible for a certbot-developer,
it really seems inadequate for a mere _user_ of certbot.

All I want to do is:
* `apt install certbot`
* `certbot certonly` (request cert)
* `vim /etc/.../hook-script`
* `certbot --test-deploy-hook` to see it actually works!

Installing (and presumably configuring) a local acme server or switching
to a staging environment are **not** things I want to mess with.

Especially not when I'm making changes to an existing hook-script
in production, where a local test-server would presumably replace
all my precious certs with versions that are invalid on the public internet?

As pointed out by many others, I believe the simplest solution is
really the right one here: Just give us a way to dry-run the hooks
with the certs that are currently stored on disk.

**Comment by adferrand** [comment] 2019-05-21 15:57
Well, personally I test the scripts on a test environment, using `--staging` flag on certbot, verifying that it works as expected, before pushing to the production. Or, directly on the production, using `--staging`, `--config-dir`, `--work-dir` and `--logs-dir` to completely isolate the test execution of certbot, while keep using the production artifacts. Because staging server of LetsEncrypt is designed for that.

But I am not blocking on other approaches, and if someone is up to make a PR, I would gladly review it. 

I also invoke @bmw, @ohemorange, @joohoi and @sydneyli if you have an opinion about this issue.

**Comment by bmw** [comment] 2019-05-21 21:45
If adferrand or anyone else he pinged has opinions, I'd be interested to hear them, but I'd personally be in favor of adding a feature like this.

I think adferrand is completely right that differences in the code used to test deploy hooks and the code to run them on normal execution can cause issues, but I personally think the benefits of adding a feature like this outweighs this risk. Just like with `--dry-run` which we recommend for users . over `--staging` or a local ACME server, I think a command like this is a significant usability benefit.

With that said, the core Certbot team is stretched a bit thin at the moment so this probably isn't something we'd get to ourselves for a while. Someone else from the Certbot team may swoop in and convince me I'm wrong (and it wouldn't be the first time), but unless that happens, I agree with adferrand that we'd accept a well written PR for this.

If anyone wants to take this on, I'd strongly encourage you to get a +1 on the design upfront. For instance, I personally don't think this feature should be a command line flag but a new subcommand such as `deploy`, `deploy_hook`, `run_deploy_hook`, etc.

A couple other things to think about are which certificates does the subcommand act on and if a new `--deploy-hook` is provided on the command line with this command, is the renewal configuration file for the certificate updated so that deploy hook is used in the future potentially instead of the one that was initially used to obtain the certificate? In general, I'd suggest making this command as simple as possible to begin with. We can always add more functionality if there is demand for it.

**Comment by bmw** [comment] 2019-05-21 21:49
Also, while I don't think implementing this would be *too* bad, I'm removing the `easy-fix` label. I believe schoen thought the request was simply running deploy hooks with `--dry-run` (which I think we should not do).

**Comment by ohemorange** [comment] 2019-05-22 00:44
> Just like with --dry-run which we recommend for users over --staging or a local ACME server, I think a command like this is a significant usability benefit.

Why _do_ we recommend `--dry-run` over `--staging`? Perhaps we should switch to recommending `--staging`; that would circumvent this issue.

**Comment by adferrand** [comment] 2019-05-22 10:57
Reading again the whole thread, I am less convinced that this feature should be integrated than before.

First because implementing it correctly, so allowing to effectively trigger a deploy hook on an actual certificate, would be a development adding a significant complexity. 

If it was the only solution, I would say it does worth it, but it is not the case, required functionalities exist in certbot to reach this goal: staging server can be used, force renewal can be triggered for on-demand test renewal, certbot directories can be set to create an isolated environment.

And if it is about unit testing the deploy script on its own, it is just a matter of setting the env variables described in the deploy script doc, and calling `bash -c "$SCRIPT"`.

As @ohemorange, I think it is more a documentation problem, about what to use to test a deploy script with certbot.

**Comment by bmw** [comment] 2019-05-22 22:10
> Why _do_ we recommend `--dry-run` over `--staging`?

I think the biggest reason is `certbot renew --dry-run` allows you to test your production renewal configuration without overwriting your trusted certs with staging certs or carefully copying `/etc/letsencrypt` somewhere else (making sure to preserve things like symlinks) and using `--config-dir` in addition to `--staging`.

@adferrand, my problem with that proposal is none of those options seem particularly user friendly and seem to push the problem of differences between testing your deploy hook and really running it onto our users. I think we can do a better job minimizing these differences in Certbot itself.

**Comment by asdil12** [comment] 2020-01-31 21:39
As noone here seems to be interested in providing a nice way for the users to debug the deploy hook, I simply patched my certbot so that it would actually run the deploy hook even in dry-run mode (where certbot simulates a renewal of all certs).

```patch
--- /usr/lib/python3/dist-packages/certbot/certbot/hooks.py       2020-01-31 22:34:51.131707086 +0100
+++ /usr/lib/python3/dist-packages/certbot/certbot/hooks.py      2020-01-31 22:35:34.111627850 +0100
@@ -213,10 +213,6 @@
     :param bool dry_run: True iff Certbot is doing a dry run

     """
-    if dry_run:
-        logger.warning("Dry run: skipping deploy hook command: %s",
-                       command)
-        return

     os.environ["RENEWED_DOMAINS"] = " ".join(domains)
     os.environ["RENEWED_LINEAGE"] = lineage_path
```

**Comment by edisonspencer** [comment] 2020-04-24 10:11
+1 this one, this would be a nice feature to have. Since it would help me to understand why my certificate is not being run after a successful renewal.

**Comment by Lin-Buo-Ren** [comment] 2020-05-04 07:59
Same issue here, however `certbot --force-renewal` seems to be dealing nice for us.

**Comment by Flowdalic** [comment] 2020-08-30 15:58
> But I am not blocking on other approaches, and if someone is up to make a PR, I would gladly review it.

@adferrand Then may I ask you to review https://github.com/certbot/certbot/pull/8242/. Your feedback would be much appreciated.

**Comment by AlexAT** [comment] 2021-08-29 10:04
The lack of this feature is erm... confusing. That was the first thing I need: test my deploy hook. 
Okay, patching it by hand was not that hard, but having some option to run deploy hooks on dry run would definitely be helpful.

**Comment by m-o-e** [comment] 2021-08-29 11:18
Two alternatives for people who still struggle with this:

* [Lego](https://go-acme.github.io/lego/usage/cli/) - A small ACME client that just works™.
   If you know your way around shell-scripting this can replace certbot in minutes.

* [Caddy](https://caddyserver.com/) - Webserver/reverse proxy.
   If you don't need the certs on disk but just want a reverse proxy
   then Caddy can give you that with a 2-line config file:
   ```
   foobar.example.com
   reverse_proxy localhost:3000
   ```

**Comment by masoud919** [comment] 2021-09-09 14:21
What if we add a new hook that always runs regardless? E.g. `--always-hook`

**Comment by Flowdalic** [comment] 2021-09-13 10:10
> The lack of this feature is erm... confusing. That was the first thing I need: test my deploy hook.
> Okay, patching it by hand was not that hard, but having some option to run deploy hooks on dry run would definitely be helpful.

What makes me especially sad is that a solution was proposed in https://github.com/certbot/certbot/pull/8242 :/

**Comment by AlexAT** [comment] 2021-09-13 11:12
Yeah... it's a pain to look how this simple testing feature takes ages to be present at least somehow. 
Especially for #8242 - I don't see any problem in deploy hooks 'failing' when no certs are yet present. 
This option is purely debug option, and will only be present if one knows what and why he is doing.
Calling it --debug-dry-run-yes-run-deploy-hooks-I-know-what-I-am-doing and implenting is still viable.

**Comment by harridu** [comment] 2021-09-25 05:03
Maybe it would be sufficient for "certbot --dry-run renew --deploy-hook myscript" to print out a line telling how it **would have called** myscript, including environment variables and command line? All you need to know to run it manually.

**Comment by AlexAT** [comment] 2021-09-25 05:41
Nope, running it manually is anyone can do. To be honest here's no point in dry-run if it cannot do all the mechanics normal run does. But that seems to be pretty much typical with python scripts, too much fuss, to small function. In the end, I've written my own app for ACME, so won't participate in the discussion anymore.

**Comment by Zerowalker** [comment] 2022-10-26 09:46
Would like this as well.
I need to use fuse mounts and as i don't know how it's run or what user it's run as etc it's hard to know how it will work out.

**Comment by ohemorange** [comment] 2023-02-08 21:46
This was added in #9355!

```
--run-deploy-hooks    When performing a test run using `--dry-run` or `reconfigure`, run any applicable deploy hooks.
                        This includes hooks set on the command line, saved in the certificate's renewal configuration
                        file, or present in the renewal-hooks directory. To exclude direcory hooks, use --no-directory-
                        hooks. The hook(s) will only be run if the dry run succeeds, and will use the current active
                        certificate, not the temporary test certificate acquired during the dry run. This flag is
                        recommended when modifying the deploy hook using `reconfigure`. (default: False)
```

Please do comment if there are additional needs not met this implementation. (And yes, I see the typo, it will be fixed.)

**Closed by ohemorange** 2023-02-08 21:46 UTC
Labels: feature request, area: hooks
