### ISSUE TITLE
renewal does not renew revoked certificates

### ISSUE THREAD

**Issue by uladkasach** [certbot/certbot#5343] opened 2017-12-20 16:29 UTC
## My operating system is (include version):
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

    $ sudo apt-get update
    $ sudo apt-get install software-properties-common
    $ sudo add-apt-repository ppa:certbot/certbot
    $ sudo apt-get update
    $ sudo apt-get install python-certbot-nginx 

## I ran this command and it produced this output:
First I revoked the certificate
```
$ certbot revoke --cert-path /etc/letsencrypt/live/cert.eval.ohie.org/fullchain.pem 
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Would you like to delete the cert(s) you just revoked?
-------------------------------------------------------------------------------
(Y)es (recommended)/(N)o: n

-------------------------------------------------------------------------------
Congratulations! You have successfully revoked the certificate that was located
at /etc/letsencrypt/live/cert.eval.ohie.org/fullchain.pem

-------------------------------------------------------------------------------
```
And then I attempted to renew the certificate, now that the existing one is revoked.
```
$ certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/cert.eval.ohie.org.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/cert.eval.ohie.org/fullchain.pem (skipped)
No renewals were attempted.
No hooks were run.
-------------------------------------------------------------------------------
```

## Certbot's behavior differed from what I expected because:
I would expect that certbot would renew a revoked certificate; especially so, considering [in the documentation](https://certbot.eff.org/docs/using.html#revoking-certificates) it is stated that:

> If you don’t use delete to remove the certificate completely, it will be renewed automatically at the next renewal event.

How can I make `certbot renew` automatically renew the revoked certificate? Do I have to enforce that I force renew after revocation? i.e., `certbot renew --cert-name __name__ --force renewal` after a revocation?

**Comment by SwartzCr** [comment] 2017-12-20 21:23
Certbot is supposed to renew revoked certificates
Are you sure that it was in the renewal window? It'll only renew it if it's within 30 days of expiry.
--force-renew would work, but you wouldn't want to run it regularly since it will cause issues with rate limiting, though you could run it once now without specifying certname and see if the revoked certificate comes up in the renewal.
Alternately you can examine the conf file for that cert and see when it's set to renew.

**Comment by bmw** [comment] 2017-12-21 20:20
In theory, Certbot should renew a revoked certificate even if the certificate is not close to expiration.

While not immediately clear at first glance, I think this is a duplicate of #1028. Some of the discussion there is a little out of date, but the general problem is our code that checks if a cert needs to be renewed doesn't check OCSP status and determine the cert needs to be renewed if it's revoked.

Since I think this is a duplicate, I'm closing this issue but please reopen if you think I'm missing something.

**Closed by bmw** 2017-12-21 20:20 UTC
Labels: area: renewal, area: ui / ux, debugging
