### ISSUE TITLE
nginx plugin not properly handling directives inherited from outside of the server block

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4999] opened 2017-08-07 18:14 UTC
Reported by @src386 [here](https://github.com/certbot/certbot/issues/4132#issuecomment-320610552):

In an nginx config, if you specify `server_names_hash_bucket_size` outside of a `server` block, we'll fail the challenge. This is because we only search for the directive in the specific server block rather than checking if it was inherited from elsewhere in the config.

While we could do something like removing the directive if we fail to restart nginx after adding it and trying again, the correct solution would be a dramatic change in our parser to be able to properly handle inherited directives.

cc @ohemorange

**Comment by ohemorange** [comment] 2017-12-18 20:35
This is a duplicate of #583.

**Closed by ohemorange** 2017-12-18 20:35 UTC
Labels: area: nginx, bug
