### ISSUE TITLE
LetsEncrypt's Apache plugin uses dummy placeholders in the generated apache conf 

### ISSUE THREAD

**Issue by clarkeandrew** [certbot/certbot#1328] opened 2015-11-04 14:35 UTC
When using letsencrypt-auto, the generated apache vhost file is created correctly but the location of the certs is not specified in the file : 

i.e.

```
SSLCertificateFile insert_cert_file_path
SSLCertificateKeyFile insert_key_file_path
```

It looks like this is quite intentional in the code but im not sure why (https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-apache/letsencrypt_apache/configurator.py#L579)

Furthermore just specifying the cert and key doesn't appear to be enough (I got browser security errors with this setup). Using the SSLCertificateChainFile directive fixes this : 

```
SLCertificateFile /etc/letsencrypt/live/domain.com/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/domain.com/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/domain.com/fullchain.pem
```

**Comment by clarkeandrew** [comment] 2015-11-04 15:20
I realise now that this may be the default behaviour for the 'auth' mode of letsencrypt. Is this the case?

**Comment by Cactucs** [comment] 2015-11-17 21:08
The source is here: https://github.com/letsencrypt/letsencrypt/blob/510da48263a4f19caa24495af6d318840eff9f29/letsencrypt-apache/letsencrypt_apache/configurator.py#L670-L673

**Comment by pde** [comment] 2015-11-21 03:44
I suspect #1582 will fix this; if anyone is motivated to check that, let us know!

**Comment by romanseidl** [comment] 2016-01-16 16:40
I have the same error on a current master or on 0.2.0. Hasn't that been fixed and merged into master?

**Comment by mfairchild365** [comment] 2016-04-04 14:02
I am having this issue too.

**Comment by mfairchild365** [comment] 2016-04-04 14:31
Ah, it looks like the problem was that `mod_ssl` was not enabled. I was able to install it with the command `sudo a2enmod ssl` and everything started to work as expected.

**Comment by joohoi** [comment] 2016-04-04 15:13
@mfairchild365 What distribution are you running? LE should actually check that mod_ssl is enabled when run on Ubuntu / Debian.

**Comment by mfairchild365** [comment] 2016-04-04 17:05
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```
And for Apache: `Apache/2.4.7 (Ubuntu)`

**Comment by joohoi** [comment] 2016-04-05 05:55
I'll have to run some tests and try to reproduce the problem, but it certainly should be supported.

**Comment by iarp** [comment] 2016-05-05 01:52
I've just run into this too, apache/2.4.7. The only thing I do after apache2 installation is `a2dismod mpm_event` so that I can then install `apache2-mpm-itk`. If I don't disable the mpm_event mod the mpm-itk fails to install until it is disabled.

> 2016-05-05 01:29:06,671:INFO:letsencrypt_apache.configurator:Created an SSL vhost at /etc/apache2/sites-enabled/000-default-le-ssl.conf
2016-05-05 01:29:06,888:INFO:letsencrypt_apache.configurator:Enabled Apache socache_shmcb module
2016-05-05 01:29:07,067:INFO:letsencrypt_apache.configurator:Enabled Apache ssl module
2016-05-05 01:29:07,153:WARNING:letsencrypt_apache.parser:Error in checking parameter list: AH00526: Syntax error on line 33 of /etc/apache2/sites-enabled/000-default-le-ssl.conf:
SSLCertificateFile: file '/etc/apache2/insert_cert_file_path' does not exist or is empty

>2016-05-05 01:29:07,179:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 360, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 219, in deploy_cert
    self.prepare_server_https("443")
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 619, in prepare_server_https
    self.prepare_https_modules(temp)
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 676, in prepare_https_modules
    self.enable_mod("ssl", temp=temp)
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1440, in enable_mod
    self.parser.update_runtime_variables()
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/parser.py", line 107, in update_runtime_variables
    stdout = self._get_runtime_cfg()
  File "/home/myusername/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/parser.py", line 151, in _get_runtime_cfg
    "Apache is unable to check whether or not the module is "
MisconfigurationError: Apache is unable to check whether or not the module is loaded because Apache is misconfigured.

**Comment by ruant** [comment] 2016-05-24 11:28
Running:

    a2enmod ssl

before letsencrypt solved the issue for me too.
(Maybe a service apache2 restart is required too? Not sure about this tho)

**Comment by MikeLund** [comment] 2017-02-10 13:29
This bug still exists when using `letsencrypt --apache`.

`a2enmod ssl` and rerunning LE fixes it, but would having something like `a2query -m ssl` in the script (to see if the module is loaded in the first place) be a good improvement?

**Comment by joohoi** [comment] 2017-02-10 13:58
We should be able to detect it correctly. Running `letsencrypt` makes me wonder if you are running an old version, perhaps from Ubuntu Xenial repository (making wild guesses here).

**Comment by iarp** [comment] 2017-02-10 14:45
I've always pulled letsencrypt from the repo whenever setting up on a new system. My original comment is almost a year ago now and we've switched to nginx which hasn't caused us issues so I can't speak for it now.

**Comment by MikeLund** [comment] 2017-02-13 09:07
@joohoi Oh yeah, I am on Xenial. So `python-letsencrypt-apache` on 14.04 LTS is a bit out of date then? Is there some other repository or PPA that should be used & would it be useful if I added it to the docs on https://certbot.eff.org/#ubuntuxenial-apache ?  Thanks!

**Comment by bmw** [comment] 2017-03-01 00:18
@MikeLund, despite being an older version, the OS packages are still the preferred method (see #3538 for discussion on this). If you want to run a newer version of the client though, I'd recommend [certbot-auto](https://certbot.eff.org/#ubuntuother-other).

**Comment by miohtama** [comment] 2017-03-27 11:33
Xenial having an older version means that the default Ubuntu + Apache instructions https://certbot.eff.org/#ubuntuxenial-apache fail

**Comment by bmw** [comment] 2017-04-07 20:56
I was able to repro this using `master` on Ubuntu 16.04. Steps to reproduce starting with the default Apache config:

```
sudo a2dissite 000-default.conf
sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled
sudo rm /etc/apache2/sites-available/*
sudo certbot --apache
```

**Comment by 00cpxxx** [comment] 2017-09-04 22:07
Still reproducible as of today, as expected previously enabling mod_ssl fixes/hides the issue.

certbot 0.17.0

**Closed** 2017-09-25 19:03 UTC
Labels: area: apache, has pr
