### ISSUE TITLE
Creating Virtual Environment - "No module named warnings" on Ubuntu 10.04.4

### ISSUE THREAD

**Issue by weepingwitch** [certbot/certbot#2944] opened 2016-05-08 16:43 UTC
when running ./letsencrypt-auto --help 

i get the following error after "Creating virtual environment..."

Traceback (most recent call last):

  File "/home/USERNAME/.local/share/letsencrypt/lib/python2.7/site.py", line 67, in <module>
    import os

  File "/home/USERNAME/.local/share/letsencrypt/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path

  File "/home/USERNAME/.local/share/letsencrypt/lib/python2.7/posixpath.py", line 17, in <module>
    import warnings

ImportError: No module named warnings

**Comment by bmw** [comment] 2016-05-09 20:57
Hm. `warnings` has been part of the Python standard library since Python 2.1. Which OS and Python version are you using?. I'm assuming if you do this you get the error as well:
```
python -c "import warnings"
```
If so, this suggests a problem with your Python installation.

**Comment by Aramgutang** [comment] 2016-08-16 06:18
I've run into the same problem, it is caused by attempting to create a Python 2.7 virtual environment using a version of vitualenv from the Python 2.6 era. This is mostly caused by the logic on [line 152 of certbot-auto](https://github.com/certbot/certbot/blob/ffc1874854fde7f61870780ce8684af2978b2434/certbot-auto#L132), which picks which python to pass to the `virtualenv` command's `--python` parameter:

    ...
    for LE_PYTHON in "$LE_PYTHON" python2.7 python27 python2 python; do
    ...

In an old distro such as Ubuntu Lucid, where the system Python is at 2.6 and virtualenv is at 1.4.5, with Python 2.7 installed alongside via the `python27` package (or from source via `make altinstall` in my case), this will result in invoking virtualenv 1.4.5 with `--python python2.7`, which will reproducibly throw the above "no module named warnings" error.

Not sure if this is a specific (known?) bug for virtualenv 1.4.5, and why that particular error is thrown, but that's what it is.

Not sure of the best solution here: changing the order on the line quoted above to prefer `python` over `python2.7` would fix it on old distros, but would break on newer distros where system Python is 3.x. 

Another option would be to perform a similar lookup for the best `virtualenv` command to use, preferring `virtualenv-2.7` or such, but that depends on such things existing and being installed, and in the case of Ubuntu Lucid, there doesn't appear to be `python27-virtualenv` package.

On the user end, this can be solved by either running certbot-auto with `env LE_PYTHON=python` (which would create the letsencrypt virtualenv with Python 2.6) or upgrading the system virtualenv (which would create the virtualenv with 2.7), so users can simply be told to do one of those in the documentation somewhere.

In my particular case, the former option resulted in segfaults thrown by the cryptography-python2.6 combo, but the latter worked just fine.

**Comment by LezLee** [comment] 2017-01-05 13:51
Take a look at my answer to this post in gis stack exchange. Hope it helps
http://gis.stackexchange.com/questions/90656/mapfish-installtion-problem/223394#223394

**Comment by bmw** [comment] 2019-01-03 22:48
Warnings is part of the Python standard library and this hasn't seen any activity since 2017. For this reason, I'm closing this issue. If you continue to have problems that you think can/should be fixed by Certbot, please comment or open a new issue.

**Closed by bmw** 2019-01-03 22:48 UTC
Labels: area: certbot-auto, area: pkging, more-info
