### ISSUE TITLE
Url not found: https://www.piwheels.hostedpi.com/simple/zope.components/argparse/

### ISSUE THREAD

**Issue by Arrappathor** [certbot/certbot#5330] opened 2017-12-15 17:24 UTC
## My operating system is (include version):
Raspbian Stretch (Upgraded from Jessie)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
i guess pip (it was before certbot was packaged in debian)

## I ran this command and it produced this output:
./letsencrypt-auto renew as root-cron

(Attention: logfile ist upside-down)

You may also find some support resources at https://certbot.eff.org/support/ .
for possible solutions.
Consult https://certbot.eff.org/docs/install.html#problems-with-python-virtual-environment

output.
We were not be able to guess the right solution from your pip 

Certbot has problem setting up the virtual environment.

=====================================================
HTTPError: 404 Client Error: Not Found for url: https://www.piwheels.hostedpi.com/simple/zope.components/argparse/
    raise HTTPError(http_error_msg, response=self)
  File "/opt/eff.org/certbot/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    resp.raise_for_status()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/index.py", line 795, in get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    page = self._get_page(location)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    for page in self._get_pages(url_locations, project_name):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    all_candidates = self.find_all_candidates(req.name)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    self.link = finder.find_requirement(self, upgrade)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    require_hashes
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    requirement_set.prepare_files(finder)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    status = self.run(options, args)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
Traceback (most recent call last):
Exception:
Collecting argparse==1.4.0 (from -r /tmp/tmp.IPWCqAQTjA/letsencrypt-auto-requirements.txt (line 11))
=====================================================
pip prints the following errors: 

Had a problem while installing Python packages.
Installing Python packages...
Creating virtual environment...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
virtualenv is already the newest version (15.1.0+ds-1).
python-virtualenv is already the newest version (15.1.0+ds-1).
python-dev is already the newest version (2.7.13-2).
python is already the newest version (2.7.13-2).
openssl is already the newest version (1.1.0f-3+deb9u1).
libssl-dev is already the newest version (1.1.0f-3+deb9u1).
libffi-dev is already the newest version (3.2.1-6).
libaugeas0 is already the newest version (1.8.0-1+deb9u1).
gcc is already the newest version (4:6.3.0-4).
ca-certificates is already the newest version (20161130+nmu1).
augeas-lenses is already the newest version (1.8.0-1+deb9u1).
Reading state information...
Building dependency tree...
Reading package lists...
Reading package lists...
Fetched 11.7 MB in 19s (606 kB/s)
Get:3 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages [11.7 MB]
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Get:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease [15.0 kB]
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)

## Certbot's behavior differed from what I expected because:
It upgraded from 0.18.2 to 0.19 and then...

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
automatic via certbot
 
I kind of solved the problem by downgrading to certbot 0.10.2 from Raspbian-repository stretch/stable, but i thought i could be of interest. 

Thank you very much for your great work!!!

**Comment by bmw** [comment] 2017-12-15 17:39
I think the actual problem might be being masked here. Do you have a file like the one suggested [here](https://github.com/certbot/certbot/issues/5138#issuecomment-333391771) adding https://www.piwheels.hostedpi.com/simple/zope.components as an URL for pip? My understanding is the need to do this has been resolved and would explain why `pip` is looking for `argparse` at that location. I would recommend removing this setting if you have it and trying again.

**Comment by Arrappathor** [comment] 2017-12-15 17:52
Hallo and thank you.
I do have changed /etc/pip.conf (and took the workaround) as i had the [issue](https://github.com/certbot/certbot/issues/5138#issuecomment-333391771) about the same time others had it. It then worked.
Also: the hosted-pi-url ist https://www.piwheels.hostedpi.com/simple/zope.component without the S at the end, whereas my pi was looking for /zope.componentS

**Comment by bmw** [comment] 2017-12-15 19:29
While I'm glad the workaround there was successful, it's at least partially the cause of the error you're seeing now. `pip` is looking for `argparse` at that location because you told `pip` that URL was another package repository. I would expect `pip` to fall back to checking another location as well (unless you put `index-url` instead of `extra-index-url`), but `pip` should stop looking for `argparse` there if you remove that line from your `pip` configuration which should no longer be needed anyway based on my reading of bennuttall/piwheels#20.

I think it's at least worth testing without the prior workaround which should either resolve the problem or give us more information.

**Comment by Arrappathor** [comment] 2017-12-15 19:52
The problem is: i can't reproduce the error since i downgraded to 0.10.2 (just to find a solution for myself), because as it worked fine, i happily deleted /opt/letsencrypt thinking i would no longer need it (and also was glad to have an installation via apt, as i wrote at the end of my first post).... so: hm. Sorry? But thanks.

**Comment by bmw** [comment] 2017-12-15 19:56
OK. Happy to hear the issue is resolved. With that in mind, I'm closing this for now but if you or others encounter the problem in the future I'll reopen.

(By the way, there is a newer version of Certbot available in stretch-backports if you'd like it.)

**Closed by bmw** 2017-12-15 19:56 UTC
Labels: area: certbot-auto, more-info
