### ISSUE TITLE
Certbot does not like long domain names: Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

### ISSUE THREAD

**Issue by Kohera** [certbot/certbot#3246] opened 2016-07-06 16:55 UTC
How to increase the maximum allowed length of the domains?

Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

2016-07-06 16:48:46,480:DEBUG:certbot.main:Picked account: <Account(262cd9df7f75cc99d945c8174d40e606)>
2016-07-06 16:48:46,481:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-07-06 16:48:46,484:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-07-06 16:48:46,728:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-07-06 16:48:46,729:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Boulder-Request-Id': '_8Od3luBekfSu_q-Ox-5IadUZ9GqHPXgXig7UBsX52k', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 06 Jul 2016 16:48:46 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '6iSj8_Z4WYKZdWl2TY6_rXik3u2H7J1h63HBPsAvddg'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-07-06 16:48:46,729:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Boulder-Request-Id': '_8Od3luBekfSu_q-Ox-5IadUZ9GqHPXgXig7UBsX52k', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 06 Jul 2016 16:48:46 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '6iSj8_Z4WYKZdWl2TY6_rXik3u2H7J1h63HBPsAvddg'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-07-06 16:48:46,730:DEBUG:root:Requesting fresh nonce
2016-07-06 16:48:46,730:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2016-07-06 16:48:46,844:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2016-07-06 16:48:46,844:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': '8Q4D60-8iZIh-45l6mWUwZqjjcW1NJs50prmsbXawQE', 'Expires': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'xGt9FkCYZVhOf3kYM7DKdLtGxM8drU8Od8nTNJhk2d8'}. Content: ''
2016-07-06 16:48:46,844:DEBUG:acme.client:Storing nonce: '\xc4k}\x16@\x98eXN\x7fy\x183\xb0\xcat\xbbF\xc4\xcf\x1d\xadO\x0ew\xc9\xd34\x98d\xd9\xdf'
2016-07-06 16:48:46,844:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2016-07-06 16:48:46,844:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "[REDACTEDLONGDOMAINNAME]"}, "resource": "new-authz"}
2016-07-06 16:48:46,845:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, jwk=None, x5t=None, x5tS256=None, cty=None, x5u=None, typ=None, alg=None, jku=None
2016-07-06 16:48:46,848:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, nonce=None, x5tS256=None, cty=None, x5t=None, x5u=None, typ=None, jku=None
2016-07-06 16:48:46,848:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "9J2kq0-lxv_-utEXpKc2a9R0HmyCLDZ_eLCWTGV98Yuk1gi8a3BgWWDEgdImprOfXecrFDcBL8AiYeH0Qh_9uHaAJYzclnz4afdLsG3zdV9IU8RLsNpM81occZZ3KKEoN78BZQoV13ny595ostO-itRd8355zZROARlv8jlRMk18qj4RV4rhnwHijXR2eGqxZuRPv9DMUNsbArYBn3p-SXYzgAi9OLoqCcrwpPqu0LNB9A9diwFzezw5qRSA83zBh4_vaN0cHBEJYOj_WdyoHFxHi-3ddhVh1KlvQwhHIyauG4xe-hWcFqn9Y7SVt0Jaoql7DL72VP39s20dekb6ow"}}, "protected": "eyJub25jZSI6ICJ4R3Q5RmtDWVpWaE9mM2tZTTdES2RMdEd4TThkclU4T2Q4blROSmhrMmQ4In0", "payload": "eyKpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJweWUxc2Z1dW0ydWZqYXE5MXI3NWR6YWFvandmdXRuNGlyNTUya3g2eGl0cTMya2EwZGliZXRycW5oeGo5Y2UueHl6In0sICJyZXNvdXJjZSI6ICJuZXctYXV0aHoifQ", "signature": "OFkljSi39ZlQ5Ol15ZZt4iGXx5D5rMTjhO-nsnLAr-CeHfdwl_KDt6vot1EGhFWzGnpEpK3qqwZR6cPVbh4WJewXoWZp3or-SE568MEP3XVi7L6S0o2JAztHw5I0fSKtJxu9gYJ-T03B8nOttK9yFzlNfKIdpu77JJuUpFBf0Z93P8p5eKUwkQrhy8l9Bt6fkXuxvh07BjahAsEX1o2zE-xkUk6AuHBNf9u9y9hlGRLqffitMSIURNkMJV7kqEBUdkiZzDJROiQF9abqd6xJwfQh9IbFKTT7YfpOEOYcWG_pmU1srh3Aw-GeNMZe226EKt8_qtDiRuS9vxpzF5XeTw"}'}
2016-07-06 16:48:46,953:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1052
2016-07-06 16:48:46,953:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '1052', 'Expires': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Boulder-Request-Id': '1NpBvehchj2SYjj4MWhoZ_HOj3VjxR5-aURH6iQIPkE', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98', 'Pragma': 'no-cache', 'Boulder-Requester': '2510920', 'Date': 'Wed, 06 Jul 2016 16:48:46 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '4pqOE7yDZyK6w68PHFcVMKjo6P_Bne8QwxJJb0gF1_4'}. Content: '{\n  "identifier": {\n    "type": "dns",\n    "value": "[REDACTEDDOMAINNAME]"\n  },\n  "status": "pending",\n  "expires": "2016-07-13T16:48:46.916200162Z",\n  "challenges": [\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n      "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA"\n    },\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519285",\n      "token": "XzLZyEcbpHVCE4BOh7VW6mlokNciVt0tWX3nWc87BpI"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286",\n      "token": "sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      1\n    ],\n    [\n      0\n    ]\n  ]\n}'
2016-07-06 16:48:46,954:DEBUG:acme.client:Storing nonce: '\xe2\x9a\x8e\x13\xbc\x83g"\xba\xc3\xaf\x0f\x1cW\x150\xa8\xe8\xe8\xff\xc1\x9d\xef\x10\xc3\x12IoH\x05\xd7\xfe'
2016-07-06 16:48:46,954:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '1052', 'Expires': 'Wed, 06 Jul 2016 16:48:46 GMT', 'Boulder-Request-Id': '1NpBvehchj2SYjj4MWhoZ_HOj3VjxR5-aURH6iQIPkE', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98', 'Pragma': 'no-cache', 'Boulder-Requester': '2510920', 'Date': 'Wed, 06 Jul 2016 16:48:46 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '4pqOE7yDZyK6w68PHFcVMKjo6P_Bne8QwxJJb0gF1_4'}): '{\n  "identifier": {\n    "type": "dns",\n    "value": "[REDACTEDDOMAINNAME]"\n  },\n  "status": "pending",\n  "expires": "2016-07-13T16:48:46.916200162Z",\n  "challenges": [\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n      "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA"\n    },\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519285",\n      "token": "XzLZyEcbpHVCE4BOh7VW6mlokNciVt0tWX3nWc87BpI"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286",\n      "token": "sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      1\n    ],\n    [\n      0\n    ]\n  ]\n}'
2016-07-06 16:48:46,954:DEBUG:acme.challenges:dns-01 was not recognized, full message: {u'status': u'pending', u'token': u'sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8', u'type': u'dns-01', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286'}
2016-07-06 16:48:46,955:INFO:certbot.auth_handler:Performing the following challenges:
2016-07-06 16:48:46,955:INFO:certbot.auth_handler:tls-sni-01 challenge for [REDACTEDLONGDOMAINNAME]
2016-07-06 16:48:46,994:INFO:certbot_apache.configurator:Enabled Apache socache_shmcb module
2016-07-06 16:48:47,060:INFO:certbot_apache.configurator:Enabled Apache ssl module
2016-07-06 16:48:47,249:DEBUG:certbot_apache.tls_sni_01:Adding Include /etc/apache2/le_tls_sni_01_cert_challenge.conf to /files/etc/apache2/apache2.conf
2016-07-06 16:48:47,251:DEBUG:certbot_apache.tls_sni_01:writing a config file with text:
 <IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName d52e0e7b94e26826e761597f31fb694b.0ee0a7c1a8891fc65d4da2e09a4cd160.acme.invalid
    UseCanonicalName on
    SSLStrictSNIVHostCheck on

    LimitRequestBody 1048576

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /var/lib/letsencrypt/L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.pem

    DocumentRoot /var/lib/letsencrypt/tls_sni_01_page/
</VirtualHost>

</IfModule>

2016-07-06 16:48:47,271:DEBUG:certbot.reverter:Creating backup of /etc/apache2/apache2.conf
2016-07-06 16:48:50,383:INFO:certbot.auth_handler:Waiting for verification...
2016-07-06 16:48:50,383:DEBUG:acme.client:Serialized JSON: {"keyAuthorization": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.NOMOF65SuTEg_d5KUv2ebipDDBTaQxIs-TERLkA2OMQ", "type": "tls-sni-01", "resource": "challenge"}
2016-07-06 16:48:50,385:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, jwk=None, x5t=None, x5tS256=None, cty=None, x5u=None, typ=None, alg=None, jku=None
2016-07-06 16:48:50,387:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, nonce=None, x5tS256=None, cty=None, x5t=None, x5u=None, typ=None, jku=None
2016-07-06 16:48:50,387:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "9J2kq0-lxv_-uTEKpKc2a9R0HmyCLDZ_eLCWTGV98Yuk1gi8a3BgWWDEgdImprOfXecrFDcBL8AiYeH0Qh_9uHaAJYzclnz4afdLsG3zdV9IU8RLsNpM81occZZ3KKEoN78BZQoV13ny595ostO-itRd8355zZROARlv8jlRMk18qj4RV4rhnwHijXR2eGqxZuRPv9DMUNsbArYBn3p-SXYzgAi9OLoqCcrwpPqu0LNB9A9diwFzezw5qRSA83zBh4_vaN0cHBEJYOj_WdyoHFxHi-3ddhWh1KlvQwhHIyauG4xe-hWcFqn9Y7SVt0Jaoql7DL72VP39s20dekb6ow"}}, "protected": "eyJub25jZSI6ICI0cHFPRTd5RFp5SzZ3NjhQSEZjVk1Lam82UF9CbmU4UXd4SkpiMGdGMV80In0", "payload": "eyJrVXlBdXRob3JpemF0aW9uIjogIkw1eXNueUJyRzZ0T0RuQjY4dDdDc2ZianVud3Y0Q1JSQ25uZUtiREVPWEEuTk9NT0Y2NVN1VEVnX2Q1S1V2MmViaXBEREJUYVF4SXMtVEVSTGtBMk9NUSIsICJ0eXBlIjogInRscy1zbmktMDEiLCAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIn0", "signature": "eDoBbnjDF_4gBG4saIFSrF5OQaJJg12r0z10wwaB62VBiYgHgTXEAjffQZ17b4rcb1R5BYp__qTC8hMEqc8VdXQYxClyh8q8_1lhK1aV5A0gfrqmRvAPhgmishC7JtNELS8tjJB_pM-FOXdKkzo2eq_9rpDIELjj-SH2szHOuzqKObkfUL0YIpU3wExpjpQP_EVhR6rQT2D7mwxDH6bAAj8PDLFZV62Fb1xMCTuqmTqXTOQUNtbphb0LCLrsya5VSfcelGQdtD2IYQYfS9MVfgMzDT55MKRoLbz0-0kGXocWn5JHunGFSuJR-Q2ncCpbHTPda2wV4qXFg9mEutasZw"}'}
2016-07-06 16:48:50,561:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284 HTTP/1.1" 202 338
2016-07-06 16:48:50,562:DEBUG:root:Received <Response [202]>. Headers: {'Content-Length': '338', 'Boulder-Request-Id': '0mAMOYL52PTWuogGd1JoONgFBXTyX4Uc7kdSopOsht4', 'Expires': 'Wed, 06 Jul 2016 16:48:50 GMT', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98>;rel="up"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284', 'Pragma': 'no-cache', 'Boulder-Requester': '2510920', 'Date': 'Wed, 06 Jul 2016 16:48:50 GMT', 'Content-Type': 'application/json', 'Replay-Nonce': 'JARMZatzYR_U3SbJCKYa_DdqKVE7_DaBlJoWQ4CJ0Ww'}. Content: '{\n  "type": "tls-sni-01",\n  "status": "pending",\n  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n  "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA",\n  "keyAuthorization": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.NOMOF65SuTEg_d5KUv2ebipDDBTaQxIs-TERLkA2OMQ"\n}'
2016-07-06 16:48:50,562:DEBUG:acme.client:Storing nonce: '$\x04Le\xabsa\x1f\xd4\xdd&\xc9\x08\xa6\x1a\xfc7j)Q;\xfc6\x81\x94\x9a\x16C\x80\x89\xd1l'
2016-07-06 16:48:50,562:DEBUG:acme.client:Received response <Response [202]> (headers: {'Content-Length': '338', 'Boulder-Request-Id': '0mAMOYL52PTWuogGd1JoONgFBXTyX4Uc7kdSopOsht4', 'Expires': 'Wed, 06 Jul 2016 16:48:50 GMT', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98>;rel="up"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284', 'Pragma': 'no-cache', 'Boulder-Requester': '2510920', 'Date': 'Wed, 06 Jul 2016 16:48:50 GMT', 'Content-Type': 'application/json', 'Replay-Nonce': 'JARMZatzYR_U3SbJCKYa_DdqKVE7_DaBlJoWQ4CJ0Ww'}): '{\n  "type": "tls-sni-01",\n  "status": "pending",\n  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n  "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA",\n  "keyAuthorization": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.NOMOF65SuTEg_d5KUv2ebipDDBTaQxIs-TERLkA2OMQ"\n}'
2016-07-06 16:48:53,565:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98. args: (), kwargs: {}
2016-07-06 16:48:53,647:DEBUG:requests.packages.urllib3.connectionpool:"GET /acme/authz/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98 HTTP/1.1" 200 1447
2016-07-06 16:48:53,648:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '1447', 'Expires': 'Wed, 06 Jul 2016 16:48:53 GMT', 'Boulder-Request-Id': 'Xae4GJWMLt9YyPOzpUJQcxX9ZXJhuNMgNSb6Sb5bgl0', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 06 Jul 2016 16:48:53 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'hLr8xt8TCLCjrMq6YJs5MKLcK4t-qIShTRUB5C93epo'}. Content: '{\n  "identifier": {\n    "type": "dns",\n    "value": "[REDACTEDDOMAINNAME]"\n  },\n  "status": "valid",\n  "expires": "2017-05-02T16:48:50Z",\n  "challenges": [\n    {\n      "type": "tls-sni-01",\n      "status": "valid",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n      "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA",\n      "keyAuthorization": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.NOMOF65SuTEg_d5KUv2ebipDDBTaQxIs-TERLkA2OMQ",\n      "validationRecord": [\n        {\n          "hostname": "[REDACTEDLONGDOMAINNAME]",\n          "port": "443",\n          "addressesResolved": [\n            "[REDACTEDIPADDRESS]"\n          ],\n          "addressUsed": "[REDACTEDIPADDRESS]"\n        }\n      ]\n    },\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519285",\n      "token": "XzLZyEcbpHVCE4BOh7VW6mlokNciVt0tWX3nWc87BpI"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286",\n      "token": "sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      1\n    ],\n    [\n      0\n    ]\n  ]\n}'
2016-07-06 16:48:53,648:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '1447', 'Expires': 'Wed, 06 Jul 2016 16:48:53 GMT', 'Boulder-Request-Id': 'Xae4GJWMLt9YyPOzpUJQcxX9ZXJhuNMgNSb6Sb5bgl0', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 06 Jul 2016 16:48:53 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'hLr8xt8TCLCjrMq6YJs5MKLcK4t-qIShTRUB5C93epo'}): '{\n  "identifier": {\n    "type": "dns",\n    "value": "[REDACTEDLONGDOMAINNAME]"\n  },\n  "status": "valid",\n  "expires": "2017-05-02T16:48:50Z",\n  "challenges": [\n    {\n      "type": "tls-sni-01",\n      "status": "valid",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519284",\n      "token": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA",\n      "keyAuthorization": "L5ysnyBrG6tODnB68t7Csfbjunwv4CRRCnneKbDEOXA.NOMOF65SuTEg_d5KUv2ebipDDBTaQxIs-TERLkA2OMQ",\n      "validationRecord": [\n        {\n          "hostname": "[REDACTEDLONGDOMAINNAME]",\n          "port": "443",\n          "addressesResolved": [\n            "[REDACTEDIPADDRESS]"\n          ],\n          "addressUsed": "[REDACTEDIPADDRESS]"\n        }\n      ]\n    },\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519285",\n      "token": "XzLZyEcbpHVCE4BOh7VW6mlokNciVt0tWX3nWc87BpI"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286",\n      "token": "sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      1\n    ],\n    [\n      0\n    ]\n  ]\n}'
2016-07-06 16:48:53,649:DEBUG:acme.challenges:dns-01 was not recognized, full message: {u'status': u'pending', u'token': u'sm30wsm4UUiLq7qJEFGsu7SppDstrH6iXVV17igLZm8', u'type': u'dns-01', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/zyBq7MpdKSjfiBIek8FPJHSt-vPT2SARu8FBhZdNM98/160519286'}
2016-07-06 16:48:53,649:INFO:certbot.auth_handler:Cleaning up challenges
2016-07-06 16:48:54,001:INFO:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-certbot.pem
2016-07-06 16:48:54,002:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 503, in run
    lineage, action = _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 94, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 276, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 256, in obtain_certificate
    csr = crypto_util.init_save_csr(key, domains, self.config.csr_dir)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/crypto_util.py", line 81, in init_save_csr
    must_staple=config.must_staple)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/crypto_util.py", line 113, in make_csr
    req.get_subject().CN = domains[0]
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 469, in __setattr__
    _raise_current_error()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]

**Comment by pde** [comment] 2016-07-06 19:11
Since you've redacted the domain name, can you give us an example of a long fictitious domain that reproduces the problem?

**Comment by bmw** [comment] 2016-07-06 21:07
This is a duplicate of #1915. Please read the discussion there for how to work around the problem.

**Closed** 2016-07-06 21:07 UTC
Labels: duplicate
