### ISSUE TITLE
Allow specifying the revocation reason

### ISSUE THREAD

**Issue by rolandshoemaker** [certbot/certbot#3242] opened 2016-07-06 02:25 UTC
The ACME spec has added support for [specifying the reason for revoking a certificate](https://ietf-wg-acme.github.io/acme/#certificate-revocation) (one of the `reasonCodes` defined in [RFC5280](https://tools.ietf.org/html/rfc5280#section-5.3.1)). Since the Boulder fix for this is extremely simple wanted to let you know this may appear pretty soon.

**Comment by bmw** [comment] 2016-07-08 19:07
I moved this into our next milestone because I wanted to make sure that this change in Boulder wouldn't cause any problems for clients that didn't support this feature. After double checking the spec, this shouldn't be a problem, so I'm bumping this to a later milestone.

**Comment by dashaxiong** [comment] 2016-12-08 05:35
Hi. The commit above (2efa1d) addresses this issue. I have opted to omit the reason field from the revocation request, if the user does not specify a reason. I have a feeling it would be better simply to send 'unspecified' in that case, do you agree? Also, when running `certbot revoke` with the new `reason` option against a local `boulder` instance I find that the audit log doesn't reflect the reason. Would appreciate a second set of eyes to look over this to confirm that the `JWS` payload is formed correctly.

**Comment by pde** [comment] 2016-12-08 19:05
@dashaxiong yes I think it's fine to say `unspecifed` if the user didn't provide a reason.

I guess we could also interactively ask for the reason (grab the `IDisplay` interface from zope and call `.menu()` on it with `default="unspecified"`.)

**Comment by dashaxiong** [comment] 2016-12-13 02:18
@pde I have made the default reason to be `unspecified`. The acme protocol and boulder server don't require any reason to be sent, so I initially opted for leaving it out in that case to minimise changes to existing tests that didn't give a reason for revocation. This was possible because of the `omitempty` flag in the `jose.Field`. But it seems cleaner to always send a reason, even if it is `unspecified`. 

Given that prompting for a reason code may cause a workflow regression, it seems wise to wait for #3878 to be resolved prior to adding the interactivity as a separate issue. Also, as the reason code is optional, is it desirable to prompt for it if it is missing?

**Comment by pde** [comment] 2016-12-14 00:36
@dashaxiong I think that's fine although we just decided to include #3878 in the 0.10.0 milestone to protect against other possible workflow regressions that will be in that release.

**Comment by dashaxiong** [comment] 2016-12-22 13:09
@rolandshoemaker While doing integration testing against a local Boulder instance the audit log doesn't reflect the reason code sent through. Here's the relevant output of `certbot/tests/boulder-integration.sh`:

```
Storing nonce: jAGHdGlH_1ez4iZPQfOnUfO_x1JnVn_TlhG-6FSgyQ0
JWS payload:
{
  "reason": 1, 
  "resource": "revoke-cert", 
  "certificate": "MIIEeDCCA2CgAwIBAgITAP-Wzp4gPJwQ6mkoksRdk0F_qDANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRoMnBweSBoMmNrZXIgZmFrZSBDQTAeFw0xNjEyMjIxMjAwMDBaFw0xNzAzMjIxMjAwMDBaMEExEDAOBgNVBAMTB2xlMi53dGYxLTArBgNVBAUTJGZmOTZjZTllMjAzYzljMTBlYTY5Mjg5MmM0NWQ5MzQxN2ZhODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJhLOhXs8DtOS6p2yV64336rrLrjEdogVLTC2F1N77ucIhYQY_YuUIIaCVhrTBMgFHvdhwY47F0ERbThqfbWwtriwdXvDEEXlbwr2ApRZ455tOsAAmpP0Yhgua9ruwF59Ge2wlAhB8GkQOhkaGMIAWJSB_ZoZ4jInzp8e38sk2FVaueumd481RdxjgQ7kvIhBhurrAU6md7X5FXvBzzRhYdvIZknz69KQ__jRzvw3Qx1kJJadUPM93a1xFZwtnAhp5RwH8d61AXbVZZTNMySagg3AHdAZX8S5BCPpn6rQPtN77TsK4NmizS94SQ_mA03iO1lmNsfWyryO2rH0C8SKf0CAwEAAaOCAYkwggGFMA4GA1UdDwEB_wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH_BAIwADAdBgNVHQ4EFgQUjqaSaI0-zbbJrGb-WpgzKjOTnd4wHwYDVR0jBBgwFoAU-3hPEvlgFYMsnxd_NBmzLjbqQYkwZgYIKwYBBQUHAQEEWjBYMCIGCCsGAQUFBzABhhZodHRwOi8vMTI3LjAuMC4xOjQwMDIvMDIGCCsGAQUFBzAChiZodHRwOi8vMTI3LjAuMC4xOjQwMDAvYWNtZS9pc3N1ZXItY2VydDASBgNVHREECzAJggdsZTIud3RmMCcGA1UdHwQgMB4wHKAaoBiGFmh0dHA6Ly9leGFtcGxlLmNvbS9jcmwwYQYDVR0gBFowWDAIBgZngQwBAgEwTAYDKgMEMEUwIgYIKwYBBQUHAgEWFmh0dHA6Ly9leGFtcGxlLmNvbS9jcHMwHwYIKwYBBQUHAgIwEwwRRG8gV2hhdCBUaG91IFdpbHQwDQYJKoZIhvcNAQELBQADggEBAEBzX-e1G1Sj2fN_FUUqKARNHtlyvgOMn3T2LfBtzMBLrLXVI1qVaZsvcL7I1fNfvCuetAXPTaeMmqCJYutv-kY6axmSiEp3YYnUVpwXefpx4zZJ1rq5HUCopWr2DRR0L5NAaWqr6jkyox5utA36DZxWeU9F7DVMwi5crV6z91-YM6V0oLP6OCSyKACoeSMJr1xdL5TZB-av7rEzV7fMuMQX24Llqd65cvDCyZBH2x6wLkfYiJNoKYXnZEjNxobxSvA4HvRNQG1DEGGQU7338NMSpHzx723sUnPOL-Tct9F7b6vaz7PFrmvZoyH1wZcrhfkYLNaOl2i42cy3BuZuD_0"
}
```

And here's the audit log:

```
I125940 boulder-ra [AUDIT] Revocation - State: Success, Serial: ff96ce9e203c9c10ea692892c45d93417fa8, CN: le2.wtf, DNS Names: [le2.wtf], Reason: unspecified, Request by registration ID: 0
```

Can you let me know if I've gone about it the right way?

**Comment by rolandshoemaker** [comment] 2016-12-23 04:36
When testing did you enable the AllowRevocationReason option in the
boulder-wfe configuration file? (e.g.
https://github.com/letsencrypt/boulder/blob/master/test/config-next/wfe.json#L13)

Without that bool set the 'reason' field will be ignored and the default
'unspecified' reason will be used.

**Comment by dashaxiong** [comment] 2017-01-01 00:57
I have enabled the AllowRevocationReason bool with the same result. 

I ran:
"""
export BOULDER_CONFIG_DIR="test/config-next"
docker-compose up
'''
And got the same result.

**Comment by dashaxiong** [comment] 2017-01-01 10:23
@rolandshoemaker All good, it succeeded!

```
I101849 boulder-ra [AUDIT] Revocation - State: Success, Serial: fff8088d90e9861b39cfe8e093048e3493a1, CN: le2.wtf, DNS Names: [le2.wtf], Reason: keyCompromise, Request by registration ID: 0
```

I was having some issues getting changes to apply to the code in the local boulder instance. In the end, what worked was editing the `default_config_dir` in `test/startservers.py` to `test/config-next`. Then copying the code across to the container with `docker cp . boulder_boulder_1:go/src/github.com/letsencrypt/boulder/`. Then starting it as usual.

**Closed** 2017-01-12 02:27 UTC
Labels: acme, has pr, ui / ux
