### ISSUE TITLE
Problems with authorization via shared account:NameCheap

### ISSUE THREAD

**Issue by steveyu123** [certbot/certbot#3471] opened 2016-09-02 02:35 UTC
I've been following the guide from: 
https://community.letsencrypt.org/t/tutorial-for-os-x-local-certificates-and-shared-hosting/6859/2

and I believe I am doing the steps correctly, but I end up with this type of response with a self-verify failure. I do own the example web domain. When I checked the directory in the SSH the key does exist in there. Anyone have any ideas why it might not work? Or anyone experience a similar response?

1)/usr/local/
2)git clone https://github.com/letsencrypt/letsencrypt
3)cd letsencrypt
4)./letsencrypt-auto certonly -a manual --rsa-key-size 4096 -d example.com -d www.example.com
5) Login via SSH, "SSH -p 21098 user@example.com"
6)mkdir -p .well-known/acme-challenge
cd .well-known/acme-challenge/
7)echo -n "key part 1" > key part 2

 Domain: www.example.com
   Type:   unauthorized
   Detail: Invalid response from
   http://www.example.com/.well-known/acme-challenge/Km-nsmDHdQqjN8Xk0OcvKHj1wT9GsjUh89s7JZsgfL4:
   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
   <html><head>
   <title>404 Not Found</title>
   </head><body>
   <h1>Not Found</h1>
   <p"

**Comment by SwartzCr** [comment] 2017-03-17 19:58
Hi @steveyu123 
I think the problem is that you're not providing the file name correctly. Have you managed to resolve this issue? If not let me know!
I'm going to close the issue for now, but re-open it if you're still having issues!

**Closed by SwartzCr** 2017-03-17 19:58 UTC
Labels: area: webroot, more-info
