### ISSUE TITLE
Install Python packages failed

### ISSUE THREAD

**Issue by rubenvereecken** [certbot/certbot#2902] opened 2016-04-29 10:00 UTC
I feel quite silly as I see what's going wrong but can't correct it. The Python package installation phase fails because pip seems unable to locate `urllib3`, that old many-faced arch nemesis of Python package management.

I tried installing the dependency but all of this happens in a virtual environment that gets torn down after the script fails, so I can't touch it outside of the script. Inside I tried installing using `pip install urllib3` but then again.. Pip needs `urllib3` to properly work? And fails. Not sure what's going on anymore now.

Here goes the full log, along with some echos of mine:

```
Creating virtual environment...
Installing Python packages...
Python 2.7.6

~/.local/share/letsencrypt/bin/python
~/.local/share/letsencrypt/bin
Had a problem while installing Python packages:
Traceback (most recent call last):
  File "~/.local/share/letsencrypt/bin/pip", line 9, in <module>
    load_entry_point('pip==8.0.3', 'console_scripts', 'pip')()
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "~/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

Running Linux Mint 17.2, based on Ubuntu 14.04.

**Comment by ucoker** [comment] 2016-05-19 18:31
I had the same issue.

**Comment by mattgiguere** [comment] 2016-07-12 01:04
I'm having the same issue running Apache on Ubuntu 14.04. @rubenvereecken @ucoker , did you figure out a workaround?

**Comment by anthonychung14** [comment] 2016-07-19 15:05
Same here. I saw this thread but not sure if it's relevant
https://github.com/certbot/certbot/issues/2108

**Comment by mattgiguere** [comment] 2016-07-19 23:53
@anthonychung14 thanks. Yeah, I saw that too, but it didn't work for me.

**Comment by bmw** [comment] 2016-07-19 23:59
Got another report of this today in #3300. I responded with:
> If you run:
```
virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
./temp_venv/bin/pip install requests==2.9.1
```
do you get the same error? What if you remove the `==2.9.1` from the end of the 2nd line?

> After running those commands there will be a `temp_venv` directory in your current working directory which can be deleted with `rm -rf temp_venv`.

**Comment by mattgiguere** [comment] 2016-07-21 16:29
@bmw both ways still fail with the same error for me. Should I type those commands you suggested before running certbot-auto, or should I modify the contents of the certbot-auto file? I typed those commands prior to running `./certbot-auto --apache`, and here's the output (minus a bunch of hits and gets) for the second attempt (i.e. without specifying requests v.2.9.1):

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ ./temp_venv/bin/pip install requests
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting requests
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 507kB 1.1MB/s 
Installing collected packages: requests
Successfully installed requests-2.10.0
ubuntu:~$ ./certbot-auto --apache
Bootstrapping dependencies for Debian-based OSes...
Ign http://us-west-1.ec2.archive.ubuntu.com trusty InRelease
Get:1 http://us-west-1.ec2.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:9 http://us-west-1.ec2.archive.ubuntu.com trusty-updates/multiverse amd64 Packages [13.2 kB]
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 1,707 kB in 2s (851 kB/s)            
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
augeas-lenses is already the newest version.
ca-certificates is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python-virtualenv is already the newest version.
The following packages were automatically installed and are no longer required:
  linux-headers-3.13.0-77 linux-headers-3.13.0-77-generic
  linux-headers-3.13.0-85 linux-headers-3.13.0-85-generic
  linux-headers-3.13.0-87 linux-headers-3.13.0-87-generic
  linux-image-3.13.0-77-generic linux-image-3.13.0-85-generic
  linux-image-3.13.0-87-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Creating virtual environment...
Installing Python packages...
Had a problem while installing Python packages:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/letsencrypt/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

**Comment by bmw** [comment] 2016-07-21 19:18
@mattgiguere, sorry. I should have explained more.

All I was trying to do with those commands was help diagnose the problem. Once I know what the problem is, I can try and help fix it.

The `virtualenv` command creates a [Python virtual environment](https://docs.python.org/3/library/venv.html#venv-def) and the second command installs the package `requests` which is where I believe the problem is occurring in `certbot-auto`.

If you run the two commands as is (without removing the `==2.9.1`) what is the output? Does the second command fail or do you get the same traceback as the one from `certbot-auto`?

If you don't get the same/similar traceback, what is the output of:
```
virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto-source/pieces/pipstrap.py | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
./temp_venv/bin/pip install requests==2.9.1
```

**Comment by mattgiguere** [comment] 2016-07-25 18:42
Ok, thanks for explaining. 

When running the commands in your initial comment, `requests` (both v.2.9.1 and the current version) install successfully. Here is the output from executing those two commands:

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ ./temp_venv/bin/pip install requests==2.9.1
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting requests==2.9.1
  Using cached requests-2.9.1-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.9.1
ubuntu:~$ 
```

When running the commands in your most recent comment, `requests` is still successfully installed, but it looks like there's an issue with a certificate:

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ curl https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto-source/pieces/pipstrap.py | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
ubuntu:~$ ./temp_venv/bin/pip install requests==2.9.1
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting requests==2.9.1
  Using cached requests-2.9.1-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.9.1
ubuntu:~$ 
```

Looking around, the certificates appear to be stored in `/etc/ssl/certs/` on my setup, not `/etc/pki/tls/certs/`. Could that be part of the problem?

**Comment by bmw** [comment] 2016-07-25 19:45
Well, I think the issue with `curl` is why the 2nd set of commands passed without a traceback. `curl` seems to have errored out and the downloaded file was never run.

I doubt that's why `certbot-auto` is erroring on you though. `certbot-auto` ships with a copy of that file included. You try using that one. What happens if you replace the `curl https://...` step above with:
```
sed -n 763,908p /path/to/certbot-auto | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
```
where `/path/to/certbot-auto` is the path to the `certbot-auto` file you've downloaded on your system.

**Comment by mattgiguere** [comment] 2016-07-25 21:55
That reproduced the error:

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Not overwriting existing python script temp_venv/bin/python (you must use temp_venv/bin/python2.7)
Installing setuptools, pip, wheel...done.
ubuntu:~$ sed -n 763,908p ./certbot-auto | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
ubuntu:~$ ./temp_venv/bin/pip install requests==2.9.1
Traceback (most recent call last):
  File "./temp_venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

**Comment by bmw** [comment] 2016-07-25 22:21
Progress!

Keeping those first two commands the same I'm curious if either of these ideas resolve the problem.

1. Changing `./temp_venv/bin/pip install requests==2.9.1` to `./temp_venv/bin/pip install requests`
2. After running the `sed` command, run `./temp_venv/bin/pip -U pip` before running `./temp_venv/bin/pip install requests==2.9.1`

**Comment by mattgiguere** [comment] 2016-07-25 22:32
Result of 1. Same error:

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ sed -n 763,908p ./certbot-auto | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
ubuntu:~$ ./temp_venv/bin/pip install requests
Traceback (most recent call last):
  File "./temp_venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

Result of 2. Same urllib3 error with the `pip -U pip` cmd:

```
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ sed -n 763,908p ./certbot-auto | PATH=./temp_venv/bin:$PATH ./temp_venv/bin/python -
ubuntu:~$ ./temp_venv/bin/pip -U pip
Traceback (most recent call last):
  File "./temp_venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

**Comment by bmw** [comment] 2016-07-25 22:39
Ah sorry. That 2nd command is supposed to be `pip install -U pip`.

Assuming it still fails, I've got another thing for you to try. Sorry I keep giving you all these commands, but I can't repo and we're narrowing down the problem.

```
virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
./temp_venv/bin/pip install -U setuptools
./temp_venv/bin/pip install -U pip
./temp_venv/bin/pip install -U wheel
./temp_venv/bin/pip install requests==2.9.1
```

**Comment by mattgiguere** [comment] 2016-07-25 23:14
No worries --- thanks for your help with this! Same result from the `pip install -U pip` cmd:

```
ubuntu:~$ ./temp_venv/bin/pip install -U pip
Traceback (most recent call last):
  File "./temp_venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$
```

Typing in the latest cmds you sent, it fails at `setuptools`:

```
ubuntu:~$ rm -rf temp_venv/
ubuntu:~$ virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) temp_venv
Running virtualenv with interpreter /home/ubuntu/anaconda2/bin/python2.7
New python executable in temp_venv/bin/python2.7
Also creating executable in temp_venv/bin/python
Installing setuptools, pip, wheel...done.
ubuntu:~$ ./temp_venv/bin/pip install -U pip
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 476kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.0.1
    Uninstalling pip-7.0.1:
      Successfully uninstalled pip-7.0.1
Successfully installed pip-8.1.2
ubuntu:~$ ./temp_venv/bin/pip install -U setuptools
Traceback (most recent call last):
  File "./temp_venv/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/ubuntu/temp_venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

**Comment by bmw** [comment] 2016-07-25 23:59
I found the bug upstream pypa/pip#3593. Unfortunately, until that gets fixed, we'll have a hard time fixing the problem in `certbot-auto` as it relies on some of the new features in `pip`.

I have some workarounds for you guys though. We're currently working on an Ubuntu 14.04 PPA. We hope that will be ready soon.

In the meantime, you can follow the instructions below. Replace `venv_dir` with the absolute path to where you want the Python virtual environment used to run Certbot to be saved.

1. Download `certbot-auto` and run `./certbot-auto --os-packages-only`
2. Run `virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) venv_dir`
3. Run `venv_dir/bin/pip install -U setuptools`
4. Run `venv_dir/bin/pip/install certbot-apache`

Now you can run Certbot by running `venv_dir/bin/certbot`. You can make this easier by putting a symlink to this file somewhere in your path. I hope this helps!

**Comment by mattgiguere** [comment] 2016-07-27 16:54
Everything seemed to work fine up until the last step of running Certbot, and then I get the same "No module named urllib3" error:

```
ubuntu:~$ venv_dir/bin/certbot
Traceback (most recent call last):
  File "venv_dir/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/certbot/account.py", line 15, in <module>
    from acme import messages
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/ubuntu/venv_dir/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
ubuntu:~$ 
```

**Comment by mactyr** [comment] 2016-09-30 23:56
I am having this same issue on Ubuntu 14.04.4 and am a little discouraged to see that the ticket seems to have gone silent since July, though perhaps it's just intractable until the upstream problem is fixed? It would be great to know if any alternate approaches (e.g. the aforementioned PPA) are available. Thanks!

**Comment by mattgiguere** [comment] 2016-10-01 00:11
I ended up using this as a temporary solution: https://gethttpsforfree.com/

**Comment by bmw** [comment] 2016-10-01 00:36
Sorry guys. @mactyr, you're correct this issue is largely intractable until the problem is fixed upstream. For Ubuntu 14.04, we currently recommend `certbot-auto`, but we can't really work around this problem on our end unless we want to significantly reduce the security of `certbot-auto`. (If you're curious, we've signed `certbot-auto` and have `pip` verify the hashes of all the packages we install, which is only available in newer versions of `pip`.)

We're continuing to work on getting an official Ubuntu 14.04 PPA (see #1706), however, until that's ready, I can continue to try and develop a workaround for you guys. The reason it's a bit tricky is I've been completely unable to reproduce the problem, however, to build off my most recent suggestion above, does this work:

In the meantime, you can follow the instructions below. Replace `venv_dir` with the absolute path to where you want the Python virtual environment used to run Certbot to be saved.

1. Download `certbot-auto` and run `./certbot-auto --os-packages-only`
2. Run `virtualenv --no-site-packages --python $(command -v python2.7 || command -v python27 || command -v python2 || command -v python) venv_dir`
3. Run `venv_dir/bin/pip install -U setuptools`
4. Run `venv_dir/bin/pip install urllib3 certbot-apache`

Now you can run Certbot by running `venv_dir/bin/certbot`. You can make this easier by putting a symlink to this file somewhere in your path.

**Comment by prionkor** [comment] 2016-11-23 05:41
I have the same problem with centOS 6.8 installation. Please find the details here. I need the fix asap as the certs will exprie soon

https://community.letsencrypt.org/t/certbot-is-borken-cant-renew-too-many-errors/22979

**Comment by prionkor** [comment] 2016-11-23 08:55
How do I get value of `venv_dir`?

**Comment by mayoralito** [comment] 2016-12-16 19:10
Hi guys, I was getting the same errors described in this thread and what I did was testing and researching about different ways about to resolve this problem and then I found this:

https://github.com/certbot/certbot/issues/1081

I ran `free -h` and I realize that free memory ram was under 192MB RAM. I just resized the Digital Ocean droplet and followed the process indicated here -> https://certbot.eff.org/#ubuntutrusty-apache and It worked at first attempt.

Hope this helps to others like it helped me.
Cheers!

**Comment by mattogodoy** [comment] 2016-12-22 12:17
I had this exact same problem and as @mayoralito correctly states, it was due to low available RAM memory. What I did is to create a swap file following these instructions: http://stackoverflow.com/a/18335151/2285524

Once I did that, it worked flawlessly.
Hope it helps someone!

**Comment by bmw** [comment] 2017-06-12 14:30
Adding more memory solved `ImportError: No module named urllib3`? That's very surprising to me.

Unfortunately, the bug upstream was closed saying it's not a bug in `pip`, but caused by a broken Python installation. See pypa/pip#3593.

**Comment by bmw** [comment] 2018-08-15 15:50
A lot has changed since this issue was made:

* The upstream issue was closed.
* `requests` stopped vendorizing `urllib3`.
* It hasn't seen any activity since 2016.

With these things in mind, I'm closing this issue, but please comment if you still have the problem!

**Closed by bmw** 2018-08-15 15:50 UTC
Labels: area: certbot-auto
