### ISSUE TITLE
Use the ACMEv2 newNonce endpoint when a new nonce is needed

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#6092] opened 2018-06-11 22:25 UTC
In our testing, sometimes Akamai fails to reach Let's Encrypt, and returns a 500 with malformed (non-JSON) contents. Certbot reports this as a missing nonce; instead it should report the malformed body and ignore the lack of a nonce.

**Comment by cpu** [comment] 2018-08-09 17:03
Here's an example of the exact 503 response and the tracebackk:
```
<snipped>
2018-06-19 20:00:41,668:INFO:certbot.main:Obtaining a new certificate
2018-06-19 20:00:41,779:DEBUG:certbot.crypto_util:Generating key (2048 bits): /home/xxx/xxx/prod-acmev02-1/conf/keys/6980_key-certbot.pem
2018-06-19 20:00:41,835:DEBUG:certbot.crypto_util:Creating CSR: /home/xxx/xxx/prod-acmev02-1/conf/csr/6980_csr-certbot.pem
2018-06-19 20:00:41,836:DEBUG:acme.client:Requesting fresh nonce
2018-06-19 20:00:41,836:DEBUG:acme.client:Sending HEAD request to https://acme-v02-1.api.letsencrypt.org/acme/new-order.
2018-06-19 20:00:41,991:DEBUG:urllib3.connectionpool:https://acme-v02-1.api.letsencrypt.org:443 "HEAD /acme/new-order HTTP/1.1" 503 0
2018-06-19 20:00:41,992:DEBUG:acme.client:Received response:
HTTP 503
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 271
Expires: Tue, 19 Jun 2018 20:00:41 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 19 Jun 2018 20:00:41 GMT
Connection: keep-alive

2018-06-19 20:00:41,992:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/home/xxx/certbot_venv/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/main.py", line 1315, in main
    return config.func(config, plugins)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/main.py", line 1206, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/main.py", line 118, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/client.py", line 351, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/client.py", line 294, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/certbot/client.py", line 326, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 779, in new_order
    return self.client.new_order(csr_pem)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 605, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 90, in _post
    return self.net.post(*args, **kwargs)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 1069, in post
    return self._post_once(*args, **kwargs)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 1079, in _post_once
    data = self._wrap_in_jws(obj, self._get_nonce(url), url, acme_version)
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 1058, in _get_nonce
    self._add_nonce(self.head(url))
  File "/home/xxx/certbot_venv/lib/python2.7/site-packages/acme/client.py", line 1053, in _add_nonce
    raise errors.MissingNonce(response)
MissingNonce: Server HEAD response did not include a replay nonce, headers: {'Content-Length': '271', 'Expires': 'Tue, 19 Jun 2018 20:00:41 GMT', 'Server': 'AkamaiGHost', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 19 Jun 2018 20:00:41 GMT', 'Content-Type': 'text/html', 'Mime-Version': '1.0'} (This may be a service outage)
2018-06-19 20:00:41,993:ERROR:certbot.log:An unexpected error occurred:

**Comment by ohemorange** [comment] 2018-10-22 23:12
Found the offending code, conveniently commented to tell us that it's not checking for an error:

```
    def head(self, *args, **kwargs):
        """Send HEAD request without checking the response.

        Note, that `_check_response` is not called, as it is expected
        that status code other than successfully 2xx will be returned, or
        messages2.Error will be raised by the server.

        """
        return self._send_request('HEAD', *args, **kwargs)
```

I think it makes sense to check that it's an expected error that we get back, not an unexpected error. Is there somewhere that defines what all the possible expected errors might be? I see that boulder gives a 405:

```
Requesting fresh nonce
Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-acct.
https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-acct HTTP/1.1" 405 0
Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 103
Allow: POST
Replay-Nonce: n_QRYFLZP947pWA4CxKpLOPMfEx1s0y8z_vehqjQu2w
Expires: Mon, 22 Oct 2018 23:10:03 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 22 Oct 2018 23:10:03 GMT
Connection: keep-alive
```

**Comment by ohemorange** [comment] 2018-10-22 23:13
(I think the `2` in `messages2.Error` is a typo?)

**Comment by ohemorange** [comment] 2018-10-22 23:16
Found related https://github.com/letsencrypt/boulder/issues/417 and turns out this issue is a duplicate of https://github.com/certbot/certbot/issues/521 which claimed to have been fixed in https://github.com/certbot/certbot/pulls/523 but seems to not have been

**Comment by ohemorange** [comment] 2018-10-22 23:17
JK, #523 was the proposed solution which didn't get used, and instead #586 got merged.

**Comment by ohemorange** [comment] 2018-10-22 23:19
It seems safe to check the response now.

**Comment by ohemorange** [comment] 2018-10-24 00:30
@jsha @cpu are we ok with just fixing this for ACMEv2 servers and leaving it as unresolved for ACMEv1 or is it important to fix it for ACMEv1

**Comment by ohemorange** [comment] 2018-10-24 00:36
readers: this is no longer a bug about error reporting, it is a bug also about implementing support for the newNonce directory endpoint

**Comment by cpu** [comment] 2018-10-24 13:14
@ohemorange I don't have strong feelings about whether its important for ACMEv1.

**Closed** 2018-11-03 00:32 UTC
Labels: area: error handling, current sprint, has pr
