### ISSUE TITLE
Parsing nginx conf file fails when include in double quotes

### ISSUE THREAD

**Issue by SmallhillCZ** [certbot/certbot#5752] opened 2018-03-17 18:43 UTC
When path for included file for include directove in nginx.conf is in double quotes, certbot fails to find the correct server_name directive. Using double quotes is correct for Nginx (nginx -t says ok), but fails for certbot.

## My operating system is (include version):

CentOS 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

 OS package manager

## I ran this command and it produced this output:

certbot --nginx

## Certbot's behavior differed from what I expected because:

Certbot should get the certificates and installed them. Instead it fails with "Could not automatically find a matching server block. Set the `server_name` directive to use the Nginx installer.".

## Here is a Certbot log showing the issue (if available):

2018-03-17 18:25:20,041:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 442, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 176, in deploy_cert
    vhosts = self.choose_vhosts(domain, create_if_no_match=True)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 285, in choose_vhosts
    vhosts = [self._vhost_from_duplicated_default(target_name)]
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 330, in _vhost_from_duplicated_default
    default_vhost = self._get_default_vhost(port)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 361, in _get_default_vhost
    raise errors.MisconfigurationError("Could not automatically find a matching server"
MisconfigurationError: Could not automatically find a matching server block. Set the `server_name` directive to use the Nginx installer.

2018-03-17 18:25:20,042:DEBUG:certbot.error_handler:Calling registered functions
2018-03-17 18:25:20,065:DEBUG:certbot.reporter:Reporting to user: Unable to install the certificate
2018-03-17 18:25:20,065:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.22.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1038, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 760, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 442, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 176, in deploy_cert
    vhosts = self.choose_vhosts(domain, create_if_no_match=True)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 285, in choose_vhosts
    vhosts = [self._vhost_from_duplicated_default(target_name)]
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 330, in _vhost_from_duplicated_default
    default_vhost = self._get_default_vhost(port)
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 361, in _get_default_vhost
    raise errors.MisconfigurationError("Could not automatically find a matching server"
MisconfigurationError: Could not automatically find a matching server block. Set the `server_name` directive to use the Nginx installer.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

http {
  rewrite_log on;
  include "/etc/nginx/conf.d/*";
}

**Comment by schoen** [comment] 2018-03-19 22:05
Thanks for the report, @SmallhillCZ . I'm pretty sure this is a duplicate of the known issue https://github.com/certbot/certbot/issues/5543. You can track the progress of the issue there.

**Closed by schoen** 2018-03-19 22:05 UTC
Labels: area: nginx, bug, duplicate
