### ISSUE TITLE
failed to renew

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4892] opened 2017-06-29 22:09 UTC
fwiw, my problem sounds vaguely like #3981/#4169

## My operating system is (include version):
RHEL 6.8 (Santiago)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto + scl python2.7

## I ran this command and it produced this output:
```sh
[root@host ~]# grep certbot /etc/crontab
13 7 * * * root /root/bin/certbot-renew
13 21 * * * root /root/bin/certbot-renew
[root@host ~]# cat /root/bin/certbot-renew
#!/bin/sh
scl enable python27 /root/bin/scl-certbot-renew
[root@host ~]# cat /root/bin/scl-certbot-renew
#!/bin/sh
/root/bin/certbot-auto -q renew --post-hook /root/bin/certbot-renew-hook
[root@host ~]# # skipping /root/bin/certbot-renew-hook because renewal failed
```

Email from cron:
```
Attempting to renew cert from /etc/letsencrypt/renewal/example.com.conf produced an unexpected error: Failed authorization procedure.
www.example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge.
Requested e192c20a3d78d302e523a517caf48855.69d7884ecd711750a8091d9e524f2585.acme.invalid from 208.113.89.231:443.
Received 2 certificate(s), first certificate had names "example.com, www.example.com", example.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge.
Requested c43a29f39433ddee78278a2f36b84ace.ccb5e54f48c0b19e1769817aeba6453b.acme.invalid from 208.113.89.231:443.
Received 2 certificate(s), first certificate had names "example.com, www.example.com".
Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/example.com/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
```

## Certbot's behavior differed from what I expected because:
```sh
[root@host ~]# scl enable python27 bash
[root@host ~]# /root/bin/certbot-auto
... prompted for renewal and successfully renewed
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
(I can provide this later if necessary)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```sh
conf/httpd.conf:<IfModule mod_ssl.c>
conf/httpd.conf:NameVirtualHost *:443
conf/httpd.conf:</IfModule>
conf.d/000-ssl.conf:LoadModule ssl_module modules/mod_ssl.so
conf.d/000-ssl.conf:Listen 443
conf.d/000-ssl.conf:SSLPassPhraseDialog  builtin
conf.d/000-ssl.conf:SSLSessionCache         shmcb:/var/cache/mod_ssl/scache(512000)
conf.d/000-ssl.conf:SSLSessionCacheTimeout  300
conf.d/000-ssl.conf:SSLMutex default
conf.d/000-ssl.conf:SSLRandomSeed startup file:/dev/urandom  256
conf.d/000-ssl.conf:SSLRandomSeed connect builtin
conf.d/000-ssl.conf:SSLCryptoDevice builtin
conf.d/000.conf:<VirtualHost *:80>
conf.d/000.conf:ServerName example.com
conf.d/000.conf:ServerAlias www.example.com
conf.d/000.conf:ProxyPass / ajp://localhost:8009/ connectiontimeout=60 timeout=600 retry=0
conf.d/000.conf:</VirtualHost>
conf.d/000-le-ssl.conf:<IfModule mod_ssl.c>
conf.d/000-le-ssl.conf:<VirtualHost *:443>
conf.d/000-le-ssl.conf:ServerName example.com
conf.d/000-le-ssl.conf:ServerAlias www.example.com
conf.d/000-le-ssl.conf:SSLCertificateFile /etc/letsencrypt/live/example.com/cert.pem
conf.d/000-le-ssl.conf:SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
conf.d/000-le-ssl.conf:Include /etc/letsencrypt/options-ssl-apache.conf
conf.d/000-le-ssl.conf:ProxyPass / ajp://localhost:8009/ connectiontimeout=60 timeout=600 retry=0
conf.d/000-le-ssl.conf:SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem
conf.d/000-le-ssl.conf:</VirtualHost>
conf.d/000-le-ssl.conf:</IfModule>
conf.d/ssl.conf:<VirtualHost _default_:443>
conf.d/ssl.conf:ErrorLog logs/ssl_error_log
conf.d/ssl.conf:TransferLog logs/ssl_access_log
conf.d/ssl.conf:LogLevel warn
conf.d/ssl.conf:SSLEngine on
conf.d/ssl.conf:SSLProtocol all -SSLv2
conf.d/ssl.conf:SSLCipherSuite DEFAULT:!EXP:!SSLv2:!DES:!IDEA:!SEED:+3DES
conf.d/ssl.conf:SSLCertificateFile /etc/pki/tls/certs/localhost.crt
conf.d/ssl.conf:SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
conf.d/ssl.conf:<Files ~ "\.(cgi|shtml|phtml|php3?)$">
conf.d/ssl.conf:    SSLOptions +StdEnvVars
conf.d/ssl.conf:</Files>
conf.d/ssl.conf:<Directory "/var/www/cgi-bin">
conf.d/ssl.conf:    SSLOptions +StdEnvVars
conf.d/ssl.conf:</Directory>
conf.d/ssl.conf:SetEnvIf User-Agent ".*MSIE.*" \
conf.d/ssl.conf:         nokeepalive ssl-unclean-shutdown \
conf.d/ssl.conf:         downgrade-1.0 force-response-1.0
conf.d/ssl.conf:CustomLog logs/ssl_request_log \
conf.d/ssl.conf:          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
conf.d/ssl.conf:</VirtualHost>
conf.d/welcome.conf:<LocationMatch "^/+$">
conf.d/welcome.conf:    Options -Indexes
conf.d/welcome.conf:    ErrorDocument 403 /error/noindex.html
conf.d/welcome.conf:</LocationMatch>
```

**Comment by jsoref** [comment] 2017-07-04 14:03
One possibly notable thing (which shouldn't matter): Apache is only configured to `listen 443` (not `listen 80`). Given that this is `tls-sni-01` as opposed to `http-01`, that shouldn't be relevant...

**Comment by SwartzCr** [comment] 2017-07-06 23:26
Can you share your renewal config? I want to make sure that it's trying the right challenge.
Also can you confirm that you've redacted the domains you're validating for and aren't actually trying to validate for example.com

**Comment by jsoref** [comment] 2017-07-07 03:33
Yes, it's redacted.

# renew_before_expiry = 30 days
version = 0.15.0
archive_dir = /etc/letsencrypt/archive/example.com
cert = /etc/letsencrypt/live/example.com/cert.pem
privkey = /etc/letsencrypt/live/example.com/privkey.pem
chain = /etc/letsencrypt/live/example.com/chain.pem
fullchain = /etc/letsencrypt/live/example.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = apache
installer = apache
account = ...

**Comment by SwartzCr** [comment] 2017-07-12 14:29
Maybe you could try adding pref_challs = tls-sni-01 to your renewal conf? You might have a similar issue to #4887 ?
If not let me know and we can do more debugging. Sorry for the delay, I was caught up preparing a talk, and should respond more quickly now.

**Comment by jsoref** [comment] 2017-07-13 05:34
Added...
Can you explain what you think certbot was doing? Do you think that certbot set up apache for http-01 while asking boulder for tls-sni-01? That seems pretty bizarre....

**Comment by SwartzCr** [comment] 2017-07-13 21:16
Did it fix your issue?
I think what was happening is that you got your certificates via the webroot challenge (`http-01`) and then certbot didn't store this information. When you went to renew, it saw you had apache on your system and tried to renew with `tls-sni-01` which is the default for apache.

**Comment by jsoref** [comment] 2017-07-14 15:52
What puzzles me is that running certbot manually interactively resulted in it properly renewing the certificate...

fwiw, while I do have some servers w/ lots of `<VirtualHost>s`, this server is really boring. At the time, it had:
```
         default server example.com (/etc/httpd/conf.d/000-le-ssl.conf:2)
         port 443 namevhost example.com (/etc/httpd/conf.d/000-le-ssl.conf:2)
                 alias www.example.com
         port 443 namevhost www.example.com (/etc/httpd/conf.d/ssl.conf:1)
```

And yes, it really does have two namevhosts for `www.{redacted-as-example.com}`.
I'm starting to think that's the problem.
The second one comes from `<VirtualHost _default_:443>` in ssl.conf (as noted in the original bug report).

Note: at times I've tried renaming `ssl.conf` and it seems that apache upgrades or something resurrects this file which results in various errors, so I've learned to leave the file in place (I'm tempted to making it unreadable+unwritable to see if I can block things from doing that, but I haven't gotten around to that adventure).

*Footnote: I've since added:
```
<VirtualHost *:80>
ServerName {ip address}
RewriteEngine On
RewriteRule . - [R=403,NC,L]
ErrorLog /dev/null
CustomLog /dev/null common
</VirtualHost>
```
```
<VirtualHost *:443>
ServerName {ip address}
RewriteEngine On
RewriteRule . - [R=403,NC,L]
ErrorLog /dev/null
CustomLog /dev/null common

# ... SSLCertificate block stolen from the "default server" for each server
</VirtualHost>
```
to each of my servers to strip out some annoying bots that are probing things and flooding my logs.

**Comment by SwartzCr** [comment] 2017-07-15 02:12
Well it seems like you might be better at debugging this than I am from afar - tinker with the vhosts and let me know how it goes?

**Comment by jsoref** [comment] 2017-07-16 20:19
I think I'm going to be decommissioning that server.
I can provide a diff between the manual renewal (that worked) and the automated that failed.
But right now, the site is renewed for ~2 months from when I filed this ticket, until which it won't try to renew...

**Comment by SwartzCr** [comment] 2017-07-17 17:31
Okay - keep me updated, sorry it's been a problem to deal with

**Comment by joohoi** [comment] 2017-07-19 08:19
If Certbot behaves differently when running with the exact same CLI parameters between cron and manually, it's most likely related to environment variables in some way. Most of the env vars that are present in interactive session do not exist in cron job per default. This is something that I'd check probably.

**Comment by jsoref** [comment] 2017-07-19 23:56
Yeah, `HOME` isn't present in cron, which means that I have `/.local` and `/root/.local` which is pretty annoying.

**Comment by bmw** [comment] 2019-02-28 19:28
Support for TLS-SNI is deprecated will be removed next month so I'm closing this issue. I'm sorry we never seemed to figure out the cause while it was still relevant.

**Closed by bmw** 2019-02-28 19:28 UTC
Labels: area: fedora / redhat / CentOS, area: renewal
