### ISSUE TITLE
Flag to issue for all virtualhosts?

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4176] opened 2017-02-05 22:10 UTC
I may have missed this, but it seems like there is no command line flag that says "auto-detect all virtual hosts in my configs and issue for them." Is that accurate? It seems like the choices are (a) enumerate domains on command line, or (b) use interactive mode, and choose the default of issuing for all virtual hosts.

The advantage of having a command line flag is that it would make it easier to issue for new names after adding virtual hosts for them, rather than having to explicitly enumerate the names.

**Comment by pde** [comment] 2017-02-05 22:25
I think this is a duplicate of #3887?

**Closed** 2017-02-05 22:27 UTC
Labels: duplicate
