### ISSUE TITLE
undefined symbol: EC_curve_nid2nist

### ISSUE THREAD

**Issue by nextgenthemes** [certbot/certbot#1851] opened 2015-12-10 08:50 UTC
Ubuntu 14.04 VPS

I get this errors when running letsencrypt on a ubuntu VPS after compiling installing and then uninstalling Libressl

I am not sure but I think libressl (portable repo here from Github) may have to do with it. I had it compiled and installed before using letsencrypt. I used `make uninstall` I get this secure platform warnings ...

I found https://community.letsencrypt.org/t/python-error/2836/3 and deleted the files but no luck.

Also I purged openssl and reinstalled it but this also not helped.

```
root@server:~/build/letsencrypt# apt-cache policy openssl
openssl:
  Installed: 1.0.1f-1ubuntu2.16
  Candidate: 1.0.1f-1ubuntu2.16
  Version table:
 *** 1.0.1f-1ubuntu2.16 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

```
root@server:~/build/letsencrypt# ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth
Updating letsencrypt and virtual environment dependencies.../root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
./root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
../root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
./root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 17, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_curve_nid2nist
```

**Comment by bmw** [comment] 2015-12-16 00:48
Any ideas @reaperhulk?

**Comment by nextgenthemes** [comment] 2015-12-16 01:13
Actually I don't have this problem anymore. I purged openssl and to my surprise it was working after that. So letsencrypt does not need the openssl package installed on Ubuntu?

I now have rebuild my VPS from scrach and have openssl installed, at the same time libressl compiled and installed (not sure if this is bad, if there are file/config/... overlaps or something). But letsencrypt works so you may just want to close this.

**Comment by bmw** [comment] 2015-12-16 01:20
I'm glad you were able to get it working. `letsencrypt` needs the `libssl-dev` package (which is installed by `letsencrypt-auto`), but not `openssl`.

I also suspect it might have something to do with `openssl` and `libressl` interfering with each other. For that reason, I'm closing this issue, but if anyone else encounters the problem, let me know and I'll reopen.

Thanks for reporting and following up on the issue @nextgenthemes!

**Comment by reaperhulk** [comment] 2015-12-16 04:54
For future reference, this is strongly suggestive of a header mismatch, where the standard openssl headers state that `EC_curve_nid2nist` is available, but then it attempted to link against the libressl dynamic library (which does not have that symbol).

**Comment by bmw** [comment] 2015-12-16 04:57
Great! Thanks for the info.

**Comment by Ge0** [comment] 2016-02-15 12:40
Hello there,

I actually have installed the `libssl-dev` package on my Debian 8 VPS and I having the same issue as mentionned above:

```
ge0@kondou ~/letsencrypt ±master⚡ » ./letsencrypt-auto              
Checking for new version...
Creating virtual environment...
Installing Python packages...
Requesting root privileges to run letsencrypt...
   sudo /home/ge0/.local/share/letsencrypt/bin/letsencrypt --no-self-upgrade
Traceback (most recent call last):
  File "/home/ge0/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 21, in <module>
    import OpenSSL
  File "/home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/ge0/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_curve_nid2nist
```

Did I actually miss something?

**Comment by BrainStone** [comment] 2016-06-16 17:42
When running my automatic renewal script on Debian 8 I got this error:

```
Automated renewal failed:
Upgrading certbot-auto 0.8.0 to 0.8.1...
Replacing certbot-auto...
Creating virtual environment...
New python executable in /root/.local/share/letsencrypt/bin/python2.7
Also creating executable in /root/.local/share/letsencrypt/bin/python
Installing setuptools, pip...done.
Running virtualenv with interpreter /usr/bin/python2.7
Installing Python packages...
Installation succeeded.
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_curve_nid2nist
```

I am also using libressl. So that might be the issue. I also never had this problem before. It appears that the update from 0.8.0 to 0.8.1 broke it for me.

**Comment by reaperhulk** [comment] 2016-06-16 20:49
What version of libressl (and cryptography) are you using? Do you have OpenSSL installed as well? One way you can get the cryptography version is by looking in `/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/__about__.py`

**Comment by BrainStone** [comment] 2016-06-16 20:52
I installed LibreSSL over OpenSSL but as far as I can tell it replaced it completly.

LibreSSL is version 2.4.0 and cryptography 1.2.3

**Comment by reaperhulk** [comment] 2016-06-16 20:58
Could you try installing the latest cryptography (1.4) to see if you still experience the issue? We had a change in 1.3.x to correct an issue with LibreSSL.

**Comment by BrainStone** [comment] 2016-06-16 21:03
How do I do this? I don't have pip

**Comment by reaperhulk** [comment] 2016-06-16 21:05
certbot's virtualenv looks like it's probably in `/root/.local/share/letsencrypt/` so if you `source /root/.local/share/letsencrypt/bin/activate` that should put you in the virtualenv where you can `pip install -U cryptography`

**Comment by BrainStone** [comment] 2016-06-16 21:11
I was able to install a newer version of cryptography. But the versioin in ``/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/__about__.py`` hasn't changed and when I try to run my renew script the same error occurs.

**Comment by reaperhulk** [comment] 2016-06-16 21:13
Unfortunately I don't know enough about how certbot bootstraps its environment, so I can't help with that. Hopefully now that we've isolated the fact that it only occurs due to an out of date package someone else can assist with getting it to properly upgrade. It's possible you could just delete the install entirely and have it re-create the environment but I don't know for sure.

**Comment by BrainStone** [comment] 2016-06-16 21:18
I woukld hope that there is somebody who can help with that. Because I really don't anymore know how I installed it.

**Comment by bmw** [comment] 2016-06-16 21:24
@BrainStone try running `~/.local/share/letsencrypt/bin/pip install -U cryptography` and check that `__about__.py` is updated in `~/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/__about__.py`. If so, try running `certbot-auto`/`letsencrypt-auto` again and see if you have the same problem.

Additionally, while this should be fixed, there are `certbot` packages available in [jessie backports](https://certbot.eff.org/#debianjessie-other) which might be useful to you.

@reaperhulk, thanks for responding to this so quickly. Our bootstrap script pins specific versions of all of our Python dependencies when first creating the venv to try and add a little more stability to the script. This pinning shouldn't stop the user from updating manually, however.

`cryptography` is currently pinned at 1.2.3 but we can update it in a future release if 1.4 has significant improvements.

**Comment by BrainStone** [comment] 2016-06-16 21:37
@bmw I just found the certbot package. This appears to be working! I just need to change a few paths and everything should be good to go. Thank you anyways!

**Comment by reaperhulk** [comment] 2016-06-16 21:43
@bmw the improvements from 1.2 -> 1.4 aren't of any real relevance to certbot. We dropped OpenSSL 0.9.8 support in 1.4 and deprecated it in 1.3 (with an env var to re-enable it). You could update the dep to `1.3.4` and it would capture the fix for LibreSSL, but you'll either have to drop OpenSSL 0.9.8 users (who are running a version unsupported by the OpenSSL project since the end of 2015) or set an extra env var to allow that to continue to work.

**Closed** 2016-06-21 21:17 UTC

**Comment by FlorentATo** [comment] 2016-06-26 00:29
Hello, I'm having the same issue.

I use Debian 8.5, LibreSSL 2.3.4, cryptography 1.2.3 (according to `~/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/__about__.py` and `/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/__about__.py`).

```
ato@kimsufi-ato:~$ pip install -U cryptography
Requirement already up-to-date: cryptography in /usr/local/lib/python2.7/dist-packages
Cleaning up...
ato@kimsufi-ato:~$ sudo pip install -U cryptography
Requirement already up-to-date: cryptography in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: pyasn1>=0.1.8 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography)
```
The error occurs when I run both `./certbot-auto` and `./letsencrypt-auto`.
Here's the error:

```
ato@kimsufi-ato:~/letsencrypt$ ./certbot-auto 
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
  /home/ato/.local/share/letsencrypt/bin/letsencrypt
Traceback (most recent call last):
  File "/home/ato/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/ato/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_curve_nid2nist
```

I don't know whether Letsencrypt officially supports LibreSSL at the moment nor what's the best way to install it properly: using apt-get or by mirroring the repo ?.

Lastly (and slightly off-topic), as a LibreSSL user, should I consider moving to [letskencrypt](https://kristaps.bsd.lv/letskencrypt/) ?

Thank you :)

**Comment by bmw** [comment] 2016-06-27 16:18
@FlorentATo, a PR has landed that should address this issue and it will be included in our next release. In the mean time, I encourage you to read the discussion above to see if it helps you resolve the issue.

**Comment by FlorentATo** [comment] 2016-06-28 07:52
Hello bmw. I did read the thread, carefully.
I was desperate enough to clean up everything then reinstalled OpenSSL and moved LibreSSL aside. No new results so I uninstalled Cryptography 1.4 to downgrade it to 1.1(.1) and **it worked**.

I'm not brave enough to compile LibreSSL again and check if it works with Cryptography 1.1. At least not now... =)

**Comment by bmw** [comment] 2016-06-29 00:21
Sorry you had the problem. The next release of Certbot will be out in a few weeks. If the issue still exists then, I'll reopen.

**Comment by FlorentATo** [comment] 2016-06-30 02:59
No worries, it's all fine now.
I keep an eye on the next release and keep you posted.
Thanks

**Comment by kikoreis** [comment] 2019-06-01 05:09
I've tracked down one possible root cause of this down to a packaging issue in python-cryptography. The version certbot is distributing (1.9) comes with its own .so files:

 /usr/lib/python3/dist-packages/cryptography/hazmat/bindings/_padding.abi3.so
 /usr/lib/python3/dist-packages/cryptography/hazmat/bindings/_openssl.abi3.so
 /usr/lib/python3/dist-packages/cryptography/hazmat/bindings/_constant_time.abi3.so

However, it fails to remove any .so files that previous versions of the package may have installed. On a stock 16.04 LTS installation, python-cryptography 1.2.3 includes its own .so files:

 /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_constant_time.x86_64-linux-gnu.so
 /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.x86_64-linux-gnu.so
 /usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_padding.x86_64-linux-gnu.so

If you add the PPA and simply upgrade to the version in the PPA, you'll end up with both sets of .so files. The python runtime prefers the filename of the old .so, which is missing key symbols, and you end up with the traceback above. As a workaround, you can simply delete the old .so files. But the packaging should really be fixed to remove them upon upgrade.
