### ISSUE TITLE
certbot Cannot find a cert or key directive in 

### ISSUE THREAD

**Issue by blacktav** [certbot/certbot#4977] opened 2017-07-31 20:08 UTC
## My operating system is (include version):
OpenSuSE Leap 42.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
certbot-auto --apache -d bavaria.domain.net

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/bavaria.domain.net.conf)

What would you like to do?
-------------------------------------------------------------------------------
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Created an SSL vhost at /etc/apache2/vhosts.d/bavaria-le-ssl.conf
Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/bavaria-le-ssl.conf/IfModule/VirtualHost. VirtualHost was not modified
Unable to find cert and/or key directives

IMPORTANT NOTES:
 - Unable to install the certificate
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/bavaria.domain.net/fullchain.pem. Your
   cert will expire on 2017-10-29. To obtain a new or tweaked version
   of this certificate in the future, simply run certbot-auto again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot-auto renew"

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-07-31 20:00:11,385:DEBUG:certbot.main:certbot version: 0.16.0
2017-07-31 20:00:11,386:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'bavaria.domain.net']
2017-07-31 20:00:11,386:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-07-31 20:00:11,399:DEBUG:certbot.log:Root logging level set at 20
2017-07-31 20:00:11,399:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-07-31 20:00:11,400:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-07-31 20:00:11,515:DEBUG:certbot_apache.configurator:Apache version is 2.4.23
2017-07-31 20:00:11,837:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f0dfefc6950>
Prep: True
2017-07-31 20:00:11,838:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f0dfefc6950> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f0dfefc6950>
2017-07-31 20:00:11,840:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, contact=(u'mailto:sysadmin@domain.com',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7f0dfed78050>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/17810740', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'), 3466a5930e32e327c44ed68af8db7553, Meta(creation_host=u'bavaria', creation_dt=datetime.datetime(2017, 6, 24, 22, 30, 44, tzinfo=<UTC>)))>
2017-07-31 20:00:11,841:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-07-31 20:00:11,844:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-07-31 20:00:12,062:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 352
2017-07-31 20:00:12,063:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: 32gXtZLq9EDbGBaTRykVhohlpAuEUS_jbOcrtIcJ8T8
Replay-Nonce: GXmAi1ZusTs6IBOo8zyFr0e9GwSgMToMqUENXvh4aUQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 31 Jul 2017 20:00:54 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 31 Jul 2017 20:00:54 GMT
Connection: keep-alive
{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-07-31 20:00:12,089:INFO:certbot.renewal:Cert not yet due for renewal
2017-07-31 20:00:14,487:INFO:certbot.main:Keeping the existing certificate
2017-07-31 20:00:14,490:DEBUG:certbot.reporter:Reporting to user: Congratulations! Your certificate and chain have been saved at /etc/letsencrypt/live/bavaria.domain.net/fullchain.pem. Your cert will expire on 2017-10-29. To obtain a new or tweaked version of this certificate in the future, simply run certbot-auto again with the "certonly" option. To non-interactively renew *all* of your certificates, run "certbot-auto renew"
2017-07-31 20:00:14,602:DEBUG:certbot.reverter:Creating backup of /etc/apache2/vhosts.d/bavaria-le-ssl.conf
2017-07-31 20:00:14,652:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/apache2/vhosts.d/bavaria-le-ssl.conf
2017-07-31 20:00:14,770:WARNING:certbot_apache.configurator:Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/bavaria-le-ssl.conf/IfModule/VirtualHost. VirtualHost was not modified
2017-07-31 20:00:14,771:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 451, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot_apache/configurator.py", line 269, in deploy_cert
    "Unable to find cert and/or key directives")
PluginError: Unable to find cert and/or key directives
2017-07-31 20:00:14,771:DEBUG:certbot.error_handler:Calling registered functions
2017-07-31 20:00:14,781:DEBUG:certbot.reporter:Reporting to user: Unable to install the certificate
2017-07-31 20:00:14,781:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 743, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 604, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 469, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 451, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot_apache/configurator.py", line 269, in deploy_cert
    "Unable to find cert and/or key directives")
PluginError: Unable to find cert and/or key directives

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
<VirtualHost *:80>
    ServerName  bavaria.domain.net
    ServerAdmin sysadmin@domain.com
    DocumentRoot /srv/www/htdocs/maintenancemode/
    ServerSignature On
</VirtualHost>

**Comment by SwartzCr** [comment] 2017-08-03 20:06
So it seems like the issue is that you're trying to update the cert in your ssl vhost rather than re-install the cert on your non-ssl vhost.
The vhost that you've included is on Port 80. Certbot will happily copy that vhost and include a reference to the certificate that you have for bavaria.domain.net if you select `1: Attempt to reinstall this existing certificate`.
When you select `2: Renew & replace the cert (limit ~5 per 7 days)` certbot assumes that you've already installed this certificate and goes and looks for the vhost file that it would have created. In your case it seems like you might not have that vhost file (although you do have a valid cert for the domain).
If you don't have a file called `bavaria-le-ssl.conf` in your `vhosts.d` folder, then I'd recommend running this command again but choosing option 1. If you do in fact have that ssl vhost .conf file, please share it with me here so I can help further debug.

**Comment by blacktav** [comment] 2017-08-03 20:24
Hi
Both, the error occurs whether or not the cert has been installed
The script seems to have a problem creating the SSL config file and I cannot see what is causing the problem.
The file should be created at /etc/apache2/vhosts.d/bavaria-le-ssl.conf as noted in the logfile, but the next line suggests the url is being mangled somewhere 
2017-07-31 20:00:14,770:WARNING:certbot_apache.configurator:Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/bavaria-le-ssl.conf/IfModule/VirtualHost. VirtualHost was not modified

I am choosing "1: Attempt to reinstall this existing certificate"
An SSL config file is NOT created
Python version is 2.7.13

**Comment by SwartzCr** [comment] 2017-08-03 21:51
Interesting, can you share with me a list of all .conf files that you have in your vhosts.d folder?

**Comment by blacktav** [comment] 2017-08-03 22:09
Although I have several active conf files at present; if they are all removed except for 1 (see below), the error occurs : console session appears as:

bavaria:/etc/apache2/vhosts.d # certbot-auto --apache -d www.domain.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/www.domain.net.conf)

What would you like to do?
-------------------------------------------------------------------------------
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate
Created an SSL vhost at /etc/apache2/vhosts.d/1-php-wwwnet-le-ssl.conf
Cannot find a cert or key directive in /files/etc/apache2/vhosts.d/1-php-wwwnet-le-ssl.conf/IfModule/VirtualHost. VirtualHost was not modified
Unable to find cert and/or key directives

IMPORTANT NOTES:
 - Unable to install the certificate
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/www.domain.net/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/www.domain.net/privkey.pem
   Your cert will expire on 2017-10-28. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again with the "certonly" option. To non-interactively renew *all*
   of your certificates, run "certbot-auto renew"
Press any key to continue...

1-php-wwwnetl.conf

# -------------------------------------
# PHP system for domain
# -------------------------------------
<VirtualHost *:80>
    ServerName www.domain.net
    DocumentRoot /srv/www/htdocs/web2017
    <Directory "/srv/www/htdocs/bubba">
      Options FollowSymLinks
        Require all granted
    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteCond %{HTTP_HOST} ^www.domain.net [NC]
        RewriteBase /
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.php [L]
    </IfModule>
    </Directory>
</VirtualHost>

**Comment by blacktav** [comment] 2017-08-03 22:18
Erk, file contents above has been munged by something...

# -------------------------------------
# PHP systems for Domain
# -------------------------------------
<VirtualHost *:80>
    ServerName www.domain.net
    DocumentRoot /srv/www/htdocs/bubba
    <Directory "/srv/www/htdocs/bubba">
      Options FollowSymLinks
        Require all granted
    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteCond %{HTTP_HOST} ^www.domain.net [NC]
        RewriteBase /
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.php [L]
    </IfModule>
    </Directory>
</VirtualHost>

**Comment by blacktav** [comment] 2017-08-03 22:20
[domain.txt](https://github.com/certbot/certbot/files/1198741/domain.txt)

**Comment by SwartzCr** [comment] 2017-08-03 22:40
hmm maybe @bmw or @joohoi have an idea of what might be happening

**Comment by blacktav** [comment] 2017-08-03 22:47
Could it be anything to do with XML libraries?
I had a problem caused some odd errors by an ancient install below /usr/local; it has been resolved now
Is there a simple way to force a rebuild of certbot?

**Comment by bmw** [comment] 2017-08-04 00:03
Thanks for the all the info here @blacktav. I was able to reproduce the problem.

Unfortunately, I don't think the Apache plugin will currently work on OpenSuSe. The way that Apache configurations work on different distros varies wildly and our Apache parser is struggling to parse the resulting configuration due to `<IfModule ...` directives. This is closely related to #3967.

@joohoi is planning on working on these issues in the next couple months, but in the meantime you will have to configure your certificates manually with Apache. Sorry for the trouble!

**Comment by bmw** [comment] 2017-08-04 00:05
@joohoi (or anyone else who works on this), I was able to successfully install the cert by removing the `<IfModule mod_ssl.c>` directives from around the vhost we create.

**Comment by SwartzCr** [comment] 2017-09-25 19:23
What's the status of this? @joohoi is this something that'll go into your apache work?
@blacktav have you been able to get your configuration working?

**Comment by blacktav** [comment] 2017-09-25 19:34
@SwartzCr yeah, I am good. I worked round the issue so I don't know if the issue is still present

**Comment by joohoi** [comment] 2017-09-25 20:10
Yes, this will be on the schedule

**Comment by joohoi** [comment] 2017-12-07 18:21
This was fixed in #5202 by giving Certbot visibility on loaded modules in OpenSUSE

**Closed by joohoi** 2017-12-07 18:21 UTC
Labels: area: apache, area: renewal, debugging

**Comment by zareefahmed** [comment] 2018-03-22 02:28
In my case, it was mod_ssl which I forgot to install after installing apache2.4
