### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/etc/httpd/conf.d/le_tls_sni_01_cert_challenge.conf'

### ISSUE THREAD

**Issue by GTMAN** [certbot/certbot#3372] opened 2016-08-04 20:10 UTC
Centos 7 with WHM/Cpanel and multiply Vhosts entries.  The conf.d folder does not exist on this setup. 
`<VirtualHost 69.164.208.139:80 [2600:3c03:0000:0000:f03c:91ff:fe79:6c48]:80>
  ServerName durhamhouses.info
  ServerAlias ipv6.durhamhouses.info www.durhamhouses.info
  DocumentRoot /home/durhamho/public_html
  ServerAdmin webmaster@durhamhouses.info
  UseCanonicalName Off
  CustomLog /etc/apache2/logs/domlogs/durhamhouses.info combined
  <IfModule log_config_module>
    <IfModule logio_module>
      CustomLog /etc/apache2/logs/domlogs/durhamhouses.info-bytes_log "%{%s}t %I .\n%{%s}t %O ."
    </IfModule>
  </IfModule>
  ## User durhamho # Needed for Cpanel::ApacheConf
  <IfModule userdir_module>
    <IfModule !mpm_itk.c>
      <IfModule !ruid2_module>
        UserDir disabled
        UserDir enabled durhamho 
      </IfModule>
    </IfModule>
  </IfModule>

  # Enable backwards compatible Server Side Include expression parser for Apache versions >= 2.4.
  # To selectively use the newer Apache 2.4 expression parser, disable SSILegacyExprParser in
  # the user's .htaccess file.  For more information, please read:
  #    http://httpd.apache.org/docs/2.4/mod/mod_include.html#ssilegacyexprparser
  <IfModule include_module>
    <Directory "/home/durhamho/public_html">
      SSILegacyExprParser On
    </Directory>
  </IfModule>

  <IfModule suphp_module>
    suPHP_UserGroup durhamho durhamho
  </IfModule>
  <IfModule suexec_module>
    <IfModule !mod_ruid2.c>
      SuexecUserGroup durhamho durhamho
    </IfModule>
  </IfModule>
  <IfModule ruid2_module>
    RMode config
    RUidGid durhamho durhamho
  </IfModule>
  <IfModule mpm_itk.c>
    # For more information on MPM ITK, please read:
    #   http://mpm-itk.sesse.net/
    AssignUserID durhamho durhamho
  </IfModule>

  <IfModule alias_module>
    ScriptAlias /cgi-bin/ /home/durhamho/public_html/cgi-bin/
  </IfModule>

  # To customize this VirtualHost use an include file at the following location
  # Include "/etc/apache2/conf.d/userdata/std/2_4/durhamho/durhamhouses.info/*.conf"
</VirtualHost>`

**Comment by bmw** [comment] 2016-08-10 01:00
Looking at the configuration file you posted, you're using `/etc/apache2` instead of `/etc/httpd`. Did you move this manually? The default location configuration location for Apache is `/etc/httpd` on CentOS 7.

**Comment by GTMAN** [comment] 2016-08-10 13:20
It is a whm/cpanel installation. I have since found out that cPanel will
soon support letsencrypt natively.

On Aug 9, 2016 9:01 PM, "Brad Warren" <notifications@github.com> wrote:

Looking at the configuration file you posted, you're using /etc/apache2
instead of /etc/httpd. Did you move this manually? The default location
configuration location for Apache is /etc/httpd on CentOS 7.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/certbot/certbot/issues/3372#issuecomment-238737741>,
or mute
the thread

**Comment by bmw** [comment] 2016-08-10 20:31
Very true ([source](https://blog.cpanel.com/announcing-cpanel-whms-official-lets-encrypt-with-autossl-plugin/))!

This issue seems like a duplicate of #3362, with the only potential difference being you're using whm/cpanel. I'm going to close this issue to keep all info in one place. Please follow the thread there for more info.

**Closed by bmw** 2016-08-10 20:31 UTC
Labels: more-info
