### ISSUE TITLE
Domains dialog should recommend bundling all domains to be enabled in a single certificate

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#8892] opened 2021-06-08 15:53 UTC
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

0.31.0-1+deb10u1

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt/dpkg

## I ran this command and it produced this output:

`certbot`
```
Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: example.com
2: example.net
3: www.example.net
4: example.org
...
```

I selected `2`, and then repeated for `3`.

## Certbot's behavior differed from what I expected because:

It created a certificate that it could have known would break apache configuration. (resulting in insecure certificates for the `servername` or `serveralias` not specified.)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

The problem is that 2 + 3 are tied to the same apache config
```
<VirtualHost *:80>
        ServerName example.net
        ServerAlias www.example.net
```

**Comment by osirisinferi** [comment] 2021-06-08 19:01
Which version of certbot are you running?

**Comment by jsoref** [comment] 2021-06-08 19:07
> 0.31.0-1+deb10u1

**Comment by ohemorange** [comment] 2021-06-10 00:04
When you say "selected 2 then repeated for 3", do you mean you ran certbot twice, or entered "2,3" in response to the question?

**Comment by jsoref** [comment] 2021-06-10 00:08
Ran it twice

**Comment by ohemorange** [comment] 2021-06-11 20:56
Ah yes. Our recommended strategy there is to put both domains in the same cert, especially for rate limit reasons. But we could be more clear about that in the dialog, so thanks for highlighting this confusion for us!

**Comment by osirisinferi** [comment] 2021-06-11 21:41
> Ah yes. Our recommended strategy there is to put both domains in the same cert, especially for rate limit reasons. But we could be more clear about that in the dialog, so thanks for highlighting this confusion for us!

I'm currently working locally on a feature for the Apache plugin which recommends hostnames from virtualhosts from which hostnames are selected, but aren't in that set of selected hostnames. I.e., the missing hostnames.

Just needs tests.

**Comment by jsoref** [comment] 2021-06-11 22:08
@ohemorange: I just expected it to do the right thing. It sounds like it will soon.

Yes, I took one of my certificates and extended it to include the other domain. But I figured I should file a report.

**Comment by alexzorin** [comment] 2021-06-12 00:27
@osirisinferi would you be able to share your design plan and what the output would look like, for that change?

I think it would be ideal to keep it as a single interactive prompt, rather than prompting twice to warn them about the remaining domains in that virtualhost.

One idea we had was to group up the domains by virtualhost.

Very roughly, ff running just `certbot --apache` it might look like:

    Which names would you like to activate HTTPS for?
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    In VirtualHost /etc/apache2/sites-enabled/000-default.conf:1
      1: example.com
      2: www.example.com
    In VirtualHost /etc/apache2/sites-enabled/three.conf:1
      3: three.com
    In VirtualHost /etc/apache2/sites-enabled/000-default.conf:1
      4: x1.com
      5: app.x1.com
      6: www.x1.com
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    We recommend selecting either all domains, or all domains in a VirtualHost.

    Select the appropriate numbers separated by commas and/or spaces, or leave input
    blank to select all options shown (Enter 'c' to cancel):

In the case of running `certbot --apache -d example.com` interactively, we could instead have the prompt suggesting securing the other domains in virtualhosts to which this domain belongs (i.e. `www.example.com` in `000-default.conf:1`).

This is just thinking out loud and and I'm not saying it should be this way, but it would be useful to get all our ideas out and thoughts lined up.

**Comment by osirisinferi** [comment] 2021-06-12 06:58
@alexzorin I agree a second prompt isn't very "clean", but that was what I was going with earlier. See my [WIP](https://github.com/certbot/certbot/compare/master...osirisinferi:wip1-hostname-suggestions-from-vhosts?expand=1).

I like your idea better, but probably would require more difficult modifications to already existing functions. My WIP above could possibly be used quite easilly for your second suggestion when the user uses `-d`.

**Comment by alexzorin** [comment] 2021-06-12 07:07
Yep, it might turn out the more ambitious approach isn't achievable due to having to break the installer interface. Thanks for posting your code. We'll update this hopefully soon.

**Comment by alexzorin** [comment] 2021-06-17 21:28
It should be much easier to make the required display changes once https://github.com/certbot/certbot/pull/8835 is merged.

**Comment by ohemorange** [comment] 2022-07-20 23:51
@alexzorin I see you started working on this in a branch but the issue is unassigned, were you hoping for (or open to) someone to take over the branch or did you want to finish it yourself?

**Comment by alexzorin** [comment] 2022-07-21 00:27
Totally open to that, it's unlikely that I'll be working on this again any time soon.

**Comment by wgreenberg** [comment] 2022-08-18 21:24
I'll grab this

**Comment by jsoref** [comment] 2022-08-18 21:37
Fwiw, the _simplest_ fix for this would be to just say:

> If you have more than one domain assigned to a virtualhost you should select all of them.

... or something to that effect in the dialog.

Conceptually, that's:
```diff
 Which names would you like to activate HTTPS for?
+If you have more than one domain assigned to a virtualhost you should select all of them.
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 1: example.com
 2: example.net
 3: www.example.net
 4: example.org
...
```

**Closed** 2022-09-07 02:55 UTC
Labels: area: ui / ux, area: nginx, area: apache, priority: significant
