### ISSUE TITLE
Keys stored with permissions allowing unprivileged access

### ISSUE THREAD

**Issue by 3n-mb** [certbot/certbot#7412] opened 2019-09-28 19:18 UTC
When I look into /etc/letsencrypt/archive (ls -l), all pem files, including privkeyX.pem have mode "-rw-r--r--".

Live folder sym-links to archive folder, which means that current keys are also readable by non-privileged users.

I'd expect all files to be "-rw-------". I'd expect certbot to enforce strict permissions, like ssh does.

Are such loose permissions required for operation? What chmod command should be used on  /etc/letsencrypt/archive to tighten this up?

##  My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt

**Comment by alexzorin** [comment] 2019-09-29 00:11
`/etc/letsencrypt/archive` is `0700`, so unprivileged users cannot get at key material in there.

But it might be worth reading over #1473 for a summary of different issues surrounding file permissions.

**Comment by 3n-mb** [comment] 2019-09-29 14:12
Wow! #1473 Has been open almost FOUR years ago, and is still relevant. Wow! Just wow!

@alexzorin when you say "key material in there", which particular version / package / setting are you talking about?
- Can you check your cli.ini. May be it is set better as one of #1473 suggestions was talking?
- On Ubuntu --help doesn't give me an arg to check certbot's version. What version are you talking about? How do I get cerbot's actual code version?
- If this is an Ubuntu package issue, what package maintainer should do? Where is a channel to tell 'em.
- Again. What work around can be used here? Some chmod with stick bit? HELP!!!
- And when correcting command is found, can we talk about it to wider audience? They have keys exposed. We know this now!

I have seven installations, and **ALL** have world readable keys. It can't be my hallucination. Now I can say that most of Wordpress installations with LetsEncrypt have this. What is the chance that CentOS has this better?

**Comment by 3n-mb** [comment] 2019-09-29 14:17
November 2018, quote from https://github.com/certbot/certbot/issues/1473#issuecomment-443347999 

> Currently, private keys are always made world readable.

Still in November 2018! Three years after opening #1473 !

**Comment by adferrand** [comment] 2019-09-29 18:03
Ok let's keep things rational, and analyze what is the current situation.

First, #1473 is closed for a reason, and what is was about is not a major security breach. We did not keep an issue about a major security breach for more than 3 years, if it is you are currently thinking.

As explained by @alexzorin, and this what #1473 is about, and prior to Certbot 0.29.0:
* Certbot was creating a directory `/etc/letsencrypt/archive` with permissions `0700`
* each private key put in a subdirectory of `/etc/letsencrypt/archive` was assigned `0644` permissions
* effectively private keys were **not** accessible by anyone except the user (usually `root`) because of the permissions on `/etc/letsencrypt/archive`
* however, if someone changed the permissions of `/etc/letsencrypt/archive`, the accessibility of private keys could change silently because of the relaxed permissions, and Certbot did not make any control on `/etc/letsencrypt/archive` permissions after its creation
* and indeed permissions on private keys were quite exotic, since one can expect `0700` for this kind of stuff, as it is usually seen in SSH installations

So the standard situation was a secured set of paths to protect the keys, but an unusual pattern that could lead to security breach if someone plays with the `/etc/letsencrypt`. And this can happen for various comprehensible reasons.

This situation has been improved with Certbot 0.29.0, and is a balance between the need to to a less error-prone pattern **and** retrocompatibility for people that were relying on the previous behavior modified by 0.29.0:
* folder `/etc/letsencrypt/archive` is still created with `0700` permissions
* private keys for new certificates are created with `0600` permissions
* private keys for renewed certificates keep group owner and permissions group, user part is always set to `6`, everybody part is always set to `0` (eg. altered key permissions `755` becomes, after renewal, `650`).

This is what explains #1473, PR #6480 closed the issue, and relevant changelog is here: https://github.com/certbot/certbot/blob/master/CHANGELOG.md#changed-11. Me and others made further proposal to improve even more this new pattern, but these proposals would require breaking changes, and so are postponed to a future version of Certbot.

Last words on your specific situation to close the issue. You are observing world readable permissions because you are on a version of Certbot older than `0.29.0`. Indeed Certbot version in official repositories for Bionic is `0.23.0`. I advise you to follow instructions on https://certbot.eff.org for Bionic, that will help you to enable the PPA for certbot, in order to install a much more up to date version (`0.31.0` at this time). Then Certbot will set up correctly private key permissions during the next certificate renewals.

**Closed by adferrand** 2019-09-29 18:03 UTC

**Comment by 3n-mb** [comment] 2019-09-29 21:54
@adferrand you are right. *Effective* permissions are such that keys can't be read.
In retrospect, its funny how many people had the same misunderstanding.

**Comment by expressrussian** [comment] 2019-12-09 15:37
Many people.
For example, COTURN does not work anymore, as it starts as turnserver/turnserver.
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot find certificate file: /etc/letsencrypt/live/domain.eu/fullchain.pem (1)
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot find private key file: /etc/letsencrypt/live/domain.eu/privkey.pem (1)
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly

This boils down to the impossibility to use ALL unprivileged applications anymore. And it looks like Letsencrypt does not care about how many such applications got broken. And Letsencrypt does not provide other workaround except users start to disable this whole "security concept" simply because it does not work for unprivileged. 
Could you provide a solution for all unprivileged applications (which do not start as root and cannot elevate privileges), please?
Or Certbot works now with Apache-like web servers ONLY?

**Comment by 3n-mb** [comment] 2019-12-09 15:58
@expressrussian 
First, hold your horses.
Secondly, read the manual about certbot. There are hooks for you to use to adapt to any specific situation.
Thirdly, are you sure that you want to allow any user to access private keys. May its better to separate TLS proxy in LXC or Docker, if your app can't reload, reading root's file, and running like non root (examples, russia-made nginx :) , haproxy).

**Comment by expressrussian** [comment] 2019-12-09 16:55
Thanks, good to hear from a human.
I am looking at 
https://certbot.eff.org/docs/
and do not find the relevant information for the users who are not experts.
I have a standalone apache-based website on Ubuntu server 1910. The renewal for my wildcard domain is manual, but it works fine with apache. There is no problem with http/https on apache, and i can stop/start the web server if necessary.
There is no problem running the certificate renewal itself. As i see, the hooks are for the renewal process. This is not the case here.
The problem is with coTURN server, which cannot get to the certificates.
COTURN server should open the custom port 5349, but it says it cannot because the access to certificates is denied. 
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot find certificate file: /etc/letsencrypt/live/domain.eu/fullchain.pem (1)
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot find private key file: /etc/letsencrypt/live/domain.eu/privkey.pem (1)
Dec 09 12:21:31 ubuntu turnserver[7602]: 0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
---
And yes, turnserver user has no right to look into /etc/letsencrypt/live every time it starts.
From my non-expert point of view, i dont know how to fix this. I can only think of breaking the whole security concept in order to make things work "great again" :) . I need to make the certificate/key file visible for turnserver every time the server reboots, and not when i renew the certificates 4 times a year.
--------------- 
I would like not to complicate things and reduce the attack footprint, so i dont run Docker on this server. Also, i do not know how to run LXC, so i dont use it. I would like to continue the scheme where apache and coturn use the same certificate. I took the most classic configuration with apache, and never used nginx, so i did not even know why it is called "russia-made" until you mentioned it. I am not that expert to know all that.
If you know how to approach this problem properly, i would be thankful.

**Comment by 3n-mb** [comment] 2019-12-09 17:34
@expressrussian 
Noone is an expert in everything. Noone.
That's why we take time and a little effort to find and digest information. For example, 
- on a page you gave a link for, do Ctrl-F in a browser, and look for word hook.
- type certbot hooks into search engine, and something will show up, like this: https://blog.wizardsoftheweb.pro/certbot-hook-api/

My impression is that you've spent more key-strokes on shouting instead of actually looking for information. Screaming in all bold fonts will get you nowhere. Just chill it.
It's not a high school, where all answers are written in the back of a textbook. You'll have to take time to calmly absorb someone else's docs, code, etc., and figure out the better solution for *your* situation.

About splitting TLS into a separate process. Unfortunately UNIX is not built on POLA (Principle of Least Authority) from a ground up. Ideally OS should run every process in environment like WASI.
We leave in a non-ideal world, and solutions like separate TLS seem more complex -- you add a layer.
Hey, I just make a humble suggestion. Find a cyber security meetup or group of red/blue hacker teams, and ask their opinion. :full_moon_with_face:

**Comment by expressrussian** [comment] 2019-12-09 17:57
Yes, i know the find command. I saw that "hook" section, it is about the process of renewing certificates.
My problem is completely different. It is not related to renewing my certificates manually for Apache while it kinda works OK. My apache web server is happy.
But the other application, coturn is not. The problem is everyday access those existing certificate files from other non-root services who cannot elevate privileges. Recent certbot developments have removed that access. Do we have now a replacement for that kind of file access for non-root users?

And i did not "screamed in bold". I did not even touch that bold button, this github site makes some parts of text bold itself. And i dont know how to unbold it.
WASI - never heard of it. Wikipedia is of no real help here:
https://en.wikipedia.org/wiki/Wasi

So, i will look how to access those certificate files from that turnserver user/group.

**Comment by expressrussian** [comment] 2019-12-09 18:50
turnserver@ubuntu:/etc/letsencrypt$ cd live
bash: cd: live: Permission denied

Looking from Windows experience, i wanted to overcome UNIX coarse permissions. And compiled a workaround which seems to work in my case:
`
apt install acl
setfacl -m g:turnserver:r-x /etc/letsencrypt/live
setfacl -m g:turnserver:r-x /etc/letsencrypt/archive/
`
After that i have:
turnserver@ubuntu:/etc/letsencrypt$ cd live
turnserver@ubuntu:/etc/letsencrypt/live$ 
and i can read the files.
Is this workaround compatible with new certbot security model?

**Comment by 3n-mb** [comment] 2019-12-09 20:40
@expressrussian 
> Is this workaround compatible with new certbot security model?

There is some misunderstanding. Certbot is responsible for automatically and securely making fresh certificates.
With certbot hooks you can do anything, copy your keys and certs, give your private keys world-readable permissions, publish your private keys to facebook, ... you can do anything with certbot hooks.
What you do with your key material is now *your* security model and is *your* resposibility.
