### ISSUE TITLE
Renewal config files should contain paths relative to config_dir

### ISSUE THREAD

**Issue by nagisa** [certbot/certbot#2155] opened 2016-01-12 21:05 UTC
Since https://github.com/letsencrypt/letsencrypt/issues/1081 is still a thing, I copied my configuration (from ~2 months ago) from the server to local machine and am trying to renew the certificate.

Running 

```
sudo letsencrypt --work-dir ~/Desktop/letsencrypt/ certonly --standalone --config-dir ~/Desktop/letsencrypt/
```

will allow one to enter domains at which point it outputs 

```
An unexpected error occurred:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Please see the logfiles in /var/log/letsencrypt for more details.
```

and quits. Logs are empty.

**Comment by kuba** [comment] 2016-01-12 21:09
"copied my configuration" is the key - you have simply not copied enough data - you must copy all `/etc/letsencrypt`

That's a clear dupe of #1195.

**Comment by nagisa** [comment] 2016-01-12 21:11
@kuba I did `scp -r server:'/etc/letsencrypt' ~/Desktop/`, so it can’t possibly have missed anything.

**Comment by kuba** [comment] 2016-01-12 21:11
`--conf-dir`, not `--work-dir`

**Comment by kuba** [comment] 2016-01-12 21:13
please `tree ~/Desktop/letsencrypt`; NB it's not really offically supported to have `--config-dir` and `--work-dir` point at the same dir

**Comment by nagisa** [comment] 2016-01-12 21:13
@kuba the `--help paths` is wrong then, since it prints:
```
$ letsencrypt --help paths
usage: 
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
  plugins              Display information about installed plugins

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        config file path (default: None)

paths:
  Arguments changing execution paths & servers

  --cert-path CERT_PATH
                        Path to where cert is saved (with auth --csr),
                        installed from or revoked. (default: None)
  --key-path KEY_PATH   Path to private key for cert installation or
                        revocation (if account key is missing) (default: None)
  --fullchain-path FULLCHAIN_PATH
                        Accompanying path to a full certificate chain (cert
                        plus chain). (default: None)
  --chain-path CHAIN_PATH
                        Accompanying path to a certificate chain. (default:
                        None)
  --config-dir CONFIG_DIR
                        Configuration directory. (default: /etc/letsencrypt)
  --work-dir WORK_DIR   Working directory. (default: /var/lib/letsencrypt)
  --logs-dir LOGS_DIR   Logs directory. (default: /var/log/letsencrypt)
  --server SERVER       ACME Directory Resource URI. (default:
                        https://acme-v01.api.letsencrypt.org/directory)
```

Note, also, that I specified both `--config-dir` and `--work-dir`.

**Comment by kuba** [comment] 2016-01-12 21:14
What should I be looking at in the `--help` that you pasted? It's clear from the output: " Configuration directory. (default: /etc/letsencrypt)". `--work-dir` is `/var/lib/letsencrypt`

**Comment by kuba** [comment] 2016-01-12 21:20
Another thing: `renewal/$domain.conf` will contain absolute paths to `/etc/letsencrypt/live/$domain`, not `~/Desktop/letsencrypt`

**Comment by nagisa** [comment] 2016-01-12 21:36
@kuba that was in response to 

> --conf-dir, not --work-dir

I tried using different directories for both work-dir and config-dir to no avail.

> Another thing: renewal/$domain.conf will contain absolute paths to /etc/letsencrypt/live/$domain, not ~/Desktop/letsencrypt

Shouldn’t command line options override these? I tried specifying all pathes (--cert-path, --key-path, --fullchain-path, --chain-path) to no avail.

Changing the pathes in the renewal/$domain.conf resulted in a different error:

OSError: [Errno 22] Invalid argument: '/home/nagisa/Desktop/letsencrypt/letsencrypt/live/$domain/cert.pem'

Directory structure and files (their md5sums) match exactly. Turns out I had to also perserve soft link structure o.O.

**Comment by nagisa** [comment] 2016-01-12 21:52
So to summarize:

* [ ] None of `--cert-path`, `--key-path`, `--fullchain-path`, `--chain-path` seem to work;
* [ ] `letsencrypt` utility fails if files inside `live/$domain/` are not symbolic links;
* [ ] Pathes in renewal configuration are absolute pathes and cannot stomach being moved around;
* [ ] Pointing arbitrary path options to arbitrary locations are not supported, especially if pathes happen to match for some reason.

**Comment by ohemorange** [comment] 2018-10-30 22:48
Looks like this was resolved!

**Closed by ohemorange** 2018-10-30 22:48 UTC
Labels: area: cert management, feature request
