### ISSUE TITLE
certbot hangs when executing renewal script

### ISSUE THREAD

**Issue by torbennehmer** [certbot/certbot#5424] opened 2018-01-13 14:13 UTC
## My operating system is (include version):
Latest Debian Stable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Debian Package:

```
root@nathan:~# certbot --version
certbot 0.10.2

root@nathan:~# dpkg -l *certbot*
...
||/ Name                        Version            Architektur        Beschreibung
+++-===========================-==================-==================-===========================================================
ii  certbot                     0.10.2-1~bpo8+1    all                automatically configure HTTPS using Let's Encrypt
ii  python-certbot              0.10.2-1~bpo8+1    all                main library for certbot
ii  python-certbot-apache       0.10.2-1~bpo8+1    all                Apache plugin for Certbot
```

## I ran this command and it produced this output:
```
root@nathan:/etc/letsencrypt# certbot renew --force-renewal --cert-name nathan.nehmer.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/nathan.nehmer.net.conf
-------------------------------------------------------------------------------
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for nathan.nehmer.net
http-01 challenge for isp.nehmer.net
Waiting for verification...
Cleaning up challenges
Unable to clean up challenge directory /etc/apache2/acme-challenge-ispconfig/.well-known/acme-challenge
Generating key (4096 bits): /etc/letsencrypt/keys/0389_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0389_csr-certbot.pem
Running renew-hook command: /usr/local/sbin/renew-nathan-ssl.sh
```

The deployed hook script completes successfully but remains as Zombie. Certbot does not collect it. 

Process tree:

```
 3514 ?        Ss     0:10 /usr/sbin/sshd
11200 ?        Ss     0:00  \_ sshd: root@pts/0 
11202 pts/0    Ss     0:01  |   \_ -bash
26264 pts/0    S+     0:05  |       \_ /usr/bin/python /usr/bin/certbot renew --force-renewal --cert-name nathan.nehmer.net
26981 pts/0    Z+     0:00  |           \_ [renew-nathan-ss] <defunct>
```

Script executed:

```
#!/bin/sh

/usr/sbin/service dovecot restart
/usr/sbin/service apache2 restart
/usr/sbin/service postfix restart

exit 0
```
The log does not help, it ends with:

```
2018-01-13 12:39:08,666:INFO:certbot.hooks:Running renew-hook command: /usr/local/sbin/renew-nathan-ssl.sh
```

This is the config file of the domain in question.

```
# renew_before_expiry = 30 days
version = 0.10.2
archive_dir = /etc/letsencrypt/archive/nathan.nehmer.net
cert = /etc/letsencrypt/live/nathan.nehmer.net/cert.pem
privkey = /etc/letsencrypt/live/nathan.nehmer.net/privkey.pem
chain = /etc/letsencrypt/live/nathan.nehmer.net/chain.pem
fullchain = /etc/letsencrypt/live/nathan.nehmer.net/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = ...
renew_hook = /usr/local/sbin/renew-nathan-ssl.sh
authenticator = webroot
rsa_key_size = 4096
installer = None
[[webroot_map]]
isp.nehmer.net = /etc/apache2/acme-challenge-ispconfig
nathan.nehmer.net = /etc/apache2/acme-challenge-ispconfig
```

Any ideas regarding this scenario would be gratly appreciated.

Best regards
Torben Nehmer

**Comment by SwartzCr** [comment] 2018-01-17 21:01
Maybe you can add something to the script to do some logging and get a sense of where it's hanging? or maybe use strace to debug it? https://linux.die.net/man/1/strace

**Comment by torbennehmer** [comment] 2018-01-20 13:43
I did a trace using
`strace -ff -tt -v`

When everything hung, I sent a CTRL+C, which was at about 14:26:06 in the log files, the lines executed before by certbot were (PID 20038):

```
14:25:21.587674 read(5, ".\n", 4096)    = 2
14:25:21.587859 poll([{fd=8, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN|POLLPRI}], 2, 4294967295) = 1 ([{fd=5, revents=POLLIN}])
14:25:21.918362 read(5, "Stopping Postfix Mail Transport "..., 4096) = 46
14:25:21.918588 poll([{fd=8, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN|POLLPRI}], 2, 4294967295) = 1 ([{fd=5, revents=POLLIN}])
14:25:23.117275 read(5, ".\n", 4096)    = 2
14:25:23.117521 poll([{fd=8, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN|POLLPRI}], 2, 4294967295) = 1 ([{fd=5, revents=POLLIN}])
14:25:23.226798 read(5, "Starting Postfix Mail Transport "..., 4096) = 46
14:25:23.226947 poll([{fd=8, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN|POLLPRI}], 2, 4294967295) = 1 ([{fd=5, revents=POLLIN}])
14:25:28.815189 read(5, ".\n", 4096)    = 2
14:25:28.815661 poll([{fd=8, events=POLLIN|POLLPRI}, {fd=5, events=POLLIN|POLLPRI}], 2, 4294967295) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
14:25:28.825974 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=20049, si_uid=0, si_status=0, si_utime=1, si_stime=4} ---
14:25:28.826063 restart_syscall(<... resuming interrupted call ...>) = 1
14:25:28.924272 close(5)                = 0
14:25:28.924484 poll([{fd=8, events=POLLIN|POLLPRI}], 1, 4294967295) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
14:26:06.240115 --- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
```

Process PID 20049 was the shell executing everything which exitted quite fine:

```
14:25:21.597059 wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 20985
14:25:28.822861 rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f3e64008180}, {0x443740, [], SA_RESTORER, 0x7f3e64008180}, 8) = 0
14:25:28.823018 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
14:25:28.823189 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=20985, si_uid=0, si_status=0, si_utime=1, si_stime=2} ---
14:25:28.823262 wait4(-1, 0x7ffc5ddcda90, WNOHANG, NULL) = -1 ECHILD (No child processes)
14:25:28.823439 rt_sigreturn()          = 0
14:25:28.823692 read(255, "\nexit 0\n", 122) = 8
14:25:28.823988 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
14:25:28.824160 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
14:25:28.824522 exit_group(0)           = ?
14:25:28.825867 +++ exited with 0 +++
```

I've attached the traces of certbot itself and all childs ist spawned directly. There are of course more childs resulting out of the service restarts, but I guess that they are of no further importance at this point. If I'm wrong, please let me know, I can of course give you additional trace files if neccessary.

Best regards
Torben Nehmer

[certbot-trace.tar.gz](https://github.com/certbot/certbot/files/1648843/certbot-trace.tar.gz)

**Comment by SwartzCr** [comment] 2018-01-22 21:32
@bmw would you be able to look into this? It seems that certbot is having trouble resuming after completing a renewal hook script

**Comment by bmw** [comment] 2018-01-24 21:29
I've actually been able to narrow this down to what I think is a bug in Python or the Dovecot init.d script. I created `test.py` with:
```
#!/usr/bin/env python
from subprocess import Popen, PIPE

cmd = Popen(["./script.sh"], stdout=PIPE,
            stderr=PIPE)
out, err = cmd.communicate()
print out
print err
```
and `script.sh` in the same directory with the contents:
```
#!/bin/sh

rm /root/output
/usr/sbin/service dovecot restart
echo "exiting" > /root/output
```
If you run `test.py` (as root), it hangs indefinitely with "exiting" written to `/root/output`.

This should be dug into more and a bug appropriately filed upstream.

**Comment by torbennehmer** [comment] 2018-02-18 14:01
I have worked around this issue now by using a flag file and watching that one via cron to restart the services on demand. Works fine for me so far. Having a fix would be fine of course, but its not a top priority for me for now as long as this works.

Thanks for that first analysis!

**Comment by nthallen** [comment] 2018-03-10 16:56
I am seeing the same thing and can confirm that @bmw 's script hangs, specifically on the startup portion of /etc/init.d/dovecot. This seems like a Python bug associated with starting a daemon. Perhaps cmd.communicate() is waiting for dovecot to terminate, even though it has done the standard tricks to disconnect from its parent process.

**Comment by NicoHaase** [comment] 2018-03-11 09:33
Any news on this? I have the same problem (as asked for in https://stackoverflow.com/questions/48976571/certbot-renewal-hook-wont-finish) and would love to find a solution. Is there any way to help out?

**Comment by nthallen** [comment] 2018-03-11 14:06
@NicoHaase I think trying to pare down the example to the smallest reproducible case would point us toward a solution. Specifically, perhaps we could create a generic daemon, and see if starting it causes the same hang. Then we might try to find out whether C's waitpid() has the same problem, or if it's actually in Python's wrapper.. I have also not investigated what possible connection remains between dovecot and test.py. Perhaps there is still an inherited file handle open that test.py is listening to? (there shouldn't be!)

**Comment by NicoHaase** [comment] 2018-03-11 14:19
Well, I think that my hook uses nearly the same code as @bmw uses. It should also restart dovecot, so I don't think I can narrow it down further

**Comment by nthallen** [comment] 2018-03-11 16:10
I think I've got it. lsof showed that dovecot is holding stderr open. I changed my startup script.sh to:
```sh
#!/bin/sh

rm /root/output
/usr/sbin/service dovecot restart 2>/dev/null
echo "exiting" > /root/output
```
This change could be applied either to the deploy-hook script or directly to the /etc/init.d/dovecot script where dovecot is launched. [If I recall correctly, that script dd not come with dovecot. I believe I found it somewhere else.]

**Comment by nthallen** [comment] 2018-03-11 16:19
I am also restarting httpd from my script, so I checked lsof for it, and I see:

```
httpd   13082 root    0r   CHR        1,3      0t0      33430 /dev/null
httpd   13082 root    1w   CHR        1,3      0t0      33430 /dev/null
httpd   13082 root    2w   REG       0,24    11776   35264057 /var/log/httpd/error_log
httpd   13082 root    3w   REG       0,24        0   24903924  (deleted)/etc/letsencrypt/.certbot.lock
httpd   13082 root    4w   REG       0,24        0   34735149  (deleted)/var/log/letsencrypt/.certbot.lock
httpd   13082 root    5w   REG       0,24    58885   34735157 /var/log/letsencrypt/letsencrypt.log.16
httpd   13082 root    6w   REG       0,24        0   42339280  (deleted)/var/lib/letsencrypt/.certbot.lock
```
I wonder whether all those 'letsencrypt' filehandles are intentional, and whether they might cause the script to hang as well.

**Comment by nthallen** [comment] 2018-03-11 16:24
'/sbin/service httpd restart` does not cause the same problem, presumably because httpd closes stdin and stdout and reopens stderr to its own log file. dovecot apparently closes stdin and stdout, but leaves stderr open.

**Comment by jdavidbakr** [comment] 2018-04-17 18:03
Experiencing the same issue, adding the dovecot restart output to /dev/null per @nthallen fixed my issue as well.  Thank you!

**Comment by bmw** [comment] 2019-05-02 23:08
I can't seem to reproduce this problem on Debian Stretch anymore so I'm closing this issue.

**Closed by bmw** 2019-05-02 23:08 UTC
Labels: area: renewal, debugging, help wanted

**Comment by klues** [comment] 2020-09-02 08:34
I had the same issue, certbot was hanging on executing my post renewal script. It basically just starts another script and finally I got it running with:
```
#!/bin/bash
/<path-to-my-scrit>/<my-script>.sh &>/dev/null &
disown
```
