### ISSUE TITLE
Explain authentication requirements

### ISSUE THREAD

**Issue by OlafvdSpek** [certbot/certbot#4986] opened 2017-08-03 14:55 UTC
Debian 9

ii  certbot                                0.10.2-1                       all          automatically configure HTTPS using Let's Encrypt
ii  python-certbot                         0.10.2-1                       all          main library for certbot

## I ran this command and it produced this output:
```
# certbot certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Place files in webroot directory (webroot)
2: Spin up a temporary webserver (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 
```

## Certbot's behavior differed from what I expected because:

It's unclear what both of the choices do and require. Standalone sounds good, but I think it requires port 80 and/or 443 to be free, which they probably aren't as those are common ports for existing web servers. ;)
Webroot sounds OK, but does this root need to be accessible via port 80 or via port 443?

What if port 80 redirects all requests to https?
What if port 80 isn't used at all?

I think:
1. This scenario should be supported better.
2. Things should be explained better.

**Comment by SwartzCr** [comment] 2017-08-03 21:40
Are you talking about if you have something like iptables redirecting all ported traffic or if your webserver configuration specifies that port 80 traffic should go to 443?
In essence webroot will use your existing server setup to serve challenge files at `YOURURL.TLD/.well-known/CHALLENGEHASH` which will be read by let's encrypt.
In this case if your server is redirecting traffic, that file will still be able to be read and you will receive a certificate.
In the other case (where you don't have a webserver running or don't have one running on 443) then standalone will spin up a webserver and serve a challenge over 443.
If you already have nginx or apache installed, then certbot can install your certificate via the apache or nginx plugin.
I'd like it if you could look at the documentation on certbot.eff.org/docs and tell me what you think could be added to make this more clear

**Comment by OlafvdSpek** [comment] 2017-08-04 11:23
> Are you talking about if you have something like iptables redirecting all ported traffic or if your webserver configuration specifies that port 80 traffic should go to 443?

HTTP redirects

> In this case if your server is redirecting traffic, that file will still be able to be read and you will receive a certificate.

I'll try again. 

> If you already have nginx or apache installed, then certbot can install your certificate via the apache or nginx plugin.

Nginx doesn't appear to be recognized:
```
# certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

> I'd like it if you could look at the documentation on certbot.eff.org/docs and tell me what you think could be added to make this more clear

The docs are good, maybe it'd help to include a link to them in the certbot certonly output.

Standalone is problematic for automatic renewal isn't it?
Webroot seems superior, but this isn't clear from the certonly output or from the docs.

BTW, I love the letsencrypt initiative and the certbot tool.

**Comment by SwartzCr** [comment] 2017-08-04 19:41
Can you try installing python-certbot-nginx and seeing if that changes anything? If not I can look through old issues and see what we've done in previous similar situations

**Comment by OlafvdSpek** [comment] 2017-08-07 07:33
```
Setting up python-pyparsing (2.1.10+dfsg1-1) ...
Setting up python-certbot-nginx (0.10.2-1) ...
root@ln0:/home/join# certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```

**Comment by SwartzCr** [comment] 2017-08-07 15:46
Can you try running `certbot --nginx`?
Can you also share with me the output of:
`which nginx`
`dpkg -l nginx`
If your nginx package is installed in a strange place that might be what is causing certbot to not be able to recognize that you have it installed.

**Comment by OlafvdSpek** [comment] 2017-08-08 06:29
```
# certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: api2.join.cc
2: ln0.join.cc
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):
```
```
# which nginx
/usr/sbin/nginx
```

```
# dpkg -l nginx
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                                      Version                                   Architecture                              Description
+++-=========================================================================-=========================================-=========================================-=======================================================================================================================================================
ii  nginx             
```

**Comment by SwartzCr** [comment] 2017-08-08 21:23
So the issue is that certbot won't default to nginx even if you have it installed in version 0.10.2
The PR to unhide nginx was just merged and will be available in 0.18.0: https://github.com/certbot/certbot/pull/4969
So it seems like certbot will work on your system, but for now you will have to specify to it that you want to use nginx by providing the `--nginx` flag. When nginx becomes unhidden, that command will still be valid, so don't worry about putting it into your renewal commands.
As far as changes to the docs, I think it'd make sense if they were each given their own issues. So I'm going to close this issue for now, since it seems like you have a command that will cause certbot to give you a sane output, and we can discuss ui/ux improvements elsewhere where they can be tracked individually.

**Closed by SwartzCr** 2017-08-08 21:23 UTC
Labels: area: documentation, more-info

**Comment by OlafvdSpek** [comment] 2017-08-09 07:44
Have you created the tickets for the docs or should I?

There's also the issue of how to use certbot without the nginx plugin if you only run on port 443.

**Comment by OlafvdSpek** [comment] 2017-08-11 09:29
@SwartzCr ?

**Comment by SwartzCr** [comment] 2017-08-14 22:03
Oh sorry, it doesn't seem like I made issues for them, would you be willing to? Please tag me in them when you do!
