### ISSUE TITLE
cannot apache plugin RPM for RHEL 6/7

### ISSUE THREAD

**Issue by shang-lin** [certbot/certbot#3719] opened 2016-10-31 19:02 UTC
I'm trying to install certbot on a RHEL7 server. I already have epel-release on my server, but when I try to install python-certbot-apache, the package is not found. 

```
$ sudo yum install epel-release
Loaded plugins: product-id, rhnplugin, search-disabled-repos, security,
              : subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
Package epel-release-6-8.noarch already installed and latest version
Nothing to do

$ sudo yum install python-certbot-apache
Loaded plugins: product-id, rhnplugin, search-disabled-repos, security,
              : subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Install Process
No package python-certbot-apache available.
Error: Nothing to do

```

The epel package listing at https://dl.fedoraproject.org/pub/epel/7/x86_64/p/ does not show the python-certbot-apache package.

RHEL 6 has the same issue.

**Comment by shang-lin** [comment] 2016-11-02 00:04
I got around this issue by running cerbot-auto from the git repo, but the official instructions recommend downloading the RPM.

**Comment by pde** [comment] 2016-11-02 19:15
@hogarthj @NoodlesNZ thoughts?

**Comment by hex-m** [comment] 2016-11-04 14:24
I can't reproduce this on my machine. `yum search certbot` on my centos7 with epel-release gives me:
> python2-certbot.noarch : Python 2 libraries used by certbot
> python2-certbot-apache.noarch : The apache plugin for certbot
> certbot.noarch : A free, automated certificate authority client

Can you install python-certbot itself? Can you install the Apache plugin when using the name python2-certbot-apache?

**Comment by shang-lin** [comment] 2016-11-04 20:49
I didn't do a yum search on the RHEL 7 machine, or I would have realized that python2-certbot-apache exists, but not python-certbot-apache. However, RHEL 6 doesn't have either.

```
$ sudo yum search certbot
Loaded plugins: product-id, rhnplugin, search-disabled-repos, security,
              : subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Warning: No matches found for: certbot
No Matches found

```

**Comment by NoodlesNZ** [comment] 2016-11-04 22:06
EL 6 doesn't have certbot/letsencrypt at all, there were a lot of dependencies needed to get it out the door and unfortunately some of them we couldn't upgrade. It has been a few months since I looked at the requirements for certbot, so I might have another try at building something for EL 6.

**Comment by LRninja** [comment] 2018-03-09 09:35
@shang-lin et al, I was having similar problem on CentOS7 and realized, after reviewing my EPEL repo file several times, that there was an extra line in my '/etc/yum.repos.d/epel.repo' file. 

    includepkgs=fail2ban*

I happen to be running fail2ban on my server, but you may need to comment out (temporarily?) any 'includepkgs' tags/lists in the repo file as they limit the results you get from yum searches. 

For more info see:

    $  man yum.conf 
    /includepkgs

cheers,

**Comment by bmw** [comment] 2019-04-18 18:38
This appeared to be a problem with the yum configuration rather than one with Certbot so I'm closing this issue.

**Closed by bmw** 2019-04-18 18:38 UTC
Labels: area: fedora / redhat / CentOS, area: pkging
